<article>
	<h1><span>Question: Response</span></h1>

	<ul class="nav">
		<li><a href="#overview">Overview</a></li>
		<li><a href="#toolbar">Toolbar</a></li>
		<li><a href="#details">Details</a></li>
		<li><a href="#parameters">Parameters</a></li>
	</ul>

	<section id="overview">
		<h2><span>Overview</span></h2>

		<p>A question submitted by a site member.</p>
	</section>
	<section id="toolbar">
		<h2><span>Toolbar</span></h2>
		<p>At the top right you will see the toolbar.</p>
		<p>The functions are:</p>
		<dl>
			<dt>Save</dt>
			<dd>Save changes and return to the edit form.</dd>

			<dt>Save &amp; Close</dt>
			<dd>Save changes and return to the listing of entries.</dd>

			<dt>Cancel</dt>
			<dd>Discard any changes made and return to the listing of entries.</dd>

			<dt>Help</dt>
			<dd>Opens this help screen.</dd>
		</dl>
	</section>
	<section id="details">
		<h2><span>Details</span></h2>

		<p>Every entry consists of a <strong>subject</strong>, optional <strong>question</strong>, and <strong>tags</strong>.</p>

		<dl>
			<dt>Anonymous</dt>
			<dd>This is a flag to indicate if the user posted the question anonymously. Entries marked as anonymous will not display the poster's name or link to their profile.</dd>

			<dt>Question</dt>
			<dd>The question the response is to. This is not an editable field.</dd>

			<dt>Answer</dt>
			<dd>A required field. The content of the post, responding to the question asked.</dd>
		</dl>
	</section>
	<section id="parameters">
		<h2><span>Parameters</span></h2>

		<p>The following options control various aspects of the published state (when and if an entry is available to users).</p>

		<dl>
			<dt>Accept</dt>
			<dd>The accepted status of the response. If checked, the response will be marked as the officially chosen answer to the question.</dd>

			<dt>Created Datep</dt>
			<dd>A timestamp (YYYY-MM-DD hh:mm:ss) for when the entry was created.</dd>

			<dt>Change Creator</dt>
			<dd>This is a user ID for the user designated as the entry creator.</dd>
		</dl>
	</section>
</article>