<?php

require_once 'lib/data/om/BaseAcknowledgement.php';


/**
 * Subclass for representing a row from the 'Acknowledgement' table.
 *
 * A low-representational-gap implementation of an Acknowldgement, which is basically
 * a few chunks of text that can be associated with a Project, Experiment, or Trial..
 *
 * This class was autogenerated by Propel on: Sat Feb  9 00:02:44 2008
 *
 * @abstract Provides kudos to people who helped them in the project, experiment or trial.
 *
 * @package    lib.data
 *
 * @uses Trial
 * @uses Experiment
 * @uses Project
 *
 * @todo Rename ackid to id in database
 */

class Acknowledgement extends BaseAcknowledgement {

  function __construct( Project $project = null,
                        Experiment $experiment = null,
                        Trial $trial = null,
                        $sponsor = "",
                        $howToCite = "")
  {
    $this->setProject($project);
    $this->setExperiment($experiment);
    $this->setTrial($trial);
    $this->setSponsor($sponsor);
    $this->setHowToCite($howToCite);
  }

  /**
   * Return the Web-Services URL that this instance is accessible at
   *
   * @return String RESTURI
   */
  function getRESTURI() {
    return "/Acknowledgement/{$this->getId()}";
  }

} // Acknowledgement
?>
