<?php

require_once 'lib/data/om/BaseDAQChannelOutput.php';


/**
 * Skeleton subclass for representing a row from the 'DAQChannel_Output' table.
 *
 *
 *
 * This class was autogenerated by Propel on:
 *
 * Mon Feb 18 08:21:37 2008
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.data
 */
class DAQChannelOutput extends BaseDAQChannelOutput {

  /**
   * Initializes internal state of DAQChannelOutput object.
   * @todo add initialization parameters
   */
  public function __construct() {
  }
} // DAQChannelOutput
