<?php

require_once 'lib/data/om/BaseEntityType.php';


/**
 * Skeleton subclass for representing a row from the 'EntityType' table.
 *
 *
 *
 * This class was autogenerated by Propel on:
 *
 * Sat Feb  9 00:02:53 2008
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.data
 */
class EntityType extends BaseEntityType {

  /**
   * Initializes internal state of EntityType object.
   * @todo We need to update this table on some rows,
   * for example:
   *    table_name of Facility is now Organization
   *    table_name of SensorLocation is now Location...
   */
  public function __construct(
    $table_name = null,
    $id_column = null,
    $class_name = null
  )
  {
    $this->setDatabaseTableName($table_name);
    $this->setTableIdColumn($id_column);
    $this->setClassName($class_name);
  }

} // EntityType
?>
