<?php

// include base peer class
require_once 'lib/data/om/BaseEquipmentModelPeer.php';

// include object class
include_once 'lib/data/EquipmentModel.php';


/**
 * Skeleton subclass for performing query and update operations on the 'EquipmentModel' table.
 *
 *
 *
 * This class was autogenerated by Propel on:
 *
 * Sat Feb  9 00:02:56 2008
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.data
 */
class EquipmentModelPeer extends BaseEquipmentModelPeer {

  /**
   * Find a EquipmentModel object based on its ID
   *
   * @param int $id
   * @return EquipmentModel
   */
  public static function find($id) {
    return self::retrieveByPK($id);
  }


  /**
   * Find all EquipmentModels
   *
   * @return array <EquipmentModel>
   */
  public static function findAll() {
    return self::doSelect(new Criteria());
  }


  //case "findByName":
  //return new Finder($finderName, "SELECT * FROM EquipmentModel WHERE name=?");
  public static function findByName($name) {
    $c = new Criteria();
    $c->add(self::NAME, $name);
    $c->setIgnoreCase(true);
    return self::doSelect($c);
  }




  //case "findByEquipmentClass":
  //return new Finder($finderName, "SELECT * FROM EquipmentModel WHERE equipmentClassId=?");
  public static function findByEquipmentClass($equipmentClassId) {
    $c = new Criteria();
    $c->add(self::EQUIPMENT_CLASS_ID, $equipmentClassId);

    return self::doSelect($c);
  }




  //case "findByNameAndEquipmentClass":
  //return new Finder($finderName, "SELECT * FROM EquipmentModel WHERE name = ? AND equipmentClassId=?");
  public static function findByNameAndEquipmentClass($name, $equipmentClassId) {
    $c = new Criteria();
    $c->add(self::NAME, $name);
    $c->add(self::EQUIPMENT_CLASS_ID, $equipmentClassId);

    return self::doSelect($c);
  }




  //case "dumpEquipmentModelTable":
  //return new Finder("dumpEquipmentModelTable", "SELECT equipmentClassId AS classId, id AS modelId, name FROM EquipmentModel ORDER BY equipmentClassId", false, false, true);
  public static function dumpEquipmentModelTable() {
    $c = new Criteria();
    $c->clearSelectColumns();
    $c->addAsColumn("CLASSID", self::EQUIPMENT_CLASS_ID);
    $c->addAsColumn("MODELID", self::ID);
    $c->addSelectColumn(self::NAME);
    $c->addAscendingOrderByColumn(self::EQUIPMENT_CLASS_ID);

    return self::doSelectRS($c);
  }


} // EquipmentModelPeer
?>
