<?php

require_once 'lib/data/om/BaseEquipmentGroupedAttribute.php';


/**
 * Skeleton subclass for representing a row from the 'Equipment_Grouped_Attribute' table.
 *
 *
 *
 * This class was autogenerated by Propel on:
 *
 * Sat Feb  9 00:02:56 2008
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.data
 */
class EquipmentGroupedAttribute extends BaseEquipmentGroupedAttribute {

  /**
   * Initializes internal state of EquipmentGroupedAttribute object.
   */
  public function __construct(
    Attribute $attribute,
    $g_attribute_id=null,
    $unit_id=null,
    $int_value=null,
    $num_value=null,
    $string_value=null,
    $date_value=null,
    $note=null,
    $page_count=null)
  {
    $this->setAttribute($attribute);
    $this->setGroupAttributeId($g_a);
    $this->setUnitId($unit_id);
    $this->setIntValue($int_value);
    $this->setStringValue($string_value);
    $this->setDateValue($date_value);
    $this->setNote($note);
    $this->setPageCount($page_count);
  }


  /**
   * Return the Web-Services URL that this instance is accessible at
   *
   * @return String RESTURI
   */
  function getRESTURI() {
    return "/EquipmentGroupedAttribute/{$this->getId()}";
  }

} // EquipmentGroupedAttribute

?>
