<?php

  // include base peer class
  require_once 'lib/data/om/BaseLoadTypePeer.php';

  // include object class
  include_once 'lib/data/LoadType.php';


/**
 * Skeleton subclass for performing query and update operations on the 'LoadType' table.
 *
 *
 *
 * This class was autogenerated by Propel on:
 *
 * Sat Feb  9 00:03:00 2008
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.data
 */
class LoadTypePeer extends BaseLoadTypePeer {

  /**
   * Find a LoadType object based on its ID
   *
   * @param int $id
   * @return LoadType
   */
  public static function find($id) {
    return self::retrieveByPK($id);
  }


  /**
   * Find all LoadTypes
   *
   * @return array <LoadType>
   */
  public static function findAll() {
    $c = new Criteria();
    $c->addAscendingOrderByColumn(self::ID);

    return self::doSelect($c);
  }


} // LoadTypePeer
?>
