<?php

  // include base peer class
  require_once 'lib/data/om/BaseMaterialFilePeer.php';

  // include object class
  include_once 'lib/data/MaterialFile.php';


/**
 * Skeleton subclass for performing query and update operations on the 'MaterialDataFile' table.
 *
 *
 *
 * This class was autogenerated by Propel on:
 *
 * Sat Feb  9 00:03:01 2008
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.data
 */
class MaterialFilePeer extends BaseMaterialFilePeer {

  /**
   * Find a MaterialFile object based on its ID
   *
   * @param int $id
   * @return MaterialFile
   */
  public static function find($id) {
    return self::retrieveByPK($id);
  }

  /**
   * Find a MaterialFile object based on its ID and materialId
   *
   * @param int $id
   * @param int $material_id
   * @return MaterialFile
   */
  public static function findOneByIdAndMaterial($id, $material_id) {
    $c = new Criteria();
    $c->add(self::MATERIAL_ID, $material_id);
    $c->add(self::ID, $id);

    return self::doSelectOne($c);
  }


  /**
   * Find all MaterialFiles
   *
   * @return array <MaterialFile>
   */
  public static function findAll() {
    return self::doSelect(new Criteria());
  }


  /*
      case "findByMaterial":
        return new Finder($finderName, "
                        SELECT mdf.id,
                               mdf.Material_id,
                               mdf.DataFile_id
                          FROM MaterialDataFile mdf
                         WHERE mdf.Material_id = ?");
  */
  public static function findByMaterial($material_id) {
    $c = new Criteria();
    $c->add(self::MATERIAL_ID, $material_id);

    return self::doSelect($c);
  }


  /**
   * Find MaterialFiles by a given Experiment
   *
   * @param int $expid
   * @return array <MaterialFile>
   */
  public static function findByExperiment($expid) {


    $c = new Criteria();
    $c->addJoin(self::MATERIAL_ID, MaterialPeer::ID);
    $c->add(MaterialPeer::EXPID, $expid);

    return self::doSelectJoinAll($c);
  }
} // MaterialFilePeer
?>
