<?php

require_once 'lib/data/om/BaseMaterialType.php';
require_once 'lib/data/MaterialTypeProperty.php';


/**
 * Skeleton subclass for representing a row from the 'MaterialType' table.
 *
 *
 *
 * This class was autogenerated by Propel on:
 *
 * Sat Feb  9 00:03:02 2008
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.data
 */
class MaterialType extends BaseMaterialType {

  /**
   * Initializes internal state of MaterialType object.
   */
  function __construct( $name = "",
                        $system_name = null,
                        $description = null)
  {
    $this->setDisplayName($name);
    $this->setSystemName($system_name);
    $this->setDescription($description);
  }


  /**
   * Return the Web-Services URL that this instance is accessible at
   *
   * @return String RESTURI
   */
  function getRESTURI() {
    return "/MaterialType/{$this->getId()}";
  }


  /**
   * Get the collection of MaterialTypeProperties of this MaterialType
   *
   * @return array <MaterialTypeProperty>
   */
  public function getMaterialTypeProperties() {
    //MaterialTypePropertyPeer::findByMaterialType($this->getId());
    return $this->getMaterialTypePropertys();
  }


  /**
   * Set the collection of MaterialTypeProperties for this MaterialType
   *
   * @param $props: array <MaterialTypeProperty>
   */
  public function setMaterialTypeProperties($props) {
    if(is_null($props)) $props = array();

    return $this->collMaterialTypePropertys = $props;
  }


  /**
   * Wrap {@link BaseMaterialType::getDisplayName}
   * Backward compatible to NEEScentral 1.7
   *
   * @return string
   */
  public function getName() {
    return $this->getDisplayName();
  }


  /**
   * Set the DisplayName for this MaterialType
   * Backward compatible to NEEScentral 1.7
   *
   * @param String $name
   */
  public function setName($name) {
    return $this->setDisplayName($name);
  }

} // MaterialType
?>
