<?php

require_once 'lib/data/om/BaseMeasurementUnitCategory.php';


/**
 * Skeleton subclass for representing a row from the 'MeasurementUnitCategory' table.
 *
 *
 *
 * This class was autogenerated by Propel on:
 *
 * Sat Feb  9 00:03:03 2008
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.data
 */
class MeasurementUnitCategory extends BaseMeasurementUnitCategory {

  /**
   * Constructor.
   *
   * Creates an instance of UnitCategory.  Parameters define the name and comment of the UnitCategory
   *
   *
   * @param int $id
   * @param string $name
   * @param string $comment
   */
  public function __construct($name='',
                              $comment='') {
    $this->setName($name);
    $this->setComment($comment);
  }


  /**
   * Get the MeasurementUnits list
   *
   * @return array <MeasurementUnit>
   */
  public function getUnits() {
    return $this->getMeasurementUnits();
  }


  /**
   * Return the Web-Services URL that this instance is accessible at
   *
   * @return String RESTURI
   */
  function getRESTURI() {
    return "/MaterialTypeProperty/{$this->getId()}";
  }

} // MeasurementUnitCategory
?>
