<?php

  // include base peer class
  require_once 'lib/data/om/BaseMeasurementUnitCategoryPeer.php';

  // include object class
  include_once 'lib/data/MeasurementUnitCategory.php';


/**
 * Skeleton subclass for performing query and update operations on the 'MeasurementUnitCategory' table.
 *
 *
 *
 * This class was autogenerated by Propel on:
 *
 * Sat Feb  9 00:03:03 2008
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.data
 */
class MeasurementUnitCategoryPeer extends BaseMeasurementUnitCategoryPeer {

  /**
   * Find a MeasurementUnitCategory object based on its ID
   *
   * @param int $id
   * @return MeasurementUnitCategory
   */
  public static function find($id) {
    return self::retrieveByPK($id);
  }


  /**
   * Find all MeasurementUnitCategories
   *
   * @return array <MeasurementUnitCategory>
   */
  public static function findAll() {
    $c = new Criteria();
    $c->addAscendingOrderByColumn(self::NAME);

    return self::doSelect($c);
  }


  /**
   * Find a MeasurementUnitCategory by a name
   *
   * @param String $name
   * @return MeasurementUnitCategory
   */
  public static function findByName($name) {
    $c = new Criteria();
    $c->add(self::NAME, $name);
    $c->setIgnoreCase(true);
    return self::doSelectOne($c);
  }


} // MeasurementUnitCategoryPeer
?>
