<?php

require_once 'lib/data/om/BaseNAWI.php';


/**
 * Skeleton subclass for representing a row from the 'NAWI' table.
 *
 *
 *
 * This class was autogenerated by Propel on:
 *
 * Sat Feb  9 00:03:04 2008
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.data
 */
class NAWI extends BaseNAWI {

  /**
   * Initializes internal state of NAWI object.
   */
  public function __construct()
  {
  }


  /**
   * Return the Web-Services URL that this instance is accessible at
   *
   * @return String RESTURI
   */
  function getRESTURI() {
    return "/NAWI/{$this->getId()}";
  }

} // NAWI
?>
