<?php

require_once 'lib/data/om/BaseSensorGroupedAttributeMap.php';


/**
 * Skeleton subclass for representing a row from the 'Sensor_Grouped_Attribute_Map' table.
 *
 *
 *
 * This class was autogenerated by Propel on:
 *
 * Sat Feb  9 00:03:10 2008
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.data
 */
class SensorGroupedAttributeMap extends BaseSensorGroupedAttributeMap {

  /**
   * Initializes internal state of SensorGroupedAttributeMap object.
   */
  public function __construct()
  {
  }

  /**
   * Return the Web-Services URL that this instance is accessible at
   *
   * @return String RESTURI
   */
  function getRESTURI() {
    return "/SensorGroupedAttributeMap/{$this->getId()}";
  }

} // SensorGroupedAttributeMap
?>
