<?php

require_once 'lib/data/om/BaseSensorModelDataFile.php';


/**
 * Skeleton subclass for representing a row from the 'SensorModelDataFile' table.
 *
 *
 *
 * This class was autogenerated by Propel on:
 *
 * Mon Feb 18 08:21:40 2008
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.data
 */
class SensorModelDataFile extends BaseSensorModelDataFile {

  /**
   * Constructs a new SensorModelDataFile
   */
  public function __construct(SensorModel $sensormodel = null,
                              DataFile $datafile = null
  )
  {
    $this->setSensorModel($sensormodel);
    $this->setDataFile($datafile);
  }


  /**
   * Return the Web-Services URL that this instance is accessible at
   *
   * @return String RESTURI
   */
  function getRESTURI() {
    return "/SensorModelDataFile/{$this->getId()}";
  }


} // SensorModelDataFile
