<?php

  // include base peer class
  require_once 'lib/data/om/BaseSensorAttributePeer.php';

  // include object class
  include_once 'lib/data/SensorAttribute.php';


/**
 * Skeleton subclass for performing query and update operations on the 'SensorAttribute' table.
 *
 *
 *
 * This class was autogenerated by Propel on:
 *
 * Sat Feb  9 00:03:08 2008
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.data
 */
class SensorAttributePeer extends BaseSensorAttributePeer {

  /**
   * Find a SensorAttribute object based on its ID
   *
   * @param int $id
   * @return SensorAttribute
   */
  public static function find($id) {
    return self::retrieveByPK($id);
  }


  /**
   * Find all SensorAttributes
   *
   * @return array <SensorAttribute>
   */
  public static function findAll() {
    return self::doSelect(new Criteria());
  }


} // SensorAttributePeer
?>
