<?php

  // include base peer class
  require_once 'lib/data/om/BaseSensorModelDataFilePeer.php';

  // include object class
  include_once 'lib/data/SensorModelDataFile.php';


/**
 * Skeleton subclass for performing query and update operations on the 'SensorModelDataFile' table.
 *
 *
 *
 * This class was autogenerated by Propel on:
 *
 * Mon Feb 18 08:21:40 2008
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.data
 */
class SensorModelDataFilePeer extends BaseSensorModelDataFilePeer {

  /**
   * Find a SensorModelDataFile object based on its ID
   *
   * @param int $id
   * @return SensorModelDataFile
   */
  public static function find($id) {
    return self::retrieveByPK($id);
  }


  /**
   * Find all SensorModelDataFiles
   *
   * @return array <SensorModelDataFile>
   */
  public static function findAll() {
    return self::doSelect(new Criteria());
  }

  /**
   * Find all SensorModelDataFiles given by SensorModel ID
   * @param int $sensor_model_id
   * @return SensorModelDataFile
   */
  public static function findBySensorModel($sensor_model_id) {
    $c = new Criteria();
    $c->add(self::SENSOR_MODEL_ID, $sensor_model_id);

    return self::doSelect($c);
  }



} // SensorModelDataFilePeer
