<?php

require_once 'lib/data/om/BaseThumbnail.php';


/**
 * Skeleton subclass for representing a row from the 'Thumbnail' table.
 *
 *
 *
 * This class was autogenerated by Propel on:
 *
 * Sat Feb  9 00:03:13 2008
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.data
 */
class Thumbnail extends BaseThumbnail {

  /**
   * Constructs a new Thumbnail
   */
  public function __construct($datafileId = null,
                              $entityId = null,
                              $entityTypeId = null)
  {
		$this->setDataFileId($datafileId);
    $this->setEntityId($entityId);
    $this->setEntityTypeId($entityTypeId);
  }

  /**
   * Return the Web-Services URL that this instance is accessible at
   *
   * @return String RESTURI
   */
  function getRESTURI() {
    return "/Thumbnail/{$this->getId()}";
  }

} // Thumbnail
?>
