<article>
	<h1><span>Support: Queries</span></h1>
	<section>
		<h2><span>Overview</span></h2>

		<p>The support ticket query builder allows users to create their own, custom queries for looking up tickets. Several default, commonly used queires are provided.</p>

		<p>Default queries are generally divided into three groups:</p>

		<dl>
			<dt>Common (in ACL)</dt>
			<dd>Commonly run queries, such as 'Open tickets' or 'New tickets'. Query is built and filtered based on user's ACL entry.</dd>

			<dt>Common (<em>not</em> in ACL)</dt>
			<dd>Commonly run queries, such as 'Open tickets' or 'New tickets'. Query is built and filtered to exclude data the user does nto have access to. Typically, this means the user will only see tickets they submitted, are assigned to, or tickets assigned to a group they belong to.</dd>

			<dt>Mine</dt>
			<dd>Commonly run queries, such as 'My open tickets' or 'My submitted tickets'. Queries are filtered to display only tickets associated to the logged in user.</dd>
		</dl>

		<p>Stats shown may also be filtered by group.</p>
	</section>
	<section>
		<h2><span>Adding/Editing</span></h2>

		<p>Queries are constructed using the Query Builder interface, which allows for specifying "Any" or "All" set of rules that must be met. Sub-groups of rules may also be applied.</p>
	</section>
</article>