<article>
	<h1><span>Support: Status</span></h1>

	<ul class="nav">
		<li><a href="#overview">Overview</a></li>
		<li><a href="#toolbar">Toolbar</a></li>
		<li><a href="#details">Details</a></li>
	</ul>

	<section id="description">
		<h2><span>Description</span></h2>
		<p>This is where you can add a new Status or edit an existing Status.</p>
	</section>
	<section id="toolbar">
		<h2><span>Toolbar</span></h2>
		<p>At the top right you will see the toolbar.</p>
		<p>The functions are:</p>
		<dl>
			<dt>Save</dt>
			<dd>Save changes and return to the edit form.</dd>

			<dt>Save &amp; Close</dt>
			<dd>Save changes and return to the listing of entries.</dd>

			<dt>Cancel</dt>
			<dd>Discard any changes made and return to the listing of entries.</dd>

			<dt>Help</dt>
			<dd>Opens this help screen.</dd>
		</dl>
	</section>
	<section id="details">
		<h2><span>Details</span></h2>

		<dl>
			<dt>Title</dt>
			<dd>The Title for this item.</dd>

			<dt>Alias</dt>
			<dd>The internal name of the item. Normally, you can leave this blank and the system will fill in a default value. The default value is the Title or Name in lower case and with dashes instead of spaces. You may enter the Alias manually. The Alias should consist of lowercase letters, numbers, and hyphens (-). No blank spaces or underscores are allowed.</dd>

			<dt>For</dt>
			<dd>If the status for open or closed tickets.</dd>

			<dt>Color</dt>
			<dd>A color to apply to tickets with this status. Allows for easier visual organization.</dd>
		</dl>
	</section>
</article>