<article>
	<h1><span>Support: Tickets</span></h1>

	<ul class="nav">
		<li><a href="#overview">Overview</a></li>
		<li><a href="#toolbar">Toolbar</a></li>
		<li><a href="#sub-menu">Sub-menu Links</a></li>
		<li><a href="#list-filters">List Filters</a></li>
	</ul>

	<section id="overview">
		<h2><span>Overview</span></h2>

		<p>Here you will find a list of submitted tickets. The view is divided between a list of queries (on the left) with various filters applied to generate specific ticket lists and the results of one of those queries (on the right).</p>
	</section>
	<section id="toolbar">
		<h2><span>Toolbar</span></h2>
		<p>At the top right you will see the toolbar. The functions are:</p>
		<dl>
			<dt>Options</dt>
			<dd>Opens the Options window where settings such as default parameters or permissions can be edited.</dd>

			<dt>New</dt>
			<dd>Opens the editing screen to create a new article.</dd>

			<dt>Trash</dt>
			<dd>Permanently remove the selected lists and all associated content (wishes, etc.).</dd>

			<dt>Help</dt>
			<dd>Opens this help screen.</dd>
		</dl>
	</section>
	<section id="sub-menu">
		<h2><span>Sub-menu Links</span></h2>
		<p>At the top left, above the filters, you will see sub-menu options. These are essentially filters for blog posts, filtering by the primary scopes (or types) of blogs. The links are:</p>
		<dl>
			<dt>Categories</dt>
			<dd>List all categories.</dd>
			<dt>Queries</dt>
			<dd>Area for managing the "Common" queries that every user sees.</dd>
			<dt>Messages</dt>
			<dd>List all canned or common response messages to support tickets.</dd>
			<dt>Resolutions</dt>
			<dd>List all available resolutions that a ticket can be assigned when closed.</dd>
			<dt>Abuse Reports</dt>
			<dd>Content that has been reported as abusive.</dd>
			<dt>Tag/Groups</dt>
			<dd>--</dd>
			<dt>Stats</dt>
			<dd>Overview of support ticket stats.</dd>
			<dt>ACL</dt>
			<dd>Interface for managing the Access Control List for support tickets.</dd>
		</dl>
	</section>
	<section id="list-filters">
		<h2><span>List Filters</span></h2>

		<h3>Page Controls</h3>
		<p>When the number of items is more than one page, you will see a page control bar as shown below.</p>

		<dl>
			<dt>Display #</dt>
			<dd>Select the number of items to show on one page.</dd>
			<dt>Start</dt>
			<dd>Click to go to the first page.</dd>
			<dt>Prev</dt>
			<dd>Click to go to the previous page.</dd>
			<dt>Page numbers</dt>
			<dd>Click to go to the desired page.</dd>
			<dt>Next</dt>
			<dd>Click to go to the next page.</dd>
			<dt>End</dt>
			<dd>Click to go to the last page.</dd>
		</dl>
	</section>
</article>