		<article>
			<h1><span>Support: Ticket</span></h1>
			<section>
				<h2><span>Overview</span></h2>

				<p>Here you will find a submitted ticket and all associated data, including comments, change and notification logs, and attachments.</p>
			</section>
			<section>
				<h2><span>Changes</span></h2>

				<p>The original ticket data may not be modified in any way. Only associated or non-destructive changes may occur, such as changing status, severity, adding/removing tags, and assigning owner. All changes are tracked in a log.</p>

				<h3>Status</h3>
				<dl>
					<dt>Open</dt>
					<dd>An open issue. The ticket needs to be addressed in some fashion.</dd>

					<dt>Awaiting user action</dt>
					<dd>This is for when you need more information from or the ticket submitter to perform a specific task (such as test that a fix is working for them). In short, further progress on the ticket is dependant upon the some course of action from the ticket submitter.</dd>

					<dt>Closed</dt>
					<dd>The ticket is considered recolved. Here, a list of resolutions can be specified to better filter and generate stats by.</dd>
				</dl>

				<h3>Owner</h3>

				<p>The owner of a ticket is the <i>current</i> user assigned to perform some action or address the the issue presented by the ticket in some way. Ownership may change several times during the life of the ticket and is tracked in the change log. When assigned to a ticket as an owner, the ticket will appear in the user's "My assigned tickets" list.</p>

				<h3>Group</h3>

				<p>Sometimes, a ticket may belong to a group of users rather than a specific person.</p>

				<h3>Severity</h3>

				<dl>
					<dt><span style="color: blue;">Low</span></dt>
					<dd>Minor loss of application functionality, product feature requests, how-to questions. There is a medium-to-low impact, but continues to function, including by using a procedural workaround.</dd>

					<dt>Medium</dt>
					<dd>Moderate loss of application functionality or performance resulting in multiple users impacted in their normal functions. Minor feature/product failure, convenient workaround exists/minor performance degradation/not impacting production.</dd>

					<dt><span style="color: orange;">High</span></dt>
					<dd>Critical loss of application functionality or performance resulting in high number of users unable to perform their normal functions. Major feature/product failure; inconvenient workaround or no workaround exists. The program is usable but severely limited.</dd>

					<dt><span style="color: red;">Critical</span></dt>
					<dd>Production application down or major malfunction resulting in a product inoperative condition. Users are unable to reasonably perform their normal functions. The specific functionality is mission critical and the situation is considered an emergency.</dd>
				</dl>
			</section>
			<section>
				<h2><span>Commenting</span></h2>

				<p>Comments are visible to anyone who has access to read this ticket, including the ticket submitter, unless the comment is marked <strong>private</strong>.</p>

				<h3>Notifying others</h3>

				<p>You may send the comment to others by filling in username, user ID, or email addresses in the "Send message to" field. Any value entered here is <em>sticky</em>--that is, the value will be retained and the field pre-filled for the next comment. This makes it easy to keep the same set of people notified. All notifications are tracked in a log.</p>
			</section>
			<section>
				<h2><span>Watching</span></h2>

				<p>When watching a ticket, you will be notified of any comments added or changes made. You may stop watching at any time.</p>
			</section>
		</article>