<article>
	<h1><span>Citations Manager: Edit Citation</span></h1>

	<ul class="nav">
		<li><a href="#overview">Overview</a></li>
		<li><a href="#toolbar">Toolbar</a></li>
		<li><a href="#details">Details</a></li>
		<li><a href="#citation-for">Citation For</a></li>
		<li><a href="#affiliation">Affiliation</a></li>
		<li><a href="#exclude">Exclude From Export</a></li>
		<li><a href="#abstract">Abstract Rollover</a></li>
	</ul>

	<section id="description">
		<h2><span>Description</span></h2>
		<p>This is where you can add a new Billboard or edit an existing Billboard.</p>
	</section>
	<section id="toolbar">
		<h2><span>Toolbar</span></h2>
		<p>At the top right you will see the toolbar.</p>
		<p>The functions are:</p>
		<dl>
			<dt>Save &amp; Close</dt>
			<dd>Save changes and return to the listing of entries.</dd>

			<dt>Cancel</dt>
			<dd>Discard any changes made and return to the listing of entries.</dd>

			<dt>Help</dt>
			<dd>Opens this help screen.</dd>
		</dl>
	</section>
	<section id="details">
		<h2><span>Details</span></h2>

		<dl>
			<dt>Type</dt>
			<dd>The Title for this item. This may or may not display on the page, depending on the parameter values you choose.</dd>
		</dl>
	</section>
	<section id="citation-for">
		<h2><span>Citation For</span></h2>

		<p>This is for establishing associations between content on the hub and a specific citation (i.e., the citation is <em>for</em> a piece of content on the hub).</p>
	</section>
	<section id="affiliation">
		<h2><span>Affiliation</span></h2>

		<p>Indicates if the entry is from an organization affiliated with the hub.</p>
	</section>
	<section id="exclude">
		<h2><span>Exclude From Export</span></h2>

		<p>??</p>
	</section>
	<section id="abstract">
		<h2><span>Abstract Rollover</span></h2>

		<p>??</p>
	</section>
</article>