			<h1><span>Course Offerings</span></h1>
			<div class="section">
				<h2><span>Overview</span></h2>

				<p>An offering contains all the course materials such as videos, slides, homeworks, and exams.</p>
			</div>
			<div class="section">
				<h2><span>Managers</span></h2>

				<p>Managers of an offering have full permissions to create, edit, or delete content for any section within the offering. Listed managers do <strong>not</strong> have permissions to create, edit, or delete content for other offerings unless explicitly specified as a manager of that offering.</p>
			</div>
			<div class="section">
				<h2><span>Sections</span></h2>

				<p>A section not only supplies information about the days and time when students may access content to study a particular subject (course), they also differentiate a particular group of students enrolled in a course from all other groups of students, enrolled in either in the same course or different courses.</p>
				<p>Section dates are used to indicate that a course is being offered during a time period.</p>
			</div>
			<div class="section">
				<h2><span>Units</span></h2>

				<p>A unit can be thought of as a container of groupings of content (lectures). To use a traditional course as an analog, the most common unit is a "week", which will contain lectures (groupings of content) for each day and a quiz at the end of the week.</p>
			</div>
			<div class="section">
				<h2><span>Pages</span></h2>

				<p>This is supplementary content that has information specific to an offering. This is typically the syllabus.</p>
			</div>