<article>
	<h1><span>Language Manager: Language Overrides</span></h1>

	<ul class="nav">
		<li><a href="#overview">Overview</a></li>
		<li><a href="#column-headers">Column Headers</a></li>
		<li><a href="#toolbar">Toolbar</a></li>
		<li><a href="#list-filters">List Filters</a></li>
	</ul>

	<section id="overview">
		<h2> <span class="mw-headline" id="Description">Description</span></h2>
		<p>Here you can override any language string in your website in any installed language.</p>
		<h2> <span class="mw-headline" id="Column_Headers">Column Headers</span></h2>
		<ul>
		<li><b>Checkbox</b>. Check this box to select one or more items. To select all items, check the box in the column heading. After one or more boxes are checked, click a toolbar button to take an action on the selected item or items. Many toolbar actions, such as Publish and Unpublish, can work with multiple items. Others, such as Edit, only work on one item at a time. If multiple items are checked and you press Edit, the first item will be opened for editing.</li>
		<li><b>Constant.</b> The language string constant being overridden.</li>
		<li><b>Text.</b> The text that is replacing the language constant.</li>
		<li><b>Language Tag.</b> The language tag of the text.</li>
		</ul>
		<ul>
		<li><b>Location.</b> Whether the item is a public front-end or an administrator back-end item. 'Site' means it is a public front-end item. 'Administrator' means it is an administrator back-end item.</li>
		</ul>
		<ul>
		<li><b>#</b>. An indexing number automatically assigned by the CMS for ease of reference.</li>
		</ul>
		<h2> <span class="mw-headline" id="List_Filters">List Filters</span></h2>
		<h3> <span class="mw-headline" id="Filter_by_Partial_Title">Filter by Partial Title</span></h3>
		<p>You can filter the list of items by typing part of the constant's name or the ID number of the constant.</p>
		<h3> <span class="mw-headline" id="Filter_by_Language">Filter by Language</span></h3>
		<p>In the upper right area, above the column headings, there is a drop-down list boxes.</p>
		<p>You can filter by the Language of the Strings and by site or administrator access</p>
		<h3> <span class="mw-headline" id="Number_of_Items_to_Display">Number of Items to Display</span></h3>
		<p>Below the list you'll find:</p>
		<ul>
		<li><b>Page Controls.</b> When the number of items is more than one page, you will see a page control bar as shown below.
		<ul>
		<li><b>Display #:</b> Select the number of items to show on one page.</li>
		<li><b>Start:</b> Click to go to the first page.</li>
		<li><b>Prev:</b> Click to go to the previous page.</li>
		<li><b>Page numbers:</b> Click to go to the desired page.</li>
		<li><b>Next:</b> Click to go to the next page.</li>
		<li><b>End:</b> Click to go to the last page.</li>
		</ul>
		</li>
		</ul>
		<h2> <span class="mw-headline" id="Options">Options</span></h2>
		<p>Click the Options button to open the <b>Language Manager Options</b> window which lets you configure this component.</p>
		<h3> <span class="mw-headline" id="Buttons_Common_to_All_Tabs">Buttons Common to All Tabs</span></h3>
		<p>At the top right of the Options modal window you will see the toolbar.</p>
		<ul>
		<li><b>Save</b>. Saves the language options and stays in the current screen.</li>
		<li><b>Save &amp; Close</b>. Saves the language options and closes the current screen.</li>
		<li><b>Cancel/Close</b>. Closes the current screen and returns to the previous screen without saving any modifications you may have made.</li>
		</ul>
		<h3> <span class="mw-headline" id="Permissions_Tab">Permissions Tab</span></h3>
		<p>This screen allows you to set the component permissions. This is important to consider if you have sites with many different user categories all of whom need to have different accessibilities to the component. The screenshot below describes what you should see and the text below that describes what each permission level gives the user access to:</p>
		<p>You work on one Group at a time by opening the slider for that group. You change the permissions in the Select New Settings drop-down list boxes. The options for each value are Inherited, Allowed, or Denied. The Calculated Setting column shows you the setting in effect. It is either Not Allowed (the default), Allowed, or Denied. Note that the Calculated Setting column is not updated until you press the Save button in the toolbar. To check that the settings are what you want, press the Save button and check the Calculated Settings column.</p>
		<p>The default values used here are the ones set in the <a href="<?php echo Route::url('index.php?option=com_help&view=help&keyref=Help25:Site_Global_Configuration#Permissions'); ?>" title="Help25:Site Global Configuration">Global Configuration Permissions Tab</a></p>
		<dl>
		<dd>
		<dl>
		<dt>Configure</dt>
		<dd>Open the language manager option screens (the modal window these options are in)</dd>
		<dt>Access Administration Interface</dt>
		<dd>Open the language manager manger screens</dd>
		<dt>Create&#160;</dt>
		<dd>Create new languages and string overrides in the component</dd>
		<dt>Delete&#160;</dt>
		<dd>Delete existing languages and string overrides in the component</dd>
		<dt>Edit&#160;</dt>
		<dd>Edit existing languages and string overrides in the component</dd>
		<dt>Edit State&#160;</dt>
		<dd>Change an languages and string overrides state (Publish, Unpublish, Archive, and Trash) in the component.</dd>
		</dl>
		</dd>
		</dl>
		<p>There are two very important points to understand from this screen. The first is to see how the permissions can be inherited from the parent Group. The second is to see how you can control the default permissions by Group and by Action. This provides a lot of flexibility. For example, if you wanted Shop Suppliers to be able to have the ability to create an article about their product, you could just change their Create value to "Allowed". If you wanted to not allow members of Administrator group to delete objects or change their state, you would change their permissions in these columns to Inherited (or Denied). It is also important to understand that the ability to have child groups is completely optional. It allows you to save some time when setting up new groups. However, if you like, you can set up all groups to have Public as the parent and not inherit any permissions from a parent group.</p>
		<h2> <span class="mw-headline" id="Toolbar">Toolbar</span></h2>
		<p>At the top right you will see the toolbar. The functions are:</p>
		<ul>
		<li><b>New</b>. Opens the editing screen to create a new language override.</li>
		<li><b>Edit</b>. Opens the editing screen for the selected language override. If more than one language override is selected (where applicable), only the first language override will be opened. The editing screen can also be opened by clicking on the Title or Name of the language override.</li>
		<li><b>Delete</b>. Deletes the selected language overrides. Works with one or multiple language overrides selected.</li>
		<li><b>Options</b>. Opens the Options window where settings such as default parameters or permissions can be edited.</li>
		<li><b>Help</b>. Opens this help screen.</li>
		</ul>
		<h2> <span class="mw-headline" id="Toolbar_Links">Toolbar Links</span></h2>
		<p>At the top left, above the columns, you will see four links as shown below:</p>
		<ul>
		<li><b>Installed - Site.</b> Shows the Languages available for the front-end of the web site. See <a href="<?php echo Route::url('index.php?option=com_help&view=help&keyref=Help25:Extensions_Language_Manager_Installed'); ?>" title="Help25:Extensions Language Manager Installed">Installed Languages Help Screen</a></li>
		<li><b>Installed - Administrator.</b> Shows the Languages available for the back-end of the web site. See <a href="<?php echo Route::url('index.php?option=com_help&view=help&keyref=Help25:Extensions_Language_Manager_Installed'); ?>" title="Help25:Extensions Language Manager Installed">Installed Languages Help Screen</a></li>
		<li><b>Content.</b> Shows the Content Languages available for the web site. See <a href="<?php echo Route::url('index.php?option=com_help&view=help&keyref=Help25:Extensions_Language_Manager_Content'); ?>" title="Help25:Extensions Language Manager Content">Extensions Language Manager Content</a>.</li>
		<li><b>Overrides.</b> Allows you to override any language strings in any language file through the backend. See <strong class="selflink">Language Overrides Help Screen</strong></li>
		</ul>
		<h2> <span class="mw-headline" id="See_Also">See Also</span></h2>
		<p><a href="<?php echo Route::url('index.php?option=com_help&view=help&keyref=Language_Overrides'); ?>" title="Language Overrides">Layout Overrides</a></p>
	</section>
</article>