

/* -----------------------------------------------------------------------
   CURATED_CONTACT_LOG
   ----------------------------------------------------------------------- */

DROP TABLE "CURATED_CONTACT_LOG" CASCADE CONSTRAINTS;

DROP SEQUENCE "CURATED_CONTACT_LOG_SEQ";


CREATE TABLE "CURATED_CONTACT_LOG"
(
	"ID" NUMBER(22)  NOT NULL,
	"CONTACT_DATE" DATE,
	"CONTACT_FIRST_NAME" VARCHAR2(80),
	"CONTACT_LAST_NAME" VARCHAR2(80),
	"CONTACT_METHOD" VARCHAR2(160),
	"CONTACT_REASON" CLOB,
	"CONTACT_RESOLUTION" CLOB,
	"CONTACT_STATUS" VARCHAR2(160),
	"CREATED_BY" VARCHAR2(80),
	"CREATED_DATE" DATE,
	"OBJECT_ID" NUMBER(22),
	"PHONE_NUMBER" VARCHAR2(120)
);

	ALTER TABLE "CURATED_CONTACT_LOG"
		ADD CONSTRAINT "CURATED_CONTACT_LOG_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "CURATED_CONTACT_LOG_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;

ALTER TABLE "CURATED_CONTACT_LOG" ADD CONSTRAINT "CURATED_CONTACT_LOG_FK_1" FOREIGN KEY ("OBJECT_ID") REFERENCES "CURATED_OBJECTS" ("OBJECT_ID") ON DELETE CASCADE;


/* -----------------------------------------------------------------------
   CURATED_EXTENDED_ATTRIBUTES
   ----------------------------------------------------------------------- */

DROP TABLE "CURATED_EXTENDED_ATTRIBUTES" CASCADE CONSTRAINTS;

DROP SEQUENCE "CRTD_XTNDD_TTRBTS_SEQ";


CREATE TABLE "CURATED_EXTENDED_ATTRIBUTES"
(
	"ID" NUMBER(22)  NOT NULL,
	"ATTRIBUTE_ID" NUMBER(22),
	"ATTRIBUTE_NAME" VARCHAR2(160),
	"ATTRIBUTE_VALUE" VARCHAR2(400),
	"OBJECT_ID" NUMBER(22)
);

	ALTER TABLE "CURATED_EXTENDED_ATTRIBUTES"
		ADD CONSTRAINT "CURATED_EXTENDED_ATTRIBUTES_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "CRTD_XTNDD_TTRBTS_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;

ALTER TABLE "CURATED_EXTENDED_ATTRIBUTES" ADD CONSTRAINT "CURATED_EXTENDED_ATTRIBUT_FK_1" FOREIGN KEY ("OBJECT_ID") REFERENCES "CURATED_OBJECTS" ("OBJECT_ID") ON DELETE CASCADE;


/* -----------------------------------------------------------------------
   CURATEDNCIDCROSS_REF
   ----------------------------------------------------------------------- */

DROP TABLE "CURATEDNCIDCROSS_REF" CASCADE CONSTRAINTS;

DROP SEQUENCE "CURATEDNCIDCROSS_REF_SEQ";


CREATE TABLE "CURATEDNCIDCROSS_REF"
(
	"ID" NUMBER(22)  NOT NULL,
	"CREATED_BY" VARCHAR2(80),
	"CREATED_DATE" DATE,
	"CURATED_ENTITYID" NUMBER(22),
	"NEESCENTRAL_OBJECTID" NUMBER(22),
	"NEESCENTRAL_TABLE_SOURCE" VARCHAR2(120)
);

	ALTER TABLE "CURATEDNCIDCROSS_REF"
		ADD CONSTRAINT "CURATEDNCIDCROSS_REF_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "CURATEDNCIDCROSS_REF_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;


/* -----------------------------------------------------------------------
   CURATED_OBJECT_ASSOCIATIONS
   ----------------------------------------------------------------------- */

DROP TABLE "CURATED_OBJECT_ASSOCIATIONS" CASCADE CONSTRAINTS;

DROP SEQUENCE "CRTD_BJCT_SSCTNS_SEQ";


CREATE TABLE "CURATED_OBJECT_ASSOCIATIONS"
(
	"ID" NUMBER(22)  NOT NULL,
	"CREATED_BY" VARCHAR2(80),
	"CREATED_DATE" DATE,
	"INVERSE_OF" NUMBER(22),
	"REFERENCE_FOR_OBJECT" NUMBER(22),
	"REFERENCE_TO_OBJECT" NUMBER(22),
	"VERB" VARCHAR2(120)
);

	ALTER TABLE "CURATED_OBJECT_ASSOCIATIONS"
		ADD CONSTRAINT "CURATED_OBJECT_ASSOCIATIONS_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "CRTD_BJCT_SSCTNS_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;


/* -----------------------------------------------------------------------
   CURATED_OBJECT_AUTHORS
   ----------------------------------------------------------------------- */

DROP TABLE "CURATED_OBJECT_AUTHORS" CASCADE CONSTRAINTS;

DROP SEQUENCE "CRTD_BJCT_THRS_SEQ";


CREATE TABLE "CURATED_OBJECT_AUTHORS"
(
	"ID" NUMBER(22)  NOT NULL,
	"AUTHOR_TYPE" VARCHAR2(80),
	"CREATED_BY" VARCHAR2(80),
	"CREATED_DATE" DATE,
	"FIRST_NAME" VARCHAR2(80),
	"LAST_NAME" VARCHAR2(80),
	"MIDDLE_NAME" VARCHAR2(80),
	"OBJECT_ID" NUMBER(22),
	"TITLE" VARCHAR2(1016)
);

	ALTER TABLE "CURATED_OBJECT_AUTHORS"
		ADD CONSTRAINT "CURATED_OBJECT_AUTHORS_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "CRTD_BJCT_THRS_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;

ALTER TABLE "CURATED_OBJECT_AUTHORS" ADD CONSTRAINT "CURATED_OBJECT_AUTHORS_FK_1" FOREIGN KEY ("OBJECT_ID") REFERENCES "CURATED_OBJECTS" ("OBJECT_ID") ON DELETE CASCADE;


/* -----------------------------------------------------------------------
   CURATED_OBJECT_CATALOG_ENTRY
   ----------------------------------------------------------------------- */

DROP TABLE "CURATED_OBJECT_CATALOG_ENTRY" CASCADE CONSTRAINTS;

DROP SEQUENCE "CRTD_BJCT_CTLG_NTRY_SEQ";


CREATE TABLE "CURATED_OBJECT_CATALOG_ENTRY"
(
	"ID" NUMBER(22)  NOT NULL,
	"CREATED_BY" VARCHAR2(80),
	"CREATED_DATE" DATE,
	"OBJECT_ID" NUMBER(22),
	"ONTOLOGY_TERM" VARCHAR2(512),
	"RELEVANCE_LEVEL" VARCHAR2(160)
);

	ALTER TABLE "CURATED_OBJECT_CATALOG_ENTRY"
		ADD CONSTRAINT "CURATED_OBJECT_CATALOG_ENTR_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "CRTD_BJCT_CTLG_NTRY_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;

ALTER TABLE "CURATED_OBJECT_CATALOG_ENTRY" ADD CONSTRAINT "CURATED_OBJECT_CATALOG_EN_FK_1" FOREIGN KEY ("OBJECT_ID") REFERENCES "CURATED_OBJECTS" ("OBJECT_ID") ON DELETE CASCADE;


/* -----------------------------------------------------------------------
   CURATED_OBJECTS
   ----------------------------------------------------------------------- */

DROP TABLE "CURATED_OBJECTS" CASCADE CONSTRAINTS;

DROP SEQUENCE "CURATED_OBJECTS_SEQ";


CREATE TABLE "CURATED_OBJECTS"
(
	"OBJECT_ID" NUMBER(22)  NOT NULL,
	"CONFORMANCE_LEVEL" VARCHAR2(160),
	"CREATED_BY" VARCHAR2(80),
	"CREATED_DATE" DATE,
	"CURATION_STATE" VARCHAR2(160),
	"DESCRIPTION" CLOB,
	"INITIAL_CURATION_DATE" DATE,
	"LINK" VARCHAR2(1016),
	"MODIFIED_BY" VARCHAR2(80),
	"MODIFIED_DATE" DATE,
	"NAME" VARCHAR2(200),
	"OBJECT_CREATION_DATE" DATE,
	"OBJECT_STATUS" VARCHAR2(160),
	"OBJECT_TYPE" VARCHAR2(160),
	"OBJECT_VISIBILITY" VARCHAR2(160),
	"SHORT_TITLE" VARCHAR2(400),
	"TITLE" VARCHAR2(1016),
	"VERSION" VARCHAR2(40)
);

	ALTER TABLE "CURATED_OBJECTS"
		ADD CONSTRAINT "CURATED_OBJECTS_PK"
	PRIMARY KEY ("OBJECT_ID");
CREATE SEQUENCE "CURATED_OBJECTS_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;


/* -----------------------------------------------------------------------
   ENTITY_CURATION_HISTORY
   ----------------------------------------------------------------------- */

DROP TABLE "ENTITY_CURATION_HISTORY" CASCADE CONSTRAINTS;

DROP SEQUENCE "NTTY_CRTN_HSTRY_SEQ";


CREATE TABLE "ENTITY_CURATION_HISTORY"
(
	"ID" NUMBER(22)  NOT NULL,
	"COMMENTS" CLOB,
	"CREATED_BY" VARCHAR2(80),
	"CREATED_DATE" DATE,
	"CURATION_STATE" VARCHAR2(160),
	"CURATION_STATE_DATE" DATE,
	"OBJECT_ID" NUMBER(22),
	"REASON" VARCHAR2(160),
	"REASON_DATE" DATE
);

	ALTER TABLE "ENTITY_CURATION_HISTORY"
		ADD CONSTRAINT "ENTITY_CURATION_HISTORY_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "NTTY_CRTN_HSTRY_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;

ALTER TABLE "ENTITY_CURATION_HISTORY" ADD CONSTRAINT "ENTITY_CURATION_HISTORY_FK_1" FOREIGN KEY ("OBJECT_ID") REFERENCES "CURATED_OBJECTS" ("OBJECT_ID") ON DELETE CASCADE;


/* -----------------------------------------------------------------------
   ENTITY_TYPE_ASSOCIATION_DEF
   ----------------------------------------------------------------------- */

DROP TABLE "ENTITY_TYPE_ASSOCIATION_DEF" CASCADE CONSTRAINTS;

DROP SEQUENCE "NTTY_TYP_SSCTN_DF_SEQ";


CREATE TABLE "ENTITY_TYPE_ASSOCIATION_DEF"
(
	"ID" NUMBER(22)  NOT NULL,
	"ASSOCIATION_VERB" VARCHAR2(120),
	"CREATED_BY" VARCHAR2(80),
	"CREATED_DATE" DATE,
	"FOR_OBJECT_TYPE" VARCHAR2(160),
	"INVERSE_ASSOCIATION_VERB" VARCHAR2(120),
	"MODIFIED_BY" VARCHAR2(80),
	"MODIFIED_DATE" DATE,
	"TO_OBJECT_TYPE" VARCHAR2(160)
);

	ALTER TABLE "ENTITY_TYPE_ASSOCIATION_DEF"
		ADD CONSTRAINT "ENTITY_TYPE_ASSOCIATION_DEF_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "NTTY_TYP_SSCTN_DF_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;


/* -----------------------------------------------------------------------
   ENTITY_TYPE_EXTENDED_ATTR_DEF
   ----------------------------------------------------------------------- */

DROP TABLE "ENTITY_TYPE_EXTENDED_ATTR_DEF" CASCADE CONSTRAINTS;

DROP SEQUENCE "NTTY_TYP_XTNDD_TTR_DF_SEQ";


CREATE TABLE "ENTITY_TYPE_EXTENDED_ATTR_DEF"
(
	"ID" NUMBER(22)  NOT NULL,
	"ATTRIBUTE_NAME" VARCHAR2(160),
	"CREATED_BY" VARCHAR2(80),
	"CREATED_DATE" DATE,
	"MODIFIED_BY" VARCHAR2(80),
	"MODIFIED_DATE" DATE,
	"OBJECT_TYPE" VARCHAR2(160)
);

	ALTER TABLE "ENTITY_TYPE_EXTENDED_ATTR_DEF"
		ADD CONSTRAINT "ENTITY_TYPE_EXTENDED_ATTR_D_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "NTTY_TYP_XTNDD_TTR_DF_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;


/* -----------------------------------------------------------------------
   LOOKUP_TYPES
   ----------------------------------------------------------------------- */

DROP TABLE "LOOKUP_TYPES" CASCADE CONSTRAINTS;

DROP SEQUENCE "LOOKUP_TYPES_SEQ";


CREATE TABLE "LOOKUP_TYPES"
(
	"ID" NUMBER(22)  NOT NULL,
	"TYPE" VARCHAR2(120)
);

	ALTER TABLE "LOOKUP_TYPES"
		ADD CONSTRAINT "LOOKUP_TYPES_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "LOOKUP_TYPES_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;


/* -----------------------------------------------------------------------
   LOOKUPS
   ----------------------------------------------------------------------- */

DROP TABLE "LOOKUPS" CASCADE CONSTRAINTS;

DROP SEQUENCE "LOOKUPS_SEQ";


CREATE TABLE "LOOKUPS"
(
	"ID" NUMBER(22)  NOT NULL,
	"CODE" VARCHAR2(40),
	"CREATED_BY" VARCHAR2(80),
	"CREATED_DATE" DATE,
	"DESCRIPTION" VARCHAR2(1016),
	"MEANING" VARCHAR2(160),
	"MODIFIED_BY" VARCHAR2(80),
	"MODIFIED_DATE" DATE,
	"TYPE" VARCHAR2(120)
);

	ALTER TABLE "LOOKUPS"
		ADD CONSTRAINT "LOOKUPS_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "LOOKUPS_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;


/* -----------------------------------------------------------------------
   MESSAGE
   ----------------------------------------------------------------------- */

DROP TABLE "MESSAGE" CASCADE CONSTRAINTS;

DROP SEQUENCE "MESSAGE_SEQ";


CREATE TABLE "MESSAGE"
(
	"ID" NUMBER(22)  NOT NULL,
	"DESCRIPTION" VARCHAR2(1016),
	"KEY_NAME" VARCHAR2(512),
	"KEY_VALUE" VARCHAR2(1016),
	"LANGUAGE" VARCHAR2(20),
	"NAME_SPACE" VARCHAR2(200),
	"SHORT_LANGUAGE" VARCHAR2(8)
);

	ALTER TABLE "MESSAGE"
		ADD CONSTRAINT "MESSAGE_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "MESSAGE_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;


/* -----------------------------------------------------------------------
   ONTOLOGY
   ----------------------------------------------------------------------- */

DROP TABLE "ONTOLOGY" CASCADE CONSTRAINTS;

DROP SEQUENCE "ONTOLOGY_SEQ";


CREATE TABLE "ONTOLOGY"
(
	"ID" NUMBER(22)  NOT NULL,
	"BROADER_TERM" NUMBER(22),
	"COMMENTS" CLOB,
	"TERM" VARCHAR2(512)
);

	ALTER TABLE "ONTOLOGY"
		ADD CONSTRAINT "ONTOLOGY_PK"
	PRIMARY KEY ("ID");
CREATE INDEX "SYS_C0040772" ON "ONTOLOGY" ("TERM");
CREATE SEQUENCE "ONTOLOGY_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;
CREATE INDEX "SYS_C0040772" ON "ONTOLOGY" ("TERM");


/* -----------------------------------------------------------------------
   ONTOLOGY_NARROW
   ----------------------------------------------------------------------- */

DROP TABLE "ONTOLOGY_NARROW" CASCADE CONSTRAINTS;

DROP SEQUENCE "ONTOLOGY_NARROW_SEQ";


CREATE TABLE "ONTOLOGY_NARROW"
(
	"ID" NUMBER(22)  NOT NULL,
	"NARROWER_TERM" NUMBER(22),
	"TERM_ID" NUMBER(22)
);

	ALTER TABLE "ONTOLOGY_NARROW"
		ADD CONSTRAINT "ONTOLOGY_NARROW_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "ONTOLOGY_NARROW_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;


/* -----------------------------------------------------------------------
   REGISTRY
   ----------------------------------------------------------------------- */

DROP TABLE "REGISTRY" CASCADE CONSTRAINTS;

DROP SEQUENCE "REGISTRY_SEQ";


CREATE TABLE "REGISTRY"
(
	"ID" NUMBER(22)  NOT NULL,
	"ACCESS_TIME" DATE,
	"DESCRIPTION" VARCHAR2(1016),
	"KEY_NAME" VARCHAR2(512),
	"KEY_TYPE" VARCHAR2(36),
	"KEY_VALUE" VARCHAR2(1016),
	"NAME_SPACE" VARCHAR2(200),
	"STATUS" VARCHAR2(32)
);

	ALTER TABLE "REGISTRY"
		ADD CONSTRAINT "REGISTRY_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "REGISTRY_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;


/* -----------------------------------------------------------------------
   SESSIONS
   ----------------------------------------------------------------------- */

DROP TABLE "SESSIONS" CASCADE CONSTRAINTS;

DROP SEQUENCE "SESSIONS_SEQ";


CREATE TABLE "SESSIONS"
(
	"SESSION_ID" VARCHAR2(128)  NOT NULL,
	"ACCESS_TIME" DATE,
	"DATA" CLOB,
	"IP_ADDRESS" VARCHAR2(60)
);

	ALTER TABLE "SESSIONS"
		ADD CONSTRAINT "SESSIONS_PK"
	PRIMARY KEY ("SESSION_ID");
CREATE SEQUENCE "SESSIONS_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;
