

/* -----------------------------------------------------------------------
   TSUNAMI_BIOLOGICAL_DATA
   ----------------------------------------------------------------------- */

DROP TABLE "TSUNAMI_BIOLOGICAL_DATA" CASCADE CONSTRAINTS;

DROP SEQUENCE "TSNM_BLGCL_DT_SEQ";


CREATE TABLE "TSUNAMI_BIOLOGICAL_DATA"
(
	"TSUNAMI_BIOLOGICAL_DATA_ID" NUMBER(22)  NOT NULL,
	"FAUNA" NUMBER(22),
	"FLORA" NUMBER(22),
	"MARINE_BIOLOGY" NUMBER(22),
	"TSUNAMI_DOC_LIB_ID" NUMBER(22)
);

	ALTER TABLE "TSUNAMI_BIOLOGICAL_DATA"
		ADD CONSTRAINT "TSUNAMI_BIOLOGICAL_DATA_PK"
	PRIMARY KEY ("TSUNAMI_BIOLOGICAL_DATA_ID");
CREATE SEQUENCE "TSNM_BLGCL_DT_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;

ALTER TABLE "TSUNAMI_BIOLOGICAL_DATA" ADD CONSTRAINT "TSUNAMI_BIOLOGICAL_DATA_FK_1" FOREIGN KEY ("TSUNAMI_DOC_LIB_ID") REFERENCES "TSUNAMI_DOC_LIB" ("TSUNAMI_DOC_LIB_ID");


/* -----------------------------------------------------------------------
   TSUNAMI_DOC_LIB
   ----------------------------------------------------------------------- */

DROP TABLE "TSUNAMI_DOC_LIB" CASCADE CONSTRAINTS;

DROP SEQUENCE "TSUNAMI_DOC_LIB_SEQ";


CREATE TABLE "TSUNAMI_DOC_LIB"
(
	"TSUNAMI_DOC_LIB_ID" NUMBER(22)  NOT NULL,
	"AUTHOR_EMAILS" VARCHAR2(1020),
	"AUTHORS" VARCHAR2(1020),
	"DESCRIPTION" CLOB,
	"DIRTY" NUMBER(22),
	"FILE_LOCATION" VARCHAR2(1020),
	"FILE_SIZE" NUMBER(22),
	"HOW_TO_CITE" VARCHAR2(1020),
	"NAME" VARCHAR2(1020),
	"SPECIFIC_LAT" FLOAT(22),
	"SPECIFIC_LON" FLOAT(22),
	"START_DATE" DATE,
	"TITLE" VARCHAR2(1020),
	"TSUNAMI_PROJECT_ID" NUMBER(22),
	"TYPE_OF_MATERIAL" VARCHAR2(48)
);

	ALTER TABLE "TSUNAMI_DOC_LIB"
		ADD CONSTRAINT "TSUNAMI_DOC_LIB_PK"
	PRIMARY KEY ("TSUNAMI_DOC_LIB_ID");
CREATE SEQUENCE "TSUNAMI_DOC_LIB_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;

ALTER TABLE "TSUNAMI_DOC_LIB" ADD CONSTRAINT "TSUNAMI_DOC_LIB_FK_1" FOREIGN KEY ("TSUNAMI_PROJECT_ID") REFERENCES "TSUNAMI_PROJECT" ("TSUNAMI_PROJECT_ID");


/* -----------------------------------------------------------------------
   TSUNAMI_ENGINEERING_DATA
   ----------------------------------------------------------------------- */

DROP TABLE "TSUNAMI_ENGINEERING_DATA" CASCADE CONSTRAINTS;

DROP SEQUENCE "TSNM_NGNRNG_DT_SEQ";


CREATE TABLE "TSUNAMI_ENGINEERING_DATA"
(
	"TSUNAMI_ENGINEERING_DATA_ID" NUMBER(22)  NOT NULL,
	"EVENT" NUMBER(22),
	"EVENT_SENSOR_DATA" NUMBER(22),
	"EVENT_VIDEO" NUMBER(22),
	"GEOTECH" NUMBER(22),
	"GEOTECH_DAMAGE_DESCR" NUMBER(22),
	"GEOTECH_SITE_CHAR" NUMBER(22),
	"GEOTECH_SOIL_CHAR" NUMBER(22),
	"GEOTECH_VUL_ASSESSMENT" NUMBER(22),
	"HM" NUMBER(22),
	"HM_EVAC_PLAN_MAPS" NUMBER(22),
	"HM_FAULT_MAPS" NUMBER(22),
	"HM_HAZARD_ASSESSMENT" NUMBER(22),
	"HM_HAZARD_MAPS" NUMBER(22),
	"HM_SHELTER_LOCATIONS" NUMBER(22),
	"LIFELINE" NUMBER(22),
	"LIFELINE_DAMAGE_DESCR" NUMBER(22),
	"LIFELINE_DESIGN" NUMBER(22),
	"LIFELINE_SEISMIC_DESIGN" NUMBER(22),
	"LIFELINE_TYPE" NUMBER(22),
	"LIFELINE_VUL_ASSESSMENT" NUMBER(22),
	"LIFELINE_YEAR" NUMBER(22),
	"STRUCTURE" NUMBER(22),
	"STRUCTURE_DAMAGE_DESCR" NUMBER(22),
	"STRUCTURE_DESIGN" NUMBER(22),
	"STRUCTURE_SEISMIC_DESIGN" NUMBER(22),
	"STRUCTURE_TYPE" NUMBER(22),
	"STRUCTURE_VUL_ASSESSMENT" NUMBER(22),
	"STRUCTURE_YEAR" NUMBER(22),
	"TSUNAMI_DOC_LIB_ID" NUMBER(22)
);

	ALTER TABLE "TSUNAMI_ENGINEERING_DATA"
		ADD CONSTRAINT "TSUNAMI_ENGINEERING_DATA_PK"
	PRIMARY KEY ("TSUNAMI_ENGINEERING_DATA_ID");
CREATE SEQUENCE "TSNM_NGNRNG_DT_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;

ALTER TABLE "TSUNAMI_ENGINEERING_DATA" ADD CONSTRAINT "TSUNAMI_ENGINEERING_DATA_FK_1" FOREIGN KEY ("TSUNAMI_DOC_LIB_ID") REFERENCES "TSUNAMI_DOC_LIB" ("TSUNAMI_DOC_LIB_ID");


/* -----------------------------------------------------------------------
   TSUNAMI_GEOLOGICAL_DATA
   ----------------------------------------------------------------------- */

DROP TABLE "TSUNAMI_GEOLOGICAL_DATA" CASCADE CONSTRAINTS;

DROP SEQUENCE "TSNM_GLGCL_DT_SEQ";


CREATE TABLE "TSUNAMI_GEOLOGICAL_DATA"
(
	"TSUNAMI_GEOLOGICAL_DATA_ID" NUMBER(22)  NOT NULL,
	"DISPLACEMENT" NUMBER(22),
	"DISPLACEMENT_SUBSIDENCE" NUMBER(22),
	"DISPLACEMENT_UPLIFT" NUMBER(22),
	"EIL" NUMBER(22),
	"EIL_CHARACTERISTICS" NUMBER(22),
	"EIL_DIST_INLAND" NUMBER(22),
	"EIL_ELEVATION" NUMBER(22),
	"FAULT" NUMBER(22),
	"FAULT_GEOMORPHIC" NUMBER(22),
	"FAULT_OFFSET" NUMBER(22),
	"FAULT_PALEO" NUMBER(22),
	"FAULT_STRIKE_MEASURE" NUMBER(22),
	"FAULT_TYPE" NUMBER(22),
	"GMCHANGES" NUMBER(22),
	"GMCHANGES_BED_MOD" NUMBER(22),
	"GMCHANGES_DEPOSIT" NUMBER(22),
	"GMCHANGES_SCOUR" NUMBER(22),
	"PALEO" NUMBER(22),
	"PALEO_CHARACTERISTICS" NUMBER(22),
	"PALEO_CORE_SAMPLES" NUMBER(22),
	"PALEO_DIST_INLAND" NUMBER(22),
	"PALEO_ELEVATION" NUMBER(22),
	"PALEO_OUTCROPS" NUMBER(22),
	"PALEO_SCALE" NUMBER(22),
	"PALEO_SED_PEELS" NUMBER(22),
	"PALEO_SPATIAL_VAR" NUMBER(22),
	"SMSL" NUMBER(22),
	"SSL_COEFFICIENT_OF_FRICTION" NUMBER(22),
	"SSL_DEPOSITS" NUMBER(22),
	"SSL_SCARS" NUMBER(22),
	"TDCBM" NUMBER(22),
	"TDCBM_CHARACTERISTICS" NUMBER(22),
	"TDCBM_DIST_INLAND" NUMBER(22),
	"TDCBM_ELEVATION" NUMBER(22),
	"TDCBM_SCALE" NUMBER(22),
	"TDCBM_SPATIAL_VAR" NUMBER(22),
	"TSUNAMI_DOC_LIB_ID" NUMBER(22)
);

	ALTER TABLE "TSUNAMI_GEOLOGICAL_DATA"
		ADD CONSTRAINT "TSUNAMI_GEOLOGICAL_DATA_PK"
	PRIMARY KEY ("TSUNAMI_GEOLOGICAL_DATA_ID");
CREATE SEQUENCE "TSNM_GLGCL_DT_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;

ALTER TABLE "TSUNAMI_GEOLOGICAL_DATA" ADD CONSTRAINT "TSUNAMI_GEOLOGICAL_DATA_FK_1" FOREIGN KEY ("TSUNAMI_DOC_LIB_ID") REFERENCES "TSUNAMI_DOC_LIB" ("TSUNAMI_DOC_LIB_ID");


/* -----------------------------------------------------------------------
   TSUNAMI_HYDRODYNAMIC_DATA
   ----------------------------------------------------------------------- */

DROP TABLE "TSUNAMI_HYDRODYNAMIC_DATA" CASCADE CONSTRAINTS;

DROP SEQUENCE "TSNM_HYDRDYNMC_DT_SEQ";


CREATE TABLE "TSUNAMI_HYDRODYNAMIC_DATA"
(
	"TSUNAMI_HYDRODYNAMIC_DATA_ID" NUMBER(22)  NOT NULL,
	"CONDITION_SEA" NUMBER(22),
	"CONDITION_SOURCE" NUMBER(22),
	"CONDITION_WEATHER" NUMBER(22),
	"CONDITION_WIND" NUMBER(22),
	"ECONDITION" NUMBER(22),
	"FLOW" NUMBER(22),
	"FLOW_DIRECTION" NUMBER(22),
	"FLOW_SOURCE" NUMBER(22),
	"FLOW_SPEED" NUMBER(22),
	"INUNDATION" NUMBER(22),
	"INUNDATION_DIST" NUMBER(22),
	"INUNDATION_QUALITY" NUMBER(22),
	"INUNDATION_SOURCE" NUMBER(22),
	"RUNUP" NUMBER(22),
	"RUNUP_ADJ_METHOD" NUMBER(22),
	"RUNUP_HEIGHT" NUMBER(22),
	"RUNUP_PORHEIGHT" NUMBER(22),
	"RUNUP_PORLOC" NUMBER(22),
	"RUNUP_QUALITY" NUMBER(22),
	"RUNUP_SOURCE" NUMBER(22),
	"RUNUP_TIDAL_ADJ" NUMBER(22),
	"TIDEGAUGE" NUMBER(22),
	"TIDEGAUGE_SOURCE" NUMBER(22),
	"TIDEGAUGE_TYPE" NUMBER(22),
	"TSUNAMI_DOC_LIB_ID" NUMBER(22),
	"WAVE" NUMBER(22),
	"WAVE_ARRIVAL_TIMES" NUMBER(22),
	"WAVE_FORM" NUMBER(22),
	"WAVE_HEIGHT" NUMBER(22),
	"WAVE_NUMBER" NUMBER(22),
	"WAVE_PERIOD" NUMBER(22),
	"WAVE_SOURCE" NUMBER(22),
	"WAVE_TIME_TO_NORM" NUMBER(22)
);

	ALTER TABLE "TSUNAMI_HYDRODYNAMIC_DATA"
		ADD CONSTRAINT "TSUNAMI_HYDRODYNAMIC_DATA_PK"
	PRIMARY KEY ("TSUNAMI_HYDRODYNAMIC_DATA_ID");
CREATE SEQUENCE "TSNM_HYDRDYNMC_DT_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;

ALTER TABLE "TSUNAMI_HYDRODYNAMIC_DATA" ADD CONSTRAINT "TSUNAMI_HYDRODYNAMIC_DATA_FK_1" FOREIGN KEY ("TSUNAMI_DOC_LIB_ID") REFERENCES "TSUNAMI_DOC_LIB" ("TSUNAMI_DOC_LIB_ID");


/* -----------------------------------------------------------------------
   TSUNAMI_PROJECT
   ----------------------------------------------------------------------- */

DROP TABLE "TSUNAMI_PROJECT" CASCADE CONSTRAINTS;

DROP SEQUENCE "TSUNAMI_PROJECT_SEQ";


CREATE TABLE "TSUNAMI_PROJECT"
(
	"TSUNAMI_PROJECT_ID" NUMBER(22)  NOT NULL,
	"CO_PI" VARCHAR2(1020),
	"CO_PI_INSTITUTION" VARCHAR2(400),
	"COLLABORATORS" VARCHAR2(1020),
	"CONTACT_EMAIL" VARCHAR2(1020),
	"CONTACT_NAME" VARCHAR2(1020),
	"DELETED" NUMBER(22),
	"DESCRIPTION" CLOB,
	"NAME" VARCHAR2(64),
	"NSF_TITLE" VARCHAR2(1020),
	"PI" VARCHAR2(1020),
	"PI_INSTITUTION" VARCHAR2(400),
	"PUBLIC_DATA" NUMBER(22),
	"SHORT_TITLE" VARCHAR2(400),
	"STATUS" VARCHAR2(400),
	"SYSADMIN_EMAIL" VARCHAR2(1020),
	"SYSADMIN_NAME" VARCHAR2(1020),
	"VIEWABLE" VARCHAR2(32)
);

	ALTER TABLE "TSUNAMI_PROJECT"
		ADD CONSTRAINT "TSUNAMI_PROJECT_PK"
	PRIMARY KEY ("TSUNAMI_PROJECT_ID");
CREATE SEQUENCE "TSUNAMI_PROJECT_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;


/* -----------------------------------------------------------------------
   TSUNAMI_SEISMIC_DATA
   ----------------------------------------------------------------------- */

DROP TABLE "TSUNAMI_SEISMIC_DATA" CASCADE CONSTRAINTS;

DROP SEQUENCE "TSUNAMI_SEISMIC_DATA_SEQ";


CREATE TABLE "TSUNAMI_SEISMIC_DATA"
(
	"TSUNAMI_SEISMIC_DATA_ID" NUMBER(22)  NOT NULL,
	"LOCAL" NUMBER(22),
	"LOCAL_DATA_SOURCES" NUMBER(22),
	"LOCAL_TYPE" NUMBER(22),
	"MEASURES" NUMBER(22),
	"MEASURES_SITE_CONFIG" NUMBER(22),
	"MEASURES_TYPES" NUMBER(22),
	"MIA" NUMBER(22),
	"MIA_SOURCE" NUMBER(22),
	"TSUNAMI_DOC_LIB_ID" NUMBER(22)
);

	ALTER TABLE "TSUNAMI_SEISMIC_DATA"
		ADD CONSTRAINT "TSUNAMI_SEISMIC_DATA_PK"
	PRIMARY KEY ("TSUNAMI_SEISMIC_DATA_ID");
CREATE SEQUENCE "TSUNAMI_SEISMIC_DATA_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;

ALTER TABLE "TSUNAMI_SEISMIC_DATA" ADD CONSTRAINT "TSUNAMI_SEISMIC_DATA_FK_1" FOREIGN KEY ("TSUNAMI_DOC_LIB_ID") REFERENCES "TSUNAMI_DOC_LIB" ("TSUNAMI_DOC_LIB_ID");


/* -----------------------------------------------------------------------
   TSUNAMI_SITE
   ----------------------------------------------------------------------- */

DROP TABLE "TSUNAMI_SITE" CASCADE CONSTRAINTS;

DROP SEQUENCE "TSUNAMI_SITE_SEQ";


CREATE TABLE "TSUNAMI_SITE"
(
	"TSUNAMI_SITE_ID" NUMBER(22)  NOT NULL,
	"BOUNDING_POLYGON" CLOB,
	"COUNTRY" VARCHAR2(1020),
	"DESCRIPTION" CLOB,
	"NAME" VARCHAR2(1020),
	"SITE_LAT" FLOAT(22),
	"SITE_LON" FLOAT(22),
	"TSUNAMI_PROJECT_ID" NUMBER(22),
	"TYPE" VARCHAR2(32)
);

	ALTER TABLE "TSUNAMI_SITE"
		ADD CONSTRAINT "TSUNAMI_SITE_PK"
	PRIMARY KEY ("TSUNAMI_SITE_ID");
CREATE SEQUENCE "TSUNAMI_SITE_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;

ALTER TABLE "TSUNAMI_SITE" ADD CONSTRAINT "TSUNAMI_SITE_FK_1" FOREIGN KEY ("TSUNAMI_PROJECT_ID") REFERENCES "TSUNAMI_PROJECT" ("TSUNAMI_PROJECT_ID");


/* -----------------------------------------------------------------------
   TSUNAMI_SITE_CONFIGURATION
   ----------------------------------------------------------------------- */

DROP TABLE "TSUNAMI_SITE_CONFIGURATION" CASCADE CONSTRAINTS;

DROP SEQUENCE "TSNM_ST_CNFGRTN_SEQ";


CREATE TABLE "TSUNAMI_SITE_CONFIGURATION"
(
	"TSUNAMI_SITE_CONFIGURATION_ID" NUMBER(22)  NOT NULL,
	"CONFIG_BATHYMETRY" NUMBER(22),
	"CONFIG_DESCRIPTION" NUMBER(22),
	"CONFIG_TOPOGRAPHY" NUMBER(22),
	"CONFIG_VISUALS" NUMBER(22),
	"TSUNAMI_DOC_LIB_ID" NUMBER(22)
);

	ALTER TABLE "TSUNAMI_SITE_CONFIGURATION"
		ADD CONSTRAINT "TSUNAMI_SITE_CONFIGURATION_PK"
	PRIMARY KEY ("TSUNAMI_SITE_CONFIGURATION_ID");
CREATE SEQUENCE "TSNM_ST_CNFGRTN_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;

ALTER TABLE "TSUNAMI_SITE_CONFIGURATION" ADD CONSTRAINT "TSUNAMI_SITE_CONFIGURATIO_FK_1" FOREIGN KEY ("TSUNAMI_DOC_LIB_ID") REFERENCES "TSUNAMI_DOC_LIB" ("TSUNAMI_DOC_LIB_ID");


/* -----------------------------------------------------------------------
   TSUNAMI_SITE_DOC_RELATIONSHIP
   ----------------------------------------------------------------------- */

DROP TABLE "TSUNAMI_SITE_DOC_RELATIONSHIP" CASCADE CONSTRAINTS;

DROP SEQUENCE "TSNM_ST_DC_RLTNSHP_SEQ";


CREATE TABLE "TSUNAMI_SITE_DOC_RELATIONSHIP"
(
	"ID" NUMBER default -1 NOT NULL,
	"TSUNAMI_DOC_LIB_ID" NUMBER(22),
	"TSUNAMI_SITE_ID" NUMBER(22)
);

	ALTER TABLE "TSUNAMI_SITE_DOC_RELATIONSHIP"
		ADD CONSTRAINT "TSUNAMI_SITE_DOC_RELATIONSH_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "TSNM_ST_DC_RLTNSHP_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;

ALTER TABLE "TSUNAMI_SITE_DOC_RELATIONSHIP" ADD CONSTRAINT "TSUNAMI_SITE_DOC_RELATION_FK_1" FOREIGN KEY ("TSUNAMI_DOC_LIB_ID") REFERENCES "TSUNAMI_DOC_LIB" ("TSUNAMI_DOC_LIB_ID");

ALTER TABLE "TSUNAMI_SITE_DOC_RELATIONSHIP" ADD CONSTRAINT "TSUNAMI_SITE_DOC_RELATION_FK_2" FOREIGN KEY ("TSUNAMI_SITE_ID") REFERENCES "TSUNAMI_SITE" ("TSUNAMI_SITE_ID");


/* -----------------------------------------------------------------------
   TSUNAMI_SOCIAL_SCIENCE_DATA
   ----------------------------------------------------------------------- */

DROP TABLE "TSUNAMI_SOCIAL_SCIENCE_DATA" CASCADE CONSTRAINTS;

DROP SEQUENCE "TSNM_SCL_SCNC_DT_SEQ";


CREATE TABLE "TSUNAMI_SOCIAL_SCIENCE_DATA"
(
	"TSUNAMI_SOCIAL_SCIENCE_DATA_ID" NUMBER(22)  NOT NULL,
	"BKG" NUMBER(22),
	"BKG_CENSUS" NUMBER(22),
	"BKG_LANGUAGE_ISSUES" NUMBER(22),
	"BKG_TOURIST_STATS" NUMBER(22),
	"BKG_TRANSPORT_SYSTEMS" NUMBER(22),
	"COMM" NUMBER(22),
	"COMM_INFO_FROMG" NUMBER(22),
	"COMM_WARN_SYS" NUMBER(22),
	"CRESPONSE" NUMBER(22),
	"CRESPONSE_INTERVW" NUMBER(22),
	"CRESPONSE_MITIGATION" NUMBER(22),
	"CRESPONSE_PREP" NUMBER(22),
	"CRESPONSE_RECOVERY" NUMBER(22),
	"CRESPONSE_WARNING" NUMBER(22),
	"DAMAGE" NUMBER(22),
	"DAMAGE_COST_EST" NUMBER(22),
	"DAMAGE_INDUSTRY" NUMBER(22),
	"DAMAGE_TYPE" NUMBER(22),
	"IMPACT" NUMBER(22),
	"IMPACT_NUM_DEAD" NUMBER(22),
	"IMPACT_NUM_FAM_SEP" NUMBER(22),
	"IMPACT_NUM_HOMELESS" NUMBER(22),
	"IMPACT_NUM_INJURED" NUMBER(22),
	"IMPACT_NUM_MISSING" NUMBER(22),
	"IRESPONSE" NUMBER(22),
	"IRESPONSE_INTERVW" NUMBER(22),
	"IRESPONSE_MITIGATION" NUMBER(22),
	"IRESPONSE_PREP" NUMBER(22),
	"IRESPONSE_RECOVERY" NUMBER(22),
	"IRESPONSE_WARNINGS" NUMBER(22),
	"ORESPONSE" NUMBER(22),
	"ORESPONSE_DISEASE" NUMBER(22),
	"ORESPONSE_GRELIEF" NUMBER(22),
	"ORESPONSE_INTERVW" NUMBER(22),
	"ORESPONSE_MITIGATION" NUMBER(22),
	"ORESPONSENGORELIEF" NUMBER(22),
	"ORESPONSE_PREP" NUMBER(22),
	"ORESPONSE_RECOVERY" NUMBER(22),
	"TSUNAMI_DOC_LIB_ID" NUMBER(22)
);

	ALTER TABLE "TSUNAMI_SOCIAL_SCIENCE_DATA"
		ADD CONSTRAINT "TSUNAMI_SOCIAL_SCIENCE_DATA_PK"
	PRIMARY KEY ("TSUNAMI_SOCIAL_SCIENCE_DATA_ID");
CREATE SEQUENCE "TSNM_SCL_SCNC_DT_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;

ALTER TABLE "TSUNAMI_SOCIAL_SCIENCE_DATA" ADD CONSTRAINT "TSUNAMI_SOCIAL_SCIENCE_DA_FK_1" FOREIGN KEY ("TSUNAMI_DOC_LIB_ID") REFERENCES "TSUNAMI_DOC_LIB" ("TSUNAMI_DOC_LIB_ID");
