

/* -----------------------------------------------------------------------
   ACKNOWLEDGEMENT
   ----------------------------------------------------------------------- */

DROP TABLE "ACKNOWLEDGEMENT" CASCADE CONSTRAINTS;

DROP SEQUENCE "ACKNOWLEDGEMENT_SEQ";


CREATE TABLE "ACKNOWLEDGEMENT"
(
	"ACKID" NUMBER(22)  NOT NULL,
	"EXPID" NUMBER(22),
	"HOW_TO_CITE" CLOB,
	"PROJID" NUMBER(22),
	"SPONSOR" VARCHAR2(4000),
	"TRIALID" NUMBER(22)
);

	ALTER TABLE "ACKNOWLEDGEMENT"
		ADD CONSTRAINT "ACKNOWLEDGEMENT_PK"
	PRIMARY KEY ("ACKID");
CREATE SEQUENCE "ACKNOWLEDGEMENT_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;

ALTER TABLE "ACKNOWLEDGEMENT" ADD CONSTRAINT "ACKNOWLEDGEMENT_FK_1" FOREIGN KEY ("EXPID") REFERENCES "EXPERIMENT" ("EXPID") ON DELETE CASCADE;

ALTER TABLE "ACKNOWLEDGEMENT" ADD CONSTRAINT "ACKNOWLEDGEMENT_FK_2" FOREIGN KEY ("PROJID") REFERENCES "PROJECT" ("PROJID") ON DELETE CASCADE;

ALTER TABLE "ACKNOWLEDGEMENT" ADD CONSTRAINT "ACKNOWLEDGEMENT_FK_3" FOREIGN KEY ("TRIALID") REFERENCES "TRIAL" ("TRIALID") ON DELETE CASCADE;


/* -----------------------------------------------------------------------
   ATTRIBUTE
   ----------------------------------------------------------------------- */

DROP TABLE "ATTRIBUTE" CASCADE CONSTRAINTS;

DROP SEQUENCE "ATTRIBUTE_SEQ";


CREATE TABLE "ATTRIBUTE"
(
	"ATTRIBUTE_ID" NUMBER(22)  NOT NULL,
	"DATA_TYPE" VARCHAR2(28),
	"DESCRIPTION" VARCHAR2(1020),
	"EQUIPMENT_CLASS_ID" NUMBER(22),
	"LABEL" VARCHAR2(512),
	"MAX_VALUE" FLOAT(22),
	"MIN_VALUE" FLOAT(22),
	"NAME" VARCHAR2(256),
	"UNIT_ID" NUMBER(22)
);

	ALTER TABLE "ATTRIBUTE"
		ADD CONSTRAINT "ATTRIBUTE_PK"
	PRIMARY KEY ("ATTRIBUTE_ID");
CREATE SEQUENCE "ATTRIBUTE_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;

ALTER TABLE "ATTRIBUTE" ADD CONSTRAINT "ATTRIBUTE_FK_1" FOREIGN KEY ("EQUIPMENT_CLASS_ID") REFERENCES "EQUIPMENT_CLASS" ("EQUIPMENT_CLASS_ID") ON DELETE SET NULL;

ALTER TABLE "ATTRIBUTE" ADD CONSTRAINT "ATTRIBUTE_FK_2" FOREIGN KEY ("UNIT_ID") REFERENCES "UNIT" ("UNIT_ID") ON DELETE CASCADE;


/* -----------------------------------------------------------------------
   AUTHORIZATION
   ----------------------------------------------------------------------- */

DROP TABLE "AUTHORIZATION" CASCADE CONSTRAINTS;

DROP SEQUENCE "AUTHORIZATION_SEQ";


CREATE TABLE "AUTHORIZATION"
(
	"ID" NUMBER(22)  NOT NULL,
	"ENTITY_ID" NUMBER(22),
	"ENTITY_TYPE_ID" NUMBER(22),
	"PERMISSIONS" VARCHAR2(112),
	"PERSON_ID" NUMBER(22)
);

	ALTER TABLE "AUTHORIZATION"
		ADD CONSTRAINT "AUTHORIZATION_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "AUTHORIZATION_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;

ALTER TABLE "AUTHORIZATION" ADD CONSTRAINT "AUTHORIZATION_FK_1" FOREIGN KEY ("ENTITY_TYPE_ID") REFERENCES "ENTITY_TYPE" ("ID") ON DELETE CASCADE;

ALTER TABLE "AUTHORIZATION" ADD CONSTRAINT "AUTHORIZATION_FK_2" FOREIGN KEY ("PERSON_ID") REFERENCES "PERSON" ("ID") ON DELETE CASCADE;


/* -----------------------------------------------------------------------
   CALIBRATION
   ----------------------------------------------------------------------- */

DROP TABLE "CALIBRATION" CASCADE CONSTRAINTS;

DROP SEQUENCE "CALIBRATION_SEQ";


CREATE TABLE "CALIBRATION"
(
	"CALIB_ID" NUMBER(22)  NOT NULL,
	"ADJUSTMENTS" FLOAT(22),
	"CALIB_DATE" DATE,
	"CALIB_FACTOR" VARCHAR2(400),
	"CALIB_FACTOR_UNITS" VARCHAR2(40),
	"CALIBRATOR" VARCHAR2(200),
	"DELETED" NUMBER(22),
	"DESCRIPTION" VARCHAR2(1020),
	"MAX_MEASURED_VALUE" FLOAT(22),
	"MEASURED_VALUE_UNITS" VARCHAR2(40),
	"MIN_MEASURED_VALUE" FLOAT(22),
	"REFERENCE" FLOAT(22),
	"REFERENCE_UNITS" VARCHAR2(40),
	"SENSITIVITY" FLOAT(22),
	"SENSITIVITY_UNITS" VARCHAR2(40),
	"SENSOR_ID" NUMBER(22)
);

	ALTER TABLE "CALIBRATION"
		ADD CONSTRAINT "CALIBRATION_PK"
	PRIMARY KEY ("CALIB_ID");
CREATE SEQUENCE "CALIBRATION_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;

ALTER TABLE "CALIBRATION" ADD CONSTRAINT "CALIBRATION_FK_1" FOREIGN KEY ("SENSOR_ID") REFERENCES "SENSOR" ("SENSOR_ID") ON DELETE CASCADE;


/* -----------------------------------------------------------------------
   CONTROLLER_CHANNEL
   ----------------------------------------------------------------------- */

DROP TABLE "CONTROLLER_CHANNEL" CASCADE CONSTRAINTS;

DROP SEQUENCE "CONTROLLER_CHANNEL_SEQ";


CREATE TABLE "CONTROLLER_CHANNEL"
(
	"ID" NUMBER(22)  NOT NULL,
	"CONTROLLER_CONFIG_ID" NUMBER(22),
	"DATA_FILE_ID" NUMBER(22),
	"DESCRIPTION" CLOB,
	"DIRECTION" VARCHAR2(400),
	"EQUIPMENT_ID" NUMBER(22),
	"NAME" VARCHAR2(400)  NOT NULL,
	"SOURCE_LOCATION_ID" NUMBER(22)  NOT NULL,
	"STATION" VARCHAR2(400)
);

	ALTER TABLE "CONTROLLER_CHANNEL"
		ADD CONSTRAINT "CONTROLLER_CHANNEL_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "CONTROLLER_CHANNEL_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;

ALTER TABLE "CONTROLLER_CHANNEL" ADD CONSTRAINT "CONTROLLER_CHANNEL_FK_1" FOREIGN KEY ("CONTROLLER_CONFIG_ID") REFERENCES "CONTROLLER_CONFIG" ("ID") ON DELETE CASCADE;

ALTER TABLE "CONTROLLER_CHANNEL" ADD CONSTRAINT "CONTROLLER_CHANNEL_FK_2" FOREIGN KEY ("DATA_FILE_ID") REFERENCES "DATA_FILE" ("ID") ON DELETE SET NULL;

ALTER TABLE "CONTROLLER_CHANNEL" ADD CONSTRAINT "CONTROLLER_CHANNEL_FK_3" FOREIGN KEY ("EQUIPMENT_ID") REFERENCES "EQUIPMENT" ("EQUIPMENT_ID") ON DELETE CASCADE;

ALTER TABLE "CONTROLLER_CHANNEL" ADD CONSTRAINT "CONTROLLER_CHANNEL_FK_4" FOREIGN KEY ("SOURCE_LOCATION_ID") REFERENCES "LOCATION" ("ID") ON DELETE CASCADE;


/* -----------------------------------------------------------------------
   CONTROLLER_CHANNEL_EQUIPMENT
   ----------------------------------------------------------------------- */

DROP TABLE "CONTROLLER_CHANNEL_EQUIPMENT" CASCADE CONSTRAINTS;

DROP SEQUENCE "CNTRLLR_CHNNL_QPMNT_SEQ";


CREATE TABLE "CONTROLLER_CHANNEL_EQUIPMENT"
(
	"ID" NUMBER(22)  NOT NULL,
	"CONTROLLER_CHANNEL_ID" NUMBER(22),
	"DESCRIPTION" CLOB,
	"EQUIPMENT_ID" NUMBER(22),
	"TYPE" VARCHAR2(128)
);

	ALTER TABLE "CONTROLLER_CHANNEL_EQUIPMENT"
		ADD CONSTRAINT "CONTROLLER_CHANNEL_EQUIPMEN_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "CNTRLLR_CHNNL_QPMNT_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;

ALTER TABLE "CONTROLLER_CHANNEL_EQUIPMENT" ADD CONSTRAINT "CONTROLLER_CHANNEL_EQUIPM_FK_1" FOREIGN KEY ("CONTROLLER_CHANNEL_ID") REFERENCES "CONTROLLER_CHANNEL" ("ID") ON DELETE CASCADE;

ALTER TABLE "CONTROLLER_CHANNEL_EQUIPMENT" ADD CONSTRAINT "CONTROLLER_CHANNEL_EQUIPM_FK_2" FOREIGN KEY ("EQUIPMENT_ID") REFERENCES "EQUIPMENT" ("EQUIPMENT_ID") ON DELETE CASCADE;


/* -----------------------------------------------------------------------
   CONTROLLER_CONFIG
   ----------------------------------------------------------------------- */

DROP TABLE "CONTROLLER_CONFIG" CASCADE CONSTRAINTS;

DROP SEQUENCE "CONTROLLER_CONFIG_SEQ";


CREATE TABLE "CONTROLLER_CONFIG"
(
	"ID" NUMBER(22)  NOT NULL,
	"CONFIG_DATA_FILE_ID" NUMBER(22),
	"DESCRIPTION" CLOB,
	"EQUIPMENT_ID" NUMBER(22),
	"INPUT_DATA_FILE_ID" NUMBER(22),
	"NAME" VARCHAR2(200),
	"PEAK_BASE_ACCELERATION" FLOAT(22),
	"PEAK_BASE_ACCELERATION_UNIT_ID" NUMBER(22),
	"TRIAL_ID" NUMBER(22)
);

	ALTER TABLE "CONTROLLER_CONFIG"
		ADD CONSTRAINT "CONTROLLER_CONFIG_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "CONTROLLER_CONFIG_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;

ALTER TABLE "CONTROLLER_CONFIG" ADD CONSTRAINT "CONTROLLER_CONFIG_FK_1" FOREIGN KEY ("INPUT_DATA_FILE_ID") REFERENCES "DATA_FILE" ("ID") ON DELETE SET NULL;

ALTER TABLE "CONTROLLER_CONFIG" ADD CONSTRAINT "CONTROLLER_CONFIG_FK_2" FOREIGN KEY ("CONFIG_DATA_FILE_ID") REFERENCES "DATA_FILE" ("ID") ON DELETE SET NULL;

ALTER TABLE "CONTROLLER_CONFIG" ADD CONSTRAINT "CONTROLLER_CONFIG_FK_3" FOREIGN KEY ("EQUIPMENT_ID") REFERENCES "EQUIPMENT" ("EQUIPMENT_ID") ON DELETE SET NULL;

ALTER TABLE "CONTROLLER_CONFIG" ADD CONSTRAINT "CONTROLLER_CONFIG_FK_4" FOREIGN KEY ("PEAK_BASE_ACCELERATION_UNIT_ID") REFERENCES "MEASUREMENT_UNIT" ("ID") ON DELETE SET NULL;

ALTER TABLE "CONTROLLER_CONFIG" ADD CONSTRAINT "CONTROLLER_CONFIG_FK_5" FOREIGN KEY ("TRIAL_ID") REFERENCES "TRIAL" ("TRIALID") ON DELETE CASCADE;


/* -----------------------------------------------------------------------
   COORDINATE_DIMENSION
   ----------------------------------------------------------------------- */

DROP TABLE "COORDINATE_DIMENSION" CASCADE CONSTRAINTS;

DROP SEQUENCE "COORDINATE_DIMENSION_SEQ";


CREATE TABLE "COORDINATE_DIMENSION"
(
	"ID" NUMBER(22)  NOT NULL,
	"NAME" VARCHAR2(1020),
	"UNIT_CATEGORY_ID" NUMBER(22)
);

	ALTER TABLE "COORDINATE_DIMENSION"
		ADD CONSTRAINT "COORDINATE_DIMENSION_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "COORDINATE_DIMENSION_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;

ALTER TABLE "COORDINATE_DIMENSION" ADD CONSTRAINT "COORDINATE_DIMENSION_FK_1" FOREIGN KEY ("UNIT_CATEGORY_ID") REFERENCES "MEASUREMENT_UNIT_CATEGORY" ("ID") ON DELETE SET NULL;


/* -----------------------------------------------------------------------
   COORDINATE_SPACE
   ----------------------------------------------------------------------- */

DROP TABLE "COORDINATE_SPACE" CASCADE CONSTRAINTS;

DROP SEQUENCE "COORDINATE_SPACE_SEQ";


CREATE TABLE "COORDINATE_SPACE"
(
	"ID" NUMBER(22)  NOT NULL,
	"ALTITUDE" FLOAT(22),
	"ALTITUDE_UNIT" NUMBER(22),
	"DATE_CREATED" DATE,
	"DESCRIPTION" CLOB,
	"EXPID" NUMBER(22),
	"LATITUDE" FLOAT(22),
	"LONGITUDE" FLOAT(22),
	"NAME" VARCHAR2(200),
	"PARENT_ID" NUMBER(22),
	"ROTATIONX" FLOAT(22),
	"ROTATIONXUNIT_ID" NUMBER(22),
	"ROTATIONY" FLOAT(22),
	"ROTATIONYUNIT_ID" NUMBER(22),
	"ROTATIONZ" FLOAT(22),
	"ROTATIONZUNIT_ID" NUMBER(22),
	"SCALE" FLOAT(22),
	"SYSTEM_ID" NUMBER(22),
	"TRANSLATIONX" FLOAT(22),
	"TRANSLATIONXUNIT_ID" NUMBER(22),
	"TRANSLATIONY" FLOAT(22),
	"TRANSLATIONYUNIT_ID" NUMBER(22),
	"TRANSLATIONZ" FLOAT(22),
	"TRANSLATIONZUNIT_ID" NUMBER(22)
);

	ALTER TABLE "COORDINATE_SPACE"
		ADD CONSTRAINT "COORDINATE_SPACE_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "COORDINATE_SPACE_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;

ALTER TABLE "COORDINATE_SPACE" ADD CONSTRAINT "COORDINATE_SPACE_FK_1" FOREIGN KEY ("PARENT_ID") REFERENCES "COORDINATE_SPACE" ("ID") ON DELETE CASCADE;

ALTER TABLE "COORDINATE_SPACE" ADD CONSTRAINT "COORDINATE_SPACE_FK_2" FOREIGN KEY ("SYSTEM_ID") REFERENCES "COORDINATE_SYSTEM" ("ID") ON DELETE SET NULL;

ALTER TABLE "COORDINATE_SPACE" ADD CONSTRAINT "COORDINATE_SPACE_FK_3" FOREIGN KEY ("EXPID") REFERENCES "EXPERIMENT" ("EXPID") ON DELETE CASCADE;

ALTER TABLE "COORDINATE_SPACE" ADD CONSTRAINT "COORDINATE_SPACE_FK_4" FOREIGN KEY ("TRANSLATIONXUNIT_ID") REFERENCES "MEASUREMENT_UNIT" ("ID") ON DELETE CASCADE;

ALTER TABLE "COORDINATE_SPACE" ADD CONSTRAINT "COORDINATE_SPACE_FK_5" FOREIGN KEY ("TRANSLATIONYUNIT_ID") REFERENCES "MEASUREMENT_UNIT" ("ID") ON DELETE CASCADE;

ALTER TABLE "COORDINATE_SPACE" ADD CONSTRAINT "COORDINATE_SPACE_FK_6" FOREIGN KEY ("ROTATIONZUNIT_ID") REFERENCES "MEASUREMENT_UNIT" ("ID") ON DELETE CASCADE;

ALTER TABLE "COORDINATE_SPACE" ADD CONSTRAINT "COORDINATE_SPACE_FK_7" FOREIGN KEY ("ALTITUDE_UNIT") REFERENCES "MEASUREMENT_UNIT" ("ID") ON DELETE SET NULL;

ALTER TABLE "COORDINATE_SPACE" ADD CONSTRAINT "COORDINATE_SPACE_FK_8" FOREIGN KEY ("ROTATIONYUNIT_ID") REFERENCES "MEASUREMENT_UNIT" ("ID") ON DELETE CASCADE;

ALTER TABLE "COORDINATE_SPACE" ADD CONSTRAINT "COORDINATE_SPACE_FK_9" FOREIGN KEY ("TRANSLATIONZUNIT_ID") REFERENCES "MEASUREMENT_UNIT" ("ID") ON DELETE CASCADE;

ALTER TABLE "COORDINATE_SPACE" ADD CONSTRAINT "COORDINATE_SPACE_FK_10" FOREIGN KEY ("ROTATIONXUNIT_ID") REFERENCES "MEASUREMENT_UNIT" ("ID") ON DELETE CASCADE;


/* -----------------------------------------------------------------------
   COORDINATE_SPACE_DATA_FILE
   ----------------------------------------------------------------------- */

DROP TABLE "COORDINATE_SPACE_DATA_FILE" CASCADE CONSTRAINTS;

DROP SEQUENCE "CRDNT_SPC_DT_FL_SEQ";


CREATE TABLE "COORDINATE_SPACE_DATA_FILE"
(
	"ID" NUMBER(22)  NOT NULL,
	"COMMENTS" VARCHAR2(1020),
	"COORDINATE_SPACE_ID" NUMBER(22),
	"DATA_FILE_ID" NUMBER(22)
);

	ALTER TABLE "COORDINATE_SPACE_DATA_FILE"
		ADD CONSTRAINT "COORDINATE_SPACE_DATA_FILE_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "CRDNT_SPC_DT_FL_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;

ALTER TABLE "COORDINATE_SPACE_DATA_FILE" ADD CONSTRAINT "COORDINATE_SPACE_DATA_FIL_FK_1" FOREIGN KEY ("COORDINATE_SPACE_ID") REFERENCES "COORDINATE_SPACE" ("ID") ON DELETE CASCADE;

ALTER TABLE "COORDINATE_SPACE_DATA_FILE" ADD CONSTRAINT "COORDINATE_SPACE_DATA_FIL_FK_2" FOREIGN KEY ("DATA_FILE_ID") REFERENCES "DATA_FILE" ("ID") ON DELETE CASCADE;


/* -----------------------------------------------------------------------
   COORDINATE_SYSTEM
   ----------------------------------------------------------------------- */

DROP TABLE "COORDINATE_SYSTEM" CASCADE CONSTRAINTS;

DROP SEQUENCE "COORDINATE_SYSTEM_SEQ";


CREATE TABLE "COORDINATE_SYSTEM"
(
	"ID" NUMBER(22)  NOT NULL,
	"DIM1" NUMBER(22),
	"DIM2" NUMBER(22),
	"DIM3" NUMBER(22),
	"NAME" VARCHAR2(200)
);

	ALTER TABLE "COORDINATE_SYSTEM"
		ADD CONSTRAINT "COORDINATE_SYSTEM_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "COORDINATE_SYSTEM_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;

ALTER TABLE "COORDINATE_SYSTEM" ADD CONSTRAINT "COORDINATE_SYSTEM_FK_1" FOREIGN KEY ("DIM1") REFERENCES "COORDINATE_DIMENSION" ("ID") ON DELETE CASCADE;

ALTER TABLE "COORDINATE_SYSTEM" ADD CONSTRAINT "COORDINATE_SYSTEM_FK_2" FOREIGN KEY ("DIM3") REFERENCES "COORDINATE_DIMENSION" ("ID") ON DELETE CASCADE;

ALTER TABLE "COORDINATE_SYSTEM" ADD CONSTRAINT "COORDINATE_SYSTEM_FK_3" FOREIGN KEY ("DIM2") REFERENCES "COORDINATE_DIMENSION" ("ID") ON DELETE CASCADE;


/* -----------------------------------------------------------------------
   DAQCHANNEL
   ----------------------------------------------------------------------- */

DROP TABLE "DAQCHANNEL" CASCADE CONSTRAINTS;

DROP SEQUENCE "DAQCHANNEL_SEQ";


CREATE TABLE "DAQCHANNEL"
(
	"ID" NUMBER(22)  NOT NULL,
	"ADCRANGE" FLOAT(22),
	"ADCRESOLUTION" FLOAT(22),
	"CHANNEL_ORDER" NUMBER(22)  NOT NULL,
	"DAQCONFIG_ID" NUMBER(22)  NOT NULL,
	"DATA_FILE_ID" NUMBER(22),
	"DESCRIPTION" CLOB,
	"EXCITATION" FLOAT(22),
	"GAIN" FLOAT(22),
	"NAME" VARCHAR2(400),
	"SENSOR_ID" NUMBER(22),
	"SENSOR_LOCATION_ID" NUMBER(22)  NOT NULL
);

	ALTER TABLE "DAQCHANNEL"
		ADD CONSTRAINT "DAQCHANNEL_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "DAQCHANNEL_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;

ALTER TABLE "DAQCHANNEL" ADD CONSTRAINT "DAQCHANNEL_FK_1" FOREIGN KEY ("DAQCONFIG_ID") REFERENCES "DAQCONFIG" ("ID") ON DELETE CASCADE;

ALTER TABLE "DAQCHANNEL" ADD CONSTRAINT "DAQCHANNEL_FK_2" FOREIGN KEY ("DATA_FILE_ID") REFERENCES "DATA_FILE" ("ID") ON DELETE SET NULL;

ALTER TABLE "DAQCHANNEL" ADD CONSTRAINT "DAQCHANNEL_FK_3" FOREIGN KEY ("SENSOR_LOCATION_ID") REFERENCES "LOCATION" ("ID") ON DELETE CASCADE;

ALTER TABLE "DAQCHANNEL" ADD CONSTRAINT "DAQCHANNEL_FK_4" FOREIGN KEY ("SENSOR_ID") REFERENCES "SENSOR" ("SENSOR_ID") ON DELETE SET NULL;


/* -----------------------------------------------------------------------
   DAQCHANNEL_EQUIPMENT
   ----------------------------------------------------------------------- */

DROP TABLE "DAQCHANNEL_EQUIPMENT" CASCADE CONSTRAINTS;

DROP SEQUENCE "DAQCHANNEL_EQUIPMENT_SEQ";


CREATE TABLE "DAQCHANNEL_EQUIPMENT"
(
	"ID" NUMBER(22)  NOT NULL,
	"DAQCHANNEL_ID" NUMBER(22),
	"DESCRIPTION" CLOB,
	"EQUIPMENT_ID" NUMBER(22),
	"TYPE" VARCHAR2(128)
);

	ALTER TABLE "DAQCHANNEL_EQUIPMENT"
		ADD CONSTRAINT "DAQCHANNEL_EQUIPMENT_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "DAQCHANNEL_EQUIPMENT_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;

ALTER TABLE "DAQCHANNEL_EQUIPMENT" ADD CONSTRAINT "DAQCHANNEL_EQUIPMENT_FK_1" FOREIGN KEY ("DAQCHANNEL_ID") REFERENCES "DAQCHANNEL" ("ID") ON DELETE CASCADE;

ALTER TABLE "DAQCHANNEL_EQUIPMENT" ADD CONSTRAINT "DAQCHANNEL_EQUIPMENT_FK_2" FOREIGN KEY ("EQUIPMENT_ID") REFERENCES "EQUIPMENT" ("EQUIPMENT_ID") ON DELETE CASCADE;


/* -----------------------------------------------------------------------
   DAQCHANNEL_OUTPUT
   ----------------------------------------------------------------------- */

DROP TABLE "DAQCHANNEL_OUTPUT" CASCADE CONSTRAINTS;

DROP SEQUENCE "DAQCHANNEL_OUTPUT_SEQ";


CREATE TABLE "DAQCHANNEL_OUTPUT"
(
	"ID" NUMBER(22)  NOT NULL,
	"DAQCHANNEL_ID" NUMBER(22),
	"TIME" FLOAT(22)
);

	ALTER TABLE "DAQCHANNEL_OUTPUT"
		ADD CONSTRAINT "DAQCHANNEL_OUTPUT_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "DAQCHANNEL_OUTPUT_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;

ALTER TABLE "DAQCHANNEL_OUTPUT" ADD CONSTRAINT "DAQCHANNEL_OUTPUT_FK_1" FOREIGN KEY ("DAQCHANNEL_ID") REFERENCES "DAQCHANNEL" ("ID") ON DELETE CASCADE;


/* -----------------------------------------------------------------------
   DAQCONFIG
   ----------------------------------------------------------------------- */

DROP TABLE "DAQCONFIG" CASCADE CONSTRAINTS;

DROP SEQUENCE "DAQCONFIG_SEQ";


CREATE TABLE "DAQCONFIG"
(
	"ID" NUMBER(22)  NOT NULL,
	"CONFIG_DATA_FILE_ID" NUMBER(22),
	"DESCRIPTION" CLOB,
	"EQUIPMENT_ID" NUMBER(22),
	"NAME" VARCHAR2(200),
	"OUTPUT_DATA_FILE_ID" NUMBER(22),
	"TRIAL_ID" NUMBER(22)
);

	ALTER TABLE "DAQCONFIG"
		ADD CONSTRAINT "DAQCONFIG_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "DAQCONFIG_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;

ALTER TABLE "DAQCONFIG" ADD CONSTRAINT "DAQCONFIG_FK_1" FOREIGN KEY ("OUTPUT_DATA_FILE_ID") REFERENCES "DATA_FILE" ("ID") ON DELETE SET NULL;

ALTER TABLE "DAQCONFIG" ADD CONSTRAINT "DAQCONFIG_FK_2" FOREIGN KEY ("CONFIG_DATA_FILE_ID") REFERENCES "DATA_FILE" ("ID") ON DELETE SET NULL;

ALTER TABLE "DAQCONFIG" ADD CONSTRAINT "DAQCONFIG_FK_3" FOREIGN KEY ("EQUIPMENT_ID") REFERENCES "EQUIPMENT" ("EQUIPMENT_ID") ON DELETE CASCADE;

ALTER TABLE "DAQCONFIG" ADD CONSTRAINT "DAQCONFIG_FK_4" FOREIGN KEY ("TRIAL_ID") REFERENCES "TRIAL" ("TRIALID") ON DELETE CASCADE;


/* -----------------------------------------------------------------------
   DATA_FILE
   ----------------------------------------------------------------------- */

DROP TABLE "DATA_FILE" CASCADE CONSTRAINTS;

DROP SEQUENCE "DATA_FILE_SEQ";


CREATE TABLE "DATA_FILE"
(
	"ID" NUMBER(22)  NOT NULL,
	"AUTHOR_EMAILS" VARCHAR2(1020),
	"AUTHORS" VARCHAR2(1020),
	"CHECKSUM" VARCHAR2(128),
	"CREATED" DATE,
	"CURATION_STATUS" VARCHAR2(40) default 'Uncurated',
	"DELETED" NUMBER(22) default false,
	"DESCRIPTION" CLOB,
	"DIRECTORY" NUMBER(22) default false,
	"FILESIZE" NUMBER(22),
	"HOW_TO_CITE" VARCHAR2(1020),
	"NAME" VARCHAR2(1020),
	"PAGE_COUNT" NUMBER(22),
	"PATH" VARCHAR2(1020),
	"TITLE" VARCHAR2(1020),
	"VIEWABLE" VARCHAR2(32) default 'MEMBERS',
	"THUMB_ID" NUMBER(22),
	"DOCUMENT_FORMAT_ID" NUMBER(22),
	"OPENING_TOOL" VARCHAR2(200),
	"USAGE_TYPE_ID" NUMBER(22)
);

	ALTER TABLE "DATA_FILE"
		ADD CONSTRAINT "DATA_FILE_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "DATA_FILE_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;

ALTER TABLE "DATA_FILE" ADD CONSTRAINT "DATA_FILE_FK_1" FOREIGN KEY ("THUMB_ID") REFERENCES "DATA_FILE" ("ID") ON DELETE SET NULL;

ALTER TABLE "DATA_FILE" ADD CONSTRAINT "DATA_FILE_FK_2" FOREIGN KEY ("DOCUMENT_FORMAT_ID") REFERENCES "DOCUMENT_FORMAT" ("DOCUMENT_FORMAT_ID") ON DELETE CASCADE;

ALTER TABLE "DATA_FILE" ADD CONSTRAINT "DATA_FILE_FK_3" FOREIGN KEY ("USAGE_TYPE_ID") REFERENCES "ENTITY_TYPE" ("ID") ON DELETE SET NULL;


/* -----------------------------------------------------------------------
   DOC_LIB
   ----------------------------------------------------------------------- */

DROP TABLE "DOC_LIB" CASCADE CONSTRAINTS;

DROP SEQUENCE "DOC_LIB_SEQ";


CREATE TABLE "DOC_LIB"
(
	"DOCID" NUMBER(22)  NOT NULL,
	"AUTHOR_EMAILS" VARCHAR2(1020),
	"AUTHORS" VARCHAR2(1020),
	"DESCRIPTION" CLOB,
	"HOW_TO_CITE" VARCHAR2(1020),
	"NAME" VARCHAR2(1020),
	"PARENT" VARCHAR2(1020),
	"TITLE" VARCHAR2(1020)
);

	ALTER TABLE "DOC_LIB"
		ADD CONSTRAINT "DOC_LIB_PK"
	PRIMARY KEY ("DOCID");
CREATE SEQUENCE "DOC_LIB_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;


/* -----------------------------------------------------------------------
   DOCUMENT_FORMAT
   ----------------------------------------------------------------------- */

DROP TABLE "DOCUMENT_FORMAT" CASCADE CONSTRAINTS;

DROP SEQUENCE "DOCUMENT_FORMAT_SEQ";


CREATE TABLE "DOCUMENT_FORMAT"
(
	"DOCUMENT_FORMAT_ID" NUMBER(22)  NOT NULL,
	"DEFAULT_EXTENSION" VARCHAR2(320),
	"FORMAT" VARCHAR2(64),
	"MIME_TYPE" VARCHAR2(320)
);

	ALTER TABLE "DOCUMENT_FORMAT"
		ADD CONSTRAINT "DOCUMENT_FORMAT_PK"
	PRIMARY KEY ("DOCUMENT_FORMAT_ID");
CREATE SEQUENCE "DOCUMENT_FORMAT_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;


/* -----------------------------------------------------------------------
   DOCUMENT_TYPE
   ----------------------------------------------------------------------- */

DROP TABLE "DOCUMENT_TYPE" CASCADE CONSTRAINTS;

DROP SEQUENCE "DOCUMENT_TYPE_SEQ";


CREATE TABLE "DOCUMENT_TYPE"
(
	"DOCUMENT_TYPE_ID" NUMBER(22)  NOT NULL,
	"NAME" VARCHAR2(256),
	"PREFERRED_FORMAT" VARCHAR2(256)
);

	ALTER TABLE "DOCUMENT_TYPE"
		ADD CONSTRAINT "DOCUMENT_TYPE_PK"
	PRIMARY KEY ("DOCUMENT_TYPE_ID");
CREATE SEQUENCE "DOCUMENT_TYPE_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;


/* -----------------------------------------------------------------------
   ELEMENT_TYPE
   ----------------------------------------------------------------------- */

DROP TABLE "ELEMENT_TYPE" CASCADE CONSTRAINTS;

DROP SEQUENCE "ELEMENT_TYPE_SEQ";


CREATE TABLE "ELEMENT_TYPE"
(
	"ID" NUMBER(22)  NOT NULL,
	"NAME" VARCHAR2(400)
);

	ALTER TABLE "ELEMENT_TYPE"
		ADD CONSTRAINT "ELEMENT_TYPE_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "ELEMENT_TYPE_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;


/* -----------------------------------------------------------------------
   ENTITY_TYPE
   ----------------------------------------------------------------------- */

DROP TABLE "ENTITY_TYPE" CASCADE CONSTRAINTS;

DROP SEQUENCE "ENTITY_TYPE_SEQ";


CREATE TABLE "ENTITY_TYPE"
(
	"ID" NUMBER(22)  NOT NULL,
	"CLASS_NAME" VARCHAR2(1020),
	"N_TABLE_NAME" VARCHAR2(1020),
	"TABLE_ID_COLUMN" VARCHAR2(1020)
);

	ALTER TABLE "ENTITY_TYPE"
		ADD CONSTRAINT "ENTITY_TYPE_PK"
	PRIMARY KEY ("ID");
CREATE INDEX "SYS_C0040591" ON "ENTITY_TYPE" ("N_TABLE_NAME");
CREATE INDEX "SYS_C0040592" ON "ENTITY_TYPE" ("CLASS_NAME");
CREATE SEQUENCE "ENTITY_TYPE_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;
CREATE INDEX "SYS_C0040591" ON "ENTITY_TYPE" ("N_TABLE_NAME");
CREATE INDEX "SYS_C0040592" ON "ENTITY_TYPE" ("CLASS_NAME");


/* -----------------------------------------------------------------------
   EQUIPMENT
   ----------------------------------------------------------------------- */

DROP TABLE "EQUIPMENT" CASCADE CONSTRAINTS;

DROP SEQUENCE "EQUIPMENT_SEQ";


CREATE TABLE "EQUIPMENT"
(
	"EQUIPMENT_ID" NUMBER(22)  NOT NULL,
	"CALIBRATION_INFORMATION" VARCHAR2(1020),
	"COMMISSION_DATE" DATE,
	"DELETED" NUMBER(22),
	"LAB_ASSIGNED_ID" VARCHAR2(1020),
	"MAJOR" NUMBER(22),
	"MODEL_ID" NUMBER(22),
	"NAME" VARCHAR2(512),
	"NEES_OPERATED" VARCHAR2(36),
	"NOTE" CLOB,
	"ORGID" NUMBER(22),
	"OWNER" VARCHAR2(512),
	"PARENT_ID" NUMBER(22),
	"QUANTITY" NUMBER(22),
	"SEPARATE_SCHEDULING" NUMBER(22),
	"SERIAL_NUMBER" VARCHAR2(1020)
);

	ALTER TABLE "EQUIPMENT"
		ADD CONSTRAINT "EQUIPMENT_PK"
	PRIMARY KEY ("EQUIPMENT_ID");
CREATE SEQUENCE "EQUIPMENT_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;

ALTER TABLE "EQUIPMENT" ADD CONSTRAINT "EQUIPMENT_FK_1" FOREIGN KEY ("PARENT_ID") REFERENCES "EQUIPMENT" ("EQUIPMENT_ID") ON DELETE CASCADE;

ALTER TABLE "EQUIPMENT" ADD CONSTRAINT "EQUIPMENT_FK_2" FOREIGN KEY ("MODEL_ID") REFERENCES "EQUIPMENT_MODEL" ("ID") ON DELETE CASCADE;

ALTER TABLE "EQUIPMENT" ADD CONSTRAINT "EQUIPMENT_FK_3" FOREIGN KEY ("ORGID") REFERENCES "ORGANIZATION" ("ORGID") ON DELETE CASCADE;


/* -----------------------------------------------------------------------
   EQUIPMENT_ATTRIBUTE
   ----------------------------------------------------------------------- */

DROP TABLE "EQUIPMENT_ATTRIBUTE" CASCADE CONSTRAINTS;

DROP SEQUENCE "EQUIPMENT_ATTRIBUTE_SEQ";


CREATE TABLE "EQUIPMENT_ATTRIBUTE"
(
	"ID" NUMBER(22)  NOT NULL,
	"DATA_TYPE" VARCHAR2(28),
	"DESCRIPTION" VARCHAR2(1020),
	"LABEL" VARCHAR2(512),
	"MAX_VALUE" FLOAT(22),
	"MIN_VALUE" FLOAT(22),
	"NAME" VARCHAR2(256),
	"PARENT_ID" NUMBER(22),
	"UNIT_ID" NUMBER(22)
);

	ALTER TABLE "EQUIPMENT_ATTRIBUTE"
		ADD CONSTRAINT "EQUIPMENT_ATTRIBUTE_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "EQUIPMENT_ATTRIBUTE_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;

ALTER TABLE "EQUIPMENT_ATTRIBUTE" ADD CONSTRAINT "EQUIPMENT_ATTRIBUTE_FK_1" FOREIGN KEY ("PARENT_ID") REFERENCES "EQUIPMENT_ATTRIBUTE" ("ID") ON DELETE CASCADE;

ALTER TABLE "EQUIPMENT_ATTRIBUTE" ADD CONSTRAINT "EQUIPMENT_ATTRIBUTE_FK_2" FOREIGN KEY ("UNIT_ID") REFERENCES "UNIT" ("UNIT_ID") ON DELETE CASCADE;


/* -----------------------------------------------------------------------
   EQUIPMENT_ATTRIBUTE_CLASS
   ----------------------------------------------------------------------- */

DROP TABLE "EQUIPMENT_ATTRIBUTE_CLASS" CASCADE CONSTRAINTS;

DROP SEQUENCE "QPMNT_TTRBT_CLSS_SEQ";


CREATE TABLE "EQUIPMENT_ATTRIBUTE_CLASS"
(
	"ID" NUMBER(22)  NOT NULL,
	"EQUIPMENT_ATTRIBUTE_ID" NUMBER(22),
	"EQUIPMENT_CLASS_ID" NUMBER(22)
);

	ALTER TABLE "EQUIPMENT_ATTRIBUTE_CLASS"
		ADD CONSTRAINT "EQUIPMENT_ATTRIBUTE_CLASS_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "QPMNT_TTRBT_CLSS_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;

ALTER TABLE "EQUIPMENT_ATTRIBUTE_CLASS" ADD CONSTRAINT "EQUIPMENT_ATTRIBUTE_CLASS_FK_1" FOREIGN KEY ("EQUIPMENT_ATTRIBUTE_ID") REFERENCES "EQUIPMENT_ATTRIBUTE" ("ID") ON DELETE CASCADE;

ALTER TABLE "EQUIPMENT_ATTRIBUTE_CLASS" ADD CONSTRAINT "EQUIPMENT_ATTRIBUTE_CLASS_FK_2" FOREIGN KEY ("EQUIPMENT_CLASS_ID") REFERENCES "EQUIPMENT_CLASS" ("EQUIPMENT_CLASS_ID") ON DELETE CASCADE;


/* -----------------------------------------------------------------------
   EQUIPMENT_ATTRIBUTE_VALUE
   ----------------------------------------------------------------------- */

DROP TABLE "EQUIPMENT_ATTRIBUTE_VALUE" CASCADE CONSTRAINTS;

DROP SEQUENCE "QPMNT_TTRBT_VL_SEQ";


CREATE TABLE "EQUIPMENT_ATTRIBUTE_VALUE"
(
	"ID" NUMBER(22)  NOT NULL,
	"EQUIPMENT_ATTRIBUTE_CLASS_ID" NUMBER(22),
	"EQUIPMENT_ATTRIBUTE_ID" NUMBER(22),
	"EQUIPMENT_ID" NUMBER(22),
	"NOTE" CLOB,
	"UNIT_ID" NUMBER(22),
	"VALUE" VARCHAR2(1020)
);

	ALTER TABLE "EQUIPMENT_ATTRIBUTE_VALUE"
		ADD CONSTRAINT "EQUIPMENT_ATTRIBUTE_VALUE_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "QPMNT_TTRBT_VL_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;

ALTER TABLE "EQUIPMENT_ATTRIBUTE_VALUE" ADD CONSTRAINT "EQUIPMENT_ATTRIBUTE_VALUE_FK_1" FOREIGN KEY ("EQUIPMENT_ID") REFERENCES "EQUIPMENT" ("EQUIPMENT_ID") ON DELETE CASCADE;

ALTER TABLE "EQUIPMENT_ATTRIBUTE_VALUE" ADD CONSTRAINT "EQUIPMENT_ATTRIBUTE_VALUE_FK_2" FOREIGN KEY ("EQUIPMENT_ATTRIBUTE_ID") REFERENCES "EQUIPMENT_ATTRIBUTE" ("ID") ON DELETE CASCADE;

ALTER TABLE "EQUIPMENT_ATTRIBUTE_VALUE" ADD CONSTRAINT "EQUIPMENT_ATTRIBUTE_VALUE_FK_3" FOREIGN KEY ("EQUIPMENT_ATTRIBUTE_CLASS_ID") REFERENCES "EQUIPMENT_ATTRIBUTE_CLASS" ("ID") ON DELETE CASCADE;

ALTER TABLE "EQUIPMENT_ATTRIBUTE_VALUE" ADD CONSTRAINT "EQUIPMENT_ATTRIBUTE_VALUE_FK_4" FOREIGN KEY ("UNIT_ID") REFERENCES "UNIT" ("UNIT_ID") ON DELETE CASCADE;


/* -----------------------------------------------------------------------
   EQUIPMENT_CLASS
   ----------------------------------------------------------------------- */

DROP TABLE "EQUIPMENT_CLASS" CASCADE CONSTRAINTS;

DROP SEQUENCE "EQUIPMENT_CLASS_SEQ";


CREATE TABLE "EQUIPMENT_CLASS"
(
	"EQUIPMENT_CLASS_ID" NUMBER(22)  NOT NULL,
	"CATEGORY" VARCHAR2(128),
	"CLASS_NAME" VARCHAR2(256),
	"DEPRECATED" NUMBER(22),
	"DESCRIPTION" CLOB,
	"MAJOR" NUMBER(22),
	"SPEC_AVAILABLE" NUMBER(22)
);

	ALTER TABLE "EQUIPMENT_CLASS"
		ADD CONSTRAINT "EQUIPMENT_CLASS_PK"
	PRIMARY KEY ("EQUIPMENT_CLASS_ID");
CREATE SEQUENCE "EQUIPMENT_CLASS_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;


/* -----------------------------------------------------------------------
   EQUIPMENT_DOCUMENTATION
   ----------------------------------------------------------------------- */

DROP TABLE "EQUIPMENT_DOCUMENTATION" CASCADE CONSTRAINTS;

DROP SEQUENCE "QPMNT_DCMNTTN_SEQ";


CREATE TABLE "EQUIPMENT_DOCUMENTATION"
(
	"EQUIPMENT_DOC_ID" NUMBER(22)  NOT NULL,
	"DESCRIPTION" VARCHAR2(1020),
	"DOCUMENT_FORMAT_ID" NUMBER(22),
	"DOCUMENT_TYPE_ID" NUMBER(22),
	"DOCUMENTATION_FILE_ID" NUMBER(22),
	"EQUIPMENT_ID" NUMBER(22),
	"LAST_MODIFIED" DATE,
	"NAME" VARCHAR2(256),
	"PAGE_COUNT" NUMBER(22)
);

	ALTER TABLE "EQUIPMENT_DOCUMENTATION"
		ADD CONSTRAINT "EQUIPMENT_DOCUMENTATION_PK"
	PRIMARY KEY ("EQUIPMENT_DOC_ID");
CREATE SEQUENCE "QPMNT_DCMNTTN_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;

ALTER TABLE "EQUIPMENT_DOCUMENTATION" ADD CONSTRAINT "EQUIPMENT_DOCUMENTATION_FK_1" FOREIGN KEY ("DOCUMENTATION_FILE_ID") REFERENCES "DATA_FILE" ("ID") ON DELETE CASCADE;

ALTER TABLE "EQUIPMENT_DOCUMENTATION" ADD CONSTRAINT "EQUIPMENT_DOCUMENTATION_FK_2" FOREIGN KEY ("DOCUMENT_FORMAT_ID") REFERENCES "DOCUMENT_FORMAT" ("DOCUMENT_FORMAT_ID") ON DELETE SET NULL;

ALTER TABLE "EQUIPMENT_DOCUMENTATION" ADD CONSTRAINT "EQUIPMENT_DOCUMENTATION_FK_3" FOREIGN KEY ("DOCUMENT_TYPE_ID") REFERENCES "DOCUMENT_TYPE" ("DOCUMENT_TYPE_ID") ON DELETE SET NULL;

ALTER TABLE "EQUIPMENT_DOCUMENTATION" ADD CONSTRAINT "EQUIPMENT_DOCUMENTATION_FK_4" FOREIGN KEY ("EQUIPMENT_ID") REFERENCES "EQUIPMENT" ("EQUIPMENT_ID") ON DELETE CASCADE;


/* -----------------------------------------------------------------------
   EQUIPMENT_GROUPED_ATTRIBUTE
   ----------------------------------------------------------------------- */

DROP TABLE "EQUIPMENT_GROUPED_ATTRIBUTE" CASCADE CONSTRAINTS;

DROP SEQUENCE "QPMNT_GRPD_TTRBT_SEQ";


CREATE TABLE "EQUIPMENT_GROUPED_ATTRIBUTE"
(
	"ID" NUMBER(22)  NOT NULL,
	"ATTRIBUTE_ID" NUMBER(22),
	"DATE_VALUE" DATE,
	"G_ATTRIBUTE_ID" NUMBER(22),
	"INT_VALUE" NUMBER(22),
	"NOTE" CLOB,
	"NUM_VALUE" FLOAT(22),
	"PAGE_COUNT" NUMBER(22),
	"STRING_VALUE" CLOB,
	"UNIT_ID" NUMBER(22)
);

	ALTER TABLE "EQUIPMENT_GROUPED_ATTRIBUTE"
		ADD CONSTRAINT "EQUIPMENT_GROUPED_ATTRIBUTE_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "QPMNT_GRPD_TTRBT_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;

ALTER TABLE "EQUIPMENT_GROUPED_ATTRIBUTE" ADD CONSTRAINT "EQUIPMENT_GROUPED_ATTRIBU_FK_1" FOREIGN KEY ("ATTRIBUTE_ID") REFERENCES "ATTRIBUTE" ("ATTRIBUTE_ID") ON DELETE CASCADE;


/* -----------------------------------------------------------------------
   EQUIPMENT_GROUPED_ATTR_MAP
   ----------------------------------------------------------------------- */

DROP TABLE "EQUIPMENT_GROUPED_ATTR_MAP" CASCADE CONSTRAINTS;

DROP SEQUENCE "QPMNT_GRPD_TTR_MP_SEQ";


CREATE TABLE "EQUIPMENT_GROUPED_ATTR_MAP"
(
	"ID" NUMBER(22)  NOT NULL,
	"ATTRIBUTE_ID" NUMBER(22),
	"EQUIPMENT_ID" NUMBER(22),
	"G_ATTRIBUTE_ID" NUMBER(22),
	"GROUP_VALUE" NUMBER(22)
);

	ALTER TABLE "EQUIPMENT_GROUPED_ATTR_MAP"
		ADD CONSTRAINT "EQUIPMENT_GROUPED_ATTR_MAP_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "QPMNT_GRPD_TTR_MP_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;

ALTER TABLE "EQUIPMENT_GROUPED_ATTR_MAP" ADD CONSTRAINT "EQUIPMENT_GROUPED_ATTR_MA_FK_1" FOREIGN KEY ("ATTRIBUTE_ID") REFERENCES "ATTRIBUTE" ("ATTRIBUTE_ID") ON DELETE CASCADE;


/* -----------------------------------------------------------------------
   EQUIPMENT_MODEL
   ----------------------------------------------------------------------- */

DROP TABLE "EQUIPMENT_MODEL" CASCADE CONSTRAINTS;

DROP SEQUENCE "EQUIPMENT_MODEL_SEQ";


CREATE TABLE "EQUIPMENT_MODEL"
(
	"ID" NUMBER(22)  NOT NULL,
	"ADDITIONAL_SPEC_FILE_ID" NUMBER(22),
	"ADDITIONAL_SPEC_PAGE_COUNT" NUMBER(22),
	"DESIGN_CONSIDERATION_FILE_ID" NUMBER(22),
	"DESIGN_PAGE_COUNT" NUMBER(22),
	"EQUIPMENT_CLASS_ID" NUMBER(22),
	"INTERFACE_DOC_FILE_ID" NUMBER(22),
	"INTERFACE_DOC_PAGE_COUNT" NUMBER(22),
	"MANUFACTURER" VARCHAR2(512),
	"MANUFACTURER_DOC_FILE_ID" NUMBER(22),
	"MANUFACTURER_DOC_PAGE_COUNT" NUMBER(22),
	"MODEL_NUMBER" VARCHAR2(1020),
	"NAME" VARCHAR2(512),
	"SUBCOMPONENTS_DOC_FILE_ID" NUMBER(22),
	"SUBCOMPONENTS_DOC_PAGE_COUNT" NUMBER(22),
	"SUPPLIER" VARCHAR2(512)
);

	ALTER TABLE "EQUIPMENT_MODEL"
		ADD CONSTRAINT "EQUIPMENT_MODEL_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "EQUIPMENT_MODEL_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;

ALTER TABLE "EQUIPMENT_MODEL" ADD CONSTRAINT "EQUIPMENT_MODEL_FK_1" FOREIGN KEY ("ADDITIONAL_SPEC_FILE_ID") REFERENCES "DATA_FILE" ("ID") ON DELETE SET NULL;

ALTER TABLE "EQUIPMENT_MODEL" ADD CONSTRAINT "EQUIPMENT_MODEL_FK_2" FOREIGN KEY ("INTERFACE_DOC_FILE_ID") REFERENCES "DATA_FILE" ("ID") ON DELETE SET NULL;

ALTER TABLE "EQUIPMENT_MODEL" ADD CONSTRAINT "EQUIPMENT_MODEL_FK_3" FOREIGN KEY ("MANUFACTURER_DOC_FILE_ID") REFERENCES "DATA_FILE" ("ID") ON DELETE SET NULL;

ALTER TABLE "EQUIPMENT_MODEL" ADD CONSTRAINT "EQUIPMENT_MODEL_FK_4" FOREIGN KEY ("SUBCOMPONENTS_DOC_FILE_ID") REFERENCES "DATA_FILE" ("ID") ON DELETE SET NULL;

ALTER TABLE "EQUIPMENT_MODEL" ADD CONSTRAINT "EQUIPMENT_MODEL_FK_5" FOREIGN KEY ("DESIGN_CONSIDERATION_FILE_ID") REFERENCES "DATA_FILE" ("ID") ON DELETE SET NULL;

ALTER TABLE "EQUIPMENT_MODEL" ADD CONSTRAINT "EQUIPMENT_MODEL_FK_6" FOREIGN KEY ("EQUIPMENT_CLASS_ID") REFERENCES "EQUIPMENT_CLASS" ("EQUIPMENT_CLASS_ID") ON DELETE SET NULL;


/* -----------------------------------------------------------------------
   EXPERIMENT
   ----------------------------------------------------------------------- */

DROP TABLE "EXPERIMENT" CASCADE CONSTRAINTS;

DROP SEQUENCE "EXPERIMENT_SEQ";


CREATE TABLE "EXPERIMENT"
(
	"EXPID" NUMBER(22)  NOT NULL,
	"CURATION_STATUS" VARCHAR2(40),
	"DELETED" NUMBER(22),
	"DESCRIPTION" CLOB,
	"END_DATE" DATE,
	"EXPERIMENT_DOMAIN_ID" NUMBER(22),
	"EXP_TYPE_ID" NUMBER(22) default 0,
	"NAME" VARCHAR2(64),
	"OBJECTIVE" CLOB,
	"PROJID" NUMBER(22),
	"START_DATE" DATE,
	"STATUS" VARCHAR2(48),
	"TITLE" VARCHAR2(1020)  NOT NULL,
	"VIEWABLE" VARCHAR2(32)
);

	ALTER TABLE "EXPERIMENT"
		ADD CONSTRAINT "EXPERIMENT_PK"
	PRIMARY KEY ("EXPID");
CREATE SEQUENCE "EXPERIMENT_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;

ALTER TABLE "EXPERIMENT" ADD CONSTRAINT "EXPERIMENT_FK_1" FOREIGN KEY ("EXPERIMENT_DOMAIN_ID") REFERENCES "EXPERIMENT_DOMAIN" ("ID") ON DELETE CASCADE;

ALTER TABLE "EXPERIMENT" ADD CONSTRAINT "EXPERIMENT_FK_2" FOREIGN KEY ("PROJID") REFERENCES "PROJECT" ("PROJID") ON DELETE CASCADE;


/* -----------------------------------------------------------------------
   EXPERIMENT_DOMAIN
   ----------------------------------------------------------------------- */

DROP TABLE "EXPERIMENT_DOMAIN" CASCADE CONSTRAINTS;

DROP SEQUENCE "EXPERIMENT_DOMAIN_SEQ";


CREATE TABLE "EXPERIMENT_DOMAIN"
(
	"ID" NUMBER(22)  NOT NULL,
	"DESCRIPTION" VARCHAR2(255)  NOT NULL,
	"DISPLAY_NAME" VARCHAR2(400)  NOT NULL,
	"SYSTEM_NAME" VARCHAR2(128)  NOT NULL,
	"DISPLAY_ORDER" NUMBER(22)  NOT NULL
);

	ALTER TABLE "EXPERIMENT_DOMAIN"
		ADD CONSTRAINT "EXPERIMENT_DOMAIN_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "EXPERIMENT_DOMAIN_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;


/* -----------------------------------------------------------------------
   EXPERIMENT_EQUIPMENT
   ----------------------------------------------------------------------- */

DROP TABLE "EXPERIMENT_EQUIPMENT" CASCADE CONSTRAINTS;

DROP SEQUENCE "EXPERIMENT_EQUIPMENT_SEQ";


CREATE TABLE "EXPERIMENT_EQUIPMENT"
(
	"ID" NUMBER(22)  NOT NULL,
	"COMMENTS" CLOB,
	"EQUIPMENT_ID" NUMBER(22),
	"EXPERIMENT_ID" NUMBER(22)
);

	ALTER TABLE "EXPERIMENT_EQUIPMENT"
		ADD CONSTRAINT "EXPERIMENT_EQUIPMENT_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "EXPERIMENT_EQUIPMENT_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;

ALTER TABLE "EXPERIMENT_EQUIPMENT" ADD CONSTRAINT "EXPERIMENT_EQUIPMENT_FK_1" FOREIGN KEY ("EQUIPMENT_ID") REFERENCES "EQUIPMENT" ("EQUIPMENT_ID") ON DELETE CASCADE;

ALTER TABLE "EXPERIMENT_EQUIPMENT" ADD CONSTRAINT "EXPERIMENT_EQUIPMENT_FK_2" FOREIGN KEY ("EXPERIMENT_ID") REFERENCES "EXPERIMENT" ("EXPID") ON DELETE CASCADE;


/* -----------------------------------------------------------------------
   EXPERIMENT_FACILITY
   ----------------------------------------------------------------------- */

DROP TABLE "EXPERIMENT_FACILITY" CASCADE CONSTRAINTS;

DROP SEQUENCE "EXPERIMENT_FACILITY_SEQ";


CREATE TABLE "EXPERIMENT_FACILITY"
(
	"ID" NUMBER(22)  NOT NULL,
	"EXPID" NUMBER(22)  NOT NULL,
	"FACILITYID" NUMBER(22)  NOT NULL
);

	ALTER TABLE "EXPERIMENT_FACILITY"
		ADD CONSTRAINT "EXPERIMENT_FACILITY_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "EXPERIMENT_FACILITY_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;

ALTER TABLE "EXPERIMENT_FACILITY" ADD CONSTRAINT "EXPERIMENT_FACILITY_FK_1" FOREIGN KEY ("EXPID") REFERENCES "EXPERIMENT" ("EXPID") ON DELETE CASCADE;

ALTER TABLE "EXPERIMENT_FACILITY" ADD CONSTRAINT "EXPERIMENT_FACILITY_FK_2" FOREIGN KEY ("FACILITYID") REFERENCES "ORGANIZATION" ("ORGID") ON DELETE CASCADE;


/* -----------------------------------------------------------------------
   EXPERIMENT_MEASUREMENT
   ----------------------------------------------------------------------- */

DROP TABLE "EXPERIMENT_MEASUREMENT" CASCADE CONSTRAINTS;

DROP SEQUENCE "XPRMNT_MSRMNT_SEQ";


CREATE TABLE "EXPERIMENT_MEASUREMENT"
(
	"ID" NUMBER(22)  NOT NULL,
	"CATEGORY" NUMBER(22),
	"DEFAULT_UNIT" NUMBER(22),
	"EXPID" NUMBER(22)
);

	ALTER TABLE "EXPERIMENT_MEASUREMENT"
		ADD CONSTRAINT "EXPERIMENT_MEASUREMENT_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "XPRMNT_MSRMNT_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;

ALTER TABLE "EXPERIMENT_MEASUREMENT" ADD CONSTRAINT "EXPERIMENT_MEASUREMENT_FK_1" FOREIGN KEY ("EXPID") REFERENCES "EXPERIMENT" ("EXPID") ON DELETE CASCADE;

ALTER TABLE "EXPERIMENT_MEASUREMENT" ADD CONSTRAINT "EXPERIMENT_MEASUREMENT_FK_2" FOREIGN KEY ("DEFAULT_UNIT") REFERENCES "MEASUREMENT_UNIT" ("ID") ON DELETE CASCADE;

ALTER TABLE "EXPERIMENT_MEASUREMENT" ADD CONSTRAINT "EXPERIMENT_MEASUREMENT_FK_3" FOREIGN KEY ("CATEGORY") REFERENCES "MEASUREMENT_UNIT_CATEGORY" ("ID") ON DELETE CASCADE;


/* -----------------------------------------------------------------------
   EXPERIMENT_MODEL
   ----------------------------------------------------------------------- */

DROP TABLE "EXPERIMENT_MODEL" CASCADE CONSTRAINTS;

DROP SEQUENCE "EXPERIMENT_MODEL_SEQ";


CREATE TABLE "EXPERIMENT_MODEL"
(
	"ID" NUMBER(22)  NOT NULL,
	"DESCRIPTION" VARCHAR2(1020),
	"EXPID" NUMBER(22),
	"NAME" VARCHAR2(400),
	"TYPEID" NUMBER(22)
);

	ALTER TABLE "EXPERIMENT_MODEL"
		ADD CONSTRAINT "EXPERIMENT_MODEL_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "EXPERIMENT_MODEL_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;

ALTER TABLE "EXPERIMENT_MODEL" ADD CONSTRAINT "EXPERIMENT_MODEL_FK_1" FOREIGN KEY ("EXPID") REFERENCES "EXPERIMENT" ("EXPID") ON DELETE CASCADE;

ALTER TABLE "EXPERIMENT_MODEL" ADD CONSTRAINT "EXPERIMENT_MODEL_FK_2" FOREIGN KEY ("TYPEID") REFERENCES "EXPERIMENT_MODEL_TYPE" ("ID") ON DELETE CASCADE;


/* -----------------------------------------------------------------------
   EXPERIMENT_MODEL_TYPE
   ----------------------------------------------------------------------- */

DROP TABLE "EXPERIMENT_MODEL_TYPE" CASCADE CONSTRAINTS;

DROP SEQUENCE "XPRMNT_MDL_TYP_SEQ";


CREATE TABLE "EXPERIMENT_MODEL_TYPE"
(
	"ID" NUMBER(22)  NOT NULL,
	"DESCRIPTION" VARCHAR2(1020),
	"DISPLAY_NAME" VARCHAR2(400),
	"SYSTEM_NAME" VARCHAR2(128)
);

	ALTER TABLE "EXPERIMENT_MODEL_TYPE"
		ADD CONSTRAINT "EXPERIMENT_MODEL_TYPE_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "XPRMNT_MDL_TYP_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;


/* -----------------------------------------------------------------------
   EXPERIMENT_ORGANIZATION
   ----------------------------------------------------------------------- */

DROP TABLE "EXPERIMENT_ORGANIZATION" CASCADE CONSTRAINTS;

DROP SEQUENCE "XPRMNT_RGNZTN_SEQ";


CREATE TABLE "EXPERIMENT_ORGANIZATION"
(
	"ID" NUMBER(22)  NOT NULL,
	"EXPID" NUMBER(22),
	"ORGID" NUMBER(22)
);

	ALTER TABLE "EXPERIMENT_ORGANIZATION"
		ADD CONSTRAINT "EXPERIMENT_ORGANIZATION_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "XPRMNT_RGNZTN_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;

ALTER TABLE "EXPERIMENT_ORGANIZATION" ADD CONSTRAINT "EXPERIMENT_ORGANIZATION_FK_1" FOREIGN KEY ("EXPID") REFERENCES "EXPERIMENT" ("EXPID") ON DELETE CASCADE;

ALTER TABLE "EXPERIMENT_ORGANIZATION" ADD CONSTRAINT "EXPERIMENT_ORGANIZATION_FK_2" FOREIGN KEY ("ORGID") REFERENCES "ORGANIZATION" ("ORGID") ON DELETE CASCADE;


/* -----------------------------------------------------------------------
   FACILITY_DATA_FILE
   ----------------------------------------------------------------------- */

DROP TABLE "FACILITY_DATA_FILE" CASCADE CONSTRAINTS;

DROP SEQUENCE "FACILITY_DATA_FILE_SEQ";


CREATE TABLE "FACILITY_DATA_FILE"
(
	"ID" NUMBER(22)  NOT NULL,
	"DATA_FILE_ID" NUMBER(22),
	"DOC_FORMAT_ID" NUMBER(22),
	"DOC_TYPE_ID" NUMBER(22),
	"FACILITY_ID" NUMBER(22),
	"GROUPBY" VARCHAR2(320),
	"INFO_TYPE" VARCHAR2(320),
	"SUB_INFO_TYPE" VARCHAR2(400)
);

	ALTER TABLE "FACILITY_DATA_FILE"
		ADD CONSTRAINT "FACILITY_DATA_FILE_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "FACILITY_DATA_FILE_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;

ALTER TABLE "FACILITY_DATA_FILE" ADD CONSTRAINT "FACILITY_DATA_FILE_FK_1" FOREIGN KEY ("DATA_FILE_ID") REFERENCES "DATA_FILE" ("ID") ON DELETE CASCADE;

ALTER TABLE "FACILITY_DATA_FILE" ADD CONSTRAINT "FACILITY_DATA_FILE_FK_2" FOREIGN KEY ("DOC_FORMAT_ID") REFERENCES "DOCUMENT_FORMAT" ("DOCUMENT_FORMAT_ID") ON DELETE CASCADE;

ALTER TABLE "FACILITY_DATA_FILE" ADD CONSTRAINT "FACILITY_DATA_FILE_FK_3" FOREIGN KEY ("DOC_TYPE_ID") REFERENCES "DOCUMENT_TYPE" ("DOCUMENT_TYPE_ID") ON DELETE CASCADE;

ALTER TABLE "FACILITY_DATA_FILE" ADD CONSTRAINT "FACILITY_DATA_FILE_FK_4" FOREIGN KEY ("FACILITY_ID") REFERENCES "ORGANIZATION" ("ORGID") ON DELETE CASCADE;


/* -----------------------------------------------------------------------
   LOAD_TYPE
   ----------------------------------------------------------------------- */

DROP TABLE "LOAD_TYPE" CASCADE CONSTRAINTS;

DROP SEQUENCE "LOAD_TYPE_SEQ";


CREATE TABLE "LOAD_TYPE"
(
	"ID" NUMBER(22)  NOT NULL,
	"NAME" VARCHAR2(1020)
);

	ALTER TABLE "LOAD_TYPE"
		ADD CONSTRAINT "LOAD_TYPE_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "LOAD_TYPE_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;


/* -----------------------------------------------------------------------
   LOCATION
   ----------------------------------------------------------------------- */

DROP TABLE "LOCATION" CASCADE CONSTRAINTS;

DROP SEQUENCE "LOCATION_SEQ";


CREATE TABLE "LOCATION"
(
	"ID" NUMBER(22)  NOT NULL,
	"COMMENTS" VARCHAR2(1020),
	"COORDINATE_SPACE_ID" NUMBER(22),
	"I" FLOAT(22),
	"I_UNIT" NUMBER(22),
	"J" FLOAT(22),
	"J_UNIT" NUMBER(22),
	"K" FLOAT(22),
	"K_UNIT" NUMBER(22),
	"LABEL" VARCHAR2(100)  NOT NULL,
	"LOCATION_TYPE_ID" NUMBER(22) default 0 NOT NULL,
	"PLAN_ID" NUMBER(22),
	"SENSOR_TYPE_ID" NUMBER(22),
	"SOURCE_TYPE_ID" NUMBER(22),
	"X" FLOAT(22)  NOT NULL,
	"X_UNIT" NUMBER(22),
	"Y" FLOAT(22)  NOT NULL,
	"Y_UNIT" NUMBER(22),
	"Z" FLOAT(22)  NOT NULL,
	"Z_UNIT" NUMBER(22)
);

	ALTER TABLE "LOCATION"
		ADD CONSTRAINT "LOCATION_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "LOCATION_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;

ALTER TABLE "LOCATION" ADD CONSTRAINT "LOCATION_FK_1" FOREIGN KEY ("COORDINATE_SPACE_ID") REFERENCES "COORDINATE_SPACE" ("ID") ON DELETE CASCADE;

ALTER TABLE "LOCATION" ADD CONSTRAINT "LOCATION_FK_2" FOREIGN KEY ("PLAN_ID") REFERENCES "LOCATION_PLAN" ("ID") ON DELETE CASCADE;

ALTER TABLE "LOCATION" ADD CONSTRAINT "LOCATION_FK_3" FOREIGN KEY ("J_UNIT") REFERENCES "MEASUREMENT_UNIT" ("ID") ON DELETE SET NULL;

ALTER TABLE "LOCATION" ADD CONSTRAINT "LOCATION_FK_4" FOREIGN KEY ("Y_UNIT") REFERENCES "MEASUREMENT_UNIT" ("ID") ON DELETE SET NULL;

ALTER TABLE "LOCATION" ADD CONSTRAINT "LOCATION_FK_5" FOREIGN KEY ("X_UNIT") REFERENCES "MEASUREMENT_UNIT" ("ID") ON DELETE SET NULL;

ALTER TABLE "LOCATION" ADD CONSTRAINT "LOCATION_FK_6" FOREIGN KEY ("I_UNIT") REFERENCES "MEASUREMENT_UNIT" ("ID") ON DELETE SET NULL;

ALTER TABLE "LOCATION" ADD CONSTRAINT "LOCATION_FK_7" FOREIGN KEY ("Z_UNIT") REFERENCES "MEASUREMENT_UNIT" ("ID") ON DELETE SET NULL;

ALTER TABLE "LOCATION" ADD CONSTRAINT "LOCATION_FK_8" FOREIGN KEY ("K_UNIT") REFERENCES "MEASUREMENT_UNIT" ("ID") ON DELETE SET NULL;

ALTER TABLE "LOCATION" ADD CONSTRAINT "LOCATION_FK_9" FOREIGN KEY ("SENSOR_TYPE_ID") REFERENCES "SENSOR_TYPE" ("ID") ON DELETE SET NULL;

ALTER TABLE "LOCATION" ADD CONSTRAINT "LOCATION_FK_10" FOREIGN KEY ("SOURCE_TYPE_ID") REFERENCES "SOURCE_TYPE" ("ID") ON DELETE SET NULL;


/* -----------------------------------------------------------------------
   LOCATION_PLAN
   ----------------------------------------------------------------------- */

DROP TABLE "LOCATION_PLAN" CASCADE CONSTRAINTS;

DROP SEQUENCE "LOCATION_PLAN_SEQ";


CREATE TABLE "LOCATION_PLAN"
(
	"ID" NUMBER(22)  NOT NULL,
	"EXPID" NUMBER(22),
	"TRIAL_ID" NUMBER(22),
	"NAME" VARCHAR2(1020),
	"PLAN_TYPE_ID" NUMBER(22) default 0
);

	ALTER TABLE "LOCATION_PLAN"
		ADD CONSTRAINT "LOCATION_PLAN_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "LOCATION_PLAN_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;

ALTER TABLE "LOCATION_PLAN" ADD CONSTRAINT "LOCATION_PLAN_FK_1" FOREIGN KEY ("EXPID") REFERENCES "EXPERIMENT" ("EXPID") ON DELETE CASCADE;

ALTER TABLE "LOCATION_PLAN" ADD CONSTRAINT "LOCATION_PLAN_FK_2" FOREIGN KEY ("TRIAL_ID") REFERENCES "TRIAL" ("TRIALID") ON DELETE CASCADE;


/* -----------------------------------------------------------------------
   MATERIAL
   ----------------------------------------------------------------------- */

DROP TABLE "MATERIAL" CASCADE CONSTRAINTS;

DROP SEQUENCE "MATERIAL_SEQ";


CREATE TABLE "MATERIAL"
(
	"ID" NUMBER(22)  NOT NULL,
	"DESCRIPTION" CLOB,
	"EXPID" NUMBER(22),
	"MATERIAL_TYPE_ID" NUMBER(22),
	"NAME" VARCHAR2(400),
	"PROTOTYPE_MATERIAL_ID" NUMBER(22)
);

	ALTER TABLE "MATERIAL"
		ADD CONSTRAINT "MATERIAL_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "MATERIAL_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;

ALTER TABLE "MATERIAL" ADD CONSTRAINT "MATERIAL_FK_1" FOREIGN KEY ("EXPID") REFERENCES "EXPERIMENT" ("EXPID") ON DELETE CASCADE;

ALTER TABLE "MATERIAL" ADD CONSTRAINT "MATERIAL_FK_2" FOREIGN KEY ("PROTOTYPE_MATERIAL_ID") REFERENCES "MATERIAL" ("ID") ON DELETE SET NULL;

ALTER TABLE "MATERIAL" ADD CONSTRAINT "MATERIAL_FK_3" FOREIGN KEY ("MATERIAL_TYPE_ID") REFERENCES "MATERIAL_TYPE" ("ID") ON DELETE CASCADE;


/* -----------------------------------------------------------------------
   MATERIAL_DATA_FILE
   ----------------------------------------------------------------------- */

DROP TABLE "MATERIAL_DATA_FILE" CASCADE CONSTRAINTS;

DROP SEQUENCE "MATERIAL_DATA_FILE_SEQ";


CREATE TABLE "MATERIAL_DATA_FILE"
(
	"ID" NUMBER(22)  NOT NULL,
	"DATA_FILE_ID" NUMBER(22),
	"MATERIAL_ID" NUMBER(22)
);

	ALTER TABLE "MATERIAL_DATA_FILE"
		ADD CONSTRAINT "MATERIAL_DATA_FILE_PK"
	PRIMARY KEY ("ID");
CREATE INDEX "SYS_C0040723" ON "MATERIAL_DATA_FILE" ("DATA_FILE_ID");
CREATE SEQUENCE "MATERIAL_DATA_FILE_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;
CREATE INDEX "SYS_C0040723" ON "MATERIAL_DATA_FILE" ("DATA_FILE_ID");

ALTER TABLE "MATERIAL_DATA_FILE" ADD CONSTRAINT "MATERIAL_DATA_FILE_FK_1" FOREIGN KEY ("DATA_FILE_ID") REFERENCES "DATA_FILE" ("ID") ON DELETE CASCADE;

ALTER TABLE "MATERIAL_DATA_FILE" ADD CONSTRAINT "MATERIAL_DATA_FILE_FK_2" FOREIGN KEY ("MATERIAL_ID") REFERENCES "MATERIAL" ("ID") ON DELETE CASCADE;


/* -----------------------------------------------------------------------
   MATERIAL_PROPERTY
   ----------------------------------------------------------------------- */

DROP TABLE "MATERIAL_PROPERTY" CASCADE CONSTRAINTS;

DROP SEQUENCE "MATERIAL_PROPERTY_SEQ";


CREATE TABLE "MATERIAL_PROPERTY"
(
	"ID" NUMBER(22)  NOT NULL,
	"MATERIAL_ID" NUMBER(22),
	"MATERIAL_TYPE_PROPERTY_ID" NUMBER(22),
	"MEASUREMENT_UNIT_ID" NUMBER(22),
	"VALUE" VARCHAR2(400)
);

	ALTER TABLE "MATERIAL_PROPERTY"
		ADD CONSTRAINT "MATERIAL_PROPERTY_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "MATERIAL_PROPERTY_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;

ALTER TABLE "MATERIAL_PROPERTY" ADD CONSTRAINT "MATERIAL_PROPERTY_FK_1" FOREIGN KEY ("MATERIAL_ID") REFERENCES "MATERIAL" ("ID") ON DELETE CASCADE;

ALTER TABLE "MATERIAL_PROPERTY" ADD CONSTRAINT "MATERIAL_PROPERTY_FK_2" FOREIGN KEY ("MATERIAL_TYPE_PROPERTY_ID") REFERENCES "MATERIAL_TYPE_PROPERTY" ("ID") ON DELETE CASCADE;

ALTER TABLE "MATERIAL_PROPERTY" ADD CONSTRAINT "MATERIAL_PROPERTY_FK_3" FOREIGN KEY ("MEASUREMENT_UNIT_ID") REFERENCES "MEASUREMENT_UNIT" ("ID") ON DELETE CASCADE;


/* -----------------------------------------------------------------------
   MATERIAL_TYPE
   ----------------------------------------------------------------------- */

DROP TABLE "MATERIAL_TYPE" CASCADE CONSTRAINTS;

DROP SEQUENCE "MATERIAL_TYPE_SEQ";


CREATE TABLE "MATERIAL_TYPE"
(
	"ID" NUMBER(22)  NOT NULL,
	"DESCRIPTION" VARCHAR2(1020),
	"DISPLAY_NAME" VARCHAR2(400),
	"SYSTEM_NAME" VARCHAR2(128)
);

	ALTER TABLE "MATERIAL_TYPE"
		ADD CONSTRAINT "MATERIAL_TYPE_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "MATERIAL_TYPE_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;


/* -----------------------------------------------------------------------
   MATERIAL_TYPE_PROPERTY
   ----------------------------------------------------------------------- */

DROP TABLE "MATERIAL_TYPE_PROPERTY" CASCADE CONSTRAINTS;

DROP SEQUENCE "MTRL_TYP_PRPRTY_SEQ";


CREATE TABLE "MATERIAL_TYPE_PROPERTY"
(
	"ID" NUMBER(22)  NOT NULL,
	"DATATYPE" VARCHAR2(24),
	"DISPLAY_NAME" VARCHAR2(400),
	"MATERIAL_TYPE_ID" NUMBER(22),
	"MEASUREMENT_UNIT_CATEGORY_ID" NUMBER(22),
	"OPTIONS" VARCHAR2(1020),
	"REQUIRED" NUMBER(22),
	"STATUS" NUMBER(22),
	"UNITS" VARCHAR2(128)
);

	ALTER TABLE "MATERIAL_TYPE_PROPERTY"
		ADD CONSTRAINT "MATERIAL_TYPE_PROPERTY_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "MTRL_TYP_PRPRTY_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;

ALTER TABLE "MATERIAL_TYPE_PROPERTY" ADD CONSTRAINT "MATERIAL_TYPE_PROPERTY_FK_1" FOREIGN KEY ("MATERIAL_TYPE_ID") REFERENCES "MATERIAL_TYPE" ("ID") ON DELETE CASCADE;

ALTER TABLE "MATERIAL_TYPE_PROPERTY" ADD CONSTRAINT "MATERIAL_TYPE_PROPERTY_FK_2" FOREIGN KEY ("MEASUREMENT_UNIT_CATEGORY_ID") REFERENCES "MEASUREMENT_UNIT_CATEGORY" ("ID") ON DELETE SET NULL;


/* -----------------------------------------------------------------------
   MEASUREMENT_UNIT
   ----------------------------------------------------------------------- */

DROP TABLE "MEASUREMENT_UNIT" CASCADE CONSTRAINTS;

DROP SEQUENCE "MEASUREMENT_UNIT_SEQ";


CREATE TABLE "MEASUREMENT_UNIT"
(
	"ID" NUMBER(22)  NOT NULL,
	"ABBREVIATION" VARCHAR2(1020),
	"BASE_UNIT" NUMBER(22),
	"CATEGORY" NUMBER(22),
	"COMMENTS" CLOB,
	"NAME" VARCHAR2(1020)
);

	ALTER TABLE "MEASUREMENT_UNIT"
		ADD CONSTRAINT "MEASUREMENT_UNIT_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "MEASUREMENT_UNIT_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;

ALTER TABLE "MEASUREMENT_UNIT" ADD CONSTRAINT "MEASUREMENT_UNIT_FK_1" FOREIGN KEY ("BASE_UNIT") REFERENCES "MEASUREMENT_UNIT" ("ID") ON DELETE SET NULL;

ALTER TABLE "MEASUREMENT_UNIT" ADD CONSTRAINT "MEASUREMENT_UNIT_FK_2" FOREIGN KEY ("CATEGORY") REFERENCES "MEASUREMENT_UNIT_CATEGORY" ("ID") ON DELETE CASCADE;


/* -----------------------------------------------------------------------
   MEASUREMENT_UNIT_CATEGORY
   ----------------------------------------------------------------------- */

DROP TABLE "MEASUREMENT_UNIT_CATEGORY" CASCADE CONSTRAINTS;

DROP SEQUENCE "MSRMNT_NT_CTGRY_SEQ";


CREATE TABLE "MEASUREMENT_UNIT_CATEGORY"
(
	"ID" NUMBER(22)  NOT NULL,
	"COMMENTS" CLOB,
	"NAME" VARCHAR2(1020)
);

	ALTER TABLE "MEASUREMENT_UNIT_CATEGORY"
		ADD CONSTRAINT "MEASUREMENT_UNIT_CATEGORY_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "MSRMNT_NT_CTGRY_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;


/* -----------------------------------------------------------------------
   MEASUREMENT_UNIT_CONVERSION
   ----------------------------------------------------------------------- */

DROP TABLE "MEASUREMENT_UNIT_CONVERSION" CASCADE CONSTRAINTS;

DROP SEQUENCE "MSRMNT_NT_CNVRSN_SEQ";


CREATE TABLE "MEASUREMENT_UNIT_CONVERSION"
(
	"ID" NUMBER(22)  NOT NULL,
	"FROM_ID" NUMBER(22),
	"K0" FLOAT(22),
	"K1" FLOAT(22),
	"TO_ID" NUMBER(22)
);

	ALTER TABLE "MEASUREMENT_UNIT_CONVERSION"
		ADD CONSTRAINT "MEASUREMENT_UNIT_CONVERSION_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "MSRMNT_NT_CNVRSN_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;

ALTER TABLE "MEASUREMENT_UNIT_CONVERSION" ADD CONSTRAINT "MEASUREMENT_UNIT_CONVERSI_FK_1" FOREIGN KEY ("TO_ID") REFERENCES "MEASUREMENT_UNIT" ("ID") ON DELETE CASCADE;

ALTER TABLE "MEASUREMENT_UNIT_CONVERSION" ADD CONSTRAINT "MEASUREMENT_UNIT_CONVERSI_FK_2" FOREIGN KEY ("FROM_ID") REFERENCES "MEASUREMENT_UNIT" ("ID") ON DELETE CASCADE;


/* -----------------------------------------------------------------------
   NAWI
   ----------------------------------------------------------------------- */

DROP TABLE "NAWI" CASCADE CONSTRAINTS;

DROP SEQUENCE "NAWI_SEQ";


CREATE TABLE "NAWI"
(
	"NAWIID" NUMBER(22)  NOT NULL,
	"ACTIVE" NUMBER(22),
	"CONTACT_EMAIL" VARCHAR2(1020),
	"CONTACT_NAME" VARCHAR2(1020),
	"EXP_DESCRIPT" CLOB,
	"EXP_NAME" VARCHAR2(1020),
	"EXP_PHASE" VARCHAR2(40),
	"MOVIE_URL" VARCHAR2(1020),
	"TEST_DT" DATE,
	"TEST_END" DATE,
	"TEST_START" DATE,
	"TEST_TZ" VARCHAR2(40)
);

	ALTER TABLE "NAWI"
		ADD CONSTRAINT "NAWI_PK"
	PRIMARY KEY ("NAWIID");
CREATE SEQUENCE "NAWI_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;


/* -----------------------------------------------------------------------
   NAWI_FACILITY
   ----------------------------------------------------------------------- */

DROP TABLE "NAWI_FACILITY" CASCADE CONSTRAINTS;

DROP SEQUENCE "NAWI_FACILITY_SEQ";


CREATE TABLE "NAWI_FACILITY"
(
	"ID" NUMBER(22)  NOT NULL,
	"FACILITYID" NUMBER(22),
	"NAWIID" NUMBER(22)
);

	ALTER TABLE "NAWI_FACILITY"
		ADD CONSTRAINT "NAWI_FACILITY_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "NAWI_FACILITY_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;

ALTER TABLE "NAWI_FACILITY" ADD CONSTRAINT "NAWI_FACILITY_FK_1" FOREIGN KEY ("NAWIID") REFERENCES "NAWI" ("NAWIID") ON DELETE CASCADE;

ALTER TABLE "NAWI_FACILITY" ADD CONSTRAINT "NAWI_FACILITY_FK_2" FOREIGN KEY ("FACILITYID") REFERENCES "ORGANIZATION" ("ORGID") ON DELETE CASCADE;


/* -----------------------------------------------------------------------
   ORGANIZATION
   ----------------------------------------------------------------------- */

DROP TABLE "ORGANIZATION" CASCADE CONSTRAINTS;

DROP SEQUENCE "ORGANIZATION_SEQ";


CREATE TABLE "ORGANIZATION"
(
	"ORGID" NUMBER(22)  NOT NULL,
	"DEPARTMENT" VARCHAR2(1020),
	"DESCRIPTION" CLOB,
	"FACILITYID" NUMBER(22),
	"FLEXTPS_URL" VARCHAR2(1020),
	"IMAGE_URL" VARCHAR2(1020),
	"LABORATORY" VARCHAR2(1020),
	"NAME" VARCHAR2(1020),
	"NAWI_ADMIN_USERS" VARCHAR2(1020),
	"NAWI_STATUS" VARCHAR2(32),
	"NSF_ACKNOWLEDGEMENT" CLOB,
	"NSF_AWARD_URL" VARCHAR2(1020),
	"ORG_TYPE_ID" NUMBER(22) default 0,
	"PARENT_ORG_ID" NUMBER(22),
	"POP_URL" VARCHAR2(1020),
	"SENSOR_MANIFEST_ID" NUMBER(22),
	"SHORT_NAME" VARCHAR2(64),
	"SITENAME" VARCHAR2(1020),
	"SITE_OP_USER" VARCHAR2(1020),
	"SYSADMIN" VARCHAR2(1020),
	"SYSADMIN_EMAIL" VARCHAR2(1020),
	"SYSADMIN_USER" VARCHAR2(1020),
	"TIMEZONE" VARCHAR2(40),
	"URL" VARCHAR2(1020)
);

	ALTER TABLE "ORGANIZATION"
		ADD CONSTRAINT "ORGANIZATION_PK"
	PRIMARY KEY ("ORGID");
CREATE INDEX "SYS_C0040783" ON "ORGANIZATION" ("NAME");
CREATE SEQUENCE "ORGANIZATION_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;
CREATE INDEX "SYS_C0040783" ON "ORGANIZATION" ("NAME");

ALTER TABLE "ORGANIZATION" ADD CONSTRAINT "ORGANIZATION_FK_1" FOREIGN KEY ("FACILITYID") REFERENCES "ORGANIZATION" ("ORGID");

ALTER TABLE "ORGANIZATION" ADD CONSTRAINT "ORGANIZATION_FK_2" FOREIGN KEY ("PARENT_ORG_ID") REFERENCES "ORGANIZATION" ("ORGID") ON DELETE CASCADE;

ALTER TABLE "ORGANIZATION" ADD CONSTRAINT "ORGANIZATION_FK_3" FOREIGN KEY ("SENSOR_MANIFEST_ID") REFERENCES "SENSOR_MANIFEST" ("ID") ON DELETE SET NULL;


/* -----------------------------------------------------------------------
   PERSON
   ----------------------------------------------------------------------- */

DROP TABLE "PERSON" CASCADE CONSTRAINTS;

DROP SEQUENCE "PERSON_SEQ";


CREATE TABLE "PERSON"
(
	"ID" NUMBER(22)  NOT NULL,
	"ADDRESS" VARCHAR2(1020),
	"ADMIN_STATUS" NUMBER(22),
	"CATEGORY" VARCHAR2(104),
	"COMMENTS" VARCHAR2(1020),
	"E_MAIL" VARCHAR2(1020),
	"FAX" VARCHAR2(80),
	"FIRST_NAME" VARCHAR2(400),
	"LAST_NAME" VARCHAR2(400),
	"PHONE" VARCHAR2(120),
	"USER_NAME" VARCHAR2(400)
);

	ALTER TABLE "PERSON"
		ADD CONSTRAINT "PERSON_PK"
	PRIMARY KEY ("ID");
CREATE INDEX "SYS_C0040796" ON "PERSON" ("USER_NAME");
CREATE SEQUENCE "PERSON_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;
CREATE INDEX "SYS_C0040796" ON "PERSON" ("USER_NAME");


/* -----------------------------------------------------------------------
   PERSON_ENTITY_ROLE
   ----------------------------------------------------------------------- */

DROP TABLE "PERSON_ENTITY_ROLE" CASCADE CONSTRAINTS;

DROP SEQUENCE "PERSON_ENTITY_ROLE_SEQ";


CREATE TABLE "PERSON_ENTITY_ROLE"
(
	"ID" NUMBER(22)  NOT NULL,
	"ENTITY_ID" NUMBER(22),
	"ENTITY_TYPE_ID" NUMBER(22),
	"PERSON_ID" NUMBER(22),
	"ROLE_ID" NUMBER(22)
);

	ALTER TABLE "PERSON_ENTITY_ROLE"
		ADD CONSTRAINT "PERSON_ENTITY_ROLE_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "PERSON_ENTITY_ROLE_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;

ALTER TABLE "PERSON_ENTITY_ROLE" ADD CONSTRAINT "PERSON_ENTITY_ROLE_FK_1" FOREIGN KEY ("ENTITY_TYPE_ID") REFERENCES "ENTITY_TYPE" ("ID") ON DELETE CASCADE;

ALTER TABLE "PERSON_ENTITY_ROLE" ADD CONSTRAINT "PERSON_ENTITY_ROLE_FK_2" FOREIGN KEY ("PERSON_ID") REFERENCES "PERSON" ("ID") ON DELETE CASCADE;

ALTER TABLE "PERSON_ENTITY_ROLE" ADD CONSTRAINT "PERSON_ENTITY_ROLE_FK_3" FOREIGN KEY ("ROLE_ID") REFERENCES "ROLE" ("ID") ON DELETE CASCADE;


/* -----------------------------------------------------------------------
   PROJECT
   ----------------------------------------------------------------------- */

DROP TABLE "PROJECT" CASCADE CONSTRAINTS;

DROP SEQUENCE "PROJECT_SEQ";


CREATE TABLE "PROJECT"
(
	"PROJID" NUMBER(22)  NOT NULL,
	"CONTACT_EMAIL" VARCHAR2(1020)  NOT NULL,
	"CONTACT_NAME" VARCHAR2(1020)  NOT NULL,
	"CURATION_STATUS" VARCHAR2(40),
	"DELETED" NUMBER(22),
	"DESCRIPTION" CLOB,
	"END_DATE" DATE,
	"FUNDORG" VARCHAR2(400),
	"FUNDORGPROJID" VARCHAR2(400),
	"NEES" NUMBER(22),
	"NSFTITLE" VARCHAR2(1020),
	"NAME" VARCHAR2(64),
	"NICKNAME" VARCHAR2(400)  NOT NULL,
	"SHORT_TITLE" VARCHAR2(400),
	"START_DATE" DATE,
	"STATUS" VARCHAR2(44),
	"SYSADMIN_EMAIL" VARCHAR2(1020),
	"SYSADMIN_NAME" VARCHAR2(1020),
	"TITLE" VARCHAR2(1020)  NOT NULL,
	"VIEWABLE" VARCHAR2(28),
	"CREATOR_ID" NUMBER(22),
	"SUPER_PROJECT_ID" NUMBER(22),
	"PROJECT_TYPE_ID" NUMBER(22) default 0
);

	ALTER TABLE "PROJECT"
		ADD CONSTRAINT "PROJECT_PK"
	PRIMARY KEY ("PROJID");
CREATE SEQUENCE "PROJECT_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;

ALTER TABLE "PROJECT" ADD CONSTRAINT "PROJECT_FK_1" FOREIGN KEY ("SUPER_PROJECT_ID") REFERENCES "PROJECT" ("PROJID") ON DELETE SET NULL;

ALTER TABLE "PROJECT" ADD CONSTRAINT "PROJECT_FK_2" FOREIGN KEY ("CREATOR_ID") REFERENCES "PERSON" ("ID") ON DELETE SET NULL;


/* -----------------------------------------------------------------------
   PROJECT_ORGANIZATION
   ----------------------------------------------------------------------- */

DROP TABLE "PROJECT_ORGANIZATION" CASCADE CONSTRAINTS;

DROP SEQUENCE "PROJECT_ORGANIZATION_SEQ";


CREATE TABLE "PROJECT_ORGANIZATION"
(
	"ID" NUMBER(22)  NOT NULL,
	"ORGID" NUMBER(22),
	"PROJID" NUMBER(22)
);

	ALTER TABLE "PROJECT_ORGANIZATION"
		ADD CONSTRAINT "PROJECT_ORGANIZATION_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "PROJECT_ORGANIZATION_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;

ALTER TABLE "PROJECT_ORGANIZATION" ADD CONSTRAINT "PROJECT_ORGANIZATION_FK_1" FOREIGN KEY ("ORGID") REFERENCES "ORGANIZATION" ("ORGID") ON DELETE CASCADE;

ALTER TABLE "PROJECT_ORGANIZATION" ADD CONSTRAINT "PROJECT_ORGANIZATION_FK_2" FOREIGN KEY ("PROJID") REFERENCES "PROJECT" ("PROJID") ON DELETE CASCADE;


/* -----------------------------------------------------------------------
   REPETITION
   ----------------------------------------------------------------------- */

DROP TABLE "REPETITION" CASCADE CONSTRAINTS;

DROP SEQUENCE "REPETITION_SEQ";


CREATE TABLE "REPETITION"
(
	"REPID" NUMBER(22)  NOT NULL,
	"CURATION_STATUS" VARCHAR2(40),
	"DELETED" NUMBER(22),
	"END_DATE" DATE,
	"NAME" VARCHAR2(64),
	"START_DATE" DATE,
	"STATUS" VARCHAR2(400),
	"TRIALID" NUMBER(22)
);

	ALTER TABLE "REPETITION"
		ADD CONSTRAINT "REPETITION_PK"
	PRIMARY KEY ("REPID");
CREATE SEQUENCE "REPETITION_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;

ALTER TABLE "REPETITION" ADD CONSTRAINT "REPETITION_FK_1" FOREIGN KEY ("TRIALID") REFERENCES "TRIAL" ("TRIALID") ON DELETE CASCADE;


/* -----------------------------------------------------------------------
   ROLE
   ----------------------------------------------------------------------- */

DROP TABLE "ROLE" CASCADE CONSTRAINTS;

DROP SEQUENCE "ROLE_SEQ";


CREATE TABLE "ROLE"
(
	"ID" NUMBER(22)  NOT NULL,
	"DEFAULT_PERMISSIONS" VARCHAR2(112),
	"ENTITY_TYPE_ID" NUMBER(22),
	"DISPLAY_NAME" VARCHAR2(255),
	"SYSTEM_NAME" VARCHAR2(255),
	"SUPER_ROLE" NUMBER(22)
);

	ALTER TABLE "ROLE"
		ADD CONSTRAINT "ROLE_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "ROLE_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;

ALTER TABLE "ROLE" ADD CONSTRAINT "ROLE_FK_1" FOREIGN KEY ("ENTITY_TYPE_ID") REFERENCES "ENTITY_TYPE" ("ID") ON DELETE CASCADE;


/* -----------------------------------------------------------------------
   SENSOR
   ----------------------------------------------------------------------- */

DROP TABLE "SENSOR" CASCADE CONSTRAINTS;

DROP SEQUENCE "SENSOR_SEQ";


CREATE TABLE "SENSOR"
(
	"SENSOR_ID" NUMBER(22)  NOT NULL,
	"COMMISSION_DATE" DATE,
	"DECOMMISSION_DATE" DATE,
	"DELETED" NUMBER(22),
	"LOCAL_ID" VARCHAR2(200),
	"NAME" VARCHAR2(200),
	"SENSOR_MODEL_ID" NUMBER(22),
	"SERIAL_NUMBER" VARCHAR2(200),
	"SUPPLIER" VARCHAR2(200)
);

	ALTER TABLE "SENSOR"
		ADD CONSTRAINT "SENSOR_PK"
	PRIMARY KEY ("SENSOR_ID");
CREATE SEQUENCE "SENSOR_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;

ALTER TABLE "SENSOR" ADD CONSTRAINT "SENSOR_FK_1" FOREIGN KEY ("SENSOR_MODEL_ID") REFERENCES "SENSOR_MODEL" ("SENSOR_MODEL_ID") ON DELETE SET NULL;


/* -----------------------------------------------------------------------
   SENSOR_ATTRIBUTE
   ----------------------------------------------------------------------- */

DROP TABLE "SENSOR_ATTRIBUTE" CASCADE CONSTRAINTS;

DROP SEQUENCE "SENSOR_ATTRIBUTE_SEQ";


CREATE TABLE "SENSOR_ATTRIBUTE"
(
	"ID" NUMBER(22)  NOT NULL,
	"ATTRIBUTE_ID" NUMBER(22),
	"DATE_VALUE" DATE,
	"GROUP_VALUE" NUMBER(22),
	"INT_VALUE" NUMBER(22),
	"NOTE" CLOB,
	"NUM_VALUE" FLOAT(22),
	"PAGE_COUNT" NUMBER(22),
	"SENSOR_ID" NUMBER(22),
	"STRING_VALUE" CLOB,
	"UNIT_ID" NUMBER(22)
);

	ALTER TABLE "SENSOR_ATTRIBUTE"
		ADD CONSTRAINT "SENSOR_ATTRIBUTE_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "SENSOR_ATTRIBUTE_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;

ALTER TABLE "SENSOR_ATTRIBUTE" ADD CONSTRAINT "SENSOR_ATTRIBUTE_FK_1" FOREIGN KEY ("ATTRIBUTE_ID") REFERENCES "ATTRIBUTE" ("ATTRIBUTE_ID") ON DELETE CASCADE;

ALTER TABLE "SENSOR_ATTRIBUTE" ADD CONSTRAINT "SENSOR_ATTRIBUTE_FK_2" FOREIGN KEY ("SENSOR_ID") REFERENCES "SENSOR" ("SENSOR_ID") ON DELETE CASCADE;

ALTER TABLE "SENSOR_ATTRIBUTE" ADD CONSTRAINT "SENSOR_ATTRIBUTE_FK_3" FOREIGN KEY ("UNIT_ID") REFERENCES "UNIT" ("UNIT_ID") ON DELETE CASCADE;


/* -----------------------------------------------------------------------
   SENSOR_GROUPED_ATTRIBUTE
   ----------------------------------------------------------------------- */

DROP TABLE "SENSOR_GROUPED_ATTRIBUTE" CASCADE CONSTRAINTS;

DROP SEQUENCE "SNSR_GRPD_TTRBT_SEQ";


CREATE TABLE "SENSOR_GROUPED_ATTRIBUTE"
(
	"ID" NUMBER(22)  NOT NULL,
	"ATTRIBUTE_ID" NUMBER(22),
	"DATE_VALUE" DATE,
	"G_ATTRIBUTE_ID" NUMBER(22),
	"INT_VALUE" NUMBER(22),
	"NOTE" CLOB,
	"NUM_VALUE" FLOAT(22),
	"PAGE_COUNT" NUMBER(22),
	"STRING_VALUE" CLOB,
	"UNIT_ID" NUMBER(22)
);

	ALTER TABLE "SENSOR_GROUPED_ATTRIBUTE"
		ADD CONSTRAINT "SENSOR_GROUPED_ATTRIBUTE_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "SNSR_GRPD_TTRBT_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;

ALTER TABLE "SENSOR_GROUPED_ATTRIBUTE" ADD CONSTRAINT "SENSOR_GROUPED_ATTRIBUTE_FK_1" FOREIGN KEY ("ATTRIBUTE_ID") REFERENCES "ATTRIBUTE" ("ATTRIBUTE_ID") ON DELETE CASCADE;


/* -----------------------------------------------------------------------
   SENSOR_GROUPED_ATTRIBUTE_MAP
   ----------------------------------------------------------------------- */

DROP TABLE "SENSOR_GROUPED_ATTRIBUTE_MAP" CASCADE CONSTRAINTS;

DROP SEQUENCE "SNSR_GRPD_TTRBT_MP_SEQ";


CREATE TABLE "SENSOR_GROUPED_ATTRIBUTE_MAP"
(
	"ID" NUMBER(22)  NOT NULL,
	"G_ATTRIBUTE_ID" NUMBER(22),
	"GROUP_VALUE" NUMBER(22)
);

	ALTER TABLE "SENSOR_GROUPED_ATTRIBUTE_MAP"
		ADD CONSTRAINT "SENSOR_GROUPED_ATTRIBUTE_MA_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "SNSR_GRPD_TTRBT_MP_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;


/* -----------------------------------------------------------------------
   SENSOR_MANIFEST
   ----------------------------------------------------------------------- */

DROP TABLE "SENSOR_MANIFEST" CASCADE CONSTRAINTS;

DROP SEQUENCE "SENSOR_MANIFEST_SEQ";


CREATE TABLE "SENSOR_MANIFEST"
(
	"ID" NUMBER(22)  NOT NULL,
	"NAME" VARCHAR2(1020)
);

	ALTER TABLE "SENSOR_MANIFEST"
		ADD CONSTRAINT "SENSOR_MANIFEST_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "SENSOR_MANIFEST_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;


/* -----------------------------------------------------------------------
   SENSOR_MODEL
   ----------------------------------------------------------------------- */

DROP TABLE "SENSOR_MODEL" CASCADE CONSTRAINTS;

DROP SEQUENCE "SENSOR_MODEL_SEQ";


CREATE TABLE "SENSOR_MODEL"
(
	"SENSOR_MODEL_ID" NUMBER(22)  NOT NULL,
	"DELETED" NUMBER(22),
	"DESCRIPTION" VARCHAR2(1020),
	"MANUFACTURER" VARCHAR2(200),
	"MAX_MEASURED_VALUE" FLOAT(22),
	"MAX_OP_TEMP" NUMBER(22),
	"MEASURED_VALUE_UNITS_ID" NUMBER(22),
	"MIN_MEASURED_VALUE" FLOAT(22),
	"MIN_OP_TEMP" NUMBER(22),
	"MODEL" VARCHAR2(200),
	"NAME" VARCHAR2(200),
	"NOTE" VARCHAR2(1020),
	"SENSITIVITY" FLOAT(22),
	"SENSITIVITY_UNITS_ID" NUMBER(22),
	"SENSOR_TYPE_ID" NUMBER(22),
	"SIGNAL_TYPE" VARCHAR2(200),
	"TEMP_UNITS_ID" NUMBER(22)
);

	ALTER TABLE "SENSOR_MODEL"
		ADD CONSTRAINT "SENSOR_MODEL_PK"
	PRIMARY KEY ("SENSOR_MODEL_ID");
CREATE INDEX "IDX_SENS_MOD_NAME" ON "SENSOR_MODEL" ("NAME");
CREATE INDEX "IDX_SENS_MOD_SENSORTYPEID" ON "SENSOR_MODEL" ("SENSOR_TYPE_ID");
CREATE SEQUENCE "SENSOR_MODEL_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;
CREATE INDEX "IDX_SENS_MOD_NAME" ON "SENSOR_MODEL" ("NAME");
CREATE INDEX "IDX_SENS_MOD_SENSORTYPEID" ON "SENSOR_MODEL" ("SENSOR_TYPE_ID");

ALTER TABLE "SENSOR_MODEL" ADD CONSTRAINT "SENSOR_MODEL_FK_1" FOREIGN KEY ("SENSOR_TYPE_ID") REFERENCES "SENSOR_TYPE" ("ID") ON DELETE CASCADE;

ALTER TABLE "SENSOR_MODEL" ADD CONSTRAINT "SENSOR_MODEL_FK_2" FOREIGN KEY ("MEASURED_VALUE_UNITS_ID") REFERENCES "MEASUREMENT_UNIT" ("ID") ON DELETE CASCADE;

ALTER TABLE "SENSOR_MODEL" ADD CONSTRAINT "SENSOR_MODEL_FK_3" FOREIGN KEY ("SENSITIVITY_UNITS_ID") REFERENCES "MEASUREMENT_UNIT" ("ID") ON DELETE CASCADE;

ALTER TABLE "SENSOR_MODEL" ADD CONSTRAINT "SENSOR_MODEL_FK_4" FOREIGN KEY ("TEMP_UNITS_ID") REFERENCES "MEASUREMENT_UNIT" ("ID") ON DELETE CASCADE;


/* -----------------------------------------------------------------------
   SENSOR_MODEL_DATA_FILE
   ----------------------------------------------------------------------- */

DROP TABLE "SENSOR_MODEL_DATA_FILE" CASCADE CONSTRAINTS;

DROP SEQUENCE "SNSR_MDL_DT_FL_SEQ";


CREATE TABLE "SENSOR_MODEL_DATA_FILE"
(
	"ID" NUMBER(22)  NOT NULL,
	"DATA_FILE_ID" NUMBER(22),
	"SENSOR_MODEL_ID" NUMBER(22)
);

	ALTER TABLE "SENSOR_MODEL_DATA_FILE"
		ADD CONSTRAINT "SENSOR_MODEL_DATA_FILE_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "SNSR_MDL_DT_FL_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;

ALTER TABLE "SENSOR_MODEL_DATA_FILE" ADD CONSTRAINT "SENSOR_MODEL_DATA_FILE_FK_1" FOREIGN KEY ("DATA_FILE_ID") REFERENCES "DATA_FILE" ("ID") ON DELETE CASCADE;

ALTER TABLE "SENSOR_MODEL_DATA_FILE" ADD CONSTRAINT "SENSOR_MODEL_DATA_FILE_FK_2" FOREIGN KEY ("SENSOR_MODEL_ID") REFERENCES "SENSOR_MODEL" ("SENSOR_MODEL_ID") ON DELETE CASCADE;


/* -----------------------------------------------------------------------
   SENSOR_POOL
   ----------------------------------------------------------------------- */

DROP TABLE "SENSOR_POOL" CASCADE CONSTRAINTS;

DROP SEQUENCE "SENSOR_POOL_SEQ";


CREATE TABLE "SENSOR_POOL"
(
	"ID" NUMBER(22)  NOT NULL,
	"EXP_ID" NUMBER(22),
	"MANIFEST_ID" NUMBER(22)
);

	ALTER TABLE "SENSOR_POOL"
		ADD CONSTRAINT "SENSOR_POOL_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "SENSOR_POOL_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;

ALTER TABLE "SENSOR_POOL" ADD CONSTRAINT "SENSOR_POOL_FK_1" FOREIGN KEY ("EXP_ID") REFERENCES "EXPERIMENT" ("EXPID") ON DELETE CASCADE;

ALTER TABLE "SENSOR_POOL" ADD CONSTRAINT "SENSOR_POOL_FK_2" FOREIGN KEY ("MANIFEST_ID") REFERENCES "SENSOR_MANIFEST" ("ID") ON DELETE CASCADE;


/* -----------------------------------------------------------------------
   SENSOR_SENSOR_MANIFEST
   ----------------------------------------------------------------------- */

DROP TABLE "SENSOR_SENSOR_MANIFEST" CASCADE CONSTRAINTS;

DROP SEQUENCE "SNSR_SNSR_MNFST_SEQ";


CREATE TABLE "SENSOR_SENSOR_MANIFEST"
(
	"ID" NUMBER(22)  NOT NULL,
	"SENSOR_ID" NUMBER(22),
	"MANIFEST_ID" NUMBER(22)
);

	ALTER TABLE "SENSOR_SENSOR_MANIFEST"
		ADD CONSTRAINT "SENSOR_SENSOR_MANIFEST_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "SNSR_SNSR_MNFST_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;

ALTER TABLE "SENSOR_SENSOR_MANIFEST" ADD CONSTRAINT "SENSOR_SENSOR_MANIFEST_FK_1" FOREIGN KEY ("SENSOR_ID") REFERENCES "SENSOR" ("SENSOR_ID") ON DELETE CASCADE;

ALTER TABLE "SENSOR_SENSOR_MANIFEST" ADD CONSTRAINT "SENSOR_SENSOR_MANIFEST_FK_2" FOREIGN KEY ("MANIFEST_ID") REFERENCES "SENSOR_MANIFEST" ("ID") ON DELETE CASCADE;


/* -----------------------------------------------------------------------
   SENSOR_TYPE
   ----------------------------------------------------------------------- */

DROP TABLE "SENSOR_TYPE" CASCADE CONSTRAINTS;

DROP SEQUENCE "SENSOR_TYPE_SEQ";


CREATE TABLE "SENSOR_TYPE"
(
	"ID" NUMBER(22)  NOT NULL,
	"NAME" VARCHAR2(1020)
);

	ALTER TABLE "SENSOR_TYPE"
		ADD CONSTRAINT "SENSOR_TYPE_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "SENSOR_TYPE_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;


/* -----------------------------------------------------------------------
   SIMILITUDE_LAW
   ----------------------------------------------------------------------- */

DROP TABLE "SIMILITUDE_LAW" CASCADE CONSTRAINTS;

DROP SEQUENCE "SIMILITUDE_LAW_SEQ";


CREATE TABLE "SIMILITUDE_LAW"
(
	"ID" NUMBER(22)  NOT NULL,
	"COMPUTE_EQUATION" VARCHAR2(1020),
	"DEPENDENCE" VARCHAR2(48),
	"DESCRIPTION" VARCHAR2(1020),
	"DISPLAY_EQUATION" VARCHAR2(512),
	"NAME" VARCHAR2(128),
	"SIMILITUDE_LAW_GROUP_ID" NUMBER(22),
	"SYMBOL" VARCHAR2(128),
	"SYSTEM_NAME" VARCHAR2(128),
	"UNIT_DESCRIPTION" VARCHAR2(256)
);

	ALTER TABLE "SIMILITUDE_LAW"
		ADD CONSTRAINT "SIMILITUDE_LAW_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "SIMILITUDE_LAW_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;

ALTER TABLE "SIMILITUDE_LAW" ADD CONSTRAINT "SIMILITUDE_LAW_FK_1" FOREIGN KEY ("SIMILITUDE_LAW_GROUP_ID") REFERENCES "SIMILITUDE_LAW_GROUP" ("ID") ON DELETE CASCADE;


/* -----------------------------------------------------------------------
   SIMILITUDE_LAW_GROUP
   ----------------------------------------------------------------------- */

DROP TABLE "SIMILITUDE_LAW_GROUP" CASCADE CONSTRAINTS;

DROP SEQUENCE "SIMILITUDE_LAW_GROUP_SEQ";


CREATE TABLE "SIMILITUDE_LAW_GROUP"
(
	"ID" NUMBER(22)  NOT NULL,
	"EXPERIMENT_DOMAIN_ID" NUMBER(22),
	"NAME" VARCHAR2(512),
	"SYSTEM_NAME" VARCHAR2(256)
);

	ALTER TABLE "SIMILITUDE_LAW_GROUP"
		ADD CONSTRAINT "SIMILITUDE_LAW_GROUP_PK"
	PRIMARY KEY ("ID");
CREATE INDEX "SYS_C0040889" ON "SIMILITUDE_LAW_GROUP" ("SYSTEM_NAME");
CREATE SEQUENCE "SIMILITUDE_LAW_GROUP_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;
CREATE INDEX "SYS_C0040889" ON "SIMILITUDE_LAW_GROUP" ("SYSTEM_NAME");

ALTER TABLE "SIMILITUDE_LAW_GROUP" ADD CONSTRAINT "SIMILITUDE_LAW_GROUP_FK_1" FOREIGN KEY ("EXPERIMENT_DOMAIN_ID") REFERENCES "EXPERIMENT_DOMAIN" ("ID") ON DELETE CASCADE;


/* -----------------------------------------------------------------------
   SIMILITUDE_LAW_VALUE
   ----------------------------------------------------------------------- */

DROP TABLE "SIMILITUDE_LAW_VALUE" CASCADE CONSTRAINTS;

DROP SEQUENCE "SIMILITUDE_LAW_VALUE_SEQ";


CREATE TABLE "SIMILITUDE_LAW_VALUE"
(
	"ID" NUMBER(22)  NOT NULL,
	"COMMENTS" VARCHAR2(1020),
	"EXPID" NUMBER(22),
	"SIMILITUDE_LAW_ID" NUMBER(22),
	"VALUE" FLOAT(22)
);

	ALTER TABLE "SIMILITUDE_LAW_VALUE"
		ADD CONSTRAINT "SIMILITUDE_LAW_VALUE_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "SIMILITUDE_LAW_VALUE_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;

ALTER TABLE "SIMILITUDE_LAW_VALUE" ADD CONSTRAINT "SIMILITUDE_LAW_VALUE_FK_1" FOREIGN KEY ("EXPID") REFERENCES "EXPERIMENT" ("EXPID") ON DELETE CASCADE;

ALTER TABLE "SIMILITUDE_LAW_VALUE" ADD CONSTRAINT "SIMILITUDE_LAW_VALUE_FK_2" FOREIGN KEY ("SIMILITUDE_LAW_ID") REFERENCES "SIMILITUDE_LAW" ("ID") ON DELETE CASCADE;


/* -----------------------------------------------------------------------
   SIMULATION_TYPE
   ----------------------------------------------------------------------- */

DROP TABLE "SIMULATION_TYPE" CASCADE CONSTRAINTS;

DROP SEQUENCE "SIMULATION_TYPE_SEQ";


CREATE TABLE "SIMULATION_TYPE"
(
	"ID" NUMBER(22)  NOT NULL,
	"NAME" VARCHAR2(400)
);

	ALTER TABLE "SIMULATION_TYPE"
		ADD CONSTRAINT "SIMULATION_TYPE_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "SIMULATION_TYPE_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;


/* -----------------------------------------------------------------------
   SOURCE_TYPE
   ----------------------------------------------------------------------- */

DROP TABLE "SOURCE_TYPE" CASCADE CONSTRAINTS;

DROP SEQUENCE "SOURCE_TYPE_SEQ";


CREATE TABLE "SOURCE_TYPE"
(
	"ID" NUMBER(22)  NOT NULL,
	"NAME" VARCHAR2(128),
	"SYSTEM_NAME" VARCHAR2(128)
);

	ALTER TABLE "SOURCE_TYPE"
		ADD CONSTRAINT "SOURCE_TYPE_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "SOURCE_TYPE_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;


/* -----------------------------------------------------------------------
   THUMBNAIL
   ----------------------------------------------------------------------- */

DROP TABLE "THUMBNAIL" CASCADE CONSTRAINTS;

DROP SEQUENCE "THUMBNAIL_SEQ";


CREATE TABLE "THUMBNAIL"
(
	"ID" NUMBER(22)  NOT NULL,
	"DATAFILE_ID" NUMBER(22),
	"ENTITY_ID" NUMBER(22),
	"ENTITY_TYPE_ID" NUMBER(22)
);

	ALTER TABLE "THUMBNAIL"
		ADD CONSTRAINT "THUMBNAIL_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "THUMBNAIL_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;

ALTER TABLE "THUMBNAIL" ADD CONSTRAINT "THUMBNAIL_FK_1" FOREIGN KEY ("DATAFILE_ID") REFERENCES "DATA_FILE" ("ID") ON DELETE CASCADE;

ALTER TABLE "THUMBNAIL" ADD CONSTRAINT "THUMBNAIL_FK_2" FOREIGN KEY ("ENTITY_TYPE_ID") REFERENCES "ENTITY_TYPE" ("ID") ON DELETE CASCADE;


/* -----------------------------------------------------------------------
   TRIAL
   ----------------------------------------------------------------------- */

DROP TABLE "TRIAL" CASCADE CONSTRAINTS;

DROP SEQUENCE "TRIAL_SEQ";


CREATE TABLE "TRIAL"
(
	"TRIALID" NUMBER(22)  NOT NULL,
	"ACCELERATION" FLOAT(22),
	"BASE_ACCELERATION" FLOAT(22),
	"BASE_ACCELERATION_UNIT_ID" NUMBER(22),
	"COMPONENT" VARCHAR2(1020),
	"CURATION_STATUS" VARCHAR2(40),
	"DELETED" NUMBER(22),
	"DESCRIPTION" CLOB,
	"END_DATE" DATE,
	"EXPID" NUMBER(22),
	"MOTION_FILE_ID" NUMBER(22),
	"MOTION_NAME" VARCHAR2(1020),
	"NAME" VARCHAR2(64),
	"OBJECTIVE" CLOB,
	"START_DATE" DATE,
	"STATION" VARCHAR2(1020),
	"STATUS" VARCHAR2(400),
	"TITLE" VARCHAR2(1020)  NOT NULL,
	"TRIAL_TYPE_ID" NUMBER(22) default 0
);

	ALTER TABLE "TRIAL"
		ADD CONSTRAINT "TRIAL_PK"
	PRIMARY KEY ("TRIALID");
CREATE SEQUENCE "TRIAL_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;

ALTER TABLE "TRIAL" ADD CONSTRAINT "TRIAL_FK_1" FOREIGN KEY ("MOTION_FILE_ID") REFERENCES "DATA_FILE" ("ID") ON DELETE SET NULL;

ALTER TABLE "TRIAL" ADD CONSTRAINT "TRIAL_FK_2" FOREIGN KEY ("EXPID") REFERENCES "EXPERIMENT" ("EXPID") ON DELETE CASCADE;

ALTER TABLE "TRIAL" ADD CONSTRAINT "TRIAL_FK_3" FOREIGN KEY ("BASE_ACCELERATION_UNIT_ID") REFERENCES "MEASUREMENT_UNIT" ("ID") ON DELETE SET NULL;


/* -----------------------------------------------------------------------
   UNIT
   ----------------------------------------------------------------------- */

DROP TABLE "UNIT" CASCADE CONSTRAINTS;

DROP SEQUENCE "UNIT_SEQ";


CREATE TABLE "UNIT"
(
	"UNIT_ID" NUMBER(22)  NOT NULL,
	"BASE_ID" NUMBER(22),
	"CONVERSION" FLOAT(22),
	"DESCRIPTION" VARCHAR2(1020),
	"NAME" VARCHAR2(256),
	"SYMBOL" VARCHAR2(512),
	"UNICODE" VARCHAR2(1020)
);

	ALTER TABLE "UNIT"
		ADD CONSTRAINT "UNIT_PK"
	PRIMARY KEY ("UNIT_ID");
CREATE SEQUENCE "UNIT_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;

ALTER TABLE "UNIT" ADD CONSTRAINT "UNIT_FK_1" FOREIGN KEY ("BASE_ID") REFERENCES "UNIT" ("UNIT_ID");


/* -----------------------------------------------------------------------
   ANNOTATION
   ----------------------------------------------------------------------- */

DROP TABLE "ANNOTATION" CASCADE CONSTRAINTS;


CREATE TABLE "ANNOTATION"
(
	"ID" NUMBER(22)  NOT NULL,
	"CREATOR_ID" NUMBER(22),
	"KEY" VARCHAR2(64),
	"MESSAGE" VARCHAR2(4000),
	"SUBJECT_TYPE_ID" NUMBER(22),
	"SUBJECT_ID" NUMBER(22),
	"OBJECT_TYPE_ID" NUMBER(22),
	"OBJECT_ID" NUMBER(22)
);

	ALTER TABLE "ANNOTATION"
		ADD CONSTRAINT "ANNOTATION_PK"
	PRIMARY KEY ("ID");

ALTER TABLE "ANNOTATION" ADD CONSTRAINT "ANNOTATION_FK_1" FOREIGN KEY ("CREATOR_ID") REFERENCES "PERSON" ("ID") ON DELETE CASCADE;

ALTER TABLE "ANNOTATION" ADD CONSTRAINT "ANNOTATION_FK_2" FOREIGN KEY ("SUBJECT_TYPE_ID") REFERENCES "ENTITY_TYPE" ("ID") ON DELETE CASCADE;

ALTER TABLE "ANNOTATION" ADD CONSTRAINT "ANNOTATION_FK_3" FOREIGN KEY ("OBJECT_TYPE_ID") REFERENCES "ENTITY_TYPE" ("ID") ON DELETE CASCADE;


/* -----------------------------------------------------------------------
   PROJECT_HOMEPAGE
   ----------------------------------------------------------------------- */

DROP TABLE "PROJECT_HOMEPAGE" CASCADE CONSTRAINTS;

DROP SEQUENCE "PROJECT_HOMEPAGE_SEQ";


CREATE TABLE "PROJECT_HOMEPAGE"
(
	"ID" NUMBER(22)  NOT NULL,
	"PROJECT_ID" NUMBER(22)  NOT NULL,
	"DATA_FILE_ID" NUMBER(22)  NOT NULL,
	"CAPTION" VARCHAR2(255),
	"DESCRIPTION" VARCHAR2(1023),
	"URL" VARCHAR2(255),
	"PROJECT_HOMEPAGE_TYPE_ID" NUMBER(22)  NOT NULL
);

	ALTER TABLE "PROJECT_HOMEPAGE"
		ADD CONSTRAINT "PROJECT_HOMEPAGE_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "PROJECT_HOMEPAGE_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;

ALTER TABLE "PROJECT_HOMEPAGE" ADD CONSTRAINT "PROJECT_HOMEPAGE_FK_1" FOREIGN KEY ("PROJECT_ID") REFERENCES "PROJECT" ("PROJID") ON DELETE CASCADE;

ALTER TABLE "PROJECT_HOMEPAGE" ADD CONSTRAINT "PROJECT_HOMEPAGE_FK_2" FOREIGN KEY ("DATA_FILE_ID") REFERENCES "DATA_FILE" ("ID") ON DELETE CASCADE;


/* -----------------------------------------------------------------------
   SPECIMEN
   ----------------------------------------------------------------------- */

DROP TABLE "SPECIMEN" CASCADE CONSTRAINTS;

DROP SEQUENCE "SPECIMEN_SEQ";


CREATE TABLE "SPECIMEN"
(
	"ID" NUMBER(22)  NOT NULL,
	"PROJID" NUMBER(22)  NOT NULL,
	"NAME" VARCHAR2(125)  NOT NULL,
	"TITLE" VARCHAR2(255)  NOT NULL,
	"DESCRIPTION" VARCHAR2(4000)
);

	ALTER TABLE "SPECIMEN"
		ADD CONSTRAINT "SPECIMEN_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "SPECIMEN_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;

ALTER TABLE "SPECIMEN" ADD CONSTRAINT "SPECIMEN_FK_1" FOREIGN KEY ("PROJID") REFERENCES "PROJECT" ("PROJID") ON DELETE CASCADE;


/* -----------------------------------------------------------------------
   SPECIMEN_COMPONENT
   ----------------------------------------------------------------------- */

DROP TABLE "SPECIMEN_COMPONENT" CASCADE CONSTRAINTS;

DROP SEQUENCE "SPECIMEN_COMP_SEQ";


CREATE TABLE "SPECIMEN_COMPONENT"
(
	"ID" NUMBER(22)  NOT NULL,
	"NAME" VARCHAR2(124)  NOT NULL,
	"TITLE" VARCHAR2(255)  NOT NULL,
	"SPECIMEN_ID" NUMBER(22)  NOT NULL,
	"PARENT_SPEC_COMP_ID" NUMBER(22),
	"DESCRIPTION" VARCHAR2(4000)
);

	ALTER TABLE "SPECIMEN_COMPONENT"
		ADD CONSTRAINT "SPECIMEN_COMPONENT_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "SPECIMEN_COMP_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;

ALTER TABLE "SPECIMEN_COMPONENT" ADD CONSTRAINT "SPECIMEN_COMPONENT_FK_1" FOREIGN KEY ("SPECIMEN_ID") REFERENCES "SPECIMEN" ("ID") ON DELETE CASCADE;

ALTER TABLE "SPECIMEN_COMPONENT" ADD CONSTRAINT "SPECIMEN_COMPONENT_FK_2" FOREIGN KEY ("PARENT_SPEC_COMP_ID") REFERENCES "SPECIMEN_COMPONENT" ("ID") ON DELETE CASCADE;


/* -----------------------------------------------------------------------
   SPECIMEN_COMPONENT_ATTRIBUTE
   ----------------------------------------------------------------------- */

DROP TABLE "SPECIMEN_COMPONENT_ATTRIBUTE" CASCADE CONSTRAINTS;

DROP SEQUENCE "SPECIMEN_COMP_ATTRIB_SEQ";


CREATE TABLE "SPECIMEN_COMPONENT_ATTRIBUTE"
(
	"ID" NUMBER(22)  NOT NULL,
	"SPEC_COMP_ID" NUMBER(22)  NOT NULL,
	"NAME" VARCHAR2(124)  NOT NULL,
	"VALUE" VARCHAR2(124),
	"UNIT_ID" NUMBER(22),
	"DISPLAY_ORDER" NUMBER(22)
);

	ALTER TABLE "SPECIMEN_COMPONENT_ATTRIBUTE"
		ADD CONSTRAINT "SPECIMEN_COMPONENT_ATTRIBUT_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "SPECIMEN_COMP_ATTRIB_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;

ALTER TABLE "SPECIMEN_COMPONENT_ATTRIBUTE" ADD CONSTRAINT "SPECIMEN_COMPONENT_ATTRIB_FK_1" FOREIGN KEY ("SPEC_COMP_ID") REFERENCES "SPECIMEN_COMPONENT" ("ID") ON DELETE CASCADE;

ALTER TABLE "SPECIMEN_COMPONENT_ATTRIBUTE" ADD CONSTRAINT "SPECIMEN_COMPONENT_ATTRIB_FK_2" FOREIGN KEY ("UNIT_ID") REFERENCES "MEASUREMENT_UNIT" ("ID") ON DELETE CASCADE;


/* -----------------------------------------------------------------------
   USER_REQ
   ----------------------------------------------------------------------- */

DROP TABLE "USER_REQ" CASCADE CONSTRAINTS;

DROP SEQUENCE "USER_REQ_SEQ";


CREATE TABLE "USER_REQ"
(
	"ID" NUMBER(22)  NOT NULL,
	"PASSWD" VARCHAR2(200)  NOT NULL,
	"EMAIL" VARCHAR2(255)  NOT NULL,
	"CATEGORY" VARCHAR2(50),
	"FIRST_NAME" VARCHAR2(100)  NOT NULL,
	"LAST_NAME" VARCHAR2(100)  NOT NULL,
	"PHONE" VARCHAR2(30)  NOT NULL,
	"FAX" VARCHAR2(20),
	"ADDRESS" VARCHAR2(255)  NOT NULL,
	"COMMENTS" VARCHAR2(255),
	"ORGID" NUMBER(22),
	"ORG_ROLE_ID" NUMBER(22),
	"EE_ORGANIZATION" VARCHAR2(100)  NOT NULL,
	"PERSONAL_REFERENCE" VARCHAR2(100)  NOT NULL
);

	ALTER TABLE "USER_REQ"
		ADD CONSTRAINT "USER_REQ_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "USER_REQ_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;


/* -----------------------------------------------------------------------
   COORDINATOR
   ----------------------------------------------------------------------- */

DROP TABLE "COORDINATOR" CASCADE CONSTRAINTS;

DROP SEQUENCE "COORDINATOR_SEQ";


CREATE TABLE "COORDINATOR"
(
	"ID" NUMBER(22)  NOT NULL,
	"PROJID" NUMBER(22)  NOT NULL,
	"FACILITY_ID" NUMBER(22)  NOT NULL,
	"NAME" VARCHAR2(128)  NOT NULL,
	"TITLE" VARCHAR2(255)  NOT NULL,
	"DESCRIPTION" VARCHAR2(4000)
);

	ALTER TABLE "COORDINATOR"
		ADD CONSTRAINT "COORDINATOR_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "COORDINATOR_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;

ALTER TABLE "COORDINATOR" ADD CONSTRAINT "COORDINATOR_FK_1" FOREIGN KEY ("PROJID") REFERENCES "PROJECT" ("PROJID") ON DELETE CASCADE;

ALTER TABLE "COORDINATOR" ADD CONSTRAINT "COORDINATOR_FK_2" FOREIGN KEY ("FACILITY_ID") REFERENCES "ORGANIZATION" ("ORGID") ON DELETE CASCADE;


/* -----------------------------------------------------------------------
   COORDINATOR_RUN
   ----------------------------------------------------------------------- */

DROP TABLE "COORDINATOR_RUN" CASCADE CONSTRAINTS;

DROP SEQUENCE "COORDINATOR_RUN_SEQ";


CREATE TABLE "COORDINATOR_RUN"
(
	"ID" NUMBER(22)  NOT NULL,
	"COORDINATOR_ID" NUMBER(22)  NOT NULL,
	"NAME" VARCHAR2(125)  NOT NULL,
	"TITLE" VARCHAR2(255)  NOT NULL,
	"OBJECTIVE" VARCHAR2(2000),
	"DESCRIPTION" VARCHAR2(2000),
	"START_DATE" DATE,
	"END_DATE" DATE
);

	ALTER TABLE "COORDINATOR_RUN"
		ADD CONSTRAINT "COORDINATOR_RUN_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "COORDINATOR_RUN_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;

ALTER TABLE "COORDINATOR_RUN" ADD CONSTRAINT "COORDINATOR_RUN_FK_1" FOREIGN KEY ("COORDINATOR_ID") REFERENCES "COORDINATOR" ("ID") ON DELETE CASCADE;


/* -----------------------------------------------------------------------
   COORDINATOR_RUN_EXPERIMENT
   ----------------------------------------------------------------------- */

DROP TABLE "COORDINATOR_RUN_EXPERIMENT" CASCADE CONSTRAINTS;

DROP SEQUENCE "COORDINATOR_RUN_EXPERIMENT_SEQ";


CREATE TABLE "COORDINATOR_RUN_EXPERIMENT"
(
	"ID" NUMBER(22)  NOT NULL,
	"EXP_ID" NUMBER(22)  NOT NULL,
	"COORDINATOR_RUN_ID" NUMBER(22)  NOT NULL
);

	ALTER TABLE "COORDINATOR_RUN_EXPERIMENT"
		ADD CONSTRAINT "COORDINATOR_RUN_EXPERIMENT_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "COORDINATOR_RUN_EXPERIMENT_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;

ALTER TABLE "COORDINATOR_RUN_EXPERIMENT" ADD CONSTRAINT "COORDINATOR_RUN_EXPERIMEN_FK_1" FOREIGN KEY ("EXP_ID") REFERENCES "EXPERIMENT" ("EXPID") ON DELETE CASCADE;

ALTER TABLE "COORDINATOR_RUN_EXPERIMENT" ADD CONSTRAINT "COORDINATOR_RUN_EXPERIMEN_FK_2" FOREIGN KEY ("COORDINATOR_RUN_ID") REFERENCES "COORDINATOR_RUN" ("ID") ON DELETE CASCADE;


/* -----------------------------------------------------------------------
   SPECCOMP_MATERIAL
   ----------------------------------------------------------------------- */

DROP TABLE "SPECCOMP_MATERIAL" CASCADE CONSTRAINTS;

DROP SEQUENCE "SPECCOMP_MATERIAL_SEQ";


CREATE TABLE "SPECCOMP_MATERIAL"
(
	"ID" NUMBER(22)  NOT NULL,
	"SPECIMEN_COMPONENT_ID" NUMBER(22)  NOT NULL,
	"MATERIAL_TYPE_ID" NUMBER(22)  NOT NULL,
	"PROTOTYPE_MATERIAL_ID" NUMBER(22),
	"NAME" VARCHAR2(125)  NOT NULL,
	"DESCRIPTION" VARCHAR2(2000)
);

	ALTER TABLE "SPECCOMP_MATERIAL"
		ADD CONSTRAINT "SPECCOMP_MATERIAL_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "SPECCOMP_MATERIAL_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;

ALTER TABLE "SPECCOMP_MATERIAL" ADD CONSTRAINT "SPECCOMP_MATERIAL_FK_1" FOREIGN KEY ("SPECIMEN_COMPONENT_ID") REFERENCES "SPECIMEN_COMPONENT" ("ID") ON DELETE CASCADE;

ALTER TABLE "SPECCOMP_MATERIAL" ADD CONSTRAINT "SPECCOMP_MATERIAL_FK_2" FOREIGN KEY ("MATERIAL_TYPE_ID") REFERENCES "MATERIAL_TYPE" ("ID") ON DELETE CASCADE;

ALTER TABLE "SPECCOMP_MATERIAL" ADD CONSTRAINT "SPECCOMP_MATERIAL_FK_3" FOREIGN KEY ("PROTOTYPE_MATERIAL_ID") REFERENCES "SPECCOMP_MATERIAL" ("ID") ON DELETE CASCADE;


/* -----------------------------------------------------------------------
   SPECCOMP_MATERIAL_PROPERTY
   ----------------------------------------------------------------------- */

DROP TABLE "SPECCOMP_MATERIAL_PROPERTY" CASCADE CONSTRAINTS;

DROP SEQUENCE "SPECCOMP_MATERIAL_PROPERTY_SEQ";


CREATE TABLE "SPECCOMP_MATERIAL_PROPERTY"
(
	"ID" NUMBER(22)  NOT NULL,
	"SPECIMEN_COMPONENT_MATERIAL_ID" NUMBER(22)  NOT NULL,
	"MATERIAL_TYPE_PROPERTY_ID" NUMBER(22)  NOT NULL,
	"MEASUREMENT_UNIT_ID" NUMBER(22),
	"VALUE" VARCHAR2(100)
);

	ALTER TABLE "SPECCOMP_MATERIAL_PROPERTY"
		ADD CONSTRAINT "SPECCOMP_MATERIAL_PROPERTY_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "SPECCOMP_MATERIAL_PROPERTY_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;

ALTER TABLE "SPECCOMP_MATERIAL_PROPERTY" ADD CONSTRAINT "SPECCOMP_MATERIAL_PROPERT_FK_1" FOREIGN KEY ("SPECIMEN_COMPONENT_MATERIAL_ID") REFERENCES "SPECCOMP_MATERIAL" ("ID") ON DELETE CASCADE;

ALTER TABLE "SPECCOMP_MATERIAL_PROPERTY" ADD CONSTRAINT "SPECCOMP_MATERIAL_PROPERT_FK_2" FOREIGN KEY ("MATERIAL_TYPE_PROPERTY_ID") REFERENCES "MATERIAL_TYPE_PROPERTY" ("ID") ON DELETE CASCADE;

ALTER TABLE "SPECCOMP_MATERIAL_PROPERTY" ADD CONSTRAINT "SPECCOMP_MATERIAL_PROPERT_FK_3" FOREIGN KEY ("MEASUREMENT_UNIT_ID") REFERENCES "MEASUREMENT_UNIT" ("ID") ON DELETE CASCADE;


/* -----------------------------------------------------------------------
   SPECCOMP_MATERIAL_DATAFILE
   ----------------------------------------------------------------------- */

DROP TABLE "SPECCOMP_MATERIAL_DATAFILE" CASCADE CONSTRAINTS;

DROP SEQUENCE "SPECCOMP_MATERIAL_DATAFILE_SEQ";


CREATE TABLE "SPECCOMP_MATERIAL_DATAFILE"
(
	"ID" NUMBER(22)  NOT NULL,
	"DATA_FILE_ID" NUMBER(22)  NOT NULL,
	"SPECIMEN_COMPONENT_MATERIAL_ID" NUMBER(22)  NOT NULL
);

	ALTER TABLE "SPECCOMP_MATERIAL_DATAFILE"
		ADD CONSTRAINT "SPECCOMP_MATERIAL_DATAFILE_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "SPECCOMP_MATERIAL_DATAFILE_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;

ALTER TABLE "SPECCOMP_MATERIAL_DATAFILE" ADD CONSTRAINT "SPECCOMP_MATERIAL_DATAFIL_FK_1" FOREIGN KEY ("DATA_FILE_ID") REFERENCES "DATA_FILE" ("ID") ON DELETE CASCADE;

ALTER TABLE "SPECCOMP_MATERIAL_DATAFILE" ADD CONSTRAINT "SPECCOMP_MATERIAL_DATAFIL_FK_2" FOREIGN KEY ("SPECIMEN_COMPONENT_MATERIAL_ID") REFERENCES "SPECCOMP_MATERIAL" ("ID") ON DELETE CASCADE;


/* -----------------------------------------------------------------------
   SPECCOMP_EXPERIMENT
   ----------------------------------------------------------------------- */

DROP TABLE "SPECCOMP_EXPERIMENT" CASCADE CONSTRAINTS;

DROP SEQUENCE "SPECCOMP_EXPERIMENT_SEQ";


CREATE TABLE "SPECCOMP_EXPERIMENT"
(
	"ID" NUMBER(22)  NOT NULL,
	"SPECIMEN_COMPONENT_ID" NUMBER(22)  NOT NULL,
	"EXPID" NUMBER(22)  NOT NULL,
	"COORD_RUN_EXP_ID" NUMBER(22)
);

	ALTER TABLE "SPECCOMP_EXPERIMENT"
		ADD CONSTRAINT "SPECCOMP_EXPERIMENT_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "SPECCOMP_EXPERIMENT_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;

ALTER TABLE "SPECCOMP_EXPERIMENT" ADD CONSTRAINT "SPECCOMP_EXPERIMENT_FK_1" FOREIGN KEY ("SPECIMEN_COMPONENT_ID") REFERENCES "SPECIMEN_COMPONENT" ("ID") ON DELETE CASCADE;

ALTER TABLE "SPECCOMP_EXPERIMENT" ADD CONSTRAINT "SPECCOMP_EXPERIMENT_FK_2" FOREIGN KEY ("EXPID") REFERENCES "EXPERIMENT" ("EXPID") ON DELETE CASCADE;

ALTER TABLE "SPECCOMP_EXPERIMENT" ADD CONSTRAINT "SPECCOMP_EXPERIMENT_FK_3" FOREIGN KEY ("COORD_RUN_EXP_ID") REFERENCES "COORDINATOR_RUN_EXPERIMENT" ("ID");


/* -----------------------------------------------------------------------
   DATA_FILE_LINK
   ----------------------------------------------------------------------- */

DROP TABLE "DATA_FILE_LINK" CASCADE CONSTRAINTS;

DROP SEQUENCE "DATA_FILE_LINK_SEQ";


CREATE TABLE "DATA_FILE_LINK"
(
	"ID" NUMBER(22)  NOT NULL,
	"PROJ_ID" NUMBER(22),
	"EXP_ID" NUMBER(22),
	"TRIAL_ID" NUMBER(22),
	"REP_ID" NUMBER(22),
	"DELETED" NUMBER(22)
);

	ALTER TABLE "DATA_FILE_LINK"
		ADD CONSTRAINT "DATA_FILE_LINK_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "DATA_FILE_LINK_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;

ALTER TABLE "DATA_FILE_LINK" ADD CONSTRAINT "DATA_FILE_LINK_FK_1" FOREIGN KEY ("PROJ_ID") REFERENCES "PROJECT" ("PROJID") ON DELETE CASCADE;

ALTER TABLE "DATA_FILE_LINK" ADD CONSTRAINT "DATA_FILE_LINK_FK_2" FOREIGN KEY ("EXP_ID") REFERENCES "EXPERIMENT" ("EXPID") ON DELETE CASCADE;

ALTER TABLE "DATA_FILE_LINK" ADD CONSTRAINT "DATA_FILE_LINK_FK_3" FOREIGN KEY ("TRIAL_ID") REFERENCES "TRIAL" ("TRIALID") ON DELETE CASCADE;

ALTER TABLE "DATA_FILE_LINK" ADD CONSTRAINT "DATA_FILE_LINK_FK_4" FOREIGN KEY ("REP_ID") REFERENCES "REPETITION" ("REPID") ON DELETE CASCADE;


/* -----------------------------------------------------------------------
   RESEARCHER_KEYWORD
   ----------------------------------------------------------------------- */

DROP TABLE "RESEARCHER_KEYWORD" CASCADE CONSTRAINTS;

DROP SEQUENCE "RESEARCHER_KEYWORD_SEQ";


CREATE TABLE "RESEARCHER_KEYWORD"
(
	"ID" NUMBER(22)  NOT NULL,
	"ENTITY_TYPE_ID" NUMBER(22)  NOT NULL,
	"ENTITY_ID" NUMBER(22)  NOT NULL,
	"KEYWORD_TERM" VARCHAR2(128)  NOT NULL,
	"CREATED_DT" DATE(22)  NOT NULL,
	"CREATED_BY" VARCHAR2(20)  NOT NULL
);

	ALTER TABLE "RESEARCHER_KEYWORD"
		ADD CONSTRAINT "RESEARCHER_KEYWORD_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "RESEARCHER_KEYWORD_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;

ALTER TABLE "RESEARCHER_KEYWORD" ADD CONSTRAINT "RESEARCHER_KEYWORD_FK_1" FOREIGN KEY ("ENTITY_TYPE_ID") REFERENCES "ENTITY_TYPE" ("ID") ON DELETE CASCADE;


/* -----------------------------------------------------------------------
   SEARCH_LOG
   ----------------------------------------------------------------------- */

DROP TABLE "SEARCH_LOG" CASCADE CONSTRAINTS;

DROP SEQUENCE "SEARCH_LOG_SEQ";


CREATE TABLE "SEARCH_LOG"
(
	"ID" NUMBER(22)  NOT NULL,
	"USERNAME" VARCHAR2(50)  NOT NULL,
	"KEYWORD" VARCHAR2(50)  NOT NULL,
	"QUERY" VARCHAR2(500)  NOT NULL,
	"CREATED_DT" DATE  NOT NULL
);

	ALTER TABLE "SEARCH_LOG"
		ADD CONSTRAINT "SEARCH_LOG_PK"
	PRIMARY KEY ("ID");
CREATE SEQUENCE "SEARCH_LOG_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;


/* -----------------------------------------------------------------------
   ENTITY_ACTIVITY_LOG
   ----------------------------------------------------------------------- */

DROP TABLE "ENTITY_ACTIVITY_LOG" CASCADE CONSTRAINTS;


CREATE TABLE "ENTITY_ACTIVITY_LOG"
(
	"ENTITY_TYPE_ID" NUMBER(22)  NOT NULL,
	"ENTITY_ID" NUMBER(22)  NOT NULL,
	"VIEW_COUNT" NUMBER(22)  NOT NULL,
	"DOWNLOAD_COUNT" NUMBER(22)  NOT NULL
);

ALTER TABLE "ENTITY_ACTIVITY_LOG" ADD CONSTRAINT "ENTITY_ACTIVITY_LOG_FK_1" FOREIGN KEY ("ENTITY_TYPE_ID") REFERENCES "ENTITY_TYPE" ("ID") ON DELETE CASCADE;


/* -----------------------------------------------------------------------
   PROJECT_GRANT
   ----------------------------------------------------------------------- */

DROP TABLE "PROJECT_GRANT" CASCADE CONSTRAINTS;

DROP SEQUENCE "PROJECT_GRANT_SEQ";


CREATE TABLE "PROJECT_GRANT"
(
	"PROJID" NUMBER(22)  NOT NULL,
	"FUND_ORG" VARCHAR2(128)  NOT NULL,
	"AWARD_NUM" VARCHAR2(32)  NOT NULL,
	"AWARD_URL" VARCHAR2(512)  NOT NULL
);
CREATE SEQUENCE "PROJECT_GRANT_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;

ALTER TABLE "PROJECT_GRANT" ADD CONSTRAINT "PROJECT_GRANT_FK_1" FOREIGN KEY ("PROJID") REFERENCES "PROJECT" ("PROJID") ON DELETE CASCADE;
