

/* -----------------------------------------------------------------------
   HOST_REQ
   ----------------------------------------------------------------------- */

DROP TABLE "HOST_REQ" CASCADE CONSTRAINTS;

DROP SEQUENCE "HOST_REQ_SEQ";


CREATE TABLE "HOST_REQ"
(
	"REQID" NUMBER(22)  NOT NULL,
	"COMMENTS" VARCHAR2(1020),
	"EMAIL" VARCHAR2(1020),
	"FIRST_NAME" VARCHAR2(400),
	"HOSTNAME" VARCHAR2(1020),
	"LAST_NAME" VARCHAR2(400),
	"USERNAME" VARCHAR2(400)
);

	ALTER TABLE "HOST_REQ"
		ADD CONSTRAINT "HOST_REQ_PK"
	PRIMARY KEY ("REQID");
CREATE SEQUENCE "HOST_REQ_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;


/* -----------------------------------------------------------------------
   PERMISSION
   ----------------------------------------------------------------------- */

DROP TABLE "PERMISSION" CASCADE CONSTRAINTS;


CREATE TABLE "PERMISSION"
(
	"ID" NUMBER(22)  NOT NULL,
	"PERSON_ID" NUMBER(22),
	"ENTITY_TYPE_ID" NUMBER(22),
	"ENTITY_ID" NUMBER(22),
	"CAN_VIEW" NUMBER(22),
	"CAN_CREATE" NUMBER(22),
	"CAN_EDIT" NUMBER(22),
	"CAN_DELETE" NUMBER(22),
	"CAN_GRANT" NUMBER(22),
	"IS_SUPER_ROLE" NUMBER(22),
	"PERMISSIONS" VARCHAR2(112)
);

	ALTER TABLE "PERMISSION"
		ADD CONSTRAINT "PERMISSION_PK"
	PRIMARY KEY ("ID");

ALTER TABLE "PERMISSION" ADD CONSTRAINT "PERMISSION_FK_1" FOREIGN KEY ("PERSON_ID") REFERENCES "PERSON" ("ID") ON DELETE CASCADE;
