

/* -----------------------------------------------------------------------
   UISTRING
   ----------------------------------------------------------------------- */

DROP TABLE "UISTRING" CASCADE CONSTRAINTS;

DROP SEQUENCE "UISTRING_SEQ";


CREATE TABLE "UISTRING"
(
	"ID" NUMBER(22)  NOT NULL,
	"TKEY" VARCHAR2(256),
	"TYPE" VARCHAR2(128),
	"VALUE" VARCHAR2(2000)  NOT NULL
);

	ALTER TABLE "UISTRING"
		ADD CONSTRAINT "UISTRING_PK"
	PRIMARY KEY ("ID");
CREATE INDEX "SYS_C0041107" ON "UISTRING" ("TKEY");
CREATE SEQUENCE "UISTRING_SEQ" INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE ORDER;
CREATE INDEX "SYS_C0041107" ON "UISTRING" ("TKEY");


/* -----------------------------------------------------------------------
   WEB_LOG_ENTRY
   ----------------------------------------------------------------------- */

DROP TABLE "WEB_LOG_ENTRY" CASCADE CONSTRAINTS;


CREATE TABLE "WEB_LOG_ENTRY"
(
	"ID" NUMBER(22)  NOT NULL,
	"PERSON_ID" NUMBER(22),
	"AUTO_CREATE_DATE" DATE,
	"MESSAGE" VARCHAR2(1024)
);

	ALTER TABLE "WEB_LOG_ENTRY"
		ADD CONSTRAINT "WEB_LOG_ENTRY_PK"
	PRIMARY KEY ("ID");

ALTER TABLE "WEB_LOG_ENTRY" ADD CONSTRAINT "WEB_LOG_ENTRY_FK_1" FOREIGN KEY ("PERSON_ID") REFERENCES "PERSON" ("ID") ON DELETE SET NULL;


/* -----------------------------------------------------------------------
   WEB_LOG_DETAIL
   ----------------------------------------------------------------------- */

DROP TABLE "WEB_LOG_DETAIL" CASCADE CONSTRAINTS;


CREATE TABLE "WEB_LOG_DETAIL"
(
	"ID" NUMBER(22)  NOT NULL,
	"ENTRY_ID" NUMBER(22),
	"TYPE" VARCHAR2(64),
	"KEY" VARCHAR2(64),
	"MESSAGE" VARCHAR2(4000)
);

	ALTER TABLE "WEB_LOG_DETAIL"
		ADD CONSTRAINT "WEB_LOG_DETAIL_PK"
	PRIMARY KEY ("ID");

ALTER TABLE "WEB_LOG_DETAIL" ADD CONSTRAINT "WEB_LOG_DETAIL_FK_1" FOREIGN KEY ("ENTRY_ID") REFERENCES "WEB_LOG_ENTRY" ("ID") ON DELETE CASCADE;
