		<article>
			<h1><span>Adding/Editing</span></h1>

			<div class="section">
				<h2><span>Overview</span></h2>

				<p>You will be presented with a form to enter your new tag. Only the field labeled &#8220;Tag&#8221; is required.</p>
				<dl>
					<dt>Admin</dt>
					<dd>This is a flag that designates if a tag is an administrative tag. Admin tags are only seen by administrators and are typically used for tagging content with information that may not be relevant or desired to be known by front-end users.</dd>
					<dt>Tag</dt>
					<dd>The tag you wish to create.</dd>
					<dt>Alias</dt>
					<dd>An alternate version of the tag such as a pluralized spelling of the tag or common abbreviation. For example, the tag &#8220;New York&#8221; may have an alias of &#8220;ny&#8221;.</dd>
					<dt>Description</dt>
					<dd>A description or definition of the tag.</dd>
					<dt>Substitute for</dt>
					<dd>A comma-separated list of tags you wish the current tag being created/edited to be substituted for.</dd>
				</dl>
			</div>
			
			<div class="section">
				<h2><span>Substitutions</span></h2>

				<p>
					Substitutions are similar to aliases in that they allow some basic mapping of one or more tags to another tag. 
					The difference lies in that an alias is still searchable; Substitutions are not.
				</p>

				<h3><span>How it works</span></h3>

				<p>
					As an example, imagine you are creating a tag called "water". For substitutions, you put in "H2O, aqua, wet stuff that falls from the sky". 
					Then a user enters "aqua" as a tag on their contribution. First, the system will try to find the tag "aqua". 
					If it doesn't exist, it will then check if it is to be substituted for a different tag. In this case, "aqua" is to be substituted with "water". 
					So, the resulting contribution will be tagged with "water" and this is what all users will see.
				</p>

				<h3><span>Adding a substitution for an existing tag</span></h3>

				<p>
					In the example above, the tag "aqua" doesn't exist before the tag "water" is created. What happens if "aqua" <em>did</em> already exist? At the 
					time of creation for the "water" tag&mdash;when you hit "save"&mdash;the system moved any associations for existing tags that matched the substitutions for "water".
					That is, if there were three items tagged with "aqua", they would now be tagged with "water" and the "aqua" tag would be deleted. This is functionally the same as merging.
				</p>

				<p class="note">
					<strong>Note:</strong> This operation can not be easily undone.
				</p>
			</div>
		</article>