		<article>
			<h1><span>Tags Manager</span></h1>

			<ul class="nav">
				<li><a href="#overview">Overview</a></li>
				<li><a href="#column-headers">Column Headers</a></li>
				<li><a href="#toolbar">Toolbar</a></li>
				<li><a href="#sub-menu">Sub-menu Links</a></li>
				<li><a href="#list-filters">List Filters</a></li>
			</ul>

			<section id="overview">
				<h2><span>Overview</span></h2>

				<p>Here you will a list of tags.</p>
			</section>
			<section id="column-headers">
				<h2><span>Column Headers</span></h2>

				<p>Click on the column heading to sort the list by that column's value. The list will be sorted in order by that column and a sort icon will show next to the column name. Click a second time to reverse the sort to high-to-low. The sort icon will change to high-to-low.</p>

				<dl>
					<dt>Checkbox</dt>
					<dd>Check this box to select one or more items. To select all items, check the box in the column heading. After one or more boxes are checked, click a toolbar button to take an action on the selected item or items. Many toolbar actions, such as Publish and Unpublish, can work with multiple items. Others, such as Edit, only work on one item at a time. If multiple items are checked and you press Edit, the first item will be opened for editing.</dd>

					<dt>Raw Tag</dt>
					<dd>The word or phrase as it was entered in.</dd>

					<dt>Tag</dt>
					<dd>The normalized version of the raw tag. Normalization makes all characters lowercose, strips punctuation, and only allows letters and numbers.</dd>

					<dt>Admin</dt>
					<dd>Indicates if the tag is an admin tag or not. As the name suggests, admin tags are only viewable on the front-end by admins.</dd>

					<dt># Tagged</dt>
					<dd>The number of items in the system that are associated with the tag.</dd>

					<dt>Aliases</dt>
					<dd>The number of aliases a tag has. An alias is an alternate spelling, abbreviation, or synonym for the tag.</dd>
				</dl>
			</section>
			<section id="toolbar">
				<h2><span>Toolbar</span></h2>
				<p>At the top right you will see the toolbar.</p>
				<p>The functions are:</p>
				<dl>
					<dt>Options</dt>
					<dd>Opens the Options window where settings such as default parameters or permissions can be edited.</dd>

					<dt>Pierce</dt>
					<dd>Copy items from one tag to another. This will essentially duplicate all associated data on a tag (aliases, items tagged, etc.) onto another tag.</dd>

					<dt>Merge</dt>
					<dd>Merge two or more tags. This will take all the associations, aliases, etc. from one or mroe tags and apply them to another tag.</dd>

					<dt>New</dt>
					<dd>Opens the editing screen to create a new article.</dd>

					<dt>Trash</dt>
					<dd>Permanently remove a tag and associated data from the site.</dd>

					<dt>Help</dt>
					<dd>Opens this help screen.</dd>
				</dl>
			</section>
			<section id="sub-menu">
				<h2><span>Sub-menu Links</span></h2>
				<p>At the top left, above the filters, you will see sub-menu options. These are essentially filters for blog posts, filtering by the primary scopes (or types) of blogs. The links are:</p>
				<dl>
					<dt>Tags</dt>
					<dd>Show tags in the system.</dd>
					<dt>Relationships</dt>
					<dd>A relationship viewer and mapper for tags.</dd>
					<dt>Focus Areas</dt>
					<dd>Set focus areas</dd>
					<dt>Plugins</dt>
					<dd>A link to the plugin manager, filtering to display only plugins in the "tags" folder.</dd>
				</dl>
			</section>
			<section id="list-filters">
				<h2><span>List Filters</span></h2>
				<p>Above the column headers is a search box for filtering results by a keyword or phrase.</p>
				<p>Click Clear to clear the Filter field and restore the list to its unfiltered state.</p>

				<h3>Page Controls</h3>
				<p>When the number of items is more than one page, you will see a page control bar as shown below.</p>

				<dl>
					<dt>Display #</dt>
					<dd>Select the number of items to show on one page.</dd>
					<dt>Start</dt>
					<dd>Click to go to the first page.</dd>
					<dt>Prev</dt>
					<dd>Click to go to the previous page.</dd>
					<dt>Page numbers</dt>
					<dd>Click to go to the desired page.</dd>
					<dt>Next</dt>
					<dd>Click to go to the next page.</dd>
					<dt>End</dt>
					<dd>Click to go to the last page.</dd>
				</dl>
			</section>
		</article>