		<article>
			<h1><span>Tags Manager: Tagged Items</span></h1>

			<ul class="nav">
				<li><a href="#overview">Overview</a></li>
				<li><a href="#column-headers">Column Headers</a></li>
				<li><a href="#toolbar">Toolbar</a></li>
				<li><a href="#sub-menu">Sub-menu Links</a></li>
				<li><a href="#list-filters">List Filters</a></li>
				<li><a href="#deleting">Deleting Tags</a></li>
			</ul>

			<section id="overview">
				<h2><span>Overview</span></h2>

				<p>Here you will a list of items that have been tagged. If a specific tag ID is provided, the list will display only items linked to that tag.</p>
			</section>
			<section id="column-headers">
				<h2><span>Column Headers</span></h2>

				<p>Click on the column heading to sort the list by that column's value. The list will be sorted in order by that column and a sort icon will show next to the column name. Click a second time to reverse the sort to high-to-low. The sort icon will change to high-to-low.</p>

				<dl>
					<dt>Checkbox</dt>
					<dd>Check this box to select one or more items. To select all items, check the box in the column heading. After one or more boxes are checked, click a toolbar button to take an action on the selected item or items. Many toolbar actions, such as Publish and Unpublish, can work with multiple items. Others, such as Edit, only work on one item at a time. If multiple items are checked and you press Edit, the first item will be opened for editing.</dd>

					<dt>ID</dt>
					<dd>ID if the entry.</dd>

					<dt>Item Type</dt>
					<dd>The type of item being tagged. This typically corresponds to a component name (without the 'com_' prefix), such as 'wishlist', 'blog', etc.</dd>

					<dt>Item ID</dt>
					<dd>The ID of the item being tagged.</dd>

					<dt>Created</dt>
					<dd>The timestamp for when the particular tag/item linkage was made (i.e., when the item was tagged).</dd>

					<dt>Creator</dt>
					<dd>The name of the user that made the tag/item link (i.e., the tagger).</dd>
				</dl>
			</section>
			<section id="toolbar">
				<h2><span>Toolbar</span></h2>
				<p>At the top right you will see the toolbar. The functions are:</p>
				<dl>
					<dt>New</dt>
					<dd>Opens the editing screen to create a tag/item link.</dd>

					<dt>Trash</dt>
					<dd>Permanently remove a tag/item link. This essentially removes a tag from an item. It does <strong>not</strong> remove the tag itself or item.</dd>

					<dt>Help</dt>
					<dd>Opens this help screen.</dd>
				</dl>
			</section>
			<section id="sub-menu">
				<h2><span>Sub-menu Links</span></h2>
				<p>At the top left, above the filters, you will see sub-menu options. These are essentially filters for blog posts, filtering by the primary scopes (or types) of blogs. The links are:</p>
				<dl>
					<dt>Tags</dt>
					<dd>Show tags in the system.</dd>
					<dt>Relationships</dt>
					<dd>A relationship viewer and mapper for tags.</dd>
					<dt>Focus Areas</dt>
					<dd>Set focus areas</dd>
					<dt>Plugins</dt>
					<dd>A link to the plugin manager, filtering to display only plugins in the "tags" folder.</dd>
				</dl>
			</section>
			<section id="list-filters">
				<h2><span>List Filters</span></h2>
				<p>Above the column headers is a search box for filtering results by a keyword or phrase.</p>
				<p>Click Clear to clear the Filter field and restore the list to its unfiltered state.</p>

				<h3>Page Controls</h3>
				<p>When the number of items is more than one page, you will see a page control bar as shown below.</p>

				<dl>
					<dt>Display #</dt>
					<dd>Select the number of items to show on one page.</dd>
					<dt>Start</dt>
					<dd>Click to go to the first page.</dd>
					<dt>Prev</dt>
					<dd>Click to go to the previous page.</dd>
					<dt>Page numbers</dt>
					<dd>Click to go to the desired page.</dd>
					<dt>Next</dt>
					<dd>Click to go to the next page.</dd>
					<dt>End</dt>
					<dd>Click to go to the last page.</dd>
				</dl>
			</section>
		</article>