<?php
/**
 * HUBzero CMS
 *
 * Copyright 2005-2011 Purdue University. All rights reserved.
 *
 * This file is part of: The HUBzero(R) Platform for Scientific Collaboration
 *
 * The HUBzero(R) Platform for Scientific Collaboration (HUBzero) is free
 * software: you can redistribute it and/or modify it under the terms of
 * the GNU Lesser General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any
 * later version.
 *
 * HUBzero is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * HUBzero is a registered trademark of Purdue University.
 *
 * @package   hubzero-cms
 * @author    Christopher Smoak <csmoak@purdue.edu>
 * @copyright Copyright 2005-2011 Purdue University. All rights reserved.
 * @license   http://www.gnu.org/licenses/lgpl-3.0.html LGPLv3
 */

// Check to ensure this file is included in Joomla!
defined('_JEXEC') or die('Restricted access');
?>
<h1>Newsletter Templates</h1>

<p>A template is a reusable frame for one or all your newlsetter &amp; email needs. Newsletter templates are built with HTML code. </p>
<p>Its a good idea to read some material before attempting to build your own template.</p>


<h2>1 Click Unsubscribe</h2>
<p>One click unsubscribe allows a user to unsubscribe from the mailinglist without a whole lot of hassle. Simply place the unsubscribe placeholder (see below) anywhere in your templates html code. When the newsletter is sent, that placeholder will automatically get replaced with the appropriate unsubscribe link for that user &amp; mailing list.</p>
<p><pre>{{UNSUBSCRIBE_LINK}}</pre></p>
