<?php
/**
 * @package    hubzero-cms
 * @copyright  Copyright 2005-2019 HUBzero Foundation, LLC.
 * @license    http://opensource.org/licenses/MIT MIT
 */

defined('_HZEXEC_') or die('Restricted access');
?>
<h1>Newsletter Templates</h1>

<p>A template is a reusable frame for one or all your newlsetter &amp; email needs. Newsletter templates are built with HTML code. </p>
<p>Its a good idea to read some material before attempting to build your own template.</p>


<h2>1 Click Unsubscribe</h2>
<p>One click unsubscribe allows a user to unsubscribe from the mailinglist without a whole lot of hassle. Simply place the unsubscribe placeholder (see below) anywhere in your templates html code. When the newsletter is sent, that placeholder will automatically get replaced with the appropriate unsubscribe link for that user &amp; mailing list.</p>
<p><pre>{{UNSUBSCRIBE_LINK}}</pre></p>
