<article>
	<h1>Events Manager</h1>

	<ul class="nav">
		<li><a href="#overview">Overview</a></li>
		<li><a href="#column-headers">Column Headers</a></li>
		<li><a href="#toolbar">Toolbar</a></li>
		<li><a href="#sub-menu">Sub-menu Links</a></li>
		<li><a href="#list-filters">List Filters</a></li>
	</ul>

	<p>Select <b>Components &#8594; Events</b> from the drop-down menu on the back-end of your installation.</p>

	<section id="description">
		<h2><span>Description</span></h2>
		<p>The Events Manager is where you can edit existing Events and create new ones. Events are organized into Categories.</p>
	</section>
	<section id="column-headers">
		<h2><span>Column Headers</span></h2>
		<p>Click on the column heading to sort the list by that column's value.</p>
		<dl>
			<dt>ID</dt>
			<dd>This is a unique identification number for this item assigned automatically. It is used to identify the item internally, and you cannot change this number. When creating a new item, this field displays 0 until you save the new entry, at which point a new ID is assigned to it.</dd>

			<dt>Checkbox</dt>
			<dd>Check this box to select one or more items. To select all items, check the box in the column heading. After one or more boxes are checked, click a toolbar button to take an action on the selected item or items. Many toolbar actions, such as Publish and Unpublish, can work with multiple items. Others, such as Edit, only work on one item at a time. If multiple items are checked and you press Edit, the first item will be opened for editing.</dd>

			<dt>Title</dt>
			<dd>The name of the item. For a Menu Item, the Title will display in the Menu. This entry is required. You can open the item for editing by clicking on the Title.</dd>

			<dt>State</dt>
			<dd>(Published/Unpublished/Archived/Trashed) The published status of the item.</dd>

			<dt>Timesheet</dt>
			<dd>An overview of when an event starts and stops.</dd>

			<dt>Access</dt>
			<dd>The viewing level access for this item.</dd>

			<dt>Pages</dt>
			<dd>The number of pages associated with an event. An event can have pages only if it accepts registration. You can open the list of pages for an event by clicking on the "# Page(s)" link.</dd>
		</dl>
	</section>
	<section id="toolbar">
		<h2><span>Toolbar</span></h2>
		<p>At the top right you will see the toolbar. The functions are:</p>
		<dl>
			<dt>Publish</dt>
			<dd>Makes the selected events available to visitors to your website.</dd>

			<dt>Unpublish</dt>
			<dd>Makes the selected events unavailable to visitors to your website.</dd>

			<dt>New</dt>
			<dd>Opens the editing screen to create a new event.</dd>

			<dt>Edit</dt>
			<dd>Opens the editing screen for the selected event. If more than one event is selected (where applicable), only the first event will be opened. The editing screen can also be opened by clicking on the Title of the event.</dd>

			<dt>Trash</dt>
			<dd>Permanently deletes the selected events.</dd>

			<dt>Help</dt>
			<dd>Opens this help screen.</dd>
		</dl>
	</section>
	<section id="sub-menu">
		<h2><span>Sub-menu Links</span></h2>
		<p>At the top left, above the Filter, you will see the following links:</p>

		<dl>
			<dt>Events</dt>
			<dd>Click this link to view a list of all events.</dd>
			<dt>Categories</dt>
			<dd>This link takes you to a list of categories for organizing events.</dd>
			<dt>Configuration</dt>
			<dd>Click this link to set or change various options for the component.</dd>
		</dl>
	</section>
	<section id="list-filters">
		<h2><span>List Filters</span></h2>

		<dl>
			<dt>Filter by Search</dt>
			<dd>
				<p>Lets you search event titles.</p>
			</dd>

			<dt>Filter by Category</dt>
			<dd>
				<p>Lets you show only items for the selected category. The categories can be managed by clicking the "Categories" sub-menu item.</p>
			</dd>

			<dt>Filter by Group</dt>
			<dd>
				<p>Lets you show only items for the selected group.</p>
			</dd>
		</dl>

		<h3>Page Controls</h3>
		<p>When the number of items is more than one page, you will see a page control bar as shown below.</p>

		<dl>
			<dt>Display #</dt>
			<dd>Select the number of items to show on one page.</dd>
			<dt>Start</dt>
			<dd>Click to go to the first page.</dd>
			<dt>Prev</dt>
			<dd>Click to go to the previous page.</dd>
			<dt>Page numbers</dt>
			<dd>Click to go to the desired page.</dd>
			<dt>Next</dt>
			<dd>Click to go to the next page.</dd>
			<dt>End</dt>
			<dd>Click to go to the last page.</dd>
		</dl>
	</section>
</article>