<article>
	<h1><span>Tools Manager: Edit Tool</span></h1>

	<ul class="nav">
		<li><a href="#overview">Overview</a></li>
		<li><a href="#toolbar">Toolbar</a></li>
		<li><a href="#details">Details</a></li>
	</ul>

	<section id="overview">
		<h2><span>Overview</span></h2>

		<p>The edit/creation form for a tool.</p>
	</section>
	<section id="toolbar">
		<h2><span>Toolbar</span></h2>
		<p>At the top right you will see the toolbar. The functions are:</p>
		<dl>
			<dt>Save &amp; Close</dt>
			<dd>Save changes and return to the listing of entries.</dd>

			<dt>Cancel</dt>
			<dd>Discard any changes made and return to the listing of entries.</dd>

			<dt>Help</dt>
			<dd>Opens this help screen.</dd>
		</dl>
	</section>
	<section id="details">
		<h2><span>Details</span></h2>

		<dl>
			<dt>Title</dt>
			<dd>The title of the entry. A required field.</dd>
		</dl>

		<p class="info"><strong>Note</strong>: All other information for a tool entry is added/edited in a tool version entry.</p>
	</section>
</article>