<article>
	<h1><span>Tools Manager: Edit Tool Version</span></h1>

	<ul class="nav">
		<li><a href="#overview">Overview</a></li>
		<li><a href="#toolbar">Toolbar</a></li>
		<li><a href="#details">Details</a></li>
	</ul>

	<section id="overview">
		<h2><span>Overview</span></h2>

		<p>The edit/creation form for a tool version.</p>
	</section>
	<section id="toolbar">
		<h2><span>Toolbar</span></h2>
		<p>At the top right you will see the toolbar. The functions are:</p>
		<dl>
			<dt>Save &amp; Close</dt>
			<dd>Save changes and return to the listing of entries.</dd>

			<dt>Cancel</dt>
			<dd>Discard any changes made and return to the listing of entries.</dd>

			<dt>Help</dt>
			<dd>Opens this help screen.</dd>
		</dl>
	</section>
	<section id="details">
		<h2><span>Details</span></h2>

		<dl>
			<dt>Command</dt>
			<dd>The invoction command for a tool session.</dd>

			<dt>Timeout</dt>
			<dd>The types used by this host. The list of types can be editied via the Host Types manager.</dd>

			<dt>Required Host</dt>
			<dd>A host required to run a session.</dd>

			<dt>Middleware</dt>
			<dd>Middleware used for a session.</dd>

			<dt>Perameters</dt>
			<dd>A list of key=value pairs of various parameters a tool session can use.</dd>
		</dl>
	</section>
</article>