<article>
	<h1 class="page-title">Help</h1>

	<section>
		<h2>Glossary</h2>

		<p>The Glossary is helpful for learning common terms used throughout the hub, in help pages, and in advanced documentation.</p>

		<ul>
			<li><a href="<?php echo Route::url('index.php?option=com_help&component=com_help&page=glossary'); ?>">Glossary</a></li>
		</ul>
	</section>

	<section>
		<h2>Getting Started</h2>

		<p>The Managers' Guide is a user manual for managing the web content and functionality of a HUB. It progresses step-by-step through various common tasks and familiarizes the manager with the administrative back-end interface. Managers will learn how to accomplish tasks such as managing (add/edit/delete) site members, configuring the hub, and more:</p>

		<ul>
			<li><a href="https://hubzero.org/documentation/current/managers">Site Managers</a></li>
		</ul>
	</section>

	<section>
		<h2>Further Information</h2>
		<ul>
			<li><a href="https://hubzero.org/documentation">Developer Documentation</a></li>
			<li><a href="https://hubzero.org/support">Hubzero Support</a></li>
		</ul>
	</section>
</article>