<article>
	<h1><span>Control Panel</span></h1>

	<p>The control panel is meant to give administrators an overview of activity and content on their site as well as provide shortcuts into common admin/maintenance functions. The panel is comprised entirely of modules. These modules can be set, rearranged, and modified via the <a href="<?php echo Route::url('index.php?option=com_help&component=com_modules&page=modules'); ?>">Module Manager</a> found under the "Extensions" menu item.</p>
</article>