language: php
php:
  - 8.2
  - 8.3
git:
  depth: 30
cache:
  directories:
    - core/vendor
before_script:
  - cd core && composer install --no-interaction --prefer-dist
  - cd ..
  - git config diff.renameLimit 0
  - changed_files=$(git diff --diff-filter=ACMRTUXB --name-only $TRAVIS_COMMIT_RANGE)
  - echo "The following will be tested:"
  - echo $changed_files
script:
  - core/bin/php_tests.sh $changed_files
