#!/bin/sh
#
# @package    hubzero-cms
# @copyright  Copyright (c) 2005-2020 The Regents of the University of California.
# @license    http://opensource.org/licenses/MIT MIT
#

cd /
if [ -f /usr/bin/maxwell ] ; then
exec /usr/bin/maxwell $*
elif [ -f /usr/lib/hubzero/bin/maxwell ] ; then
exec /usr/lib/hubzero/bin/maxwell $*
elif [ -f /usr/lib/mw/bin/maxwell ] ; then
exec /usr/lib/mw/bin/maxwell $*
elif [ -f /opt/mw/bin/maxwell ] ; then
exec /opt/mw/bin/maxwell $*
else
exec /opt/narwhal/narwhal $*
fi
