<article>
	<h1><span>User Notes</span></h1>

	<p>To access this screen you can either:</p>
		<ul><li> Click the <b>User Manager</b> button in the <a href="<?php echo Route::url('index.php?option=com_help&view=help&keyref=Help25:Site_Control_Panel'); ?>" title="Help25:Site Control Panel">Control Panel</a> and select the User Notes tab, or
		</li><li> Select <b>Users &#8594; User Notes</b> from the drop-down menus.
		</li></ul>
	</section>
	<section>
		<h2> <span class="mw-headline" id="Description">Description</span></h2>
		<p>User notes are pieces of information which can be assigned to registered users on your site. These notes can contain for example comments about 'offending' or 'difficult' users, etc.</p>
	</section>
	<section>
		<h2> <span class="mw-headline" id="Column_Headers">Column Headers</span></h2>
		<p>In the table containing the user notes assigned to users registered on your site, you will see different columns. Here you can read what they mean and what is displayed in that column.</p>
		<ul><li><b>Checkbox</b>. Check this box to select one or more items. To select all items, check the box in the column heading. After one or more boxes are checked, click a toolbar button to take an action on the selected item or items. Many toolbar actions, such as Publish and Unpublish, can work with multiple items. Others, such as Edit, only work on one item at a time. If multiple items are checked and you press Edit, the first item will be opened for editing.
		</li><li><b>User</b>. The name of the user.
		</li><li><b>Subject</b>. The subject of the user note.
		</li></ul>
		<ul><li><b>Category.</b> The Category this item belongs to.
		</li><li><b>Status</b>. (Published/Unpublished/Archived/Trashed) The published status of the item.
		</li><li><b>Review date</b>. The date when the user note was created.
		</li></ul>
		<ul><li><b>ID</b>. This is a unique identification number for this item assigned automatically by the CMS. It is used to identify the item internally, and you cannot change this number. When creating a new item, this field displays 0 until you save the new entry, at which point a new ID is assigned to it.
		</li></ul>
	</section>
	<section>
		<h2> <span class="mw-headline" id="Toolbar">Toolbar</span></h2>
		<p>At the top right you will see the toolbar:</p>
		<p>The functions are:</p>
		<ul><li><b>New</b>. Opens the editing screen to create a new user note.
		</li><li><b>Edit</b>. Opens the editing screen for the selected user note. If more than one user note is selected (where applicable), only the first user note will be opened. The editing screen can also be opened by clicking on the Title or Name of the user note.
		</li><li><b>Publish.</b> Makes the selected user notes available to administrators to your website.
		</li><li><b>Unpublish.</b> Makes the selected user notes available to administrators to your website.
		</li><li><b>Archive</b>. Changes the status of the selected user notes to indicate that they are archived.  Archived user notes can be moved back to the published or unpublished state by selecting "Archived" in the Select Status filter and changing the status of the user notes to Published or Unpublished as preferred.
		</li><li><b>Check In</b>. Checks-in the selected user notes. Works with one or multiple user notes selected.
		</li><li><b>Trash</b>. Changes the status of the selected user notes to indicate that they are trashed.  Trashed user notes can still be recovered by selecting "Trashed" in the Select Status filter and changing the status of the user notes to Published or Unpublished as preferred.  To permanently delete trashed user notes, select "Trashed" in the Select Status filter, select the user notes to be permanently deleted, then click the Empty Trash toolbar icon.
		</li><li><b>Options</b>. Opens the Options window where settings such as default parameters or permissions can be edited.
		</li><li><b>Help</b>. Opens this help screen.
		</li></ul>
	</section>
	<section>
		<h2> <span class="mw-headline" id="Options">Options</span></h2>
		<p>Click the Options button to open the <b>User Manager Options</b> window which lets you configure this component.
		</p>
		<h3> <span class="mw-headline" id="Buttons_Common_to_All_Tabs">Buttons Common to All Tabs</span></h3>
		<ul><li><b>Save</b>. Saves the user options and stays in the current screen.
		</li><li><b>Save &amp; Close</b>. Saves the user options and closes the current screen.
		</li><li><b>Cancel/Close</b>. Closes the current screen and returns to the previous screen without saving any modifications you may have made.
		</li></ul>
		<h3> <span class="mw-headline" id="Component">Component</span></h3>

		<ul><li><b>Allow User Registration.</b> (Yes/No) If set Yes, users can register from the front end of the site using the Create an Account link provided on the Login module. If set to No, the "Create and Account" link will not show. 
		</li><li><b>New User Registration Group.</b> The group that users are assigned to by default when they register on the site. Defaults to Registered.
		</li><li><b>Guest User Group.</b> The group that guests are assigned to. (Guests are visitors to the site who are not logged in.) This is set to Public by default. If you change this to a different group, it is possible to create content on the site that is visible to guests but not visible to logged in users. See <a href="<?php echo Route::url('index.php?option=com_help&view=help&keyref=ACL_Tutorial#Allowing_Guest-Only_Access_to_Menu_Items_and_Modules'); ?>" class="mw-redirect">Allowing Guest-Only Access to Menu Items and Modules</a>.
		</li><li><b>Send Password.</b> If set to yes the user will be emailed their password on the registration email. Note there are potential security issues if this is set to yes.
		</li><li><b>New User Account Activation.</b>
		<ul><li><b>None.</b> User account will be active immediately with no action required.
		</li><li><b>Self.</b> User will receive an email with an activation link. The account will be activated when the user clicks the activation link.
		</li><li><b>Admin.</b> User will receive an email with an activation link. When the user clicks this link, the Site Admin will be notified via email and the Site Admin needs to activate the user's account.
		</li></ul>
		</li><li><b>Notification Mail to Administrators.</b> (Yes/No) Send email notification to administrators with <b>User Account Activation</b>.
		</li><li><b>Captcha.</b> Use Captcha for User Account Registration and Username or User Password reminders. 
		</li><li><b>Frontend User Parameters.</b> (Show/Hide) If set to Show, users will be able to modify their language, editor, and help site preferences from the front end of the site. If set to Hide, the user will not be able to change these settings.
		</li><li><b>Frontend Language.</b> (Show/Hide) Show or hide the option for users to set their default site language.
		</li><li><b>Change Login Name.</b> (Yes/No) Allow user to change Login Name.
		</li><li><b>Maximum Reset Count.</b> (0-20) Maximum number of reset password attempts per <b>Time in Hours</b>. Zero means no limit on reset password attempts.
		</li><li><b>Time in Hours.</b> (1-24) Time period in hours for the <b>Maximum Reset Count</b>.
		</li></ul>
		<h3> <span class="mw-headline" id="Mass_Mail">Mass Mail</span></h3>

		<ul><li><b>Subject Prefix</b>. Enter optional text to be inserted automatically before the subject of the mass email.
		</li><li><b>Mailbody Suffix</b>. Enter optional text to be inserted automatically after the body of the email (for example, a signature).
		</li></ul>
		<h3> <span class="mw-headline" id="Permissions">Permissions</span></h3>
		<p>This screen allows you to set the component permissions in the CMS. This is important to consider if you have sites with many different user categories all of whom need to have different accessibilities to the component. The screenshot below describes what you should see and the text below that describes what each permission level gives the user access to:
		<p>You work on one Group at a time by opening the slider for that group. You change the permissions in the Select New Settings drop-down list boxes.
		The options for each value are Inherited, Allowed, or Denied. The Calculated Setting column shows you the setting in effect. It is either Not Allowed (the default), Allowed, or Denied.
		Note that the Calculated Setting column is not updated until you press the Save button in the toolbar. To check that the settings are what you want, press the Save button and check the Calculated Settings column.
		</p><p>The default values used here are the ones set in the <a href="<?php echo Route::url('index.php?option=com_help&view=help&keyref=Help25:Site_Global_Configuration#Permissions'); ?>" title="Help25:Site Global Configuration">Global Configuration Permissions Tab</a>
		</p>
		<dl><dd><dl><dt>Configure</dt><dd> Open the users component option screens (the modal window these options are in)
		</dd><dt>Access Administration Interface</dt><dd> Open the users component manger screens
		</dd><dt>Create&#160;</dt><dd> Create new users in the component
		</dd><dt>Delete&#160;</dt><dd> Delete existing users in the component
		</dd><dt>Edit&#160;</dt><dd> Edit existing users in the component
		</dd><dt>Edit State&#160;</dt><dd> Change an users state (Publish, Unpublish, Archive, and Trash) in the component.
		</dd></dl>
		</dd></dl>
		<p>There are two very important points to understand from this screen. The first is to see how the permissions can be inherited from the parent Group. The second is to see how you can control the default permissions by Group and by Action.
		This provides a lot of flexibility. For example, if you wanted Shop Suppliers to be able to have the ability to create an article about their product, you could just change their Create value to "Allowed". If you wanted to not allow members of Administrator group to delete objects or change their state, you would change their permissions in these columns to Inherited (or Denied).
		It is also important to understand that the ability to have child groups is completely optional. It allows you to save some time when setting up new groups. However, if you like, you can set up all groups to have Public as the parent and not inherit any permissions from a parent group.
		</p>
	</section>
	<section>
		<h2><span class="mw-headline" id="List_Filters">List Filters</span></h2>
		<p><b>Filter by Partial User Name or Partial Subject text</b></p>
		<ul>
			<li><b>Filter</b>. In the upper left is a Search field and two buttons, as shown below.</li>
		</ul>

		<p><b>Filter by Category or Status of the user note</b></p>
		<ul>
			<li>In the upper right there are drop-down menus as shown below.</li>
		</ul>

		<p>Choose one of the categories or statuses to find matching user notes.</p>
		<ul>
			<li>
				<b>Page Controls.</b> When the number of items is more than one page, you will see a page control bar as shown below.
				<ul>
					<li><b>Display #:</b> Select the number of items to show on one page.</li>
					<li><b>Start:</b> Click to go to the first page.</li>
					<li><b>Prev:</b> Click to go to the previous page.</li>
					<li><b>Page numbers:</b> Click to go to the desired page.</li>
					<li><b>Next:</b> Click to go to the next page.</li>
					<li><b>End:</b> Click to go to the last page.</li>
				</ul>
			</li>
		</ul>
	</section>
	<section>
		<h2><span class="mw-headline" id="Quick_Tips">Quick Tips</span></h2>
		<ul>
			<li>Click on the username to edit the user note properties.</li>
		</ul>
	</section>
	<section>
		<h2><span class="mw-headline" id="Related_information">Related information</span></h2>
		<ul>
			<li><a href="<?php echo Route::url('index.php?option=com_help&view=help&keyref=Help25:Users_User_Notes_Edit'); ?>" title="Help25:Users User Notes Edit">User Manager: Add/Edit Notes</a></li>
		</ul>
	</section>
</article>