<article>
	<h1><span>User Notes: Edit Note</span></h1>

	<p>Edit a note or comment on a specific user</p>

	<section>
		<h2><span class="mw-headline" id="How_to_access">How to access</span></h2>
		<p>To edit an existing user note, navigate to the User Notes tab of the User Manager (<b>Users &#8594; User Manager &#8594; User Notes</b>). Then</p>
		<ol>
			<li>click on the user name or</li>
			<li>click on the check box for the user note and click on the Edit button.</li>
		</ol>
		<p>To create a new user note</p>
		<ol>
			<li>select <b>Users &#8594; User Notes &#8594; Add User Note</b> from the menu or</li>
			<li>click on the New button in the User Manager: User Notes screen.</li>
		</ol>
	</section>
	<section>
		<h2> <span class="mw-headline" id="Description">Description</span></h2>
		<p>User notes are pieces of information which can be assigned to registered users on your site. These notes can contain for example comments about 'offending' or 'difficult' users, etc.</p>
		<p>In this screen you can create an user note or edit an user note.</p>
	</section>
	<section>
		<h2><span class="mw-headline" id="Note_Details"> Note Details </span></h2>
		<ul>
			<li><b>Subject</b>. The subject of the user note.</li>
			<li><b>ID</b>. The selected user to which the user note belongs.</li>
			<li><b>Category</b>. The category to which the user note belongs.</li>
			<li><b>Status</b>. (Published/Unpublished/Archived/Trashed) The published status of the user note.</li>
			<li><b>Review date</b>. The date when the user note was created.</li>
			<li><b>Note</b>. The actual text of the user note.</li>
		</ul>
	</section>
	<section>
		<h2><span class="mw-headline" id="Toolbar"> Toolbar</span></h2>
		<p>At the top right you will see the toolbar. The functions are:</p>
		<ul>
			<li><b>Save</b>. Saves the user group and stays in the current screen.</li>
			<li><b>Save &amp; Close</b>. Saves the user group and closes the current screen.</li>
			<li><b>Cancel/Close</b>. Closes the current screen and returns to the previous screen without saving any modifications you may have made.</li>
			<li><b>Help</b>. Opens this help screen.</li>
		</ul>
	</section>
	<section>
		<h2><span class="mw-headline" id="Related_information">Related information</span></h2>
		<ul>
			<li><a href="<?php echo Route::url('index.php?option=com_help&view=help&keyref=Help25:Users_User_Notes'); ?>" title="Help25:Users User Notes">User Manager: Users Notes</a></li>
		</ul>
	</section>
</article>