<article>
	<h1><span>User Manager: Customize Profile</span></h1>

	<p>Allows an administrator to define profile/registration fields.</p>

	<section>
		<h2><span class="mw-headline" id="How_to_access">How to access</span></h2>
		<p>To edit the profile schema, navigate to the Members Manager (<b>Users &#8594; Members</b>). Then click the button int he toolbar labeled <strong>profile</strong>.</p>
	</section>
	<section>
		<h2> <span class="mw-headline" id="Description">Description</span></h2>
		<p>In this screen, you have the ability to define user profile fields, if said fields are required or optional, what values are allowable, and what fields are dependent upon a value from another field being chosen.</p>
	</section>
	<section>
		<h2><span class="mw-headline" id="User_Fields">Field Types</span></h2>

		<dl>
			<dt>Text</dt>
			<dd>A single-line textbox.</dd>
			<dt>Paragraph</dt>
			<dd>A multi-line textbox (a.k.a. textarea).</dd>
			<dt>Checkboxes</dt>
			<dd>A list of options where the user may select one or more.</dd>
			<dt>Multiple Choice</dt>
			<dd>A list of options where the user can only choose one of the available options.</dd>
			<dt>Date/Time</dt>
			<dd>A textbox specifically for entering timestamps.</dd>
			<dt>Dropdown</dt>
			<dd>A dropdown (select box) of options where the user can only choose one of the available options.</dd>
			<dt>Country</dt>
			<dd>A dropdown (select box) of countries. <i>The list of countries is automatically populated.</i></dd>
			<dt>Website</dt>
			<dd>A textbox specifically for entering URLs.</dd>
			<dt>Hidden</dt>
			<dd>A hidden input.</dd>
			<dt>ORCID</dt>
			<dd>A textbox for entering entering ORCIDs.</dd>
		</dl>
	</section>
	<section>
		<h2> <span class="mw-headline" id="Toolbar">Toolbar</span></h2>
		<p>At the top right you will see the toolbar:
		</p><p>The functions are:
		</p>
		<ul><li><b>Save</b>. Saves the user and stays in the current screen.
		</li><li><b>Save &amp; Close</b>. Saves the user and closes the current screen.
		</li><li><b>Save &amp; New</b>. Saves the user and keeps the editing screen open and ready to create another user.
		</li><li><b>Cancel/Close</b>. Closes the current screen and returns to the previous screen without saving any modifications you may have made.
		</li><li><b>Help</b>. Opens this help screen.
		</li></ul>
	</section>
</article>