<?php
/**
 * HUBzero CMS
 *
 * Copyright 2005-2011 Purdue University. All rights reserved.
 *
 * This file is part of: The HUBzero(R) Platform for Scientific Collaboration
 *
 * The HUBzero(R) Platform for Scientific Collaboration (HUBzero) is free
 * software: you can redistribute it and/or modify it under the terms of
 * the GNU Lesser General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any
 * later version.
 *
 * HUBzero is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * HUBzero is a registered trademark of Purdue University.
 *
 * @package   hubzero-cms
 * @author    Christopher Smoak <csmoak@purdue.edu>
 * @copyright Copyright 2005-2011 Purdue University. All rights reserved.
 * @license   http://www.gnu.org/licenses/lgpl-3.0.html LGPLv3
 */

// Check to ensure this file is included in Joomla!
defined('_JEXEC') or die('Restricted access');
?>
<artcle>
	<h1>Answers Help</h1>

	<section>
		<h2>Discover</h2>
		<p>Browse answered questions to learn what insights others have left or share your knowledge by answering a few questions.</p>

		<h3>Search</h3>
		<p>You can also use the search box on the page to locate questions and answers related to specific words and phrases.</p>
	</section>

	<section>
		<h2>Ask</h2>
		<p>What would you like to know? Ask a question on a topic that's important, so that other people can give you answers.</p>

		<h3>Tags</h3>
		<p>Tags are a way of categorizing questions. By adding tags you help others find your questions and get answers more quickly!</p>

		<h3>Select the best Answer</h3>
		<p>Once your question has been answered, you need pick a best answer. When viewing the list of answers, each one will have a button that says "Accept answer". Click it and you're done!</p>
	</section>

	<section>
		<h2>Answer</h2>
		<p>Share your knowledge, Help others and be an Expert.</p>

		<h3>Tags</h3>
		<p>Use tags to find open questions related to the topic you know about.</p>

		<h3>Search</h3>
		<p>You can also use the search box on the page to locate questions and answers related to specific words and phrases.</p>

		<h3>Best Answer</h3>
		<p>Your answer to a question may be chosen as the best one, giving you <a href="<?php echo JRoute::_('index.php?option=com_help&component=answers&page=points'); ?>">extra points</a>, and bragging rights!</p>
	</section>

	<ul>
		<li>
			<a href="<?php echo JRoute::_('index.php?option=com_help&component=answers&page=points'); ?>">Earning points in the Questions &amp; Answers forum</a>
		</li>
	</ul>
</article>