<article>
	<h1>Template Manager: Edit Source</h1>

	<p>This screen is accessed from the back-end Joomla! administrator panel. It is used to edit the source code of template files.
</p>
<h2> <span class="mw-headline" id="How_to_Access">How to Access</span></h2>
<p>Navigate to the <a href="/proxy/index.php?option=com_help&view=help&keyref=Help25:Extensions_Template_Manager_Templates_Edit" title="Help25:Extensions Template Manager Templates Edit">Template Manager: Customise Template</a> screen. Click on the name of the template you want to edit. Then click the link to the template file that you want to edit.
</p>
<h2> <span class="mw-headline" id="Description">Description</span></h2>
<p>This screen is where the source code of template files is edited. It provides a plain text interface to edit the template files. HTML, PHP and CSS programming syntax is highlighted to make the source code files easier to read.
</p>
<h2> <span class="mw-headline" id="Screenshot">Screenshot</span></h2>
<p><a href="/proxy/index.php?option=com_help&view=help&keyref=File:Help25-extensions-template_manager-templates-edit_source-screen.png" class="image"><img alt="Help25-extensions-template manager-templates-edit source-screen.png" src="http://docs.joomla.org/images/2/22/Help25-extensions-template_manager-templates-edit_source-screen.png" width="670" height="225" /></a>
</p>
<h2> <span class="mw-headline" id="Details_and_Options">Details and Options</span></h2>
<ul><li><b>Source Code.</b> The contents of the selected template file is displayed and editible here.
</li></ul>
<h2> <span class="mw-headline" id="Toolbar">Toolbar</span></h2>
<p>At the top right you will see the toolbar:
</p><p><a href="/proxy/index.php?option=com_help&view=help&keyref=File:Help25-Toolbar-Save-SaveClose-Close-Help.png" class="image"><img alt="Help25-Toolbar-Save-SaveClose-Close-Help.png" src="http://docs.joomla.org/images/7/7c/Help25-Toolbar-Save-SaveClose-Close-Help.png" width="250" height="65" /></a>
</p><p>The functions are:
</p>
<ul><li><b>Save</b>. Saves the template source file and stays in the current screen.
</li><li><b>Save &amp; Close</b>. Saves the template source file and closes the current screen.
</li><li><b>Cancel/Close</b>. Closes the current screen and returns to the previous screen without saving any modifications you may have made.
</li><li><b>Help</b>. Opens this help screen.
</li></ul>
<h2> <span class="mw-headline" id="Quick_Tips">Quick Tips</span></h2>
<ul><li> Important: Do not delete the default template files using FTP because it generates an error in both the front-end and back-end.
</li><li> Before editing the HTML and the CSS file of the template, it is a good idea to make a backup of the file you are editing. Also, you can edit these files outside of Joomla! using the HTML or CSS editor of your choice.
</li></ul>
<h2> <span class="mw-headline" id="Related_Information">Related Information</span></h2>
<ul><li> To install templates: <a href="/proxy/index.php?option=com_help&view=help&keyref=Help25:Extensions_Extension_Manager_Install" title="Help25:Extensions Extension Manager Install">Extension Manager: Install</a>
</li></ul>
</article>