<article>
	<h1>Template Manager: Edit Style</h1>

	<section id="Description">
		<h2><span class="mw-headline">Description</span></h2>
		<p>This is where you edit a template's styles. When a template is first installed, a default style is created for it. The default style for the template will have the same name as the template with a <i>- Default</i> suffix. To make a different variation of the default template style, check the default style's checkbox and press the <i>Duplicate</i> icon in the toolbar. Then edit the duplicate.</p>
	</section>
	<section id="Details_and_Options">
		<h2><span class="mw-headline">Details and Options</span></h2>

		<h3><span class="mw-headline" id="Details">Details</span></h3>
		<ul>
			<li><b>Style Name.</b> The name of the style. This is the name that will display in the Style column of the <i>Template Manager: Styles</i> screen.</li>
			<li><b>Template.</b> The name of the template the style is derived from.</li>
			<li><b>Default.</b> Whether or not the style is the default for the location.</li>
			<li><b>ID</b>. This is a unique identification number for this item assigned automatically. It is used to identify the item internally, and you cannot change this number. When creating a new item, this field displays 0 until you save the new entry, at which point a new ID is assigned to it.</li>
			<li><b>Template description.</b> The description of the template the style is derived from.</li>
		</ul>

		<h3><span class="mw-headline" id="Menu_assignment">Menu assignment</span></h3>
		<p>This section contains all the menu items configured in your website. To apply the current style to a menu item's corresponding web page, check the box next to the menu item. You can press the <i>Toggle Selection</i> button to invert the menu item selections.</p>
		<p><b>Note</b>: If a checkbox is grayed out and cannot be checked then it could be because the menu item is in use by another user.  You can see if this is the case by going to the <a href="index.php?option=com_help&view=help&keyref=Help25:Menus_Menu_Item_Manager" title="Help25:Menus Menu Item Manager">menu manager screen for the menu</a> concerned.  If there is a padlock symbol next to the menu item then it is currently in use by another user.</p>

		<h3><span class="mw-headline" id="Advanced_Options">Advanced Options</span></h3>
		<p>This section <b>may not be present for all templates</b> and is dependent on the actual template being used. If a template from which a style is derived from has configurable options they will be present here. It is these additional configurable options which allow you to have multiple different styles of templates with variations of these options. The options available will vary based on what options the template developer made available.</p>
	</section>
	<section id="Toolbar">
		<h2><span class="mw-headline">Toolbar</span></h2>
		<p>At the top right you will see the toolbar. The functions are:</p>
		<ul>
			<li><b>Save</b>. Saves the template style and stays in the current screen.</li>
			<li><b>Save &amp; Close</b>. Saves the template style and closes the current screen.</li>
			<li><b>Save as Copy</b>. Saves your changes to a copy of the current template style.  Does not affect the current template style.  This toolbar icon is not shown if you are creating a new template style.</li>
			<li><b>Cancel/Close</b>. Closes the current screen and returns to the previous screen without saving any modifications you may have made.</li>
			<li><b>Help</b>. Opens this help screen.</li>
		</ul>
	</section>
	<section id="Related_Information">
		<h2><span class="mw-headline">Related Information</span></h2>
		<p>To install templates: <a href="index.php?option=com_help&view=help&keyref=Help25:Extensions_Extension_Manager_Install" title="Help25:Extensions Extension Manager Install">Extension Manager: Install</a></p>
	</section>
</article>