<article>
	<h1>Template Manager: Styles</h1>

	<h2> <span class="mw-headline" id="How_to_access">How to access</span></h2>
<ul><li> Select <b>Extensions &#8594; Template Manager</b> from the drop-down menu of the <i><b>Joomla! Administrator Panel</b></i>. 
</li><li> Select the <b>Styles</b> menu link from the <a href="/proxy/index.php?option=com_help&view=help&keyref=Help25:Extensions_Template_Manager_Templates" title="Help25:Extensions Template Manager Templates">Template Manager: Templates</a> screen.
</li></ul>
<h2> <span class="mw-headline" id="Description">Description</span></h2>
<p>The <b>Template Manager: Styles</b> screen allows you to manage template styles which you can then apply to your Joomla! installation. You can specify the default style to be applied to web pages in the public and administrator interfaces. You can also configure different styles for the various menu item web pages on your site. Styles allow to you have multiple different configurations of a template saved and then apply them on a site-wide or per-page basis.
</p>
<h2> <span class="mw-headline" id="Screenshot">Screenshot</span></h2>
<p><a href="/proxy/index.php?option=com_help&view=help&keyref=File:Help25-extensions-template_manager-styles-screen.png" class="image"><img alt="Help25-extensions-template manager-styles-screen.png" src="http://docs.joomla.org/images/5/53/Help25-extensions-template_manager-styles-screen.png" width="670" height="345" /></a>
</p>
<h2> <span class="mw-headline" id="Column_Headers">Column Headers</span></h2>
<p>Click on the column heading to sort the list by that column's value.
</p>
<ul><li><b>Checkbox</b>. Check this box to select one or more items. To select all items, check the box in the column heading. After one or more boxes are checked, click a toolbar button to take an action on the selected item or items. Many toolbar actions, such as Publish and Unpublish, can work with multiple items. Others, such as Edit, only work on one item at a time. If multiple items are checked and you press Edit, the first item will be opened for editing.
</li><li><b>Style.</b> The style name. The default style that is installed with a new template will have '-Default' at the end of its name.
</li><li><b>Location.</b> Whether the style is a public front-end or an administrator back-end style. 'Site' means it is a public front-end style. 'Administrator' means it is an administrator back-end style.
</li><li><b>Template.</b> The name of the template which the style was derived from.
</li><li><b>Default.</b> Whether or not the style is the default applied to pages which do not have a specific style configured. A gold star means the style is the default. There can be only one default style set for locations.
</li><li><b>Assigned.</b> Whether or not the template is configured on a web page. A green circle with a white check mark in it means the style is being used on at least one web page of your site.
</li></ul>
<ul><li><b>ID</b>. This is a unique identification number for this item assigned automatically by Joomla!. It is used to identify the item internally, and you cannot change this number. When creating a new item, this field displays 0 until you save the new entry, at which point a new ID is assigned to it.
</li></ul>
<h2> <span class="mw-headline" id="List_Filters">List Filters</span></h2>
<h3> <span class="mw-headline" id="Filter_by_Partial_Title">Filter by Partial Title</span></h3>
<p>You can filter the list of items by typing part of the styles's name or the ID number of the style.
</p>
<dl><dd><a href="/proxy/index.php?option=com_help&view=help&keyref=File:Help25-banners-manage-filter-name.png" class="image"><img alt="Help25-banners-manage-filter-name.png" src="http://docs.joomla.org/images/2/2b/Help25-banners-manage-filter-name.png" width="286" height="25" /></a>
</dd></dl>
<h3> <span class="mw-headline" id="Filter_by_Location_and_Template">Filter by Location and Template</span></h3>
<p>In the upper right area, above the column headings, there are two drop-down list boxes as shown below:
</p>
<dl><dd><a href="/proxy/index.php?option=com_help&view=help&keyref=File:Help25-extensions-template_manager-styles-filter-attributes.png" class="image"><img alt="Help25-extensions-template manager-styles-filter-attributes.png" src="http://docs.joomla.org/images/b/b8/Help25-extensions-template_manager-styles-filter-attributes.png" width="246" height="23" /></a>
</dd></dl>
<p>The selections may be combined. Only items matching all selections will be displayed in the list.
</p>
<ul><li><b>Select Location.</b> The location the template is used in - Site or Administrator.
</li><li><b>Select Template.</b> The template which the style is derived from.
</li></ul>
<h3> <span class="mw-headline" id="Number_of_Items_to_Display">Number of Items to Display</span></h3>
<ul><li><b>Page Controls.</b> When the number of items is more than one page, you will see a page control bar as shown below.<div class="thumb tnone"><div class="thumbinner" style="width:543px;"><a href="/proxy/index.php?option=com_help&view=help&keyref=File:Help25-chunk-colheader-pagination.png" class="image"><img alt="Help25-chunk-colheader-pagination.png" src="http://docs.joomla.org/images/7/76/Help25-chunk-colheader-pagination.png" width="541" height="37" class="thumbimage" /></a>  <div class="thumbcaption"></div></div></div>
<ul><li><b>Display #:</b> Select the number of items to show on one page.
</li><li><b>Start:</b> Click to go to the first page.
</li><li><b>Prev:</b> Click to go to the previous page.
</li><li><b>Page numbers:</b> Click to go to the desired page.
</li><li><b>Next:</b> Click to go to the next page.
</li><li><b>End:</b> Click to go to the last page.
</li></ul>
</li></ul>
<h2> <span class="mw-headline" id="Toolbar">Toolbar</span></h2>
<p>At the top right you will see the toolbar:
</p><p><a href="/proxy/index.php?option=com_help&view=help&keyref=File:Help25-Toolbar-MakeDefault-Edit-Duplicate-Delete-Options-Help.png" class="image"><img alt="Help25-Toolbar-MakeDefault-Edit-Duplicate-Delete-Options-Help.png" src="http://docs.joomla.org/images/6/6a/Help25-Toolbar-MakeDefault-Edit-Duplicate-Delete-Options-Help.png" width="382" height="65" /></a>
</p><p>The functions are:
</p>
<ul><li><b>Make Default</b>. Makes the selected template style the default.
</li><li><b>Edit</b>. Opens the editing screen for the selected contact. If more than one contact is selected (where applicable), only the first contact will be opened. The editing screen can also be opened by clicking on the Title or Name of the contact.
</li><li><b>Duplicate</b>. Makes a copy of the selected template style.  The copy is created immediately and is given the same name as the original but prefixed with "Copy of" and/or suffixed with a number (eg. "(2)") so that it can be distinguished from the original and any other copies.
</li><li><b>Delete</b>. Deletes the selected template styles. Works with one or multiple template styles selected.
</li><li><b>Options</b>. Opens the Options window where settings such as default parameters or permissions can be edited.
</li><li><b>Help</b>. Opens this help screen.
</li></ul>
<h2> <span class="mw-headline" id="Options">Options</span></h2>
<p>Click the Options button to open the <b>Template Manager Options </b> window which lets you configure this component.
</p>
<div class="center"><div class="floatnone"><a href="/proxy/index.php?option=com_help&view=help&keyref=File:Help25-extensions-template-manager-options.png" class="image"><img alt="Help25-extensions-template-manager-options.png" src="http://docs.joomla.org/images/a/a4/Help25-extensions-template-manager-options.png" width="670" height="432" /></a></div></div>
<h3> <span class="mw-headline" id="Buttons_Common_to_All_Tabs">Buttons Common to All Tabs</span></h3>
At the top right of the Options modal window you will see the toolbar.<div class="thumb tnone"><div class="thumbinner" style="width:212px;"><a href="/proxy/index.php?option=com_help&view=help&keyref=File:Help25-screenshot-article-manager-options-toolbar.png" class="image"><img alt="Help25-screenshot-article-manager-options-toolbar.png" src="http://docs.joomla.org/images/b/bd/Help25-screenshot-article-manager-options-toolbar.png" width="210" height="36" class="thumbimage" /></a>  <div class="thumbcaption"></div></div></div>
<ul><li><b>Save</b>. Saves the template options and stays in the current screen.
</li><li><b>Save &amp; Close</b>. Saves the template options and closes the current screen.
</li><li><b>Cancel/Close</b>. Closes the current screen and returns to the previous screen without saving any modifications you may have made.
</li></ul>
<h3> <span class="mw-headline" id="Templates_Tab">Templates Tab</span></h3>
<ul><li><b>Preview Module Positions.</b> Enables the preview of the module positions in the template by appending tp=1 to the web address. Also enables the Preview button in the list of templates.
</li></ul>
<h3> <span class="mw-headline" id="Permissions_Tab">Permissions Tab</span></h3>
<p>This screen allows you to set the component permissions in Joomla. This is important to consider if you have sites with many different user categories all of whom need to have different accessibilities to the component. The screenshot below describes what you should see and the text below that describes what each permission level gives the user access to:
</p>
<div class="center"><div class="floatnone"><a href="/proxy/index.php?option=com_help&view=help&keyref=File:Help25-extensions-template_manager-options-permissions.png" class="image"><img alt="Help25-extensions-template manager-options-permissions.png" src="http://docs.joomla.org/images/a/a3/Help25-extensions-template_manager-options-permissions.png" width="670" height="385" /></a></div></div>
<p>You work on one Group at a time by opening the slider for that group. You change the permissions in the Select New Settings drop-down list boxes.
The options for each value are Inherited, Allowed, or Denied. The Calculated Setting column shows you the setting in effect. It is either Not Allowed (the default), Allowed, or Denied.
Note that the Calculated Setting column is not updated until you press the Save button in the toolbar. To check that the settings are what you want, press the Save button and check the Calculated Settings column.
</p><p>The default values used here are the ones set in the <a href="/proxy/index.php?option=com_help&view=help&keyref=Help25:Site_Global_Configuration#Permissions" title="Help25:Site Global Configuration">Global Configuration Permissions Tab</a>
</p>
<dl><dd><dl><dt>Configure</dt><dd> Open the template manager option screens (the modal window these options are in)
</dd><dt>Access Administration Interface</dt><dd> Open the template manager manger screens
</dd><dt>Create&#160;</dt><dd> Create new styles in the component
</dd><dt>Delete&#160;</dt><dd> Delete existing styles in the component
</dd><dt>Edit&#160;</dt><dd> Edit existing templates and styles in the component
</dd><dt>Edit State&#160;</dt><dd> Change an templates and styles state (Publish, Unpublish, Archive, and Trash) in the component.
</dd></dl>
</dd></dl>
<p>There are two very important points to understand from this screen. The first is to see how the permissions can be inherited from the parent Group. The second is to see how you can control the default permissions by Group and by Action.
This provides a lot of flexibility. For example, if you wanted Shop Suppliers to be able to have the ability to create an article about their product, you could just change their Create value to "Allowed". If you wanted to not allow members of Administrator group to delete objects or change their state, you would change their permissions in these columns to Inherited (or Denied).
It is also important to understand that the ability to have child groups is completely optional. It allows you to save some time when setting up new groups. However, if you like, you can set up all groups to have Public as the parent and not inherit any permissions from a parent group.
</p>
<h2> <span class="mw-headline" id="Toolbar_Links">Toolbar Links</span></h2>
<p>At the top left, above the Filter, you will see the following two links:
</p><p><a href="/proxy/index.php?option=com_help&view=help&keyref=File:Help25-extensions-template_manager-styles-links.png" class="image"><img alt="Help25-extensions-template manager-styles-links.png" src="http://docs.joomla.org/images/d/d8/Help25-extensions-template_manager-styles-links.png" width="182" height="37" /></a>
</p>
<ul><li><b>Styles.</b> This link takes you to the screen you are currently on.
</li><li><b>Templates.</b> Click this link to go to the <a href="/proxy/index.php?option=com_help&view=help&keyref=Help25:Extensions_Template_Manager_Templates" title="Help25:Extensions Template Manager Templates">Template Manager: Templates</a> screen.
</li></ul>
<h2> <span class="mw-headline" id="Quick_Tips">Quick Tips</span></h2>
<ul><li> If you want to use the same Style for all of the pages on your site, you just assign one style as the Default. You can also assign different Styles to different pages.
</li></ul>
<h2> <span class="mw-headline" id="Related_Information">Related Information</span></h2>
<ul><li> To edit installed templates: <a href="/proxy/index.php?option=com_help&view=help&keyref=Help25:Extensions_Template_Manager_Templates" title="Help25:Extensions Template Manager Templates">Template Manager: Templates</a>
</li></ul>

</article>