<article>
	<h1>Template Manager: Customize Template</h1>

	<p>This screen is accessed from the back-end Joomla! administrator panel. It is used to edit template master files and associated stylesheets.
</p>
<h2> <span class="mw-headline" id="How_to_Access">How to Access</span></h2>
<p>Navigate to the <a href="/proxy/index.php?option=com_help&view=help&keyref=Help25:Extensions_Template_Manager_Templates" title="Help25:Extensions Template Manager Templates">Template Manager: Templates</a> screen. To edit a template, click on the templates's name.
</p>
<h2> <span class="mw-headline" id="Description">Description</span></h2>
<p>This is where you edit a template's source code. You can edit the template's master files and stylesheets from this screen.
</p>
<h2> <span class="mw-headline" id="Screenshot">Screenshot</span></h2>
<p><a href="/proxy/index.php?option=com_help&view=help&keyref=File:Help25-extensions-template_manager-templates-edit.png" class="image"><img alt="Help25-extensions-template manager-templates-edit.png" src="http://docs.joomla.org/images/0/07/Help25-extensions-template_manager-templates-edit.png" width="670" height="283" /></a>
</p>
<h2> <span class="mw-headline" id="Details_and_Options">Details and Options</span></h2>
<h3> <span class="mw-headline" id="Template_Description">Template Description</span></h3>
<p>Shows a screenshot of the template and a description of the template
</p>
<h3> <span class="mw-headline" id="Template_Master_Files">Template Master Files</span></h3>
<ul><li><b>Edit main page template.</b> The primary file used for the template's layout.
</li><li><b>Edit error page template.</b> The template layout for the site's error pages.
</li><li><b>Edit error offline template.</b> The template layout for the site's offline pages.
</li><li><b>Edit print view template.</b> The template layout for the site's <i>print view</i> function.
</li></ul>
<h3> <span class="mw-headline" id="Stylesheets">Stylesheets</span></h3>
<p>This section contains all of the template's editable stylesheets. Click on a stylesheet's name to edit its source code.
</p>
<h3> <span class="mw-headline" id="Copy_Template">Copy Template</span></h3>
<p>Allows the template to be copied and renamed.
</p>
<h2> <span class="mw-headline" id="Toolbar">Toolbar</span></h2>
<p>At the top right you will see the toolbar:
</p><p><a href="/proxy/index.php?option=com_help&view=help&keyref=File:Help25-Toolbar-Close-Help.png" class="image"><img alt="Help25-Toolbar-Close-Help.png" src="http://docs.joomla.org/images/b/bb/Help25-Toolbar-Close-Help.png" width="115" height="65" /></a>
</p><p>The functions are:
</p>
<ul><li><b>Cancel/Close</b>. Closes the current screen and returns to the previous screen without saving any modifications you may have made.
</li><li><b>Help</b>. Opens this help screen.
</li></ul>
<h2> <span class="mw-headline" id="Quick_Tips">Quick Tips</span></h2>
<ul><li> Before editing the HTML and the CSS file of the template, it is a good idea to make a backup of the file you are editing. Also, you can edit these files outside of Joomla! using the HTML or CSS editor of your choice.
</li></ul>
<h2> <span class="mw-headline" id="Related_Information">Related Information</span></h2>
<ul><li> To install templates: <a href="/proxy/index.php?option=com_help&view=help&keyref=Help25:Extensions_Extension_Manager_Install" title="Help25:Extensions Extension Manager Install">Extension Manager: Install</a>
</li></ul>

</article>