INSERT IGNORE INTO `#__rsform_components`
(`ComponentId`, `FormId`, `ComponentTypeId`, `Order`, `Published`)
VALUES
(1, 1, 1, 2, 1),
(2, 1, 10, 1, 1),
(3, 1, 1, 3, 1),
(4, 1, 3, 4, 1),
(5, 1, 5, 5, 1),
(6, 1, 4, 6, 1),
(7, 1, 6, 7, 1),
(8, 1, 13, 8, 1),
(9, 1, 10, 9, 1);

INSERT IGNORE INTO `#__rsform_forms` SET
`FormId`=1,
`FormName`='RSformPro example',
`FormLayout`='<div class="componentheading">{global:formtitle}</div>\n{error}\n<table border="0">\n	<tr>\n		<td>{Header:caption}</td>\n		<td>{Header:body}<div class="formClr"/>{Header:validation}</td>\n		<td>{Header:description}</td>\n	</tr>\n	<tr>\n		<td>{FullName:caption} (*)</td>\n		<td>{FullName:body}<div class="formClr"/>{FullName:validation}</td>\n		<td>{FullName:description}</td>\n	</tr>\n	<tr>\n		<td>{Email:caption} (*)</td>\n		<td>{Email:body}<div class="formClr"/>{Email:validation}</td>\n		<td>{Email:description}</td>\n	</tr>\n	<tr>\n		<td>{CompanySize:caption} (*)</td>\n		<td>{CompanySize:body}<div class="formClr"/>{CompanySize:validation}</td>\n		<td>{CompanySize:description}</td>\n	</tr>\n	<tr>\n		<td>{Position:caption} (*)</td>\n		<td>{Position:body}<div class="formClr"/>{Position:validation}</td>\n		<td>{Position:description}</td>\n	</tr>\n	<tr>\n		<td>{ContactBy:caption}</td>\n		<td>{ContactBy:body}<div class="formClr"/>{ContactBy:validation}</td>\n		<td>{ContactBy:description}</td>\n	</tr>\n	<tr>\n		<td>{ContactWhen:caption} (*)</td>\n		<td>{ContactWhen:body}<div class="formClr"/>{ContactWhen:validation}</td>\n		<td>{ContactWhen:description}</td>\n	</tr>\n	<tr>\n		<td>{Submit:caption}</td>\n		<td>{Submit:body}<div class="formClr"/>{Submit:validation}</td>\n		<td>{Submit:description}</td>\n	</tr>\n	<tr>\n		<td>{Footer:caption}</td>\n		<td>{Footer:body}<div class="formClr"/>{Footer:validation}</td>\n		<td>{Footer:description}</td>\n	</tr>\n</table>\n',
`FormLayoutName`='inline',
`FormLayoutAutogenerate`=1,
`FormTitle`='RSForm! Pro example',
`Published`=1,
`Lang`='',
`ReturnUrl`='',
`Thankyou`='<p>Dear {FullName:value},</p><p> thank you for your submission. One of our staff members will contact you by  {ContactBy:value} as soon as possible.</p>',
`UserEmailText`='<p>Dear {FullName:value},</p><p> we received your contact request. Someone will get back to you by {ContactBy:value} soon. </p>',
`UserEmailTo`='{Email:value}',
`UserEmailFrom`='your@email.com',
`UserEmailFromName`='Your Company',
`UserEmailSubject`='Contact confirmation',
`UserEmailMode`=1,
`AdminEmailText`='<p>Customize this e-mail also. You will receive it as administrator. </p><p>{FullName:caption}:{FullName:value}<br />\n{Email:caption}:{Email:value}<br />\n{CompanySize:caption}:{CompanySize:value}<br />\n{Position:caption}:{Position:value}<br />\n{ContactBy:caption}:{ContactBy:value}<br />\n{ContactWhen:caption}:{ContactWhen:value}</p>',
`AdminEmailTo`='youradminemail@email.com',
`AdminEmailFrom`='{Email:value}',
`AdminEmailFromName`='Your Company',
`AdminEmailSubject`='Contact',
`AdminEmailMode`=1,
`MultipleSeparator`=', ';

INSERT IGNORE INTO `#__rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`)
VALUES
(1, 1, 'NAME', 'FullName'),
(2, 1, 'CAPTION', 'Full Name'),
(3, 1, 'REQUIRED', 'YES'),
(4, 1, 'SIZE', '20'),
(5, 1, 'MAXSIZE', ''),
(6, 1, 'VALIDATIONRULE', 'none'),
(7, 1, 'VALIDATIONMESSAGE', 'Please type your full name.'),
(8, 1, 'ADDITIONALATTRIBUTES', ''),
(9, 1, 'DEFAULTVALUE', ''),
(10, 1, 'DESCRIPTION', ''),
(11, 2, 'NAME', 'Header'),
(12, 2, 'TEXT', '<b>This text describes the form. It is added using the Free Text component</b>. HTML code can be added directly here.'),
(13, 3, 'NAME', 'Email'),
(14, 3, 'CAPTION', 'E-mail'),
(15, 3, 'REQUIRED', 'YES'),
(16, 3, 'SIZE', '20'),
(17, 3, 'MAXSIZE', ''),
(18, 3, 'VALIDATIONRULE', 'email'),
(19, 3, 'VALIDATIONMESSAGE', 'Invalid email address.'),
(20, 3, 'ADDITIONALATTRIBUTES', ''),
(21, 3, 'DEFAULTVALUE', ''),
(22, 3, 'DESCRIPTION', ''),
(23, 4, 'NAME', 'CompanySize'),
(24, 4, 'CAPTION', 'Number of Employees'),
(25, 4, 'SIZE', ''),
(26, 4, 'MULTIPLE', 'NO'),
(27, 4, 'ITEMS', '|Please Select[c]\n1-20\n21-50\n51-100\n>100|More than 100'),
(28, 4, 'REQUIRED', 'YES'),
(29, 4, 'ADDITIONALATTRIBUTES', ''),
(30, 4, 'DESCRIPTION', ''),
(31, 4, 'VALIDATIONMESSAGE', 'Please tell us how big is your company.'),
(32, 5, 'NAME', 'Position'),
(33, 5, 'CAPTION', 'Position'),
(34, 5, 'ITEMS', 'CEO\nCFO\nCTO\nHR[c]'),
(35, 5, 'FLOW', 'HORIZONTAL'),
(36, 5, 'REQUIRED', 'YES'),
(37, 5, 'ADDITIONALATTRIBUTES', ''),
(38, 5, 'DESCRIPTION', ''),
(39, 5, 'VALIDATIONMESSAGE', 'Please specify your position in the company'),
(40, 6, 'NAME', 'ContactBy'),
(41, 6, 'CAPTION', 'How should we contact you?'),
(42, 6, 'ITEMS', 'E-mail[c]\nPhone\nNewsletter[c]\nMail'),
(43, 6, 'FLOW', 'HORIZONTAL'),
(44, 6, 'REQUIRED', 'NO'),
(45, 6, 'ADDITIONALATTRIBUTES', ''),
(46, 6, 'DESCRIPTION', ''),
(47, 6, 'VALIDATIONMESSAGE', ''),
(48, 7, 'NAME', 'ContactWhen'),
(49, 7, 'CAPTION', 'When would you like to be contacted?'),
(50, 7, 'REQUIRED', 'YES'),
(51, 7, 'DATEFORMAT', 'dd.mm.yyyy'),
(52, 7, 'CALENDARLAYOUT', 'POPUP'),
(53, 7, 'ADDITIONALATTRIBUTES', ''),
(54, 7, 'READONLY', 'YES'),
(55, 7, 'POPUPLABEL', '...'),
(56, 7, 'DESCRIPTION', ''),
(57, 7, 'VALIDATIONMESSAGE', 'Please select a date when we should contact you.'),
(58, 8, 'NAME', 'Submit'),
(59, 8, 'LABEL', 'Submit'),
(60, 8, 'CAPTION', ''),
(61, 8, 'RESET', 'YES'),
(62, 8, 'RESETLABEL', 'Reset'),
(63, 8, 'ADDITIONALATTRIBUTES', ''),
(64, 9, 'NAME', 'Footer'),
(65, 9, 'TEXT', 'This form is an example. Please check our knowledgebase for articles related to how you should build your form. Articles are updated daily. <a href="http://www.rsjoomla.com/" target="_blank">http://www.rsjoomla.com/</a>');

INSERT INTO `#__rsform_components` (`ComponentId`, `FormId`, `ComponentTypeId`, `Order`, `Published`) VALUES
(10, 2, 1, 2, 1),
(11, 2, 10, 1, 1),
(12, 2, 1, 3, 1),
(13, 2, 3, 6, 1),
(14, 2, 5, 7, 1),
(15, 2, 4, 10, 1),
(16, 2, 6, 11, 1),
(17, 2, 13, 12, 1),
(18, 2, 10, 13, 1),
(19, 2, 41, 4, 1),
(20, 2, 41, 8, 1),
(21, 2, 10, 5, 1),
(22, 2, 10, 9, 1);

INSERT INTO `#__rsform_forms` (`FormId`, `FormName`, `FormLayout`, `FormLayoutName`, `FormLayoutAutogenerate`, `CSS`, `JS`, `FormTitle`, `Published`, `Lang`, `ReturnUrl`, `ShowThankyou`, `Thankyou`, `UserEmailText`, `UserEmailTo`, `UserEmailCC`, `UserEmailBCC`, `UserEmailFrom`, `UserEmailReplyTo`, `UserEmailFromName`, `UserEmailSubject`, `UserEmailMode`, `UserEmailAttach`, `UserEmailAttachFile`, `AdminEmailText`, `AdminEmailTo`, `AdminEmailCC`, `AdminEmailBCC`, `AdminEmailFrom`, `AdminEmailReplyTo`, `AdminEmailFromName`, `AdminEmailSubject`, `AdminEmailMode`, `ScriptProcess`, `ScriptProcess2`, `ScriptDisplay`, `UserEmailScript`, `AdminEmailScript`, `MetaTitle`, `MetaDesc`, `MetaKeywords`, `Required`, `ErrorMessage`, `MultipleSeparator`, `TextareaNewLines`) VALUES
(2, 'RSformPro Multipage example', '<div class="componentheading">{global:formtitle}</div>\n{error}\n<table border="0">\n	<!-- Do not remove this ID, it is used to identify the page so that the pagination script can work correctly -->\n	<tbody id="rsform_2_page_0">\n	<tr>\n		<td>{Header:caption}</td>\n		<td>{Header:body}<div class="formClr"></div>{Header:validation}</td>\n		<td>{Header:description}</td>\n	</tr>\n	<tr>\n		<td>{FullName:caption} (*)</td>\n		<td>{FullName:body}<div class="formClr"></div>{FullName:validation}</td>\n		<td>{FullName:description}</td>\n	</tr>\n	<tr>\n		<td>{Email:caption} (*)</td>\n		<td>{Email:body}<div class="formClr"></div>{Email:validation}</td>\n		<td>{Email:description}</td>\n	</tr>\n	<tr>\n		<td>&nbsp;</td>\n		<td>{Page1:body}</td>\n		<td>&nbsp;</td>\n	</tr>\n	</tbody>\n<!-- Do not remove this ID, it is used to identify the page so that the pagination script can work correctly -->\n	<tbody id="rsform_2_page_1">\n	<tr>\n		<td>{CompanyHeader:caption}</td>\n		<td>{CompanyHeader:body}<div class="formClr"></div>{CompanyHeader:validation}</td>\n		<td>{CompanyHeader:description}</td>\n	</tr>\n	<tr>\n		<td>{CompanySize:caption} (*)</td>\n		<td>{CompanySize:body}<div class="formClr"></div>{CompanySize:validation}</td>\n		<td>{CompanySize:description}</td>\n	</tr>\n	<tr>\n		<td>{Position:caption} (*)</td>\n		<td>{Position:body}<div class="formClr"></div>{Position:validation}</td>\n		<td>{Position:description}</td>\n	</tr>\n	<tr>\n		<td>&nbsp;</td>\n		<td>{Page2:body}</td>\n		<td>&nbsp;</td>\n	</tr>\n	</tbody>\n<!-- Do not remove this ID, it is used to identify the page so that the pagination script can work correctly -->\n	<tbody id="rsform_2_page_2">\n	<tr>\n		<td>{ContactHeader:caption}</td>\n		<td>{ContactHeader:body}<div class="formClr"></div>{ContactHeader:validation}</td>\n		<td>{ContactHeader:description}</td>\n	</tr>\n	<tr>\n		<td>{ContactBy:caption}</td>\n		<td>{ContactBy:body}<div class="formClr"></div>{ContactBy:validation}</td>\n		<td>{ContactBy:description}</td>\n	</tr>\n	<tr>\n		<td>{ContactWhen:caption} (*)</td>\n		<td>{ContactWhen:body}<div class="formClr"></div>{ContactWhen:validation}</td>\n		<td>{ContactWhen:description}</td>\n	</tr>\n	<tr>\n		<td>{Submit:caption}</td>\n		<td>{Submit:body}<div class="formClr"></div>{Submit:validation}</td>\n		<td>{Submit:description}</td>\n	</tr>\n	<tr>\n		<td>{Footer:caption}</td>\n		<td>{Footer:body}<div class="formClr"></div>{Footer:validation}</td>\n		<td>{Footer:description}</td>\n	</tr>\n	</tbody>\n</table>\n', 'inline', 1, '', '', 'RSForm! Pro Multipage example', 1, '', '', 0, '<p>Dear {FullName:value},</p><p> thank you for your submission. One of our staff members will contact you by  {ContactBy:value} as soon as possible.</p>', '<p>Dear {FullName:value},</p><p> we received your contact request. Someone will get back to you by {ContactBy:value} soon. </p>', '{Email:value}', '', '', 'your@email.com', '', 'Your Company', 'Contact confirmation', 1, 0, '', '<p>Customize this e-mail also. You will receive it as administrator. </p><p>{FullName:caption}:{FullName:value}<br />\n{Email:caption}:{Email:value}<br />\n{CompanySize:caption}:{CompanySize:value}<br />\n{Position:caption}:{Position:value}<br />\n{ContactBy:caption}:{ContactBy:value}<br />\n{ContactWhen:caption}:{ContactWhen:value}</p>', 'youradminemail@email.com', '', '', '{Email:value}', '', 'Your Company', 'Contact', 1, '', '', '', '', '', 0, 'This is the meta description of your form. You can use it for SEO purposes.', 'rsform, contact, form, joomla', '(*)', '<p class="formRed">Please complete all required fields!</p>', ', ', 1);

INSERT INTO `#__rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES
(68, 10, 'NAME', 'FullName'),
(69, 10, 'CAPTION', 'Full Name'),
(70, 10, 'REQUIRED', 'YES'),
(71, 10, 'SIZE', '20'),
(72, 10, 'MAXSIZE', ''),
(73, 10, 'VALIDATIONRULE', 'none'),
(74, 10, 'VALIDATIONMESSAGE', 'Please type your full name.'),
(75, 10, 'ADDITIONALATTRIBUTES', ''),
(76, 10, 'DEFAULTVALUE', ''),
(77, 10, 'DESCRIPTION', ''),
(78, 10, 'VALIDATIONEXTRA', ''),
(79, 11, 'NAME', 'Header'),
(80, 11, 'TEXT', '<b>This text describes the form. It is added using the Free Text component</b>. HTML code can be added directly here.'),
(81, 12, 'NAME', 'Email'),
(82, 12, 'CAPTION', 'E-mail'),
(83, 12, 'REQUIRED', 'YES'),
(84, 12, 'SIZE', '20'),
(85, 12, 'MAXSIZE', ''),
(86, 12, 'VALIDATIONRULE', 'email'),
(87, 12, 'VALIDATIONMESSAGE', 'Invalid email address.'),
(88, 12, 'ADDITIONALATTRIBUTES', ''),
(89, 12, 'DEFAULTVALUE', ''),
(90, 12, 'DESCRIPTION', ''),
(91, 12, 'VALIDATIONEXTRA', ''),
(92, 13, 'NAME', 'CompanySize'),
(93, 13, 'CAPTION', 'Number of Employees'),
(94, 13, 'SIZE', ''),
(95, 13, 'MULTIPLE', 'NO'),
(96, 13, 'ITEMS', '|Please Select[c]\n1-20\n21-50\n51-100\n>100|More than 100'),
(97, 13, 'REQUIRED', 'YES'),
(98, 13, 'ADDITIONALATTRIBUTES', ''),
(99, 13, 'DESCRIPTION', ''),
(100, 13, 'VALIDATIONMESSAGE', 'Please tell us how big is your company.'),
(101, 14, 'NAME', 'Position'),
(102, 14, 'CAPTION', 'Position'),
(103, 14, 'ITEMS', 'CEO\nCFO\nCTO\nHR[c]'),
(104, 14, 'FLOW', 'HORIZONTAL'),
(105, 14, 'REQUIRED', 'YES'),
(106, 14, 'ADDITIONALATTRIBUTES', ''),
(107, 14, 'DESCRIPTION', ''),
(108, 14, 'VALIDATIONMESSAGE', 'Please specify your position in the company'),
(109, 15, 'NAME', 'ContactBy'),
(110, 15, 'CAPTION', 'How should we contact you?'),
(111, 15, 'ITEMS', 'E-mail[c]\nPhone\nNewsletter[c]\nMail'),
(112, 15, 'FLOW', 'HORIZONTAL'),
(113, 15, 'REQUIRED', 'NO'),
(114, 15, 'ADDITIONALATTRIBUTES', ''),
(115, 15, 'DESCRIPTION', ''),
(116, 15, 'VALIDATIONMESSAGE', ''),
(117, 16, 'NAME', 'ContactWhen'),
(118, 16, 'CAPTION', 'When would you like to be contacted?'),
(119, 16, 'REQUIRED', 'YES'),
(120, 16, 'DATEFORMAT', 'dd.mm.yyyy'),
(121, 16, 'CALENDARLAYOUT', 'POPUP'),
(122, 16, 'ADDITIONALATTRIBUTES', ''),
(123, 16, 'READONLY', 'YES'),
(124, 16, 'POPUPLABEL', '...'),
(125, 16, 'DESCRIPTION', ''),
(126, 16, 'VALIDATIONMESSAGE', 'Please select a date when we should contact you.'),
(127, 17, 'NAME', 'Submit'),
(128, 17, 'LABEL', 'Submit'),
(129, 17, 'CAPTION', ''),
(130, 17, 'RESET', 'YES'),
(131, 17, 'RESETLABEL', 'Reset'),
(132, 17, 'ADDITIONALATTRIBUTES', ''),
(133, 18, 'NAME', 'Footer'),
(134, 18, 'TEXT', 'This form is an example. Please check our knowledgebase for articles related to how you should build your form. Articles are updated daily. <a href="http://www.rsjoomla.com/" target="_blank">http://www.rsjoomla.com/</a>'),
(135, 19, 'NAME', 'Page1'),
(136, 19, 'NEXTBUTTON', 'Next >'),
(137, 19, 'PREVBUTTON', 'Prev'),
(138, 19, 'ADDITIONALATTRIBUTES', ''),
(139, 20, 'NAME', 'Page2'),
(140, 20, 'NEXTBUTTON', 'Next >'),
(141, 20, 'PREVBUTTON', 'Prev'),
(142, 20, 'ADDITIONALATTRIBUTES', ''),
(143, 21, 'NAME', 'CompanyHeader'),
(144, 21, 'TEXT', 'Please tell us a little about your company.'),
(145, 22, 'NAME', 'ContactHeader'),
(146, 22, 'TEXT', 'Please let us know how and when to contact you.');