<?php
/**
 * @package    hubzero-cms
 * @copyright  Copyright 2005-2019 HUBzero Foundation, LLC.
 * @license    http://opensource.org/licenses/MIT MIT
 */

// No direct access.
defined('_HZEXEC_') or die();
?>
<article>
	<h1>Newsletter Help</h1>
	<p>Below are links to help articles for the newsletter section of the HUB.</p>
	<ul>
		<li>
			<a href="<?php echo Route::url('index.php?option=com_help&component=newsletter&page=emailtracking'); ?>">How Email Tracking Works</a>
		</li>
	</ul>
</article>