<article>
	<h1><span>Course Certificate</span></h1>
	<section>
		<h2><span>Overview</span></h2>

		<p>The certificate interface allows for a <strong>PDF</strong> to be uploaded. Once uploaded, a preview will be available where you can place, drag, and resize various elements for items such as the user's name, course name, etc. to be dynamically filled in when a certificate is claimed.</p>
		<p>Click a button to add an element to the certificate. Position desired elements and click "save".</p>
	</section>
</article>