<article>
	<h1><span>Course Certificate</span></h1>
	<section>
		<h2><span>Overview</span></h2>

		<p>The certificate interface allows for a <strong>PDF</strong> to be uploaded. Once uploaded, a preview will be available where you can place, drag, and resize various elements for items such as the user's name, course name, etc. to be dynamically filled in when a certificate is claimed.</p>
	</section>
	<section>
		<h2><span>Placing Elements</span></h2>
		<p>After uploading a certificate file, a preview of the file will be presented. Just above the preview is a toolbar consisting of a number of buttons. Each button represents a placeholder for information pertaining to the user claiming said certificate. For example, the placeholder "Name" will inject the current ticket redeemer's name into the spot where "Name" is positioned on the certificate preview. Click a button to add an element to the certificate. Position desired elements and click "save".</p>
	</section>
	<section>
		<h2><span>Replacing a Certificate / Deleting a Certificate</span></h2>
		<p>To replace an existing certificate or remove it entirely, press the "Delete" button (typically, looks like a trashcan) in the top toolbar. This will <strong>permanenetly</strong> remove any uploaded certificate file and layout information (i.e., placeholders).</p>
	</section>
</article>