<article>
	<h1><span>Courses Manager: Edit Course</span></h1>

	<ul class="nav">
		<li><a href="#overview">Overview</a></li>
		<li><a href="#toolbar">Toolbar</a></li>
		<li><a href="#details">Details</a></li>
		<li><a href="#publishing">Publishing</a></li>
		<li><a href="#image">Image</a></li>
		<li><a href="#managers">Managers</a></li>
	</ul>

	<section id="overview">
		<h2><span>Overview</span></h2>

		<p>This is the form for editing a course or creating a new course.</p>
	</section>
	<section id="toolbar">
		<h2><span>Toolbar</span></h2>
		<p>At the top right you will see the toolbar.</p>
		<p>The functions are:</p>
		<dl>
			<dt>Save</dt>
			<dd>Save changes and return to the edit form.</dd>

			<dt>Save &amp; Close</dt>
			<dd>Save changes and return to the listing of entries.</dd>

			<dt>Cancel</dt>
			<dd>Discard any changes made and return to the listing of entries.</dd>

			<dt>Help</dt>
			<dd>Opens this help screen.</dd>
		</dl>
	</section>
	<section id="details">
		<h2><span>Details</span></h2>

		<p>Every entry consists of a <strong>title</strong>, and <strong>alias</strong>. Preferrebly, all entries should also have a short blurb and longer, detailed description.</p>

		<dl>
			<dt>Group</dt>
			<dd>This is for associating a group with a course. If a value is chosen, the course's overview page will display information about the group ownership and can be foudn by filterting the course catalog by the chosen group.</dd>

			<dt>Title</dt>
			<dd>The full name of the course. A required field.</dd>

			<dt>Alias</dt>
			<dd>This is an optional unique identifier used priamrily for URLs. When an alias isn't provided, one is generated from the provided title. The text is made lowercase, all punctuation is stripped, and spaces are turned into dashes.</dd>

			<dt>Blurb</dt>
			<dd>This is the text that appears in the course catalog and comprises a short one or two sentences that briefly describe the course.</dd>

			<dt>Description</dt>
			<dd>A brief description for the collection.</dd>

			<dt>Tags</dt>
			<dd>A comma-separated list of tags. Tags are keywords or phrases associated with the course and allow site visitors to discover entries based on topics or interests.</dd>
		</dl>
	</section>
	<section id="publishing">
		<h2><span>Publishing</span></h2>

		<p>The following options control various aspects of the published state (when and if an entry is available to users).</p>

		<dl>
			<dt>State</dt>
			<dd>The published status of the entry. Unpublished and trashed jobs will never be run.</dd>
		</dl>
	</section>
	<section id="image">
		<h2><span>Image</span></h2>

		<p>This area is for uploading a picture to be associated with the course. The image can appear int he course catalog, courses intro page, and course overview. <strong>Note:</strong> An entry must be saved first before a picture can be added.</p>
	</section>
	<section id="managers">
		<h2><span>Managers</span></h2>

		<p>Here is where users can be made managers of the course, giving them full edit capabilities.</p>
	</section>
</article>