			<h1><span>Courses</span></h1>
			<div class="section">
				<h2><span>Overview</span></h2>

				<p>Items found here are essentially catalog entries. This includes the name of the course</p>
			</div>
			<div class="section">
				<h2><span>Managers</span></h2>

				<p>Managers of a course have full permissions to create, edit, or delete content for any offering or section within the course.</p>
			</div>
			<div class="section">
				<h2><span>Offerings</span></h2>

				<p>An offering contains all the course materials such as videos, slides, homeworks, and exams.</p>

				<h3>When to create a new offering</h3>

				<p>A new offering should only be created when significant changes have been made to the course materials. A typo (misspelling or error in grammar) would not be considered <strong>significant</strong>.</p>
			</div>
			<div class="section">
				<h2><span>Pages</span></h2>

				<p>This is supplementary information related to the course as a whole and <strong>not</strong> specific to particular offering. The most common page will be "Frequently Asked Questions" (FAQs) about the course containing information on "How is the course going to work?" or "Why should I take these courses?". Information concerning specific lecture content is discouraged as lecture content is subject to change between offerings.</p>
			</div>