			<h1><span>Course Roles</span></h1>
			<div class="section">
				<h2><span>Overview</span></h2>

				<p>
					The course Roles works in conjunction with a user login system to allow or deny a user access to course content and various information or features of a course.
				</p>

				<p class="note">
					Roles are not fully implemented at this time. Currently, the only role that differs from the others in functionality is "instructor".
				</p>
			</div>
			<div class="section">
				<h2><span>Instructors</span></h2>

				<p>
					Instructors will appear in the "Instructors" list on the course overview and, if discussions are enabled, all comments from an instructor will be labeled as such.
				</p>
			</div>
			<div class="section">
				<h2><span>Managers</span></h2>

				<p>
					Managers have full access to a course and its contents, editing capabilities, and so forth but are not listed or noted as such on the overview or elsewhere within the course as instructors are.
				</p>
			</div>