			<h1><span>Course Sections</span></h1>
			<div class="section">
				<h2><span>Overview</span></h2>

				<p>A section not only supplies information about the days and time when students may access content to study a particular subject (course), they also differentiate a particular group of students enrolled in a course from all other groups of students, enrolled in either in the same course or different courses.</p>
				<p>Section dates are used to indicate that a course is being offered during a time period.</p>
			</div>
			<div class="section">
				<h2><span>Students</span></h2>

				<p>This is a list of all students enrolled in this section.</p>
			</div>
			<div class="section">
				<h2><span>Codes</span></h2>

				<p>These are redeemable coupon codes. Each code is unique, tied to a specific section, and can only be used once.</p>
			</div>