<?php
/**
 * HUBzero CMS
 *
 * Copyright 2005-2011 Purdue University. All rights reserved.
 *
 * This file is part of: The HUBzero(R) Platform for Scientific Collaboration
 *
 * The HUBzero(R) Platform for Scientific Collaboration (HUBzero) is free
 * software: you can redistribute it and/or modify it under the terms of
 * the GNU Lesser General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any
 * later version.
 *
 * HUBzero is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * HUBzero is a registered trademark of Purdue University.
 *
 * @package   hubzero-cms
 * @author    Christopher Smoak <csmoak@purdue.edu>
 * @copyright Copyright 2005-2011 Purdue University. All rights reserved.
 * @license   http://www.gnu.org/licenses/lgpl-3.0.html LGPLv3
 */

// Check to ensure this file is included in Joomla!
defined('_JEXEC') or die('Restricted access');

// lets see if the logged in user is a manager in any super groups
$superGroups = \Hubzero\User\Helper::getGroups(
	JFactory::getUser()->get('id'), 
	'managers',
	3
);

// are page modules enabled for standard groups
$groupParams = JComponentHelper::getParams('com_groups');
$groupModules = $groupParams->get('page_modules', 0);
?>

<h1>Group Help</h1>
<p>Groups are a way to connect people with a common interest. They are also an easy way to share content and conversation, either privately or with the world.</p>
<ul>
	<li>
		<a href="<?php echo JRoute::_('index.php?option=com_help&component=groups&page=general'); ?>">What are Groups?</a>
	</li>
	<li>
		<a href="<?php echo JRoute::_('index.php?option=com_help&component=groups&page=membership'); ?>">Group Membership</a>
	</li>
	<li>
		<a href="<?php echo JRoute::_('index.php?option=com_help&component=groups&page=pages'); ?>">Group Pages</a>
	</li>
	<li>
		<a href="<?php echo JRoute::_('index.php?option=com_help&component=groups&page=categories'); ?>">Group Page Categories</a>
	</li>

	<?php if ((!empty($superGroups) && count($superGroups) > 0) || $groupModules) : ?>
		<li>
			<a href="<?php echo JRoute::_('index.php?option=com_help&component=groups&page=modules'); ?>">Group Page Modules</a>
		</li>
	<?php endif; ?>

	<?php if (!empty($superGroups) && count($superGroups) > 0) : ?>
		<li>
			<a href="<?php echo JRoute::_('index.php?option=com_help&component=groups&page=supergroup'); ?>">Super Groups</a>
		</li>
		<li>
			<a href="<?php echo JRoute::_('index.php?option=com_help&component=groups&page=supergroup_development'); ?>">Super Group Development</a>
		</li>
	<?php endif; ?>
	<li>
		<a href="<?php echo JRoute::_('index.php?option=com_help&component=groups&page=guidelines'); ?>">Guidelines &amp; Tips</a>
	</li>
	<li>
		<a href="<?php echo JRoute::_('index.php?option=com_help&component=groups&page=faqs'); ?>">FAQs</a>
	</li>
</ul>