<?php
/**
 * HUBzero CMS
 *
 * Copyright 2005-2011 Purdue University. All rights reserved.
 *
 * This file is part of: The HUBzero(R) Platform for Scientific Collaboration
 *
 * The HUBzero(R) Platform for Scientific Collaboration (HUBzero) is free
 * software: you can redistribute it and/or modify it under the terms of
 * the GNU Lesser General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any
 * later version.
 *
 * HUBzero is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * HUBzero is a registered trademark of Purdue University.
 *
 * @package   hubzero-cms
 * @author    Christopher Smoak <csmoak@purdue.edu>
 * @copyright Copyright 2005-2011 Purdue University. All rights reserved.
 * @license   http://www.gnu.org/licenses/lgpl-3.0.html LGPLv3
 */

// Check to ensure this file is included in Joomla!
defined('_JEXEC') or die('Restricted access');

$groupCname = JRequest::getVar('cn', '');
?>
<h1>Group Pages</h1>

<p>Groups pages are a great way to add extra content pages to your group.</p>

<hr />

<a name="grouphomepageoverride"></a>
<h2>Overriding Group Home Page</h2>
<p>You can override the group home page by setting one of your group pages to be the home page via the manage pages interface.</p>

<?php if ($groupCname != '') : ?>
	<a target="_blank" onclick="window.opener.location=this.href;return false;" href="<?php echo JRoute::_('index.php?option=com_groups&cn='.$groupCname.'&task=pages'); ?>">Open the group page manager</a>
<?php endif; ?>

<hr />

