<?php
/**
 * HUBzero CMS
 *
 * Copyright 2005-2011 Purdue University. All rights reserved.
 *
 * This file is part of: The HUBzero(R) Platform for Scientific Collaboration
 *
 * The HUBzero(R) Platform for Scientific Collaboration (HUBzero) is free
 * software: you can redistribute it and/or modify it under the terms of
 * the GNU Lesser General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any
 * later version.
 *
 * HUBzero is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * HUBzero is a registered trademark of Purdue University.
 *
 * @package   hubzero-cms
 * @author    Christopher Smoak <csmoak@purdue.edu>
 * @copyright Copyright 2005-2011 Purdue University. All rights reserved.
 * @license   http://www.gnu.org/licenses/lgpl-3.0.html LGPLv3
 */

// Check to ensure this file is included in Joomla!
defined('_JEXEC') or die('Restricted access');
?>
<h1>Super Group Development (Overview)</h1>

<h4>Table of Contents</h4>
<ul>
	<li><a href="#whatisgitlab">What is Gitlab?</a></li>
	<li><a href="#whygithub">Why Gitlab?</a></li>
</ul>

<hr />

<h3 id="whatisgitlab">What is Gitlab?</h3>
<p>In efforts to make super group development easier, we are utilizing a code management tool called <a href="https://www.gitlab.com/" target="_blank">Gitlab</a>. Similar to <a href="https://www.github.com/" target="_blank">Github</a> in functionality and looks, it provides an easy way for the developers to write &amp; push code and give the HUBzero team the security we needed to allow third party developers to commit code to production machines.</p>

<hr />

<h3 id="whygithub">Why Gitlab?</h3>
<p>There are many benefits for both parties (the developer &amp; the Hub team) to using a tool like Gitlab for managing the code of a super group.</p>

<h6>Security</h6>
<p>Live site access can be very dangerous for even a very experienced developer. The use of Gitlab removes the need to access the live site all together. The developer can code and test in whatever environement they want, add their changes and the hub can pull in the approved changes right through the HUB admin interface.</p>

<p>Gitlab also allows the HUB team to monitor and approve code after the developer has pushed their updates. Changes MUST be approved by the HUB team before they can be moved to the live site.</p>

<hr />

<h6>Developer Freedom</h6>
<p>Developers will actually work on whats called a "forked" copy of the super group repository. This means they they are working on their very own version of the super group code and can do whatever they want to it without affecting the live site super group or any other developers also working on the super group.</p>

<hr />

<h6>Frequent Updates</h6>
<p>Managing the super groups by Gitlab (outside of the main CMS), allows for more regular updates. At any point after the hub is configured to work with Gitlab, any hub admin who has access to the groups adminstrator panel can update the the super groups code.</p>

<hr />

<h6>Extra Features</h6>
<p>Along with a nice code browser/editor, Gitlab comes with an Issue tracker and Wiki section for each project. Each project has the ability to use those sections however these please.</p>






