<article>
	<h1><span>Blog Entry: Comment</span></h1>

	<ul class="nav">
		<li><a href="#overview">Overview</a></li>
		<li><a href="#toolbar">Toolbar</a></li>
		<li><a href="#details">Details</a></li>
		<li><a href="#publishing">Publishing</a></li>
	</ul>

	<section id="overview">
		<h2><span>Overview</span></h2>

		<p>This is the edit/creation form for a comment posted to a blog entry.</p>
	</section>
	<section id="toolbar">
		<h2><span>Toolbar</span></h2>
		<p>At the top right you will see the toolbar.</p>
		<p>The functions are:</p>
		<dl>
			<dt>Save</dt>
			<dd>Save changes and return to the edit form.</dd>

			<dt>Save &amp; Close</dt>
			<dd>Save changes and return to the listing of entries.</dd>

			<dt>Cancel</dt>
			<dd>Discard any changes made and return to the listing of entries.</dd>

			<dt>Help</dt>
			<dd>Opens this help screen.</dd>
		</dl>
	</section>
	<section id="details">
		<h2><span>Details</span></h2>

		<dl>
			<dt>Anonymous</dt>
			<dd>This is a flag to indicate if the user posted the question anonymously. Entries marked as anonymous will not display the poster's name or link to their profile.</dd>

			<dt>Content</dt>
			<dd>The primary body of the post. A required field.</dd>
		</dl>
	</section>
	<section id="publishing">
		<h2><span>Publishing</span></h2>

		<dl>
			<dt>State</dt>
			<dd>
				<p>The pulishing state of a comment. This affects how and when an entry is seen.</p>
				<ul>
					<li><strong>Unpublished</strong> - Does not display on the site or in search results.</li>
					<li><strong>Published</strong> - Viewable by site visitors and discoverable in searches and listings.</li>
					<li><strong>Trashed</strong> - Does not display on the site or in search results.</li>
					<li><strong>Flagged</strong> - Content was flagged. Entry will be visible but content may be replaced with a message denoting it as being under review.</li>
				</ul>
			</dd>
		</dl>
	</section>
</article>