tinyMCE.addI18n('en.dlg',{
// JCE specific
modified: 'Modified',
file: 'File',
folder: 'Folder',
files: 'files',
folders: 'folders',
comments: 'Comments',
size: 'Size',
preview: 'Preview',
duration: 'Duration',
dimensions: 'Dimensions',
contents: 'Contents',
unwritable: 'Unwritable',
bad_name: 'Bad file or folder name',
message_tree: 'Building tree list...',
message_load: 'Loading...',
message_properties: 'Retrieving properties...',
current_dir: 'Current directory is: ',
help: 'Help',
name: 'Name',
uploading: 'Uploading...',
upload: 'Upload',
queue: 'Queue',
upload_exits: 'Action if file exists: ',
overwrite: 'Overwrite file',
unique: 'Create unique name',
cancel: 'Cancel',
ok: 'OK',
browse: 'Browse',
'options': 'Options',
'confirm': 'Confirm',
yes: 'Yes',
no: 'No',
'alert': 'Alert',
new_folder: 'New Folder',
rename: 'Rename',
'delete': 'Delete',
delete_folder_alert: 'Delete folder?',
delete_file_alert: 'Delete file(s)?',
rename_folder: 'Rename Folder',
rename_file: 'Rename File',
rename_alert: 'Renaming files/folders will break existing links. Continue?',
file_select: 'Click on a file name to insert, click to the right of the name to view its properties. CTRL+Click selects multiple files.',
notwritable: 'Unwritable',
notwritable_desc: 'Unwritable::Folder or file is not writable and cannot be renamed, moved or deleted.',
bad_name: 'Bad file or folder name',
bad_name_desc: 'Bad file or folder name::Folder/file name can only contain the characters a-zA-Z0-9_-.',
select_value: 'Add Value'
});