<article>
	<h1><span>OAIPMH</span></h1>
	<ul class="nav">
		<li><a href="#overview">Overview</a></li>
		<li><a href="#dublincore">Dublin Core Specifications</a></li>
		<li><a href="#guide">Manual Harvesting Guide</a></li>
		<li><a href="#toolbar">Toolbar</a></li>
	</ul>
	<section id="overview">
		<h2><span>Overview</span></h2>

		<p>The Open Archives Initiative Protocol for Metadata Harvesting (OAI-PMH) is a low-barrier mechanism for repository interoperability. Data Providers are repositories that expose structured metadata via OAI-PMH. Service Providers then make OAI-PMH service requests to harvest that metadata. OAI-PMH is a set of six verbs or services that are invoked within HTTP.</p>
	</section>
	<section id="dublincore">
		<h2><span>Dublin Core Specifications</span></h2>

		<p>The OAI-PMH component allows custom SQL statements to be written that allow discovery and exposure of records that exist anywhere within a HUB. Each of the 15 Dublin Core elements can be individually modified to point to different tables or fields. You may also create additional groups of SQL statements to expose multiple sets of records from multiple groups of tables. By default, all values for the standard HUB Records have been populated.</p>
		<ol>
			<li><strong>Resource IDs</strong>: a SQL statement to SELECT only the database IDs of the records you wish to expose with this group. These IDs will be used in the remainder of this group’s DC queries with the variable <code>$id</code>. Default: <code>SELECT id FROM #__resources WHERE standalone = 1</code></li>
			<li><strong>Specify sets</strong>: a SQL to SELECT the setName, setSpec, and setDesc for this group of sets. If you would like to exclude certain sets from this group, you may do it here. Default: <code>SELECT alias, type, description FROM #__resource_types WHERE category = 27</code></li>
			<li><strong>Dublin Core Elements</strong>: By default, the OAI-PMH component is populated with SQL statements for Title, Author, Subject, Description, Date, Identifier, and Relation from the <code>#__resources</code> table. You may modify these and add the remaining elements for the first group. You may enter SQL statements or static values in any of these fields.</li>
			<li><strong>Additional Groups</strong>: Click Add Group to create a new tab and a new group of SQL statements for an additional set. Repeat steps 1-3 for this new tab. To remove a group, click [ remove group ] at the bottom of any tab (except Group 1).</li>
		</ol>
	</section>
	<section id="guide">
		<h2><span>Manual Harvesting Guide</span></h2>

		<p>Begin with:</p>
		<pre>yourhub.com/oaipmh?</pre>

		<p>Add a verb:</p>
		<pre>verb=GetRecord&amp;identifier=(a unique record ID)<br />
verb=ListSets<br />
verb=Identify<br />
verb=ListMetadataFormats<br />
verb=ListIdentifiers<br />
verb=ListRecords</pre>

		<p>Specify your metadata format (not needed for ListSets, Identify, ListMetadataFormats):</p>
		<pre>&amp;metadataPrefix=oai_dc&amp;metadataPrefix=oai_ore</pre>

		<p>If using ListIdentifiers or ListRecords, you may specify a date range:</p>
		<pre>&amp;from=YYYY-MM-DD<br />&amp;until=YYYY-MM-DD</pre>

		<p>To view the next page of results, find the &lt;resumptionToken&gt;XXXXX&lt;/resumptionToken&gt; at the bottom of the XML and place it at the end of the query string:</p>
		<pre>&amp;resumptionToken=XXXXX</pre>

		<p>Example:</p>
		<pre>yourhub.com/oaipmh?verb=ListRecords&amp;metadataPrefix=oai_dc</pre>
	</section>
	<section id="toolbar">
		<h2><span>Toolbar</span></h2>
		<p>At the top right you will see the toolbar.</p>
		<p>The functions are:</p>
		<dl>
			<dt>Options</dt>
			<dd>Opens the Options window where settings such as default parameters or permissions can be edited.</dd>

			<dt>Save Settings</dt>
			<dd>Save the current configurations.</dd>

			<dt>Cancel</dt>
			<dd>Cancel any changes and revert to previous settings.</dd>

			<dt>Help</dt>
			<dd>Opens this help screen.</dd>
		</dl>
	</section>
</article>