<article>
	<h1><span>OAIPMH</span></h1>
	<ul class="nav">
		<li><a href="#overview">Overview</a></li>
		<li><a href="#schemas">Schemas</a></li>
		<li><a href="#providers">Data Providers</a></li>
		<li><a href="#guide">Manual Harvesting Guide</a></li>
		<li><a href="#toolbar">Toolbar</a></li>
	</ul>
	<section id="overview">
		<h2><span>Overview</span></h2>

		<p>The Open Archives Initiative Protocol for Metadata Harvesting (OAI-PMH) is a low-barrier mechanism for repository interoperability. Data Providers are repositories that expose structured metadata via OAI-PMH. Service Providers then make OAI-PMH service requests to harvest that metadata. OAI-PMH is a set of six verbs or services that are invoked within HTTP.</p>
	</section>
	<section id="schemas">
		<h2><span>Schemas</span></h2>

		<p>The OAI-PMH component allows for output in various data schemas. Click the <strong>Schemas</strong> sub-menu item to view the installed schemas and the <code>metadataPrefix</code> used to output data in the respective schema.</p>
	</section>
	<section id="providers">
		<h2><span>Data Providers</span></h2>

		<p>The OAI-PMH component uses data providers for feeding records to the service. Each provider is represented by a plugin. This allows for easy addition, removal, and configuration of data types without having to modify the core OAIPMH code. The list of available plugins can be found and configured by clicking the <strong>Plugins</strong> menu item above or by navigating to the <strong>Plugins Manager</strong> and filtering by type "oaipmh".</p>
	</section>
	<section id="guide">
		<h2><span>Manual Harvesting Guide</span></h2>

		<p>Begin with:</p>
		<pre>yourhub.com/oaipmh?</pre>

		<p>Add a verb:</p>
		<pre>verb=GetRecord&amp;identifier=(a unique record ID)<br />
verb=ListSets<br />
verb=Identify<br />
verb=ListMetadataFormats<br />
verb=ListIdentifiers<br />
verb=ListRecords</pre>

		<p>Specify your metadata format (not needed for ListSets, Identify, ListMetadataFormats):</p>
		<pre>&amp;metadataPrefix=oai_dc</pre>

		<p>If using ListIdentifiers or ListRecords, you may specify a date range:</p>
		<pre>&amp;from=YYYY-MM-DD<br />&amp;until=YYYY-MM-DD</pre>

		<p>To view the next page of results, find the &lt;resumptionToken&gt;XXXXX&lt;/resumptionToken&gt; at the bottom of the XML and place it at the end of the query string:</p>
		<pre>&amp;resumptionToken=XXXXX</pre>

		<p>Example:</p>
		<pre>yourhub.com/oaipmh?verb=ListRecords&amp;metadataPrefix=oai_dc</pre>
	</section>
	<section id="toolbar">
		<h2><span>Toolbar</span></h2>
		<p>At the top right you will see the toolbar.</p>
		<p>The functions are:</p>
		<dl>
			<dt>Options</dt>
			<dd>Opens the Options window where settings such as default parameters or permissions can be edited.</dd>

			<dt>Help</dt>
			<dd>Opens this help screen.</dd>
		</dl>
	</section>
</article>