<?php
/**
 * HUBzero CMS
 *
 * Copyright 2005-2015 HUBzero Foundation, LLC.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 *
 * HUBzero is a registered trademark of Purdue University.
 *
 * @package   hubzero-cms
 * @author    Christopher Smoak <csmoak@purdue.edu>
 * @copyright Copyright 2005-2015 HUBzero Foundation, LLC.
 * @license   http://opensource.org/licenses/MIT MIT
 */

// No direct access.
defined('_HZEXEC_') or die();
?>
<article>
	<h1>Tags FAQs</h1>

	<nav>
		<ol>
			<li>
				<a href="#whataretags">What are tags?</a>
			</li>
			<li>
				<a href="#createtags">How do I create a new tag?</a>
			</li>
			<li>
				<a href="#deletetags">How can I delete a tag?</a>
			</li>
			<li>
				<a href="#removetag">How can I remove a tag from a resource/group/my profile/etc?</a>
			</li>
			<li>
				<a href="#taglimit">Is there a limit on the number of tags I can add to an item?</a>
			</li>
			<li>
				<a href="#whotagged">Can I tell who's tagged another member's content?</a>
			</li>
		</ol>
	</nav>

	<section id="whataretags">
		<h3>What are tags?</h3>
		<p>Tags are like keywords or category labels. Tags help you find content, events, and members which have something in common or similar interests. Tags can be added to groups, your profile, resources, wiki pages, and events.</p>
	</section>

	<section id="createtags">
		<h3>How do I create a new tag?</h3>
		<p>When creating or editing content, your profile, groups, etc. you can add or remove tags as you wish. If a tag doesn't already exist, simply typing it in a "Tags" form field will create it and make it available for everyone to use.</p>
	</section>

	<section id="deletetags">
		<h3>How can I delete a tag?</h3>
		<p>You can't. Tags can only be deleted by the site administrators. You may only remove tags from a piece of content or profile.</p>
	</section>

	<section id="removetag">
		<h3>How can I remove a tag from a resource/group/my profile/etc?</h3>
		<p>When editing content, your profile, groups, etc. you can remove tags by simply deleting them from the list presented in the "Tags" form field.</p>
	</section>

	<section id="taglimit">
		<h3>Is there a limit on the number of tags I can add to an item?</h3>
		<p>No. You should be able to add as many tags as you want to taggable content/profiles.</p>
	</section>

	<section id="whotagged">
		<h3>Can I tell who's tagged another member's content?</h3>
		<p>No. Who tagged an item and what tags they added is currently not available to users.</p>
	</section>
</article>