<?php
/**
 * @package    hubzero-cms
 * @copyright  Copyright (c) 2005-2020 The Regents of the University of California.
 * @license    http://opensource.org/licenses/MIT MIT
 */

// No direct access.
defined('_HZEXEC_') or die();
?>
<article>
	<h1>Tags Help</h1>
	<p>Tags are like keywords or category labels. Tags help you find content, events, and members which have something in common or similar interests. Tags can be added to groups, your profile, resources, wiki pages, and events.</p>
	<ul>
		<li>
			<a href="<?php echo Route::url('index.php?option=com_help&component=tags&page=faqs'); ?>">FAQs</a>
		</li>
	</ul>
</article>