<article>
	<h1>Category Manager</h1>

	<p>Select <b>Content &#8594; Category Manager</b> from the drop-down menu on the back-end of your installation.</p>

	<section id="description">
		<h2><span>Description</span></h2>
		<p>The Category Manager is where you can edit existing Categories and create new ones. Articles are organized into Sections and Categories. Categories are the second level of organization underneath Sections. Every Section contains one or more Categories. The special Section 'Uncategorized' has a special Category also called 'Uncategorized'. These are built in.</p>
	</section>
	<section id="column-headers">
		<h2><span>Column Headers</span></h2>
		<p>Click on the column heading to sort the list by that column's value.</p>
		<dl>
			<dt>Checkbox</dt>
			<dd>Check this box to select one or more items. To select all items, check the box in the column heading. After one or more boxes are checked, click a toolbar button to take an action on the selected item or items. Many toolbar actions, such as Publish and Unpublish, can work with multiple items. Others, such as Edit, only work on one item at a time. If multiple items are checked and you press Edit, the first item will be opened for editing.</dd>

			<dt>Title</dt>
			<dd>The name of the item. For a Menu Item, the Title will display in the Menu. For an Article or Category, the Title may optionally be displayed on the web page. This entry is required. You can open the item for editing by clicking on the Title.</dd>

			<dt>Status</dt>
			<dd>(Published/Unpublished/Archived/Trashed) The published status of the item.</dd>

			<dt>Ordering</dt>
			<dd>The order in which to display items. You can sort the list by order number by clicking on the Ordering label in the column heading. If the list is sorted by this column, you can change the order by clicking the arrows or by entering the sequential order and clicking the 'Save Order' icon. Note that the ordering is only defined within a single category. For this reason, it is easier to re-order the list if you use the Category filter to select one category.</dd>

			<dt>Access</dt>
			<dd>The viewing level access for this item.</dd>

			<dt>Language</dt>
			<dd>Item language.</dd>

			<dt>ID</dt>
			<dd>This is a unique identification number for this item assigned automatically by the CMS. It is used to identify the item internally, and you cannot change this number. When creating a new item, this field displays 0 until you save the new entry, at which point a new ID is assigned to it.</dd>
		</dl>
	</section>
	<section id="toolbar">
		<h2><span>Toolbar</span></h2>
		<p>At the top right you will see the toolbar. The functions are:</p>
		<dl>
			<dt>New</dt>
			<dd>Opens the editing screen to create a new content category.</dd>
			<dt>Edit</dt>
			<dd>Opens the editing screen for the selected content category. If more than one content category is selected (where applicable), only the first content category will be opened. The editing screen can also be opened by clicking on the Title or Name of the content category.</dd>
			<dt>Publish</dt>
			<dd>Makes the selected content categories available to visitors to your website.</dd>
			<dt>Unpublish</dt>
			<dd>Makes the selected content categories unavailable to visitors to your website.</dd>
			<dt>Archive</dt>
			<dd>Changes the status of the selected content categories to indicate that they are archived.  Archived content categories can be moved back to the published or unpublished state by selecting "Archived" in the Select Status filter and changing the status of the content categories to Published or Unpublished as preferred.</dd>
			<dt>Check In</dt>
			<dd>Checks-in the selected content categories. Works with one or multiple content categories selected.</dd>
			<dt>Trash</dt>
			<dd>Changes the status of the selected content categories to indicate that they are trashed.  Trashed content categories can still be recovered by selecting "Trashed" in the Select Status filter and changing the status of the content categories to Published or Unpublished as preferred.  To permanently delete trashed content categories, select "Trashed" in the Select Status filter, select the content categories to be permanently deleted, then click the Empty Trash toolbar icon.</dd>
			<dt>Rebuild</dt>
			<dd>Reconstructs and refreshes the content category table. Normally, you do <i>not</i> need to rebuild this table. This function is provided in case the data in the table becomes corrupted.</dd>
			<dt>Options</dt>
			<dd>Opens the Options window where settings such as default parameters or permissions can be edited.</dd>
			<dt>Help</dt>
			<dd>Opens this help screen.</dd>
		</dl>
	</section>
	<section id="toolbar-links">
		<h2><span>Toolbar Links</span></h2>
		<p>At the top left, above the Filter, you will see the following links:</p>

		<dl>
			<dt>Articles</dt>
			<dd>Click this link to go to the <a href="index.php?option=com_help&view=help&keyref=Help25:Content_Article_Manager" title="Content Article Manager">Content Manager: Articles</a> screen.</dd>
			<dt>Categories</dt>
			<dd>This link takes you to the screen you are currently on.</dd>
			<dt>Featured Articles</dt>
			<dd>Click this link to go to the <a href="index.php?option=com_help&view=help&keyref=Help25:Content_Featured_Articles" title="Content Featured Articles">Content Manager: Featured Articles</a> screen.</dd>
		</dl>
	</section>
	<section id="toolbar-links">
		<h2><span>List Filters</span></h2>

		<dl>
			<dt>Filter by Partial Title</dt>
			<dd>
				<p>You can filter the list of items either by entering in part of the title or the ID number. Or you can select a combination of Section, Category, Author, and Published State.</p>
				<ul>
					<li><b>Filter by Partial Title or ID. </b> In the upper left is a filter field and two buttons.
						<ul>
							<li> To filter by partial title, enter part of the title and click Search.</li>
							<li> To filter by ID number, enter "id:xx", where "xx" is the ID number (for example, "id:9").</li>
						</ul>
					</li>
				</ul>
				<p>Click Clear to clear the Filter field and restore the list to its unfiltered state.</p>
			</dd>

			<dt>Filter by Max Levels, Status, Access, Language</dt>
			<dd>In the upper right area, above the column headings, are 4 drop-down list boxes. The selections may be combined. Only items matching all selections will display in the list.</dd>

			<dt>Filter by Max Levels (Category Level)</dt>
			<dd>
				<p>Lets you show only items whose category is at or above the specified level in the category hierarchy.</p>
				<ul>
					<li><i>- Select Max Levels -:</i> Show all items regardless of level of their assigned category.</li>
					<li><i>1:</i> Only show items whose category is at the top level in the category hierarchy (in other words, with categories whose parent category is "- No Parent -".)</li>
					<li><i>2-10:</i> Only show items whose category is in the top 2-10 levels in the category hierarchy.</li>
				</ul>
			</dd>

			<dt>Filter by Published Status</dt>
			<dd>
				<p>Lets you show only items with the selected published status.</p>
				<ul>
					<li><i>- Select Status -:</i> Shows items that are Published and Unpublished. Does <i>not</i> show items that are Trashed or Archived.</li>
					<li><i>Published:</i> Shows only items that are Published.</li>
					<li><i>Unpublished:</i> Shows only items that are Unpublished.</li>
					<li><i>Archived:</i> Shows only items that are Archived.</li>
					<li><i>Trashed:</i> Shows only items that are Trashed. <i>Important Note:</i> To permanently delete items:
						<ol>
							<li>Change the status of the items to Trashed.</li>
							<li>Change the Status filter to Trashed. At this point the trashed items will show and an icon called "Empty trash" will show in the toolbar.</li>
							<li>Select the desired trashed items and click on "Empty Trash" in the toolbar. The items will be permanently deleted.</li>
						</ol>
					</li>
					<li><i>All:</i> Shows all items regardless of published status.</li>
				</ul>
			</dd>

			<dt>Filter by Viewing Access Level</dt>
			<dd>
				<p>Lets you show only items that have a specified viewing access level. The list box will show the access levels defined for your site, similar to the example below.</p>
				<ul>
					<li><i>- Select Access -:</i> Show items with any viewing access level.</li>
					<li><i>&lt;your access level&gt;:</i> Show items only with this viewing access level.</li>
				</ul>
			</dd>

			<dt>Filter by Language</dt>
			<dd>
				<p>Lets you show only items that have a specific language assigned. The list box will show the languages defined for your site, similar to the example below.</p>
				<ul>
					<li><i>- Select Language - or All:</i> Show items for any language.</li>
					<li><i>&lt;your language&gt;:</i> Show items only for this language.</li>
				</ul>
			</dd>
		</dl>
	</section>
	<section id="batch-process">
		<h2><span>Batch Process</span></h2>
		<p>This section allows you to change settings for a group of selected items. You can change one value or all three values at one time. Note that if you copy items to a new category, changes you have selected fro access level and language will be applied to the copies, not the original. To batch process a group of items:</p>
		<ol>
			<li>Select one or more items on the list by checking the desired check boxes.</li>
			<li>Set one or more of the following values:
				<ul>
					<li>To change the access levels, select the desired new access level from the Set Access Level list box.</li>
					<li>To change the Language, select the desired language from the Set Language list box.</li>
					<li>To change the Category, select a category. To leave the category unchanged, use the default value of "Select". 
						<ul>
							<li>To copy the items to a different category, select the desired category from the category list box and check the Copy option. In this case, the original items are unchanged and the copies are assigned to the new category and, if selected, the new access level and language.</li>
							<li>To move the items to a different category, select the desired category from the category list box and check the Move option. In this case, the original items will be moved to a new category and, if selected, be assigned the new access level and language.</li>
						</ul>
					</li>
				</ul>
			</li>
			<li> When all of the settings are entered, click on Process to perform the changes. A message "Batch process completed successfully." will show.</li>
		</ol>

		<p>Note that nothing will happen if you (a) don't have any items selected or (b) have not selected an access level, language, or category.</p>
		<p>If you wish to clear your entered selections, click on the Clear button. This will return all of the Batch controls to their default values. Note that this does <i>not</i> uncheck the check boxes for the items.</p>
	</section>
	<section id="quick-tips">
		<h2><span>Quick Tips</span></h2>
		<ul>
			<li>Click on the Title of a Category to edit it.</li>
			<li>Click on the green check mark or the red X in the Published column to toggle between Published and Unpublished.</li>
			<li>Click on the Column Headers to sort the Categories by that column. Click a second time to sort descending (Z to A).</li>
		</ul>
	</section>
	<section id="related-info">
		<h2><span>Related Information</span></h2>
		<ul>
			<li>To add or edit Categories: <a href="index.php?option=com_help&view=help&keyref=Help25:Components_Content_Categories_Edit" title="Components Content Categories Edit">Category Manager - New/Edit</a></li>
			<li>To create a page showing Articles for a Category in a Blog layout: <a href="index.php?option=com_help&view=help&keyref=Screen.menus.edit.15#Category_Blog_Layout">Menu Item Manager - New/Edit - Category Blog Layout</a></li>
			<li>To create a page showing Articles for a Category in a List layout: <a href="index.php?option=com_help&view=help&keyref=Screen.menus.edit.15#Category_List_Layout">Menu Item Manager - New/Edit - Category List Layout</a></li>
		</ul>
	</section>
</article>