<article>
	<h1>Category Manager: Edit Category</h1>

	<section id="description">
		<h2><span>Description</span></h2>
		<p>This is where you can add a new Category or edit an existing Category. Categories allow you to display related Articles together on a page and to filter Articles in the Article Manager. All Articles are assigned either to a Category that you create or to the special Category called 'Uncategorized'.</p>
	</section>
	<section id="column-headers">
		<h2><span>Column Headers</span></h2>

		<h3><span>Details</span></h3>
		<dl>
			<dt>Title</dt>
			<dd>The Title for this item. This may or may not display on the page, depending on the parameter values you choose.</dd>

			<dt>Alias</dt>
			<dd>The internal name of the item. Normally, you can leave this blank and the CMS will fill in a default value. The default value is the Title or Name in lower case and with dashes instead of spaces. You may enter the Alias manually. The Alias should consist of lowercase letters and hyphens (-). No blank spaces or underscores are allowed. The Alias will be used in the URL when SEF is activated. Note: If the title consists of non-Latin characters, the Alias will default to the current date and time, for example "2009-02-11-17-54-38".</dd>

			<dt>Parent</dt>
			<dd>Allows a parent category for the category being edited/created to be chosen.</dd>

			<dt>Published</dt>
			<dd>Whether or not this item is published. Select <i>Yes</i> or <i>No</i> from the radio button group to set the Published state for this item.</dd>

			<dt>Access Level</dt>
			<dd>Who has access to this item. Current options are:
				<ul>
					<li><span style="color:green">Public</span>: Everyone has access</li>
					<li><span style="color:red">Registered</span>: Only registered users have access</li>
					<li><span style="color:black">Special</span>: Only users with author status or higher have access</li>
				</ul>

				<p>Enter the desired level using the drop-down list box.</p>
			</dd>

			<dt>Category Permissions</dt>
			<dd>
				<p>The permissions section for the category will be at the bottom of the screen. The options allowed are:</p>

				<dl>
					<dt>Create&#160;</dt>
					<dd>Create new items in the category</dd>
					<dt>Delete&#160;</dt>
					<dd>Delete existing items in the category</dd>
					<dt>Edit&#160;</dt>
					<dd>Edit existing items in the category</dd>
					<dt>Edit State&#160;</dt>
					<dd>Change an items state (Publish, Unpublish, Archive, and Trash) in the category.</dd>
					<dt>Edit Own&#160;</dt>
					<dd>Edit existing items in the category that the logged in user has created.</dd>
				</dl>

				<p>There are two very important points to understand from this screen. The first is to see how the permissions can be inherited from the parent Group. The second is to see how you can control the default permissions by Group and by Action.</p>
				<p>This provides a lot of flexibility. For example, if you wanted Shop Suppliers to be able to have the ability to create an item in the category, you could just change their Create value to "Allowed". If you wanted to not allow members of Administrator group to delete objects or change their state, you would change their permissions in these columns to Inherited (or Denied).</p>
				<p>It is also important to understand that the ability to have child groups is completely optional. It allows you to save some time when setting up new groups. However, if you like, you can set up all groups to have Public as the parent and not inherit any permissions from a parent group.</p>
				<p>Please note the inherited values will come from the Permissions set in the <a href="<?php echo Route::url('index.php?option=com_help&component=com_config&page=global_config#Permissions'); ?>" title="Help25:Site Global Configuration">Global Configuration Permissions Tab</a></p>
			</dd>

			<dt>Description</dt>
			<dd>The description for the item. Section and Category descriptions for Articles may be shown on web pages, depending on the parameter settings. These descriptions are entered using the same editor that is used for Articles. Note that Section and Category descriptions may not be edited from the front end.</dd>

			<dt>Language</dt>
			<dd>Select the language for this item. If you are not using the multi-language feature, keep the default of 'All'.</dd>

			<dt>ID</dt>
			<dd>The unique ID number automatically assigned to this item by the CMS. This number cannot be changed.</dd>
		</dl>

		<h3><span>Category Description</span></h3>
		<p>This is where you enter the description of the category. The editor you use depends on the settings for your site and your user. The core install includes multiple editor options: CKEditor (the default), TinyMCE, Code Mirror, and None. Additional editors can be installed as extension plugins if desired (see the Extensions direction category of editors for a list). A number of the editors such as CKEditor and TinyMCE are WYSIWYG (what you see is what you get) editors that allows users a familiar word-processing interface to use when editing Articles and other content. These can be configured from the <a href="index.php?option=com_help&component=com_plugins&page=plugins" title="Extensions: Plugin Manager"> Plugin Manager</a>.</p>

		<h4><span>Editor Buttons</span></h4>
		<p>Five buttons are located just below the edit window, as shown below:</p>

		<dl>
			<dt>Article</dt>
			<dd><p>This button opens a modal window that allows you to easily create a link to any article on the current site. The link is created using the article's title as the link text. The modal window is the same as for selecting an article for a Single Article Menu Item. To create a link to the desired article:</p>

				<ul>
					<li>Place the cursor at the point in the article where you want the linked article title to be inserted.</li>
					<li>Click on the Article button to open the modal window.</li>
					<li>Click on the title to select the desired article in the modal window. You can use the filters and search to help find the desired article.</li>
					<li>A link with the article's title will be inserted at the current cursor location.</li>
					<li>If needed, you can edit the link text.</li>
				</ul>
			</dd>
			<dt>Image</dt>
			<dd>
				<p>This button provides an easy way to insert an image into an Article. Images may be inserted from the 'images' folder and may also be uploaded. When you click the Image button, a window pops up, as shown below:</p>
				<ul><li><b>Directory.</b> The current directory on the host server. This is the 'images' directory under your home directory. Use the drop-down list box to select a subdirectory.
				</li><li><b>Up.</b> Navigate to the parent directory. Note that the top directory for this function is 'images/stories'. You can not navigate to a higher directory.
				</li><li><b>Insert.</b> Insert the selected image. The insert point will be the current cursor position. You will see the image display inside the edit window.
				</li><li><b>Cancel</b>. Cancel the operation and close the popup window. You can cancel also in clicking the X at right top corner.
				</li><li><b>Thumbnail Browse Area.</b> Click on an image thumbnail to select the image. Click on a folder icon to navigate to that subdirectory.
				</li><li><b>Image URL.</b> Click on one of the image thumbnails and the URL for the image will be entered for you.
				</li><li><b>Align.</b> Select the desired alignment (left or right) from the drop-down list box. 
				</li><li><b>Image Description.</b> Enter a description for the image.
				</li><li><b>Image Title.</b> Enter a Title for this image. This displays when a User hovers the mouse on the image.
				</li><li><b>Caption.</b> If checked, image title will display as a caption below the image.
				</li><li><b>Choose Files.</b> Click this button to browse to an image file to upload from your local computer. A file dialog will open allowing you to select a file.
				</li><li><b>Start Upload.</b> Once you have selected a file, press this button to upload the file to your 'images' folder. The thumbnail for the new image will now show in the thumbnail area.
				</li></ul>
			</dd>
			<dt>Pagebreak</dt>
			<dd>
				<p>This button allows you to insert a pagebreak inside an Article. A pagebreak allows for page navigation when the article is displayed on a layout. This is useful for long articles. When this button is pressed, a popup window is displayed as shown below:</p>
				<ul><li> <b>Page Title</b>. Enter the title to display for the new page (for example, 'Page 2').
				</li><li> <b>Table of Contents Alias</b>. Optional field to display in the table of contents for this page. In a multi-page article, the CMS displays a 'table of contents' for the page that allows the user to select any page. If this field is blank, the Page Title will be used. If you want a different title in the table of contents, enter it here.
				</li><li> <b>Insert Page Break.</b> Click this button to insert the pagebreak with the entered fields. The Pagebreak will display as a gray dashed line across the Article. Note that a pagebreak cannot be edited. If you need to change a field in the pagebreak, click on the Article just past the pagebreak, press Backspace until the pagebreak is deleted, then insert a new pagebreak with the desired information.
				</li><li><b>Read more...</b> This button inserts a 'Read more...' break in the Article. This shows as a red dotted line across the Article. If an Article has a 'Read more...' break, only the text before the break, called the Into Text, will initially display, along with a 'Read more...' link. If the User clicks this link, either the entire Article or just the part after the 'Read more...' link is displayed. This depends on the setting of the 'Intro Text' parameters for the Article and in the Global Configuration. The 'Read more...' break allows you to save space on pages by just showing the Intro Text. Note that the 'Read more...' break only shows in the Front Page, Section, and Category Blog layouts. If you want to insert breaks for an Article shown in an Article Layout, use the Page Break button.
				</li></ul>
			</dd>
		</dl>

		<h3><span>Publishing Options</span></h3>
		<p><strong>Note: This slider can be hidden by users with Admin Permission for the article manager.</strong></p>

		<p>This section allows you to enter parameters for this Article. These entries are optional. The CMS automatically creates default entries for these values.</p>
		<dl>
			<dt>Created by</dt>
			<dd>Name of the User who created this item. This will default to the currently logged-in user. If you want to change this to a different user, click the Select User button to select a different user.</dd>

			<dt>Created By Alias</dt>
			<dd>This optional field allows you to enter in an alias for this Author for this Article. This allows you to display a different Author name for this Article.</dd>

			<dt>Created Date</dt>
			<dd>This field defaults to the current time when the Article was created. You can enter in a different date and time or click on the calendar icon to find the desired date.</dd>

			<dt>Start Publishing</dt>
			<dd>Date and time to start publishing. Use this field if you want to enter content ahead of time and then have it published automatically at a future time.</dd>

			<dt>Finish Publishing</dt>
			<dd>Date and time to finish publishing. Use this field if you want to have content automatically changed to Unpublished state at a future time (for example, when it is no longer applicable).</dd>

			<dt>>Modified By</dt>
			<dd>Displays who last edited the article. Note this field is non-editable.</dd>

			<dt>Modified Date</dt>
			<dd>Date and time the article was last modified on. Note this field is non-editable.</dd>

			<dt>Revision</dt>
			<dd>How many times the article has been edited. Note this field is non-editable.</dd>

			<dt>Hits</dt>
			<dd>The number of times an item has been viewed.</dd>
		</dl>

		<h3><span>Basic Options</span></h3>

		<dl>
			<dt>Alternative Layout</dt>
			<dd>If you have defined one or more alternative layouts for the Single Article menu item, you can select the layout to use for this article. See <a href="<?php echo Route::url('index.php?option=com_help&view=help&keyref=Layout_Overrides'); ?>" title="Layout Overrides" class="mw-redirect">Layout Overrides</a> for more information about alternative layouts.</dd>

			<dt>Image</dt>
			<dd>Click the Select button to choose an image that will be displayed with the category. This will open a modal window that allows you to select an image from your images folder. See <a href="#Editor_Buttons">Editor Buttons</a> for more information on working with images. After you have selected an image, you can hover the mouse on the "Preview" text to see a preview of the image.</dd>

			<dt>Note</dt>
			<dd>Item note. This is normally for the site administrator's use (for example, to document information about this item) and does not show in the front end of the site.</dd>
		</dl>

		<h3><span>Metadata Options</span></h3>
		<p>This section allows you to enter Metadata Information for this Article. Metadata is information about the Article that is not displayed but is available to Search Engines and other systems to classify the Article. This gives you more control over how the content will be analyzed by these programs. All of these entries are optional. Metadata is shown inside HTML meta elements. The entry screen is shown below:</p>

		<dl>
			<dt>Meta Description</dt>
			<dd>An optional paragraph to be used as the description of the page in the HTML output. This will generally display in the results of search engines. If entered, this creates an HTML meta element with a name attribute of "description" and a content attribute equal to the entered text.</dd>

			<dt>Meta Keywords</dt>
			<dd>Optional entry for keywords. Must be entered separated by commas (for example, "cats, dogs, pets") and may be entered in upper or lower case. (For example, "CATS" will match "cats" or "Cats"). Keywords can be used in several ways:

				<ol>
					<li> To help Search Engines and other systems classify the content of the Article.</li>
					<li> In combination with Banner tags, to display specific Banners based on the Article content. For example, say you have one Banner with an ad for dog products and another Banner for cat products. You can have your dog Banner display when a User is viewing a dog-related Article and your cat Banner display for a cat-related Article. To do this, you would:
						<ol>
							<li> Add the keywords 'dog' and 'cat' to the appropriate Articles.</li>
							<li> Add the Tags 'dog' and 'cat' to the appropriate Banners in the <a href="<?php echo Route::url('index.php?option=com_help&view=help&keyref=Help25:Components_Banners_Banners_Edit'); ?>" title="Components Banners Banners Edit"> Banner Manager New/Edit</a> screen.</li>
							<li> Set the Banner module Parameter 'Search By Tags' to 'Yes in the <a href="<?php echo Route::url('index.php?option=com_help&view=help&keyref=Help25:Extensions_Module_Manager_Banners'); ?>" title="Extensions Module Manager Banners"> Banner Module Edit</a> screen.</li>
						</ol>
					</li>
					<li> For articles only, in combination with the <a href="<?php echo Route::url('index.php?option=com_help&view=help&keyref=Help25:Extensions_Module_Manager_Articles_Related'); ?>" title="Extensions Module Manager Articles Related"> Related Articles module</a>, to display Articles that share at least one keyword in common. For example, if the current Article displayed has the keywords "cats, dogs, monkeys", any other Articles with at least one of these keywords will show in the Related Articles module.</li>
				</ol>
			</dd>

			<dt>Author</dt>
			<dd>Optional entry for an Author name within the metadata. If entered, this creates an HTML meta element with the name attribute of "author" and the content attribute as entered here.</dd>

			<dt>Robots</dt>
			<dd>The instructions for web "robots" that browse to this page.
				<ul>
					<li><i>Use Global:</i> Use the value set in the Component&#8594;Options for this component.</li>
					<li><i>Index, Follow:</i> Index this page and follow the links on this page.</li>
					<li><i>No index, Follow:</i> Do not index this page, but still follow the links on the page. For example, you might do this for a site map page where you want the links to be indexed but you don't want this page to show in search engines.</li>
					<li><i>Index, No follow:</i> Index this page, but do not follow any links on the page. For example, you might want to do this for an events calendar, where you want the page to show in search engines but you do not want to index each event.</li>
					<li><i>No index, no follow:</i> Do not index this page or follow any links on the page.</li>
				</ul>
			</dd>
		</dl>
	</section>
	<section id="toolbar">
		<h2><span>Toolbar</span></h2>
		<p>At the top right you will see the toolbar. The functions are:</p>
		<dl>
			<dt>Save</dt>
			<dd>Saves the content category and stays in the current screen.</dd>
			<dt>Save &amp; Close</dt>
			<dd>Saves the content category and closes the current screen.</dd>
			<dt>Save &amp; New</dt>
			<dd>Saves the content category and keeps the editing screen open and ready to create another content category.</dd>
			<dt>Cancel/Close</dt>
			<dd>Closes the current screen and returns to the previous screen without saving any modifications you may have made.</dd>
			<dt>Help</dt>
			<dd>Opens this help screen.</dd>
		</dl>
	</section>
	<section id="related-info">
		<h2><span>Related Information</span></h2>
		<ul>
			<li>To work with existing Categories: <a href="<?php echo Route::url('index.php?option=com_help&view=help&keyref=Help25:Components_Content_Categories'); ?>" title="Components Content Categories">Category Manager</a></li>
			<li>To work with Articles: <a href="<?php echo Route::url('index.php?option=com_help&view=help&keyref=Help25:Content_Article_Manager'); ?>" title="Content Article Manager">Article Manager</a></li>
			<li>To create a page showing Articles for a Category in a Blog layout: <a href="<?php echo Route::url('index.php?option=com_help&view=help&keyref=Screen.menus.edit.15#Category_Blog_Layout'); ?>">Menu Item Manager - New/Edit - Category Blog Layout</a></li>
			<li>To create a page showing Articles for a Category in a List layout: <a href="<?php echo Route::url('index.php?option=com_help&view=help&keyref=Screen.menus.edit.15#Category_List_Layout'); ?>">Menu Item Manager - New/Edit - Category List Layout</a></li>
		</ul>
	</section>
</article>