<?php
/**
 * HUBzero CMS
 *
 * Copyright 2005-2015 HUBzero Foundation, LLC.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 *
 * HUBzero is a registered trademark of Purdue University.
 *
 * @package   hubzero-cms
 * @author    Shawn Rice <zooley@purdue.edu>
 * @copyright Copyright 2005-2015 HUBzero Foundation, LLC.
 * @license   http://opensource.org/licenses/MIT MIT
 */

// No direct access.
defined('_HZEXEC_') or die();

?>
<article>
	<h1>Forum Categories</h1>
	<p>Forum categories are a simple way to group related threads or discussions together.</p>

	<hr />

	<section>
		<h2>Locked Categories</h2>
		<p>When a category is locked, no new threads may be created within that category. Typically, a locked category will be indicated as such by a <span class="icon-lock">padloack</span> icon.</p>
	</section>
<?php if (User::authorise('core.admin', 'com_forum.component') || User::authorise('core.manage', 'com_forum.component')) { ?>
	<hr />

	<section>
		<h2>Creating a Category</h2>
		<p>Note that a category <strong>must</strong> be assigned to a section. If a suitable section does not exist, it can be created.</p>
		<p>At the bottom of each section, a "New Category" button can be found.</p>
		<ol>
			<li>Click the "New Category".</li>
			<li>Provide a title for the category.</li>
			<li>(optional) Provide a description. This is typically a short, one or two lines.</li>
			<li>Click "Save".</li>
		</ol>
		<p>After saving, the newly created category will be ready for immediate use (i.e., new threads).</p>
	</section>
	<section>
		<h2>Editing a Category</h2>
		<ol>
			<li>From the main forum page, find the desired category.</li>
			<li>Click the edit button, typically a small <span class="icon-edit">pencil</span> icon.</li>
			<li>Make any desired changes.</li>
			<li>Click "Save".</li>
		</ol>
	</section>
	<section>
		<h2>Locking a Category</h2>
		<p>When a category is locked, no new threads may be created within that category.</p>
		<ol>
			<li>From the main forum page, find the desired category.</li>
			<li>Click the edit button, typically a small <span class="icon-edit">pencil</span> icon.</li>
			<li>Check the box labeled "Lock Category".</li>
			<li>Click "Save".</li>
		</ol>
	</section>
	<section>
		<h2>Deleting a Category</h2>
		<p>When a category is removed, all content within that category will no longer be available. If it is wished that the threads within are preserved, they must be re-assigned to a new category before the category is deleted.</p>
		<ol>
			<li>From the main forum page, find the desired category.</li>
			<li>Click the delete button, typically a small <span class="icon-delete">trash can</span> icon.</li>
			<li>You will be asked to confirm deletion.</li>
			<li>Click "Yes".</li>
		</ol>
	</section>
<?php } ?>
</article>