<?php
/**
 * HUBzero CMS
 *
 * Copyright 2005-2015 HUBzero Foundation, LLC.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 *
 * HUBzero is a registered trademark of Purdue University.
 *
 * @package   hubzero-cms
 * @author    Christopher Smoak <csmoak@purdue.edu>
 * @copyright Copyright 2005-2015 HUBzero Foundation, LLC.
 * @license   http://opensource.org/licenses/MIT MIT
 */

// No direct access.
defined('_HZEXEC_') or die();
?>
<article>
	<h1>Forum FAQs</h1>

	<ol>
		<li>
			<a href="#lockedcategories">What does a locked category mean?</a>
		</li>
		<li>
			<a href="#lockedthreads">What does a locked thread mean?</a>
		</li>
		<li>
			<a href="#stickythreads">What is a sticky thread?</a>
		</li>
	</ol>

	<hr />

	<section id="lockedcategories">
		<h3>What does a locked category mean?</h3>
		<p>When a category is locked, no new threads may be created within that category.</p>
	</section>

	<section id="lockedthreads">
		<h3>What does a locked thread mean?</h3>
		<p>When a thread is locked, no new posts may be created within that thread. Essentially, the thread becomes "Read only".</p>
	</section>

	<section id="stickythreads">
		<h3>What is a sticky thread?</h3>
		<p>When a thread is marked as <strong>sticky</strong>, it will be sorted to the top of the list of all threads within a category. This is done typically to highlight a thread containing important or oft-sought information.</p>
	</section>
</article>