<?php
/**
 * @package    hubzero-cms
 * @copyright  Copyright 2005-2019 HUBzero Foundation, LLC.
 * @license    http://opensource.org/licenses/MIT MIT
 */

// No direct access.
defined('_HZEXEC_') or die();
?>
<article>
	<h1>Forum FAQs</h1>

	<ol>
		<li>
			<a href="#lockedcategories">What does a locked category mean?</a>
		</li>
		<li>
			<a href="#lockedthreads">What does a locked thread mean?</a>
		</li>
		<li>
			<a href="#stickythreads">What is a sticky thread?</a>
		</li>
	</ol>

	<hr />

	<section id="lockedcategories">
		<h3>What does a locked category mean?</h3>
		<p>When a category is locked, no new threads may be created within that category.</p>
	</section>

	<section id="lockedthreads">
		<h3>What does a locked thread mean?</h3>
		<p>When a thread is locked, no new posts may be created within that thread. Essentially, the thread becomes "Read only".</p>
	</section>

	<section id="stickythreads">
		<h3>What is a sticky thread?</h3>
		<p>When a thread is marked as <strong>sticky</strong>, it will be sorted to the top of the list of all threads within a category. This is done typically to highlight a thread containing important or oft-sought information.</p>
	</section>
</article>