<?php
/**
 * HUBzero CMS
 *
 * Copyright 2005-2011 Purdue University. All rights reserved.
 *
 * This file is part of: The HUBzero(R) Platform for Scientific Collaboration
 *
 * The HUBzero(R) Platform for Scientific Collaboration (HUBzero) is free
 * software: you can redistribute it and/or modify it under the terms of
 * the GNU Lesser General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any
 * later version.
 *
 * HUBzero is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * HUBzero is a registered trademark of Purdue University.
 *
 * @package   hubzero-cms
 * @author    Christopher Smoak <csmoak@purdue.edu>
 * @copyright Copyright 2005-2011 Purdue University. All rights reserved.
 * @license   http://www.gnu.org/licenses/lgpl-3.0.html LGPLv3
 */

// Check to ensure this file is included in Joomla!
defined('_JEXEC') or die('Restricted access');
?>
<article>
	<h1>Forum FAQs</h1>

	<ol>
		<li>
			<a href="#lockedcategories">What does a locked category mean?</a>
		</li>
		<li>
			<a href="#lockedthreads">What does a locked thread mean?</a>
		</li>
		<li>
			<a href="#stickythreads">What is a sticky thread?</a>
		</li>
	</ol>

	<hr />

	<section id="lockedcategories">
		<h3>What does a locked category mean?</h3>
		<p>When a category is locked, no new threads may be created within that category.</p>
	</section>

	<section id="lockedthreads">
		<h3>What does a locked thread mean?</h3>
		<p>When a thread is locked, no new posts may be created within that thread. Essentially, the thread becomes "Read only".</p>
	</section>

	<section id="stickythreads">
		<h3>What is a sticky thread?</h3>
		<p>When a thread is marked as <strong>sticky</strong>, it will be sorted to the top of the list of all threads within a category. This is done typically to highlight a thread containing important or oft-sought information.</p>
	</section>
</article>