<?php
/**
 * HUBzero CMS
 *
 * Copyright 2005-2015 HUBzero Foundation, LLC.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 *
 * HUBzero is a registered trademark of Purdue University.
 *
 * @package   hubzero-cms
 * @author    Shawn Rice <zooley@purdue.edu>
 * @copyright Copyright 2005-2015 HUBzero Foundation, LLC.
 * @license   http://opensource.org/licenses/MIT MIT
 */

// No direct access.
defined('_HZEXEC_') or die();
?>
<article>
	<h1>Forum Help</h1>

	<p>A forum, or message board, is an online discussion area where people can hold conversations in the form of posted messages.</p>
	<p>Forums have a specific set of jargon associated with them; e.g. a single conversation is called a "thread" or discussion.</p>
	<p>A discussion forum is hierarchical or tree-like in structure: a forum can contain a number of <strong>sections</strong>, each of which may have several categories. Within a forum's <strong>category</strong>, each new discussion started is called a <strong>thread</strong>, and can be replied to by as many people as so wish.</p>

	<nav>
		<ul>
			<li>
				<a href="<?php echo Route::url('index.php?option=com_help&component=forum&page=sections'); ?>">Sections</a>
			</li>
			<li>
				<a href="<?php echo Route::url('index.php?option=com_help&component=forum&page=categories'); ?>">Categories</a>
			</li>
			<li>
				<a href="<?php echo Route::url('index.php?option=com_help&component=forum&page=threads'); ?>">Threads</a>
			</li>
			<?php /*<li>
				<a href="<?php echo Route::url('index.php?option=com_help&component=forum&page=guidelines'); ?>">Guidelines &amp; Tips</a>
			</li> */ ?>
			<li>
				<a href="<?php echo Route::url('index.php?option=com_help&component=forum&page=faqs'); ?>">FAQs</a>
			</li>
		</ul>
	</nav>
</article>