<?php
/**
 * @package    hubzero-cms
 * @copyright  Copyright 2005-2019 HUBzero Foundation, LLC.
 * @license    http://opensource.org/licenses/MIT MIT
 */

// No direct access.
defined('_HZEXEC_') or die();
?>
<article>
	<h1>Forum Sections</h1>

	<p>Sections are a way to organize or group related categories (topics). By default, sections are sequenced alphabetically by title.</p>

	<?php /*if (User::authorise('core.admin', 'com_forum.component') || User::authorise('core.manage', 'com_forum.component')) { ?>
		<section>
			<h2>Creating a Section</h2>
			<p>--</p>
		</section>

		<section>
			<h2>Organizing Sections</h2>
			<p>--</p>
		</section>
	<?php }*/ ?>
</article>