<?php
/**
 * @package    hubzero-cms
 * @copyright  Copyright 2005-2019 HUBzero Foundation, LLC.
 * @license    http://opensource.org/licenses/MIT MIT
 */

// No direct access.
defined('_HZEXEC_') or die();
?>
<article>
	<h1>Forum Threads</h1>

	<p>A thread (sometimes called a discussion) is a collection of posts displayed from oldest to latest. A thread is defined by a title, an additional description that may summarize the intended discussion, and an opening or original post (common abbreviation OP, which can also mean original poster), which opens whatever dialogue or makes whatever announcement the poster wished. A thread can contain any number of posts, including multiple posts from the same members, even if they are one after the other.</p>

	<hr />
	<section>
		<h2>Creating a Thread</h2>
		<p>--</p>
	</section>
	<section>
		<h2>Making a Thread Sticky</h2>
		<p>Threads that are important are sticky (or "pinned"). A sticky thread will always have priority in listings. A sticky thread is typically indicated by a <span class="icon-asterisk">asterisk</span> or star icon.</p>
	</section>
	<section>
		<h2>Deleting a Thread</h2>
		<p>--.</p>
	</section>
</article>