<article>
	<h1><span>Feedback Manager: Quotes</span></h1>

	<ul class="nav">
		<li><a href="#overview">Overview</a></li>
		<li><a href="#column-headers">Column Headers</a></li>
		<li><a href="#toolbar">Toolbar</a></li>
		<li><a href="#list-filters">List Filters</a></li>
	</ul>

	<section id="overview">
		<h2><span>Overview</span></h2>

		<p>Here you will a list of submitted feedback.</p>
	</section>
	<section id="column-headers">
		<h2><span>Column Headers</span></h2>

		<p>Click on the column heading to sort the list by that column's value. The list will be sorted in order by that column and a sort icon will show next to the column name. Click a second time to reverse the sort to high-to-low. The sort icon will change to high-to-low.</p>

		<dl>
			<dt>ID</dt>
			<dd>This is a unique identification number for this item assigned automatically by the system. It is used to identify the item internally and cannot be changed. When creating a new item, this field is 0 until the entry is saved, at which point a new ID is assigned to it.</dd>

			<dt>Checkbox</dt>
			<dd>Check this box to select one or more items. To select all items, check the box in the column heading. After one or more boxes are checked, click a toolbar button to take an action on the selected item or items. Many toolbar actions, such as Publish and Unpublish, can work with multiple items. Others, such as Edit, only work on one item at a time. If multiple items are checked and you press Edit, the first item will be opened for editing.</dd>

			<dt>Submitted</dt>
			<dd>The date the feedback was submitted.</dd>

			<dt>Author</dt>
			<dd>The author of the feedback. You can open the entry for editing by clicking on the name.</dd>

			<dt>Organization</dt>
			<dd>The organization of the author.</dd>

			<dt>Quote</dt>
			<dd>The first sentence or so of the submitted feedback. You can open the entry for editing by clicking on the quote.</dd>

			<dt>Notable Quotes</dt>
			<dd>This indicates if the entry has been selected to be a "notable quote". Notable Quotes can be used by modules to appear in quote lists, be randomly selected for display, etc.</dd>

			<dt>OK to Publish</dt>
			<dd>An indicator that the author gave permission to make the quote publicly viewable.</dd>
		</dl>
	</section>
	<section id="toolbar">
		<h2><span>Toolbar</span></h2>
		<p>At the top right you will see the toolbar.</p>
		<p>The functions are:</p>
		<dl>
			<dt>Options</dt>
			<dd>Opens the Options window where settings such as default parameters or permissions can be edited.</dd>

			<dt>New</dt>
			<dd>Opens the editing screen to create a new question.</dd>

			<dt>Edit</dt>
			<dd>Opens the editing screen for the selected item. If more than one item is selected (where applicable), only the first item will be opened. The editing screen can also be opened by clicking on the Title of the item.</dd>

			<dt>Delete</dt>
			<dd>Permanently deletes selected items and their associated content.</dd>

			<dt>Help</dt>
			<dd>Opens this help screen.</dd>
		</dl>
	</section>
	<section id="list-filters">
		<h2><span>List Filters</span></h2>

		<dl>
			<dt>Search</dt>
			<dd>Above the column headers is a search box for filtering results by a keyword or phrase.</dd>
		</dl>

		<p>Click Clear to clear the Filter field and restore the list to its unfiltered state.</p>

		<h3>Page Controls</h3>
		<p>When the number of items is more than one page, you will see a page control bar as shown below.</p>

		<dl>
			<dt>Display #</dt>
			<dd>Select the number of items to show on one page.</dd>
			<dt>Start</dt>
			<dd>Click to go to the first page.</dd>
			<dt>Prev</dt>
			<dd>Click to go to the previous page.</dd>
			<dt>Page numbers</dt>
			<dd>Click to go to the desired page.</dd>
			<dt>Next</dt>
			<dd>Click to go to the next page.</dd>
			<dt>End</dt>
			<dd>Click to go to the last page.</dd>
		</dl>
	</section>
</article>