<article>
	<h1><span>Feedback Manager: Edit Quote</span></h1>

	<ul class="nav">
		<li><a href="#overview">Overview</a></li>
		<li><a href="#toolbar">Toolbar</a></li>
		<li><a href="#details">Details</a></li>
		<li><a href="#picture">Picture</a></li>
	</ul>

	<section id="overview">
		<h2><span>Overview</span></h2>

		<p>This is the edit/creation form for user-submitted feedback.</p>
	</section>
	<section id="toolbar">
		<h2><span>Toolbar</span></h2>
		<p>At the top right you will see the toolbar.</p>
		<p>The functions are:</p>
		<dl>
			<dt>Save</dt>
			<dd>Save changes and return to the edit form.</dd>

			<dt>Save &amp; Close</dt>
			<dd>Save changes and return to the listing of entries.</dd>

			<dt>Cancel</dt>
			<dd>Discard any changes made and return to the listing of entries.</dd>

			<dt>Help</dt>
			<dd>Opens this help screen.</dd>
		</dl>
	</section>
	<section id="details">
		<h2><span>Details</span></h2>

		<dl>
			<dt>Select for Notable Quotes page</dt>
			<dd>This indicates if the entry has been selected to be a "notable quote". Notable Quotes can be used by modules to appear in quote lists, be randomly selected for display, etc.</dd>

			<dt>Author full name</dt>
			<dd>The author of the feedback. You can open the entry for editing by clicking on the name.</dd>

			<dt>Organization</dt>
			<dd>The organization of the author.</dd>

			<dt>User ID</dt>
			<dd>The ID of the author, if they have an account.</dd>

			<dt>Author consents</dt>
			<dd>
				<dl>
					<dt>Author consent to publish quote</dt>
					<dd>An indicator that the author gave permission to make the quote publicly viewable.</dd>

					<dt>Author consent to be contacted for further info regarding this quote</dt>
					<dd>An indicator that the author gave permission to be contacted for future quotes, interviews, etc.</dd>
				</dl>
			</dd>

			<dt>Short Quote</dt>
			<dd>This is a currated, trimmed version of the feedback. Typically, this will be one or two lines selected from the body of the full quote.</dd>

			<dt>Mini Quote</dt>
			<dd>Like the Short Quote, this is a currated, trimmed version fo the feedback. However, this is meant to be a short, one line/sentence.</dd>

			<dt>Full Quote</dt>
			<dd>The submitted feedback.</dd>

			<dt>Quote Submitted</dt>
			<dd>The date the feedback was submitted.</dd>

			<dt>Editor notes</dt>
			<dd>Any notes concerning the author or feedback an editor may wish to make. This information is displayed to <strong>administrators only</strong>.</dd>
		</dl>
	</section>
	<section id="picture">
		<h2><span>Picture</span></h2>

		<p>This is an area for any pictures, such as author photo, associated with this quote.</p>
	</section>
</article>