<?php

require_once 'lib/data/tsunami/om/BaseTsunamiProject.php';
require_once 'lib/data/Role.php';


/**
 * Skeleton subclass for representing a row from the 'TsunamiProject' table.
 *
 *
 *
 * This class was autogenerated by Propel on:
 *
 * Sat Feb  9 00:03:16 2008
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.data.tsunami
 */
class TsunamiProject extends BaseTsunamiProject {

  function isPublic() {
    return $this->getPublicData();
  }

  function getTeamLeader() { //returns a person
    // Kevin, we need to update this Role Name in database
    $role = RolePeer::findByNameEntityType("Team Leader", DomainEntityType::ENTITY_TYPE_TSUNAMI_PROJECT); //this is the Team Leader ID
    if(is_null($role)) return null;

    $leader = PersonEntityRolePeer::findByEntityRole($this,$role);
    if (is_null($leader)) return null;

    return $leader->getPerson();
  }

  function getTeam() { //returns an array of 0 or more people, excluding the team leader
    $team = array();
    // Kevin, we need to update this Role Name in database
    $role = RolePeer::findByNameEntityType("Collaborator", DomainEntityType::ENTITY_TYPE_TSUNAMI_PROJECT);
    if(is_null($role)) return array();

    $people = PersonEntityRolePeer::findByEntityRole($this,$role);

    foreach($people as $per) {
      $team[] = $per->getPerson();
    }
    return($team);
  }
} // TsunamiProject
