<?php

  // include base peer class
  require_once 'lib/data/tsunami/om/BaseTsunamiSiteDocRelationshipPeer.php';

  // include object class
  include_once 'lib/data/tsunami/TsunamiSiteDocRelationship.php';


/**
 * Skeleton subclass for performing query and update operations on the 'TsunamiSiteDocRelationship' table.
 *
 *
 *
 * This class was autogenerated by Propel on:
 *
 * Sat Feb  9 00:03:17 2008
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.data.tsunami
 */
class TsunamiSiteDocRelationshipPeer extends BaseTsunamiSiteDocRelationshipPeer {

  /**
   * Find a TsunamiSiteDocRelationship object based on its ID
   *
   * @param int $id
   * @return TsunamiSiteDocRelationship
   */
  public static function find($id) {
    return self::retrieveByPK($id);
  }

  /**
   * Find all TsunamiSiteDocRelationships
   *
   * @return array <TsunamiSiteDocRelationship>
   */
  public static function findAll() {
    return self::doSelect(new Criteria());
  }


  /**
   * Get TsunamiSiteId by TsunamiDocLibId
   *
   * @param int $tsunami_doc_lib_id
   * @return int TsunamiSiteId
   */
  public static function getTsunamiDocSiteId($tsunami_doc_lib_id = null) {
    if (is_null($tsunami_doc_lib_id)) return null;

    $c = new Criteria();
    $c->add(self::TSUNAMI_DOC_LIB_ID, $tsunami_doc_lib_id);
    $obj = self::doSelectOne($c);

    if(is_null($obj)) return null;
    return $obj->getTsunamiSiteId();
  }

} // TsunamiSiteDocRelationshipPeer
