<?php

  // include base peer class
  require_once 'lib/data/tsunami/om/BaseTsunamiProjectPeer.php';

  // include object class
  include_once 'lib/data/tsunami/TsunamiProject.php';


/**
 * Skeleton subclass for performing query and update operations on the 'TsunamiProject' table.
 *
 *
 *
 * This class was autogenerated by Propel on:
 *
 * Sat Feb  9 00:03:16 2008
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.data.tsunami
 */
class TsunamiProjectPeer extends BaseTsunamiProjectPeer {

  /**
   * Find a TsunamiProject object based on its ID
   *
   * @param int $id
   * @return TsunamiProject
   */
  public static function find($id) {
    return self::retrieveByPK($id);
  }

  /**
   * Find all TsunamiProjects
   *
   * @return array <TsunamiProject>
   */
  public static function findAll() {
    return self::doSelect(new Criteria());
  }


  public static function findPublicProject() {
    $c = new Criteria();
    $c->add(self::PUBLIC_DATA, 1);

    return self::doSelect($c);
  }
} // TsunamiProjectPeer
