<article>
	<h1><span>Application</span></h1>

	<ul class="nav">
		<li><a href="#overview">Overview</a></li>
		<li><a href="#toolbar">Toolbar</a></li>
		<li><a href="#details">Details</a></li>
		<li><a href="#publishing">Publishing</a></li>
	</ul>

	<section id="overview">
		<h2><span>Overview</span></h2>

		<p>The edit/creation form for a blog entry.</p>
	</section>
	<section id="toolbar">
		<h2><span>Toolbar</span></h2>
		<p>At the top right you will see the toolbar.</p>
		<p>The functions are:</p>
		<dl>
			<dt>Save</dt>
			<dd>Save changes and return to the edit form.</dd>

			<dt>Save &amp; Close</dt>
			<dd>Save changes and return to the listing of entries.</dd>

			<dt>Cancel</dt>
			<dd>Discard any changes made and return to the listing of entries.</dd>

			<dt>Help</dt>
			<dd>Opens this help screen.</dd>
		</dl>
	</section>
	<section id="publishing">
		<h2><span>Accept / Reject</span></h2>

		<p>When viewing the summary of an application, you may accept or reject the application. If rejecting, this will place the application back into a "draft" status where the submitter may edit and re-submit for consideration. If desired, notes to the submitter may be added at the time of rejection.</p>
	</section>
</article>