<article>
	<h1>Extension Manager: Manage</h1>

	<section>
		<h2> <span class="mw-headline" id="Overview">Overview</span></h2>
		<p>This screen is accessed from the back-end administrator panel. It is used to enable/disable/uninstall extensions that are installed in your installation. Some examples of extensions are plug-ins, components, and site templates.</p>
	</section>
	<section>
		<h2> <span class="mw-headline" id="How_to_Access">How to Access</span></h2>
		<p>Select <b>Extensions → Extension Manager</b> from the drop-down menu of the <i><b>Administrator Panel</b></i>. Then select the <b>Manage</b> menu item in the <i><b>Extension manager</b></i> screen that appears.</p>
	</section>
	<section>
		<h2> <span class="mw-headline" id="Description">Description</span></h2>
		<p>This screen allows you to Enable/Disable extensions. To Enable/Disable an extension is the same as to Publish/Unpublish it. In addition you can uninstall extensions from this screen as well.</p>
	</section>
	<section>
		<h2> <span class="mw-headline" id="Column_Headers">Column Headers</span></h2>
		<p>Click on the column heading to sort the list by that column's value. The list will be sorted in order by that column and a sort icon will show next to the column name, as shown below. Click a second time to reverse the sort to high-to-low. The sort icon will change to high-to-low, as shown below.</p>
		<ul>
			<li><b>Checkbox</b>. Check this box to select one or more items. To select all items, check the box in the column heading. After one or more boxes are checked, click a toolbar button to take an action on the selected item or items. Many toolbar actions, such as Publish and Unpublish, can work with multiple items. Others, such as Edit, only work on one item at a time. If multiple items are checked and you press Edit, the first item will be opened for editing.</li>
			<li><b>Name.</b> The name of the extension.</li>
			<li><b>Location.</b> Whether the extension is a public front-end or an administrator back-end extension. 'Site' means it is a public front-end extension. 'Administrator' means it is an administrator back-end extension.</li>
			<li><b>Status.</b> (Enable/Disable) The published status of the extension.</li>
			<li><b>Extension Type.</b> The extension type. Some examples of extension types are module, plug-in, template, or language.</li>
			<li><b>Version.</b> The version number of the Extension.</li>
			<li><b>Date.</b> The date this extension was released.</li>
			<li><b>Author.</b> The author of this extension.</li>
			<li><b>Folder.</b> If the extension is a plug-in, the subdirectory of your installation's /plugins directory where the extension is located.</li>
			<li><b>ID</b>. This is a unique identification number for this item assigned automatically by the CMS. It is used to identify the item internally, and you cannot change this number. When creating a new item, this field displays 0 until you save the new entry, at which point a new ID is assigned to it.</li>
			<li><b>Display #.</b> (Use Global/Hide/Show) Whether to hide or show the Display # control that allows the user to select the number of items to show in the list. An example is shown below. If there are more items than this number, you can use the page navigation buttons (Start, Prev, Next, End, and page numbers) to navigate between pages. Note that if you have a large number of items, it may be helpful to use the Filter options, located above the column headings, to limit which items display.</li>
		</ul>
	</section>
	<section>
		<h2> <span class="mw-headline" id="List_Filters">List Filters</span></h2>
		<p>The list of extensions which appears on this screen may be very large. You can use one of the available filters or any combination of them to limit the number of extensions displayed to just the extensions which match your filter parameters.</p>
		<ul>
			<li>
				<b>Filter by Partial Title or ID. </b> In the upper left is a filter field and two buttons, as shown below.
				<ul>
					<li> To filter by partial title, enter part of the title and click Search.</li>
					<li> To filter by ID number, enter "id:xx", where "xx" is the ID number (for example, "id:9").</li>
				</ul>
			</li>
		</ul>
		<dl>
			<dd>Click Clear to clear the Filter field and restore the list to its unfiltered state.</dd>
		</dl>
		<p><b>Filter by Extension Location, Status, Type and Folder</b></p>
		<ul>
			<li> <b>Select Location.</b> Select an extension location from the drop-down list box of available clients. There are two locations - Site and Administrator. Site locations are extensions which are designed for use in areas outside of the administrator interface. Administrator extensions are for the back-end administrative functions of your installation. Usually you would only directly interact with these extensions through the administrator web interface.</li>
			<li> <b>Select status.</b> Select the extension's status. This is published, unpublished or protected (a default extension that may not be uninstalled or unpublished)</li>
			<li> <b>Select type.</b> Select the extension type from the drop-down list box of available types.</li>
			<li> <b>Select folder.</b> Select a plug-in folder from the drop-down list box of available folders. There is a separate folder for each type of plug-in defined in your installation.</li>
		</ul>
	</section>
	<section>
		<h2> <span class="mw-headline" id="Toolbar">Toolbar</span></h2>
		<p>At the top right you will see the toolbar. The functions are:</p>
		<ul>
			<li><b>Enable</b>. Makes the selected extension(s) available for use on your website.</li>
			<li><b>Disable</b>. Makes the selected extension(s) unavailable for use on your website.</li>
			<li><b>Refresh cache</b>. Refresh the information displayed for the selected extension(s).</li>
			<li><b>Uninstall</b>. Uninstall the selected extension(s).</li>
			<li><b>Options</b>. Opens the Options window where settings such as default parameters or permissions can be edited.</li>
			<li><b>Help</b>. Opens this help screen.</li>
		</ul>
	</section>
	<section>
		<h2> <span class="mw-headline" id="Links_to_Other_Screens">Links to Other Screens</span></h2>
		<p>At the top left, you will see the following five links:
		</p>
		<ul>
			<li><b>Install.</b> Links to the <a href="<?php echo Route::url('index.php?option=com_help&view=help&keyref=Help25:Extensions_Extension_Manager_Install'); ?>" title="Help25:Extensions Extension Manager Install">Install Screen</a>.</li>
			<li><b>Update.</b> Links to the <a href="<?php echo Route::url('index.php?option=com_help&view=help&keyref=Help25:Extensions_Extension_Manager_Update'); ?>" title="Help25:Extensions Extension Manager Update">Update Screen</a>.</li>
			<li><b>Manage.</b> Links to the <strong class="selflink">Manage Screen</strong>.</li>
			<li><b>Discover.</b> Links to the <a href="<?php echo Route::url('index.php?option=com_help&view=help&keyref=Help25:Extensions_Extension_Manager_Discover'); ?>" title="Help25:Extensions Extension Manager Discover">Discover Screen</a>.</li>
			<li><b>Database.</b> Links to the <a href="<?php echo Route::url('index.php?option=com_help&view=help&keyref=Help25:Extensions_Extension_Manager_Database'); ?>" title="Help25:Extensions Extension Manager Database">Database Screen</a>.</li>
			<li><b>Warnings.</b> Links to the <a href="<?php echo Route::url('index.php?option=com_help&view=help&keyref=Help25:Extensions_Extension_Manager_Warnings'); ?>" title="Help25:Extensions Extension Manager Warnings">Warnings Screen</a>.</li>
			<li><b>Install Langauges.</b> Links to the <a href="<?php echo Route::url('index.php?option=com_help&view=help&keyref=Help25:Extensions_Extension_Manager_languages'); ?>" title="Help25:Extensions Extension Manager languages">Languages Screen</a>.</li>
		</ul>
	</section>
	<section>
		<h2> <span class="mw-headline" id="Quick_Tips">Quick Tips</span></h2>
		<ul>
			<li> Throughout the administrator interface you will see the terms "Publish" and "Unpublish". <i>Publish</i> means the same thing as <i>Enable</i> or <i>Activate</i>. <i>Unpublish</i> means the same thing as <i>Disable</i> or <i>Deactivate</i>. You may see the terms used interchangeably in extension screens and help documentation you find online.</li>
			<li> Some information such as <i>Date</i> or <i>Author</i> may not be displayed for an extension. This is not a problem. It merely means the information was not specified by the extension developer in the extension's installation package.</li>
		</ul>
	</section>
</article>