<?php

require_once 'lib/data/tsunami/om/BaseTsunamiSocialScienceData.php';


/**
 * Skeleton subclass for representing a row from the 'TsunamiSocialScienceData' table.
 *
 * 
 *
 * This class was autogenerated by Propel on:
 *
 * Sat Feb  9 00:03:17 2008
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.data.tsunami
 */
class TsunamiSocialScienceData extends BaseTsunamiSocialScienceData {

} // TsunamiSocialScienceData
