<?php

require_once 'lib/data/tsunami/om/BaseTsunamiSite.php';


/**
 * Skeleton subclass for representing a row from the 'TsunamiSite' table.
 *
 * 
 *
 * This class was autogenerated by Propel on:
 *
 * Sat Feb  9 00:03:16 2008
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.data.tsunami
 */
class TsunamiSite extends BaseTsunamiSite {

} // TsunamiSite
