<?php
/**
 * HUBzero CMS
 *
 * Copyright 2005-2011 Purdue University. All rights reserved.
 *
 * This file is part of: The HUBzero(R) Platform for Scientific Collaboration
 *
 * The HUBzero(R) Platform for Scientific Collaboration (HUBzero) is free
 * software: you can redistribute it and/or modify it under the terms of
 * the GNU Lesser General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any
 * later version.
 *
 * HUBzero is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * HUBzero is a registered trademark of Purdue University.
 *
 * @package   hubzero-cms
 * @author    Christopher Smoak <csmoak@purdue.edu>
 * @copyright Copyright 2005-2011 Purdue University. All rights reserved.
 * @license   http://www.gnu.org/licenses/lgpl-3.0.html LGPLv3
 */

// Check to ensure this file is included in Joomla!
defined('_JEXEC') or die('Restricted access');
?>
<h1 class="page-title">Calendar Subscriptions</h1>
<p>Users can subscribe to a group calendar two separate ways:</p>
<ol>
	<li><strong><a href="#download">Download:</a></strong> They can download a group calendar of events and import that into their calendar off the HUB.</li>
	<li><strong><a href="#subscribe">Subscribe:</a></strong> They use a calendar application such as iCal or Outlook to subscribe to the group calendar.</li>
</ol>

<a name="download"></a>
<h2>Downloading the Group Calendar</h2>
<p>To download a group calendar, navigate to a group's calendar tab. If you scroll down, under the calendar of events you should see a box titled "Subscribe", which looks like the image below</p>
<p>
	<img src="/plugins/groups/calendar/help/en-GB/subscribe.png" alt="Subscribe" />
</p>
<p>Here you can pick which of the group calendar's you want to download. After you have made your choices simply click the <u><em>Download</em></u> button. A iCalendar file (.ics) will be downloaded by your browser, which you can then import into any calendar application with iCalendar support.</p>
<p>
	<a target="_blank" href="http://en.wikipedia.org/wiki/List_of_applications_with_iCalendar_support">
		Here is a list of applications with support for iCalendar files (.ics) &rarr;
	</a>
</p>

<a name="subscribe"></a>
<h2>Subscribing to the Group Calendar</h2>
<p>Subscribing to a group calendar has 1 major benefit over downloading a group calendar; changes made to the group events on the HUB are reflected in the subscribers calendar.</p>
<p>To subscribe to group calendar follow the same steps described above to download a calendar but instead click the <u><em>Subscribe</em></u> button. This will open the default calendar application on your calendar with a dialog box asking if you would like to subscribe to this calendar. If the groups calendar access setting is restricted to Registered HUB Users or Group Members, you will also be prompted for you HUB login and password.</p>

<a name="faqs"></a>
<h2>Subscription FAQs</h2>
<ul class="unstyled">
	<li><a href="#faqs-google-calendar">Can I subscribe with Google Calendar?</a></li>
</ul>

<a name="faqs-google-calendar"></a>
<h4>1. Can I subscribe with Google Calendar?</h4>
<p>Currently Google Calendar doesn't support private or authenticated calendar subscriptions, which is good for the security of your data, but bad if you like having all you calendars in one place. Only if a group's calendar access setting is set to <u><em>Any HUB Visitor</em></u> will users be able to subscribe with their Google Calendar. This setting can be changed at anytime by any group manager, in the group customize interface.</p>
<p>An alternative for Google Calendar users is that they download and import a group calendar following the steps described above.</p>