<?php
/**
 * HUBzero CMS
 *
 * Copyright 2005-2015 HUBzero Foundation, LLC.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 *
 * HUBzero is a registered trademark of Purdue University.
 *
 * @package   hubzero-cms
 * @author    Christopher Smoak <csmoak@purdue.edu>
 * @copyright Copyright 2005-2015 HUBzero Foundation, LLC.
 * @license   http://opensource.org/licenses/MIT MIT
 */

// No direct access.
defined('_HZEXEC_') or die();
?>
<artcle>
	<h1>Answers Help</h1>

	<section>
		<h2>Discover</h2>
		<p>Browse answered questions to learn what insights others have left or share your knowledge by answering a few questions.</p>

		<h3>Search</h3>
		<p>You can also use the search box on the page to locate questions and answers related to specific words and phrases.</p>
	</section>

	<section>
		<h2>Ask</h2>
		<p>What would you like to know? Ask a question on a topic that's important, so that other people can give you answers.</p>

		<h3>Tags</h3>
		<p>Tags are a way of categorizing questions. By adding tags you help others find your questions and get answers more quickly!</p>

		<h3>Select the best Answer</h3>
		<p>Once your question has been answered, you need pick a best answer. When viewing the list of answers, each one will have a button that says "Accept answer". Click it and you're done!</p>
	</section>

	<section>
		<h2>Answer</h2>
		<p>Share your knowledge, Help others and be an Expert.</p>

		<h3>Tags</h3>
		<p>Use tags to find open questions related to the topic you know about.</p>

		<h3>Search</h3>
		<p>You can also use the search box on the page to locate questions and answers related to specific words and phrases.</p>

		<h3>Best Answer</h3>
		<p>Your answer to a question may be chosen as the best one, giving you <a href="<?php echo Route::url('index.php?option=com_help&component=answers&page=points'); ?>">extra points</a>, and bragging rights!</p>
	</section>

	<ul>
		<li>
			<a href="<?php echo Route::url('index.php?option=com_help&component=answers&page=points'); ?>">Earning points in the Questions &amp; Answers forum</a>
		</li>
	</ul>
</article>