<article>
	<h1><span>Support: ACL</span></h1>
	<section>
		<h2><span>Overview</span></h2>

		<p>
			The ACL (Access Control Layer) works in conjunction with a user login system to allow or deny a user access to support tickets and various information or features of a ticket.
		</p>
	</section>
	<section>
		<h2><span>Adding/Editing</span></h2>

		<p>
			Permissions may be set for individuals or entire groups of users. All members of a group will inherit any permissions set for the group. If a user is a member of multiple groups with <abbr title="Access Control Layer">ACL</abbr> settings, the highest permissions will take affect. Take, for example, the following group settings:
		</p>
		<table summary="ACL settings for two groups">
			<caption>Table 1: ACL</caption>
			<thead>
				<tr>
					<th> </th>
					<th> </th>
					<th class="grouping" colspan="3">Tickets</th>
					<th colspan="2">Comments</th>
					<th class="grouping" colspan="2">Private Comments</th>
				</tr>
				<tr>
					<th>Object</th>
					<th>Model</th>
					<th class="grouping">Read</th>
					<th class="grouping">Update</th>
					<th class="grouping">Delete</th>
					<th>Create</th>
					<th>Read</th>
					<th class="grouping">Create</th>
					<th class="grouping">Read</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<th>dev (111)</th>
					<td>group</td>
					<td class="grouping"><span class="yes">yes</span></td>
					<td class="grouping"><span class="yes">yes</span></td>
					<td class="grouping"><span class="yes">yes</span></td>
					<td><span class="yes">yes</span></td>
					<td><span class="yes">yes</span></td>
					<td class="grouping"><span class="yes">yes</span></td>
					<td class="grouping"><span class="yes">yes</span></td>
				</tr>
				<tr>
					<th>support (222)</th>
					<td>group</td>
					<td class="grouping"><span class="yes">yes</span></td>
					<td class="grouping"><span class="no">no</span></td>
					<td class="grouping"><span class="no">no</span></td>
					<td><span class="yes">yes</span></td>
					<td><span class="yes">yes</span></td>
					<td class="grouping"><span class="no">no</span></td>
					<td class="grouping"><span class="no">no</span></td>
				</tr>
			</tbody>
		</table>
		<p>
			If user "john" is a member of both groups, his permissions will result as follows:
		</p>
		<table summary="Resulting permissions for user john">
			<caption>Table 2: Resulting permissions</caption>
			<thead>
				<tr>
					<th> </th>
					<th> </th>
					<th class="grouping" colspan="3">Tickets</th>
					<th colspan="2">Comments</th>
					<th class="grouping" colspan="2">Private Comments</th>
				</tr>
				<tr>
					<th>Object</th>
					<th>Model</th>
					<th class="grouping">Read</th>
					<th class="grouping">Update</th>
					<th class="grouping">Delete</th>
					<th>Create</th>
					<th>Read</th>
					<th class="grouping">Create</th>
					<th class="grouping">Read</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<th>john (333)</th>
					<td>user</td>
					<td class="grouping"><span class="yes">yes</span></td>
					<td class="grouping"><span class="yes">yes</span></td>
					<td class="grouping"><span class="yes">yes</span></td>
					<td><span class="yes">yes</span></td>
					<td><span class="yes">yes</span></td>
					<td class="grouping"><span class="yes">yes</span></td>
					<td class="grouping"><span class="yes">yes</span></td>
				</tr>
			</tbody>
		</table>
		<p>
			Individual ACL settings take precedence over any other settings. Once again, take the following two groups and their permissions settings. User "john" is a member of both groups. We then add specific permissions settings for "john":
		</p>
		<table summary="ACL settings for two groups and a user">
			<caption>Table 3: ACL</caption>
			<thead>
				<tr>
					<th> </th>
					<th> </th>
					<th class="grouping" colspan="3">Tickets</th>
					<th colspan="2">Comments</th>
					<th class="grouping" colspan="2">Private Comments</th>
				</tr>
				<tr>
					<th>Object</th>
					<th>Model</th>
					<th class="grouping">Read</th>
					<th class="grouping">Update</th>
					<th class="grouping">Delete</th>
					<th>Create</th>
					<th>Read</th>
					<th class="grouping">Create</th>
					<th class="grouping">Read</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<th>dev (111)</th>
					<td>group</td>
					<td class="grouping"><span class="yes">yes</span></td>
					<td class="grouping"><span class="yes">yes</span></td>
					<td class="grouping"><span class="yes">yes</span></td>
					<td><span class="yes">yes</span></td>
					<td><span class="yes">yes</span></td>
					<td class="grouping"><span class="yes">yes</span></td>
					<td class="grouping"><span class="yes">yes</span></td>
				</tr>
				<tr>
					<th>support (222)</th>
					<td>group</td>
					<td class="grouping"><span class="yes">yes</span></td>
					<td class="grouping"><span class="no">no</span></td>
					<td class="grouping"><span class="no">no</span></td>
					<td><span class="yes">yes</span></td>
					<td><span class="yes">yes</span></td>
					<td class="grouping"><span class="no">no</span></td>
					<td class="grouping"><span class="no">no</span></td>
				</tr>
				<tr>
					<th>john (333)</th>
					<td>user</td>
					<td class="grouping"><span class="no">no</span></td>
					<td class="grouping"><span class="no">no</span></td>
					<td class="grouping"><span class="no">no</span></td>
					<td><span class="no">no</span></td>
					<td><span class="no">no</span></td>
					<td class="grouping"><span class="no">no</span></td>
					<td class="grouping"><span class="no">no</span></td>
				</tr>
			</tbody>
		</table>
		<p>
			The ACL in table 3 will result in the following permissions for user "john":
		</p>
		<table summary="Resulting permissions for user john">
			<caption>Table 4: Resulting permissions</caption>
			<thead>
				<tr>
					<th> </th>
					<th> </th>
					<th class="grouping" colspan="3">Tickets</th>
					<th colspan="2">Comments</th>
					<th class="grouping" colspan="2">Private Comments</th>
				</tr>
				<tr>
					<th>Object</th>
					<th>Model</th>
					<th class="grouping">Read</th>
					<th class="grouping">Update</th>
					<th class="grouping">Delete</th>
					<th>Create</th>
					<th>Read</th>
					<th class="grouping">Create</th>
					<th class="grouping">Read</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<th>john (333)</th>
					<td>user</td>
					<td class="grouping"><span class="no">no</span></td>
					<td class="grouping"><span class="no">no</span></td>
					<td class="grouping"><span class="no">no</span></td>
					<td><span class="no">no</span></td>
					<td><span class="no">no</span></td>
					<td class="grouping"><span class="no">no</span></td>
					<td class="grouping"><span class="no">no</span></td>
				</tr>
			</tbody>
		</table>
		<p class="note">
			<strong>Note:</strong> A user will always have read access to tickets they submitted or are assigned to. This will even override any specific ACL settings.
		</p>
	</section>
</article>