<article>
	<h1><span>Tools Manager: Edit Host Type</span></h1>

	<ul class="nav">
		<li><a href="#overview">Overview</a></li>
		<li><a href="#toolbar">Toolbar</a></li>
		<li><a href="#details">Details</a></li>
	</ul>

	<section id="overview">
		<h2><span>Overview</span></h2>

		<p>The edit/creation form for a tool host type.</p>
	</section>
	<section id="toolbar">
		<h2><span>Toolbar</span></h2>
		<p>At the top right you will see the toolbar. The functions are:</p>

		<dl>
			<dt>Save</dt>
			<dd>Save changes and return to the edit form.</dd>

			<dt>Save &amp; Close</dt>
			<dd>Save changes and return to the listing of entries.</dd>

			<dt>Cancel</dt>
			<dd>Discard any changes made and return to the listing of entries.</dd>

			<dt>Help</dt>
			<dd>Opens this help screen.</dd>
		</dl>
	</section>
	<section id="details">
		<h2><span>Details</span></h2>

		<dl>
			<dt>Name</dt>
			<dd>The title of the entry. A required field.</dd>

			<dt>Value</dt>
			<dd>The ... value.</dd>

			<dt>Description</dt>
			<dd>A short description for this entry.</dd>
		</dl>
	</section>
</article>