<article>
	<h1><span>Tools Manager: Sessions</span></h1>

	<ul class="nav">
		<li><a href="#overview">Overview</a></li>
		<li><a href="#column-headers">Column Headers</a></li>
		<li><a href="#toolbar">Toolbar</a></li>
		<li><a href="#sub-menu">Sub-menu Links</a></li>
		<li><a href="#list-filters">List Filters</a></li>
	</ul>

	<section id="overview">
		<h2><span>Overview</span></h2>

		<p>Here you will a list of active tool sessions.</p>
	</section>
	<section id="column-headers">
		<h2><span>Column Headers</span></h2>

		<p>Click on the column heading to sort the list by that column's value. The list will be sorted in order by that column and a sort icon will show next to the column name. Click a second time to reverse the sort to high-to-low. The sort icon will change to high-to-low.</p>

		<dl>
			<dt>Checkbox</dt>
			<dd>Check this box to select one or more items. To select all items, check the box in the column heading. After one or more boxes are checked, click a toolbar button to take an action on the selected item or items. Many toolbar actions, such as Publish and Unpublish, can work with multiple items. Others, such as Edit, only work on one item at a time. If multiple items are checked and you press Edit, the first item will be opened for editing.</dd>

			<dt>Session</dt>
			<dd>A unique identifier for the session.</dd>

			<dt>Owner</dt>
			<dd>Who currently owns the session.</dd>

			<dt>Started</dt>
			<dd>When the session was started.</dd>

			<dt>Last Accessed</dt>
			<dd>When the sessionw as last accessed.</dd>

			<dt>Tool</dt>
			<dd>The tool the session is for.</dd>

			<dt>Exec Host</dt>
			<dd>The execution host for the session.</dd>

			<dt>Stop</dt>
			<dd>Forcefully stop a session.</dd>
		</dl>
	</section>
	<section id="toolbar">
		<h2><span>Toolbar</span></h2>
		<p>At the top right you will see the toolbar. The functions are:</p>
		<dl>
			<dt>Trash</dt>
			<dd>PErmenently stop and remove the session.</dd>

			<dt>Help</dt>
			<dd>Opens this help screen.</dd>
		</dl>
	</section>
	<section id="sub-menu">
		<h2><span>Sub-menu Links</span></h2>
		<p>At the top left, above the filters, you will see sub-menu options. These are links to managing various aspects of the tool environment. The links are:</p>
		<dl>
			<dt>Pipeline</dt>
			<dd>List of registered tools.</dd>
			<dt>Hosts</dt>
			<dd>List tool hosts.</dd>
			<dt>Host Types</dt>
			<dd>List host types.</dd>
			<dt>Zones</dt>
			<dd>List available tool zones.</dd>
			<dt>Sessions</dt>
			<dd>A list of currently active tool sessions.</dd>
		</dl>
	</section>
	<section id="list-filters">
		<h2><span>List Filters</span></h2>

		<h3>Page Controls</h3>
		<p>When the number of items is more than one page, you will see a page control bar as shown below.</p>

		<dl>
			<dt>Display #</dt>
			<dd>Select the number of items to show on one page.</dd>
			<dt>Start</dt>
			<dd>Click to go to the first page.</dd>
			<dt>Prev</dt>
			<dd>Click to go to the previous page.</dd>
			<dt>Page numbers</dt>
			<dd>Click to go to the desired page.</dd>
			<dt>Next</dt>
			<dd>Click to go to the next page.</dd>
			<dt>End</dt>
			<dd>Click to go to the last page.</dd>
		</dl>
	</section>
</article>