<article>
	<h1><span>Tools Manager: Session Zones</span></h1>

	<ul class="nav">
		<li><a href="#overview">Overview</a></li>
		<li><a href="#column-headers">Column Headers</a></li>
		<li><a href="#toolbar">Toolbar</a></li>
		<li><a href="#sub-menu">Sub-menu Links</a></li>
		<li><a href="#list-filters">List Filters</a></li>
	</ul>

	<section id="overview">
		<h2><span>Overview</span></h2>

		<p>Here you will a list of tools and their current installed status.</p>
	</section>
	<section id="column-headers">
		<h2><span>Column Headers</span></h2>

		<p>Click on the column heading to sort the list by that column's value. The list will be sorted in order by that column and a sort icon will show next to the column name. Click a second time to reverse the sort to high-to-low. The sort icon will change to high-to-low.</p>

		<dl>
			<dt>ID</dt>
			<dd>This is a unique identification number for this item assigned automatically by the system. It is used to identify the item internally and cannot be changed. When creating a new item, this field is 0 until the entry is saved, at which point a new ID is assigned to it.</dd>

			<dt>Zone</dt>
			<dd>The name of the item. This entry is required. You can open the item for editing by clicking on the Zone.</dd>

			<dt>Type</dt>
			<dd>(Local/Remote) The type of zone it is.</dd>

			<dt>State</dt>
			<dd>The published status of the item.</dd>

			<dt>Master</dt>
			<dd>--</dd>

			<dt>SSH Key Path</dt>
			<dd>The path to the SSH key.</dd>

			<dt>Locations</dt>
			<dd>The number of locations associated with the zone.</dd>
		</dl>
	</section>
	<section id="toolbar">
		<h2><span>Toolbar</span></h2>
		<p>At the top right you will see the toolbar. The functions are:</p>
		<dl>
			<dt>New</dt>
			<dd>Opens the editing screen to create a new entry.</dd>

			<dt>Trash</dt>
			<dd>Permanently deletes an entry.</dd>

			<dt>Help</dt>
			<dd>Opens this help screen.</dd>
		</dl>
	</section>
	<section id="sub-menu">
		<h2><span>Sub-menu Links</span></h2>
		<p>At the top left, above the filters, you will see sub-menu options. These are links to managing various aspects of the tool environment. The links are:</p>
		<dl>
			<dt>Pipeline</dt>
			<dd>List of registered tools.</dd>
			<dt>Hosts</dt>
			<dd>List tool hosts.</dd>
			<dt>Host Types</dt>
			<dd>List host types.</dd>
			<dt>Zones</dt>
			<dd>List available tool zones.</dd>
			<dt>Sessions</dt>
			<dd>A list of currently active tool sessions.</dd>
		</dl>
	</section>
	<section id="list-filters">
		<h2><span>List Filters</span></h2>

		<h3>Page Controls</h3>
		<p>When the number of items is more than one page, you will see a page control bar as shown below.</p>

		<dl>
			<dt>Display #</dt>
			<dd>Select the number of items to show on one page.</dd>
			<dt>Start</dt>
			<dd>Click to go to the first page.</dd>
			<dt>Prev</dt>
			<dd>Click to go to the previous page.</dd>
			<dt>Page numbers</dt>
			<dd>Click to go to the desired page.</dd>
			<dt>Next</dt>
			<dd>Click to go to the next page.</dd>
			<dt>End</dt>
			<dd>Click to go to the last page.</dd>
		</dl>
	</section>
</article>