<article>
	<h1><span>Tools Manager: Edit Zone</span></h1>

	<ul class="nav">
		<li><a href="#overview">Overview</a></li>
		<li><a href="#toolbar">Toolbar</a></li>
		<li><a href="#details">Details</a></li>
		<li><a href="#image">Image</a></li>
		<li><a href="#locations">Locations</a></li>
	</ul>

	<section id="overview">
		<h2><span>Overview</span></h2>

		<p>The edit/creation form for a tool version.</p>
	</section>
	<section id="toolbar">
		<h2><span>Toolbar</span></h2>
		<p>At the top right you will see the toolbar. The functions are:</p>
		<dl>
			<dt>Save &amp; Close</dt>
			<dd>Save changes and return to the listing of entries.</dd>

			<dt>Cancel</dt>
			<dd>Discard any changes made and return to the listing of entries.</dd>

			<dt>Help</dt>
			<dd>Opens this help screen.</dd>
		</dl>
	</section>
	<section id="details">
		<h2><span>Details</span></h2>

		<dl>
			<dt>Zone</dt>
			<dd>A unique identifier consisting of letters, numbers, and underscores.</dd>

			<dt>Title</dt>
			<dd>A title for the entry.</dd>

			<dt>Master</dt>
			<dd>--</dd>

			<dt>Type</dt>
			<dd>(Local/Remote) The type of zone it is.</dd>

			<dt>State</dt>
			<dd>The published status of the item.</dd>
		</dl>
	</section>
	<section id="image">
		<h2><span>Image</span></h2>

		<p>This is an image or logo associated with the zone. NEw entries must be saved first before an image can be applied.</p>
	</section>
	<section id="locations">
		<h2><span>Locations</span></h2>

		<p>A list of locations with various levels of granularity associated with a zone.</p>
	</section>
</article>