<?php
/**
 * HUBzero CMS
 *
 * Copyright 2005-2015 HUBzero Foundation, LLC.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 *
 * HUBzero is a registered trademark of Purdue University.
 *
 * @package   hubzero-cms
 * @author    Christopher Smoak <csmoak@purdue.edu>
 * @copyright Copyright 2005-2015 HUBzero Foundation, LLC.
 * @license   http://opensource.org/licenses/MIT MIT
 */

// No direct access.
defined('_HZEXEC_') or die();
?>
<article>
	<h1>How Email Tracking Works</h1>
	<p>When the HUB sends out an email newsletter, we embed a tiny invisible image at the bottom of the email message. This image sometimes called a "Tracker" or "Web Beacon" is unique to each newsletter mailing.</p>
	<p>When the newsletter is opened by a recipient, this "Tracker" is downloaded from our server and we count that as a 'open'.</p>
	<p>We also track your newsletter clicks by directing the links in your newsletters to a central location, where we are able to capture that click, and then redirect the user to their final and desired destination.</p>
	<p>By default is email tracking is set to 'on', but you can choose to turn off newsletter tracking at any time.</p>
	<p><img src="<?php echo rtrim(Request::base(true), '/'); ?>/core/components/com_newsletter/site/help/en-GB/email-tracking.png" alt="" /></p>

	<h2>Can I use my own Tracking Code</h2>
	<p>Yes you can! Just make sure to turn email tracking off on the HUB for that newsletter. Just make sure to insert the other tracking code into the outgoing newsletter. We dont strip any 3rd party tracking code before sending.</p>
</article>