<article>
	<h1><span>Events Manager: Edit Event</span></h1>

	<ul class="nav">
		<li><a href="#overview">Overview</a></li>
		<li><a href="#toolbar">Toolbar</a></li>
		<li><a href="#details">Details</a></li>
		<li><a href="#publishing">Publishing</a></li>
	</ul>

	<section id="description">
		<h2><span>Description</span></h2>
		<p>This is where you can add a new Event or edit an existing Event.</p>
	</section>
	<section id="toolbar">
		<h2><span>Toolbar</span></h2>
		<p>At the top right you will see the toolbar.</p>
		<p>The functions are:</p>
		<dl>
			<dt>Save &amp; Close</dt>
			<dd>Save changes and return to the listing of entries.</dd>

			<dt>Cancel</dt>
			<dd>Discard any changes made and return to the listing of entries.</dd>

			<dt>Help</dt>
			<dd>Opens this help screen.</dd>
		</dl>
	</section>
	<section id="details">
		<h2><span>Event</span></h2>

		<dl>
			<dt>Title</dt>
			<dd>The Title for this item.</dd>

			<dt>Category</dt>
			<dd>A category the event can be found in.</dd>

			<dt>Activity</dt>
			<dd>A long description of the event.</dd>
		</dl>
	</section>
	<section id="publishing">
		<h2><span>Publishing</span></h2>

		<dl>
			<dt>Start Date</dt>
			<dd>The date the event will start. Format is YYYY-MM-DD</dd>

			<dt>Start Time</dt>
			<dd>The time the event will start. Format is HH:mm</dd>

			<dt>End Date</dt>
			<dd>The date the event will end. Format is YYYY-MM-DD</dd>

			<dt>End Time</dt>
			<dd>The time the event will end. Format is HH:mm</dd>
		</dl>
	</section>
</article>