<article>
	<h1><span>Wiki Manager: Pages</span></h1>

	<ul class="nav">
		<li><a href="#overview">Overview</a></li>
		<li><a href="#column-headers">Column Headers</a></li>
		<li><a href="#toolbar">Toolbar</a></li>
		<li><a href="#sub-menu">Sub-menu Links</a></li>
		<li><a href="#list-filters">List Filters</a></li>
	</ul>

	<section id="overview">
		<h2><span>Overview</span></h2>

		<p>Here you will a list of all wiki pages.</p>
	</section>
	<section id="column-headers">
		<h2><span>Column Headers</span></h2>

		<p>Click on the column heading to sort the list by that column's value. The list will be sorted in order by that column and a sort icon will show next to the column name. Click a second time to reverse the sort to high-to-low. The sort icon will change to high-to-low.</p>

		<dl>
			<dt>Checkbox</dt>
			<dd>Check this box to select one or more items. To select all items, check the box in the column heading. After one or more boxes are checked, click a toolbar button to take an action on the selected item or items. Many toolbar actions, such as Publish and Unpublish, can work with multiple items. Others, such as Edit, only work on one item at a time. If multiple items are checked and you press Edit, the first item will be opened for editing.</dd>

			<dt>ID</dt>
			<dd>This is a unique identification number for this item assigned automatically by the system. It is used to identify the item internally and cannot be changed. When creating a new item, this field is 0 until the entry is saved, at which point a new ID is assigned to it.</dd>

			<dt>Title</dt>
			<dd>The name of the item. This entry is required. You can open the item for editing by clicking on the Title.</dd>

			<dt>Mode</dt>
			<dd>(Wiki/Knol/Static) The mode of the page, which can affect how the page is displayed and who can edit the page.</dd>

			<dt>State</dt>
			<dd>(Public/Private/Registered/Trashed) The published status of the item.</dd>

			<dt>Group</dt>
			<dd>The group the wiki page belongs to.</dd>

			<dt>Revisions</dt>
			<dd>The number of revisions the page has. Clicking the number will present a list of entries.</dd>

			<dt>Comments</dt>
			<dd>How many comments have been made on the page. Clicking the number will present a list of entries.</dd>
		</dl>
	</section>
	<section id="toolbar">
		<h2><span>Toolbar</span></h2>
		<p>At the top right you will see the toolbar.</p>
		<p>The functions are:</p>
		<dl>
			<dt>Options</dt>
			<dd>Opens the Options window where settings such as default parameters or permissions can be edited.</dd>

			<dt>New</dt>
			<dd>Opens the editing screen to create a new entry.</dd>

			<dt>Trash</dt>
			<dd>Permanently removes the selected entries and any associated content.</dd>

			<dt>Edit</dt>
			<dd>Opens the editing screen for the selected entry. If more than one entry is selected (where applicable), only the first entry will be opened. The editing screen can also be opened by clicking on the Title of the page.</dd>

			<dt>Help</dt>
			<dd>Opens this help screen.</dd>
		</dl>
	</section>
	<section id="sub-menu">
		<h2><span>Sub-menu Links</span></h2>
		<p>At the top left, above the filters, you will see sub-menu options. The links are:</p>
		<dl>
			<dt>Wiki Pages</dt>
			<dd>Show all wiki pages.</dd>
			<dt>Plugins</dt>
			<dd>Show plugins associated with this component. This is a link to the plugins manager with the type or folder of "wiki" pre-selected.</dd>
		</dl>
	</section>
	<section id="list-filters">
		<h2><span>List Filters</span></h2>
		<dl>
			<dt>Search</dt>
			<dd>Searches titles and pagenames.</dd>
			<dt>Group</dt>
			<dd>Filter the list of results by the group ownership. This is a quick way to view pages only associated with a specific group.</dd>
			<dt>Namespace</dt>
			<dd>Filter the list by the namespace of a page. Namespaces are anything that precedes a colon ":" in a pagename. The wiki comes with a number of namespaces already built-in, the most common of which are "Help:", "Template:", and "Special:".</dd>
		</dl>

		<h3>Page Controls</h3>
		<p>When the number of items is more than one page, you will see a page control bar as shown below.</p>

		<dl>
			<dt>Display #</dt>
			<dd>Select the number of items to show on one page.</dd>
			<dt>Start</dt>
			<dd>Click to go to the first page.</dd>
			<dt>Prev</dt>
			<dd>Click to go to the previous page.</dd>
			<dt>Page numbers</dt>
			<dd>Click to go to the desired page.</dd>
			<dt>Next</dt>
			<dd>Click to go to the next page.</dd>
			<dt>End</dt>
			<dd>Click to go to the last page.</dd>
		</dl>
	</section>
</article>