<article>
	<h1><span>Wiki Manager: Edit Page Revision</span></h1>

	<ul class="nav">
		<li><a href="#overview">Overview</a></li>
		<li><a href="#toolbar">Toolbar</a></li>
		<li><a href="#details">Details</a></li>
		<li><a href="#parameters">Parameters</a></li>
	</ul>

	<section id="description">
		<h2><span>Description</span></h2>
		<p>This is where you can add a new Page Revision or edit an existing Page Revision.</p>
	</section>
	<section id="toolbar">
		<h2><span>Toolbar</span></h2>
		<p>At the top right you will see the toolbar. The functions are:</p>
		<dl>
			<dt>Save &amp; Close</dt>
			<dd>Save changes and return to the listing of entries.</dd>

			<dt>Save</dt>
			<dd>Save changes and return to the edit form.</dd>

			<dt>Cancel</dt>
			<dd>Discard any changes made and return to the listing of entries.</dd>

			<dt>Help</dt>
			<dd>Opens this help screen.</dd>
		</dl>
	</section>
	<section id="details">
		<h2><span>Details</span></h2>

		<dl>
			<dt>Edit Summary</dt>
			<dd>Any notes or summary of changes made from the previous revision.</dd>

			<dt>Content</dt>
			<dd>The primary body of the post. A required field.</dd>
		</dl>
	</section>
	<section id="parameters">
		<h2><span>Parameters</span></h2>

		<dl>
			<dt>Minor edit</dt>
			<dd>An indicator as to if the change was a minor change or not.</dd>

			<dt>State</dt>
			<dd>(Approved/Not Approved/Trashed) The permissions status of the page. Revisions that have not been approved will not be seen when viewing the page. Revisions must be approved in order to take effect. Trashed revisions will not show up in the public wiki.</dd>

			<dt>Created</dt>
			<dd>A timestamp of when the revision was created.</dd>

			<dt>Creator</dt>
			<dd>The user who created the revision.</dd>
		</dl>
	</section>
</article>