<?php
/**
 * @package    hubzero-cms
 * @copyright  Copyright 2005-2019 HUBzero Foundation, LLC.
 * @license    http://opensource.org/licenses/MIT MIT
 */
?>
<article>
	<h1>Support Help</h1>
	<p>Below are links to help articles for the support center.</p>
	<ul>
		<li>
			<a href="<?php echo Route::url('index.php?option=com_help&component=support&page=faqs'); ?>">FAQ's</a>
		</li>
	</ul>
</article>