<?php
/**
 * @package    hubzero-cms
 * @copyright  Copyright 2005-2019 HUBzero Foundation, LLC.
 * @license    http://opensource.org/licenses/MIT MIT
 */
?>

<h1>Member Dashboard</h1>
<p>The Member Dashboard section is the user's landing page after logging in successfully. It has a number of widgets that contain items for easy access, for example the "My Sessions" widget which lists any of your current tool sessions and also shows your storage space usage.</p>
<p><img src="<?php echo rtrim(Request::base(true), '/'); ?>/core/components/com_members/site/help/en-GB/dashboard/dashboard.png" alt="" /></p>

<hr />

<h2>Personalizing Your Dashboard</h2>
<p>You have the option to personalize your Dashboard by adding, removing, or rearranging modules. This customization feature allows you to fit the Dashboard to your personal needs. Once it has been personalized, it will appear how you arranged it at each login.</p>

<h3>To add a module to your Dashboard:</h3>
<p>1. Place your mouse pointer on the Personalize Dashboard button in the upper right hand corner of the screen. This button allows you to add a module.</p>
<p><img src="<?php echo rtrim(Request::base(true), '/'); ?>/core/components/com_members/site/help/en-GB/dashboard/personalize.png" alt="" /></p>


<p>2. A box will appear with a list of modules available. Click the "add" button next to the module you would like added to your Dashboard.</p>
<p><img src="<?php echo rtrim(Request::base(true), '/'); ?>/core/components/com_members/site/help/en-GB/dashboard/addmodule.png" alt="" /></p>


<p>After clicking "add", the new module will appear on your dashboard.</p>
<p><img src="<?php echo rtrim(Request::base(true), '/'); ?>/core/components/com_members/site/help/en-GB/dashboard/newmodule.png" alt="" /></p>

<h3>To remove a module to your Dashboard:</h3>
<p>1. Place your mouse pointer over the upper right hand corner of the box, and click the X that appears.</p>
<p><img src="<?php echo rtrim(Request::base(true), '/'); ?>/core/components/com_members/site/help/en-GB/dashboard/removemodule.png" alt="" /></p>

<p>2. A message will appear asking you to confirm the removal. Click OK to confirm.</p>
<p><img src="<?php echo rtrim(Request::base(true), '/'); ?>/core/components/com_members/site/help/en-GB/dashboard/removemodule_confirm.png" alt="" /></p>


<h3>To rearrange your modules:</h3>
<p>1. Place your mouse on the top of the module you wish to move until a cursor appears.</p>
<p><img src="<?php echo rtrim(Request::base(true), '/'); ?>/core/components/com_members/site/help/en-GB/dashboard/rearrange.png" alt="" /></p>

<p>2. Press and hold down the button on the mouse or other pointing device to grab the module.</p>
<p>3. Drag the module to the desired location, and drop it by releasing the button.</p>
<p><img src="<?php echo rtrim(Request::base(true), '/'); ?>/core/components/com_members/site/help/en-GB/dashboard/rearrange_moved.png" alt="" /></p>
