<?php
/**
 * HUBzero CMS
 *
 * Copyright 2005-2015 HUBzero Foundation, LLC.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 *
 * HUBzero is a registered trademark of Purdue University.
 *
 * @package   hubzero-cms
 * @author    Christopher Smoak <csmoak@purdue.edu>
 * @copyright Copyright 2005-2015 HUBzero Foundation, LLC.
 * @license   http://opensource.org/licenses/MIT MIT
 */

// No direct access.
defined('_HZEXEC_') or die();
?>

<h1>Member Dashboard</h1>
<p>The Member Dashboard section is the user's landing page after logging in successfully. It has a number of widgets that contain items for easy access, for example the "My Sessions" widget which lists any of your current tool sessions and also shows your storage space usage.</p>
<p><img src="<?php echo rtrim(Request::base(true), '/'); ?>/core/components/com_members/site/help/en-GB/dashboard/dashboard.png" alt="" /></p>

<hr />

<h2>Personalizing Your Dashboard</h2>
<p>You have the option to personalize your Dashboard by adding, removing, or rearranging modules. This customization feature allows you to fit the Dashboard to your personal needs. Once it has been personalized, it will appear how you arranged it at each login.</p>

<h3>To add a module to your Dashboard:</h3>
<p>1. Place your mouse pointer on the Personalize Dashboard button in the upper right hand corner of the screen. This button allows you to add a module.</p>
<p><img src="<?php echo rtrim(Request::base(true), '/'); ?>/core/components/com_members/site/help/en-GB/dashboard/personalize.png" alt="" /></p>


<p>2. A box will appear with a list of modules available. Click the "add" button next to the module you would like added to your Dashboard.</p>
<p><img src="<?php echo rtrim(Request::base(true), '/'); ?>/core/components/com_members/site/help/en-GB/dashboard/addmodule.png" alt="" /></p>


<p>After clicking "add", the new module will appear on your dashboard.</p>
<p><img src="<?php echo rtrim(Request::base(true), '/'); ?>/core/components/com_members/site/help/en-GB/dashboard/newmodule.png" alt="" /></p>

<h3>To remove a module to your Dashboard:</h3>
<p>1. Place your mouse pointer over the upper right hand corner of the box, and click the X that appears.</p>
<p><img src="<?php echo rtrim(Request::base(true), '/'); ?>/core/components/com_members/site/help/en-GB/dashboard/removemodule.png" alt="" /></p>

<p>2. A message will appear asking you to confirm the removal. Click OK to confirm.</p>
<p><img src="<?php echo rtrim(Request::base(true), '/'); ?>/core/components/com_members/site/help/en-GB/dashboard/removemodule_confirm.png" alt="" /></p>


<h3>To rearrange your modules:</h3>
<p>1. Place your mouse on the top of the module you wish to move until a cursor appears.</p>
<p><img src="<?php echo rtrim(Request::base(true), '/'); ?>/core/components/com_members/site/help/en-GB/dashboard/rearrange.png" alt="" /></p>

<p>2. Press and hold down the button on the mouse or other pointing device to grab the module.</p>
<p>3. Drag the module to the desired location, and drop it by releasing the button.</p>
<p><img src="<?php echo rtrim(Request::base(true), '/'); ?>/core/components/com_members/site/help/en-GB/dashboard/rearrange_moved.png" alt="" /></p>
