<?php
/**
 * HUBzero CMS
 *
 * Copyright 2005-2015 HUBzero Foundation, LLC.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 *
 * HUBzero is a registered trademark of Purdue University.
 *
 * @package   hubzero-cms
 * @author    Christopher Smoak <csmoak@purdue.edu>
 * @copyright Copyright 2005-2015 HUBzero Foundation, LLC.
 * @license   http://opensource.org/licenses/MIT MIT
 */

// No direct access.
defined('_HZEXEC_') or die();
?>

<h1>Member FAQ's</h1>

<ol>
	<li>
		<a href="#changeusername">How do I change my username?</a>
	</li>
	<li>
		<a href="#changepassword">How do I change my password?</a>
	</li>
	<li>
		<a href="#whyregister">Why do I need to register at all?</a>
	</li>
	<li>
		<a href="#autologoff">Why do I get logged off automatically?</a>
	</li>
	<li>
		<a href="#lostpassword">I've lost my password!</a>
	</li>
	<li>
		<a href="#cantloginanymore">I registered in the past but cannot log in anymore!</a>
	</li>
	<li>
		<a href="#cantlogin">I registered but cannot log in!</a>
	</li>
	<li>
		<a href="#whycantlogin">Why can't I log in?</a>
	</li>
	<li>
		<a href="#racial">Why is Hispanic / Latino not a racial background choice?</a>
	</li>
</ol>

<a name="changeusername"></a>
<h3>How do I change my username?</h3>
<p>Sorry, but login names cannot be changed. If this is poses a serious problem for you, please contact our <a target="_blank" href="/support/ticket/new">support team.</a></p>

<hr />

<?php
$page = "Member Profile";
$link = "/members/myaccount/profile#profile-password";
if (Plugin::isEnabled('members', 'account'))
{
	$page = "Member Account";
	$link = "/members/myaccount/account";
}
?>
<a name="changepassword"></a>
<h3>How do I change my password?</h3>
<p>We have an online form to change your password. You can find that form on your <a target="_blank" href="<?php echo $link; ?>"><?php echo $page; ?> page.</a></p>

<hr />

<a name="whyregister"></a>
<h3>Why do I need to register at all?</h3>
<p>Registration will give you access to additional features not available to guest users, including simulation tools, learning modules, and more. The registration process is completely automatic and it takes just a few minutes.
Our funding agency periodically reviews statistics about the number of users that access our site. By registering and providing some information about yourself, you are helping to justify our existence and continue our funding.</p>

<hr />

<a name="autologoff"></a>
<h3>Why do I get logged off automatically?</h3>
<p>If you do not check the Remember login box when you log in, the site will only keep you logged in for a short time. This prevents misuse of your account by anyone else. To stay logged in, check the box during login. This is not recommended if you access the site from a shared computer--e.g., in a library, internet cafe, university lab, etc.</p>

<hr />

<a name="lostpassword"></a>
<h3>I've lost my password!</h3>
<p>Don't panic! Just click on the <a target="_blank" href="/login/reset">Forgot your Password</a> link on the <a target="_blank" href="/login">login page</a> and enter the e-mail address for your account. A verification token will be sent to you. Once you have received the token, you will be able to choose a new password for your account. If you don't receive an e-mail with the token right away, check your junk mail folder and make sure that it didn't get filed there by mistake. If you no longer have access to the e-mail address that you have on file with us, <a target="_blank" href="<?php echo Route::url('index.php?option=com_support&task=new'); ?>">contact support</a> and we'll help you recover your account.</p>

<hr />

<a name="cantloginanymore"></a>
<h3>I registered in the past but cannot log in anymore!</h3>
<p>You may have entered an incorrect username or password. If you've forgotten either one, you can <a target="_blank" href="/login/remind">recover your username</a> or <a target="_blank" href="/login/reset">recover your password</a>. Just fill out the form, and we'll send your account information to the e-mail address that you registered with your account. If you've changed e-mail addresses and can no longer recover your account information, <a target="_blank" href="/support/ticket/new">contact support</a>, and we'll help you recover your account.</p>

<hr />

<a name="cantlogin"></a>
<h3>I registered but cannot log in!</h3>
<p>If this is a <strong>new account</strong>, you won't be able to log in until you've confirmed your e-mail address. Right after you registered, you should have received an e-mail at the address that you registered with us. This e-mail contains a special link. Click on the link to prove that you can receive e-mail from us. If you did not receive the e-mail, make sure that you did not misspell your e-mail address when you registered with us. Check your junk mail folder to see if the e-mail message wound up there.</p>

<p>If this is an <strong>old account</strong>, check that you are entering the correct username and password. If you've forgotten your password, you can <a target="_blank" href="/login/reset">recover it.</a>
In either case, make sure that <a target="_blank" href="#">cookies are enabled</a> for your browser. If all else fails, <a target="_blank" href="/support/ticket/new">report the problem</a> in our support area.</p>

<hr />

<a name="whycantlogin"></a>
<h3>Why can't I log in?</h3>
<p>Have you registered? You must register in order to log in. If you have registered and you still cannot log in then check and double-check your username and password. Usually this is the problem; if not, <a target="_blank" href="/support/ticket/new">contact support.</a></p>

<hr />

<a name="racial"></a>
<h3>Why is Hispanic / Latino not a racial background choice?</h3>
<p>According to U.S. government guidelines, ethnic heritage and racial background are to be separate, distinct questions and responses. "Ethnic Heritage" defines membership in cultural groups such as Hispanic / Latino, whereas "Racial Background" is based on ancestry and genetic groups. This issue is handled in various ways outside the U.S., and the current standards continue to evolve. We realize this distinction may be somewhat confusing, but we must conform to the latest reporting standards required by the government.
More precise definitions of the various racial background and ethnic heritage choices are as follows:</p>

<h4>Racial Background:</h4>
<ul>
	<li>
		<strong>American Indian or Alaska Native</strong><br />
		Persons having origins in any of the original peoples of North and South America (including Central America), and who maintains cultural identification through tribal affiliation or community recognition.
	</li>
	<li>
		<strong>Asian</strong><br />
		Persons having origins in any of the original peoples of the Far East, Southeast Asia or the Indian subcontinent, including for example, Cambodia, China, India, Japan, Korea, Malaysia, Pakistan, the Philippine Islands, Thailand, and Vietnam.
	</li>
	<li>
		<strong>Black or African American</strong><br />
		Persons having origins in any of the black racial groups of Africa.
	</li>
	<li>
		<strong>Native Hawaiian or Other Pacific Islander</strong><br />
		Persons having origins in any of the original peoples of Hawaii, Guam, Samoa, or other Pacific Islands.
	</li>
	<li>
		<strong>White</strong><br />
		Persons having origins in any of the original peoples of Europe, the Middle East, or North Africa.
	</li>
</ul>

<h4>Ethnic Heritage:</h4>
<ul>
	<li>
		<strong>Hispanic or Latino</strong><br />
		Persons of Cuban, Mexican, Puerto Rican, Central or South American, or other Spanish culture of origin, regardless of race.
	</li>
</ul>