<?php
/**
 * @package    hubzero-cms
 * @copyright  Copyright 2005-2019 HUBzero Foundation, LLC.
 * @license    http://opensource.org/licenses/MIT MIT
 */
?>

<h1>Member Help</h1>

<h3>What is a member?</h3>
<p>A Member Area is each individual user's space within the HUB. Your member profile contains many sections including your dashboard, your profile, a wiki, a blog, and many more. Each member has the ability to use or not use each of these sections how they want. Some of the more important sections will be discussed in more detail below.</p>

<ul>
	<li>
		<a href="<?php echo Route::url('index.php?option=com_help&component=members&page=dashboard'); ?>">Dashboard Help</a>
	</li>
	<li>
		<a href="<?php echo Route::url('index.php?option=com_help&component=members&page=profile'); ?>">Profile Help</a>
	</li>
	<li>
		<a href="<?php echo Route::url('index.php?option=com_help&component=members&page=faqs'); ?>">FAQ's</a>
	</li>
</ul>