<?php
/**
 * HUBzero CMS
 *
 * Copyright 2005-2011 Purdue University. All rights reserved.
 *
 * This file is part of: The HUBzero(R) Platform for Scientific Collaboration
 *
 * The HUBzero(R) Platform for Scientific Collaboration (HUBzero) is free
 * software: you can redistribute it and/or modify it under the terms of
 * the GNU Lesser General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any
 * later version.
 *
 * HUBzero is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * HUBzero is a registered trademark of Purdue University.
 *
 * @package   hubzero-cms
 * @author    Christopher Smoak <csmoak@purdue.edu>
 * @copyright Copyright 2005-2011 Purdue University. All rights reserved.
 * @license   http://www.gnu.org/licenses/lgpl-3.0.html LGPLv3
 */

// Check to ensure this file is included in Joomla!
defined('_JEXEC') or die('Restricted access');
?>

<h1>Member Help</h1>

<h3>What is a member?</h3>
<p>A Member Area is each individual user's space within the HUB. Your member profile contains many sections including your dashboard, your profile, a wiki, a blog, and many more. Each member has the ability to use or not use each of these sections how they want. Some of the more important sections will be discussed in more detail below.</p>

<ul>
	<li>
		<a href="<?php echo Route::url('index.php?option=com_help&component=members&page=dashboard'); ?>">Dashboard Help</a>
	</li>
	<li>
		<a href="<?php echo Route::url('index.php?option=com_help&component=members&page=profile'); ?>">Profile Help</a>
	</li>
	<li>
		<a href="<?php echo Route::url('index.php?option=com_help&component=members&page=faqs'); ?>">FAQ's</a>
	</li>
</ul>