<?php
/**
 * HUBzero CMS
 *
 * Copyright 2005-2015 HUBzero Foundation, LLC.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 *
 * HUBzero is a registered trademark of Purdue University.
 *
 * @package   hubzero-cms
 * @author    Christopher Smoak <csmoak@purdue.edu>
 * @copyright Copyright 2005-2015 HUBzero Foundation, LLC.
 * @license   http://opensource.org/licenses/MIT MIT
 */

// No direct access.
defined('_HZEXEC_') or die();
?>

<h1>Member Help</h1>

<h3>What is a member?</h3>
<p>A Member Area is each individual user's space within the HUB. Your member profile contains many sections including your dashboard, your profile, a wiki, a blog, and many more. Each member has the ability to use or not use each of these sections how they want. Some of the more important sections will be discussed in more detail below.</p>

<ul>
	<li>
		<a href="<?php echo Route::url('index.php?option=com_help&component=members&page=dashboard'); ?>">Dashboard Help</a>
	</li>
	<li>
		<a href="<?php echo Route::url('index.php?option=com_help&component=members&page=profile'); ?>">Profile Help</a>
	</li>
	<li>
		<a href="<?php echo Route::url('index.php?option=com_help&component=members&page=faqs'); ?>">FAQ's</a>
	</li>
</ul>