<?php
/**
 * HUBzero CMS
 *
 * Copyright 2005-2015 HUBzero Foundation, LLC.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 *
 * HUBzero is a registered trademark of Purdue University.
 *
 * @package   hubzero-cms
 * @author    Christopher Smoak <csmoak@purdue.edu>
 * @copyright Copyright 2005-2015 HUBzero Foundation, LLC.
 * @license   http://opensource.org/licenses/MIT MIT
 */

// No direct access.
defined('_HZEXEC_') or die();
?>
<h1>Member Profile</h1>
<p>The Member Profile section contains specific details about the user, ranging from their name to email address, phone number, and personal website.</p>
<p><img src="<?php echo rtrim(Request::base(true), '/'); ?>/core/components/com_members/site/help/en-GB/profile/profile.png" alt="" /></p>

<hr />

<h2>Editing Your Profile</h2>
<p>The Member Profile has a new "edit in place" feature to help users edit their profile easier and faster. To edit your profile, first navigate to your Member Profile. Your should see a screen similar to the picture above. Simply click on the edit link along the right side of any profile field to start editing that field. A hidden pane should slide down and you should see fields to edit that specific field of your profile. This is also where you can set the privacy level for that specific field. When your done editing click the Save Button and your profile will be updated. Clicking the Cancel Button will disregard your changes.</p>
<p><img src="<?php echo rtrim(Request::base(true), '/'); ?>/core/components/com_members/site/help/en-GB/profile/edit.png" alt="" /></p>

<hr />

<h2>Profile Privacy</h2>
<p>All Member accounts on the HUB are created with a default privacy setting of "Public". To edit your Profile Privacy setting, first navigate to your Member Profile. Next to your name you should see a lock icon. A dark colored icon means that your Profile Privacy is set to public. A light colored icon means your Profile Privacy is set to private. You can toggle your Profile Privacy by simply clicking on the lock icon.</p>
<p><img src="<?php echo rtrim(Request::base(true), '/'); ?>/core/components/com_members/site/help/en-GB/profile/privacy.png" alt="" /></p>
<p><em>**Note: You will see the lock icon next to your name on every section of your Member Area, but you must navigate to the Member Profile section within your Member area in order to toggle your privacy setting.</em></p>

<hr />

<h2>Uploading/Updating your Profile Picture</h2>
<p>All Member accounts on the HUB will be created with a default Profile Picture that is a silhouette. To edit your Profile Picture, first navigate to your Member Profile. You should see a semi-transparent black button over your current Profile Picture that says "Change Picture". Clicking that link will bring up a popup to upload a new photo or remove your current one (if its not set to the default silhouette) and should look like the image below.</p>
<p><img src="<?php echo rtrim(Request::base(true), '/'); ?>/core/components/com_members/site/help/en-GB/profile/picture.png" alt="" /></p>

<p>To Upload a new picture click on the black button that says "Upload an Image". Your computer should display a file browser to select an image. After you select an image the file will be automatically uploaded and once complete should be displayed in the preview area within the popup. If you are happy with the newly uploaded image click the "Save Changes" Button and your profile should refresh with the new profile picture set.</p>
<p><em>**Note: You will see your profile picture on every section of your Member area, but you must navigate to the Profile section with your Member area first in order to upload, update, or remove your profile picture.</em></p>