<?php
/**
 * HUBzero CMS
 *
 * Copyright 2005-2015 HUBzero Foundation, LLC.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 *
 * HUBzero is a registered trademark of Purdue University.
 *
 * @package   hubzero-cms
 * @author    Sam Wilson <samwilson@purdue.edu>
 * @copyright Copyright 2005-2015 HUBzero Foundation, LLC.
 * @license   http://opensource.org/licenses/MIT MIT
 */

// No direct access.
defined('_HZEXEC_') or die();
?>

<h1>The Basics</h1>

<a name="why_enroll"></a><h2>Why enroll?</h2>
<p>
	The <?php echo Config::get('sitename'); ?> courses environment offers instructors and students many 
	features to help facilitate the most engaging and interactive learning experience possible.
	And we're adding new features all the time. Many of these feature, like in-depth instructor
	videos, announcements, and more, are available right away, just by browsing the available courses. But, some features
	require an extra level of personalization, and thus require enrollment in the course. Just to give you a taste, some of the 
	exciting featurese available after enrollment include:
</p>

<ul>
	<li>
		<h3>Lecture notes</h3>
		<img src="<?php echo rtrim(Request::base(true), '/'); ?>/core/components/com_courses/site/help/images/notes.png" alt="lecture notes screenshot" />
		<p>These are personalized notes, just for you. And they're time coded!</p>
	</li>
	<li>
		<h3>Detailed progress</h3>
		<img src="<?php echo rtrim(Request::base(true), '/'); ?>/core/components/com_courses/site/help/images/progress.png" alt="detail progress screenshot" />
		<p>This tells you exactly where you are and how you're doing.</p>
	</li>
	<li>
		<h3>Interactive discussion</h3>
		<img src="<?php echo rtrim(Request::base(true), '/'); ?>/core/components/com_courses/site/help/images/discussion.png" alt="discussions screenshot" />
		<p>Ask questions...get help. It's that simple!</p>
	</li>
	<li>
		<h3>Assessments</h3>
		<img src="<?php echo rtrim(Request::base(true), '/'); ?>/core/components/com_courses/site/help/images/assessment.png" alt="assessments screenshot" />
		<p>Make sure you're on track by taking assessments. This may also qualify you for a badge or certificate!</p>
	</li>
	<li>
		<h3>Badges and certificates</h3>
		<img src="<?php echo rtrim(Request::base(true), '/'); ?>/core/components/com_courses/site/help/images/recognitions.png" alt="recognitions screenshot" />
		<p>Show off your work. Now everyone knows how smart you are!</p>
	</li>
</ul>

<p>
	So, why not get started today?
</p>
