<?php
/**
 * @package    hubzero-cms
 * @copyright  Copyright (c) 2005-2020 The Regents of the University of California.
 * @license    http://opensource.org/licenses/MIT MIT
 */

// No direct access.
defined('_HZEXEC_') or die();
?>

<h1>Using the instructor builder</h1>

<h2 id="object">Embedding a Youtube or Kaltura Video into your outline</h2>
<p>
	Embedding a Youtube video into your course outline is simple. From the Youtube video page that you'd like to use, simply 
	switch to the "Share" tab, and choose "Embed".  Then copy and paste the embed code provided. Don't use the old embed code
	style. It should look something like this:
</p>

<pre>
	<?php echo htmlspecialchars('<iframe width="560" height="315" 
	src="http://www.youtube.com/embed/tW1-fSRiAdc?rel=0" 
	frameborder="0" allowfullscreen></iframe>'); ?>
</pre>

<a id="link"></a><h2>Embedding an exteral link into your outline</h2>
<p>
	Embedding an external link into your course outline is simple. Just enter the URL in the text box provided, for example:
</p>

<pre>
	<?php echo htmlspecialchars('https://www.example.com/path/'); ?>
</pre>
