<?php
/**
 * HUBzero CMS
 *
 * Copyright 2005-2015 Purdue University. All rights reserved.
 *
 * This file is part of: The HUBzero(R) Platform for Scientific Collaboration
 *
 * The HUBzero(R) Platform for Scientific Collaboration (HUBzero) is free
 * software: you can redistribute it and/or modify it under the terms of
 * the GNU Lesser General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any
 * later version.
 *
 * HUBzero is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * HUBzero is a registered trademark of Purdue University.
 *
 * @package   hubzero-cms
 * @author    Christopher Smoak <csmoak@purdue.edu>
 * @copyright Copyright 2005-2015 Purdue University. All rights reserved.
 * @license   http://www.gnu.org/licenses/lgpl-3.0.html LGPLv3
 */

// Check to ensure this file is included in Joomla!
defined('_JEXEC') or die('Restricted access');
?>

<h1>Using the instructor builder</h1>

<a name="object"></a><h2>Embedding a Youtube or Kaltura Video into your outline</h2>
<p>
	Embedding a Youtube video into your course outline is simple. From the Youtube video page that you'd like to use, simply 
	switch to the "Share" tab, and choose "Embed".  Then copy and paste the embed code provided. Don't use the old embed code
	style. It should look something like this:
</p>

<pre>
	<?php echo htmlspecialchars('<iframe width="560" height="315" 
	src="http://www.youtube.com/embed/tW1-fSRiAdc?rel=0" 
	frameborder="0" allowfullscreen></iframe>'); ?>
</pre>