<?php
/**
 * @package    hubzero-cms
 * @copyright  Copyright 2005-2019 HUBzero Foundation, LLC.
 * @license    http://opensource.org/licenses/MIT MIT
 */

// No direct access.
defined('_HZEXEC_') or die();
?>

<h1>Courses Help</h1>
<p>
	The HUBzero courses platform offers many features to get you up and running, distributing online course materials and interactive content to a local classroom, or around the world. Though the platform has been designed to be simple and self-serve, there are also plenty of options to keep you busy. Follow a link below to help clear up those options, or dive deeper into the intricacies of the HUBzero courses platform!
</p>
<h2>Students</h2>
<ul>
	<li>
		<a href="<?php echo Route::url('index.php?option=com_help&component=courses&page=basics'); ?>">Why enroll?</a>
	</li>
</ul>
<h2>Instructors:</h2>
<h4>Building a course</h4>
<ul>
	<li>
		<a href="<?php echo Route::url('index.php?option=com_help&component=courses&page=builder'); ?>">Using the interactive builder</a>
	</li>
</ul>