<?php
/**
 * HUBzero CMS
 *
 * Copyright 2005-2015 HUBzero Foundation, LLC.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 *
 * HUBzero is a registered trademark of Purdue University.
 *
 * @package   hubzero-cms
 * @author    Sam Wilson <samwilson@purdue.edu>
 * @copyright Copyright 2005-2015 HUBzero Foundation, LLC.
 * @license   http://opensource.org/licenses/MIT MIT
 */

// No direct access.
defined('_HZEXEC_') or die();
?>

<h1>Courses Help</h1>
<p>
	The HUBzero courses platform offers many features to get you up and running, distributing online course materials and interactive content to a local classroom, or around the world. Though the platform has been designed to be simple and self-serve, there are also plenty of options to keep you busy. Follow a link below to help clear up those options, or dive deeper into the intricacies of the HUBzero courses platform!
</p>
<h2>Students</h2>
<ul>
	<li>
		<a href="<?php echo Route::url('index.php?option=com_help&component=courses&page=basics'); ?>">Why enroll?</a>
	</li>
</ul>
<h2>Instructors:</h2>
<h4>Building a course</h4>
<ul>
	<li>
		<a href="<?php echo Route::url('index.php?option=com_help&component=courses&page=builder'); ?>">Using the interactive builder</a>
	</li>
</ul>