<article>
	<h1>Menu Manager: Edit Menu Item</h1>

	<h2> <span class="mw-headline" id="How_To_Access">How To Access</span></h2>
<p>To create a new Single Article Menu Item:</p>
<ul>
<li>Select <b>Menus → [name of the menu]</b> from the drop-down menu on the back-end of your installation (for example, <b>Menus → Main Menu</b>).</li>
<li>Click <b>New</b> to create a new menu item.</li>
<li>Click the Menu Item Type Select button and then click the Single Article link under Articles.</li>
</ul>
<p>To edit an existing Single Article Menu Item, click its Title in <a href="<?php echo Route::url('index.php?option=com_help&view=help&keyref=Help25:Menus_Menu_Item_Manager'); ?>" title="Help25:Menus Menu Item Manager">Menu Manager: Menu Items</a>.</p>
<h2> <span class="mw-headline" id="Description">Description</span></h2>
<p>Used to show one article in the front end of the site.</p>

<h2> <span class="mw-headline" id="Column_Headers">Column Headers</span></h2>
<h3> <span class="mw-headline" id="Required_Settings">Required Settings</span></h3>
<p>The Single Article Layout has the following required settings:</p>

<ul>
<li><b>Select Article.</b> This field holds the article to be shown in this layout. Press the Select/Change button to open the article selection modal window, as shown below.</li>

<p>This screen is similar to the <a href="<?php echo Route::url('index.php?option=com_help&view=help&keyref=Help25:Content_Article_Manager'); ?>" title="Help25:Content Article Manager">Article Manager</a>. You can use the Filter fields to find the desired article and then click on the article's Title to select it. At that point, the modal window will close and the title will show in the Select Article field.</p>
<h3> <span class="mw-headline" id="Article_Options">Article Options</span></h3>
<p>The Single Article Layout has the following Article Options, as shown below. These options determine how the article will show in the layout.</p>

<p>Note that these options include "Use Global". If this is selected, the setting from the <a href="<?php echo Route::url('index.php?option=com_help&view=help&keyref=Help25:Content_Article_Manager'); ?>" title="Help25:Content Article Manager">Article Manager Options</a> will be used.</p>
<ul>
<li><b>Show Title.</b> (Use Global/Hide/Show). Whether or not to show the Article's Title.</li>
</ul>
<ul>
<li><b>Linked Titles.</b> (Use Global/No/Yes). If the Article's Title is shown, whether to show it as a link to the article.</li>
</ul>
<ul>
<li><b>Show Intro Text.</b> (Hide/Show) Hide or Show an Article's Intro Text when the 'Read more...' link is selected. Intro Text is the part of the Article before a 'Read more...' break. If this parameter is 'Show', when the User selects the 'Read more...' link, the entire article will display, including the Intro Text. If this parameter is 'Hide', when the User selects the 'Read more...' link, only the part of the Article after the 'Read more...' link will display.</li>
</ul>
<ul>
<li><b>Show Category.</b> (Use Global/Hide/Show). Whether or not to show the Article's Category.</li>
</ul>
<ul>
<li><b>Link Category.</b> (Use Global/No/Yes). If the Article's Category is shown, whether to show it as a link to a Category layout (list or blog) for that Category.</li>
</ul>
<ul>
<li><b>Show Parent.</b> (Use Global/Hide/Show). Whether or not to show the Article's Parent Category.</li>
</ul>
<ul>
<li><b>Link Parent.</b> (Use Global/No/Yes). If the Article's Parent Category is shown, whether to show it as a link to a Category layout (list or blog) for that Category.</li>
</ul>
<ul>
<li><b>Show Author.</b> (Use Global/Hide/Show) Whether to show the author of the Article.</li>
</ul>
<ul>
<li><b>Link Author.</b> (Use Global/No/Yes). If the Article's author is shown, whether to show it as a link to a Contact layout for that author. Note that the author must be set up as a Contact in <a href="<?php echo Route::url('index.php?option=com_help&view=help&keyref=Help25:Components_Contacts_Contacts_Edit'); ?>" title="Help25:Components Contacts Contacts Edit">Contact Manager: Edit</a>.</li>
</ul>
<ul>
<li><b>Show Create Date.</b> (Use Global/Hide/Show). Whether or not to show the Article's create date.</li>
</ul>
<ul>
<li><b>Show Modify Date.</b> (Use Global/Hide/Show). Whether or not to show the Article's modify date.</li>
</ul>
<ul>
<li><b>Show Publish Date.</b> (Use Global/Hide/Show). Whether or not to show the Article's start publishing date.</li>
</ul>
<ul>
<li><b>Show Navigation.</b> (Use Global/Hide/Show). Whether or not to show a navigation link (for example, Next or Previous article) when you drill down to the article.</li>
</ul>
<ul>
<li><b>Show Voting.</b> (Use Global/Hide/Show). Whether or not to show the a voting icon for the article.</li>
</ul>
<ul>
<li><b>Show Icons.</b> (Use Global/Hide/Show). If set to Show, Print and Email will use icons instead of text.</li>
</ul>
<ul>
<li><b>Show Print Icon.</b> (Use Global/Hide/Show). Show or Hide the Print Article button.</li>
</ul>
<ul>
<li><b>Show Email Icon.</b> (Use Global/Hide/Show). Show or Hide the Email Article button.</li>
</ul>
<ul>
<li><b>Show Hits.</b> (Use Global/Hide/Show). Show or Hide the number of times the article has been hit (displayed by a user).</li>
</ul>
<ul>
<li><b>Show Unauthorised Links.</b> (Use Global/No/Yes). If Yes, the Intro Text for restricted articles will show. Clicking on the "Read More" link will require users to log in to view the full article content.</li>
</ul>
<ul>
<li><b>Positioning of the Links.</b> (Use Global/Above/Below). If Above, links are shown above the content. Otherwise they are shown below the content.</li>
</ul>
<h3> <span class="mw-headline" id="Common_Options">Common Options</span></h3>
<p>See <a href="<?php echo Route::url('index.php?option=com_help&view=help&keyref=Help25:Menus_Menu_Item_Manager_Edit'); ?>" title="Help25:Menus Menu Item Manager Edit">Menu Item Manager: New Menu Item</a> for help on fields common to all Menu Item types, including Details, Link Type Options, Page Display Options, Metadata Options, and Module Assignments for this Menu Item.</p>
<h2> <span class="mw-headline" id="Toolbar">Toolbar</span></h2>
<p>At the top right you will see the toolbar. The functions are:</p>
<ul>
<li><b>Save</b>. Saves the menu item and stays in the current screen.</li>
<li><b>Save &amp; Close</b>. Saves the menu item and closes the current screen.</li>
<li><b>Save &amp; New</b>. Saves the menu item and keeps the editing screen open and ready to create another menu item.</li>
<li><b>Save as Copy</b>. Saves your changes to a copy of the current menu item. Does not affect the current menu item. This toolbar icon is not shown if you are creating a new menu item.</li>
<li><b>Cancel/Close</b>. Closes the current screen and returns to the previous screen without saving any modifications you may have made.</li>
<li><b>Help</b>. Opens this help screen.</li>
</ul>
<h2> <span class="mw-headline" id="Quick_Tips">Quick Tips</span></h2>
<ul>
<li>If you have a Single Article Layout defined for an article, that layout will show any time a user drills down to that article. For example, if an article is shown on another menu item type (for example, in a Category Blog or List Layout or a Featured Articles Layout), the user will be taken to the Single Article Layout for that article (if defined).</li>
<li>Archived articles are no longer published but are still stored on the site. Articles are Archived using the <a href="<?php echo Route::url('index.php?option=com_help&view=help&keyref=Screen.content.15'); ?>" title="Screen.content.15" class="mw-redirect">Article Manager</a> screen. Note that Articles assigned to the "Uncategorized" Section will not show on the Archived Article List layout.</li>
</ul>
<h2> <span class="mw-headline" id="Related_Information">Related Information</span></h2>
<ul>
<li>Articles are created using <a href="<?php echo Route::url('index.php?option=com_help&view=help&keyref=Help25:Content_Article_Manager_Edit'); ?>" title="Help25:Content Article Manager Edit">Article Manager: Add or Edit</a>.</li>
</ul>
</article>