<article>
	<h1>Menu Manager</h1>

	<p>Provides an overview of the menus available on a site. This includes the details of each individual menu's number of items published, unpublished and names of linked modules.</p>
<h2> <span class="mw-headline" id="How_to_Access">How to Access</span></h2>
<p>To access this screen you can either:</p>
<ul>
<li>Click the <b>Menu Manager</b> button in the <a href="<?php echo Route::url('index.php?option=com_help&view=help&keyref=Help25:Site_Control_Panel'); ?>" title="Help25:Site Control Panel">Control Panel</a>, or</li>
<li>Select <b>Menus → Menu Manager</b> from the drop-down menus.</li>
</ul>
<h2> <span class="mw-headline" id="Description">Description</span></h2>
<p>Menus allow a user to navigate through the site. A menu is an object which contains one or more menu items. Each menu item points to a logical page on the site. A menu module is required to place the menu on the page. One menu can have more than one module. For example, one module might show only the first level menu items and a second module might show the level 2 menu items.</p>
<p>The process for adding a menu to the site is normally as follows:</p>
<ol>
<li>Create a new menu (using this screen).</li>
<li>Create one or more new menu items on the menu. Each menu item will have a specific menu item type.</li>
<li>Create one or more menu modules to display the menu on the site. When you create the modules, you will select which menu items (pages) the modules will show on.</li>
</ol>

<h2> <span class="mw-headline" id="Column_Headers">Column Headers</span></h2>
<ul>
<li><b>Checkbox</b>. Check this box to select one or more items. To select all items, check the box in the column heading. After one or more boxes are checked, click a toolbar button to take an action on the selected item or items. Many toolbar actions, such as Publish and Unpublish, can work with multiple items. Others, such as Edit, only work on one item at a time. If multiple items are checked and you press Edit, the first item will be opened for editing.</li>
<li><b>Title</b>. The name of the menu.</li>
<li><b># Published</b>. Number of published menu items in this menu.</li>
<li><b># Unpublished</b>. Number of unpublished menu items in this menu.</li>
<li><b># Trashed</b>. Number of trashed menu items in this menu.</li>
<li><b>Modules Linked to the Menu</b>. Lists any menu modules associated with the menu. The column shows the module's name, access level, and position on template.</li>
</ul>
<ul>
<li><b>ID</b>. This is a unique identification number for this item assigned automatically by the CMS. It is used to identify the item internally, and you cannot change this number. When creating a new item, this field displays 0 until you save the new entry, at which point a new ID is assigned to it.</li>
</ul>
<h2> <span class="mw-headline" id="List_Filters">List Filters</span></h2>
<ul>
<li><b>Page Controls.</b> When the number of items is more than one page, you will see a page control bar as shown below.

<ul>
<li><b>Display #:</b> Select the number of items to show on one page.</li>
<li><b>Start:</b> Click to go to the first page.</li>
<li><b>Prev:</b> Click to go to the previous page.</li>
<li><b>Page numbers:</b> Click to go to the desired page.</li>
<li><b>Next:</b> Click to go to the next page.</li>
<li><b>End:</b> Click to go to the last page.</li>
</ul>
</li>
</ul>
<h2> <span class="mw-headline" id="Toolbar">Toolbar</span></h2>
<p>At the top right you will see the toolbar. The functions are:</p>
<ul>
<li><b>New</b>. Opens the editing screen to create a new menu.</li>
<li><b>Edit</b>. Opens the editing screen for the selected menu. If more than one menu is selected (where applicable), only the first menu will be opened. The editing screen can also be opened by clicking on the Title or Name of the menu.</li>
<li><b>Delete</b>. Deletes the selected menus. Works with one or multiple menus selected. Deleting a menu also deletes all the menu items it contains and any associated menu modules. On clicking Delete you will be asked to confirm that you want to delete the selected menus. Clicking OK button will delete the menus. Click Cancel to abort the deletion.</li>
<li><b>Rebuild</b>. Reconstructs and refreshes the menu table. Normally, you do <i>not</i> need to rebuild this table. This function is provided in case the data in the table becomes corrupted.</li>
<li><b>Options</b>. Opens the Options window where settings such as default parameters or permissions can be edited. See Menus Configuration.</li>
<li><b>Help</b>. Opens this help screen.</li>
</ul>
<h2> <span class="mw-headline" id="Options">Options</span></h2>
<h3> <span class="mw-headline" id="Buttons_Common_to_All_Tabs">Buttons Common to All Tabs</span></h3>
<ul>
<li><b>Save</b>. Saves the banner options and stays in the current screen.</li>
<li><b>Save &amp; Close</b>. Saves the banner options and closes the current screen.</li>
<li><b>Cancel/Close</b>. Closes the current screen and returns to the previous screen without saving any modifications you may have made.</li>
</ul>
<h3> <span class="mw-headline" id="Page_Display_Options">Page Display Options</span></h3>
<ul>
<li><b>Browser Page Title.</b> Optional text for the "Browser Page Title" Element. If blank - a default value is used.</li>
<li><b>Show Page Heading.</b> (Show/Hide) Show or hide the Browser page title (above) in the heading of the page.</li>
<li><b>Page Heading.</b> Optional alternative text for the page heading.</li>
<li><b>Page Class.</b> Add an optional page class to elements in the page. It allows CSS styling specific to menu items pages.</li>
</ul>
<h3> <span class="mw-headline" id="Permissions_Tab">Permissions Tab</span></h3>
<p>This screen allows you to set the component permissions. This is important to consider if you have sites with many different user categories all of whom need to have different accessibilities to the component. The screenshot below describes what you should see and the text below that describes what each permission level gives the user access to:</p>

<p>You work on one Group at a time by opening the slider for that group. You change the permissions in the Select New Settings drop-down list boxes. The options for each value are Inherited, Allowed, or Denied. The Calculated Setting column shows you the setting in effect. It is either Not Allowed (the default), Allowed, or Denied. Note that the Calculated Setting column is not updated until you press the Save button in the toolbar. To check that the settings are what you want, press the Save button and check the Calculated Settings column.</p>
<p>The default values used here are the ones set in the <a href="<?php echo Route::url('index.php?option=com_help&view=help&keyref=Help25:Site_Global_Configuration#Permissions'); ?>" title="Help25:Site Global Configuration">Global Configuration Permissions Tab</a></p>
<dl>
<dd>
<dl>
<dt>Configure</dt>
<dd>Open the menus component option screens (the modal window these options are in)</dd>
<dt>Access Administration Interface</dt>
<dd>Open the menus component manger screens</dd>
<dt>Create&#160;</dt>
<dd>Create new menus in the component</dd>
<dt>Delete&#160;</dt>
<dd>Delete existing menus in the component</dd>
<dt>Edit&#160;</dt>
<dd>Edit existing menus in the component</dd>
<dt>Edit State&#160;</dt>
<dd>Change an menus state (Publish, Unpublish, Archive, and Trash) in the component.</dd>
</dl>
</dd>
</dl>
<p>There are two very important points to understand from this screen. The first is to see how the permissions can be inherited from the parent Group. The second is to see how you can control the default permissions by Group and by Action. This provides a lot of flexibility. For example, if you wanted Shop Suppliers to be able to have the ability to create an article about their product, you could just change their Create value to "Allowed". If you wanted to not allow members of Administrator group to delete objects or change their state, you would change their permissions in these columns to Inherited (or Denied). It is also important to understand that the ability to have child groups is completely optional. It allows you to save some time when setting up new groups. However, if you like, you can set up all groups to have Public as the parent and not inherit any permissions from a parent group.</p>
<h2> <span class="mw-headline" id="Quick_Tips">Quick Tips</span></h2>
<ul>
<li>It is expedient to give a descriptive title for new menus because, later, you will see it in the <i>Backend Menus</i> menu. It is a good idea to fill in the <i>Description</i> field with information about the menu. If you enter a short title in the <i>Module title</i> field, you can identify the menu's module using that title in the Module Manager.</li>
<li>Though you can create a copy of a selected menu by clicking the <i>Copy</i> toolbar button, you can make another instance in the Module Manager as well.</li>
<li>When you create a new menu, use only English alphanumeric characters without space in the Unique Name field. It is a good idea using only a-z, 0-9 and underscore (_) characters. Please read the tooltips as well.</li>
<li>If you don't enter a <i>Module title</i>, no module will be created and the menu cannot be displayed in the front end. However you can use the Module Manager later to create a new mod_mainmenu module, and assign it to the menu.</li>
<li>If you delete an existing menu, do not forget that all the menu items of the respective menu will be also deleted.</li>
<li>The Main Menu has your default menu item, so it <b>should not be deleted</b>. The default menu item is your home page, and your site will not function if it is deleted. If you change the default menu item, make sure that you don't delete that menu item either! The menu with the default menu item is marked with an asterisk (*) in the <i>Menus</i> menu.</li>
</ul>
<h2> <span class="mw-headline" id="Related_Information">Related Information</span></h2>
<ul>
<li>To add new Menus: <a href="<?php echo Route::url('index.php?option=com_help&view=help&keyref=Help25:Menus_Menu_Manager_Edit'); ?>" title="Help25:Menus Menu Manager Edit">Menu Manager New/Edit</a></li>
<li>To set action permissions for menus: <a href="<?php echo Route::url('index.php?option=com_help&view=help&keyref=Help25:Menus_Menu_Manager#Options'); ?>" title="Help25:Menus Menu Manager">Menus Configuration</a></li>
<li>To add or edit Menu Items: <a href="<?php echo Route::url('index.php?option=com_help&view=help&keyref=Help25:Menus_Menu_Item_Manager'); ?>" title="Help25:Menus Menu Item Manager">Menu Item Manager</a></li>
<li>To add or edit Menu Modules: <a href="<?php echo Route::url('index.php?option=com_help&view=help&keyref=Help25:Menus_Menu_Item_Manager_Edit'); ?>" title="Help25:Menus Menu Item Manager Edit">Module Manager</a></li>
</ul>
</article>