<article>
	<h1>Menu Manager: Edit Menu</h1>

	<h2> <span class="mw-headline" id="Description">Description</span></h2>
<p>You can add or modify menus in this screen.</p>

<h2> <span class="mw-headline" id="Column_Headers">Column Headers</span></h2>
<ul>
<li><b>Title</b>. The name of the item. For a Menu Item, the Title will display in the Menu. For an Article, Section, or Category, the Title may optionally be displayed on the web page. This entry is required. You can open the item for editing by clicking on the Title.</li>
</ul>
<ul>
<li><b>Type</b>. The type column in the menu manager will actually be the Unique Name of the menu.</li>
</ul>
<p><b>Description:</b> A brief note describing the menu, which will be displayed in the Menu Manager.</p>
<h2> <span class="mw-headline" id="Toolbar">Toolbar</span></h2>
<p>At the top right you will see the toolbar. The functions are:</p>
<ul>
<li><b>Save</b>. Saves the menu and stays in the current screen.</li>
<li><b>Save &amp; Close</b>. Saves the menu and closes the current screen.</li>
<li><b>Save &amp; New</b>. Saves the menu and keeps the editing screen open and ready to create another menu.</li>
<li><b>Cancel/Close</b>. Closes the current screen and returns to the previous screen without saving any modifications you may have made.</li>
<li><b>Help</b>. Opens this help screen.</li>
</ul>
<h2> <span class="mw-headline" id="Quick_Tips">Quick Tips</span></h2>
<ul>
<li>Hover your mouse over the '*' next to the input box, and extra information will be shown.</li>
<li>If you forgot to create a module for this menu, you can do so by using the <a href="<?php echo Route::url('index.php?option=com_help&view=help&keyref=Help25:Extensions_Module_Manager'); ?>" title="Help25:Extensions Module Manager">Module Manager</a>, found by going to Extensions -&gt; Module Manager. Click on 'New', and then on 'Menu'. Fill in a title and select the Menu in the Module Parameters.</li>
<li>It is a good idea to give a descriptive title for new menus. This is how the menu will be identified in the <i>Backend Menus menu</i>. It is also a good idea to fill in the <i>Description</i> field with information about the menu. This is how the menu's module will be referred to in the Module Manager.</li>
<li>When you create a new menu, use only alphanumeric characters without spaces in the <i>Unique Name</i> field. It is a good idea to use only a-z, 0-9 and underscore (_) characters. Please read the tooltips as well.</li>
</ul>
<h2> <span class="mw-headline" id="Related_information">Related information</span></h2>
<ul>
<li><a href="<?php echo Route::url('index.php?option=com_help&view=help&keyref=Help25:Menus_Menu_Manager'); ?>" title="Help25:Menus Menu Manager">Menu Manager</a></li>
<li><a href="<?php echo Route::url('index.php?option=com_help&view=help&keyref=Help25:Site_Control_Panel'); ?>" title="Help25:Site Control Panel">Control Panel</a></li>
</ul>
</article>