<?php
/**
 * HUBzero CMS
 *
 * Copyright 2005-2014 Purdue University. All rights reserved.
 *
 * This file is part of: The HUBzero(R) Platform for Scientific Collaboration
 *
 * The HUBzero(R) Platform for Scientific Collaboration (HUBzero) is free
 * software: you can redistribute it and/or modify it under the terms of
 * the GNU Lesser General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any
 * later version.
 *
 * HUBzero is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * HUBzero is a registered trademark of Purdue University.
 *
 * @package   hubzero-cms
 * @author    Shawn Rice <zooley@purdue.edu>
 * @copyright Copyright 2005-2014 Purdue University. All rights reserved.
 * @license   http://www.gnu.org/licenses/lgpl-3.0.html LGPLv3
 */

// Check to ensure this file is included in Joomla!
defined('_JEXEC') or die('Restricted access');
?>
<article>
	<h1>Forum Help</h1>

	<p>A forum, or message board, is an online discussion area where people can hold conversations in the form of posted messages.</p>
	<p>Forums have a specific set of jargon associated with them; e.g. a single conversation is called a "thread" or discussion.</p>
	<p>A discussion forum is hierarchical or tree-like in structure: a forum can contain a number of <strong>sections</strong>, each of which may have several categories. Within a forum's <strong>category</strong>, each new discussion started is called a <strong>thread</strong>, and can be replied to by as many people as so wish.</p>

	<nav>
		<ul>
			<li>
				<a href="<?php echo JRoute::_('index.php?option=com_help&component=forum&page=sections'); ?>">Sections</a>
			</li>
			<li>
				<a href="<?php echo JRoute::_('index.php?option=com_help&component=forum&page=categories'); ?>">Categories</a>
			</li>
			<li>
				<a href="<?php echo JRoute::_('index.php?option=com_help&component=forum&page=threads'); ?>">Threads</a>
			</li>
			<?php /*<li>
				<a href="<?php echo JRoute::_('index.php?option=com_help&component=forum&page=guidelines'); ?>">Guidelines &amp; Tips</a>
			</li> */ ?>
			<li>
				<a href="<?php echo JRoute::_('index.php?option=com_help&component=forum&page=faqs'); ?>">FAQs</a>
			</li>
		</ul>
	</nav>
</article>