<?php
/**
 * @package    hubzero-cms
 * @copyright  Copyright 2005-2019 HUBzero Foundation, LLC.
 * @license    http://opensource.org/licenses/MIT MIT
 */
?>
<article>
	<h1>Tools Help</h1>
	<p>Below are help pages related to tools and tool sessions.</p>
	<ul>
		<li>
			<a href="<?php echo Route::url('index.php?option=com_help&component=tools&page=sessions'); ?>">Tool Sessions</a>
		</li>
		<li>
			<a href="<?php echo Route::url('index.php?option=com_help&component=tools&page=storage'); ?>">Tool Storage</a>
		</li>
	</ul>
</article>