<article>
	<h1><span>Media Manager</span></h1>

	<ul class="nav">
		<li><a href="#overview">Overview</a></li>
		<li><a href="#toolbar">Toolbar</a></li>
		<li><a href="#functions">Functions</a></li>
		<li><a href="#tips">Quick Tips</a></li>
		<li><a href="#related">Related information</a></li>
	</ul>

	<section id="overview">
		<h2><span>Overview</span></h2>

		<p>The Media Manager is a very useful tool for uploading or deleting files in the &lt;root&gt;https://myhub.org/site/media/images/ directory on your web server. You can upload new files, delete existing ones, and create sub-directories. The Media Manager offers two views: thumbnails view and details view. The first (thumbnails view) will show a preview of the image files. The second (details view) will show the file name, dimensions, and file size. There is also a handy 'delete' button next to each file.</p>
	</section>
	<section id="toolbar">
		<h2>Toolbar</h2>
		<p>At the top right you will see the toolbar. The functions are:</p>
		<ul>
			<li><b>Delete</b>. Deletes the selected images. Works with one or multiple images selected.</li>
			<li><b>Options</b>. Opens the Options window where settings such as default parameters or permissions can be edited.</li>
			<li><b>Help</b>. Opens this help screen.</li>
		</ul>
	</section>
	<section id="functions">
		<h2>Functions</h2>
		<dl>
			<dt>Switching Views&#160;</dt>
			<dd>To alternate views between thumbnails and details simply select the view you want by clicking "Thumbnails View" or "Details View".<br /></dd>
			<dt>Uploading Files&#160;</dt>
			<dd>If you would like to upload images or other files to the &lt;root&gt;https://myhub.org/site/media/images/ directory (or any of the sub directories) simply open the directory you want to upload in by clicking on it in the file navigation utility on the right side of the screen. Near the bottom of the Media Manager, there is an area marked <b>Upload File [Max 10M]</b>. Underneath that heading are three buttons: "Browse", "Start Upload", and "Clear Completed". To upload a file, start by using the "Browse" button to find the file you would like to upload, and then click "Open". (You can do this several times so long as the overall file size accumulation doesn't exceed your max file upload size). Once you have all the files you want queued, hit the "Start Upload" button. The files will be uploaded to the selected directory.<br /></dd>
			<dt>Create A Sub Directory&#160;</dt>
			<dd>If you want to create a sub directory, you can do so using the Media Manager. Navigate to the directory you want the soon-to-be sub directory to be located in. In the upper right hand side of the Media Manager, there is a text field area next to a button labeled "Create Folder". Type the name of the desired sub directory into this text field, and then click the "Create Folder" button. The page will refresh and the sub folder will have been created.</dd>
		</dl>
	</section>
	<section id="tips">
		<h2>Quick Tips</h2>
		<ul>
		<li>The Media Manager's maximum upload size can be changed to an amount other than 10M in the <a href="<?php echo JRoute::_('index.php?option=com_help&view=help&keyref=Help25:Site_Global_Configuration'); ?>">Global Configuration</a>.</li>
		<li>You can upload multiple files at the same time. Click on 'Start Upload' to upload all images displayed beneath it.</li>
		<li>Click on 'Clear completed' to delete the completed files from the uploading list. The images will not be removed from your /images directory.</li>
		</ul>
	</section>
	<section id="related">
		<h2>Related information</h2>
		<ul>
			<li><a href="<?php echo JRoute::_('index.php?option=com_help&view=help&keyref=Help25:Site_Control_Panel'); ?>">Control Panel</a></li>
		</ul>
	</section>
</article>