<?php
/**
 * HUBzero CMS
 *
 * Copyright 2005-2015 HUBzero Foundation, LLC.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 *
 * HUBzero is a registered trademark of Purdue University.
 *
 * @package   hubzero-cms
 * @author    Christopher Smoak <csmoak@purdue.edu>
 * @copyright Copyright 2005-2015 HUBzero Foundation, LLC.
 * @license   http://opensource.org/licenses/MIT MIT
 */

// No direct access.
defined('_HZEXEC_') or die();
?>
<article>
	<h1>Collections Help: Collection</h1>
	<p>A collection is where you organize your posts by topic. You could collect resources for creating an introduction to Nanotechnology, for example. You can even put a collection inside another collection!</p>

	<section>
		<h2>Default Collection</h2>
		<p>Everyone gets a default collection auto-created for you. This is so you already have something you can start to add posts to right away. Default collections are private from the start, but feel free to change the privacy setting as you like. You can also change the to change the title and description.</p>
	</section>

	<section>
		<h2>Creating a Collection</h2>
		<p>You can create a collection by clicking the "New Collection" button found when viewing your list of collections or "on-the-fly" when collecting a post.</p>

		<h3>"New Collection" button</h3>
		<p>After clicking the button, you will be presented with some fields to customize and describe your collection. The only required field is a title but you may, optionally, enter a longer description.</p>

		<h3>"on-the-fly"</h3>
		<p>A collection can be created at the time of collecting something on the site. When browsing collectibles content, such as resources, wiki pages, etc., you may find a "Collect" button on the page. After clicking said button, you will be presented with some an option to add the item to an existing collection or to create a new collection with the title you enter.</p>
	</section>

	<section>
		<h2>Create a private Collection</h2>
		<p>You can also make private or secret collections. When creating or editing a collection, there will be a "Privacy" field with a pull-down list of options. Select "Private" and save the changes. When a collection is private, a little <span class="icon-private">padlock</span> will appear next to its title.</p>
		<p><strong>Note:</strong> When a collection is private, it will not appear in searches or in the <a href="<?php echo Route::url('index.php?option=com_collections'); ?>">site-wide collections</a> list.</p>
	</section>

	<section>
		<h2>Deleting a Collection</h2>
		<p>To delete a collection, login to your account and find the appropriate collection in your "Collections" list. When hovering or focusing on the collection, a "Delete" button will appear. When clicked, you will be asked to confirm the deletion. If you say no, nothing further will happen. If yes, the colleciton will be removed.</p>
		<p><strong>Note:</strong> Removing a collection will <em>not</em> remove all the posts found within the collection.</p>
	</section>
</article>