<?php
/**
 * @package    hubzero-cms
 * @copyright  Copyright 2005-2019 The Regents of the University of California.
 * @license    http://opensource.org/licenses/MIT MIT
 */

// No direct access.
defined('_HZEXEC_') or die();
?>
<article>
	<h1>Collections Help: Following/Unfollowing</h1>

	<h2>Follow</h2>
	<p>When you follow someone, their posts show up in your live feed. You can follow all of someone's collections or just the ones you like best. To manage who you're following, go to your profile, find Collections, and click Following.</p>

	<h2>Unfollow</h2>
	<p>When you unfollow someone, their collections won't show up in your live feed anymore. You can unfollow all of someone's collections, or just the ones you're not that interested in.</p>
</article>