<?php
/**
 * HUBzero CMS
 *
 * Copyright 2005-2015 HUBzero Foundation, LLC.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 *
 * HUBzero is a registered trademark of Purdue University.
 *
 * @package   hubzero-cms
 * @author    Shawn Rice <zooley@purdue.edu>
 * @copyright Copyright 2005-2015 HUBzero Foundation, LLC.
 * @license   http://opensource.org/licenses/MIT MIT
 */

// No direct access.
defined('_HZEXEC_') or die();

\Hubzero\Document\Assets::addComponentStylesheet('com_collections', 'help');
?>
<article>
	<h1>Collections Help</h1>

	<p class="tagline">Collections are a quick and easy way to share, favorite, and organize information on a hub.</p>

	<section class="about-odd posts">
		<h2>Post</h2>
		<p>A post starts with an image, link, or file you want to share. You can add a post by collecting content on the site or upload a file right from your computer. Any post can be reposted, and all posts link back to their source.</p>
		<p><a href="<?php echo Route::url('index.php?option=com_help&component=collections&page=posts'); ?>">Learn more</a></p>
	</section>

	<section class="about-even collections">
		<h2>Collect</h2>
		<p>A collection is where you organize your posts by topic. You could collect resources for creating an introduction to Nanotechnology, for example. Collections can be secret or public, and you can even put a collection inside another collection!</p>
		<p><a href="<?php echo Route::url('index.php?option=com_help&component=collections&page=collections'); ?>">Learn more</a></p>
	</section>

	<section class="about-odd following">
		<h2>Follow</h2>
		<p>When you follow someone, their posts show up in your live feed. You can follow all of someone's collections or just the ones you like best. To manage who you're following, go to your profile, find Collections, and click Following.</p>
		<p><a href="<?php echo Route::url('index.php?option=com_help&component=collections&page=following'); ?>">Learn more</a></p>
	</section>
</article>