<!DOCTYPE html>
<!--[if lt IE 7 ]> <html dir="ltr" lang="en" class="ie6"> <![endif]-->
<!--[if IE 7 ]>    <html dir="ltr" lang="en" class="ie7"> <![endif]-->
<!--[if IE 8 ]>    <html dir="ltr" lang="en" class="ie8"> <![endif]-->
<!--[if IE 9 ]>    <html dir="ltr" lang="en" class="ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html dir="ltr" lang="en"> <!--<![endif]-->
	<head>
		<title>Support Documentation: Stats</title>
		<link rel="stylesheet" href="/media/system/css/documentation.css" type="text/css" />
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	</head>
	<body id="documentation-body">
		<div class="article">
			<h1><span>Stats</span></h1>
			<div class="section">
				<h2><span>Overview</span></h2>

				<p>The stats page gives a basic overview of support ticket activity starting at the beginning of a chosen year, defaulting to the current year if none specified.</p>

				<p>The following data is shown:</p>

				<ul>
					<li>Tickets opened for the given year</li>
					<li>Tickets closed for the given year</li>
					<li>Tickets opened for the current month of the year</li>
					<li>Tickets closed for the current month of the year</li>
					<li>Tickets opened for the current week of the year</li>
					<li>Tickets closed for the current week of the year</li>
					<li>Open tickets</li>
					<li>Unassigned tickets</li>
					<li>Average ticket lifetime</li>
					<li>A list of administrators and the number of tickets closed
						<ul>
							<li>closed for the given year</li>
							<li>closed for the current month of the year</li>
							<li>closed for the current week of the year</li>
						</ul>
					</li>
					<li>A line chart displaying Tickets Submitted (red) vs. Closed (green) on a monthly basis</li>
				</ul>

				<p>Stats shown may also be filtered by group.</p>
			</div>
		</div>
	</body>
</html>