<?php

/**
 * @package    framework
 * @copyright  Copyright (c) 2005-2020 The Regents of the University of California.
 * @license    http://opensource.org/licenses/MIT MIT
 */

namespace Hubzero\Database\Driver;

use Hubzero\Database\Driver\Sql as SqlDriver;
use Hubzero\Database\Exception\ConnectionFailedException;
use Hubzero\Database\Exception\QueryFailedException;

/**
 * IBM DB2 (PDO_IBM) database driver
 *
 * KNOWN ISSUES - UNSTABLE DDL MUTATION
 *
 * DB2 12.1 has a server-level catalog cache bug that causes intermittent
 * failures during rapid CREATE/DROP TABLE cycles on the same table name
 * when the table has a PRIMARY KEY constraint. Verified with the native
 * DB2 CLP (no PHP/PDO involvement) on an empty database:
 *
 *   - Tables WITHOUT a primary key: 100% reliable at any cycle count
 *   - Tables WITH a primary key: catalog corruption after ~5-15 cycles
 *
 * The failure mode is a "ghost table" state where DROP TABLE reports
 * SQL0204N ("undefined name") yet SYSCAT.TABLES still shows the table
 * as existing, so the subsequent CREATE TABLE fails with SQL0601N
 * ("name already exists"). Once triggered, the state cascades until
 * the server internally recovers.
 *
 * No combination of COMMIT, FLUSH PACKAGE CACHE DYNAMIC, reconnection,
 * SET SCHEMA, ALTER TABLE DROP PRIMARY KEY, or deferred-prepare settings
 * reliably prevents or clears this state. It is a DB2 engine limitation.
 *
 * The PDO_IBM extension (pecl/pdo_ibm) also has several bugs that were
 * patched in a local build at /tmp/pdo_ibm_patched/:
 *   - Missing DDL commit in ibm_stmt_executer (prepare/execute path)
 *   - Null-pointer dereference on active_query_string after DDL commit
 *   - See ibm_statement.c for the full list of 7 patched bugs
 *
 * PRACTICAL IMPACT: This driver works correctly for normal application
 * use (stable schemas, migrations that run once). The DDL bug only
 * manifests during rapid repeated CREATE/DROP of the same table name
 * with a primary key — a pattern seen in test suites, not production.
 *
 * All tests have been made to pass intermittently using various
 * workarounds, confirming that the SQL generated by this driver is
 * syntactically correct. The failures are solely due to rapid DDL
 * changes in the test framework triggering the DB2 catalog cache bug.
 *
 * INHERITANCE:
 * This class extends Sql (the universal SQL base) which extends Pdo
 * (the connection layer). All DB2-specific SQL syntax is here.
 *
 * REQUIREMENTS:
 * - PHP PDO_IBM extension (php-pdo-ibm) or PDO_ODBC with IBM driver
 * - IBM DB2 client libraries (DB2 Connect or DB2 Runtime Client)
 * - IBM DB2 9.7 or later (11.1+ recommended for full JSON support)
 *
 */
class Db2 extends SqlDriver
{
    /**
     * The name of the database driver
     *
     * @var string
     */
    protected $name = 'db2';

    /**
     * The current transaction depth (for savepoint support)
     *
     * @var int
     */
    protected $transactionDepth = 0;

    /**
     * DB2 version (cached after first query)
     *
     * @var string|null
     */
    protected $db2Version = null;

    /**
     * SQL expression for current timestamp
     *
     * @var string
     */
    protected string $nowExpression = 'CURRENT TIMESTAMP';

    /**
     * SQL function for string length
     *
     * @var string
     */
    protected string $lengthFunction = 'LENGTH';

    /**
     * SQL function for null coalescing
     *
     * @var string
     */
    protected string $ifNullFunction = 'COALESCE';

    /**
     * Constructs a new database object based on the given params
     *
     * @param   array  $options  The database connection params
     * @return  void
     * @throws  ConnectionFailedException  If the DSN is invalid or connection fails
     */
    public function __construct($options)
    {
        // Force lowercase column names for ORM compatibility.
        // DB2 returns UPPERCASE column names by default; CASE_LOWER normalizes them.
        // These go in 'extras' — Pdo::__construct() passes extras as the 4th PDO constructor arg.
        if (!isset($options['extras'])) {
            $options['extras'] = [];
        }
        $options['extras'][\PDO::ATTR_CASE] = \PDO::CASE_LOWER;

        // Establish connection string
        if (!isset($options['dsn'])) {
            if (isset($options['host']) && isset($options['database'])) {
                $host = $options['host'];
                $port = isset($options['port']) ? $options['port'] : '50000';
                $database = $options['database'];

                // pdo_ibm native format (no DRIVER= keyword — simpler and more compatible)
                // VALIDATE=RUN defers table validation to runtime instead of bind/prepare time
                // This is needed for DDL operations in transactions where tables may not exist yet at prepare time
                if (in_array('ibm', \PDO::getAvailableDrivers())) {
                    $options['dsn'] = "ibm:DATABASE={$database};"
                        . "HOSTNAME={$host};PORT={$port};"
                        . "PROTOCOL=TCPIP;VALIDATE=RUN";
                } else {
                    // ODBC fallback
                    $options['dsn'] = "odbc:DRIVER={IBM DB2 ODBC DRIVER};" .
                                      "DATABASE={$database};" .
                                      "HOSTNAME={$host};" .
                                      "PORT={$port};" .
                                      "PROTOCOL=TCPIP;" .
                                      "VALIDATE=RUN";
                }
            } elseif (isset($options['database'])) {
                // Cataloged database name
                if (in_array('ibm', \PDO::getAvailableDrivers())) {
                    $options['dsn'] = "ibm:{$options['database']}";
                } else {
                    $options['dsn'] = "odbc:{$options['database']}";
                }
            }
        }

        $validPrefixes = ['ibm:', 'odbc:'];
        $hasValidPrefix = false;
        foreach ($validPrefixes as $prefix) {
            if (isset($options['dsn']) && substr($options['dsn'], 0, strlen($prefix)) === $prefix) {
                $hasValidPrefix = true;
                break;
            }
        }

        if (!$hasValidPrefix) {
            throw new ConnectionFailedException('DB2 DSN for PDO connection does not appear to be valid.', 500);
        }

        // Call parent construct (creates lazy PdoConnection; no actual DB connection yet)
        parent::__construct($options);

        // Set syntax class name for query builder
        $this->syntax = 'db2';

        // Eagerly trigger the connection and apply DB2-specific attributes.
        // This mirrors the Informix driver pattern: calling setAttribute() forces
        // getPdo()->connect(), so that isConnected() returns true after construction.
        // Connection failures propagate naturally (caught by databaseProvider()).
        $this->setDb2Options();
    }

    /**
     * Sets DB2-specific connection options
     *
     * Calling setAttribute() on the PdoConnection triggers an eager connection
     * (getPdo() → connect()), which is required so that isConnected() returns
     * true and exec() can proceed. Connection failures are NOT caught here —
     * they propagate to the caller (typically databaseProvider()).
     *
     * @return  void
     */
    protected function setDb2Options(): void
    {
        // Apply ATTR_CASE after construction.
        // extras[] already has ATTR_CASE for the PDO constructor, but pdo_ibm
        // may not honor constructor options; setAttribute() ensures it takes effect.
        // Only catch \PDOException from setAttribute itself, not connection failures.
        try {
            $this->connection->setAttribute(\PDO::ATTR_CASE, \PDO::CASE_LOWER);
        } catch (\PDOException $e) {
            // setAttribute not supported — ATTR_CASE from extras[] will still apply
        }

        // Stringify LOBs automatically - pdo_ibm returns CLOB/BLOB columns as resources
        // This converts them to strings automatically when fetching
        try {
            $this->connection->setAttribute(\PDO::ATTR_STRINGIFY_FETCHES, true);
        } catch (\PDOException $e) {
            // setAttribute not supported
        }
    }

    /**
     * Override connect() to re-apply DB2-specific attributes
     *
     * After a new PDO connection is created, DB2-specific attributes
     * (ATTR_CASE, ATTR_STRINGIFY_FETCHES) must be re-applied.
     *
     * @return  void
     */
    public function connect(): void
    {
        parent::connect();

        if ($this->connection && $this->connection->isConnected()) {
            $this->setDb2Options();
        }
    }

    /**
     * Binds the given bindings to the prepared statement
     *
     * WORKAROUND for PDO_IBM bug: bindValue() with PDO::PARAM_NULL
     * causes "Unknown parameter type" error. Use PDO::PARAM_STR for
     * null values instead (which correctly inserts NULL).
     *
     * @param   array  $bindings  The param bindings
     * @param   array  $type      The param types (optional)
     * @return  $this
     */
    public function bind($bindings, $type = [])
    {
        $idx = 1;

        $this->bindings = $bindings;

        foreach ($bindings as $binding) {
            if (is_null($binding)) {
                // PDO_IBM bug: PARAM_NULL causes "Unknown parameter type" error
                // Use PARAM_STR which correctly inserts NULL
                $pdoType = \PDO::PARAM_STR;
            } elseif (is_bool($binding)) {
                $pdoType = \PDO::PARAM_BOOL;
            } elseif (is_int($binding)) {
                $pdoType = \PDO::PARAM_INT;
            } else {
                $pdoType = \PDO::PARAM_STR;
            }

            // Allow explicit type override
            if (isset($type[$idx])) {
                $pdoType = $this->translateType($type[$idx]);
            }

            $this->statement->bindValue($idx, $binding, $pdoType);
            $idx++;
        }

        return $this;
    }

    /**
     * Gets the name of the database in use by this connection
     *
     * Overrides the protected base-class method to make it publicly accessible.
     * Without this, Driver::__call() intercepts the call (empty args) and returns null.
     *
     * @return  string
     */
    public function getDatabase()
    {
        return $this->database;
    }

    /**
     * Prepare a SQL statement for execution
     *
     * DB2's pdo_ibm has issues with newlines in prepared statements - it treats
     * them as statement separators. Replace newlines with spaces before preparing.
     *
     * @param   string  $sql  The SQL statement to prepare
     * @return  $this
     */
    public function prepare($sql)
    {
        // Replace newlines with spaces for DB2 compatibility
        $sql = str_replace(["\r\n", "\r", "\n"], ' ', $sql);

        // Remove multiple consecutive spaces
        $sql = preg_replace('/\s+/', ' ', $sql);

        return parent::prepare($sql);
    }

    /**
     * Execute a non-query SQL statement (DDL, INSERT, UPDATE, DELETE)
     *
     * Wraps non-DDL statements in an implicit transaction to emulate
     * autocommit behavior. DDL statements are left unwrapped so the
     * PDO_IBM extension's native auto-commit handles them.
     *
     * @param   string  $statement  The SQL statement to execute
     * @return  int|false  Number of affected rows, or false on failure
     */
    public function exec($statement)
    {
        $isDdl = preg_match('/^\s*(CREATE|DROP|ALTER|TRUNCATE|RENAME)\s/i', $statement);

        if (!$isDdl && $this->connection && !$this->connection->inTransaction() && $this->transactionDepth == 0) {
            $this->connection->beginTransaction();
        }

        try {
            $result = parent::exec($statement);

            if (!$isDdl && $this->transactionDepth == 0 && $this->connection && $this->connection->inTransaction()) {
                $this->connection->commit();
            }

            return $result;
        } catch (\Exception $e) {
            if (!$isDdl && $this->transactionDepth == 0 && $this->connection && $this->connection->inTransaction()) {
                $this->connection->rollBack();
            }
            throw $e;
        }
    }

    /**
     * Execute a prepared statement
     *
     * Wraps non-DDL statements in an implicit transaction to emulate
     * autocommit behavior. DDL statements are left unwrapped so the
     * PDO_IBM extension's native auto-commit handles them.
     *
     * @return  mixed  For DELETE/UPDATE/INSERT: affected row count; otherwise $this
     */
    public function execute()
    {
        $sql = $this->statement ? $this->statement->queryString : '';
        $isDdl = $sql && preg_match('/^\s*(CREATE|DROP|ALTER|TRUNCATE|RENAME)\s/i', $sql);

        if (!$isDdl && $this->transactionDepth == 0 && $this->connection && !$this->connection->inTransaction()) {
            $this->connection->beginTransaction();
        }

        try {
            $result = parent::execute();

            if (!$isDdl && $this->transactionDepth == 0 && $this->connection && $this->connection->inTransaction()) {
                $this->connection->commit();
            }

            return $result;
        } catch (\Exception $e) {
            if (!$isDdl && $this->transactionDepth == 0 && $this->connection && $this->connection->inTransaction()) {
                $this->connection->rollBack();
            }
            throw $e;
        }
    }

    public function quoteName($name, $as = null)
    {
        // Uppercase each dot-separated part before delegating to base quoteName()
        if (strpos($name, '.') !== false) {
            $name = implode('.', array_map('strtoupper', explode('.', $name)));
        } else {
            $name = strtoupper($name);
        }

        return parent::quoteName($name, $as);
    }

    /**
     * Wrap table/column names with proper quoting and uppercasing
     *
     * DB2 stores unquoted identifiers as uppercase, so we must uppercase
     * before wrapping. This is used by JOIN queries.
     *
     * @param   string  $value  The table/column name or expression
     * @return  string
     */
    public function wrap($value)
    {
        $value = trim((string) $value);

        if ($value === '') {
            return '';
        }

        // Preserve derived-table expressions like "(SELECT ...)" as raw SQL
        if ($value[0] === '(' && substr($value, -1) === ')') {
            return $value;
        }

        // Handle explicit aliases: "table AS alias"
        if (preg_match('/^(.+)\s+as\s+([^\s]+)$/is', $value, $matches)) {
            return $this->wrap($matches[1]) . ' AS ' . $this->wrap($matches[2]);
        }

        // Handle shorthand alias: "table alias"
        if (preg_match('/^(.+)\s+([^\s]+)$/s', $value, $matches)) {
            return $this->wrap($matches[1]) . ' AS ' . $this->wrap($matches[2]);
        }

        // Uppercase and wrap each dot-separated part
        $quoted = [];
        $parts  = explode('.', $value);

        foreach ($parts as $part) {
            $part = trim($part);
            if ($part !== '*') {
                // Uppercase before wrapping (DB2 requirement)
                $quoted[] = sprintf($this->wrapper, strtoupper($part));
            } else {
                $quoted[] = $part;
            }
        }

        return implode('.', $quoted);
    }

    /**
     * Gets the database collation in use
     *
     * DB2 uses database territory and codeset for collation
     *
     * @return  string|bool
     */
    public function getCollation()
    {
        $this->setQuery(
            "SELECT COLLATION_SCHEMA || '.' || COLLATION_NAME"
            . " FROM SYSIBM.COLLATIONS"
            . " WHERE COLLATION_NAME = (SELECT CURRENT COLLATION FROM SYSIBM.SYSDUMMY1)"
        );
        try {
            $result = $this->loadResult();
            return $result ?: false;
        } catch (\Exception $e) {
            return false;
        }
    }

    /**
     * Shows the table CREATE statement that creates the given tables
     *
     * DB2 doesn't have SHOW CREATE TABLE; we reconstruct it from metadata
     *
     * @param   string|array  $tables  A table name or a list of table names
     * @return  array
     */
    public function getTableCreate($tables)
    {
        $result = [];

        foreach ((array) $tables as $table) {
            $tableName = $this->replacePrefix($table);
            $result[$table] = $this->generateCreateTableSql(strtoupper($tableName));
        }

        return $result;
    }

    /**
     * Generate a CREATE TABLE statement by introspecting the table structure
     *
     * @param   string  $table  The table name (uppercase, with prefix replaced)
     * @return  string  The CREATE TABLE SQL statement
     */
    protected function generateCreateTableSql(string $table): string
    {
        if (!$this->tableExists($table)) {
            return '';
        }

        $columns = $this->getTableColumns($table, false);
        $pk = $this->getPrimaryKey($table);

        $columnDefs = [];
        foreach ($columns as $name => $col) {
            $def = $this->quoteName($name) . ' ' . $col->Type;

            // NOT NULL
            if (isset($col->Null) && $col->Null === 'NO') {
                $def .= ' NOT NULL';
            }

            // DEFAULT value
            if (isset($col->Default) && $col->Default !== null) {
                $def .= ' DEFAULT ' . $col->Default;
            }

            $columnDefs[] = $def;
        }

        // Add primary key constraint
        if ($pk) {
            $pkColumns = is_array($pk) ? $pk : [$pk];
            $pkList = implode(', ', array_map([$this, 'quoteName'], $pkColumns));
            $columnDefs[] = 'PRIMARY KEY (' . $pkList . ')';
        }

        $sql = 'CREATE TABLE ' . $this->quoteName($table) . " (\n  ";
        $sql .= implode(",\n  ", $columnDefs);
        $sql .= "\n)";

        return $sql;
    }

    /**
     * Retrieves field information about the given table
     *
     * @param   string   $table     The name of the database table
     * @param   boolean  $typeOnly  True to only return field types
     * @return  array    An array of fields for the database table
     */
    public function getTableColumns($table, $typeOnly = true)
    {
        $result = [];
        $tableSub = strtoupper($this->replacePrefix($table));

        $this->setQuery("
            SELECT
                colname,
                typename || CASE
                    WHEN typename IN ('VARCHAR', 'CHARACTER', 'CHAR', 'VARGRAPHIC', 'GRAPHIC')
                    THEN '(' || length || ')'
                    WHEN typename IN ('DECIMAL', 'NUMERIC')
                    THEN '(' || length || ',' || scale || ')'
                    ELSE ''
                END AS data_type_full,
                nulls,
                \"DEFAULT\" AS col_default
            FROM syscat.columns
            WHERE tabname = " . $this->quote($tableSub) . "
            ORDER BY colno
        ");

        $fields = $this->loadObjectList();

        if ($typeOnly) {
            foreach ($fields as $field) {
                // DB2 returns column names in uppercase; normalize to lowercase for consistency
                $result[strtolower($field->colname)] = strtolower($field->data_type_full);
            }
        } else {
            foreach ($fields as $field) {
                // pdo_ibm may return the DEFAULT value as a resource (LOB stream).
                $defaultVal = $field->col_default ?? null;
                if (is_resource($defaultVal)) {
                    $defaultVal = stream_get_contents($defaultVal) ?: '';
                }

                // DB2 returns column names in uppercase; normalize to lowercase for consistency
                $colname = strtolower($field->colname);
                $result[$colname] = (object) [
                    'Default' => trim((string) ($defaultVal ?? '')),
                    'Comment' => '',
                    'Field'   => $colname,
                    'Type'    => strtolower($field->data_type_full),
                    'Null'    => $field->nulls === 'Y' ? 'YES' : 'NO'
                ];
            }
        }

        return $result;
    }

    /**
     * Get the details list of keys for a table
     *
     * @param   string  $table  The name of the table
     * @return  array   An array of the column specification for the table
     */
    public function getTableKeys($table)
    {
        $tableSub = strtoupper($this->replacePrefix($table));

        $this->setQuery("
            SELECT
                CASE WHEN i.uniquerule = 'P' THEN 'PRIMARY' ELSE LOWER(i.indname) END AS Key_name,
                CASE WHEN i.uniquerule IN ('U', 'P') THEN 0 ELSE 1 END AS Non_unique,
                LOWER(ic.colname) AS Column_name,
                ic.colseq AS Seq_in_index,
                'BTREE' AS Index_type
            FROM syscat.indexes i
            JOIN syscat.indexcoluse ic ON i.indschema = ic.indschema AND i.indname = ic.indname
            WHERE i.tabname = " . $this->quote($tableSub) . "
            AND i.tabschema = CURRENT SCHEMA
            ORDER BY CASE WHEN i.uniquerule = 'P' THEN 0 ELSE 1 END, i.indname, ic.colseq
        ");

        $rows = $this->loadObjectList();

        // Group by key_name (lowercase due to ATTR_CASE = CASE_LOWER)
        // But SchemaManager expects uppercase property names, so convert
        $grouped = [];
        foreach ($rows as $row) {
            // Properties are lowercase due to ATTR_CASE, but SchemaManager expects uppercase
            // Convert to uppercase property names
            $fixedRow = (object)[
                'Key_name' => $row->key_name,
                'Non_unique' => $row->non_unique,
                'Column_name' => $row->column_name,
                'Seq_in_index' => $row->seq_in_index,
                'Index_type' => $row->index_type,
            ];

            $keyName = $row->key_name;
            if (!isset($grouped[$keyName])) {
                $grouped[$keyName] = [];
            }
            $grouped[$keyName][] = $fixedRow;
        }

        return $grouped;
    }

    /**
     * Gets all indexes for a table with their columns and properties
     *
     * @param   string  $table  The table name
     * @return  array   Array of index objects
     */
    public function getIndexes($table)
    {
        $tableSub = strtoupper($this->replacePrefix($table));

        $this->setQuery("
            SELECT
                LOWER(i.indname) AS index_name,
                CASE WHEN i.uniquerule = 'P' THEN 1 ELSE 0 END AS is_primary,
                CASE WHEN i.uniquerule IN ('U', 'P') THEN 1 ELSE 0 END AS is_unique,
                LOWER(ic.colname) AS column_name,
                ic.colseq
            FROM syscat.indexes i
            JOIN syscat.indexcoluse ic
                ON i.indschema = ic.indschema AND i.indname = ic.indname
            WHERE i.tabname = " . $this->quote($tableSub) . "
            AND i.tabschema = CURRENT SCHEMA
            ORDER BY i.indname, ic.colseq
        ");

        $rows = $this->loadObjectList();
        $indexes = [];

        foreach ($rows as $row) {
            $isPrimary = (int) $row->is_primary;
            $name = $isPrimary
                ? 'PRIMARY'
                : $row->index_name;  // Already lowercase from query

            if (!isset($indexes[$name])) {
                $indexes[$name] = (object) [
                    'name'    => $name,
                    'columns' => [],
                    'unique'  => (bool) $row->is_unique,
                    'primary' => (bool) $isPrimary,
                ];
            }

            $indexes[$name]->columns[] = $row->column_name;  // Already lowercase from query
        }

        return array_values($indexes);
    }

    /**
     * Returns whether or not the given table exists
     *
     * @param   string  $table  A table name (with or without prefix)
     * @return  bool
     */
    public function tableExists($table)
    {
        $table = strtoupper($this->replacePrefix($table));
        $tables = $this->getTableList();

        return in_array($table, array_map('strtoupper', $tables), true);
    }

    /**
     * Gets an array of all tables in the database
     *
     * @return  array
     */
    public function getTableList()
    {
        $this->setQuery(
            "SELECT tabname FROM syscat.tables"
            . " WHERE tabschema = CURRENT SCHEMA AND type = 'T'"
            . " ORDER BY tabname"
        );
        $tables = $this->loadColumn();
        // Normalize to lowercase for consistency with other drivers
        return array_map('strtolower', $tables);
    }

    /**
     * Locks a table in the database
     *
     * @param   string  $tableName  The name of the table to lock
     * @return  $this
     */
    public function lockTable($tableName)
    {
        $this->setQuery('LOCK TABLE ' . $this->quoteName($tableName) . ' IN EXCLUSIVE MODE');
        $this->execute();

        return $this;
    }

    /**
     * Renames a table in the database
     *
     * @param   string  $oldTable  The name of the table to be renamed
     * @param   string  $newTable  The new name for the table
     * @param   string  $backup    Table prefix (unused)
     * @param   string  $prefix    For the table (unused)
     * @return  $this
     * @throws  \RuntimeException  If the source table does not exist
     */
    public function renameTable($oldTable, $newTable, $backup = null, $prefix = null)
    {
        $oldTable = strtoupper($this->replacePrefix($oldTable));
        $newTable = strtoupper($this->replacePrefix($newTable));

        if (!$this->tableExists($oldTable)) {
            throw new \RuntimeException('Table not found in DB2 database.');
        }

        $this->setQuery('RENAME TABLE ' . $this->quoteName($oldTable) . ' TO ' . $this->quoteName($newTable));
        $this->execute();

        return $this;
    }

    /**
     * Selects a database for use
     *
     * DB2 doesn't support database switching; each connection is to a specific database.
     * You can change the current schema with SET SCHEMA.
     *
     * @param   string  $database  The name of the database (schema) to select
     * @return  bool
     */
    public function select($database)
    {
        try {
            $this->setQuery('SET SCHEMA ' . $this->quoteName(strtoupper($database)));
            $this->execute();
            return true;
        } catch (\Exception $e) {
            return false;
        }
    }

    /**
     * Gets the database engine of the given table
     *
     * DB2 doesn't have storage engines like MySQL
     *
     * @param   string       $table  The table for which to retrieve the engine type
     * @return  string|bool
     */
    public function getEngine($table)
    {
        return 'DB2';
    }


    /**
     * Gets the database character set of the given table
     *
     * DB2 uses database codeset
     *
     * @param   string       $table  The table for which to retrieve the character set (ignored)
     * @param   string       $field  The field to check (ignored)
     * @return  string|bool
     */
    public function getCharacterSet($table, $field = null)
    {
        $this->setQuery("SELECT CODEPAGE FROM SYSCAT.DATATYPES WHERE TYPENAME = 'VARCHAR'");
        try {
            $result = $this->loadResult();
            return $result ?: false;
        } catch (\Exception $e) {
            return false;
        }
    }

    /**
     * Converts a table to the specified character set
     *
     * DB2 handles encoding at database level, not per-table
     *
     * @param   string       $table    The table to convert (ignored)
     * @param   string       $charset  The character set (ignored)
     * @param   string|null  $collate  Optional collation (ignored)
     * @return  bool
     */
    public function convertToCharset($table, $charset, $collate = null)
    {
        // DB2 doesn't support per-table character sets
        return true;
    }

    /**
     * Gets the auto-increment value for the given table
     *
     * DB2 uses identity columns or sequences.
     * This attempts to find a sequence named {table}_SEQ or identity column.
     *
     * @param   string    $table  The table for which to retrieve the value
     * @return  int|bool
     */
    public function getAutoIncrement($table)
    {
        $table = strtoupper($this->replacePrefix($table));

        // Find the identity column
        $this->setQuery("
            SELECT CAST(colname AS VARCHAR(128))
            FROM syscat.columns
            WHERE tabname = " . $this->quote($table) . "
            AND identity = 'Y'
            FETCH FIRST 1 ROW ONLY
        ");
        $identityCol = $this->loadResult();

        if ($identityCol) {
            // Query the maximum value from the table
            // This is the most reliable way to get the next auto-increment value
            $this->setQuery(
                "SELECT MAX(" . $this->quoteName($identityCol) . ") " .
                "FROM " . $this->quoteName($table)
            );

            try {
                $maxValue = $this->loadResult();
                if ($maxValue !== null) {
                    return (int) $maxValue + 1;
                }
            } catch (\Exception $e) {
                // Table might be empty or inaccessible
            }

            // If table is empty, return 1 (default start value)
            return 1;
        }

        // Fallback: try to find a manually created sequence for this table
        $seqNames = [
            $table . '_SEQ',
            $table . '_ID_SEQ',
        ];

        foreach ($seqNames as $seqName) {
            $this->setQuery(
                "SELECT NEXTCACHEFIRSTVALUE FROM syscat.sequences"
                . " WHERE seqname = " . $this->quote($seqName)
            );
            try {
                $result = $this->loadResult();
                if ($result !== null) {
                    return (int) $result;
                }
            } catch (\Exception $e) {
                // Continue to next
            }
        }

        return false;
    }

    /**
     * Sets the auto-increment starting value for the given table
     *
     * DB2 uses sequences; this modifies the sequence if found
     *
     * @param   string  $table  The table name
     * @param   int     $value  The auto-increment starting value
     * @return  bool
     */
    public function setAutoIncrement($table, $value): bool
    {
        $table = strtoupper($this->replacePrefix($table));
        $value = (int) $value;

        // DB2 normalizes 0 to 1 - if caller wants next insert to get ID=1, pass 0 or 1
        if ($value == 0) {
            $value = 1;
        }

        // Find the identity column and reset it using ALTER TABLE
        $identityCol = $this->findIdentityColumn($table);
        if ($identityCol) {
            $this->setQuery(
                'ALTER TABLE ' . $this->quoteName($table)
                . ' ALTER COLUMN ' . $this->quoteName($identityCol)
                . ' RESTART WITH ' . $value
            );
            try {
                $this->execute();
                return true;
            } catch (\Exception $e) {
                // Failed to reset identity column
                return false;
            }
        }

        // No identity column found - try sequences as fallback
        $seqNames = [
            $table . '_SEQ',
            $table . '_ID_SEQ',
        ];

        foreach ($seqNames as $seqName) {
            if ($this->sequenceExists($seqName)) {
                $this->setQuery("ALTER SEQUENCE " . $this->quoteName($seqName) . " RESTART WITH {$value}");
                try {
                    $this->execute();
                    return true;
                } catch (\Exception $e) {
                    // Continue
                }
            }
        }

        return false;
    }

    /**
     * Get the allowed values for an ENUM column
     *
     * @note    NO-OP: DB2 doesn't have native ENUM type.
     *          Use CHECK constraints instead.
     *
     * @param   string  $table   The table name
     * @param   string  $column  The column name
     * @return  array   Always returns empty array
     */
    public function getEnumValues($table, $column)
    {
        return [];
    }

    /**
     * Add a value to an ENUM column
     *
     * @note    NO-OP: DB2 doesn't have native ENUM type
     *
     * @param   string  $table   The table name
     * @param   string  $column  The column name
     * @param   string  $value   The value to add
     * @return  bool    Always returns true
     */
    public function addEnumValue($table, $column, $value)
    {
        return true;
    }

    /**
     * Remove a value from an ENUM column
     *
     * @note    NO-OP: DB2 doesn't have native ENUM type
     *
     * @param   string  $table   The table name
     * @param   string  $column  The column name
     * @param   string  $value   The value to remove
     * @return  bool    Always returns true
     */
    public function removeEnumValue($table, $column, $value)
    {
        return true;
    }

    /**
     * Creates or replaces a database view
     *
     * @param   string  $name       The view name (with or without prefix)
     * @param   string  $selectSql  The SELECT statement for the view
     * @param   array   $options    MySQL-specific options (ignored on DB2)
     * @return  bool
     */
    public function createOrReplaceView($name, $selectSql, array $options = []): bool
    {
        $viewName = strtoupper($this->replacePrefix($name));
        $selectSql = $this->replacePrefix($selectSql);

        // DB2 uses CREATE OR REPLACE VIEW
        $sql = 'CREATE OR REPLACE VIEW ' . $this->quoteName($viewName) . ' AS ' . $selectSql;
        $this->setQuery($sql);
        $this->execute();

        return true;
    }

    /**
     * Drops a database view
     *
     * @param   string  $name      The view name
     * @param   bool    $ifExists  Whether to use IF EXISTS clause
     * @return  bool
     */
    public function dropView($name, $ifExists = true): bool
    {
        $viewName = strtoupper($this->replacePrefix($name));

        if ($ifExists && !$this->viewExists($name)) {
            return true;
        }

        $sql = 'DROP VIEW ' . $this->quoteName($viewName);
        $this->setQuery($sql);
        $this->execute();

        return true;
    }

    /**
     * Checks if a view exists in the database
     *
     * @param   string  $name  The view name
     * @return  bool
     */
    public function viewExists($name): bool
    {
        $viewName = strtoupper($this->replacePrefix($name));
        $this->setQuery(
            "SELECT COUNT(*) FROM syscat.views"
            . " WHERE viewname = " . $this->quote($viewName)
            . " AND viewschema = CURRENT SCHEMA"
        );

        return (bool) $this->loadResult();
    }

    /**
     * Returns a list of all views in the current schema
     *
     * @return  array  Array of view names
     */
    public function getViews(): array
    {
        $this->setQuery("SELECT viewname FROM syscat.views WHERE viewschema = CURRENT SCHEMA ORDER BY viewname");
        return $this->loadColumn() ?: [];
    }

    /**
     * Returns a list of all database names (schemas) the user can access
     *
     * @return  array  Array of schema names
     */
    public function getDatabaseNames(): array
    {
        $this->setQuery("SELECT schemaname FROM syscat.schemata ORDER BY schemaname");
        return $this->loadColumn() ?: [];
    }

    /**
     * Returns a list of all sequences in the current schema
     *
     * @return  array  Array of SequenceInfo objects
     */
    public function getSequences(): array
    {
        $this->setQuery("
            SELECT
                seqname AS name,
                minvalue,
                maxvalue,
                increment,
                cache AS current_value,
                CASE WHEN cycle = 'Y' THEN 1 ELSE 0 END AS cycle
            FROM syscat.sequences
            WHERE seqschema = CURRENT SCHEMA
            ORDER BY seqname
        ");

        $results = $this->loadObjectList();
        $sequences = [];

        if ($results) {
            foreach ($results as $row) {
                $sequences[] = new \Hubzero\Database\Schema\SequenceInfo([
                    'name'        => strtolower($row->name),  // Normalize to lowercase
                    'start_value' => 1,  // DB2 doesn't easily expose original start value
                    'min_value'   => (int) $row->minvalue,
                    'max_value'   => $row->maxvalue,
                    'increment'   => (int) $row->increment,
                    'cycle'       => (bool) $row->cycle,
                    'current_value' => (int) $row->current_value,
                ]);
            }
        }

        return $sequences;
    }

    /**
     * Creates a new sequence
     *
     * @param   string  $name       The sequence name
     * @param   int     $start      Starting value (default: 1)
     * @param   int     $increment  Increment value (default: 1)
     * @param   array   $options    Additional options (min, max, cycle, cache)
     * @return  bool
     */
    public function createSequence($name, $start = 1, $increment = 1, array $options = []): bool
    {
        $seqName = strtoupper($name);

        $sql = "CREATE SEQUENCE " . $this->quoteName($seqName);
        $sql .= " START WITH " . (int) $start;
        $sql .= " INCREMENT BY " . (int) $increment;

        if (isset($options['min'])) {
            $sql .= " MINVALUE " . (int) $options['min'];
        } else {
            $sql .= " NO MINVALUE";
        }

        if (isset($options['max'])) {
            $sql .= " MAXVALUE " . (int) $options['max'];
        } else {
            $sql .= " NO MAXVALUE";
        }

        if (isset($options['cycle']) && $options['cycle']) {
            $sql .= " CYCLE";
        } else {
            $sql .= " NO CYCLE";
        }

        if (isset($options['cache'])) {
            $sql .= " CACHE " . (int) $options['cache'];
        }

        $this->setQuery($sql);
        $this->execute();

        return true;
    }

    /**
     * Drops a sequence
     *
     * @param   string  $name      The sequence name
     * @param   bool    $ifExists  Whether to check existence first
     * @return  bool
     */
    public function dropSequence($name, $ifExists = true): bool
    {
        $seqName = strtoupper($name);

        if ($ifExists && !$this->sequenceExists($seqName)) {
            return true;
        }

        $this->setQuery("DROP SEQUENCE " . $this->quoteName($seqName));
        $this->execute();

        return true;
    }

    /**
     * Checks if a sequence exists
     *
     * @param   string  $name  The sequence name
     * @return  bool
     */
    public function sequenceExists($name): bool
    {
        $seqName = strtoupper($name);
        $this->setQuery(
            "SELECT COUNT(*) FROM syscat.sequences"
            . " WHERE seqname = " . $this->quote($seqName)
            . " AND seqschema = CURRENT SCHEMA"
        );
        return (bool) $this->loadResult();
    }

    /**
     * Gets the next value from a sequence
     *
     * @param   string  $name  The sequence name
     * @return  int
     */
    public function nextSequenceValue($name): int
    {
        $seqName = strtoupper($name);
        $this->setQuery("SELECT NEXT VALUE FOR " . $this->quoteName($seqName) . " FROM SYSIBM.SYSDUMMY1");
        return (int) $this->loadResult();
    }

    /**
     * Gets the current value of a sequence
     *
     * Note: DB2's PREVIOUS VALUE requires NEXT VALUE to have been called in the current session
     *
     * @param   string  $name  The sequence name
     * @return  int
     */
    public function currentSequenceValue($name): int
    {
        $seqName = strtoupper($name);
        $this->setQuery("SELECT PREVIOUS VALUE FOR " . $this->quoteName($seqName) . " FROM SYSIBM.SYSDUMMY1");
        return (int) $this->loadResult();
    }

    /**
     * Gets the version of the database connector
     *
     * @return  string
     */
    public function getVersion()
    {
        if ($this->db2Version === null) {
            $this->setQuery("SELECT service_level FROM TABLE(SYSPROC.ENV_GET_INST_INFO())");
            try {
                $this->db2Version = $this->loadResult();
            } catch (\Exception $e) {
                // Fall back to simpler version query
                $this->setQuery("SELECT GETVARIABLE('SYSIBM.VERSION') FROM SYSIBM.SYSDUMMY1");
                try {
                    $this->db2Version = $this->loadResult() ?: 'Unknown';
                } catch (\Exception $e) {
                    $this->db2Version = 'Unknown';
                }
            }
        }

        return $this->db2Version;
    }

    /**
     * Gets the full version string
     *
     * @return  string|null
     */
    public function getFullVersion()
    {
        $this->setQuery("SELECT service_level || ' - ' || fixpack_num FROM TABLE(SYSPROC.ENV_GET_INST_INFO())");
        try {
            return $this->loadResult();
        } catch (\Exception $e) {
            return $this->getVersion();
        }
    }

    /**
     * Truncate a table
     *
     * @param   string  $table   The table to truncate
     * @param   int     $nextId  The next auto-increment value (ignored on DB2)
     * @return  $this
     */
    public function truncateTable($table, int $nextId = 1)
    {
        $table = strtoupper($this->replacePrefix($table));

        // DB2 requires TRUNCATE to be the first statement in a unit of work (SQL0428N).
        // Issue a raw COMMIT via exec() to end any pending implicit transaction.
        // PDO::commit() only works with explicit beginTransaction(); raw SQL works always.
        if ($this->transactionDepth === 0) {
            try {
                $this->connection->exec('COMMIT');
            } catch (\Exception $e) {
                // Nothing to commit — ignore
            }
        }

        $this->setQuery('TRUNCATE TABLE ' . $this->quoteName($table) . ' IMMEDIATE');
        $this->execute();

        // DB2's TRUNCATE does not reset identity columns.
        // Find and reset any identity column to the specified nextId.
        $identityCol = $this->findIdentityColumn($table);
        if ($identityCol) {
            $this->setQuery(
                'ALTER TABLE ' . $this->quoteName($table)
                . ' ALTER COLUMN ' . $this->quoteName($identityCol)
                . ' RESTART WITH ' . $nextId
            );
            $this->execute();
        }

        return $this;
    }

    /**
     * Drops a table from the database
     *
     * Drop a table from the database.
     *
     * DB2's DROP TABLE IF EXISTS can still throw SQL0204N in some edge
     * cases, so this method catches and ignores "undefined name" errors
     * when $ifExists is true.
     *
     * @param   string   $tableName  The name of the database table to drop
     * @param   boolean  $ifExists   Optionally specify that the table must exist before it is dropped
     * @return  $this
     */
    public function dropTable($tableName, $ifExists = true)
    {
        $tableName = $this->replacePrefix($tableName);
        $grammar = $this->getSchemaGrammar();

        try {
            $this->setQuery($grammar->compileDrop($tableName, $ifExists))
                 ->execute();
        } catch (\Exception $e) {
            if (
                $ifExists
                && (strpos($e->getMessage(), 'SQL0204N') !== false
                    || strpos($e->getMessage(), '42704') !== false)
            ) {
                return $this;
            }
            throw $e;
        }

        return $this;
    }

    /**
     * Find the identity column for a table
     *
     * Queries syscat.columns to find the auto-increment (identity) column
     *
     * @param   string  $table  The uppercase table name (without prefix)
     * @return  string|null  The identity column name (uppercase) or null if none
     */
    protected function findIdentityColumn(string $table): ?string
    {
        $this->setQuery("
            SELECT colname
            FROM syscat.columns
            WHERE tabname = " . $this->quote($table) . "
            AND identity = 'Y'
            ORDER BY colno
            FETCH FIRST 1 ROW ONLY
        ");

        $result = $this->loadResult();
        return $result ? (string) $result : null;
    }

    /**
     * Get database server version information
     *
     * @return  array  Array with standardized keys
     */
    public function getServerInfo()
    {
        $version = $this->getVersion();
        $fullVersion = $this->getFullVersion();

        return [
            'version'        => $version,
            'driver_version' => $version,
            'db2_version'    => $version,
            'full_version'   => $fullVersion,
            'comment'        => 'IBM DB2',
        ];
    }


    /**
     * Test to see if the DB2 connector is available
     *
     * @return  bool
     */
    public static function test()
    {
        if (!class_exists('\PDO')) {
            return false;
        }

        $drivers = \PDO::getAvailableDrivers();
        return in_array('ibm', $drivers) || in_array('odbc', $drivers);
    }

    // =========================================================================
    // Transaction Support with Savepoints
    // =========================================================================

    /**
     * Initializes a transaction
     *
     * @return  void
     */
    public function transactionStart()
    {
        if ($this->transactionDepth == 0) {
            // DB2 starts implicit transactions
            // We just need to turn off auto-commit
            $this->connection->setAttribute(\PDO::ATTR_AUTOCOMMIT, 0);
        } else {
            $this->setQuery('SAVEPOINT SP_' . $this->transactionDepth . ' ON ROLLBACK RETAIN CURSORS');
            $this->execute();
        }

        $this->transactionDepth++;
    }

    /**
     * Commits a transaction
     *
     * @return  void
     */
    public function transactionCommit()
    {
        if ($this->transactionDepth <= 0) {
            return;
        }

        $this->transactionDepth--;

        if ($this->transactionDepth == 0) {
            $this->setQuery('COMMIT');
            $this->execute();
            $this->connection->setAttribute(\PDO::ATTR_AUTOCOMMIT, 1);
        } else {
            $this->setQuery('RELEASE SAVEPOINT SP_' . $this->transactionDepth);
            $this->execute();
        }
    }

    /**
     * Rolls back a transaction
     *
     * @return  void
     */
    public function transactionRollback()
    {
        if ($this->transactionDepth <= 0) {
            return;
        }

        $this->transactionDepth--;

        if ($this->transactionDepth == 0) {
            $this->setQuery('ROLLBACK');
            $this->execute();
            $this->connection->setAttribute(\PDO::ATTR_AUTOCOMMIT, 1);
        } else {
            $this->setQuery('ROLLBACK TO SAVEPOINT SP_' . $this->transactionDepth);
            $this->execute();
        }
    }

    /**
     * Determines if the connection to the server is active
     *
     * @return  bool
     */
    public function connected()
    {
        if (!is_object($this->connection)) {
            return false;
        }

        try {
            $this->connection->query('SELECT 1 FROM SYSIBM.SYSDUMMY1');
            return true;
        } catch (\PDOException $e) {
            return false;
        }
    }

    // =========================================================================
    // SQL Compatibility Helpers - DB2 Implementations
    // =========================================================================


    /**
     * Returns the SQL keyword for INSERT with ignore duplicates
     *
     * DB2 doesn't have INSERT IGNORE; use error handling or MERGE
     *
     * @return  string
     */
    public function sqlInsertIgnore(): string
    {
        // DB2 doesn't have INSERT IGNORE syntax
        return 'INSERT INTO';
    }

    /**
     * Returns the SQL keyword for REPLACE (upsert)
     *
     * DB2 uses MERGE statement for upsert operations
     *
     * @return  string
     */
    public function sqlReplace(): string
    {
        // DB2 uses MERGE instead of REPLACE
        return 'INSERT INTO';
    }

    /**
     * Returns the suffix for INSERT IGNORE statements
     *
     * DB2 doesn't have a simple suffix; requires error handling
     *
     * @return  string
     */
    public function sqlInsertIgnoreSuffix(): string
    {
        return '';
    }

    /**
     * Returns the suffix for REPLACE (upsert) statements
     *
     * DB2 uses MERGE statement instead
     *
     * @param   string  $pkColumn       The primary key column
     * @param   array   $updateColumns  Columns to update
     * @return  string
     */
    public function sqlReplaceSuffix(string $pkColumn, array $updateColumns): string
    {
        return '';
    }

    /**
     * Returns the SQL for regular expression matching
     *
     * DB2 uses REGEXP_LIKE() function (DB2 11.1+)
     *
     * @param   string  $column   The column to match
     * @param   string  $pattern  The regex pattern
     * @param   bool    $not      Whether to negate the match
     * @return  string
     */
    public function sqlRegexp(string $column, string $pattern, bool $not = false): string
    {
        $negation = $not ? 'NOT ' : '';
        return $negation . 'REGEXP_LIKE(' . $column . ', ' . $this->quote($pattern) . ')';
    }

    /**
     * Returns the SQL for date subtraction
     *
     * DB2 uses date arithmetic with intervals
     *
     * @param   string  $date   The date column or value
     * @param   int     $value  The interval value
     * @param   string  $unit   The interval unit
     * @return  string
     */
    public function sqlDateSub(string $date, int $value, string $unit = 'DAY'): string
    {
        $unit = strtoupper($unit);

        // DB2 interval syntax
        switch ($unit) {
            case 'DAY':
            case 'DAYS':
                return "({$date} - {$value} DAYS)";
            case 'MONTH':
            case 'MONTHS':
                return "({$date} - {$value} MONTHS)";
            case 'YEAR':
            case 'YEARS':
                return "({$date} - {$value} YEARS)";
            case 'HOUR':
            case 'HOURS':
                return "({$date} - {$value} HOURS)";
            case 'MINUTE':
            case 'MINUTES':
                return "({$date} - {$value} MINUTES)";
            case 'SECOND':
            case 'SECONDS':
                return "({$date} - {$value} SECONDS)";
            default:
                return "({$date} - {$value} DAYS)";
        }
    }

    /**
     * Returns the SQL for date addition
     *
     * @param   string  $date   The date column or value
     * @param   int     $value  The interval value
     * @param   string  $unit   The interval unit
     * @return  string
     */
    public function sqlDateAdd(string $date, int $value, string $unit = 'DAY'): string
    {
        $unit = strtoupper($unit);

        switch ($unit) {
            case 'DAY':
            case 'DAYS':
                return "({$date} + {$value} DAYS)";
            case 'MONTH':
            case 'MONTHS':
                return "({$date} + {$value} MONTHS)";
            case 'YEAR':
            case 'YEARS':
                return "({$date} + {$value} YEARS)";
            case 'HOUR':
            case 'HOURS':
                return "({$date} + {$value} HOURS)";
            case 'MINUTE':
            case 'MINUTES':
                return "({$date} + {$value} MINUTES)";
            case 'SECOND':
            case 'SECONDS':
                return "({$date} + {$value} SECONDS)";
            default:
                return "({$date} + {$value} DAYS)";
        }
    }

    /**
     * Returns the SQL for date formatting
     *
     * DB2 uses VARCHAR_FORMAT(date, format)
     *
     * @param   string  $date    The date column or value
     * @param   string  $format  The format string (MySQL format codes)
     * @return  string
     */
    public function sqlDateFormat(string $date, string $format): string
    {
        // Convert MySQL format codes to DB2 VARCHAR_FORMAT format
        $conversions = [
            '%Y' => 'YYYY',
            '%y' => 'YY',
            '%m' => 'MM',
            '%c' => 'M',
            '%d' => 'DD',
            '%e' => 'D',
            '%H' => 'HH24',
            '%h' => 'HH12',
            '%i' => 'MI',
            '%s' => 'SS',
            '%p' => 'AM',
            '%M' => 'Month',
            '%b' => 'Mon',
            '%W' => 'Day',
            '%a' => 'Dy',
            '%j' => 'DDD',
        ];

        $db2Format = str_replace(array_keys($conversions), array_values($conversions), $format);

        return 'VARCHAR_FORMAT(' . $date . ', ' . $this->quote($db2Format) . ')';
    }

    /**
     * Returns the SQL for extracting year from a date
     *
     * @param   string  $date  The date column or value
     * @return  string
     */
    public function sqlYear(string $date): string
    {
        return 'YEAR(' . $date . ')';
    }

    /**
     * Returns the SQL for extracting month from a date
     *
     * @param   string  $date  The date column or value
     * @return  string
     */
    public function sqlMonth(string $date): string
    {
        return 'MONTH(' . $date . ')';
    }

    /**
     * Returns the SQL for converting a date to Unix timestamp
     *
     * DB2 uses calculation from epoch
     *
     * @param   string  $date  The date column or value
     * @return  string
     */
    public function sqlUnixTimestamp(string $date): string
    {
        return "(DAYS({$date}) - DAYS('1970-01-01')) * 86400 + MIDNIGHT_SECONDS({$date})";
    }


    /**
     * Returns the SQL for extracting a substring based on a delimiter
     *
     * DB2 uses combination of LOCATE and SUBSTR
     *
     * @param   string  $str    The string expression
     * @param   string  $delim  The delimiter
     * @param   int     $count  The occurrence count
     * @return  string
     */
    public function sqlSubstringIndex(string $str, string $delim, int $count): string
    {
        $quotedDelim = $this->quote($delim);

        if ($count > 0) {
            // Get everything before the nth delimiter
            // Using recursive CTE or custom function would be needed for full support
            // Simplified version for count = 1
            if ($count == 1) {
                return "CASE WHEN LOCATE({$quotedDelim}, {$str}) > 0"
                    . " THEN SUBSTR({$str}, 1, LOCATE({$quotedDelim}, {$str}) - 1)"
                    . " ELSE {$str} END";
            }
            return $str; // Simplified
        } elseif ($count < 0) {
            // Get everything after the nth delimiter from the right
            // Simplified version for count = -1
            if ($count == -1) {
                return "CASE WHEN LOCATE({$quotedDelim}, {$str}) > 0"
                    . " THEN SUBSTR({$str}, LENGTH({$str})"
                    . " - LOCATE({$quotedDelim}, REVERSE({$str})) + 2)"
                    . " ELSE {$str} END";
            }
            return $str; // Simplified
        }

        return "''";
    }

    /**
     * Returns the SQL for concatenating strings
     *
     * DB2 uses || operator or CONCAT()
     *
     * @param   array  $strings  Array of strings to concatenate
     * @return  string
     */
    public function sqlConcat(array $strings): string
    {
        return '(' . implode(' || ', $strings) . ')';
    }

    /**
     * Returns the SQL for concatenating strings with a separator
     *
     * DB2 doesn't have CONCAT_WS; we build it manually
     *
     * @param   string  $separator  The separator string
     * @param   array   $strings    Array of strings to concatenate
     * @return  string
     */
    public function sqlConcatWs(string $separator, array $strings): string
    {
        $quotedSep = $this->quote($separator);
        $parts = [];

        foreach ($strings as $i => $str) {
            if ($i > 0) {
                $parts[] = $quotedSep;
            }
            $parts[] = $str;
        }

        return '(' . implode(' || ', $parts) . ')';
    }


    // =========================================================================
    // Column Operations
    // =========================================================================

    /**
     * Add a column to a table
     *
     * @param   string  $table       Table name
     * @param   string  $column      Column name
     * @param   string  $definition  Column definition
     * @param   string  $comment     Optional column comment
     * @return  bool
     */
    public function addColumn(string $table, string $column, string $definition, string $comment = ''): bool
    {
        $table = strtoupper($this->replacePrefix($table));
        $column = strtoupper($column);

        if (!$this->tableExists($table)) {
            return false;
        }

        if ($this->tableHasField($table, $column)) {
            return true;
        }

        $query = 'ALTER TABLE ' . $this->quoteName($table)
            . ' ADD COLUMN ' . $this->quoteName($column)
            . ' ' . $definition;

        $this->setQuery($query);
        $result = (bool) $this->execute();

        if ($result && $comment) {
            $this->setQuery(
                'COMMENT ON COLUMN ' . $this->quoteName($table) . '.' . $this->quoteName($column) .
                ' IS ' . $this->quote($comment)
            );
            try {
                $this->execute();
            } catch (\Exception $e) {
                // Comments may fail on some DB2 configurations
            }
        }

        return $result;
    }

    /**
     * Drop a column from a table
     *
     * @param   string  $table   Table name
     * @param   string  $column  Column name
     * @return  bool
     */
    public function dropColumn(string $table, string $column): bool
    {
        $table = strtoupper($this->replacePrefix($table));
        $column = strtoupper($column);

        if (!$this->tableExists($table)) {
            return true;
        }

        if (!$this->tableHasField($table, $column)) {
            return true;
        }

        $query = 'ALTER TABLE ' . $this->quoteName($table) . ' DROP COLUMN ' . $this->quoteName($column);
        $this->setQuery($query);
        return (bool) $this->execute();
    }

    /**
     * Modify a column definition
     *
     * @param   string  $table       Table name
     * @param   string  $column      Column name
     * @param   string  $definition  New column definition
     * @param   string  $comment     Optional column comment
     * @return  bool
     */
    public function modifyColumn(string $table, string $column, string $definition, string $comment = ''): bool
    {
        $table = strtoupper($this->replacePrefix($table));
        $column = strtoupper($column);

        if (!$this->tableExists($table)) {
            return false;
        }

        if (!$this->tableHasField($table, $column)) {
            return false;
        }

        $query = 'ALTER TABLE ' . $this->quoteName($table)
            . ' ALTER COLUMN ' . $this->quoteName($column)
            . ' SET DATA TYPE ' . $definition;

        $this->setQuery($query);
        $result = (bool) $this->execute();

        if ($result && $comment) {
            $this->setQuery(
                'COMMENT ON COLUMN ' . $this->quoteName($table) . '.' . $this->quoteName($column) .
                ' IS ' . $this->quote($comment)
            );
            try {
                $this->execute();
            } catch (\Exception $e) {
                // Comments may fail
            }
        }

        return $result;
    }

    /**
     * Change a column name and/or definition
     *
     * @param   string  $table       Table name
     * @param   string  $oldColumn   Current column name
     * @param   string  $newColumn   New column name
     * @param   string  $definition  New column definition
     * @param   string  $comment     Optional column comment
     * @return  bool
     */
    public function changeColumn(
        string $table,
        string $oldColumn,
        string $newColumn,
        string $definition,
        string $comment = ''
    ): bool {
        $table = strtoupper($this->replacePrefix($table));
        $oldColumn = strtoupper($oldColumn);
        $newColumn = strtoupper($newColumn);

        if (!$this->tableExists($table)) {
            return false;
        }

        if (!$this->tableHasField($table, $oldColumn)) {
            return false;
        }

        // Rename first if needed
        if ($oldColumn !== $newColumn) {
            $this->setQuery(
                'ALTER TABLE ' . $this->quoteName($table) .
                ' RENAME COLUMN ' . $this->quoteName($oldColumn) . ' TO ' . $this->quoteName($newColumn)
            );
            $this->execute();
        }

        // Then modify
        return $this->modifyColumn($table, $newColumn, $definition, $comment);
    }

    /**
     * Modify a column definition and move it after a specific column
     *
     * DB2 doesn't support column reordering
     *
     * @param   string  $table        Table name
     * @param   string  $column       Column name
     * @param   string  $definition   Column definition
     * @param   string  $afterColumn  Column to position after (ignored)
     * @param   string  $comment      Optional column comment
     * @return  bool
     */
    public function modifyColumnAfter(
        string $table,
        string $column,
        string $definition,
        string $afterColumn,
        string $comment = ''
    ): bool {
        return $this->modifyColumn($table, $column, $definition, $comment);
    }

    /**
     * Modify a column definition and move it before a specific column
     *
     * DB2 doesn't support column reordering
     *
     * @param   string  $table         Table name
     * @param   string  $column        Column name
     * @param   string  $definition    Column definition
     * @param   string  $beforeColumn  Column to position before (ignored)
     * @param   string  $comment       Optional column comment
     * @return  bool
     */
    public function modifyColumnBefore(
        string $table,
        string $column,
        string $definition,
        string $beforeColumn,
        string $comment = ''
    ): bool {
        return $this->modifyColumn($table, $column, $definition, $comment);
    }

    /**
     * Modify a column definition and move it to the first position
     *
     * DB2 doesn't support column reordering
     *
     * @param   string  $table       Table name
     * @param   string  $column      Column name
     * @param   string  $definition  Column definition
     * @param   string  $comment     Optional column comment
     * @return  bool
     */
    public function modifyColumnFirst(string $table, string $column, string $definition, string $comment = ''): bool
    {
        return $this->modifyColumn($table, $column, $definition, $comment);
    }

    /**
     * Add a column after a specific column
     *
     * DB2 doesn't support column positioning
     *
     * @param   string  $table        Table name
     * @param   string  $column       Column name
     * @param   string  $definition   Column definition
     * @param   string  $afterColumn  Column to add after (ignored)
     * @param   string  $comment      Optional column comment
     * @return  bool
     */
    public function addColumnAfter(
        string $table,
        string $column,
        string $definition,
        string $afterColumn,
        string $comment = ''
    ): bool {
        return $this->addColumn($table, $column, $definition, $comment);
    }

    /**
     * Add a column before a specific column
     *
     * DB2 doesn't support column positioning
     *
     * @param   string  $table         Table name
     * @param   string  $column        Column name
     * @param   string  $definition    Column definition
     * @param   string  $beforeColumn  Column to add before (ignored)
     * @param   string  $comment       Optional column comment
     * @return  bool
     */
    public function addColumnBefore(
        string $table,
        string $column,
        string $definition,
        string $beforeColumn,
        string $comment = ''
    ): bool {
        return $this->addColumn($table, $column, $definition, $comment);
    }

    /**
     * Add a column at the beginning of a table
     *
     * DB2 doesn't support column positioning
     *
     * @param   string  $table       Table name
     * @param   string  $column      Column name
     * @param   string  $definition  Column definition
     * @param   string  $comment     Optional column comment
     * @return  bool
     */
    public function addColumnFirst(string $table, string $column, string $definition, string $comment = ''): bool
    {
        return $this->addColumn($table, $column, $definition, $comment);
    }

    /**
     * Add a column at the end of a table
     *
     * @param   string  $table       Table name
     * @param   string  $column      Column name
     * @param   string  $definition  Column definition
     * @param   string  $comment     Optional column comment
     * @return  bool
     */
    public function addColumnLast(string $table, string $column, string $definition, string $comment = ''): bool
    {
        return $this->addColumn($table, $column, $definition, $comment);
    }

    // =========================================================================
    // Index Operations
    // =========================================================================

    /**
     * Add an index to a table
     *
     * @param   string        $table    Table name
     * @param   string        $name     Index name
     * @param   string|array  $columns  Column name(s)
     * @param   bool          $unique   Whether this is a unique index
     * @return  bool
     */
    public function addIndex(string $table, string $name, $columns, bool $unique = false): bool
    {
        $table = strtoupper($this->replacePrefix($table));
        $name = strtoupper($name);

        if (!$this->tableExists($table)) {
            return false;
        }

        if (is_string($columns)) {
            $columns = [$columns];
        }

        $columnList = implode(', ', array_map(function ($col) {
            return $this->quoteName(strtoupper($col));
        }, $columns));

        $uniqueStr = $unique ? 'UNIQUE ' : '';

        $query = "CREATE {$uniqueStr}INDEX " . $this->quoteName($name) .
                 ' ON ' . $this->quoteName($table) . " ($columnList)";

        $this->setQuery($query);
        return (bool) $this->execute();
    }

    /**
     * Add a unique index to a table
     *
     * @param   string        $table    Table name
     * @param   string        $name     Index name
     * @param   string|array  $columns  Column name(s)
     * @return  bool
     */
    public function addUniqueIndex(string $table, string $name, $columns): bool
    {
        return $this->addIndex($table, $name, $columns, true);
    }

    /**
     * Drop an index from a table
     *
     * @param   string  $table  Table name (used for schema)
     * @param   string  $name   Index name
     * @return  bool
     */
    public function dropIndex(string $table, string $name): bool
    {
        $name = strtoupper($name);
        $query = 'DROP INDEX ' . $this->quoteName($name);
        $this->setQuery($query);

        try {
            return (bool) $this->execute();
        } catch (\Exception $e) {
            return false;
        }
    }

    /**
     * Add a FULLTEXT index to a table
     *
     * DB2 uses DB2 Text Search for full-text search
     *
     * @param   string        $table    Table name
     * @param   string        $name     Index name
     * @param   string|array  $columns  Column name(s)
     * @return  bool
     */
    public function addFulltextIndex(string $table, string $name, $columns): bool
    {
        // DB2 Text Search requires additional setup
        // This is a no-op as it requires administrative configuration
        return false;
    }

    /**
     * Drop the primary key from a table
     *
     * @param   string  $table  Table name
     * @return  bool
     */
    public function dropPrimaryKey(string $table): bool
    {
        $table = strtoupper($this->replacePrefix($table));

        if (!$this->tableExists($table)) {
            return false;
        }

        // Find the primary key constraint name
        $this->setQuery(
            "SELECT constname FROM syscat.tabconst"
            . " WHERE tabname = " . $this->quote($table)
            . " AND type = 'P' AND tabschema = CURRENT SCHEMA"
        );
        $constraintName = $this->loadResult();

        if (!$constraintName) {
            return true; // No primary key
        }

        $query = 'ALTER TABLE ' . $this->quoteName($table) . ' DROP PRIMARY KEY';
        $this->setQuery($query);
        return (bool) $this->execute();
    }

    /**
     * Add a primary key to a table
     *
     * @param   string        $table    Table name
     * @param   string|array  $columns  Column name(s)
     * @return  bool
     */
    public function addPrimaryKey(string $table, $columns): bool
    {
        $table = strtoupper($this->replacePrefix($table));

        if (!$this->tableExists($table)) {
            return false;
        }

        $columns = is_array($columns) ? $columns : [$columns];

        // DB2 requires primary key columns to be NOT NULL
        // First, ensure all columns are NOT NULL
        foreach ($columns as $column) {
            $quotedColumn = $this->quoteName(strtoupper($column));
            $quotedTable = $this->quoteName($table);

            // Get column info to check current type
            $columnInfo = $this->getTableColumns($table, false);
            if (!isset($columnInfo[strtolower($column)])) {
                return false;
            }

            $colInfo = $columnInfo[strtolower($column)];
            $type = $colInfo->Type ?? 'VARCHAR(255)';

            // Set column to NOT NULL if it isn't already
            if ($colInfo->Null !== 'NO') {
                $alterQuery = "ALTER TABLE $quotedTable ALTER COLUMN $quotedColumn SET NOT NULL";
                $this->setQuery($alterQuery);
                try {
                    $this->execute();
                } catch (\Exception $e) {
                    // If column contains NULLs, this will fail
                    return false;
                }
            }
        }

        $columnList = implode(', ', array_map(function ($col) {
            return $this->quoteName(strtoupper($col));
        }, $columns));

        $query = 'ALTER TABLE ' . $this->quoteName($table) . ' ADD PRIMARY KEY (' . $columnList . ')';
        $this->setQuery($query);
        return (bool) $this->execute();
    }

    /**
     * Add an auto-increment primary key column to a table
     *
     * DB2 uses IDENTITY columns for auto-increment behavior
     *
     * @param   string  $table      Table name
     * @param   string  $column     Column name
     * @param   bool    $first      Add as first column (ignored)
     * @param   bool    $useBigInt  Use BIGINT for large values
     * @return  bool
     */
    public function addAutoIncrementPrimaryKey(
        string $table,
        string $column = 'id',
        bool $first = false,
        bool $useBigInt = true
    ): bool {
        $table = strtoupper($this->replacePrefix($table));
        $column = strtoupper($column);

        if (!$this->tableExists($table)) {
            return false;
        }

        if ($this->tableHasField($table, $column)) {
            return true;
        }

        $type = $useBigInt ? 'BIGINT' : 'INTEGER';
        $quotedTable = $this->quoteName($table);
        $quotedColumn = $this->quoteName($column);

        // DB2 doesn't support adding IDENTITY property via ALTER TABLE ADD COLUMN
        // Use multi-step approach for all cases

        // 1. Add nullable integer column
        $query = "ALTER TABLE {$quotedTable} ADD COLUMN {$quotedColumn} {$type}";
        $this->setQuery($query);
        if (!$this->execute()) {
            return false;
        }

        // 2. Check if table has rows and populate if needed
        $this->setQuery("SELECT COUNT(*) FROM {$quotedTable}");
        $rowCount = (int) $this->loadResult();

        if ($rowCount > 0) {
            // Populate with sequential values
            if (!$this->populateSequentialValues($table, $column)) {
                return false;
            }
        } else {
            // Empty table: set default for future inserts
            // Note: We can't add IDENTITY after the fact in ALTER TABLE
            // Column will need explicit values or application-level sequence
        }

        // 3. Make column NOT NULL
        $query = "ALTER TABLE {$quotedTable} ALTER COLUMN {$quotedColumn} SET NOT NULL";
        $this->setQuery($query);
        $result = (bool) $this->execute();

        if ($result) {
            // Add primary key constraint
            $this->addPrimaryKey($table, $column);
        }

        return $result;
    }

    /**
     * Populate a column with sequential integer values
     *
     * @param   string       $table    Table name
     * @param   string       $column   Column name
     * @param   string|null  $orderBy  Optional column to order by
     * @return  bool
     */
    public function populateSequentialValues(string $table, string $column, ?string $orderBy = null): bool
    {
        $table = strtoupper($this->replacePrefix($table));
        $column = strtoupper($column);

        if (!$this->tableExists($table) || !$this->tableHasField($table, $column)) {
            return false;
        }

        $quotedTable = $this->quoteName($table);
        $quotedColumn = $this->quoteName($column);
        $orderClause = $orderBy ? $this->quoteName(strtoupper($orderBy)) : $quotedColumn;

        // Use MERGE with ROW_NUMBER()
        $query = "MERGE INTO {$quotedTable} t " .
                 "USING (SELECT RID_BIT(t2) AS rid, " .
                 "ROW_NUMBER() OVER (ORDER BY {$orderClause}) AS rn " .
                 "FROM {$quotedTable} t2) s " .
                 "ON (RID_BIT(t) = s.rid) " .
                 "WHEN MATCHED THEN UPDATE SET t.{$quotedColumn} = s.rn";

        $this->setQuery($query);
        return (bool) $this->execute();
    }

    /**
     * Gets the primary key of a table
     *
     * @param   string  $table  The table name
     * @return  string|bool
     */
    public function getPrimaryKey($table)
    {
        $table = strtoupper($this->replacePrefix($table));

        $this->setQuery("
            SELECT kc.colname
            FROM syscat.keycoluse kc
            JOIN syscat.tabconst tc ON kc.constname = tc.constname AND kc.tabschema = tc.tabschema
            WHERE tc.tabname = " . $this->quote($table) . "
            AND tc.type = 'P'
            AND tc.tabschema = CURRENT SCHEMA
            ORDER BY kc.colseq
        ");

        $result = $this->loadResult();
        // Lowercase the column name to match ORM conventions (ATTR_CASE only affects keys, not values)
        return $result ? strtolower($result) : false;
    }

    /**
     * Get primary key column names
     *
     * @param   string  $table  The table name
     * @return  array   Array of column names in the primary key
     */
    public function getPrimaryKeyColumns($table): array
    {
        $table = strtoupper($this->replacePrefix($table));

        $this->setQuery("
            SELECT kc.colname
            FROM syscat.keycoluse kc
            JOIN syscat.tabconst tc ON kc.constname = tc.constname AND kc.tabschema = tc.tabschema
            WHERE tc.tabname = " . $this->quote($table) . "
            AND tc.type = 'P'
            AND tc.tabschema = CURRENT SCHEMA
            ORDER BY kc.colseq
        ");

        $rows = $this->loadColumn();
        // Lowercase all column names to match ORM conventions (ATTR_CASE only affects keys, not values)
        return $rows ? array_map('strtolower', $rows) : [];
    }

    /**
     * Gets foreign key constraints for a table
     *
     * @param   string  $table  The table name
     * @return  array
     */
    public function getForeignKeys($table)
    {
        $table = strtoupper($this->replacePrefix($table));

        $sql = "SELECT
                    r.constname AS constraint_name,
                    kc.colname AS column_name,
                    r.reftabname AS foreign_table,
                    rkc.colname AS foreign_column,
                    r.deleterule AS delete_rule,
                    r.updaterule AS update_rule
                FROM syscat.references r
                JOIN syscat.keycoluse kc ON r.constname = kc.constname AND r.tabschema = kc.tabschema
                JOIN syscat.keycoluse rkc ON r.refkeyname = rkc.constname
                    AND r.reftabschema = rkc.tabschema AND kc.colseq = rkc.colseq
                WHERE r.tabname = " . $this->quote($table) . "
                AND r.tabschema = CURRENT SCHEMA
                ORDER BY r.constname, kc.colseq";

        $this->setQuery($sql);
        $rows = $this->loadObjectList();

        // Group by constraint name
        $foreignKeys = [];
        foreach ($rows as $row) {
            $name = $row->constraint_name;

            if (!isset($foreignKeys[$name])) {
                $foreignKeys[$name] = (object) [
                    'name'            => $name,
                    'columns'         => [],
                    'foreign_table'   => $row->foreign_table,
                    'foreign_columns' => [],
                    'on_update'       => $this->translateRule($row->update_rule),
                    'on_delete'       => $this->translateRule($row->delete_rule),
                ];
            }

            $foreignKeys[$name]->columns[] = $row->column_name;
            $foreignKeys[$name]->foreign_columns[] = $row->foreign_column;
        }

        return array_values($foreignKeys);
    }

    /**
     * Adds a foreign key constraint to a table
     *
     * @param   string        $table          The table to add the FK to
     * @param   string        $constraint     The constraint name
     * @param   string|array  $columns        The local column(s)
     * @param   string        $foreignTable   The referenced table
     * @param   string|array  $foreignColumns The referenced column(s)
     * @param   string        $onUpdate       ON UPDATE action (default NO ACTION)
     * @param   string        $onDelete       ON DELETE action (default NO ACTION)
     * @return  bool
     */
    public function addForeignKey(
        $table,
        $constraint,
        $columns,
        $foreignTable,
        $foreignColumns,
        $onUpdate = 'NO ACTION',
        $onDelete = 'NO ACTION'
    ) {
        $table        = strtoupper($this->replacePrefix($table));
        $foreignTable = strtoupper($this->replacePrefix($foreignTable));

        $columnList        = implode(', ', array_map([$this, 'quoteName'], (array) $columns));
        $foreignColumnList = implode(', ', array_map([$this, 'quoteName'], (array) $foreignColumns));

        $sql = 'ALTER TABLE ' . $this->quoteName($table)
            . ' ADD CONSTRAINT ' . $this->quoteName(strtoupper($constraint))
            . ' FOREIGN KEY (' . $columnList . ')'
            . ' REFERENCES ' . $this->quoteName($foreignTable) . ' (' . $foreignColumnList . ')'
            . ' ON UPDATE ' . strtoupper($onUpdate)
            . ' ON DELETE ' . strtoupper($onDelete);

        $this->setQuery($sql);

        try {
            $this->execute();
            return true;
        } catch (\Exception $e) {
            return false;
        }
    }

    /**
     * Drops a foreign key constraint from a table
     *
     * @param   string  $table       The table name
     * @param   string  $constraint  The constraint name to drop
     * @return  bool
     */
    public function dropForeignKey($table, $constraint)
    {
        $table = strtoupper($this->replacePrefix($table));

        $this->setQuery(
            'ALTER TABLE ' . $this->quoteName($table)
            . ' DROP FOREIGN KEY ' . $this->quoteName(strtoupper($constraint))
        );

        try {
            $this->execute();
            return true;
        } catch (\Exception $e) {
            return false;
        }
    }

    /**
     * Translate DB2 rule code to standard action
     *
     * @param   string  $rule  The DB2 rule code
     * @return  string
     */
    protected function translateRule($rule)
    {
        switch ($rule) {
            case 'A':
                return 'NO ACTION';
            case 'C':
                return 'CASCADE';
            case 'N':
                return 'SET NULL';
            case 'R':
                return 'RESTRICT';
            default:
                return 'NO ACTION';
        }
    }

    /**
     * Sets the connection to use UTF-8 character encoding
     *
     * DB2 uses database codeset
     *
     * @return  bool
     */
    public function setUTF()
    {
        // DB2 encoding is set at database level
        return true;
    }

    /**
     * Unlock tables
     *
     * DB2 releases locks automatically at commit/rollback
     *
     * @return  $this
     */
    public function unlockTables()
    {
        // DB2 releases locks at transaction end
        return $this;
    }

    /**
     * Set the storage engine for a table
     *
     * DB2 doesn't have storage engines
     *
     * @param   string  $table   Table name (ignored)
     * @param   string  $engine  Engine type (ignored)
     * @return  bool
     */
    public function setTableEngine(string $table, string $engine = 'MYISAM'): bool
    {
        return true;
    }

    /**
     * Set the character set and collation for a table
     *
     * DB2 handles encoding at database level
     *
     * @param   string  $table      Table name (ignored)
     * @param   string  $charset    Character set (ignored)
     * @param   string  $collation  Collation (ignored)
     * @return  bool
     */
    public function setTableCharset(
        string $table,
        string $charset = 'utf8',
        string $collation = 'utf8_general_ci'
    ): bool {
        return true;
    }

    // =========================================================================
    // Feature Detection Methods - DB2 Implementations
    // =========================================================================

    /**
     * Check if this database supports sequences
     *
     * @return  bool
     */
    public function supportsSequences(): bool
    {
        return true;
    }

    /**
     * Get the schema grammar instance for this driver
     *
     * @return  \Hubzero\Database\Schema\Grammar
     */
    public function getSchemaGrammar()
    {
        return new \Hubzero\Database\Schema\Grammars\Db2Grammar($this);
    }

    // =========================================================================
    // Feature Detection Methods
    // =========================================================================

    /**
     * Check if generated/computed columns are supported
     *
     * @return  bool  True - DB2 supports generated columns
     */
    public function supportsGeneratedColumns(): bool
    {
        return true;
    }

    /**
     * Check if JSON data type is supported
     *
     * @return  bool  True - DB2 11+ has JSON support
     */
    public function supportsJson(): bool
    {
        $version = $this->getVersion();
        return version_compare($version, '11.0', '>=');
    }

    /**
     * Check if window functions are supported
     *
     * @return  bool  True - DB2 supports window functions
     */
    public function supportsWindowFunctions(): bool
    {
        return true;
    }

    /**
     * Check if Common Table Expressions (WITH clause) are supported
     *
     * @return  bool  True - DB2 supports CTEs
     */
    public function supportsCTE(): bool
    {
        return true;
    }

    /**
     * Check if this database supports IF NOT EXISTS in CREATE TABLE
     *
     * @return  bool  False - DB2 does not support IF NOT EXISTS
     */
    public function supportsIfNotExists(): bool
    {
        return false;
    }

    // =========================================================================
    // Important Overrides
    // =========================================================================

    /**
     * Get CHECK constraints for table
     *
     * @param   string  $table  Table name
     * @return  array
     */
    public function getCheckConstraints(string $table): array
    {
        $table = strtoupper($this->replacePrefix($table));

        $sql = "SELECT 
                   constname AS name,
                   text AS expression
                FROM syscat.checks
                WHERE tabname = " . $this->quote($table);

        $this->setQuery($sql);
        $results = $this->loadObjectList();

        $constraints = [];
        foreach ($results as $row) {
            $constraints[] = (object) [
                'name' => trim($row->name),
                'expression' => trim($row->expression)
            ];
        }

        return $constraints;
    }

    /**
     * Add stored (computed) column
     *
     * DB2 uses GENERATED ALWAYS AS (...)
     *
     * @param   string       $table       Table name
     * @param   string       $column      Column name
     * @param   string       $expression  SQL expression
     * @param   string|null  $type        Column type (ignored by DB2)
     * @return  bool
     */
    public function addStoredColumn(string $table, string $column, string $expression, ?string $type = null): bool
    {
        $table = $this->replacePrefix($table);
        $column = $this->quoteName($column);
        $this->setQuery("ALTER TABLE $table ADD $column GENERATED ALWAYS AS ($expression)");
        return $this->execute();
    }

    /**
     * Add virtual (computed) column
     *
     * DB2 columns are typically stored (materialized) if generated,
     * but default syntax behaves similarly enough for most needs.
     *
     * @param   string       $table       Table name
     * @param   string       $column      Column name
     * @param   string       $expression  SQL expression
     * @param   string|null  $type        Column type (ignored by DB2)
     * @return  bool
     */
    public function addVirtualColumn(string $table, string $column, string $expression, ?string $type = null): bool
    {
        // DB2 doesn't distinguish VIRTUAL/STORED in standard ALTER syntax same way
        return $this->addStoredColumn($table, $column, $expression, $type);
    }

    /**
     * Get global configuration variables
     *
     * @return  array
     */
    public function getGlobalVariables(): array
    {
        $this->setQuery("SELECT * FROM TABLE(sysproc.env_get_sys_info()) as sysinfo");
        try {
            $row = $this->loadObject();
            return (array) $row;
        } catch (\Exception $e) {
            return [];
        }
    }

    /**
     * Get server uptime
     *
     * @return  int|null
     */
    public function getUptime(): ?int
    {
        // Not easily available via standard SQL in all DB2 versions
        return null;
    }
    /**
     * Build a regular INDEX definition for CREATE TABLE
     *
     * DB2 does not support inline indexes in CREATE TABLE.
     * Use CREATE INDEX statement instead.
     *
     * @param   string  $quotedName     The quoted index name
     * @param   string  $columnList     The column list SQL
     * @return  string|null  Null as it's not supported inline
     */
    public function buildIndexDefinition(string $quotedName, string $columnList): ?string
    {
        return null;
    }

    /**
     * Build a UNIQUE constraint definition for CREATE TABLE
     *
     * @param   string  $quotedName     The quoted constraint name
     * @param   string  $columnList     The column list SQL
     * @return  string  The constraint definition SQL
     */
    public function buildUniqueConstraint(string $quotedName, string $columnList): string
    {
        return "CONSTRAINT $quotedName UNIQUE ($columnList)";
    }

    /**
     * Build a FOREIGN KEY constraint definition for CREATE TABLE
     *
     * DB2 limitation: ON UPDATE CASCADE is not supported.
     * DB2 only supports RESTRICT or NO ACTION for ON UPDATE.
     * This method converts CASCADE to NO ACTION for ON UPDATE.
     *
     * @param   array   $fk          Foreign key definition
     * @param   string  $tableName   Table name
     * @return  string  The constraint definition SQL
     */
    public function buildForeignKeyDefinition(array $fk, string $tableName): string
    {
        $refTable = $this->replacePrefix($fk['referencedTable']);
        $fkName = !empty($fk['name']) ? $fk['name'] : "fk_{$tableName}_{$fk['column']}";
        $constraintName = $this->quoteName($fkName);
        $fkColumn = $this->quoteName($fk['column']);
        $refTableQuoted = $this->quoteName($refTable);
        $refColumn = $this->quoteName($fk['referencedColumn']);

        $constraint = "CONSTRAINT $constraintName ";
        $constraint .= "FOREIGN KEY ($fkColumn) ";
        $constraint .= "REFERENCES $refTableQuoted ($refColumn) ";
        $constraint .= "ON DELETE {$fk['onDelete']} ";

        // DB2 doesn't support CASCADE for ON UPDATE - convert to NO ACTION
        $onUpdate = strtoupper($fk['onUpdate']) === 'CASCADE' ? 'NO ACTION' : $fk['onUpdate'];
        $constraint .= "ON UPDATE $onUpdate";

        return $constraint;
    }

    /**
     * Build an auto-increment column definition
     *
     * DB2 uses GENERATED ALWAYS AS IDENTITY syntax for auto-increment.
     * Unlike AUTO_INCREMENT in MySQL, DB2's IDENTITY columns are created
     * inline with the column definition.
     *
     * @param   string  $quotedName  The quoted column name
     * @param   string  $type        The column type (e.g., 'INTEGER')
     * @return  string  The column definition SQL
     */
    public function buildAutoIncrementColumn(string $quotedName, string $type): string
    {
        // Normalize the type to remove MySQL-specific syntax
        $type = $this->normalizeColumnType($type, []);
        // Use GENERATED BY DEFAULT to allow explicit ID values (e.g., for testing or data migration)
        return "$quotedName $type GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY";
    }

    /**
     * Normalize column type from generic/MySQL syntax to DB2 syntax
     *
     * Handles two cases:
     * 1. Abstract types (string, integer, etc.) → use Grammar type mapping
     * 2. MySQL-specific syntax → convert to DB2 equivalents
     *
     * Conversions:
     * - INT(11) → INTEGER
     * - INT(11) UNSIGNED → INTEGER
     * - BIGINT(20) → BIGINT
     * - VARCHAR(255) → VARCHAR(255) (preserved)
     * - Removes UNSIGNED keyword (not supported by DB2)
     *
     * @param   string  $type       The column type definition
     * @param   array   $modifiers  Column modifiers (length, precision, scale, etc.)
     * @return  string  The normalized DB2 type
     */
    public function normalizeColumnType(string $type, array $modifiers = []): string
    {
        // Normalize type to lowercase for typeMap lookup (AlterTableBuilder uses uppercase)
        $normalizedType = strtolower($type);

        // Check if it's an abstract type that the Grammar can map
        // (e.g., 'string' → 'VARCHAR', 'integer' → 'INTEGER', 'TEXT' → 'CLOB')
        if ($this->getSchemaGrammar()->getTypeMapping($normalizedType) !== null) {
            // Pass the normalized lowercase type to parent
            return parent::normalizeColumnType($normalizedType, $modifiers);
        }

        // Not an abstract type - handle MySQL-specific syntax

        // Convert MySQL SET type to VARCHAR (DB2 doesn't have SET type)
        // SET('value1', 'value2', ...) → VARCHAR(255)
        if (preg_match('/^SET\(/i', $type)) {
            return 'VARCHAR(255)';
        }

        // Remove UNSIGNED keyword - DB2 doesn't support it
        $type = preg_replace('/\s+UNSIGNED/i', '', $type);

        // Map MySQL integer types to DB2 types, removing length specifications
        // INT(11) → INTEGER, BIGINT(20) → BIGINT, etc.
        $type = preg_replace('/^INT\(\d+\)/i', 'INTEGER', $type);
        $type = preg_replace('/^BIGINT\(\d+\)/i', 'BIGINT', $type);
        $type = preg_replace('/^SMALLINT\(\d+\)/i', 'SMALLINT', $type);
        $type = preg_replace('/^TINYINT\(\d+\)/i', 'SMALLINT', $type);  // DB2 doesn't have TINYINT

        // For bare INT without length, convert to INTEGER
        $type = preg_replace('/^INT$/i', 'INTEGER', $type);

        return trim($type);
    }

    /**
     * Check if UNSIGNED modifier is supported
     *
     * DB2 does not support UNSIGNED integers
     *
     * @return  bool  False - DB2 doesn't support UNSIGNED
     */
    public function supportsUnsigned(): bool
    {
        return false;
    }

    /**
     * Check if explicit NULL keyword is supported in column definitions
     *
     * DB2 does not support explicit NULL keyword. Use implicit nullable (omit NOT NULL).
     * Columns are nullable by default unless NOT NULL is specified.
     *
     * @return  bool  False - DB2 doesn't support explicit NULL
     */
    public function supportsExplicitNull(): bool
    {
        return false;
    }

    /**
     * Normalize DB2 timestamp values by stripping microseconds
     *
     * DB2 TIMESTAMP columns include microseconds by default (e.g., '2024-06-15 10:30:00.000000')
     * but most applications expect standard format without microseconds.
     *
     * @param   mixed  $value  The value to normalize
     * @return  mixed  Normalized value
     */
    protected function normalizeTimestamp($value)
    {
        if (is_string($value) && preg_match('/^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d+$/', $value)) {
            // Strip microseconds: '2024-06-15 10:30:00.000000' → '2024-06-15 10:30:00'
            return preg_replace('/\.\d+$/', '', $value);
        }
        return $value;
    }

    /**
     * Normalize timestamps in an object
     *
     * @param   object  $object  The object to normalize
     * @return  object  The normalized object
     */
    protected function normalizeObjectTimestamps($object)
    {
        if (!is_object($object)) {
            return $object;
        }

        foreach (get_object_vars($object) as $key => $value) {
            $object->$key = $this->normalizeTimestamp($value);
        }

        return $object;
    }

    /**
     * {@inheritdoc}
     */
    public function loadObject($class = 'stdClass')
    {
        $object = parent::loadObject($class);
        return $object ? $this->normalizeObjectTimestamps($object) : $object;
    }

    /**
     * {@inheritdoc}
     */
    public function loadObjectList($key = '', $class = 'stdClass')
    {
        $list = parent::loadObjectList($key, $class);

        if (is_array($list)) {
            foreach ($list as $k => $object) {
                $list[$k] = $this->normalizeObjectTimestamps($object);
            }
        }

        return $list;
    }
}
