<?php
/**
 * @package    hubzero-cms
 * @copyright  Copyright (c) 2005-2020 The Regents of the University of California.
 * @license    http://opensource.org/licenses/MIT MIT
 */
?>
<article>
	<h1>Search Boosts</h1>

	<section id="values">
		<h2>Boost Values</h2>

		<p>A positive boost value moves matching items higher in the search results.</p>
		<p>A boost value of zero does not affect search results.</p>
		<p>A negative boost value moves matching items further down in  the search results.</p>
	</section>
</article>
