<article>
	<h1>Template Manager: Templates</h1>

	<p>This screen is accessed from the back-end administrator panel. It is used to preview and templates in your website.</p>

	<section id="Description">
		<h2> <span class="mw-headline">Description</span></h2>
		<p>The <b>Template Manager: Templates</b> screen allows you to preview and edit templates which are installed in your installation.</p>
	</section>
	<section id="Column_Headers">
		<h2><span class="mw-headline">Column Headers</span></h2>
		<p>Click on the column heading to sort the list by that column's value.
		</p>
		<ul><li><b>Preview.</b> A image preview of the template (not this will only appear if supplied with the template).
		</li><li><b>Template.</b> The name of the template.
		</li><li><b>Location.</b> Whether the style is a public front-end or an administrator back-end style. 'Site' means it is a public front-end style. 'Administrator' means it is an administrator back-end style.
		</li><li><b>Version.</b> The version number of the item.
		</li><li><b>Date.</b> The date the item was created by the developer.
		</li><li><b>Author.</b> The developer of the template.
		</li></ul>
	</section>
	<section id="List_Filters">
		<h2><span class="mw-headline">List Filters</span></h2>

		<h4><span class="mw-headline" id="Filter_by_Partial_Title">Filter by Partial Title</span></h4>
		<ul><li><b>Filter by Partial Title or ID. </b> In the upper left is a filter field and two buttons, as shown below.
		<ul><li> To filter by partial title, enter part of the title and click Search.
		</li><li> To filter by ID number, enter "id:xx", where "xx" is the ID number (for example, "id:9").
		</li></ul>
		</li></ul>
		<dl><dd>Click Clear to clear the Filter field and restore the list to its unfiltered state.
		</dd></dl>

		<h4> <span class="mw-headline" id="Filter_by_Location">Filter by Location</span></h4>
		<p>In the upper right area, above the column headings, there is a drop-down list box as shown below:</p>
		<p>Only items matching the selection will be displayed in the list.</p>
		<ul>
			<li> <b>Select Location.</b> Select an extension location from the drop-down list box of available clients. There are two locations - Site and Administrator.</li>
		</ul>

		<h4> <span class="mw-headline" id="Number_of_Items_to_Display">Number of Items to Display</span></h4>
		<p>Below the list you'll find:</p>
		<ul>
			<li>
				<b>Page Controls.</b> When the number of items is more than one page, you will see a page control bar as shown below.
				<ul>
					<li><b>Display #:</b> Select the number of items to show on one page.</li>
					<li><b>Start:</b> Click to go to the first page.</li>
					<li><b>Prev:</b> Click to go to the previous page.</li>
					<li><b>Page numbers:</b> Click to go to the desired page.</li>
					<li><b>Next:</b> Click to go to the next page.</li>
					<li><b>End:</b> Click to go to the last page.</li>
				</ul>
			</li>
		</ul>
	</section>
	<section id="Toolbar">
		<h2> <span class="mw-headline">Toolbar</span></h2>
		<p>At the top right you will see the toolbar. The functions are:</p>
		<ul><li><b>Options</b>. Opens the Options window where settings such as default parameters or permissions can be edited.
		</li><li><b>Help</b>. Opens this help screen.
		</li></ul>
	</section>
	<section id="Options">
		<h2><span class="mw-headline">Options</span></h2>
		<p>Click the Options button to open the <b>Template Manager Options </b> window which lets you configure this component.</p>

		<h3> <span class="mw-headline" id="Buttons_Common_to_All_Tabs">Buttons Common to All Tabs</span></h3>
		<p>At the top right of the Options modal window you will see the toolbar.</p>
		<ul><li><b>Save</b>. Saves the template options and stays in the current screen.
		</li><li><b>Save &amp; Close</b>. Saves the template options and closes the current screen.
		</li><li><b>Cancel/Close</b>. Closes the current screen and returns to the previous screen without saving any modifications you may have made.
		</li></ul>

		<h3> <span class="mw-headline" id="Templates_Tab">Templates Tab</span></h3>
		<ul><li><b>Preview Module Positions.</b> Enables the preview of the module positions in the template by appending tp=1 to the web address. Also enables the Preview button in the list of templates.
		</li></ul>

		<h3> <span class="mw-headline" id="Permissions_Tab">Permissions Tab</span></h3>
		<p>This screen allows you to set the component permissions in the CMS. This is important to consider if you have sites with many different user categories all of whom need to have different accessibilities to the component. The screenshot below describes what you should see and the text below that describes what each permission level gives the user access to:</p>
		<p>You work on one Group at a time by opening the slider for that group. You change the permissions in the Select New Settings drop-down list boxes.
		The options for each value are Inherited, Allowed, or Denied. The Calculated Setting column shows you the setting in effect. It is either Not Allowed (the default), Allowed, or Denied.
		Note that the Calculated Setting column is not updated until you press the Save button in the toolbar. To check that the settings are what you want, press the Save button and check the Calculated Settings column.</p>
		<p>The default values used here are the ones set in the <a href="<?php echo Route::url('index.php?option=com_help&component=com_config&page=global_config'); ?>" title="Help25:Site Global Configuration">Global Configuration Permissions Tab</a></p>
		<dl><dd><dl><dt>Configure</dt><dd> Open the template manager option screens (the modal window these options are in)
		</dd><dt>Access Administration Interface</dt><dd> Open the template manager manger screens
		</dd><dt>Create&#160;</dt><dd> Create new styles in the component
		</dd><dt>Delete&#160;</dt><dd> Delete existing styles in the component
		</dd><dt>Edit&#160;</dt><dd> Edit existing templates and styles in the component
		</dd><dt>Edit State&#160;</dt><dd> Change an templates and styles state (Publish, Unpublish, Archive, and Trash) in the component.
		</dd></dl>
		</dd></dl>
		<p>There are two very important points to understand from this screen. The first is to see how the permissions can be inherited from the parent Group. The second is to see how you can control the default permissions by Group and by Action.
		This provides a lot of flexibility. For example, if you wanted Shop Suppliers to be able to have the ability to create an article about their product, you could just change their Create value to "Allowed". If you wanted to not allow members of Administrator group to delete objects or change their state, you would change their permissions in these columns to Inherited (or Denied).
		It is also important to understand that the ability to have child groups is completely optional. It allows you to save some time when setting up new groups. However, if you like, you can set up all groups to have Public as the parent and not inherit any permissions from a parent group.</p>
	</section>
	<section id="Toolbar_Links">
		<h2><span class="mw-headline">Toolbar Links</span></h2>
		<p>At the top left, above the Filter, you will see the following two links:</p>
		<ul><li><b>Styles.</b> Click this link to go to the <a href="<?php echo Route::url('index.php?option=com_help&component=com_templates&page=styles'); ?>" title="Help: Extensions Template Manager Styles">Template Manager: Styles</a> screen.
		</li><li><b>Templates.</b> This link takes you to the screen you are currently on.
		</li></ul>
	</section>
	<section id="Related_Information">
		<h2><span class="mw-headline">Related Information</span></h2>
		<p>To edit templates styles: <a href="<?php echo Route::url('index.php?option=com_help&component=com_templates&page=styles'); ?>" title="Help: Extensions Template Manager Styles">Template Manager: Styles</a></p>
	</section>
</article>