<?php

/**
 * @package    framework
 * @copyright  Copyright (c) 2005-2020 The Regents of the University of California.
 * @license    http://opensource.org/licenses/MIT MIT
 */

namespace Hubzero\Database\Tests;

use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\Attributes\Group;
use Hubzero\Database\Driver;
use Hubzero\Database\Driver\Firebird;

/**
 * Firebird-specific driver tests
 *
 * Runs against all configured backends via the standard databaseProvider.
 * Tests that receive a non-Firebird driver pass with a no-op assertion.
 * If multiple Firebird instances are configured (e.g. Firebird 3 and 4),
 * each test runs against all of them.
 *
 * Configuration: Add 'firebird' to DB_TEST_BACKENDS and set DB_FIREBIRD_*
 * credentials in phpunit.xml or via environment variables.
 */
#[Group('firebird')]
#[Group('database')]
class FirebirdDriverTest extends AbstractDriverTestCase
{
    protected static function getTestTables(): array
    {
        return ['FT_ITEMS', 'FT_CATEGORIES'];
    }

    protected static function setUpDatabase(Driver $driver): void
    {
        if (get_class($driver) !== Firebird::class) {
            return;
        }

        // Drop in correct order (view depends on table, child depends on parent)
        foreach (['FT_ACTIVE_ITEMS'] as $view) {
            try {
                $driver->exec("DROP VIEW $view");
            } catch (\Exception $e) {
            }
        }
        foreach (['FT_ITEMS', 'FT_CATEGORIES'] as $table) {
            try {
                $driver->dropTable($table, true);
            } catch (\Exception $e) {
            }
        }

        $driver->exec('
            CREATE TABLE FT_CATEGORIES (
                ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                NAME VARCHAR(100) NOT NULL,
                SLUG VARCHAR(100),
                SORT_ORDER INTEGER DEFAULT 0,
                ACTIVE SMALLINT DEFAULT 1,
                CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        ');

        $driver->exec('
            CREATE TABLE FT_ITEMS (
                ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                CATEGORY_ID INTEGER,
                TITLE VARCHAR(200) NOT NULL,
                DESCRIPTION BLOB SUB_TYPE TEXT,
                PRICE DECIMAL(10,2) DEFAULT 0.00,
                STOCK INTEGER DEFAULT 0,
                STATUS VARCHAR(20) DEFAULT \'active\',
                CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT FK_ITEMS_CAT FOREIGN KEY (CATEGORY_ID)
                    REFERENCES FT_CATEGORIES(ID) ON DELETE SET NULL
            )
        ');

        $driver->exec('CREATE INDEX IDX_ITEMS_STATUS ON FT_ITEMS (STATUS)');
        $driver->exec('CREATE INDEX IDX_ITEMS_CAT ON FT_ITEMS (CATEGORY_ID)');

        $driver->exec("INSERT INTO FT_CATEGORIES (NAME, SLUG, SORT_ORDER) VALUES ('Electronics', 'electronics', 1)");
        $driver->exec("INSERT INTO FT_CATEGORIES (NAME, SLUG, SORT_ORDER) VALUES ('Books', 'books', 2)");
        $driver->exec(
            "INSERT INTO FT_CATEGORIES (NAME, SLUG, SORT_ORDER, ACTIVE) VALUES ('Archived', 'archived', 99, 0)"
        );

        $driver->exec(
            "INSERT INTO FT_ITEMS (CATEGORY_ID, TITLE, PRICE, STOCK, STATUS) VALUES (1, 'Laptop', 999.99, 10, 'active')"
        );
        $driver->exec(
            "INSERT INTO FT_ITEMS (CATEGORY_ID, TITLE, PRICE, STOCK, STATUS) VALUES (1, 'Phone', 599.99, 25, 'active')"
        );
        $driver->exec(
            "INSERT INTO FT_ITEMS (CATEGORY_ID, TITLE, PRICE, STOCK, STATUS) VALUES (2, 'Novel', 19.99, 100, 'active')"
        );
        $driver->exec(
            "INSERT INTO FT_ITEMS (CATEGORY_ID, TITLE, PRICE, STOCK, STATUS) VALUES (2, 'Textbook', 79.99, 5, 'draft')"
        );
    }

    /**
     * Check if the driver is Firebird; if not, pass with no-op assertion.
     */
    private function requiresFirebird(Driver $driver): bool
    {
        if (get_class($driver) !== Firebird::class) {
            $this->assertTrue(true);
            return false;
        }
        return true;
    }

    protected function tearDown(): void
    {
        parent::tearDown();

        // Clean up ad-hoc tables created by individual migration tests
        $migTables = [
            'MIG_ADD_PK', 'MIG_IDEMPOTENT', 'MIG_CUSTOM_PK',
            'MIG_COMPLEX', 'MIG_RESOURCE_ASSOC', 'MIG_DROP_COL',
            'MIG_ADD_COL', 'MIG_INDEX_TEST', 'MIG_FK_CHILD', 'MIG_FK_PARENT',
            'MIG_TRUNCATE', 'MIG_VARCHAR_LEN', 'MIG_INT_BIGINT',
            'MIG_DEFAULTS', 'MIG_NOTNULL',
            'MIG_VIEW_CRE', 'MIG_VIEW_REP', 'MIG_VIEW_EXI', 'MIG_VIEW_DRO'
        ];

        $migGenerators = [
            'GEN_MIG_ADD_PK_ID', 'GEN_MIG_CUSTOM_PK_ID',
            'GEN_MIG_COMPLEX_ID', 'GEN_MIG_RESOURCE_ASSOC_ID'
        ];

        $migViews = ['MIG_TEST_VIEW_CRE', 'MIG_REPLACE_VIEW', 'MIG_EXISTS_VIEW', 'MIG_DROP_VIEW'];

        foreach (static::getClassDrivers() as $driver) {
            if (get_class($driver) !== Firebird::class) {
                continue;
            }
            foreach ($migViews as $view) {
                try {
                    $driver->exec("DROP VIEW $view");
                } catch (\Exception $e) {
                }
            }
            foreach ($migTables as $table) {
                try {
                    $driver->exec("DROP TABLE $table");
                } catch (\Exception $e) {
                }
            }
            foreach ($migGenerators as $gen) {
                try {
                    $driver->exec("DROP GENERATOR $gen");
                } catch (\Exception $e) {
                }
            }
        }
    }

    public static function tearDownAfterClass(): void
    {
        // Drop views before parent drops the base tables they depend on
        foreach (static::getClassDrivers() as $driver) {
            if (get_class($driver) !== Firebird::class) {
                continue;
            }
            try {
                $driver->exec('DROP VIEW FT_ACTIVE_ITEMS');
            } catch (\Exception $e) {
            }
        }

        parent::tearDownAfterClass();
    }

    // =========================================================================
    // Connection & Version
    // =========================================================================

    #[Test]
    #[DataProvider('databaseProvider')]
    public function driverConnectionWorks(string $dbName, Driver $driver): void
    {
        if (!$this->requiresFirebird($driver)) {
            return;
        }

        $driver->setQuery('SELECT 1');
        $this->assertEquals(1, $driver->loadResult());
    }

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canGetFirebirdVersion(string $dbName, Driver $driver): void
    {
        if (!$this->requiresFirebird($driver)) {
            return;
        }

        $version = $driver->getVersion();
        $this->assertNotEmpty($version);
        $this->assertMatchesRegularExpression('/^[0-9]+\./', $version);
    }

    // =========================================================================
    // Schema Introspection
    // =========================================================================

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canListTables(string $dbName, Driver $driver): void
    {
        if (!$this->requiresFirebird($driver)) {
            return;
        }

        $driver->setQuery("
            SELECT TRIM(RDB\$RELATION_NAME) AS table_name
            FROM RDB\$RELATIONS
            WHERE RDB\$SYSTEM_FLAG = 0 AND RDB\$VIEW_BLR IS NULL
            ORDER BY RDB\$RELATION_NAME
        ");
        $tables = $driver->loadColumn();

        $this->assertContains('FT_CATEGORIES', $tables);
        $this->assertContains('FT_ITEMS', $tables);
    }

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canCheckTableExists(string $dbName, Driver $driver): void
    {
        if (!$this->requiresFirebird($driver)) {
            return;
        }

        $driver->setQuery("
            SELECT COUNT(*) FROM RDB\$RELATIONS
            WHERE RDB\$RELATION_NAME = 'FT_CATEGORIES' AND RDB\$SYSTEM_FLAG = 0
        ");
        $this->assertEquals(1, $driver->loadResult());

        $driver->setQuery("
            SELECT COUNT(*) FROM RDB\$RELATIONS
            WHERE RDB\$RELATION_NAME = 'NONEXISTENT_TABLE' AND RDB\$SYSTEM_FLAG = 0
        ");
        $this->assertEquals(0, $driver->loadResult());
    }

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canGetTableColumns(string $dbName, Driver $driver): void
    {
        if (!$this->requiresFirebird($driver)) {
            return;
        }

        $driver->setQuery("
            SELECT
                TRIM(rf.RDB\$FIELD_NAME) AS field_name,
                f.RDB\$FIELD_TYPE AS field_type,
                f.RDB\$FIELD_LENGTH AS field_length,
                rf.RDB\$NULL_FLAG AS not_null
            FROM RDB\$RELATION_FIELDS rf
            JOIN RDB\$FIELDS f ON rf.RDB\$FIELD_SOURCE = f.RDB\$FIELD_NAME
            WHERE TRIM(rf.RDB\$RELATION_NAME) = 'FT_CATEGORIES'
            ORDER BY rf.RDB\$FIELD_POSITION
        ");
        $columns = $driver->loadObjectList();
        $columnNames = array_map(fn($c) => strtolower(trim($c->field_name ?? '')), $columns);

        $this->assertContains('id', $columnNames);
        $this->assertContains('name', $columnNames);
        $this->assertContains('slug', $columnNames);
        $this->assertContains('created_at', $columnNames);
    }

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canGetPrimaryKey(string $dbName, Driver $driver): void
    {
        if (!$this->requiresFirebird($driver)) {
            return;
        }

        $driver->setQuery("
            SELECT TRIM(i.RDB\$FIELD_NAME) AS column_name
            FROM RDB\$RELATION_CONSTRAINTS rc
            JOIN RDB\$INDEX_SEGMENTS i ON rc.RDB\$INDEX_NAME = i.RDB\$INDEX_NAME
            WHERE TRIM(rc.RDB\$RELATION_NAME) = 'FT_CATEGORIES'
            AND rc.RDB\$CONSTRAINT_TYPE = 'PRIMARY KEY'
        ");
        $this->assertEquals('id', strtolower(trim($driver->loadResult() ?? '')));
    }

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canGetForeignKeys(string $dbName, Driver $driver): void
    {
        if (!$this->requiresFirebird($driver)) {
            return;
        }

        $driver->setQuery("
            SELECT
                TRIM(rc.RDB\$CONSTRAINT_NAME) AS constraint_name,
                TRIM(s.RDB\$FIELD_NAME) AS column_name,
                TRIM(ref_rc.RDB\$RELATION_NAME) AS referenced_table
            FROM RDB\$RELATION_CONSTRAINTS rc
            JOIN RDB\$INDEX_SEGMENTS s ON rc.RDB\$INDEX_NAME = s.RDB\$INDEX_NAME
            JOIN RDB\$REF_CONSTRAINTS refc ON rc.RDB\$CONSTRAINT_NAME = refc.RDB\$CONSTRAINT_NAME
            JOIN RDB\$RELATION_CONSTRAINTS ref_rc ON refc.RDB\$CONST_NAME_UQ = ref_rc.RDB\$CONSTRAINT_NAME
            WHERE TRIM(rc.RDB\$RELATION_NAME) = 'FT_ITEMS'
            AND rc.RDB\$CONSTRAINT_TYPE = 'FOREIGN KEY'
        ");
        $fk = $driver->loadObject();

        $this->assertNotNull($fk);
        $this->assertEquals('fk_items_cat', strtolower(trim($fk->constraint_name ?? '')));
        $this->assertEquals('category_id', strtolower(trim($fk->column_name ?? '')));
        $this->assertEquals('ft_categories', strtolower(trim($fk->referenced_table ?? '')));
    }

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canGetIndexes(string $dbName, Driver $driver): void
    {
        if (!$this->requiresFirebird($driver)) {
            return;
        }

        $driver->setQuery("
            SELECT
                TRIM(i.RDB\$INDEX_NAME) AS index_name,
                i.RDB\$UNIQUE_FLAG AS is_unique,
                TRIM(s.RDB\$FIELD_NAME) AS column_name
            FROM RDB\$INDICES i
            JOIN RDB\$INDEX_SEGMENTS s ON i.RDB\$INDEX_NAME = s.RDB\$INDEX_NAME
            WHERE TRIM(i.RDB\$RELATION_NAME) = 'FT_ITEMS'
            AND i.RDB\$SYSTEM_FLAG = 0
            ORDER BY i.RDB\$INDEX_NAME
        ");
        $indexes = $driver->loadObjectList();
        $indexNames = array_map(fn($i) => strtolower(trim($i->index_name ?? '')), $indexes);

        $this->assertContains('idx_items_status', $indexNames);
        $this->assertContains('idx_items_cat', $indexNames);
    }

    // =========================================================================
    // CRUD Operations
    // =========================================================================

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canSelectAllRecords(string $dbName, Driver $driver): void
    {
        if (!$this->requiresFirebird($driver)) {
            return;
        }

        $driver->setQuery('SELECT * FROM FT_CATEGORIES ORDER BY ID');
        $categories = $driver->loadObjectList();

        $this->assertCount(3, $categories);
        $this->assertEquals('Electronics', trim($categories[0]->name ?? ''));
        $this->assertEquals('Books', trim($categories[1]->name ?? ''));
    }

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canSelectWithWhereClause(string $dbName, Driver $driver): void
    {
        if (!$this->requiresFirebird($driver)) {
            return;
        }

        $driver->setQuery("SELECT * FROM FT_ITEMS WHERE STATUS = 'active'");
        $this->assertCount(3, $driver->loadObjectList());
    }

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canSelectWithJoin(string $dbName, Driver $driver): void
    {
        if (!$this->requiresFirebird($driver)) {
            return;
        }

        $driver->setQuery("
            SELECT i.TITLE, c.NAME AS category_name
            FROM FT_ITEMS i
            JOIN FT_CATEGORIES c ON i.CATEGORY_ID = c.ID
            ORDER BY i.ID
        ");
        $items = $driver->loadObjectList();

        $this->assertCount(4, $items);
        $this->assertEquals('Electronics', trim($items[0]->category_name ?? ''));
    }

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canInsertRecord(string $dbName, Driver $driver): void
    {
        if (!$this->requiresFirebird($driver)) {
            return;
        }

        $driver->exec("INSERT INTO FT_CATEGORIES (NAME, SLUG) VALUES ('Test Category', 'test-cat')");

        $driver->setQuery("SELECT * FROM FT_CATEGORIES WHERE SLUG = 'test-cat'");
        $cat = $driver->loadObject();
        $this->assertNotNull($cat);
        $this->assertEquals('Test Category', trim($cat->name ?? ''));

        $driver->exec("DELETE FROM FT_CATEGORIES WHERE SLUG = 'test-cat'");
    }

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canUpdateRecord(string $dbName, Driver $driver): void
    {
        if (!$this->requiresFirebird($driver)) {
            return;
        }

        $driver->exec("INSERT INTO FT_CATEGORIES (NAME, SLUG) VALUES ('Update Test', 'update-test')");
        $driver->exec("UPDATE FT_CATEGORIES SET NAME = 'Updated Name' WHERE SLUG = 'update-test'");

        $driver->setQuery("SELECT NAME FROM FT_CATEGORIES WHERE SLUG = 'update-test'");
        $this->assertEquals('Updated Name', trim($driver->loadResult()));

        $driver->exec("DELETE FROM FT_CATEGORIES WHERE SLUG = 'update-test'");
    }

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canDeleteRecord(string $dbName, Driver $driver): void
    {
        if (!$this->requiresFirebird($driver)) {
            return;
        }

        $driver->exec("INSERT INTO FT_CATEGORIES (NAME, SLUG) VALUES ('Delete Test', 'delete-test')");
        $driver->exec("DELETE FROM FT_CATEGORIES WHERE SLUG = 'delete-test'");

        $driver->setQuery("SELECT COUNT(*) FROM FT_CATEGORIES WHERE SLUG = 'delete-test'");
        $this->assertEquals(0, $driver->loadResult());
    }

    // =========================================================================
    // Transactions
    // =========================================================================

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canCommitTransaction(string $dbName, Driver $driver): void
    {
        if (!$this->requiresFirebird($driver)) {
            return;
        }

        $driver->transactionStart();
        $driver->exec("INSERT INTO FT_CATEGORIES (NAME, SLUG) VALUES ('Trans Commit', 'trans-commit')");
        $driver->transactionCommit();

        $driver->setQuery("SELECT * FROM FT_CATEGORIES WHERE SLUG = 'trans-commit'");
        $this->assertNotNull($driver->loadObject());

        $driver->exec("DELETE FROM FT_CATEGORIES WHERE SLUG = 'trans-commit'");
    }

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canRollbackTransaction(string $dbName, Driver $driver): void
    {
        if (!$this->requiresFirebird($driver)) {
            return;
        }

        // Separate connection to test isolation
        $config = static::$testDatabases[$dbName];
        $driver2 = new Firebird($config);
        $driver2->connect();

        $driver2->transactionStart();
        $driver2->exec("INSERT INTO FT_CATEGORIES (NAME, SLUG) VALUES ('Trans Rollback', 'trans-rollback')");
        $driver2->transactionRollback();

        $driver->setQuery("SELECT COUNT(*) FROM FT_CATEGORIES WHERE SLUG = 'trans-rollback'");
        $count = (int) $driver->loadResult();

        $driver->exec("DELETE FROM FT_CATEGORIES WHERE SLUG = 'trans-rollback'");
        $driver2->disconnect();

        $this->assertEquals(0, $count, 'Rolled back row should not be visible');
    }

    // =========================================================================
    // Aggregate Functions
    // =========================================================================

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canUseCount(string $dbName, Driver $driver): void
    {
        if (!$this->requiresFirebird($driver)) {
            return;
        }

        $driver->setQuery("SELECT COUNT(*) FROM FT_ITEMS");
        $this->assertEquals(4, $driver->loadResult());
    }

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canUseSum(string $dbName, Driver $driver): void
    {
        if (!$this->requiresFirebird($driver)) {
            return;
        }

        $driver->setQuery("SELECT SUM(STOCK) FROM FT_ITEMS");
        $this->assertEquals(140, $driver->loadResult());
    }

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canUseAvg(string $dbName, Driver $driver): void
    {
        if (!$this->requiresFirebird($driver)) {
            return;
        }

        $driver->setQuery("SELECT AVG(PRICE) FROM FT_ITEMS");
        $this->assertGreaterThan(0, $driver->loadResult());
    }

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canUseMinMax(string $dbName, Driver $driver): void
    {
        if (!$this->requiresFirebird($driver)) {
            return;
        }

        $driver->setQuery("SELECT MIN(PRICE) AS min_price, MAX(PRICE) AS max_price FROM FT_ITEMS");
        $row = $driver->loadObject();

        $this->assertEquals(19.99, $row->min_price ?? null);
        $this->assertEquals(999.99, $row->max_price ?? null);
    }

    // =========================================================================
    // Date/Time Functions
    // =========================================================================

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canUseCurrentTimestamp(string $dbName, Driver $driver): void
    {
        if (!$this->requiresFirebird($driver)) {
            return;
        }

        $driver->setQuery("SELECT CURRENT_TIMESTAMP AS ts FROM RDB\$DATABASE");
        $this->assertNotEmpty($driver->loadResult());
    }

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canExtractDateParts(string $dbName, Driver $driver): void
    {
        if (!$this->requiresFirebird($driver)) {
            return;
        }

        $driver->setQuery("
            SELECT
                EXTRACT(YEAR FROM CURRENT_TIMESTAMP) AS yr,
                EXTRACT(MONTH FROM CURRENT_TIMESTAMP) AS mo,
                EXTRACT(DAY FROM CURRENT_TIMESTAMP) AS dy
            FROM RDB\$DATABASE
        ");
        $row = $driver->loadObject();

        $this->assertGreaterThanOrEqual(2020, (int) ($row->yr ?? 0));
        $this->assertGreaterThanOrEqual(1, (int) ($row->mo ?? 0));
        $this->assertLessThanOrEqual(12, (int) ($row->mo ?? 0));
        $this->assertGreaterThanOrEqual(1, (int) ($row->dy ?? 0));
        $this->assertLessThanOrEqual(31, (int) ($row->dy ?? 0));
    }

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canUseDateadd(string $dbName, Driver $driver): void
    {
        if (!$this->requiresFirebird($driver)) {
            return;
        }

        $driver->setQuery("
            SELECT
                DATEADD(7 DAY TO CURRENT_DATE) AS next_week,
                DATEADD(-30 DAY TO CURRENT_DATE) AS last_month
            FROM RDB\$DATABASE
        ");
        $row = $driver->loadObject();

        $this->assertNotEmpty($row->next_week ?? '');
        $this->assertNotEmpty($row->last_month ?? '');
    }

    // =========================================================================
    // String Functions
    // =========================================================================

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canConcatenateStrings(string $dbName, Driver $driver): void
    {
        if (!$this->requiresFirebird($driver)) {
            return;
        }

        $driver->setQuery("SELECT 'Hello' || ' ' || 'World' AS greeting FROM RDB\$DATABASE");
        $this->assertEquals('Hello World', trim($driver->loadResult()));
    }

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canUseCharLength(string $dbName, Driver $driver): void
    {
        if (!$this->requiresFirebird($driver)) {
            return;
        }

        $driver->setQuery("SELECT CHAR_LENGTH('Test String') AS len FROM RDB\$DATABASE");
        $this->assertEquals(11, $driver->loadResult());
    }

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canUseUpperLower(string $dbName, Driver $driver): void
    {
        if (!$this->requiresFirebird($driver)) {
            return;
        }

        $driver->setQuery("
            SELECT UPPER('hello') AS up, LOWER('WORLD') AS lo FROM RDB\$DATABASE
        ");
        $row = $driver->loadObject();

        $this->assertEquals('HELLO', trim($row->up ?? ''));
        $this->assertEquals('world', trim($row->lo ?? ''));
    }

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canUseSubstring(string $dbName, Driver $driver): void
    {
        if (!$this->requiresFirebird($driver)) {
            return;
        }

        $driver->setQuery("SELECT SUBSTRING('Hello World' FROM 1 FOR 5) AS sub FROM RDB\$DATABASE");
        $this->assertEquals('Hello', trim($driver->loadResult()));
    }

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canUsePosition(string $dbName, Driver $driver): void
    {
        if (!$this->requiresFirebird($driver)) {
            return;
        }

        $driver->setQuery("SELECT POSITION('World' IN 'Hello World') AS pos FROM RDB\$DATABASE");
        $this->assertEquals(7, $driver->loadResult());
    }

    // =========================================================================
    // NULL Handling
    // =========================================================================

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canUseCoalesce(string $dbName, Driver $driver): void
    {
        if (!$this->requiresFirebird($driver)) {
            return;
        }

        $driver->setQuery("SELECT COALESCE(NULL, 'default') AS result FROM RDB\$DATABASE");
        $this->assertEquals('default', trim($driver->loadResult()));
    }

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canFilterNulls(string $dbName, Driver $driver): void
    {
        if (!$this->requiresFirebird($driver)) {
            return;
        }

        $driver->exec("INSERT INTO FT_ITEMS (TITLE, STATUS) VALUES ('No Category', 'active')");

        $driver->setQuery("SELECT COUNT(*) FROM FT_ITEMS WHERE CATEGORY_ID IS NULL");
        $this->assertGreaterThan(0, $driver->loadResult());

        $driver->exec("DELETE FROM FT_ITEMS WHERE TITLE = 'No Category'");
    }

    // =========================================================================
    // CASE Expressions
    // =========================================================================

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canUseCaseExpression(string $dbName, Driver $driver): void
    {
        if (!$this->requiresFirebird($driver)) {
            return;
        }

        $driver->setQuery("
            SELECT TITLE,
                CASE STATUS
                    WHEN 'active' THEN 'Available'
                    WHEN 'draft' THEN 'Coming Soon'
                    ELSE 'Unknown'
                END AS status_label
            FROM FT_ITEMS ORDER BY ID
        ");
        $items = $driver->loadObjectList();

        $this->assertEquals('Available', trim($items[0]->status_label ?? ''));
        $this->assertEquals('Coming Soon', trim($items[3]->status_label ?? ''));
    }

    // =========================================================================
    // GROUP BY & Subqueries
    // =========================================================================

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canGroupByWithHaving(string $dbName, Driver $driver): void
    {
        if (!$this->requiresFirebird($driver)) {
            return;
        }

        $driver->setQuery("
            SELECT CATEGORY_ID, COUNT(*) AS item_count
            FROM FT_ITEMS
            WHERE CATEGORY_ID IS NOT NULL
            GROUP BY CATEGORY_ID
            HAVING COUNT(*) >= 2
            ORDER BY CATEGORY_ID
        ");
        $rows = $driver->loadObjectList();

        $this->assertCount(2, $rows);
        $this->assertEquals(2, $rows[0]->item_count ?? 0);
    }

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canUseSubqueryInWhere(string $dbName, Driver $driver): void
    {
        if (!$this->requiresFirebird($driver)) {
            return;
        }

        $driver->setQuery("
            SELECT * FROM FT_ITEMS
            WHERE CATEGORY_ID IN (SELECT ID FROM FT_CATEGORIES WHERE ACTIVE = 1)
        ");
        $this->assertCount(4, $driver->loadObjectList());
    }

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canUseCorrelatedSubquery(string $dbName, Driver $driver): void
    {
        if (!$this->requiresFirebird($driver)) {
            return;
        }

        $driver->setQuery("
            SELECT c.NAME,
                (SELECT COUNT(*) FROM FT_ITEMS i WHERE i.CATEGORY_ID = c.ID) AS item_count
            FROM FT_CATEGORIES c
            WHERE c.ACTIVE = 1 AND c.NAME IN ('Electronics', 'Books')
            ORDER BY c.ID
        ");
        $rows = $driver->loadObjectList();

        $this->assertCount(2, $rows);
        $electronics = array_values(array_filter($rows, fn($r) => trim($r->name ?? '') === 'Electronics'));
        $books = array_values(array_filter($rows, fn($r) => trim($r->name ?? '') === 'Books'));

        $this->assertEquals(2, $electronics[0]->item_count ?? 0);
        $this->assertEquals(2, $books[0]->item_count ?? 0);
    }

    // =========================================================================
    // Limit/Offset
    // =========================================================================

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canLimitResultsWithFirst(string $dbName, Driver $driver): void
    {
        if (!$this->requiresFirebird($driver)) {
            return;
        }

        $driver->setQuery("SELECT FIRST 2 * FROM FT_ITEMS ORDER BY ID");
        $this->assertCount(2, $driver->loadObjectList());
    }

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canSkipAndLimitWithFirstSkip(string $dbName, Driver $driver): void
    {
        if (!$this->requiresFirebird($driver)) {
            return;
        }

        $driver->setQuery("SELECT FIRST 2 SKIP 1 * FROM FT_ITEMS ORDER BY ID");
        $items = $driver->loadObjectList();

        $this->assertCount(2, $items);
        $this->assertEquals('Phone', trim($items[0]->title ?? ''));
    }

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canUseOffsetFetch(string $dbName, Driver $driver): void
    {
        if (!$this->requiresFirebird($driver)) {
            return;
        }

        $driver->setQuery("SELECT * FROM FT_ITEMS ORDER BY ID OFFSET 1 ROWS FETCH NEXT 2 ROWS ONLY");
        $this->assertCount(2, $driver->loadObjectList());
    }

    // =========================================================================
    // BLOBs
    // =========================================================================

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canInsertAndReadBlob(string $dbName, Driver $driver): void
    {
        if (!$this->requiresFirebird($driver)) {
            return;
        }

        $longText = str_repeat("This is a test paragraph. ", 100);

        $driver->exec(
            "INSERT INTO FT_ITEMS (CATEGORY_ID, TITLE, DESCRIPTION, STATUS) "
            . "VALUES (1, 'Blob Test', '$longText', 'active')"
        );

        $driver->setQuery("SELECT DESCRIPTION FROM FT_ITEMS WHERE TITLE = 'Blob Test'");
        $description = $driver->loadResult();

        if (is_resource($description)) {
            $description = stream_get_contents($description);
        }

        $this->assertEquals($longText, $description);

        $driver->exec("DELETE FROM FT_ITEMS WHERE TITLE = 'Blob Test'");
    }

    // =========================================================================
    // Generators (Sequences)
    // =========================================================================

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canCreateAndUseGenerator(string $dbName, Driver $driver): void
    {
        if (!$this->requiresFirebird($driver)) {
            return;
        }

        $driver->exec("CREATE GENERATOR GEN_FT_TEST");
        $driver->exec("SET GENERATOR GEN_FT_TEST TO 100");

        $driver->setQuery("SELECT GEN_ID(GEN_FT_TEST, 1) FROM RDB\$DATABASE");
        $this->assertEquals(101, $driver->loadResult());

        $driver->setQuery("SELECT GEN_ID(GEN_FT_TEST, 0) FROM RDB\$DATABASE");
        $this->assertEquals(101, $driver->loadResult());

        $driver->exec("DROP GENERATOR GEN_FT_TEST");
    }

    // =========================================================================
    // Query Builder Integration
    // =========================================================================

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canUseFluentQueryWithLimit(string $dbName, Driver $driver): void
    {
        if (!$this->requiresFirebird($driver)) {
            return;
        }

        $items = $driver->getQuery()
            ->select('*')
            ->from('FT_ITEMS')
            ->order('id', 'asc')
            ->limit(2)
            ->fetch('rows');

        $this->assertCount(2, $items);
    }

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canUseFluentQueryWithSubquery(string $dbName, Driver $driver): void
    {
        if (!$this->requiresFirebird($driver)) {
            return;
        }

        $items = $driver->getQuery()
            ->select('*')
            ->from('FT_ITEMS')
            ->whereIn('category_id', function ($sub) {
                $sub->select('id')
                    ->from('FT_CATEGORIES')
                    ->whereEquals('active', 1);
            })
            ->order('id', 'asc')
            ->fetch('rows');

        $this->assertCount(4, $items);
    }

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canHandleEmptyWhereIn(string $dbName, Driver $driver): void
    {
        if (!$this->requiresFirebird($driver)) {
            return;
        }

        $items = $driver->getQuery()
            ->select('*')
            ->from('FT_ITEMS')
            ->whereIn('id', [])
            ->fetch('rows');

        $this->assertCount(0, $items);
    }

    // =========================================================================
    // DDL: Column Operations
    // =========================================================================

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canAddColumn(string $dbName, Driver $driver): void
    {
        if (!$this->requiresFirebird($driver)) {
            return;
        }

        $driver->exec("CREATE TABLE MIG_ADD_COL (ID INTEGER PRIMARY KEY, NAME VARCHAR(100))");
        $driver->exec("ALTER TABLE MIG_ADD_COL ADD EMAIL VARCHAR(200)");

        $driver->setQuery("
            SELECT COUNT(*) FROM RDB\$RELATION_FIELDS
            WHERE RDB\$RELATION_NAME = 'MIG_ADD_COL' AND RDB\$FIELD_NAME = 'EMAIL'
        ");
        $this->assertEquals(1, (int) $driver->loadResult());
    }

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canDropColumn(string $dbName, Driver $driver): void
    {
        if (!$this->requiresFirebird($driver)) {
            return;
        }

        $driver->exec("
            CREATE TABLE MIG_DROP_COL (
                ID INTEGER PRIMARY KEY, NAME VARCHAR(100),
                EMAIL VARCHAR(200), STATUS VARCHAR(20)
            )
        ");
        $driver->exec("ALTER TABLE MIG_DROP_COL DROP EMAIL");

        $driver->setQuery("
            SELECT COUNT(*) FROM RDB\$RELATION_FIELDS
            WHERE RDB\$RELATION_NAME = 'MIG_DROP_COL' AND RDB\$FIELD_NAME = 'EMAIL'
        ");
        $this->assertEquals(0, (int) $driver->loadResult());
    }

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canAlterColumnType(string $dbName, Driver $driver): void
    {
        if (!$this->requiresFirebird($driver)) {
            return;
        }

        $driver->exec("CREATE TABLE MIG_ADD_COL (ID INTEGER PRIMARY KEY, DESCRIPTION VARCHAR(100))");
        $driver->exec("ALTER TABLE MIG_ADD_COL ALTER DESCRIPTION TYPE VARCHAR(500)");

        $driver->setQuery("
            SELECT f.RDB\$CHARACTER_LENGTH
            FROM RDB\$RELATION_FIELDS rf
            JOIN RDB\$FIELDS f ON rf.RDB\$FIELD_SOURCE = f.RDB\$FIELD_NAME
            WHERE rf.RDB\$RELATION_NAME = 'MIG_ADD_COL'
            AND rf.RDB\$FIELD_NAME = 'DESCRIPTION'
        ");
        $this->assertGreaterThanOrEqual(500, (int) $driver->loadResult());
    }

    // =========================================================================
    // DDL: Index Operations
    // =========================================================================

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canCreateIndex(string $dbName, Driver $driver): void
    {
        if (!$this->requiresFirebird($driver)) {
            return;
        }

        $driver->exec("CREATE TABLE MIG_INDEX_TEST (ID INTEGER PRIMARY KEY, NAME VARCHAR(100), EMAIL VARCHAR(200))");
        $driver->exec("CREATE INDEX IDX_MIG_NAME ON MIG_INDEX_TEST (NAME)");

        $driver->setQuery("SELECT COUNT(*) FROM RDB\$INDICES WHERE RDB\$INDEX_NAME = 'IDX_MIG_NAME'");
        $this->assertEquals(1, (int) $driver->loadResult());
    }

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canCreateUniqueIndex(string $dbName, Driver $driver): void
    {
        if (!$this->requiresFirebird($driver)) {
            return;
        }

        $driver->exec("CREATE TABLE MIG_INDEX_TEST (ID INTEGER PRIMARY KEY, NAME VARCHAR(100), EMAIL VARCHAR(200))");
        $driver->exec("CREATE UNIQUE INDEX IDX_MIG_EMAIL ON MIG_INDEX_TEST (EMAIL)");

        $driver->setQuery("SELECT RDB\$UNIQUE_FLAG FROM RDB\$INDICES WHERE RDB\$INDEX_NAME = 'IDX_MIG_EMAIL'");
        $this->assertEquals(1, (int) $driver->loadResult());
    }

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canDropIndex(string $dbName, Driver $driver): void
    {
        if (!$this->requiresFirebird($driver)) {
            return;
        }

        $driver->exec("CREATE TABLE MIG_INDEX_TEST (ID INTEGER PRIMARY KEY, NAME VARCHAR(100))");
        $driver->exec("CREATE INDEX IDX_MIG_DROP ON MIG_INDEX_TEST (NAME)");
        $driver->exec("DROP INDEX IDX_MIG_DROP");

        $driver->setQuery("SELECT COUNT(*) FROM RDB\$INDICES WHERE RDB\$INDEX_NAME = 'IDX_MIG_DROP'");
        $this->assertEquals(0, (int) $driver->loadResult());
    }

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canCreateCompositeIndex(string $dbName, Driver $driver): void
    {
        if (!$this->requiresFirebird($driver)) {
            return;
        }

        $driver->exec("CREATE TABLE MIG_INDEX_TEST (ID INTEGER PRIMARY KEY, CATEGORY VARCHAR(50), STATUS VARCHAR(20))");
        $driver->exec("CREATE INDEX IDX_MIG_COMPOSITE ON MIG_INDEX_TEST (CATEGORY, STATUS)");

        $driver->setQuery("SELECT COUNT(*) FROM RDB\$INDEX_SEGMENTS WHERE RDB\$INDEX_NAME = 'IDX_MIG_COMPOSITE'");
        $this->assertEquals(2, (int) $driver->loadResult());
    }

    // =========================================================================
    // DDL: Foreign Key Operations
    // =========================================================================

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canCreateForeignKey(string $dbName, Driver $driver): void
    {
        if (!$this->requiresFirebird($driver)) {
            return;
        }

        $driver->exec("CREATE TABLE MIG_FK_PARENT (ID INTEGER PRIMARY KEY, NAME VARCHAR(100))");
        $driver->exec("
            CREATE TABLE MIG_FK_CHILD (
                ID INTEGER PRIMARY KEY, PARENT_ID INTEGER,
                CONSTRAINT FK_CHILD_PARENT FOREIGN KEY (PARENT_ID) REFERENCES MIG_FK_PARENT(ID)
            )
        ");

        $driver->setQuery("SELECT COUNT(*) FROM RDB\$REF_CONSTRAINTS WHERE RDB\$CONSTRAINT_NAME = 'FK_CHILD_PARENT'");
        $this->assertEquals(1, (int) $driver->loadResult());
    }

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canDropForeignKey(string $dbName, Driver $driver): void
    {
        if (!$this->requiresFirebird($driver)) {
            return;
        }

        $driver->exec("CREATE TABLE MIG_FK_PARENT (ID INTEGER PRIMARY KEY)");
        $driver->exec("
            CREATE TABLE MIG_FK_CHILD (
                ID INTEGER PRIMARY KEY, PARENT_ID INTEGER,
                CONSTRAINT FK_DROP_TEST FOREIGN KEY (PARENT_ID) REFERENCES MIG_FK_PARENT(ID)
            )
        ");
        $driver->exec("ALTER TABLE MIG_FK_CHILD DROP CONSTRAINT FK_DROP_TEST");

        $driver->setQuery("SELECT COUNT(*) FROM RDB\$REF_CONSTRAINTS WHERE RDB\$CONSTRAINT_NAME = 'FK_DROP_TEST'");
        $this->assertEquals(0, (int) $driver->loadResult());
    }

    // =========================================================================
    // Views
    // =========================================================================

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canCreateView(string $dbName, Driver $driver): void
    {
        if (!$this->requiresFirebird($driver)) {
            return;
        }

        $driver->exec("
            CREATE TABLE MIG_VIEW_CRE (
                ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                NAME VARCHAR(100),
                STATUS VARCHAR(20) DEFAULT 'active'
            )
        ");
        $driver->exec("INSERT INTO MIG_VIEW_CRE (NAME) VALUES ('Test')");
        $driver->exec("CREATE VIEW MIG_TEST_VIEW_CRE AS SELECT ID, NAME FROM MIG_VIEW_CRE WHERE STATUS = 'active'");

        $driver->setQuery("SELECT COUNT(*) FROM MIG_TEST_VIEW_CRE");
        $this->assertGreaterThanOrEqual(1, (int) $driver->loadResult());
    }

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canReplaceView(string $dbName, Driver $driver): void
    {
        if (!$this->requiresFirebird($driver)) {
            return;
        }

        $driver->exec("
            CREATE TABLE MIG_VIEW_REP (
                ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                NAME VARCHAR(100), EMAIL VARCHAR(100), STATUS VARCHAR(20)
            )
        ");
        $driver->exec("CREATE VIEW MIG_REPLACE_VIEW AS SELECT ID FROM MIG_VIEW_REP");

        // Firebird < 4 requires drop-then-recreate
        $driver->exec("DROP VIEW MIG_REPLACE_VIEW");
        $driver->exec("CREATE VIEW MIG_REPLACE_VIEW AS SELECT ID, NAME, EMAIL FROM MIG_VIEW_REP");

        $driver->setQuery("
            SELECT rf.RDB\$FIELD_NAME FROM RDB\$RELATION_FIELDS rf
            WHERE rf.RDB\$RELATION_NAME = 'MIG_REPLACE_VIEW'
        ");
        $columns = array_map('trim', $driver->loadColumn());

        $this->assertContains('ID', $columns);
        $this->assertContains('NAME', $columns);
        $this->assertContains('EMAIL', $columns);
    }

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canCheckViewExists(string $dbName, Driver $driver): void
    {
        if (!$this->requiresFirebird($driver)) {
            return;
        }

        $driver->exec("CREATE TABLE MIG_VIEW_EXI (ID INTEGER PRIMARY KEY)");
        $driver->exec("CREATE VIEW MIG_EXISTS_VIEW AS SELECT * FROM MIG_VIEW_EXI");

        $this->assertTrue($driver->viewExists('MIG_EXISTS_VIEW'));
        $this->assertFalse($driver->viewExists('NONEXISTENT_VIEW'));
    }

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canDropView(string $dbName, Driver $driver): void
    {
        if (!$this->requiresFirebird($driver)) {
            return;
        }

        $driver->exec("CREATE TABLE MIG_VIEW_DRO (ID INTEGER PRIMARY KEY)");
        $driver->exec("CREATE VIEW MIG_DROP_VIEW AS SELECT * FROM MIG_VIEW_DRO");

        $this->assertTrue($driver->viewExists('MIG_DROP_VIEW'));
        $driver->exec("DROP VIEW MIG_DROP_VIEW");
        $this->assertFalse($driver->viewExists('MIG_DROP_VIEW'));
    }

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canCreateAndQueryViewOnData(string $dbName, Driver $driver): void
    {
        if (!$this->requiresFirebird($driver)) {
            return;
        }

        $driver->exec("CREATE VIEW FT_ACTIVE_ITEMS AS SELECT * FROM FT_ITEMS WHERE STATUS = 'active'");

        $driver->setQuery("SELECT COUNT(*) FROM FT_ACTIVE_ITEMS");
        $this->assertGreaterThan(0, $driver->loadResult());

        $driver->transactionCommit();
    }

    // =========================================================================
    // Table Operations
    // =========================================================================

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canTruncateTableViaDelete(string $dbName, Driver $driver): void
    {
        if (!$this->requiresFirebird($driver)) {
            return;
        }

        $driver->exec("
            CREATE TABLE MIG_TRUNCATE (
                ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                NAME VARCHAR(100)
            )
        ");
        $driver->exec("INSERT INTO MIG_TRUNCATE (NAME) VALUES ('one')");
        $driver->exec("INSERT INTO MIG_TRUNCATE (NAME) VALUES ('two')");
        $driver->exec("INSERT INTO MIG_TRUNCATE (NAME) VALUES ('three')");

        $driver->setQuery("SELECT COUNT(*) FROM MIG_TRUNCATE");
        $this->assertEquals(3, (int) $driver->loadResult());

        // Firebird doesn't have TRUNCATE, use DELETE
        $driver->exec("DELETE FROM MIG_TRUNCATE");

        $driver->setQuery("SELECT COUNT(*) FROM MIG_TRUNCATE");
        $this->assertEquals(0, (int) $driver->loadResult());
    }

    // =========================================================================
    // Migration Patterns: Adding Primary Keys with Generators
    // =========================================================================

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canAddPrimaryKeyWithGenerator(string $dbName, Driver $driver): void
    {
        if (!$this->requiresFirebird($driver)) {
            return;
        }

        $driver->exec("CREATE TABLE MIG_ADD_PK (NAME VARCHAR(100), DATA_VAL VARCHAR(100))");
        $driver->exec("ALTER TABLE MIG_ADD_PK ADD ID INTEGER DEFAULT 0 NOT NULL");
        $driver->exec("CREATE GENERATOR GEN_MIG_ADD_PK_ID");
        $driver->exec("SET GENERATOR GEN_MIG_ADD_PK_ID TO 0");
        $driver->exec("
            CREATE TRIGGER TRG_MIG_ADD_PK_BI FOR MIG_ADD_PK
            ACTIVE BEFORE INSERT POSITION 0
            AS BEGIN
                IF (NEW.ID IS NULL OR NEW.ID = 0) THEN
                    NEW.ID = GEN_ID(GEN_MIG_ADD_PK_ID, 1);
            END
        ");
        $driver->exec("ALTER TABLE MIG_ADD_PK ADD CONSTRAINT PK_MIG_ADD_PK PRIMARY KEY (ID)");

        $driver->exec("INSERT INTO MIG_ADD_PK (NAME, DATA_VAL) VALUES ('test1', 'val1')");
        $driver->exec("INSERT INTO MIG_ADD_PK (NAME, DATA_VAL) VALUES ('test2', 'val2')");

        $driver->setQuery("SELECT ID, NAME FROM MIG_ADD_PK ORDER BY ID");
        $rows = $driver->loadObjectList();

        $this->assertCount(2, $rows);
        $this->assertEquals(1, (int) $rows[0]->id);
        $this->assertEquals(2, (int) $rows[1]->id);
    }

    #[Test]
    #[DataProvider('databaseProvider')]
    public function identityColumnAutoIncrements(string $dbName, Driver $driver): void
    {
        if (!$this->requiresFirebird($driver)) {
            return;
        }

        $driver->exec("
            CREATE TABLE MIG_IDEMPOTENT (
                ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                NAME VARCHAR(100)
            )
        ");

        $driver->exec("INSERT INTO MIG_IDEMPOTENT (NAME) VALUES ('first')");
        $driver->exec("INSERT INTO MIG_IDEMPOTENT (NAME) VALUES ('second')");

        $driver->setQuery("SELECT ID, NAME FROM MIG_IDEMPOTENT ORDER BY ID");
        $rows = $driver->loadObjectList();

        $this->assertCount(2, $rows);
        $this->assertEquals(1, (int) $rows[0]->id);
        $this->assertEquals(2, (int) $rows[1]->id);
    }

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canAddCustomNamedPrimaryKey(string $dbName, Driver $driver): void
    {
        if (!$this->requiresFirebird($driver)) {
            return;
        }

        $driver->exec("CREATE TABLE MIG_CUSTOM_PK (NAME VARCHAR(100))");
        $driver->exec("ALTER TABLE MIG_CUSTOM_PK ADD RECORD_ID INTEGER NOT NULL");
        $driver->exec("CREATE GENERATOR GEN_MIG_CUSTOM_PK_ID");
        $driver->exec("
            CREATE TRIGGER TRG_MIG_CUSTOM_PK FOR MIG_CUSTOM_PK
            BEFORE INSERT AS BEGIN
                IF (NEW.RECORD_ID IS NULL) THEN
                    NEW.RECORD_ID = GEN_ID(GEN_MIG_CUSTOM_PK_ID, 1);
            END
        ");
        $driver->exec("ALTER TABLE MIG_CUSTOM_PK ADD CONSTRAINT PK_MIG_CUSTOM PRIMARY KEY (RECORD_ID)");

        $driver->exec("INSERT INTO MIG_CUSTOM_PK (NAME) VALUES ('test')");
        $driver->setQuery("SELECT RECORD_ID FROM MIG_CUSTOM_PK");

        $this->assertEquals(1, (int) $driver->loadResult());
    }

    // =========================================================================
    // Migration Patterns: Complex Scenarios
    // =========================================================================

    #[Test]
    #[DataProvider('databaseProvider')]
    public function complexMigrationAddsPkToLegacyTable(string $dbName, Driver $driver): void
    {
        if (!$this->requiresFirebird($driver)) {
            return;
        }

        $driver->exec("CREATE TABLE MIG_COMPLEX (AUTHOR_ID INTEGER, RESOURCE_ID INTEGER, ORDERING INTEGER)");
        $driver->exec("INSERT INTO MIG_COMPLEX VALUES (1, 100, 1)");
        $driver->exec("INSERT INTO MIG_COMPLEX VALUES (2, 100, 2)");

        $driver->exec("ALTER TABLE MIG_COMPLEX ADD ID INTEGER DEFAULT 0 NOT NULL");
        $driver->exec("CREATE GENERATOR GEN_MIG_COMPLEX_ID");
        $driver->exec("UPDATE MIG_COMPLEX SET ID = 1 WHERE AUTHOR_ID = 1 AND RESOURCE_ID = 100");
        $driver->exec("UPDATE MIG_COMPLEX SET ID = 2 WHERE AUTHOR_ID = 2 AND RESOURCE_ID = 100");
        $driver->exec("ALTER SEQUENCE GEN_MIG_COMPLEX_ID RESTART WITH 3");
        $driver->exec("ALTER TABLE MIG_COMPLEX ADD CONSTRAINT PK_MIG_COMPLEX PRIMARY KEY (ID)");
        $driver->exec("
            CREATE TRIGGER TRG_MIG_COMPLEX_BI FOR MIG_COMPLEX
            ACTIVE BEFORE INSERT POSITION 0
            AS BEGIN
                IF (NEW.ID IS NULL OR NEW.ID = 0) THEN
                    NEW.ID = GEN_ID(GEN_MIG_COMPLEX_ID, 1);
            END
        ");
        $driver->exec("CREATE UNIQUE INDEX IDX_MIG_COMPLEX_AR ON MIG_COMPLEX (AUTHOR_ID, RESOURCE_ID)");

        $driver->setQuery("SELECT ID, AUTHOR_ID FROM MIG_COMPLEX ORDER BY ID");
        $rows = $driver->loadObjectList();

        $this->assertCount(2, $rows);
        $this->assertNotEquals($rows[0]->id, $rows[1]->id);

        $driver->exec("INSERT INTO MIG_COMPLEX (AUTHOR_ID, RESOURCE_ID, ORDERING) VALUES (3, 101, 1)");
        $driver->setQuery("SELECT ID FROM MIG_COMPLEX WHERE AUTHOR_ID = 3");
        $this->assertGreaterThan(0, (int) $driver->loadResult());
    }

    #[Test]
    #[DataProvider('databaseProvider')]
    public function resourceAssocMigrationPattern(string $dbName, Driver $driver): void
    {
        if (!$this->requiresFirebird($driver)) {
            return;
        }

        $driver->exec("CREATE TABLE MIG_RESOURCE_ASSOC (PARENT_ID INTEGER, CHILD_ID INTEGER, ORDERING INTEGER)");
        $driver->exec("INSERT INTO MIG_RESOURCE_ASSOC VALUES (1, 10, 1)");
        $driver->exec("INSERT INTO MIG_RESOURCE_ASSOC VALUES (1, 11, 2)");

        $driver->setQuery("
            SELECT COUNT(*) FROM RDB\$RELATION_FIELDS
            WHERE RDB\$RELATION_NAME = 'MIG_RESOURCE_ASSOC' AND TRIM(RDB\$FIELD_NAME) = 'ID'
        ");
        $hasId = (int) $driver->loadResult() > 0;

        if (!$hasId) {
            $driver->exec("ALTER TABLE MIG_RESOURCE_ASSOC ADD ID INTEGER DEFAULT 0 NOT NULL");
            $driver->exec("UPDATE MIG_RESOURCE_ASSOC SET ID = 1 WHERE ORDERING = 1");
            $driver->exec("UPDATE MIG_RESOURCE_ASSOC SET ID = 2 WHERE ORDERING = 2");
            $driver->exec("CREATE GENERATOR GEN_MIG_RESOURCE_ASSOC_ID");
            $driver->exec("ALTER SEQUENCE GEN_MIG_RESOURCE_ASSOC_ID RESTART WITH 3");
            $driver->exec("
                CREATE TRIGGER TRG_MIG_RESOURCE_ASSOC_BI FOR MIG_RESOURCE_ASSOC
                ACTIVE BEFORE INSERT POSITION 0
                AS BEGIN
                    IF (NEW.ID IS NULL OR NEW.ID = 0) THEN
                        NEW.ID = GEN_ID(GEN_MIG_RESOURCE_ASSOC_ID, 1);
                END
            ");
            $driver->exec("ALTER TABLE MIG_RESOURCE_ASSOC ADD CONSTRAINT PK_MIG_RESOURCE_ASSOC PRIMARY KEY (ID)");
        }

        $driver->setQuery("SELECT ID, PARENT_ID, CHILD_ID FROM MIG_RESOURCE_ASSOC ORDER BY ORDERING");
        $rows = $driver->loadObjectList();
        $this->assertCount(2, $rows);
        $this->assertEquals(1, $rows[0]->parent_id);
        $this->assertEquals(10, $rows[0]->child_id);
    }

    // =========================================================================
    // Migration Patterns: Data Type Changes
    // =========================================================================

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canChangeVarcharLength(string $dbName, Driver $driver): void
    {
        if (!$this->requiresFirebird($driver)) {
            return;
        }

        $driver->exec("CREATE TABLE MIG_VARCHAR_LEN (ID INTEGER PRIMARY KEY, TITLE VARCHAR(100))");
        $driver->exec("ALTER TABLE MIG_VARCHAR_LEN ALTER TITLE TYPE VARCHAR(255)");

        $driver->setQuery("
            SELECT f.RDB\$CHARACTER_LENGTH AS char_len
            FROM RDB\$RELATION_FIELDS rf
            JOIN RDB\$FIELDS f ON rf.RDB\$FIELD_SOURCE = f.RDB\$FIELD_NAME
            WHERE rf.RDB\$RELATION_NAME = 'MIG_VARCHAR_LEN' AND TRIM(rf.RDB\$FIELD_NAME) = 'TITLE'
        ");
        $this->assertGreaterThanOrEqual(255, (int) $driver->loadResult());
    }

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canChangeIntegerToBigint(string $dbName, Driver $driver): void
    {
        if (!$this->requiresFirebird($driver)) {
            return;
        }

        $driver->exec("CREATE TABLE MIG_INT_BIGINT (ID INTEGER PRIMARY KEY, COUNTER INTEGER)");
        $driver->exec("ALTER TABLE MIG_INT_BIGINT ALTER COUNTER TYPE BIGINT");

        $driver->setQuery("
            SELECT f.RDB\$FIELD_TYPE
            FROM RDB\$RELATION_FIELDS rf
            JOIN RDB\$FIELDS f ON rf.RDB\$FIELD_SOURCE = f.RDB\$FIELD_NAME
            WHERE rf.RDB\$RELATION_NAME = 'MIG_INT_BIGINT' AND TRIM(rf.RDB\$FIELD_NAME) = 'COUNTER'
        ");
        // Type 16 = BIGINT/INT64 in Firebird
        $this->assertEquals(16, (int) $driver->loadResult());
    }

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canAddDefaultValue(string $dbName, Driver $driver): void
    {
        if (!$this->requiresFirebird($driver)) {
            return;
        }

        $driver->exec("CREATE TABLE MIG_DEFAULTS (ID INTEGER PRIMARY KEY, STATUS VARCHAR(20))");
        $driver->exec("ALTER TABLE MIG_DEFAULTS ALTER STATUS SET DEFAULT 'active'");

        $driver->exec("INSERT INTO MIG_DEFAULTS (ID) VALUES (1)");
        $driver->setQuery("SELECT STATUS FROM MIG_DEFAULTS WHERE ID = 1");
        $this->assertEquals('active', trim($driver->loadResult()));
    }

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canSetColumnNotNull(string $dbName, Driver $driver): void
    {
        if (!$this->requiresFirebird($driver)) {
            return;
        }

        $driver->exec("CREATE TABLE MIG_NOTNULL (ID INTEGER PRIMARY KEY, REQUIRED_FIELD VARCHAR(100))");
        $driver->exec("ALTER TABLE MIG_NOTNULL ALTER REQUIRED_FIELD SET NOT NULL");

        $driver->setQuery("
            SELECT rf.RDB\$NULL_FLAG
            FROM RDB\$RELATION_FIELDS rf
            WHERE rf.RDB\$RELATION_NAME = 'MIG_NOTNULL'
            AND TRIM(rf.RDB\$FIELD_NAME) = 'REQUIRED_FIELD'
        ");
        $this->assertEquals(1, (int) $driver->loadResult());
    }
}
