<?php

/**
 * @package    framework
 * @copyright  Copyright (c) 2005-2020 The Regents of the University of California.
 * @license    http://opensource.org/licenses/MIT MIT
 */

namespace Hubzero\Database\Tests;

use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\Attributes\Group;
use Hubzero\Database\Driver;
use Hubzero\Database\Driver\Oci;
use Hubzero\Database\Schema\TableBuilder;

/**
 * Oracle-specific driver tests
 *
 * Runs against all configured backends via the standard databaseProvider.
 * Tests that receive a non-Oracle driver pass with a no-op assertion.
 *
 * Configuration: Add 'oci' to DB_TEST_BACKENDS and set DB_OCI_*
 * credentials in phpunit.xml or via environment variables.
 */
#[Group('oci')]
#[Group('database')]
class OciDriverTest extends AbstractDriverTestCase
{
    protected static function getTestTables(): array
    {
        return ['ora_items', 'ora_categories'];
    }

    protected static function setUpDatabase(Driver $driver): void
    {
        if (get_class($driver) !== Oci::class) {
            return;
        }

        // Drop in FK-safe order
        foreach (['ora_items', 'ora_categories'] as $table) {
            try {
                $driver->dropTable($table, true);
            } catch (\Exception $e) {
            }
        }

        $driver->exec("
            CREATE TABLE ora_categories (
                id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR2(100) NOT NULL,
                slug VARCHAR2(100),
                sort_order NUMBER(10) DEFAULT 0,
                active NUMBER(1) DEFAULT 1,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        ");

        $driver->exec("
            CREATE TABLE ora_items (
                id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                category_id NUMBER(10),
                title VARCHAR2(200) NOT NULL,
                description CLOB,
                price NUMBER(10,2) DEFAULT 0.00,
                stock NUMBER(10) DEFAULT 0,
                status VARCHAR2(20) DEFAULT 'active',
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT fk_ora_items_cat FOREIGN KEY (category_id)
                    REFERENCES ora_categories(id) ON DELETE SET NULL
            )
        ");

        $driver->exec(
            "CREATE INDEX idx_ora_items_status ON ora_items (status)"
        );

        $driver->exec(
            "INSERT INTO ora_categories (name, slug, sort_order)"
            . " VALUES ('Electronics', 'electronics', 1)"
        );
        $driver->exec(
            "INSERT INTO ora_categories (name, slug, sort_order)"
            . " VALUES ('Books', 'books', 2)"
        );
        $driver->exec(
            "INSERT INTO ora_categories (name, slug, sort_order, active)"
            . " VALUES ('Archived', 'archived', 99, 0)"
        );

        $driver->exec(
            "INSERT INTO ora_items (category_id, title, price, stock, status)"
            . " VALUES (1, 'Laptop', 999.99, 10, 'active')"
        );
        $driver->exec(
            "INSERT INTO ora_items (category_id, title, price, stock, status)"
            . " VALUES (1, 'Phone', 599.99, 25, 'active')"
        );
        $driver->exec(
            "INSERT INTO ora_items (category_id, title, price, stock, status)"
            . " VALUES (2, 'Novel', 19.99, 100, 'active')"
        );
        $driver->exec(
            "INSERT INTO ora_items (category_id, title, price, stock, status)"
            . " VALUES (2, 'Textbook', 79.99, 5, 'draft')"
        );
    }

    private function requiresOracle(Driver $driver): bool
    {
        if (get_class($driver) !== Oci::class) {
            $this->assertTrue(true);
            return false;
        }
        return true;
    }

    protected function tearDown(): void
    {
        parent::tearDown();

        $adHocViews = ['ora_test_view', 'ora_active_items'];
        $adHocTables = [
            'ora_rename_dest', 'ora_rename_src',
            'ora_fk_child', 'ora_fk_parent',
            'ora_ddl_test', 'ora_trunc_test',
            'ora_identity_test', 'ora_view_src',
            'ora_pk_test',
        ];
        $adHocSequences = ['ora_test_seq'];

        foreach (static::getClassDrivers() as $driver) {
            if (get_class($driver) !== Oci::class) {
                continue;
            }
            foreach ($adHocViews as $view) {
                try {
                    $driver->dropView($view, true);
                } catch (\Exception $e) {
                }
            }
            foreach ($adHocTables as $table) {
                try {
                    $driver->dropTable($table, true);
                } catch (\Exception $e) {
                }
            }
            foreach ($adHocSequences as $seq) {
                try {
                    $driver->dropSequence($seq, true);
                } catch (\Exception $e) {
                }
            }
        }
    }

    public static function tearDownAfterClass(): void
    {
        foreach (static::getClassDrivers() as $driver) {
            if (get_class($driver) !== Oci::class) {
                continue;
            }
            try {
                $driver->dropView('ora_active_items', true);
            } catch (\Exception $e) {
            }
        }

        parent::tearDownAfterClass();
    }

    #[Test]
    #[DataProvider('databaseProvider')]
    public function oracleGrammarDelegationMatchesGenericCreateCompilation(string $dbName, Driver $driver): void
    {
        if (!$this->requiresOracle($driver)) {
            return;
        }

        $fallbackGrammar = new class ($driver) extends \Hubzero\Database\Schema\Grammars\OciGrammar {
            public function compileCreateTableFromDefinition(array $definition): array
            {
                return parent::compileCreateTableFromDefinition($definition);
            }
        };

        $delegated = new TableBuilder($driver, 'parity_oracle_items');
        $delegated->id()
            ->string('name', 80)
            ->integer('status')->default(1)
            ->index('idx_name', 'name')
            ->uniqueIndex('uidx_name', 'name')
            ->foreign('group_id', 'parity_groups', 'id', 'CASCADE', 'RESTRICT')
            ->ifNotExists(false);

        $fallback = new class ($driver, 'parity_oracle_items', $fallbackGrammar) extends TableBuilder {
            private \Hubzero\Database\Schema\Grammar $grammar;

            public function __construct(
                Driver $driver,
                string $table,
                \Hubzero\Database\Schema\Grammar $grammar
            ) {
                parent::__construct($driver, $table);
                $this->grammar = $grammar;
            }

            protected function getGrammar()
            {
                return $this->grammar;
            }
        };

        $fallback->id()
            ->string('name', 80)
            ->integer('status')->default(1)
            ->index('idx_name', 'name')
            ->uniqueIndex('uidx_name', 'name')
            ->foreign('group_id', 'parity_groups', 'id', 'CASCADE', 'RESTRICT')
            ->ifNotExists(false);

        $this->assertSame($fallback->toSqlStatements(), $delegated->toSqlStatements());
    }

    // =========================================================================
    // Connection & Server Info
    // =========================================================================

    #[Test]
    #[DataProvider('databaseProvider')]
    public function driverIsOracleInstance(
        string $dbName,
        Driver $driver
    ): void {
        if (!$this->requiresOracle($driver)) {
            return;
        }

        $this->assertSame(Oci::class, get_class($driver));
    }

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canExecuteBasicQuery(
        string $dbName,
        Driver $driver
    ): void {
        if (!$this->requiresOracle($driver)) {
            return;
        }

        $driver->setQuery('SELECT 1 AS val FROM DUAL');
        $this->assertEquals(1, $driver->loadResult());
    }

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canGetVersion(string $dbName, Driver $driver): void
    {
        if (!$this->requiresOracle($driver)) {
            return;
        }

        $version = $driver->getVersion();
        $this->assertNotEmpty($version);
    }

    // =========================================================================
    // Schema Introspection via Driver API
    // =========================================================================

    #[Test]
    #[DataProvider('databaseProvider')]
    public function tableExistsReturnsTrueForExistingTable(
        string $dbName,
        Driver $driver
    ): void {
        if (!$this->requiresOracle($driver)) {
            return;
        }

        $this->assertTrue($driver->tableExists('ora_categories'));
    }

    #[Test]
    #[DataProvider('databaseProvider')]
    public function tableExistsReturnsFalseForMissingTable(
        string $dbName,
        Driver $driver
    ): void {
        if (!$this->requiresOracle($driver)) {
            return;
        }

        $this->assertFalse(
            $driver->tableExists('ora_nonexistent_table')
        );
    }

    #[Test]
    #[DataProvider('databaseProvider')]
    public function getTableListIncludesTestTables(
        string $dbName,
        Driver $driver
    ): void {
        if (!$this->requiresOracle($driver)) {
            return;
        }

        $tables = $driver->getTableList();

        $this->assertContains('ora_categories', $tables);
        $this->assertContains('ora_items', $tables);
    }

    #[Test]
    #[DataProvider('databaseProvider')]
    public function getTableColumnsTypeOnly(
        string $dbName,
        Driver $driver
    ): void {
        if (!$this->requiresOracle($driver)) {
            return;
        }

        $columns = $driver->getTableColumns('ora_categories', true);

        $this->assertArrayHasKey('id', $columns);
        $this->assertArrayHasKey('name', $columns);
        $this->assertArrayHasKey('slug', $columns);
    }

    #[Test]
    #[DataProvider('databaseProvider')]
    public function getPrimaryKeyReturnsColumnName(
        string $dbName,
        Driver $driver
    ): void {
        if (!$this->requiresOracle($driver)) {
            return;
        }

        $pk = $driver->getPrimaryKey('ora_categories');
        $this->assertNotNull($pk);
    }

    #[Test]
    #[DataProvider('databaseProvider')]
    public function getForeignKeysForChildTable(
        string $dbName,
        Driver $driver
    ): void {
        if (!$this->requiresOracle($driver)) {
            return;
        }

        $fks = $driver->getForeignKeys('ora_items');
        $this->assertNotEmpty(
            $fks,
            'ora_items should have a foreign key on category_id'
        );
    }

    // =========================================================================
    // CRUD Operations
    // =========================================================================

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canSelectAll(string $dbName, Driver $driver): void
    {
        if (!$this->requiresOracle($driver)) {
            return;
        }

        $driver->setQuery(
            'SELECT * FROM ora_categories ORDER BY id'
        );
        $rows = $driver->loadObjectList();

        $this->assertCount(3, $rows);
        $this->assertEquals('Electronics', $rows[0]->name);
    }

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canSelectWithWhere(
        string $dbName,
        Driver $driver
    ): void {
        if (!$this->requiresOracle($driver)) {
            return;
        }

        $driver->setQuery(
            "SELECT * FROM ora_items WHERE status = 'active'"
        );
        $this->assertCount(3, $driver->loadObjectList());
    }

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canSelectWithJoin(
        string $dbName,
        Driver $driver
    ): void {
        if (!$this->requiresOracle($driver)) {
            return;
        }

        $driver->setQuery("
            SELECT i.title, c.name AS category_name
            FROM ora_items i
            JOIN ora_categories c ON i.category_id = c.id
            ORDER BY i.id
        ");
        $items = $driver->loadObjectList();
        $this->assertCount(4, $items);
        $this->assertEquals('Electronics', $items[0]->category_name);
    }

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canInsertRecord(
        string $dbName,
        Driver $driver
    ): void {
        if (!$this->requiresOracle($driver)) {
            return;
        }

        $driver->exec(
            "INSERT INTO ora_categories (name, slug)"
            . " VALUES ('Test', 'test-insert')"
        );

        $driver->setQuery(
            "SELECT name FROM ora_categories WHERE slug = 'test-insert'"
        );
        $this->assertEquals('Test', $driver->loadResult());

        $driver->exec(
            "DELETE FROM ora_categories WHERE slug = 'test-insert'"
        );
    }

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canUpdateRecord(
        string $dbName,
        Driver $driver
    ): void {
        if (!$this->requiresOracle($driver)) {
            return;
        }

        $driver->exec(
            "INSERT INTO ora_categories (name, slug)"
            . " VALUES ('Before', 'update-test')"
        );
        $driver->exec(
            "UPDATE ora_categories SET name = 'After'"
            . " WHERE slug = 'update-test'"
        );

        $driver->setQuery(
            "SELECT name FROM ora_categories"
            . " WHERE slug = 'update-test'"
        );
        $this->assertEquals('After', $driver->loadResult());

        $driver->exec(
            "DELETE FROM ora_categories WHERE slug = 'update-test'"
        );
    }

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canDeleteRecord(
        string $dbName,
        Driver $driver
    ): void {
        if (!$this->requiresOracle($driver)) {
            return;
        }

        $driver->exec(
            "INSERT INTO ora_categories (name, slug)"
            . " VALUES ('Delete Me', 'delete-test')"
        );
        $driver->exec(
            "DELETE FROM ora_categories WHERE slug = 'delete-test'"
        );

        $driver->setQuery(
            "SELECT COUNT(*) FROM ora_categories"
            . " WHERE slug = 'delete-test'"
        );
        $this->assertEquals(0, $driver->loadResult());
    }

    // =========================================================================
    // Transactions
    // =========================================================================

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canCommitTransaction(
        string $dbName,
        Driver $driver
    ): void {
        if (!$this->requiresOracle($driver)) {
            return;
        }

        $driver->transactionStart();
        $driver->exec(
            "INSERT INTO ora_categories (name, slug)"
            . " VALUES ('Committed', 'trans-commit')"
        );
        $driver->transactionCommit();

        $driver->setQuery(
            "SELECT COUNT(*) FROM ora_categories"
            . " WHERE slug = 'trans-commit'"
        );
        $this->assertEquals(1, $driver->loadResult());

        $driver->exec(
            "DELETE FROM ora_categories WHERE slug = 'trans-commit'"
        );
    }

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canRollbackTransaction(
        string $dbName,
        Driver $driver
    ): void {
        if (!$this->requiresOracle($driver)) {
            return;
        }

        $config = static::$testDatabases[$dbName];
        $driver2 = new Oci($config);
        $driver2->connect();

        $driver2->transactionStart();
        $driver2->exec(
            "INSERT INTO ora_categories (name, slug)"
            . " VALUES ('Rolled Back', 'trans-rollback')"
        );
        $driver2->transactionRollback();

        $driver->setQuery(
            "SELECT COUNT(*) FROM ora_categories"
            . " WHERE slug = 'trans-rollback'"
        );
        $count = (int) $driver->loadResult();

        $driver2->disconnect();

        $this->assertEquals(
            0,
            $count,
            'Rolled back row should not be visible'
        );
    }

    // =========================================================================
    // Oracle SQL Features
    // =========================================================================

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canUseAggregateFunctions(
        string $dbName,
        Driver $driver
    ): void {
        if (!$this->requiresOracle($driver)) {
            return;
        }

        $driver->setQuery("
            SELECT COUNT(*) AS cnt, SUM(stock) AS total_stock,
                   MIN(price) AS min_price, MAX(price) AS max_price
            FROM ora_items
        ");
        $row = $driver->loadObject();

        $this->assertEquals(4, $row->cnt);
        $this->assertEquals(140, $row->total_stock);
        $this->assertEquals(19.99, (float) $row->min_price);
        $this->assertEquals(999.99, (float) $row->max_price);
    }

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canUseDualTable(
        string $dbName,
        Driver $driver
    ): void {
        if (!$this->requiresOracle($driver)) {
            return;
        }

        $driver->setQuery("SELECT SYSDATE FROM DUAL");
        $this->assertNotEmpty($driver->loadResult());
    }

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canUseNvlForNullCoalescing(
        string $dbName,
        Driver $driver
    ): void {
        if (!$this->requiresOracle($driver)) {
            return;
        }

        $driver->setQuery(
            "SELECT NVL(NULL, 'fallback') AS result FROM DUAL"
        );
        $this->assertEquals('fallback', $driver->loadResult());
    }

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canConcatenateWithDoubleBar(
        string $dbName,
        Driver $driver
    ): void {
        if (!$this->requiresOracle($driver)) {
            return;
        }

        $driver->setQuery(
            "SELECT 'Hello' || ' ' || 'World' AS greeting FROM DUAL"
        );
        $this->assertEquals('Hello World', $driver->loadResult());
    }

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canUseCaseExpression(
        string $dbName,
        Driver $driver
    ): void {
        if (!$this->requiresOracle($driver)) {
            return;
        }

        $driver->setQuery("
            SELECT title,
                CASE status
                    WHEN 'active' THEN 'Available'
                    WHEN 'draft' THEN 'Coming Soon'
                    ELSE 'Unknown'
                END AS label
            FROM ora_items ORDER BY id
        ");
        $items = $driver->loadObjectList();

        $this->assertEquals('Available', $items[0]->label);
        $this->assertEquals('Coming Soon', $items[3]->label);
    }

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canGroupByWithHaving(
        string $dbName,
        Driver $driver
    ): void {
        if (!$this->requiresOracle($driver)) {
            return;
        }

        $driver->setQuery("
            SELECT category_id, COUNT(*) AS cnt
            FROM ora_items
            WHERE category_id IS NOT NULL
            GROUP BY category_id
            HAVING COUNT(*) >= 2
        ");
        $this->assertCount(2, $driver->loadObjectList());
    }

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canUseSubquery(
        string $dbName,
        Driver $driver
    ): void {
        if (!$this->requiresOracle($driver)) {
            return;
        }

        $driver->setQuery("
            SELECT * FROM ora_items
            WHERE category_id IN (
                SELECT id FROM ora_categories WHERE active = 1
            )
        ");
        $this->assertCount(4, $driver->loadObjectList());
    }

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canUseFetchFirstForLimit(
        string $dbName,
        Driver $driver
    ): void {
        if (!$this->requiresOracle($driver)) {
            return;
        }

        // Oracle 12c+ FETCH FIRST syntax
        $driver->setQuery(
            'SELECT * FROM ora_items ORDER BY id'
            . ' FETCH FIRST 2 ROWS ONLY'
        );
        $this->assertCount(2, $driver->loadObjectList());
    }

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canUseOffsetFetch(
        string $dbName,
        Driver $driver
    ): void {
        if (!$this->requiresOracle($driver)) {
            return;
        }

        $driver->setQuery(
            'SELECT * FROM ora_items ORDER BY id'
            . ' OFFSET 1 ROWS FETCH NEXT 2 ROWS ONLY'
        );
        $items = $driver->loadObjectList();

        $this->assertCount(2, $items);
        $this->assertEquals('Phone', $items[0]->title);
    }

    // =========================================================================
    // Sequences
    // =========================================================================

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canCreateAndUseSequence(
        string $dbName,
        Driver $driver
    ): void {
        if (!$this->requiresOracle($driver)) {
            return;
        }

        $this->assertTrue(
            $driver->createSequence('ora_test_seq', 100)
        );
        $this->assertTrue($driver->sequenceExists('ora_test_seq'));

        $val = $driver->nextSequenceValue('ora_test_seq');
        $this->assertEquals(100, $val);

        $val = $driver->nextSequenceValue('ora_test_seq');
        $this->assertEquals(101, $val);

        $sequences = $driver->getSequences();
        $this->assertContains('ora_test_seq', $sequences);

        $this->assertTrue($driver->dropSequence('ora_test_seq'));
        $this->assertFalse($driver->sequenceExists('ora_test_seq'));
    }

    // =========================================================================
    // Views
    // =========================================================================

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canManageViews(string $dbName, Driver $driver): void
    {
        if (!$this->requiresOracle($driver)) {
            return;
        }

        $this->assertTrue($driver->createOrReplaceView(
            'ora_active_items',
            "SELECT id, title FROM ora_items WHERE status = 'active'"
        ));
        $this->assertTrue($driver->viewExists('ora_active_items'));

        $driver->setQuery("SELECT COUNT(*) FROM ora_active_items");
        $this->assertEquals(3, $driver->loadResult());

        $views = $driver->getViews();
        $this->assertContains('ora_active_items', $views);

        $this->assertFalse(
            $driver->viewExists('ora_nonexistent_view')
        );

        $this->assertTrue($driver->dropView('ora_active_items'));
        $this->assertFalse($driver->viewExists('ora_active_items'));
    }

    // =========================================================================
    // DDL: Column Operations
    // =========================================================================

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canAddAndDropColumn(
        string $dbName,
        Driver $driver
    ): void {
        if (!$this->requiresOracle($driver)) {
            return;
        }

        $driver->exec(
            "CREATE TABLE ora_ddl_test"
            . " (id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
            . " name VARCHAR2(100))"
        );

        $this->assertTrue(
            $driver->addColumn('ora_ddl_test', 'email', 'VARCHAR2(200)')
        );
        $columns = $driver->getTableColumns('ora_ddl_test', true);
        $this->assertArrayHasKey('email', $columns);

        $this->assertTrue(
            $driver->dropColumn('ora_ddl_test', 'email')
        );
        $columns = $driver->getTableColumns('ora_ddl_test', true);
        $this->assertArrayNotHasKey('email', $columns);
    }

    // =========================================================================
    // Table Operations
    // =========================================================================

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canTruncateTable(
        string $dbName,
        Driver $driver
    ): void {
        if (!$this->requiresOracle($driver)) {
            return;
        }

        $driver->exec(
            "CREATE TABLE ora_trunc_test"
            . " (id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
            . " name VARCHAR2(50))"
        );
        $driver->exec(
            "INSERT INTO ora_trunc_test (name) VALUES ('one')"
        );
        $driver->exec(
            "INSERT INTO ora_trunc_test (name) VALUES ('two')"
        );

        $driver->setQuery("SELECT COUNT(*) FROM ora_trunc_test");
        $this->assertEquals(2, $driver->loadResult());

        $driver->truncateTable('ora_trunc_test');

        $driver->setQuery("SELECT COUNT(*) FROM ora_trunc_test");
        $this->assertEquals(0, $driver->loadResult());
    }

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canRenameTable(
        string $dbName,
        Driver $driver
    ): void {
        if (!$this->requiresOracle($driver)) {
            return;
        }

        $driver->exec(
            "CREATE TABLE ora_rename_src"
            . " (id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
            . " name VARCHAR2(50))"
        );
        $driver->exec(
            "INSERT INTO ora_rename_src (name) VALUES ('test')"
        );

        $driver->renameTable('ora_rename_src', 'ora_rename_dest');

        $this->assertTrue($driver->tableExists('ora_rename_dest'));
        $this->assertFalse($driver->tableExists('ora_rename_src'));

        $driver->setQuery("SELECT name FROM ora_rename_dest");
        $this->assertEquals('test', $driver->loadResult());
    }

    // =========================================================================
    // Query Builder Integration
    // =========================================================================

    #[Test]
    #[DataProvider('databaseProvider')]
    public function queryBuilderSelectWithLimit(
        string $dbName,
        Driver $driver
    ): void {
        if (!$this->requiresOracle($driver)) {
            return;
        }

        $items = $driver->getQuery()
            ->select('*')
            ->from('ora_items')
            ->order('id', 'asc')
            ->limit(2)
            ->fetch('rows');

        $this->assertCount(2, $items);
    }

    #[Test]
    #[DataProvider('databaseProvider')]
    public function queryBuilderSelectWithOffset(
        string $dbName,
        Driver $driver
    ): void {
        if (!$this->requiresOracle($driver)) {
            return;
        }

        $items = $driver->getQuery()
            ->select('*')
            ->from('ora_items')
            ->order('id', 'asc')
            ->limit(2)
            ->start(1)
            ->fetch('rows');

        $this->assertCount(2, $items);
        $this->assertEquals('Phone', $items[0]->title);
    }

    #[Test]
    #[DataProvider('databaseProvider')]
    public function queryBuilderWhereInSubquery(
        string $dbName,
        Driver $driver
    ): void {
        if (!$this->requiresOracle($driver)) {
            return;
        }

        $items = $driver->getQuery()
            ->select('*')
            ->from('ora_items')
            ->whereIn('category_id', function ($sub) {
                $sub->select('id')
                    ->from('ora_categories')
                    ->whereEquals('active', 1);
            })
            ->fetch('rows');

        $this->assertCount(4, $items);
    }

    #[Test]
    #[DataProvider('databaseProvider')]
    public function queryBuilderHandlesEmptyWhereIn(
        string $dbName,
        Driver $driver
    ): void {
        if (!$this->requiresOracle($driver)) {
            return;
        }

        $items = $driver->getQuery()
            ->select('*')
            ->from('ora_items')
            ->whereIn('id', [])
            ->fetch('rows');

        $this->assertCount(0, $items);
    }

    // =========================================================================
    // Feature Detection
    // =========================================================================

    #[Test]
    #[DataProvider('databaseProvider')]
    public function featureDetectionReturnsExpectedValues(
        string $dbName,
        Driver $driver
    ): void {
        if (!$this->requiresOracle($driver)) {
            return;
        }

        $this->assertFalse($driver->supportsEngine());
        $this->assertFalse($driver->supportsEnum());
        $this->assertFalse($driver->supportsUnsigned());
        $this->assertFalse($driver->supportsColumnPositioning());
        $this->assertTrue($driver->supportsSequences());
        $this->assertTrue($driver->supportsCTE());
        $this->assertTrue($driver->supportsWindowFunctions());
        $this->assertTrue($driver->supportsJson());
    }

    // =========================================================================
    // Schema Builder Integration
    // =========================================================================

    #[Test]
    #[DataProvider('databaseProvider')]
    public function canUseCreateTableBuilder(
        string $dbName,
        Driver $driver
    ): void {
        if (!$this->requiresOracle($driver)) {
            return;
        }

        $driver->createTable('ora_ddl_test')
            ->id()
            ->string('name', 100)
            ->integer('score')->default(0)->nullable()
            ->execute();

        $this->assertTrue($driver->tableExists('ora_ddl_test'));

        $columns = $driver->getTableColumns('ora_ddl_test', true);
        $this->assertArrayHasKey('id', $columns);
        $this->assertArrayHasKey('name', $columns);
        $this->assertArrayHasKey('score', $columns);
    }
}
