<?php
/**
 * HUBzero CMS
 *
 * Copyright 2005-2015 HUBzero Foundation, LLC.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 *
 * HUBzero is a registered trademark of Purdue University.
 *
 * @package   hubzero-cms
 * @author    Christopher Smoak <csmoak@purdue.edu>
 * @copyright Copyright 2005-2015 HUBzero Foundation, LLC.
 * @license   http://opensource.org/licenses/MIT MIT
 */

// No direct access.
defined('_HZEXEC_') or die();
?>
<article>
	<h1>Resources FAQ's</h1>

	<nav>
		<ul>
			<li>
				<a href="#whatareresources">What are resources?</a>
			</li>
			<li>
				<a href="#uploadresources">How do I upload a new resource?</a>
			</li>
			<li>
				<a href="#deleteresources">How can I delete a resource?</a>
			</li>
			<li>
				<a href="#resourcelimit">Is there a limit on the number of resources I can submit?</a>
			</li>
		</ul>
	</nav>

	<section id="whatareresources">
		<h3>What are resources?</h3>
		<p>Think of a hub as an empty library. Resources are items on the shelves. Unlike a traditional library, resources not only be publications, but also videos, tools, animations, and other types. Anyone can upload resources, although some hubs require moderation and approval before a resource is posted.</p>
	</section>

	<section id="uploadresources">
		<h3>How do I upload a new resource?</h3>
		<p>You can submit a new resource with our <a target="_blank" href="<?php echo rtrim(Request::base(true), '/'); ?>/resources/new">contribution section.</a> This will guide you, step-by-step, through the process. If you get interrupted during the submission process, no problem. The hub will remember where you left off. Submissions may be worked on at your leisure and submitted at any future date when you feel they are ready.</p>
	</section>

	<section id="deleteresources">
		<h3>How can I delete a resource?</h3>
		<p>Currently, you can't. This is partly because others may reference your resource in journal articles, and it would be wrong for it to suddenly disappear. Instead, resources are normally "retired," or put in a state where they can be seen but not downloaded or used. If you wish to have a resource retired or completely removed, please contact our support and we will work with you to address the issue.</p>
	</section>

	<section id="resourcelimit">
		<h3>Is there a limit on the number of resources I can submit?</h3>
		<p>No. Think of resources as publications or presentations that you would be proud to have others find in the library. It usually takes time to produce high-quality resources, but there is no limit on the amount that you can contribute</p>
	</section>
</article>