<?php
/**
 * @package    hubzero-cms
 * @copyright  Copyright 2005-2019 HUBzero Foundation, LLC.
 * @license    http://opensource.org/licenses/MIT MIT
 */
?>
<article>
	<h1>Resources Help</h1>
	<p>Think of a hub as an empty library. Resources are items on the shelves. Unlike a traditional library, resources not only be publications, but also videos, tools, animations, and other types. Anyone can upload resources, although some hubs require moderation and approval before a resource is posted.</p>
	<ul>
		<li>
			<a href="<?php echo Route::url('index.php?option=com_help&component=resources&page=faqs'); ?>">FAQ's</a>
		</li>
		<li>
			<a href="<?php echo Route::url('index.php?option=com_help&component=resources&page=rating'); ?>">Rating a Resource</a>
		</li>
		<li>
			<a href="<?php echo Route::url('index.php?option=com_help&component=resources&page=video'); ?>">How to View/Download Video Content?</a>
		</li>
	</ul>
</article>