<?php
/**
 * @package    hubzero-cms
 * @copyright  Copyright (c) 2005-2020 The Regents of the University of California.
 * @license    http://opensource.org/licenses/MIT MIT
 */
?>
<article>
	<h1>Rating A Resource</h1>

	<p>Every resource has two sets of stars: the average rating and your rating. If you haven't rated a resource, you're rating will show up as a set of slightly grayed out stars.</p>
	<p>To rate the resource, hover over your rating stars. The stars will change to red depending on where your cursor is. If you want a four star rating, move the cursor until you see four red stars and then click. You will be taken to a form where you can then add comments, suggestions, and even tags. If you'd like to remain anonymous, be sure to check the box. Otherwise, your name will show up next to your rating and your comments on the resource page.</p>
</article>