<?php
/**
 * @package    hubzero-cms
 * @copyright  Copyright 2005-2019 HUBzero Foundation, LLC.
 * @license    http://opensource.org/licenses/MIT MIT
 */
?>
<article>
	<h1>How to View/Download Video Content?</h1>

	<section>
		<p>While almost any video format can be uploaded to a hub, the most common (and recommended) format is MP4 (MPEG-4), also known as M4V (MPEG-4 Video). Most modern operating systems come equipped for viewing this format directly on your computer. If you do not already have the necessary software to view the videos, there are a variety of players available across most operating systems easily discoverable from a quick query in your favorite search engine.</p>
	</section>

	<section>
		<h2>Downloading Video and Audio Content</h2>
		<p>Most of the hub's video and audio content is downloadable. Procedures vary depending on the browser you are using:</p>
		<ul>
			<li>
				<strong>chrome</strong> Right click (hold click for Mac) on the resource link, select "Download linked file", a dialog box will appear allowing you to save document as a file.
			</li>
			<li>
				<strong>Firefox</strong> Right click (hold click for Mac) on the resource link, select "Save Link As...", a dialog box will appear allowing you to save document as a file.
			</li>
			<li>
				<strong>Internet Explorer</strong> Right click on the resource link, then select "Save Target As...", a dialog box will appear allowing you to save document as a file. Mac users should drag the link to their desktop or folder and the document will be downloaded.
			</li>
			<li>
				<strong>Safari</strong> Control-click on the resource link, then select "Download Linked File", the document will download to your download's folder. The download folder is specified using the Preferences menu and selecting the General tab.
			</li>
		</ul>
	</section>

	<section>
		<h2>Continued Problems</h2>
		<p><strong>If the problem persists, please send us a <a target="_blank" href="<?php echo Route::url('index.php?option=com_support&task=new'); ?>">trouble report.</a></strong></p>
	</section>
</article>