<?php
/**
 * HUBzero CMS
 *
 * Copyright 2005-2015 HUBzero Foundation, LLC.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 *
 * HUBzero is a registered trademark of Purdue University.
 *
 * @package   hubzero-cms
 * @author    Christopher Smoak <csmoak@purdue.edu>
 * @copyright Copyright 2005-2015 HUBzero Foundation, LLC.
 * @license   http://opensource.org/licenses/MIT MIT
 */

// No direct access.
defined('_HZEXEC_') or die();
?>
<article>
	<h1>How to View/Download Video Content?</h1>

	<section>
		<p>This hub relies on two formats of video files, MP4 (MPEG-4) mostly used for podcasts but also can be viewed directly on your computer, and Windows Media Player which is used by older lectures and seminars. In general we suggest Apple Quicktime for playing MP4 files, however there are a variety of MP4 players available.
		We recommend VideoLAN.org's <a target="_blank" href="http://www.videolan.org/">VLC - Media Player</a>, a free cross-platform media player that supports a large number of multimedia formats, without the need for additional codecs. It will play both the MP4 and Windows Media Player files. You will have to copy and paste the video URL from your browser to the VLC player (menu file->open network). Below are operating system specific issues for those using Windows Media Player.</p>
		<p>Below is a list of OS specific player issues:</p>

		<ul>
			<li>
				<strong>Windows</strong><br />
				If you're experiencing problems viewing video lectures on Windows systems, make sure that you've installed the latest WindowsMedia software:
				<a target="_blank" href="http://windows.microsoft.com/en-us/windows/windows-media-player">Windows Media Player for Windows</a>
			</li>
			<li>
				<strong>Mac OS X</strong><br />
				If you're experiencing problems viewing video lectures on Mac OS X systems, make sure that you've installed the latest WindowsMedia software:
				<a target="_blank" href="http://windows.microsoft.com/en-us/windows/windows-media-components-quicktime">Windows Media Player for Mac OS X</a><br /><br />
				<strong>NOTE:</strong> Microsoft will continue to offer Windows Media Player for Mac as a download free of charge, but has no plans to provide future updates or product support. Instead, Microsoft will be offering Windows Media® Components for Quicktime, by Flip4Mac™, as an alternative for Mac OS X users wanting to play Windows Media Audio and Windows Media Video. Requires Mac OS X version 10.3.9 or later and QuickTime version 6.5 or later.<br /><br />
				<strong>Known Issue:</strong> Windows Media Player 9 for Mas OS X may have difficulty playing secure video streams (URLs starting with 'https'). The Flip4Mac plugin described above fixes this problem.
			</li>
			<li>
				<strong>Linux</strong><br />
				No currently known issues. Use <a target="_blank" href="http://www.videolan.org/">VideoLAN Media Player</a> or equivalent application.
			</li>
		</ul>
	</section>

	<section>
		<h2>Downloading Video and Audio Content</h2>
		<p>Most of the nanoHUB's video and audio content is downloadable. Procedures vary depending on the browser you are using:</p>
		<ul>
			<li>
				<strong>Firefox</strong> Right click (hold click for Mac) on the resource link, select "Save Link As...", a dialog box will appear allowing you to save document as a file.
			</li>
			<li>
				<strong>Internet Explorer</strong> Right click on the resource link, then select "Save Target As...", a dialog box will appear allowing you to save document as a file. Mac users should drag the link to their desktop or folder and the document will be downloaded.
			</li>
			<li>
				<strong>Safari</strong> Control-click on the resource link, then select "Download Linked File", the document will download to your download's folder. The download folder is specified using the Preferences menu and selecting the General tab.
			</li>
		</ul>
	</section>

	<section>
		<h2>Continued Problems</h2>
		<p><strong>If the problem persists, please send us a <a target="_blank" href="<?php echo Route::url('index.php?option=com_support&task=new'); ?>">trouble report.</a></strong></p>
	</section>
</article>