<?php
/**
 * HUBzero CMS
 *
 * Copyright 2005-2015 HUBzero Foundation, LLC.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 *
 * HUBzero is a registered trademark of Purdue University.
 *
 * @package   hubzero-cms
 * @author    Christopher Smoak <csmoak@purdue.edu>
 * @copyright Copyright 2005-2015 HUBzero Foundation, LLC.
 * @license   http://opensource.org/licenses/MIT MIT
 */

// No direct access.
defined('_HZEXEC_') or die();
?>
<article>
	<h1>Group Page Categories</h1>
	<p>Page categories are a simple easy to use way to group related pages together.</p>
	<p class="info">Categories are NOT hierarchical.</p>

	<hr />

	<h3>Adding Page Categories</h3>
	<ol>
		<li>Navigate to the page manager.</li>
		<li>Click on the "Manage Page Categories" tab.</li>
		<li>Here you will see any current page categories.</li>
		<li>Click the "New Page Category" button. Fill in the name field, color is optonal, then click "Save Category".</li>
	</ol>
	<figure>
		<img src="<?php echo rtrim(Request::base(true), '/'); ?>/core/components/com_groups/site/help/images/categories/manager.png" alt="" />
		<figcaption>Group Category Manager</figcaption>
	</figure>


	<hr />

	<h3>Editing Page Categories</h3>
	<ol>
		<li>Navigate to the page manager.</li>
		<li>Click on the "Manage Page Categories" tab.</li>
		<li>Here you will see any current page categories.</li>
		<li>Click on the "Manage Page Category" button for the category you wish to edit.</li>
		<li>Change the name or color settings, then click the "Save Category" button to finish.</li>
	</ol>
	<figure>
		<img src="<?php echo rtrim(Request::base(true), '/'); ?>/core/components/com_groups/site/help/images/categories/edit.png" alt="" />
		<figcaption>Edit Page Category</figcaption>
	</figure>

	<hr />

	<h3>Assigning Page Categories</h3>
	<p>Putting a page into a page category is done through the edit page interface.</p>
</article>