<?php
/**
 * HUBzero CMS
 *
 * Copyright 2005-2015 HUBzero Foundation, LLC.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 *
 * HUBzero is a registered trademark of Purdue University.
 *
 * @package   hubzero-cms
 * @author    Christopher Smoak <csmoak@purdue.edu>
 * @copyright Copyright 2005-2015 HUBzero Foundation, LLC.
 * @license   http://opensource.org/licenses/MIT MIT
 */

// No direct access.
defined('_HZEXEC_') or die();
?>
<article>
	<h1>What are Groups?</h1>

	<p>Groups are a way to connect people with a common interest. They are also an easy way to share content and conversation, either privately or with the world. Group members can:</p>
	<ul>
		<li>Post content that only other group members are allowed to see.</li>
		<li>Export their content to other web sites, and brand it with their own logo.</li>
		<li>Upload a group logo and use it as the group identity.</li>
		<li>Create events on the group calendar that only group members can attend.</li>
	</ul>

	<hr />

	<h2>Create a New Group</h2>
	<p>You can <a target="_blank" href="<?php echo Route::url('index.php?option=com_groups&task=new'); ?>">create your own group</a> as a registered user. Just fill in a simple form choosing a group name, a title, and a brief description, so that others will know what your group is about. Once created, your group title and description will be available for all to see in the <a target="_blank" href="<?php echo Route::url('index.php?option=com_groups&task=browse'); ?>">list of all groups.</a> Each group also has its own page, which contains a link that other users can click on to request membership.</p>

	<hr />

	<h2>Managing Group Members</h2>
	<p>Whenever another user requests membership, you will receive an email asking you to approve their request. To do this, log in and visit the group page, click members on the left side and click on "Pending Requests" just above the first member of the list. Click on the green check to accept the new user into the group. You can use the members page to promote ordinary users to also act as managers, so they can help you approve or deny requests. You can also demote or remove users from your group by clicking on the appropriate icon next to the users name.</p>

	<p>Once removed from a group, a user will no longer have access to hidden group resources. Of course, they can always rejoin the group at any point by requesting membership and going through the usual approval process.</p>

	<p>Member Roles are similar to the way tags work, member roles are labels or a way to categorize people within a group. There’s no difference in permissions between member roles.</p>

	<p><strong>Note:</strong> All groups must have at least one manager. If you are the last manager of a group, you will <em><u>NOT</u></em> be able to demote or remove yourself from the group.</p>
</article>