<?php
/**
 * HUBzero CMS
 *
 * Copyright 2005-2015 HUBzero Foundation, LLC.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 *
 * HUBzero is a registered trademark of Purdue University.
 *
 * @package   hubzero-cms
 * @author    Christopher Smoak <csmoak@purdue.edu>
 * @copyright Copyright 2005-2015 HUBzero Foundation, LLC.
 * @license   http://opensource.org/licenses/MIT MIT
 */

// No direct access.
defined('_HZEXEC_') or die();
?>
<article>
	<h1>Group Guidelines &amp; Tips</h1>
	<p>Ultimately it is the Administrators of the HUB that decide what the rules are within groups, but if you have been made a manager of a group, here are some suggestions for keeping your group happy:</p>

	<hr />

	<h2>Manager Guidelines</h2>
	<p>If you are a manager of a group, here are some pointers for creating a thriving community:</p>

	<ol>
		<li><strong>Invite your friends</strong> and anyone you know who is interested in what you are interested in. Having group members is the first step in having a successful group!</li>
		<li><strong>Visit the group frequently.</strong> Groups thrive with daily discussion, and with daily responses from other members of the community, in chat and on the discussion boards.</li>
		<li><strong>Moderate, moderate, moderate!</strong> Successful groups are kept in check by good moderation. Tend that garden; pull the weeds, mow the lawn, prune the roses, etc. To help you moderate your group, you can enlist other members to become moderators. Moderators don't have full administrative power, but they can help you moderate pool submissions, keep tabs on discussions, and weed out the people who don't play by the rules.</li>
	</ol>

	<hr />

	<h2>Removing members</h2>
	<p>Here are some general guidelines to help managers determine how and when to use the removing feature.</p>
	<p>"Removing" is when a person is removed from a group. They can come back if they want, but some trolls just need a cooling off period and are remorseful when they return.</p>
	<ul>
		<li>Use this power wisely and sparingly.</li>
		<li>If a troll types or posts something offensive, they should be warned.</li>
		<li>If they continue their behavior, they should be removed. You can do this from the members list.</li>
	</ul>

	<hr />

	<h2>Group Life</h2>
	<h3>Swearing</h3>
	<p>People ask if it's OK to swear. It is OK to swear so long as you're not offending, insulting or harassing anybody.</p>

	<h3>Porn</h3>
	<p>Porn, nudity and other such content is not disallowed, but it shouldn't be posted in public areas.</p>

	<h3>Trolls</h3>
	<p>Trolls are people who are just being rude and obnoxious, and are generally trying to offend, shock, harass, abuse or otherwise annoy people. Dealing with such people can often be difficult, but they should not go unwarned or unremoved. Trolls can destroy a community, and often this is their goal.</p>

	<p>Trolls thrive on attention, and often the best way to deal with them is to completely ignore them. They don't know when they are being ignored, all they know is that no one is responding to their attempts to annoy, harass or offend.</p>
</article>