<?php
/**
 * HUBzero CMS
 *
 * Copyright 2005-2015 HUBzero Foundation, LLC.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 *
 * HUBzero is a registered trademark of Purdue University.
 *
 * @package   hubzero-cms
 * @author    Christopher Smoak <csmoak@purdue.edu>
 * @copyright Copyright 2005-2015 HUBzero Foundation, LLC.
 * @license   http://opensource.org/licenses/MIT MIT
 */

// No direct access.
defined('_HZEXEC_') or die();

// lets see if the logged in user is a manager in any super groups
$superGroups = \Hubzero\User\Helper::getGroups(
	User::get('id'), 
	'managers',
	3
);

// are page modules enabled for standard groups
$groupParams  = Component::params('com_groups');
$groupModules = $groupParams->get('page_modules', 0);
?>
<article>
	<h1>Group Help</h1>
	<p>Groups are a way to connect people with a common interest. They are also an easy way to share content and conversation, either privately or with the world.</p>
	<ul>
		<li>
			<a href="<?php echo Route::url('index.php?option=com_help&component=groups&page=general'); ?>">What are Groups?</a>
		</li>
		<li>
			<a href="<?php echo Route::url('index.php?option=com_help&component=groups&page=membership'); ?>">Group Membership</a>
		</li>
		<li>
			<a href="<?php echo Route::url('index.php?option=com_help&component=groups&page=pages'); ?>">Group Pages</a>
		</li>
		<li>
			<a href="<?php echo Route::url('index.php?option=com_help&component=groups&page=categories'); ?>">Group Page Categories</a>
		</li>
		<?php if ((!empty($superGroups) && count($superGroups) > 0) || $groupModules) : ?>
			<li>
				<a href="<?php echo Route::url('index.php?option=com_help&component=groups&page=modules'); ?>">Group Page Modules</a>
			</li>
		<?php endif; ?>
		<li>
			<a href="<?php echo Route::url('index.php?option=com_help&component=groups&page=guidelines'); ?>">Guidelines &amp; Tips</a>
		</li>
		<li>
			<a href="<?php echo Route::url('index.php?option=com_help&component=groups&page=faqs'); ?>">FAQs</a>
		</li>
	</ul>
</article>