<article>
	<h1>Extension Manager: Install</h1>

	<p>This screen is accessed from the back-end Joomla! administrator panel. It is used to install extensions into your Joomla! installation. Some examples of extensions are plug-ins, components, and site templates.
</p>
<h2> <span class="mw-headline" id="How_to_Access">How to Access</span></h2>
<ul><li>Select <b>Extensions → Extension Manager</b> from the drop-down menu of the <i><b>Joomla! Administrator Panel</b></i>. Then select the <b>Install</b> menu item in the <i><b>Extension manager</b></i> screen that appears.
</li></ul>
<h2> <span class="mw-headline" id="Description">Description</span></h2>
<p>Extensions are add-ons that expand the functionality of Joomla!. Extensions are used to add capabilities to Joomla! that do not exist in the standard package. Hundreds of Extensions are available for Joomla!, with more being developed all of the time.
</p><p>Extensions are categorized into five types, as follows:
</p>
<ul><li> A <i>Component</i> is a mini-application that renders the main body of the page. Examples of Components are Contacts, the Front Page, and News Feeds.
</li><li> A <i>Module</i> is a smaller Extension typically used for rendering a small element that displays across multiple pages. Examples of Modules include Menus and Related Items.
</li><li> A <i>Plugin</i> is a section of code that runs when a pre-defined event happens within Joomla!. For example, editors are Plugins that run when an edit session is opened.
</li><li> The <i>Language</i> Extension allows for the Front-end and Back-end of Joomla! to be presented in any language for which a language Extension exists. This way, Joomla! can be released in a new language with no changes to the core program.
</li><li> A <i>Template</i> controls the way the content of a web site is displayed, including the location and layout of elements, colors, fonts, and so on. Templates allow the appearance of the web site to be separated from its content.
</li></ul>
<h2> <span class="mw-headline" id="Screenshot">Screenshot</span></h2>
<p><a href="/proxy/index.php?option=com_help&view=help&keyref=File:Help25-extension_manager-install-screen.png" class="image"><img alt="Help25-extension manager-install-screen.png" src="http://docs.joomla.org/images/c/c6/Help25-extension_manager-install-screen.png" width="670" height="209" /></a>
</p>
<h2> <span class="mw-headline" id="Toolbar">Toolbar</span></h2>
<p>At the top right you will see the toolbar:
</p><p><a href="/proxy/index.php?option=com_help&view=help&keyref=File:Help25-Toolbar-Options-Help.png" class="image"><img alt="Help25-Toolbar-Options-Help.png" src="http://docs.joomla.org/images/9/91/Help25-Toolbar-Options-Help.png" width="123" height="65" /></a>
</p><p>The functions are:
</p>
<ul><li><b>Options</b>. Opens the Options window where settings such as default parameters or permissions can be edited.
</li><li><b>Help</b>. Opens this help screen.
</li></ul>
<h2> <span class="mw-headline" id="Links_to_Other_Screens">Links to Other Screens</span></h2>
<p>At the top left, you will see the following five links:
</p><p><a href="/proxy/index.php?option=com_help&view=help&keyref=File:Help-extension_manager-install-menu.png" class="image"><img alt="Help-extension manager-install-menu.png" src="http://docs.joomla.org/images/8/8d/Help-extension_manager-install-menu.png" width="382" height="26" /></a>
</p>
<ul><li><b>Install.</b> Links to the <strong class="selflink">Install Screen</strong>.
</li><li><b>Update.</b> Links to the <a href="/proxy/index.php?option=com_help&view=help&keyref=Help25:Extensions_Extension_Manager_Update" title="Help25:Extensions Extension Manager Update">Update Screen</a>.
</li><li><b>Manage.</b> Links to the <a href="/proxy/index.php?option=com_help&view=help&keyref=Help25:Extensions_Extension_Manager_Manage" title="Help25:Extensions Extension Manager Manage">Manage Screen</a>.
</li><li><b>Discover.</b> Links to the <a href="/proxy/index.php?option=com_help&view=help&keyref=Help25:Extensions_Extension_Manager_Discover" title="Help25:Extensions Extension Manager Discover">Discover Screen</a>.
</li><li><b>Database.</b> Links to the <a href="/proxy/index.php?option=com_help&view=help&keyref=Help25:Extensions_Extension_Manager_Database" title="Help25:Extensions Extension Manager Database">Database Screen</a>.
</li><li><b>Warnings.</b> Links to the <a href="/proxy/index.php?option=com_help&view=help&keyref=Help25:Extensions_Extension_Manager_Warnings" title="Help25:Extensions Extension Manager Warnings">Warnings Screen</a>.
</li><li><b>Install Langauges.</b> Links to the <a href="/proxy/index.php?option=com_help&view=help&keyref=Help25:Extensions_Extension_Manager_languages" title="Help25:Extensions Extension Manager languages">Languages Screen</a>.
</li></ul>
<h2> <span class="mw-headline" id="Outline">Outline</span></h2>
<p>Joomla! Extensions can be installed using one of three methods, as indicated below. Only one method is needed to install a given Extension.
</p><p>The normal procedure for installing a Joomla! Extension is as follows:
</p>
<ol><li> Download one or more archive files (normally ".zip" or "tar.gz" format) from the Extension provider's web site to a local directory on your computer. Note that some Extensions are installed as one file (for example, one Component or Module) while other Extensions might have two or more files (for example, a Component and a Module). If there are two or more parts, each one will have its own archive file.
</li><li> Choose one of the methods describe below (<b>usually Package File</b>)
</li><li> When it is finished, the screen will display the message "Install Component Success". If the installation is not successful, an error message will display.
</li><li> Depending on the Extension, it may be necessary to enable the Extension (for example, in the <a href="/proxy/index.php?option=com_help&view=help&keyref=Help25:Extensions_Module_Manager" title="Help25:Extensions Module Manager">Module Manager</a> or <a href="/proxy/index.php?option=com_help&view=help&keyref=Help25:Extensions_Plugin_Manager" title="Help25:Extensions Plugin Manager">Plugin Manager</a>).
</li></ol>
<ul><li><b>Package File.</b> (the common way)
<ol><li> Browse to the location where you downloaded the Extension's archive file.
</li><li> Then press "Upload File &amp; Install". Joomla! will read the contents of the archive file and install the Extension.
</li></ol>
</li></ul>
<ul><li><b>Install Directory.</b> As an alternative to installing from an archive file, you can follow the steps below:
<ol><li>Create a temporary directory on your local hard drive and unpack the Extension's archive file in this temporary directory.
</li><li>Using FTP, upload the contents of this directory (including files and subdirectories) to a directory on your server.
</li><li>In the <i>Install Directory</i> field specify the server directory where you uploaded the files and subdirectories of the package.
</li><li>Click on the <i>Install</i> button and Joomla! will install the contents of the given directory.
</li></ol>
</li></ul>
<ul><li><b>Install URL.</b> A third alternative for installing an Extension is as follows. Instead of downloading the archive file to your local computer, just specify the URL of the target archive file. Then click the "Install" button and Joomla! automatically installs it directly from this URL. <i>Note that, with this method, you will not have a copy of the archive file on your local computer.</i>
</li></ul>
<h2> <span class="mw-headline" id="Quick_Tips">Quick Tips</span></h2>
<ul><li>Three alternate installation methods are available, as indicated above. The most common one is the "Upload Package File" method.
</li></ul>
<ul><li>If you want to install a third-party Module or Plugin that belongs to a Component, you will generally need to install the Component as well as the Module or Plugin in order to use the Module or Plugin. This is normally documented in the Extension's installation instructions on the author's web site.
</li></ul>
<ul><li>Similarly, if you uninstall a third-party Component that also has its own Modules or Plugins, these Modules and Plugins can no longer be used. So it is normally recommended to uninstall these dependent Modules and Plugins as well.
</li></ul>
<ul><li>Some Components developed by third party developers may have their own Modules or Plugins included in the installer. In this case, make sure these Module or Plugin directories are writable. Otherwise the Extension will not work properly.
</li></ul>
<ul><li><font color="#ff0000"><b>SECURITY WARNING:</b> It is recommended that you use only those third-party Extensions on your site that you really need. Do not use your live site for testing purposes because it may compromise your site and server. Test new extensions on a local test web site before deploying them on your live site.
</li></ul>
<ul><li>Do not install Joomla! Extensions downloaded from warez sites because they may be infected by a virus or malware that cause damage on the server and can contaminate the computer of your visitors!
</li></ul>
<ul><li>Installing from remote URL can be dangerous. For this reason, it is generally recommended that you use the "Upload Package File" or "Install from Directory" options when installing new Extensions.
</li></ul>
<p></font>
</p>
<h2> <span class="mw-headline" id="Related_Information">Related Information</span></h2>
<ul><li>If you install a Component Extension, it will be listed as a new Menu Item in the <i>Components</i> menu.
</li></ul>
<ul><li>You can assign a Menu Item to an installed Component Extension in the <a href="/proxy/index.php?option=com_help&view=help&keyref=Help25:Menus_Menu_Item_Manager" title="Help25:Menus Menu Item Manager">Menu Item Manager</a> by clicking the <i>New</i> toolbar button. The new Component will show in the Internal Link list of Menu Item Types.
</li></ul>
<ul><li>If you install a Module Extension, it will be added to the list of the Modules in the <a href="/proxy/index.php?option=com_help&view=help&keyref=Help25:Extensions_Module_Manager" title="Help25:Extensions Module Manager">Module Manager</a>, where you can enable/disable it. You can also customize it's parameters in the <a href="/proxy/index.php?option=com_help&view=help&keyref=Help25:Extensions_Module_Manager_Edit" title="Help25:Extensions Module Manager Edit">Module Edit</a> screen.
</li></ul>
<ul><li>An installed Plugin Extension will be added to the list of the <a href="/proxy/index.php?option=com_help&view=help&keyref=Help25:Extensions_Plugin_Manager" title="Help25:Extensions Plugin Manager">Plugin Manager</a>, where you can enable/disable it. You can also customize its parameters in the <a href="/proxy/index.php?option=com_help&view=help&keyref=Help25:Extensions_Plugin_Manager_Edit" title="Help25:Extensions Plugin Manager Edit">Plugin Edit</a> screen.
</li></ul>
<ul><li>An installed Template Extension will be added to the Site or Administrator list of the <a href="/proxy/index.php?option=com_help&view=help&keyref=Help25:Extensions_Template_Manager_Styles" title="Help25:Extensions Template Manager Styles">Template Manager</a> where you can assign it to all of the pages or to the selected ones. You can also customize its parameters, edit the HTML or CSS source, or preview the available Module positions.
</li></ul>
<ul><li>An installed Language Extension will be added to the Site or Administrator list of the <a href="/proxy/index.php?option=com_help&view=help&keyref=Help25:Extensions_Language_Manager_Installed" title="Help25:Extensions Language Manager Installed">Language Manager</a>, depending on the client attribute of the Extension. This screen let's you assign it as the default language, if desired.
</li></ul>
</article>