<article>
	<h1>Extension Manager: Languages</h1>

	<p>This screen is accessed from the back-end Joomla! administrator panel. It will allow you to install language packs for Joomla and any installed extensions.</p>
<h2> <span class="mw-headline" id="How_to_Access">How to Access</span></h2>
<ul><li>Select <b>Extensions → Extension Manager</b> from the drop-down menu of the <i><b>Joomla! Administrator Panel</b></i>. Then select the <b>Install Languages</b> menu item in the <i><b>Extension manager</b></i> screen that appears.
</li></ul>
<h2> <span class="mw-headline" id="Description">Description</span></h2>
<p>This screen allows you to quickly and simply install Joomla accredited language packs with ease without having to download them from JED. Please see the <a href="/proxy/index.php?option=com_help&view=help&keyref=Language_Switcher_Tutorial" title="Language Switcher Tutorial">Language Switcher Tutorial</a> for further information about what to do when you have installed your Joomla language pack to turn it into a true multilingual site.
</p>
<h2> <span class="mw-headline" id="Screenshot">Screenshot</span></h2>
<p><a href="/proxy/index.php?option=com_help&view=help&keyref=File:Help25-extension-manager-languages-screen.png" class="image"><img alt="Help25-extension-manager-languages-screen.png" src="http://docs.joomla.org/images/b/bc/Help25-extension-manager-languages-screen.png" width="670" height="435" /></a>
</p>
<h2> <span class="mw-headline" id="Column_Headers">Column Headers</span></h2>
<p><a href="/proxy/index.php?option=com_help&view=help&keyref=File:Help25-languages-manager-screen-headers.png" class="image"><img alt="Help25-languages-manager-screen-headers.png" src="http://docs.joomla.org/images/2/20/Help25-languages-manager-screen-headers.png" width="670" height="17" /></a>
</p>
<ul><li><b>Checkbox</b>. Check this box to select one or more items. To select all items, check the box in the column heading. After one or more boxes are checked, click a toolbar button to take an action on the selected item or items. Many toolbar actions, such as Publish and Unpublish, can work with multiple items. Others, such as Edit, only work on one item at a time. If multiple items are checked and you press Edit, the first item will be opened for editing.
</li><li> <b>Name.</b> The name of the Langauge.
</li><li> <b>Version.</b> The version of the Langauge file. This is the Joomla version it was built for followed by a fullstop and then the subversion of the language pack for that Joomla version (starting at 1). For example a French translation of Joomla for 2.5.9 would be: Joomla 2.5.9.1
</li><li> <b>Name.</b> The name of the Langauge.
</li><li> <b>Type.</b> The extension type. This should always be package.
</li><li> <b>Details URL.</b> The update URL for the package.
</li></ul>
<ul><li><b>ID</b>. This is a unique identification number for this item assigned automatically by Joomla!. It is used to identify the item internally, and you cannot change this number. When creating a new item, this field displays 0 until you save the new entry, at which point a new ID is assigned to it.
</li></ul>
<h2> <span class="mw-headline" id="List_Filters">List Filters</span></h2>
<h3> <span class="mw-headline" id="Filter_by_Partial_Title">Filter by Partial Title</span></h3>
<p>You can filter the list of items by typing part of the banner's name or the ID number of the banner.
<a href="/proxy/index.php?option=com_help&view=help&keyref=File:Help25-banners-manage-filter-name.png" class="image"><img alt="Help25-banners-manage-filter-name.png" src="http://docs.joomla.org/images/2/2b/Help25-banners-manage-filter-name.png" width="286" height="25" /></a>
</p><p>If you have a large number of items on the list, you can use this filter to find the desired item(s) quickly. Enter either all or part of the name and press 'Search' to display the matching items. You can enter in whole words or part of a word. For example, 'ooml' will match all titles with the word 'Joomla!' in them.
</p>
<h3> <span class="mw-headline" id="Pagination">Pagination</span></h3>
<ul><li><b>Page Controls.</b> When the number of items is more than one page, you will see a page control bar as shown below.<div class="thumb tnone"><div class="thumbinner" style="width:543px;"><a href="/proxy/index.php?option=com_help&view=help&keyref=File:Help25-chunk-colheader-pagination.png" class="image"><img alt="Help25-chunk-colheader-pagination.png" src="http://docs.joomla.org/images/7/76/Help25-chunk-colheader-pagination.png" width="541" height="37" class="thumbimage" /></a>  <div class="thumbcaption"></div></div></div>
<ul><li><b>Display #:</b> Select the number of items to show on one page.
</li><li><b>Start:</b> Click to go to the first page.
</li><li><b>Prev:</b> Click to go to the previous page.
</li><li><b>Page numbers:</b> Click to go to the desired page.
</li><li><b>Next:</b> Click to go to the next page.
</li><li><b>End:</b> Click to go to the last page.
</li></ul>
</li></ul>
<h2> <span class="mw-headline" id="Toolbar">Toolbar</span></h2>
<p>At the top right you will see the toolbar:
</p><p><a href="/proxy/index.php?option=com_help&view=help&keyref=File:Help25-Toolbar-Install-Find-Purge-Options-Help.png" class="image"><img alt="Help25-Toolbar-Install-Find-Purge-Options-Help.png" src="http://docs.joomla.org/images/1/17/Help25-Toolbar-Install-Find-Purge-Options-Help.png" width="340" height="71" /></a>
</p><p>The functions are:
</p>
<ul><li><b>Install</b>. Installs the selected item.
</li><li><b>Find Langagues.</b> Search for accredited Joomla language packs (similar to the find updates button in the <a href="/proxy/index.php?option=com_help&view=help&keyref=Help25:Extensions_Extension_Manager_Update" title="Help25:Extensions Extension Manager Update">Update Manager</a>)
</li><li><b>Purge Cache</b>. Clears cached information about available language updates.  This will update the list of available language updates shown on this screen.
</li><li><b>Options</b>. Opens the Options window where settings such as default parameters or permissions can be edited.
</li><li><b>Help</b>. Opens this help screen.
</li></ul>
<h2> <span class="mw-headline" id="Links_to_Other_Screens">Links to Other Screens</span></h2>
<p>At the top left, you will see the following five links:
</p><p><a href="/proxy/index.php?option=com_help&view=help&keyref=File:Help-extension_manager-install-menu.png" class="image"><img alt="Help-extension manager-install-menu.png" src="http://docs.joomla.org/images/8/8d/Help-extension_manager-install-menu.png" width="382" height="26" /></a>
</p>
<ul><li><b>Install.</b> Links to the <a href="/proxy/index.php?option=com_help&view=help&keyref=Help25:Extensions_Extension_Manager_Install" title="Help25:Extensions Extension Manager Install">Install Screen</a>.
</li><li><b>Update.</b> Links to the <a href="/proxy/index.php?option=com_help&view=help&keyref=Help25:Extensions_Extension_Manager_Update" title="Help25:Extensions Extension Manager Update">Update Screen</a>.
</li><li><b>Manage.</b> Links to the <a href="/proxy/index.php?option=com_help&view=help&keyref=Help25:Extensions_Extension_Manager_Manage" title="Help25:Extensions Extension Manager Manage">Manage Screen</a>.
</li><li><b>Discover.</b> Links to the <a href="/proxy/index.php?option=com_help&view=help&keyref=Help25:Extensions_Extension_Manager_Discover" title="Help25:Extensions Extension Manager Discover">Discover Screen</a>.
</li><li><b>Database.</b> Links to the <a href="/proxy/index.php?option=com_help&view=help&keyref=Help25:Extensions_Extension_Manager_Database" title="Help25:Extensions Extension Manager Database">Database Screen</a>.
</li><li><b>Warnings.</b> Links to the <a href="/proxy/index.php?option=com_help&view=help&keyref=Help25:Extensions_Extension_Manager_Warnings" title="Help25:Extensions Extension Manager Warnings">Warnings Screen</a>.
</li><li><b>Install Langauges.</b> Links to the <strong class="selflink">Languages Screen</strong>.
</li></ul>
</article>