<article>
	<h1>Extension Manager: Warnings</h1>

	<p>This screen is accessed from the back-end Joomla! administrator panel. It will display warnings related to your installed extensions.</p>
<h2> <span class="mw-headline" id="How_to_Access">How to Access</span></h2>
<ul><li>Select <b>Extensions → Extension Manager</b> from the drop-down menu of the <i><b>Joomla! Administrator Panel</b></i>. Then select the <b>Warnings</b> menu item in the <i><b>Extension manager</b></i> screen that appears.
</li></ul>
<h2> <span class="mw-headline" id="Description">Description</span></h2>
<p>This screen will display any warnings related to extensions you have installed in your Joomla! installation. Warnings such as possible conflicts in your installation or dependency failures may appear here.
</p>
<h2> <span class="mw-headline" id="Screenshot">Screenshot</span></h2>
<p><a href="/proxy/index.php?option=com_help&view=help&keyref=File:Help25-extension_manager-warnings-screen.png" class="image"><img alt="Help25-extension manager-warnings-screen.png" src="http://docs.joomla.org/images/8/86/Help25-extension_manager-warnings-screen.png" width="670" height="103" /></a>
</p>
<h2> <span class="mw-headline" id="Toolbar">Toolbar</span></h2>
<p>At the top right you will see the toolbar:
</p><p><a href="/proxy/index.php?option=com_help&view=help&keyref=File:Help25-Toolbar-Options-Help.png" class="image"><img alt="Help25-Toolbar-Options-Help.png" src="http://docs.joomla.org/images/9/91/Help25-Toolbar-Options-Help.png" width="123" height="65" /></a>
</p><p>The functions are:
</p>
<ul><li><b>Options</b>. Opens the Options window where settings such as default parameters or permissions can be edited.
</li><li><b>Help</b>. Opens this help screen.
</li></ul>
<h2> <span class="mw-headline" id="Links_to_Other_Screens">Links to Other Screens</span></h2>
<p>At the top left, you will see the following five links:
</p><p><a href="/proxy/index.php?option=com_help&view=help&keyref=File:Help-extension_manager-install-menu.png" class="image"><img alt="Help-extension manager-install-menu.png" src="http://docs.joomla.org/images/8/8d/Help-extension_manager-install-menu.png" width="382" height="26" /></a>
</p>
<ul><li><b>Install.</b> Links to the <a href="/proxy/index.php?option=com_help&view=help&keyref=Help25:Extensions_Extension_Manager_Install" title="Help25:Extensions Extension Manager Install">Install Screen</a>.
</li><li><b>Update.</b> Links to the <a href="/proxy/index.php?option=com_help&view=help&keyref=Help25:Extensions_Extension_Manager_Update" title="Help25:Extensions Extension Manager Update">Update Screen</a>.
</li><li><b>Manage.</b> Links to the <a href="/proxy/index.php?option=com_help&view=help&keyref=Help25:Extensions_Extension_Manager_Manage" title="Help25:Extensions Extension Manager Manage">Manage Screen</a>.
</li><li><b>Discover.</b> Links to the <a href="/proxy/index.php?option=com_help&view=help&keyref=Help25:Extensions_Extension_Manager_Discover" title="Help25:Extensions Extension Manager Discover">Discover Screen</a>.
</li><li><b>Database.</b> Links to the <a href="/proxy/index.php?option=com_help&view=help&keyref=Help25:Extensions_Extension_Manager_Database" title="Help25:Extensions Extension Manager Database">Database Screen</a>.
</li><li><b>Warnings.</b> Links to the <strong class="selflink">Warnings Screen</strong>.
</li><li><b>Install Langauges.</b> Links to the <a href="/proxy/index.php?option=com_help&view=help&keyref=Help25:Extensions_Extension_Manager_languages" title="Help25:Extensions Extension Manager languages">Languages Screen</a>.
</li></ul>
</article>