<?php
/**
 * HUBzero CMS
 *
 * Copyright 2005-2015 HUBzero Foundation, LLC.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 *
 * HUBzero is a registered trademark of Purdue University.
 *
 * @package   hubzero-cms
 * @author    Christopher Smoak <csmoak@purdue.edu>
 * @copyright Copyright 2005-2015 HUBzero Foundation, LLC.
 * @license   http://opensource.org/licenses/MIT MIT
 */

defined('_HZEXEC_') or die('Restricted access');

$params = Plugin::params('content', 'formathtml');

// define path to macros
$path = PATH_CORE . DS . 'plugins' . DS . 'content' . DS . 'formathtml' . DS . 'macros';

// get all macro files
$files = Filesystem::files($path, '.php', true, true, array('CVS', '.DS_Store', '__MACOSX', 'macro-assets'));

// include base macro class
require_once $path . DS . '..' . DS . 'macro.php';

// include each macro
foreach ($files as $file)
{
	require_once $file;
}
if ($path = $params->get('macropath'))
{
	// define path to macros
	$path = PATH_ROOT . DS . ltrim($path, DS);

	if (is_dir($path))
	{
		// get all macro files
		$files = Filesystem::files($path, '.php', true, true, array('CVS', '.DS_Store', '__MACOSX', 'macro-assets'));

		// include each macro
		foreach ($files as $file)
		{
			require_once $file;
		}
	}
}
// anonymous function to get macros description
$macroAttributes = function($class)
{
	if (is_subclass_of($class, 'Plugins\Content\Formathtml\Macro'))
	{
		$macroClass = new $class();
		if (method_exists($macroClass, 'description'))
		{
			$nameParts = explode("\\", str_replace('Plugins\\Content\\Formathtml\\Macros\\', '', $class));
			$name = '[[' . implode('.', $nameParts) . '(args)]]';
			$namespace = (count($nameParts) > 1) ? $nameParts[0] : 'general';
			$desc = $macroClass->description();
			if ($desc == '')
			{
				return;
			}
			return array('namespace' => ucfirst($namespace), 'name' => $name, 'description' => $desc);
		}
	}
};

// get macro description html
$macrosNameAndDesc = array_values(array_filter(array_map($macroAttributes, get_declared_classes())));

// group according to namepace
$macrosList = array();
foreach ($macrosNameAndDesc as $macroNameAndDesc)
{
	if (!isset($macrosList[$macroNameAndDesc['namespace']]))
	{
		$macrosList[$macroNameAndDesc['namespace']] = array();
	}

	array_push($macrosList[$macroNameAndDesc['namespace']], $macroNameAndDesc);
}
?>
<h1 class="page-title">HTML Macros</h1>
<p>Below is a list of available macros, useful for generating dynamic content in HTML.</p>

<?php foreach ($macrosList as $namespace => $macros) : ?>
	<h3><?php echo $namespace; ?> Macros</h3>
	<dl>
		<?php foreach ($macros as $macro) : ?>
			<dt><?php echo $macro['name']; ?></dt>
			<dd><?php echo $macro['description']; ?></dd>
		<?php endforeach; ?>
	</dl>
<?php endforeach; ?>