<h1 class="page-title">Sample Help Page</h1>

<h2>Headings</h2>
<div class="example">
	<h1>H1. Heading 1</h1>
	<h2>H2. Heading 2</h2>
	<h3>H3. Heading 3</h3>
	<h4>H4. Heading 4</h4>
	<h5>H5. Heading 5</h5>
	<h6>H6. Heading 6</h6>
</div>

<h2>Body Copy &amp; Links</h2>
<div class="example">
	<p>Donec vel leo odio, in pharetra est. Cras mi nunc, <a href="#1">dapibus sit amet posuere quis, placerat sit amet libero.</a> Nullam malesuada, nibh ac molestie fringilla, ligula neque molestie sem, eget imperdiet nibh lectus varius nulla. Curabitur condimentum sollicitudin dui sollicitudin iaculis. Nunc malesuada, turpis ac laoreet sollicitudin, eros turpis accumsan orci, eu lacinia diam nisi id nisl. Mauris laoreet eleifend luctus. Aenean semper ullamcorper rutrum. Duis et nisi est, vel lacinia massa. Aliquam erat volutpat. Ut commodo magna id nunc sodales adipiscing. Maecenas mollis suscipit massa, eget elementum sem euismod eu.</p>
	<p>Donec vel leo odio, in pharetra est. Cras mi nunc, dapibus sit amet posuere quis, placerat sit amet libero. <a href="#2">Nullam malesuada</a>, nibh ac molestie fringilla, ligula neque molestie sem, eget imperdiet nibh lectus varius nulla. Curabitur condimentum sollicitudin dui sollicitudin iaculis. Nunc malesuada, turpis ac laoreet sollicitudin, eros turpis accumsan orci, eu lacinia diam nisi id nisl. Mauris laoreet eleifend luctus. Aenean semper ullamcorper rutrum. Duis et nisi est, vel lacinia massa. Aliquam erat volutpat. Ut commodo magna id nunc sodales adipiscing. Maecenas mollis suscipit massa, <a href="#3">eget elementum sem euismod eu.</a></p>
</div>

<h2>Bold, Italic, Underline, Deleted Text</h2>
<div class="example">
	<p>This text has <strong>bold parts</strong></p>
	<p>This text has <em>italic parts</em></p>
	<p>This text has <u>underline parts</u></p>
	<p>This text has <del>bold parts</del></p>
</div>

<h2>Code</h2>
<div class="example">
	<pre>&lt;div id="help"&gt;This is a help div&lt;/div&gt;</pre>
</div>

<h2>Unordered Lists</h2>
<div class="example">
	<ul>
		<li>Nullam non nulla mauris, eget tempus tellus.</li>
		<li>Aenean ultricies est sit amet turpis blandit tempor.</li>
		<li>Donec non sem sed arcu accumsan accumsan.</li>
		<li>Proin eu tortor magna, imperdiet egestas libero.
			<ul>
				<li>Nullam non nulla mauris, eget tempus tellus.</li>
				<li>Aenean ultricies est sit amet turpis blandit tempor.</li>
				<li>Donec non sem sed arcu accumsan accumsan.</li>
				<li>Proin eu tortor magna, imperdiet egestas libero.</li>
				<li>Nulla eget enim tellus, vel sagittis felis.</li>
			</ul>
		</li>
		<li>Nulla eget enim tellus, vel sagittis felis.</li>
	</ul>
</div>

<h2>Ordered Lists</h2>
<div class="example">
	<ol>
		<li>Nullam non nulla mauris, eget tempus tellus.</li>
		<li>Aenean ultricies est sit amet turpis blandit tempor.</li>
		<li>Donec non sem sed arcu accumsan accumsan.</li>
		<li>Proin eu tortor magna, imperdiet egestas libero.
			<ol>
				<li>Nullam non nulla mauris, eget tempus tellus.</li>
				<li>Aenean ultricies est sit amet turpis blandit tempor.</li>
				<li>Donec non sem sed arcu accumsan accumsan.</li>
				<li>Proin eu tortor magna, imperdiet egestas libero.</li>
				<li>Nulla eget enim tellus, vel sagittis felis.</li>
			</ol>
		</li>
		<li>Nulla eget enim tellus, vel sagittis felis.</li>
	</ol>
</div>

<h2>Definition Lists</h2>
<div class="example">
	<dl>
		<dt>Definition 1</dt>
		<dd>This is a definition description</dd>
		<dt>Definition 2</dt>
		<dd>This is a definition description</dd>
		<dt>Definition 3</dt>
		<dd>This is a definition description</dd>
	</dl>
</div>

<h2>Tables</h2>
<div class="example">
	<table>
		<thead>
			<tr>
				<th>Column 1</th>
				<th>Column 2</th>
				<th>Column 3</th>
				<th>Column 4</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>Text 1</td>
				<td>Text 2</td>
				<td>Text 3</td>
				<td>Text 4</td>
			</tr>
			<tr>
				<td>Text 5</td>
				<td>Text 6</td>
				<td>Text 7</td>
				<td>Text 8</td>
			</tr>
			<tr>
				<td>Text 9</td>
				<td>Text 10</td>
				<td>Text 11</td>
				<td>Text 12</td>
			</tr>
			<tr>
				<td>Text 13</td>
				<td>Text 14</td>
				<td>Text 15</td>
				<td>Text 16</td>
			</tr>
		</tbody>
		<tfoot>
			<tr>
				<td colspan="2">Footer 1</td>
				<td colspan="2">Footer 2</td>
			</tr>
		</tfoot>
	</table>
</div>

<h2>Images</h2>
<div class="example">
	<figure>
		<img src="http://placehold.it/200x200&amp;text=Image+1">
		<figcaption>Caption 1</figcaption>
	</figure>
	<figure>
		<img src="http://placehold.it/200x200&amp;text=Image+2">
		<figcaption>Caption 2</figcaption>
	</figure>
	<figure>
		<img src="http://placehold.it/200x200&amp;text=Image+3">
		<figcaption>Caption 3</figcaption>
	</figure>
</div>