<?php

/**
 * @package    framework
 * @copyright  Copyright (c) 2005-2025 The Regents of the University of California.
 * @license    http://opensource.org/licenses/MIT MIT
 */

namespace Hubzero\Console\Command\Install;

/**
 * App directory structure helper class
 *
 * This class creates the /app directory structure and config files.
 * It can be used both by minimal muse (before autoloading) and full muse.
 **/
class AppDirectory
{
    /**
     * Subdirectories created at install time
     * (cache, logs, tmp, templates are created on-demand at runtime)
     *
     * @var array
     **/
    private const SUBDIRECTORIES = [
        'config',
    ];

    /**
     * Create the app directory structure
     *
     * @param   bool    $ansi     Whether to use ANSI color output
     * @param   string  $appPath  Path to the app directory
     * @return  bool    True on success, false on failure
     */
    public static function create($ansi = true, $appPath = null)
    {
        if ($appPath === null) {
            $appPath = defined('PATH_APP')
                ? PATH_APP
                : dirname(dirname(dirname(dirname(dirname(dirname(__DIR__)))))) . '/app';
        }

        self::output("\n", $ansi);
        self::output("\e[33mCreating App Directory Structure\e[39m\n", $ansi);
        self::output("--------------------------------\n", $ansi);

        $allCreated = true;

        // Create main app directory if it doesn't exist
        if (!is_dir($appPath)) {
            if (!@mkdir($appPath, 0775, true)) {
                self::output("  \e[31m[FAIL]\e[39m Could not create {$appPath}\n", $ansi, true);
                return false;
            }
            self::output("  \e[32m[OK]\e[39m Created {$appPath}\n", $ansi);
            self::output("       Permissions: 0775\n", $ansi);
        } else {
            self::output("  \e[32m[OK]\e[39m {$appPath} exists\n", $ansi);
            // Ensure group has rwx permissions
            self::ensureGroupPermissions($appPath, $ansi);
        }

        // Create subdirectories
        foreach (self::SUBDIRECTORIES as $subdir) {
            $path = $appPath . '/' . $subdir;
            // Config directory should have no other permissions (0770)
            $perms = ($subdir === 'config') ? 0770 : 0775;

            if (!is_dir($path)) {
                if (!@mkdir($path, $perms, true)) {
                    self::output("  \e[31m[FAIL]\e[39m Could not create {$path}\n", $ansi, true);
                    $allCreated = false;
                    continue;
                }
                self::output("  \e[32m[OK]\e[39m Created {$path}\n", $ansi);
                self::output("       Permissions: 0" . decoct($perms) . "\n", $ansi);
            } else {
                self::output("  \e[32m[OK]\e[39m {$path} exists\n", $ansi);
                // Ensure group has rwx permissions and config has no other permissions
                if ($subdir === 'config') {
                    self::ensureConfigPermissions($path, $ansi);
                } else {
                    self::ensureGroupPermissions($path, $ansi);
                }
            }

            // Add index.html to prevent directory listing (fallback protection)
            $indexPath = $path . '/index.html';
            if (!file_exists($indexPath)) {
                @file_put_contents($indexPath, "<!DOCTYPE html><html><head></head><body></body></html>\n");
            }
        }

        if ($allCreated) {
            self::output("\n", $ansi);
            self::output("\e[32mApp directory structure created.\e[39m\n", $ansi);
        } else {
            self::output("\n", $ansi, true);
            self::output("\e[37;41mERROR:\e[39;49m Some directories could not be created.\n", $ansi, true);
        }

        self::output("\n", $ansi);

        return $allCreated;
    }

    /**
     * Write database configuration file
     *
     * @param   bool    $ansi      Whether to use ANSI color output
     * @param   string  $appPath   Path to the app directory
     * @param   array   $config    Database configuration array
     * @return  bool    True on success, false on failure
     */
    public static function writeDatabaseConfig($ansi, $appPath, array $config)
    {
        $configPath = $appPath . '/config/database.php';

        $content = "<?php\n\n";
        $content .= "/**\n";
        $content .= " * Database configuration\n";
        $content .= " * Generated by muse install on " . date('Y-m-d H:i:s') . "\n";
        $content .= " */\n\n";
        $content .= "return array(\n";
        $content .= "    'dbtype'   => " . var_export($config['dbtype'] ?? 'mysql', true) . ",\n";
        $content .= "    'host'     => " . var_export($config['host'] ?? 'localhost', true) . ",\n";

        // Add port if specified and not default
        if (!empty($config['port'])) {
            $content .= "    'port'     => " . var_export((int) $config['port'], true) . ",\n";
        }

        // Add socket if specified (for Unix socket connections)
        if (!empty($config['socket'])) {
            $content .= "    'socket'   => " . var_export($config['socket'], true) . ",\n";
        }

        $content .= "    'user'     => " . var_export($config['user'] ?? '', true) . ",\n";
        $content .= "    'password' => " . var_export($config['password'] ?? '', true) . ",\n";
        $content .= "    'db'       => " . var_export($config['db'] ?? '', true) . ",\n";
        $content .= "    'dbprefix' => " . var_export($config['dbprefix'] ?? 'jos_', true) . ",\n";
        $content .= ");\n";

        if (@file_put_contents($configPath, $content) === false) {
            self::output("  \e[31m[FAIL]\e[39m Could not write {$configPath}\n", $ansi, true);
            return false;
        }

        // Secure the file
        @chmod($configPath, 0640);

        self::output("  \e[32m[OK]\e[39m Created database.php\n", $ansi);
        return true;
    }

    /**
     * Write application configuration file
     *
     * @param   bool    $ansi      Whether to use ANSI color output
     * @param   string  $appPath   Path to the app directory
     * @param   array   $config    Application configuration array
     * @return  bool    True on success, false on failure
     */
    public static function writeAppConfig($ansi, $appPath, array $config)
    {
        $configPath = $appPath . '/config/app.php';

        // Generate a random secret if not provided
        $secret = $config['secret'] ?? bin2hex(random_bytes(32));

        $content = "<?php\n\n";
        $content .= "/**\n";
        $content .= " * Application configuration\n";
        $content .= " * Generated by muse install on " . date('Y-m-d H:i:s') . "\n";
        $content .= " */\n\n";
        $content .= "return array(\n";
        $content .= "    'secret'              => " . var_export($secret, true) . ",\n";
        $appEnv = var_export($config['application_env'] ?? 'production', true);
        $content .= "    'application_env'     => " . $appEnv . ",\n";
        $content .= "    'error_reporting'     => " . var_export($config['error_reporting'] ?? 'default', true) . ",\n";
        $content .= "    'debug'               => " . var_export($config['debug'] ?? '0', true) . ",\n";
        $content .= "    'debug_lang'          => " . var_export($config['debug_lang'] ?? '0', true) . ",\n";
        $content .= "    'profile'             => " . var_export($config['profile'] ?? '0', true) . ",\n";
        $content .= "    'editor'              => " . var_export($config['editor'] ?? 'ckeditor', true) . ",\n";
        $content .= "    'list_limit'          => " . var_export($config['list_limit'] ?? '25', true) . ",\n";
        $content .= "    'feed_limit'          => " . var_export($config['feed_limit'] ?? '10', true) . ",\n";
        $content .= "    'feed_email'          => " . var_export($config['feed_email'] ?? 'author', true) . ",\n";
        $content .= "    'gzip'                => " . var_export($config['gzip'] ?? '0', true) . ",\n";
        $content .= "    'log_path'            => " . var_export($appPath . '/logs', true) . ",\n";
        $content .= "    'tmp_path'            => " . var_export($appPath . '/tmp', true) . ",\n";
        $content .= "    'force_ssl'           => " . var_export($config['force_ssl'] ?? '0', true) . ",\n";
        $content .= "    'offset'              => " . var_export($config['offset'] ?? 'UTC', true) . ",\n";
        $content .= "    'sitename'            => " . var_export($config['sitename'] ?? 'HUBzero', true) . ",\n";
        $content .= "    'captcha'             => " . var_export($config['captcha'] ?? 'image', true) . ",\n";
        $content .= "    'access'              => " . var_export($config['access'] ?? '1', true) . ",\n";
        $content .= "    'log_post_data'       => " . var_export($config['log_post_data'] ?? '0', true) . ",\n";
        $content .= "    'live_site'           => " . var_export($config['live_site'] ?? '', true) . ",\n";
        $content .= "    'xmlrpc_server'       => " . var_export($config['xmlrpc_server'] ?? '0', true) . ",\n";
        $content .= "    'helpurl'             => " . var_export($config['helpurl'] ?? '', true) . ",\n";
        $content .= ");\n";

        if (@file_put_contents($configPath, $content) === false) {
            self::output("  \e[31m[FAIL]\e[39m Could not write {$configPath}\n", $ansi, true);
            return false;
        }

        self::output("  \e[32m[OK]\e[39m Created app.php\n", $ansi);
        return true;
    }

    /**
     * Write all default configuration files
     *
     * @param   bool    $ansi     Whether to use ANSI color output
     * @param   string  $appPath  Path to the app directory
     * @param   array   $config   Configuration values to use
     * @return  bool    True on success, false on failure
     */
    public static function writeDefaultConfigs($ansi, $appPath, array $config = [])
    {
        self::output("\n", $ansi);
        self::output("\e[33mWriting Configuration Files\e[39m\n", $ansi);
        self::output("---------------------------\n", $ansi);

        $allWritten = true;

        // Write cache.php
        if (
            !self::writeConfigFile($ansi, $appPath, 'cache.php', [
            'caching'       => '0',
            'cache_handler' => 'file',
            'cachetime'     => '15',
            ])
        ) {
            $allWritten = false;
        }

        // Write session.php
        if (
            !self::writeConfigFile($ansi, $appPath, 'session.php', [
            'session_handler'  => 'database',
            'lifetime'         => '45',
            'cookie_path'      => '',
            'cookie_domain'    => '',
            'cookiesubdomains' => '0',
            ])
        ) {
            $allWritten = false;
        }

        // Write mail.php
        if (
            !self::writeConfigFile($ansi, $appPath, 'mail.php', [
            'mailer'     => 'mail',
            'mailfrom'   => $config['mailfrom'] ?? 'noreply@example.com',
            'fromname'   => $config['sitename'] ?? 'HUBzero',
            'smtpauth'   => '0',
            'smtphost'   => 'localhost',
            'smtpport'   => '25',
            'smtpuser'   => '',
            'smtppass'   => '',
            'smtpsecure' => 'none',
            'sendmail'   => '/usr/sbin/sendmail',
            ])
        ) {
            $allWritten = false;
        }

        // Write seo.php
        if (
            !self::writeConfigFile($ansi, $appPath, 'seo.php', [
            'sef'                 => '1',
            'sef_groups'          => '0',
            'sef_rewrite'         => '1',
            'sef_suffix'          => '0',
            'unicodeslugs'        => '0',
            'sitename_pagetitles' => '0',
            ])
        ) {
            $allWritten = false;
        }

        // Write offline.php
        if (
            !self::writeConfigFile($ansi, $appPath, 'offline.php', [
            'offline'                 => '0',
            'display_offline_message' => '1',
            'offline_message'         => 'This site is down for maintenance. Please check back again soon.',
            'offline_image'           => '',
            ])
        ) {
            $allWritten = false;
        }

        // Write meta.php
        if (
            !self::writeConfigFile($ansi, $appPath, 'meta.php', [
            'MetaAuthor'  => '1',
            'MetaTitle'   => '0',
            'MetaDesc'    => $config['MetaDesc'] ?? 'HUBzero - The platform for scientific research and collaboration.',
            'MetaKeys'    => $config['MetaKeys'] ?? 'hub, hubzero, research, collaboration',
            'MetaVersion' => '0',
            'MetaRights'  => '',
            'robots'      => '',
            ])
        ) {
            $allWritten = false;
        }

        // Write ftp.php
        if (
            !self::writeConfigFile($ansi, $appPath, 'ftp.php', [
            'ftp_enable' => '0',
            'ftp_host'   => '127.0.0.1',
            'ftp_port'   => '21',
            'ftp_user'   => '',
            'ftp_pass'   => '',
            'ftp_root'   => '',
            ])
        ) {
            $allWritten = false;
        }

        // Write rate_limit.php
        if (
            !self::writeConfigFile($ansi, $appPath, 'rate_limit.php', [
            'short' => [
                'period' => '5',
                'limit'  => '500',
            ],
            'long' => [
                'period' => '1440',
                'limit'  => '10000',
            ],
            ])
        ) {
            $allWritten = false;
        }

        if ($allWritten) {
            self::output("\n", $ansi);
            self::output("\e[32mConfiguration files created.\e[39m\n", $ansi);
        } else {
            self::output("\n", $ansi, true);
            self::output("\e[37;41mERROR:\e[39;49m Some config files could not be written.\n", $ansi, true);
        }

        self::output("\n", $ansi);

        return $allWritten;
    }

    /**
     * Write a configuration file
     *
     * @param   bool    $ansi      Whether to use ANSI color output
     * @param   string  $appPath   Path to the app directory
     * @param   string  $filename  Config filename
     * @param   array   $config    Configuration array
     * @return  bool    True on success, false on failure
     */
    private static function writeConfigFile($ansi, $appPath, $filename, array $config)
    {
        $configPath = $appPath . '/config/' . $filename;

        // Skip if file already exists
        if (file_exists($configPath)) {
            self::output("  \e[32m[OK]\e[39m {$filename} exists\n", $ansi);
            return true;
        }

        $content = "<?php\n\n";
        $content .= "/**\n";
        $content .= " * " . ucfirst(str_replace('.php', '', $filename)) . " configuration\n";
        $content .= " * Generated by muse install on " . date('Y-m-d H:i:s') . "\n";
        $content .= " */\n\n";
        $content .= "return " . self::arrayExport($config, 0) . ";\n";

        if (@file_put_contents($configPath, $content) === false) {
            self::output("  \e[31m[FAIL]\e[39m Could not write {$filename}\n", $ansi, true);
            return false;
        }

        self::output("  \e[32m[OK]\e[39m Created {$filename}\n", $ansi);
        return true;
    }

    /**
     * Export array to PHP code string
     *
     * @param   array  $array   Array to export
     * @param   int    $indent  Indentation level
     * @return  string
     */
    private static function arrayExport(array $array, $indent = 0)
    {
        $spaces = str_repeat('    ', $indent);
        $innerSpaces = str_repeat('    ', $indent + 1);

        $output = "array(\n";

        foreach ($array as $key => $value) {
            $output .= $innerSpaces;
            $output .= var_export($key, true) . ' => ';

            if (is_array($value)) {
                $output .= self::arrayExport($value, $indent + 1);
            } else {
                $output .= var_export($value, true);
            }

            $output .= ",\n";
        }

        $output .= $spaces . ")";

        return $output;
    }

    /**
     * Ensure directory has group rwx permissions
     *
     * @param   string  $path  Path to the directory
     * @param   bool    $ansi  Whether to use ANSI colors
     * @return  void
     */
    private static function ensureGroupPermissions($path, $ansi = true)
    {
        $currentPerms = @fileperms($path);
        if ($currentPerms !== false) {
            // Add group rwx (0070) to current permissions
            $newPerms = $currentPerms | 0070;
            if ($newPerms !== $currentPerms) {
                // Extract just the permission bits (last 9 bits)
                $oldMode = $currentPerms & 0777;
                $newMode = $newPerms & 0777;
                self::output("       Permissions: 0" . decoct($oldMode) . " -> 0" . decoct($newMode) . "\n", $ansi);
                @chmod($path, $newPerms);
            }
        }
    }

    /**
     * Ensure config directory has group rwx but no other permissions
     *
     * @param   string  $path  Path to the directory
     * @param   bool    $ansi  Whether to use ANSI colors
     * @return  void
     */
    private static function ensureConfigPermissions($path, $ansi = true)
    {
        $currentPerms = @fileperms($path);
        if ($currentPerms !== false) {
            // Add group rwx (0070) and remove other permissions (mask off 0007)
            $newPerms = ($currentPerms | 0070) & ~0007;
            if ($newPerms !== $currentPerms) {
                // Extract just the permission bits (last 9 bits)
                $oldMode = $currentPerms & 0777;
                $newMode = $newPerms & 0777;
                self::output("       Permissions: 0" . decoct($oldMode) . " -> 0" . decoct($newMode) . "\n", $ansi);
                @chmod($path, $newPerms);
            }
        }
    }

    /**
     * Output helper that handles ANSI stripping
     *
     * @param   string  $text   Text to output
     * @param   bool    $ansi   Whether to use ANSI colors
     * @param   bool    $error  Whether this is an error message
     * @return  void
     */
    private static function output($text, $ansi = true, $error = false)
    {
        if (!$ansi) {
            $text = preg_replace("/\e\[\d+m/", "", $text);
            $text = preg_replace("/\e\[\d+;\d+m/", "", $text);
        }
        echo $text;
    }
}
