<?php

require_once 'lib/data/om/BaseDocLib.php';


/**
 * Skeleton subclass for representing a row from the 'DocLib' table.
 *
 * Fry implemented DocLib as the basis for a content-management system.
 * It remains incomplete but is now used by the Curation application.
 *
 * This class was autogenerated by Propel on:
 *
 * Sat Feb  9 00:02:52 2008
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.data
 * @deprecated
 */

/**
 * Curation use this table
 *
 */
class DocLib extends BaseDocLib {

  /**
   * Initializes internal state of DocLib object.
   * @todo add initialization parameters
   */
  public function __construct()
  {
  }

} // DocLib
?>
