<?php

  // include base peer class
  require_once 'lib/data/om/BaseDocLibPeer.php';

  // include object class
  include_once 'lib/data/DocLib.php';


/**
 * Skeleton subclass for performing query and update operations on the 'DocLib' table.
 *
 *
 *
 * This class was autogenerated by Propel on:
 *
 * Sat Feb  9 00:02:52 2008
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.data
 */
class DocLibPeer extends BaseDocLibPeer {

  /**
   * Find a DocLib object based on its ID
   *
   * @param int $id
   * @return DocLib
   */
  public static function find($id) {
    throw new Exception("DOC LIB Surfaces!");
    return self::retrieveByPK($id);
  }


  /**
   * Find all DocLibs
   *
   * @return array <DocLib>
   */
  public static function findAll() {
    throw new Exception("DOC LIB Surfaces!");
    return self::doSelect(new Criteria());
  }


} // DocLibPeer
?>
