<?php

require_once 'lib/data/om/BaseDocumentFormat.php';


/**
 * Skeleton subclass for representing a row from the 'DocumentFormat' table.
 *
 *
 *
 * This class was autogenerated by Propel on:
 *
 * Sat Feb  9 00:02:52 2008
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.data
 */
class DocumentFormat extends BaseDocumentFormat {

  /**
   * Initializes internal state of DocumentFormat object.
   */
  public function __construct($format=null,
                              $mimetype=null,
                              $extension=null)
  {
		$this->setFormat($format);
		$this->setMimeType($mimetype);
		$this->setDefaultExtension($extension);
  }


	/**
	 * Get the Id of DocumentFormat
	 * Backward compatible with NEEScentral 1.7
	 *
	 * @return Int ID
	 */
	public function getDocumentFormatId() {
	  return $this->getId();
	}
} // DocumentFormat
?>
