<?php

require_once 'lib/data/om/BaseDocumentType.php';


/**
 * Skeleton subclass for representing a row from the 'DocumentType' table.
 *
 *
 *
 * This class was autogenerated by Propel on:
 *
 * Sat Feb  9 00:02:52 2008
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.data
 */
class DocumentType extends BaseDocumentType {

  /**
   * Initializes internal state of DocumentType object.
   */
  public function __construct($name= "",
                              $preferredFormat = "")
  {
		$this->setName($name);
		$this->setPreferredFormat($preferredFormat);
	}

} // DocumentType
?>
