<?php

  // include base peer class
  require_once 'lib/data/om/BaseDocumentTypePeer.php';

  // include object class
  include_once 'lib/data/DocumentType.php';


/**
 * Skeleton subclass for performing query and update operations on the 'DocumentType' table.
 *
 *
 *
 * This class was autogenerated by Propel on:
 *
 * Sat Feb  9 00:02:52 2008
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.data
 */
class DocumentTypePeer extends BaseDocumentTypePeer {

  /**
   * Find a DocumentType object based on its ID
   *
   * @param int $id
   * @return DocumentType
   */
  public static function find($id) {
    return self::retrieveByPK($id);
  }


  /**
   * Find all DocumentTypes
   *
   * @return array <DocumentType>
   */
  public static function findAll() {
    return self::doSelect(new Criteria());
  }


  //case "findByFormat":
  //return new Finder($finderName, "SELECT * FROM DocumentType WHERE preferredFormat=?");
  public static function findByFormat($preferredFormat) {
    $c = new Criteria();
    $c->add(self::PREFERRED_FORMAT, $preferredFormat);

    return self::doSelect($c);
  }

  //case "findByName":
  //return new Finder($finderName, "SELECT * FROM DocumentType WHERE name=?");
  public static function findByName($name) {
    $c = new Criteria();
    $c->add(self::NAME, $name);
    $c->setIgnoreCase(true);
    return self::doSelectOne($c);
  }

} // DocumentTypePeer
?>
