<?php

require_once 'lib/data/om/BaseElementType.php';


/**
 * ElementType
 *
 * Part of the simulation data model, e.g. Brick element or a shell or plate or spring element,
 * changes
 *
 * Element refers to a "finite elemment" in an FEA-based simulation
 *
 * This class was autogenerated by Propel on:
 *
 * Sat Feb  9 00:02:52 2008
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.data
 */
class ElementType extends BaseElementType {

  /**
   * Initializes internal state of ElementType object.
   */
  function __construct($name = "")
  {
    $this->setName($name);
  }

} // ElementType
?>
