<?php

  // include base peer class
  require_once 'lib/data/om/BaseEquipmentClassPeer.php';

  // include object class
  include_once 'lib/data/EquipmentClass.php';


/**
 * Skeleton subclass for performing query and update operations on the 'EquipmentClass' table.
 *
 *
 *
 * This class was autogenerated by Propel on:
 *
 * Sat Feb  9 00:02:55 2008
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.data
 */
class EquipmentClassPeer extends BaseEquipmentClassPeer {


  /**
   * Find an EquipmentClass object based on its ID
   *
   * @param int $id
   * @return EquipmentClass
   */
  public static function find($id) {
    return self::retrieveByPK($id);
  }


  /**
   * Find a list of all EquipmentClass
   *
   * @return array <EquipmentClass>
   */
  public static function findAll() {
    return self::doSelect(new Criteria());
  }



  /**
   * Find an Equipment Class by a given Class Name
   * SELECT * FROM EquipmentClass WHERE className=?
   *
   * @param String $className
   * @return EquipmentClass
   */
  public static function findAllByClassName($className) {
    $c = new Criteria();
    $c->add(self::CLASS_NAME, $className);

    return self::doSelectOne($c);
  }


  /**
   *
   * SELECT
   *    M.EQUIPMENT_CLASS_ID,
   *    C.CLASS_NAME,
   *    COUNT(M.EQUIPMENT_CLASS_ID) AS COUNT
   * FROM
   *    EQUIPMENT_CLASS C LEFT JOIN EQUIPMENT_MODEL M ON C.EQUIPMENT_CLASS_ID = M.EQUIPMENT_CLASS_ID
   * GROUP BY
   *    M.EQUIPMENT_CLASS_ID,
   *    C.CLASS_NAME;
   *
   */
  public static function findGroupByEquipmentModel() {

    $sql = "SELECT
               M.EQUIPMENT_CLASS_ID,
               C.CLASS_NAME,
               COUNT(M.EQUIPMENT_CLASS_ID) AS COUNT
            FROM
               EQUIPMENT_CLASS C LEFT JOIN EQUIPMENT_MODEL M ON C.EQUIPMENT_CLASS_ID = M.EQUIPMENT_CLASS_ID
            GROUP BY
               M.EQUIPMENT_CLASS_ID,
               C.CLASS_NAME";

    $conn = Propel::getConnection(self::DATABASE_NAME);
    $stmt = $conn->prepareStatement($sql);
    $rs = $stmt->executeQuery(ResultSet::FETCHMODE_ASSOC);

    return $rs;
  }
} // EquipmentClassPeer
?>
