<?php

  // include base peer class
  require_once 'lib/data/om/BaseEquipmentGroupedAttributePeer.php';

  // include object class
  include_once 'lib/data/EquipmentGroupedAttribute.php';


/**
 * Skeleton subclass for performing query and update operations on the 'Equipment_Grouped_Attribute' table.
 *
 *
 *
 * This class was autogenerated by Propel on:
 *
 * Sat Feb  9 00:02:56 2008
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.data
 */
class EquipmentGroupedAttributePeer extends BaseEquipmentGroupedAttributePeer {

  /**
   * Find an EquipmentGroupedAttribute object based on its ID
   *
   * @param int $id
   * @return EquipmentGroupedAttribute
   */
  public static function find($id) {
    return self::retrieveByPK($id);
  }


  /**
   * Find all EquipmentGroupedAttributes
   *
   * @return array <EquipmentGroupedAttribute>
   */
  public static function findAll() {
    return self::doSelect(new Criteria());
  }

} // EquipmentGroupedAttributePeer
?>
