<?php

  // include base peer class
  require_once 'lib/data/om/BaseEquipmentGroupedAttributeMapPeer.php';

  // include object class
  include_once 'lib/data/EquipmentGroupedAttributeMap.php';


/**
 * Skeleton subclass for performing query and update operations on the 'Equipment_Grouped_Attr_Map' table.
 *
 *
 *
 * This class was autogenerated by Propel on:
 *
 * Sat Feb  9 00:02:56 2008
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.data
 */
class EquipmentGroupedAttributeMapPeer extends BaseEquipmentGroupedAttributeMapPeer {

  /**
   * Find an EquipmentGroupedAttributeMap object based on its ID
   *
   * @param int $id
   * @return EquipmentGroupedAttributeMap
   */
  public static function find($id) {
    return self::retrieveByPK($id);
  }


  /**
   * Find all EquipmentGroupedAttributeMaps
   *
   * @return array <EquipmentGroupedAttributeMap>
   */
  public static function findAll() {
    return self::doSelect(new Criteria());
  }

} // EquipmentGroupedAttributeMapPeer
?>
