<?php

require_once 'lib/data/om/BaseEquipmentAttributeValue.php';


/**
 * Skeleton subclass for representing a row from the 'EquipmentAttributeValue' table.
 *
 *
 *
 * This class was autogenerated by Propel on:
 *
 * Sat Feb  9 00:02:55 2008
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.data
 *
 * @uses Equipment
 * @uses EquipmentAttribute
 * @uses Unit
 * @uses EquipmentAttributeClass
 */
class EquipmentAttributeValue extends BaseEquipmentAttributeValue {

  /**
   * Initializes internal state of EquipmentAttributeValue object.
   */
  function __construct(Equipment $equipment = null,
                       EquipmentAttributeClass $clattr = null,
                       EquipmentAttribute $attr = null,
                       $value=null,
                       $note=null,
                       Unit $unit=null)
  {
    $this->setEquipment($equipment);
    $this->setEquipmentAttributeClass($clattr);
    $this->setEquipmentAttribute($attr);
    $this->setValue($value);
    $this->setNote($note);
    $this->setUnit($unit);
  }


  /**
   * Return the Web-Services URL that this instance is accessible at
   *
   * @return String RESTURI
   */
  function getRESTURI() {
    return "/EquipmentAttributeValue/{$this->getId()}";
  }


} // EquipmentAttributeValue
?>
