<?php

  // include base peer class
  require_once 'lib/data/om/BaseEquipmentPeer.php';

  // include object class
  include_once 'lib/data/Equipment.php';


/**
 * Skeleton subclass for performing query and update operations on the 'Equipment' table.
 *
 *
 *
 * This class was autogenerated by Propel on:
 *
 * Sat Feb  9 00:02:54 2008
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.data
 */
class EquipmentPeer extends BaseEquipmentPeer {

  /**
   * Find an Equipment object based on its ID
   *
   * @param int $id
   * @return Equipment
   */
  public static function find($id) {
    return self::retrieveByPK($id);
  }


  /**
   * Find a list of all Equipment
   *
   * @return array <Equipment>
   */
  public static function findAll() {
    return self::doSelect(new Criteria());
  }



  /**
   * Find list of Equipment by Organization
   *
   * @param int $orgid
   * @return array <Equipment>
   */
  public static function findAllByOrganization($orgid) {
    $c = new Criteria();
    $c->add(self::ORGID, $orgid);
    $c->addAscendingOrderByColumn(self::NAME);

    return self::doSelect($c);
  }


  /**
   * Find a list of Major Equipment by Organization
   *
   * @param int $orgid
   * @return array <Equipment>
   */
  public static function findAllMajorByOrganization($orgid) {
    $c = new Criteria();
    $c->add(self::ORGID, $orgid);
    $c->add(self::MAJOR, 1);
    $c->addAscendingOrderByColumn(self::NAME);

    return self::doSelect($c);
  }


  /**
   * Find list of Equipment by a Parent Equipment
   *
   * @param int $parentId: The Parent Equipment id
   * @return array <Equipment>
   */
  public static function findAllByParent($parentId) {
    $c = new Criteria();
    $c->add(self::PARENT_ID, $parentId);

    return self::doSelect($c);
  }


  /**
   * Find a list of Equipment given by a Model
   *
   * @param int $modelId
   * @return array <Equipment>
   */
  public static function findByFormat($modelId) {
    $c = new Criteria();
    $c->add(self::MODEL_ID, $modelId);

    return self::doSelect($c);
  }



/*
    $sql = "SELECT e.*
              FROM Equipment e
        INNER JOIN ExperimentEquipment ee
                ON e.equipmentId = ee.equipmentId
        INNER JOIN EquipmentModel em
                ON e.modelId = em.id
        INNER JOIN EquipmentClass ec
                ON em.equipmentClassId = ec.equipmentClassId
             WHERE ee.experimentid = ?
               AND ec.className = ?";

*/
  public static function findByExperimentEquipmentClass($experimentid, $className) {

    require_once 'lib/data/ExperimentEquipmentPeer.php';
    require_once 'lib/data/EquipmentModelPeer.php';
    require_once 'lib/data/EquipmentClassPeer.php';

    $c = new Criteria();
    $c->addJoin(self::EQUIPMENT_ID, ExperimentEquipmentPeer::EQUIPMENT_ID, Criteria::INNER_JOIN);
    $c->addJoin(self::MODEL_ID, EquipmentModelPeer::ID, Criteria::INNER_JOIN);
    $c->addJoin(EquipmentModelPeer::EQUIPMENT_CLASS_ID, EquipmentClassPeer::EQUIPMENT_CLASS_ID, Criteria::INNER_JOIN);
    $c->add(ExperimentEquipmentPeer::EXPERIMENT_ID, $experimentid);
    $c->add(EquipmentClassPeer::CLASS_NAME, $className);
    $c->addAscendingOrderByColumn(self::EQUIPMENT_ID );

    return self::doSelect($c);

  }

  /**
   * Finds the equipment used in a project.  Before Prototype 3, we found
   * that the equipment was being duplicated in the display.  See findByProject
   * below.
   * @param int $p_iProjectId
   * @return array <Equipment>
   * @deprecated
   */
  public static function findByProject0($p_iProjectId){
    require_once 'lib/data/ExperimentEquipmentPeer.php';
    require_once 'lib/data/ExperimentPeer.php';
    require_once 'lib/data/EquipmentModelPeer.php';
    require_once 'lib/data/EquipmentClassPeer.php';

    $c = new Criteria();
    $c->addJoin(self::EQUIPMENT_ID, ExperimentEquipmentPeer::EQUIPMENT_ID, Criteria::INNER_JOIN);
    $c->addJoin(ExperimentEquipmentPeer::EXPERIMENT_ID, ExperimentPeer::EXPID, Criteria::INNER_JOIN);
    $c->addJoin(self::MODEL_ID, EquipmentModelPeer::ID, Criteria::INNER_JOIN);
    $c->addJoin(EquipmentModelPeer::EQUIPMENT_CLASS_ID, EquipmentClassPeer::EQUIPMENT_CLASS_ID, Criteria::INNER_JOIN);
    $c->add(ExperimentPeer::PROJID, $p_iProjectId);
    $c->add(ExperimentPeer::DELETED, 0);
    $c->add(self::DELETED, 0);
    $c->addAscendingOrderByColumn(self::EQUIPMENT_ID );

    return self::doSelect($c);
  }

  public static function findByProject($p_iProjectId){
    $iEquipmentIdArray = array();

    $strQuery = "select distinct e.equipment_id
                 from equipment e,
                     experiment_equipment ee,
                     experiment ex,
                     equipment_model em,
                     equipment_class ec
                 where e.equipment_id = ee.equipment_id
                   and ee.experiment_id = ex.expid
                   and e.model_id = em.id
                   and em.equipment_class_id = ec.equipment_class_id
                   and ex.projid=?";
    $oConnection = Propel::getConnection();
    $oStatement = $oConnection->prepareStatement($strQuery);
    $oStatement->setInt(1, $p_iProjectId);
    $oResultSet = $oStatement->executeQuery(ResultSet::FETCHMODE_ASSOC);
    while($oResultSet->next()){
      $iEquipmentId = $oResultSet->getInt("EQUIPMENT_ID");
      array_push($iEquipmentIdArray, $iEquipmentId);
    }

    //if we have primary keys, lookup and return the equipment
    if(!empty($iEquipmentIdArray)){
      return self::retrieveByPKs($iEquipmentIdArray);
    }

    //otherwise, return the empty array
    return $iEquipmentIdArray;
  }

  public static function findByNameModelIdOrgId($p_strEquipmentName, $p_iModelId, $p_iOrganizationId){
    $c = new Criteria();
    $c->add(self::NAME, $p_strEquipmentName);
    $c->add(self::MODEL_ID, $p_iModelId);
    $c->add(self::ORGID, $p_iOrganizationId);
    $c->add(self::DELETED, 0);
    return self::doSelectOne($c);
  }

} // EquipmentPeer
?>
