<?php

require_once 'lib/data/om/BaseEquipmentGroupedAttributeMap.php';


/**
 * Skeleton subclass for representing a row from the 'Equipment_Grouped_Attr_Map' table.
 *
 *
 *
 * This class was autogenerated by Propel on:
 *
 * Sat Feb  9 00:02:56 2008
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.data
 */
class EquipmentGroupedAttributeMap extends BaseEquipmentGroupedAttributeMap {

  /**
   * Initializes internal state of EquipmentGroupedAttributeMap object.
   */
  public function __construct(
    Attribute $attribute=null,
    $equipmentId=null,
    $g_attribute_id=null,
    $group_value=null
  )
  {
    $this->setAttribute($attribute);
    $this->setEquipmentId($equipmentId);
    $this->setGroupAttributeId($g_attribute_id);
    $this->setGroupValue($group_value);
  }


  /**
   * Return the Web-Services URL that this instance is accessible at
   *
   * @return String RESTURI
   */
  function getRESTURI() {
    return "/EquipmentGroupedAttributeMap/{$this->getId()}";
  }

} // EquipmentGroupedAttributeMap
?>
