<?php

// include base peer class
require_once 'lib/data/om/BaseExperimentModelPeer.php';

// include object class
include_once 'lib/data/ExperimentModel.php';


/**
 * Skeleton subclass for performing query and update operations on the 'ExperimentModel' table.
 *
 *
 *
 * This class was autogenerated by Propel on:
 *
 * Sat Feb  9 00:02:58 2008
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.data
 */
class ExperimentModelPeer extends BaseExperimentModelPeer {

  /**
   * Find an ExperimentModel object based on its ID
   *
   * @param int $id
   * @return ExperimentModel
   */
  public static function find($id) {
    return self::retrieveByPK($id);
  }


  /**
   * Find all ExperimentModels
   *
   * @return array <ExperimentModel>
   */
  public static function findAll() {
    return self::doSelect(new Criteria());
  }


  /**
   * Find ONE ExperimentModel belong to an Experiment and its ID
   *
   * @param int $expid
   * @param int $id
   * @return ExperimentModel
   */
  public static function findOneByIds($expid,  $id) {
    $c = new Criteria();

    $c = new Criteria();
    $c->add(self::EXPID, $expid);
    $c->add(self::ID, $id);

    return self::doSelectOne($c);
  }


  /**
   * Find all ExperimentModels by Experiment
   *
   * @param int $expid
   * @return array <ExperimentModel>
   */
  public static function findByExperiment($expid) {
    $c = new Criteria();
    $c->add(self::EXPID, $expid);

    return self::doSelect($c);
  }



  /**
   * Find all ExperimentModels by a Model Type
   *
   * @param int $typeid
   * @return array <ExperimentModel>
   */
  public static function findByModelType($typeid) {
    $c = new Criteria();
    $c->add(self::TYPEID, $typeid);

    return self::doSelect($c);
  }


  /**
   * Find all ExperimentModels by a ModelType and Experiment
   *
   * @param int $expid
   * @param int $typeid
   * @return array <ExperimentModel>
   */
  public static function findByExpModelType($expid, $typeid) {
    $c = new Criteria();
    $c->add(self::EXPID, $expid);
    $c->add(self::TYPEID, $typeid);

    return self::doSelect($c);
  }


  /**
   * Clone the ExperimentModel to another
   *
   * @param Experiment $old_exp
   * @param Experiment $new_exp
   * @return boolean value, true if successed, false if failed
   */
  public static function cloneExperimentModel(Experiment $old_exp, Experiment $new_exp){

    if(is_null($old_exp) || is_null($new_exp)) return false;

    $sql = "INSERT INTO
              Experiment_Model (ID, TYPEID, EXPID, NAME, DESCRIPTION)
            SELECT
              EXPERIMENT_MODEL_SEQ.NEXTVAL,
              TYPEID,
              ?,
              NAME,
              DESCRIPTION
            FROM
              Experiment_Model
            WHERE
              EXPID = ?";

    try {
      $conn = Propel::getConnection(self::DATABASE_NAME);

      $stmt = $conn->prepareStatement($sql);
      $stmt->setInt(1, $new_exp->getId());
      $stmt->setInt(2, $old_exp->getId());
      $stmt->executeUpdate();

      return true;
    }
    catch (Exeption $e) {
      return false;
    }
  }


} // ExperimentModelPeer
?>
