<?php

  // include base peer class
  require_once 'lib/data/om/BaseExperimentModelTypePeer.php';

  // include object class
  include_once 'lib/data/ExperimentModelType.php';


/**
 * Skeleton subclass for performing query and update operations on the 'ExperimentModelType' table.
 *
 *
 *
 * This class was autogenerated by Propel on:
 *
 * Sat Feb  9 00:02:58 2008
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.data
 */
class ExperimentModelTypePeer extends BaseExperimentModelTypePeer {

  /**
   * Find an ExperimentModelType object based on its ID
   *
   * @param int $id
   * @return ExperimentModelType
   */
  public static function find($id) {
    return self::retrieveByPK($id);
  }

  /**
   * Find all ExperimentModelType
   *
   * @return array <ExperimentModelType>
   */
  public static function findAll() {
    $c =new Criteria();
    $c->addAscendingOrderByColumn(self::DISPLAY_NAME);

    return self::doSelect($c);
  }


  /**
   * Find one ExperimentModelType by a Model
   *
   * @param int $id
   * @return ExperimentModelType
   */
  public static function findByModel($id) {
    $c =new Criteria();
    $c->addJoin(self::ID, ExperimentModelPeer::TYPEID);
    $c->add(ExperimentModelPeer::ID, $id);

    return self::doSelectOne($c);
  }


  /**
   * Find one ExperimentModelType by a Model
   *
   * @param int $id
   * @return ExperimentModelType
   */
  public static function findByDisplayName($name) {
    $c =new Criteria();
    $c->add(self::DISPLAY_NAME, $name);

    return self::doSelectOne($c);
  }

} // ExperimentModelTypePeer
?>
