<?php

require_once 'lib/data/om/BaseMaterialProperty.php';


/**
 * MaterialProperty
 *
 *
 *
 * This class was autogenerated by Propel on:
 *
 * Sat Feb  9 00:03:02 2008
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.data
 *
 * @uses Material
 * @uses MaterialTypeProperty
 * @uses MeasurementUnit
 *
 */
class MaterialProperty extends BaseMaterialProperty {

  /**
   * Initializes internal state of MaterialProperty object.
   */
  function __construct(MaterialTypeProperty $materialTypeProperty=null,
                       Material $material = null,
                       $value = "",
                       MeasurementUnit $unit = null)
  {
    $this->setMaterialTypeProperty($materialTypeProperty);
    $this->setMaterial($material);
    $this->setValue($value);
    $this->setMeasurementUnit($unit);
  }



  /**
   * Return the Web-Services URL that this instance is accessible at
   *
   * @return String RESTURI
   */
  function getRESTURI() {
    return "/MaterialProperty/{$this->getId()}";
  }

  /**
   * Wrap {@link BaseMaterialProperty::getMeasurementUnit}
   * Backward compatible to NEEScentral 1.7
   *
   * @return MeasurementUnit
   */
  public function getUnit() {
    return $this->getMeasurementUnit();
  }


  /**
   * Set the MeasurementUnit for this MaterialProperty
   * Backward compatible to NEEScentral 1.7
   *
   * @param MeasurementUnit $unit
   */
  public function setUnit(MeasurementUnit $unit) {
    return $this->setMeasurementUnit($unit);
  }

} // MaterialProperty
?>
