<?php

require_once 'lib/data/om/BaseNAWIFacility.php';


/**
 * Skeleton subclass for representing a row from the 'NAWI_Facility' table.
 *
 *
 *
 * This class was autogenerated by Propel on:
 *
 * Sat Feb  9 00:03:04 2008
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.data
 */
class NAWIFacility extends BaseNAWIFacility {

  /**
   * Initializes internal state of NAWIFacility object.
   */
  public function __construct()
  {
  }


  /**
   * get the WAWI Facility for this NAWIFacility object.
   * Note that the Organization here is the Facility because we merge Facility and Organization into one table Organization
   *
   * @return Facility
   */
  public function getFacility() {
    return $this->getOrganization();
  }


  /**
   * Return the Web-Services URL that this instance is accessible at
   *
   * @return String RESTURI
   */
  function getRESTURI() {
    return "/NAWIFacility/{$this->getId()}";
  }

} // NAWIFacility
?>
