<?php

  // include base peer class
  require_once 'lib/data/om/BaseSensorGroupedAttributeMapPeer.php';

  // include object class
  include_once 'lib/data/SensorGroupedAttributeMap.php';


/**
 * Skeleton subclass for performing query and update operations on the 'Sensor_Grouped_Attribute_Map' table.
 *
 *
 *
 * This class was autogenerated by Propel on:
 *
 * Sat Feb  9 00:03:10 2008
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.data
 */
class SensorGroupedAttributeMapPeer extends BaseSensorGroupedAttributeMapPeer {

  /**
   * Find a SensorGroupedAttributeMap object based on its ID
   *
   * @param int $id
   * @return SensorGroupedAttributeMap
   */
  public static function find($id) {
    return self::retrieveByPK($id);
  }


  /**
   * Find all SensorGroupedAttributeMaps
   *
   * @return array <SensorGroupedAttributeMap>
   */
  public static function findAll() {
    return self::doSelect(new Criteria());
  }


} // SensorGroupedAttributeMapPeer
?>
