<?php

require_once 'lib/data/om/BaseSensorType.php';


/**
 * Skeleton subclass for representing a row from the 'SensorType' table.
 *
 *
 *
 * This class was autogenerated by Propel on:
 *
 * Sat Feb  9 00:03:09 2008
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.data
 */
class SensorType extends BaseSensorType {

  /**
   * Constructs a new SensorType Object
   */
  public function __construct($name = '')
  {
    $this->setName($name);
  }

  /**
   * Return the Web-Services URL that this instance is accessible at
   *
   * @return String RESTURI
   */
  function getRESTURI() {
    return "/SensorType/{$this->getId()}";
  }


} // SensorType
?>
