<?php

require_once 'lib/data/om/BaseSourceType.php';


/**
 * Skeleton subclass for representing a row from the 'SourceType' table.
 *
 *
 *
 * This class was autogenerated by Propel on:
 *
 * Sat Feb  9 00:03:12 2008
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.data
 */
class SourceType extends BaseSourceType {

  /**
   * Constructs a new SourceType Object
   */
  public function __construct($name = '',
                              $system_name = ''
  )
  {
    $this->setName($name);
    $this->setSystemName($system_name);
  }

  /**
   * Return the Web-Services URL that this instance is accessible at
   *
   * @return String RESTURI
   */
  function getRESTURI() {
    return "/SourceType/{$this->getId()}";
  }

} // SourceType
?>
