<?php

  // include base peer class
  require_once 'lib/data/om/BaseUnitPeer.php';

  // include object class
  include_once 'lib/data/Unit.php';


/**
 * Skeleton subclass for performing query and update operations on the 'Unit' table.
 *
 *
 *
 * This class was autogenerated by Propel on:
 *
 * Sat Feb  9 00:03:18 2008
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.data
 */
class UnitPeer extends BaseUnitPeer {

  /**
   * Find a Unit object based on its ID
   *
   * @param int $id
   * @return Unit
   */
  public static function find($id) {
    return self::retrieveByPK($id);
  }


  /**
   * Find a list of all Unit
   *
   * @return array <Unit>
   */
  public static function findAll() {
    return self::doSelect(new Criteria());
  }


} // UnitPeer
?>
