		<article>
			<h1><span>Knowledge Base: Article</span></h1>

			<ul class="nav">
				<li><a href="#overview">Overview</a></li>
				<li><a href="#toolbar">Toolbar</a></li>
				<li><a href="#details">Details</a></li>
				<li><a href="#state">State</a></li>
				<li><a href="#parameters">Parameters</a></li>
			</ul>

			<section id="overview">
				<h2><span>Overview</span></h2>

				<p>A knowledge base article.</p>
			</section>
			<section id="toolbar">
				<h2><span>Toolbar</span></h2>
				<p>At the top right you will see the toolbar.</p>
				<p>The functions are:</p>
				<dl>
					<dt>Save</dt>
					<dd>Save changes and return to the edit form.</dd>

					<!-- <dt>Save &amp; Close</dt>
					<dd>Save changes and return to the listing of entries.</dd> -->

					<dt>Cancel</dt>
					<dd>Discard any changes made and return to the listing of entries.</dd>

					<dt>Help</dt>
					<dd>Opens this help screen.</dd>
				</dl>
			</section>
			<section id="details">
				<h2><span>Details</span></h2>

				<p>Every entry consists of a <strong>title</strong>, <strong>alias</strong>, and <strong>content</strong>.</p>

				<dl>
					<dt>Category</dt>
					<dd>The category the article resides in.</dd>

					<dt>Sub-category</dt>
					<dd>The sub-category the article resides in.</dd>

					<dt>Title</dt>
					<dd>The title of the post. A required field.</dd>

					<dt>Alias</dt>
					<dd>This is an optional identifier used priamrily for URLs. When an alias isn't provided, one is generated from the provided title. The text is made lowercase, all punctuation is stripped, and spaces are turned into dashes.</dd>

					<dt>Body</dt>
					<dd>The primary body of the post. A required field.</dd>

					<dt>Tags</dt>
					<dd>This is an optional, comma-separated list of keywords or phrases that describe the content of the entry.</dd>
				</dl>
			</section>
			<section id="state">
				<h2><span>State</span></h2>

				<p>The following options control various aspects of the published state (when and if an entry is available to users).</p>

				<dl>
					<dt>State</dt>
					<dd>The published status of the entry. Unpublished and trashed jobs will never be run.</dd>

					<dt>Access level</dt>
					<dd>Which user 'access levels' have access to this item. You can change an item's Access Level by clicking on its name to open it up for editing. The default user 'access levels' which come preconfigured are:
						<ul>
							<li>Public: Everyone has access including website visitors who have not logged in</li>
							<li>Registered: Only users with registered status or higher will have access</li>
							<li>Special: Only users with author status or higher have access</li>
						</ul>
					</dd>
				</dl>
			</section>
			<section id="Parameters">
				<h2><span>Parameters</span></h2>

				<p>The following options control various aspects of the article's display and functionality.</p>

				<dl>
					<dt>Authors</dt>
					<dd>Show or hide the author of the article.</dd>

					<dt>Comments</dt>
					<dd>Allow or disallow comments on an article. If allowed, a comment thread and post form will be displayed below the article.</dd>

					<dt>Close Comments</dt>
					<dd>If comments are enabled: The time period in which to disable the post form and disallow any new comments.</dd>

					<dt>Feeds</dt>
					<dd>Enable or disable a comment RSS feed.</dd>

					<dt>Feed Entries</dt>
					<dd>The amount of text to be displayed within the feed.</dd>

					<dt>Date</dt>
					<dd>(Hide/Created/Modified/Published) How (And what) date to display on the article.</dd>
				</dl>
			</section>
		</article>