<article>
	<h1><span>Groups Manager: Pages</span></h1>

	<ul class="nav">
		<li><a href="#overview">Overview</a></li>
		<li><a href="#column-headers">Column Headers</a></li>
		<li><a href="#toolbar">Toolbar</a></li>
		<li><a href="#list-filters">List Filters</a></li>
	</ul>

	<section id="overview">
		<h2><span>Overview</span></h2>

		<p>Here you will a list of pages associated with a group.</p>
	</section>
	<section id="column-headers">
		<h2><span>Column Headers</span></h2>

		<p>Click on the column heading to sort the list by that column's value. The list will be sorted in order by that column and a sort icon will show next to the column name. Click a second time to reverse the sort to high-to-low. The sort icon will change to high-to-low.</p>

		<dl>
			<dt>Checkbox</dt>
			<dd>Check this box to select one or more items. To select all items, check the box in the column heading. After one or more boxes are checked, click a toolbar button to take an action on the selected item or items. Many toolbar actions, such as Publish and Unpublish, can work with multiple items. Others, such as Edit, only work on one item at a time. If multiple items are checked and you press Edit, the first item will be opened for editing.</dd>

			<dt>Title</dt>
			<dd>The name of the item. This entry is required. You can open the item for editing by clicking on the Title.</dd>

			<dt>Order</dt>
			<dd>The order in which to display items. You can sort the list by order number by clicking on the Order label in the column heading. If the list is sorted by this column, you can change the order by clicking the arrows or by entering the sequential order and clicking the 'Save Order' icon. Note that the ordering is only defined within a single category. For this reason, it is easier to re-order the list if you use the Category filter to select one category.</dd>

			<dt>State</dt>
			<dd>(Public/Private/Registered/Trashed) The published status of the item.</dd>

			<dt>Home</dt>
			<dd>This indicates if a page is makred as the default or "home" page for a group.</dd>

			<dt>Versions</dt>
			<dd>Denotes the number of versions a page has.</dd>
		</dl>
	</section>
	<section id="toolbar">
		<h2><span>Toolbar</span></h2>
		<p>At the top right you will see the toolbar. The functions are:</p>
		<dl>
			<dt>New</dt>
			<dd>Opens the editing screen to create a new group.</dd>

			<dt>Edit</dt>
			<dd>Opens the editing screen for the selected group. If more than one group is selected (where applicable), only the first group will be opened. The editing screen can also be opened by clicking on the Name of the group.</dd>

			<dt>Trash</dt>
			<dd>Permanently removes the selected entries and any associated content.</dd>

			<dt>Manage</dt>
			<dd>Click to edit the current group viewing pages for.</dd>

			<dt>Help</dt>
			<dd>Opens this help screen.</dd>
		</dl>
	</section>
	<section id="list-filters">
		<h2><span>List Filters</span></h2>

		<dl>
			<dt>Page Controls</dt>
			<dd>
				<p>When the number of items is more than one page, you will see a page control bar as shown below.</p>

				<dl>
					<dt>Display #</dt>
					<dd>Select the number of items to show on one page.</dd>
					<dt>Start</dt>
					<dd>Click to go to the first page.</dd>
					<dt>Prev</dt>
					<dd>Click to go to the previous page.</dd>
					<dt>Page numbers</dt>
					<dd>Click to go to the desired page.</dd>
					<dt>Next</dt>
					<dd>Click to go to the next page.</dd>
					<dt>End</dt>
					<dd>Click to go to the last page.</dd>
				</dl>
			</dd>
		</dl>
	</section>
</article>