<article>
	<h1><span>Search</span></h1>
	<section id="site-map">
		<h2><span>Site Map</span></h2>

		<p>The site search is aimed at accessing content, not structure. So, queries look for certain parts of the site may not work as well as one might hope, instead turning up tangentially related pieces of content. By encoding the site structure as content here the search has a better chance of doing the right thing.</p>
	</section>
</article>