<article>
	<h1><span>Forum Manager: Threads</span></h1>

	<ul class="nav">
		<li><a href="#overview">Overview</a></li>
		<li><a href="#column-headers">Column Headers</a></li>
		<li><a href="#toolbar">Toolbar</a></li>
		<li><a href="#sub-menu">Sub-menu Links</a></li>
		<li><a href="#list-filters">List Filters</a></li>
	</ul>

	<section id="overview">
		<h2><span>Overview</span></h2>

		<p>Here you will a list of threads. A thread is composed of one or more posts ordered in a chronological fashion.</p>
	</section>
	<section id="column-headers">
		<h2><span>Column Headers</span></h2>

		<p>Click on the column heading to sort the list by that column's value. The list will be sorted in order by that column and a sort icon will show next to the column name. Click a second time to reverse the sort to high-to-low. The sort icon will change to high-to-low.</p>

		<dl>
			<dt>Checkbox</dt>
			<dd>Check this box to select one or more items. To select all items, check the box in the column heading. After one or more boxes are checked, click a toolbar button to take an action on the selected item or items. Many toolbar actions, such as Publish and Unpublish, can work with multiple items. Others, such as Edit, only work on one item at a time. If multiple items are checked and you press Edit, the first item will be opened for editing.</dd>

			<dt>ID</dt>
			<dd>This is a unique identification number for this item assigned automatically by the system. It is used to identify the item internally and cannot be changed. When creating a new item, this field is 0 until the entry is saved, at which point a new ID is assigned to it.</dd>

			<dt>Title</dt>
			<dd>The name of the item. This entry is required. You can view the posts in a thread by clicking on the Title.</dd>

			<dt>State</dt>
			<dd>(Public/Private/Registered/Trashed) The published status of the item.</dd>

			<dt>Sticky</dt>
			<dd>The "sticky" state of an item. Sticky threads will appear at the top of the list of threads, regardless of the sorting or age. This is a way of ensuring users see certain threads deemed important.</dd>

			<dt>Access</dt>
			<dd>The viewing level access for this item.</dd>

			<dt>Scope</dt>
			<dd>Scope is comprised of the the type of object and unique identifier the forum is associated with, since individual groups, courses, ec. can have their own forums.</dd>

			<dt>Creator</dt>
			<dd>The creator of the thread.</dd>

			<dt>Created</dt>
			<dd>The timestamp of when the thread was created.</dd>
		</dl>
	</section>
	<section id="toolbar">
		<h2><span>Toolbar</span></h2>
		<p>At the top right you will see the toolbar.</p>
		<p>The functions are:</p>
		<dl>
			<dt>Options</dt>
			<dd>Opens the Options window where settings such as default parameters or permissions can be edited.</dd>

			<dt>Publish</dt>
			<dd>Makes the selected posts available to visitors to the site.</dd>

			<dt>Unpublish</dt>
			<dd>Makes the selected posts unavailable to visitors to the site.</dd>

			<dt>New</dt>
			<dd>Opens the editing screen to create a new article.</dd>

			<dt>Trash</dt>
			<dd>Permanently removes the selected entries and any associated content (categories and posts).</dd>

			<dt>Help</dt>
			<dd>Opens this help screen.</dd>
		</dl>
	</section>
	<section id="sub-menu">
		<h2><span>Sub-menu Links</span></h2>
		<p>At the top left, above the filters, you will see sub-menu options. These are the various levels of organization of a forum, in order of specificity. The links are:</p>
		<dl>
			<dt>Sections</dt>
			<dd>Show all sections. Categories can be filtered by a specific scope (forum).</dd>
			<dt>Categories</dt>
			<dd>Show categories within a forum. Categories can be further filtered by a specific section or scope.</dd>
			<dt>Threads</dt>
			<dd>Show threads of dicussion within a forum. Threads can be further filtered by category and scope.</dd>
		</dl>
	</section>
	<section id="list-filters">
		<h2><span>List Filters</span></h2>
		<p>Above the column headers is a search box for filtering results by <strong>category</strong>.</p>

		<h3>Page Controls</h3>
		<p>When the number of items is more than one page, you will see a page control bar as shown below.</p>

		<dl>
			<dt>Display #</dt>
			<dd>Select the number of items to show on one page.</dd>
			<dt>Start</dt>
			<dd>Click to go to the first page.</dd>
			<dt>Prev</dt>
			<dd>Click to go to the previous page.</dd>
			<dt>Page numbers</dt>
			<dd>Click to go to the desired page.</dd>
			<dt>Next</dt>
			<dd>Click to go to the next page.</dd>
			<dt>End</dt>
			<dd>Click to go to the last page.</dd>
		</dl>
	</section>
</article>