<article>
	<h1><span>Jobs Manager: Edit Job</span></h1>

	<ul class="nav">
		<li><a href="#overview">Overview</a></li>
		<li><a href="#toolbar">Toolbar</a></li>
		<li><a href="#company">Company</a></li>
		<li><a href="#job">Job</a></li>
		<li><a href="#contact">Contact</a></li>
		<li><a href="#manage">Manage This Job</a></li>
	</ul>

	<section id="description">
		<h2><span>Description</span></h2>
		<p>This is where you can add a new Section or edit an existing Section.</p>
	</section>
	<section id="toolbar">
		<h2><span>Toolbar</span></h2>
		<p>At the top right you will see the toolbar.</p>
		<p>The functions are:</p>
		<dl>
			<dt>Save &amp; Close</dt>
			<dd>Save changes and return to the listing of entries.</dd>

			<dt>Cancel</dt>
			<dd>Discard any changes made and return to the listing of entries.</dd>

			<dt>Help</dt>
			<dd>Opens this help screen.</dd>
		</dl>
	</section>
	<section id="company">
		<h2><span>Company</span></h2>

		<p>This is for specifying details about the employing company.</p>

		<dl>
			<dt>Name</dt>
			<dd>The name of the company.</dd>

			<dt>URL</dt>
			<dd>The URL to the company's site (if exists).</dd>

			<dt>Location</dt>
			<dd>Company location. This is typically City name, State and/or Country.</dd>
		</dl>
	</section>
	<section id="job">
		<h2><span>Job</span></h2>

		<dl>
			<dt>Category</dt>
			<dd>The category the job can be found in. The categories can be managed by clicking "Categories" from the sub-menu of the Jobs Manager.</dd>

			<dt>Type</dt>
			<dd>The type of position. This is usually somehting like Full-Time, Part-Time, Freelance, or other common descriptor. The types can be managed by clicking "Types" from the sub-menu of the Jobs Manager.</dd>

			<dt>Country</dt>
			<dd>The country the job is in.</dd>

			<dt>Title</dt>
			<dd>The job position title.</dd>

			<dt>Description</dt>
			<dd>A description for the job. This should enclude information about the details of the job, such as daily duties, qualifications needed, etc.</dd>

			<dt>Position Start Date</dt>
			<dd>When the job starts.</dd>

			<dt>Applications Due</dt>
			<dd>A due date for all applications to be in by.</dd>

			<dt>External URL</dt>
			<dd>An externam URL, possibly with further details or a submission form, related to the position.</dd>

			<dt>Allow internal application</dt>
			<dd>Allow site administrators and employees to apply for this position?</dd>
		</dl>
	</section>
	<section id="contact">
		<h2><span>Contact Information</span></h2>

		<p>This is optional contact information pertaining to the job.</p>

		<dl>
			<dt>Name</dt>
			<dd>The name of whom to contact.</dd>

			<dt>Email</dt>
			<dd>The email address of whom to contact.</dd>

			<dt>Phone</dt>
			<dd>A phone number the person can be reached at.</dd>
		</dl>
	</section>
	<section id="manage">
		<h2><span>Manage This Job</span></h2>

		<p>These are administrative controls for changing status and/or messaging the entry creator.</p>

		<dl>
			<dt>Change Status / Take Action</dt>
			<dd>An action to perform.</dd>

			<dt>Message to Author</dt>
			<dd>A message to send to the entry creator.</dd>
		</dl>
	</section>
</article>