<article>
	<h1><span>Store Manager: Edit Item</span></h1>

	<ul class="nav">
		<li><a href="#overview">Overview</a></li>
		<li><a href="#toolbar">Toolbar</a></li>
		<li><a href="#details">Details</a></li>
		<li><a href="#options">Options</a></li>
		<li><a href="#picture">Picture</a></li>
	</ul>

	<section id="description">
		<h2><span>Description</span></h2>
		<p>This is where you can add a new Item or edit an existing Item.</p>
	</section>
	<section id="toolbar">
		<h2><span>Toolbar</span></h2>
		<p>At the top right you will see the toolbar. The functions are:</p>
		<dl>
			<dt>Save &amp; Close</dt>
			<dd>Save changes and return to the listing of entries.</dd>

			<dt>Cancel</dt>
			<dd>Discard any changes made and return to the listing of entries.</dd>

			<dt>Help</dt>
			<dd>Opens this help screen.</dd>
		</dl>
	</section>
	<section id="details">
		<h2><span>Details</span></h2>

		<dl>
			<dt>Category</dt>
			<dd>A category that the item can be found in. This helps not only users to discover content but managers as well.</dd>

			<dt>Price</dt>
			<dd>The price without denomination of the Item.</dd>

			<dt>Title</dt>
			<dd>The Title for this item. This may or may not display on the page, depending on the parameter values you choose.</dd>

			<dt>Description</dt>
			<dd>A short description for the product.</dd>
		</dl>
	</section>
	<section id="options">
		<h2><span>Options</span></h2>

		<dl>
			<dt>Published</dt>
			<dd>The published status of the item. Unpublished items will not appear in the store.</dd>

			<dt>In Stock</dt>
			<dd>The availability of the item.</dd>

			<dt>Featured</dt>
			<dd>Indicates if the item is a "featureD" item or not. Featured items may be displayed differently in the store.</dd>

			<dt>Available Sizes</dt>
			<dd>A comma-separated list of sizes (e.g. L, S, M). This may not apply to many items.</dd>
		</dl>
	</section>
	<section id="picture">
		<h2><span>Picture</span></h2>

		<p>A picture of the item.</p>
	</section>
</article>