<article>
	<h1>Category Manager: Edit Category</h1>

	<h2> <span class="mw-headline" id="How_to_Access">How to Access</span></h2>
<p>Navigate to the <a href="/proxy/index.php?option=com_help&view=help&keyref=Help25:Components_Content_Categories" title="Help25:Components Content Categories">Category Manager</a>. To add a new Category, press the 'New' icon in the toolbar. To edit an existing Category, click on the Category title or click the Category's checkbox and then click on the Edit icon in the toolbar.
</p>
<h2> <span class="mw-headline" id="Description">Description</span></h2>
<p>This is where you can add a new Category or edit an existing Category. Categories allow you to display related Articles together on a page and to filter Articles in the Article Manager. All Articles are assigned either to a Category that you create or to the special Category called 'Uncategorized'.
</p>
<h2> <span class="mw-headline" id="Screenshot">Screenshot</span></h2>
<p><a href="/proxy/index.php?option=com_help&view=help&keyref=File:Help25-content_category_edit.png" class="image"><img alt="Help25-content category edit.png" src="http://docs.joomla.org/images/5/52/Help25-content_category_edit.png" width="800" height="416" /></a>
</p>
<h2> <span class="mw-headline" id="Coloumn_Headers">Coloumn Headers</span></h2>
<h3> <span class="mw-headline" id="Details">Details</span></h3>
<ul><li><b>Title.</b> The Title for this item. This may or may not display on the page, depending on the parameter values you choose.
</li></ul>
<ul><li><b>Alias.</b> The internal name of the item. Normally, you can leave this blank and Joomla! will fill in a default value. The default value is the Title or Name in lower case and with dashes instead of spaces. You may enter the Alias manually. The Alias should consist of lowercase letters and hyphens (-). No blank spaces or underscores are allowed. The Alias will be used in the URL when SEF is activated. Note: If the title consists of non-Latin characters, the Alias will default to the current date and time, for example "2009-02-11-17-54-38".
</li></ul>
<ul><li><b>Parent.</b> Allows a parent category for the category being edited/created to be chosen.
</li></ul>
<ul><li><b>Published.</b> Whether or not this item is published. Select <i>Yes</i> or <i>No</i> from the radio button group to set the Published state for this item.
</li></ul>
<ul><li> <b>Access Level</b>. Who has access to this item. Current options are:
<ul><li> <span style="color:green">Public</span>: Everyone has access
</li><li> <span style="color:red">Registered</span>: Only registered users have access
</li><li> <span style="color:black">Special</span>: Only users with author status or higher have access
</li></ul>
</li></ul>
<dl><dd>Enter the desired level using the drop-down list box.
</dd></dl>
<ul><li><b>Category Permissions.</b>
</li></ul>
<dl><dd>The permissions section for the category will be at the bottom of the screen and will look like the following:
</dd></dl>
<dl><dd><a href="/proxy/index.php?option=com_help&view=help&keyref=File:Help25-admin-components-search-options-permissions.png" class="image"><img alt="Help25-admin-components-search-options-permissions.png" src="http://docs.joomla.org/images/e/e5/Help25-admin-components-search-options-permissions.png" width="670" height="315" /></a>
</dd></dl>
<dl><dd>The options allowed are:
</dd><dd>
<dl><dt>Create&#160;</dt><dd> Create new items in the category
</dd></dl>
</dd><dd>
<dl><dt>Delete&#160;</dt><dd> Delete existing items in the category
</dd></dl>
</dd><dd>
<dl><dt>Edit&#160;</dt><dd> Edit existing items in the category
</dd></dl>
</dd><dd>
<dl><dt>Edit State&#160;</dt><dd> Change an items state (Publish, Unpublish, Archive, and Trash) in the category.
</dd></dl>
</dd><dd>
<dl><dt>Edit Own&#160;</dt><dd> Edit existing items in the category that the logged in user has created.
</dd></dl>
</dd></dl>
<dl><dd>There are two very important points to understand from this screen. The first is to see how the permissions can be inherited from the parent Group. The second is to see how you can control the default permissions by Group and by Action.
</dd></dl>
<dl><dd>This provides a lot of flexibility. For example, if you wanted Shop Suppliers to be able to have the ability to create an item in the category, you could just change their Create value to "Allowed". If you wanted to not allow members of Administrator group to delete objects or change their state, you would change their permissions in these columns to Inherited (or Denied).
</dd><dd>It is also important to understand that the ability to have child groups is completely optional. It allows you to save some time when setting up new groups. However, if you like, you can set up all groups to have Public as the parent and not inherit any permissions from a parent group.
</dd></dl>
<dl><dd>Please note the inherited values will come from the Permissions set in the <a href="/proxy/index.php?option=com_help&view=help&keyref=Help25:Site_Global_Configuration#Permissions" title="Help25:Site Global Configuration">Global Configuration Permissions Tab</a>
</dd></dl>
<ul><li> <b>Description</b>. The description for the item. Section and Category descriptions for Articles may be shown on web pages, depending on the parameter settings. These descriptions are entered using the same editor that is used for Articles. Note that Section and Category descriptions may not be edited from the front end.
</li></ul>
<ul><li> <b>Language.</b> Select the language for this item. If you are not using the multi-language feature of Joomla, keep the default of 'All'.
</li></ul>
<ul><li><b>ID.</b> The unique ID number automatically assigned to this item by Joomla!. This number cannot be changed.
</li></ul>
<h3> <span class="mw-headline" id="Category_Description">Category Description</span></h3>
<p>This is where you enter the description of the category. The editor you use depends on the settings for your site and your user. Joomla core includes three editor options: TinyMCE (the default), Code Mirror, and None. Additional editors can be installed as extension plugins if desired (see the Joomla Extensions direction category of editors for a list).
</p>
<h4> <span class="mw-headline" id="TinyMCE_Editor">TinyMCE Editor</span></h4>
<p>TinyMCE is the default editor for both front-end and back-end users. TinyMCE is a WYSIWYG (what you see is what you get) editor that allows users a familiar word-processing interface to use when editing Articles and other content. TinyMCE can be configured with three different sets of toolbar buttons: advanced, simple, and extended. This is set as an option in the <a href="/proxy/index.php?option=com_help&view=help&keyref=Help25:Extensions_Plugin_Manager" title="Help25:Extensions Plugin Manager"> Plugin Manager</a> for the 'Editor - TinyMCE' plugin.
</p><p><b>Advanced Toolbar</b>
</p>
The advanced toolbar provides a three-row toolbar as shown below: <div class="thumb tnone"><div class="thumbinner" style="width:613px;"><a href="/proxy/index.php?option=com_help&view=help&keyref=File:Help25-screenshot-editor-tinymce-advanced.png" class="image"><img alt="Help25-screenshot-editor-tinymce-advanced.png" src="http://docs.joomla.org/images/a/ad/Help25-screenshot-editor-tinymce-advanced.png" width="611" height="82" class="thumbimage" /></a>  <div class="thumbcaption"></div></div></div>
<p>This is the default setting. The 3-row toolbar below provides many standard editing commands, as follows:
</p>
<ul><li><b>Top Row.</b> 
<ul><li>Buttons in the upper left allow you to make text bold, italic, underlined, or strikethrough. Next to that are buttons for align left, right, center, and full. 
</li><li>Styles. Caption and System Pagebreak styles can be set. Highlight the desired text and select the style. This will allow this text to be formatted based on CSS rules.
</li><li>Format. Select pre-defined formats for Paragraph, Address, Heading1, and so on.
</li></ul>
</li></ul>
<ul><li><b>Second Row.</b> 
<ul><li>Unordered List, Ordered list, Outdent (move left) and Indent (indent right). 
</li><li>Undo (Ctrl+Z) and Re-do (Ctrl+Y).
</li><li>Insert/Edit Link. To insert or edit a link, select the linked text and press this button. A popup dialog displays that lets you enter details about the link.
</li><li>Unlink. To remove a link, highlight the linked text and press this button.
</li><li>Insert/Edit Anchor. An <a href="/proxy/index.php?option=com_help&view=help&keyref=Glossary#Anchor" title="Glossary"> anchor</a> is a bookmark inside an article that lets you link directly to that point in the article. To insert an anchor, move the cursor to the desired location within the article and click this button. A window will display. Enter the name of the Anchor and press Insert. A small anchor icon will show in the location of the anchor. You can edit the name of the anchor by clicking on it and pressing this button. You can delete the anchor just by selecting it and pressing the Delete key.
</li><li>Insert/Edit Image. To insert and image, place the cursor in the desired location and press this button. A popup dialog displays that lets you enter in the Image URL and other information about how the image will display.
</li><li>Cleanup Messy Code. This button allows you to clean up HTML code, perhaps from HTML text that you copied in from another source.
</li><li>About TinyMCE editor. Shows the TinyMCE version.
</li><li>Edit HTML Source. A popup displays showing the HTML source code, allowing you to edit the HTML source code.
</li></ul>
</li></ul>
<ul><li><b>Third Row.</b>
<ul><li>Insert Horizontal Ruler.
</li><li>Remove Formatting.
</li><li>Toggle Guidelines/Invisible elements.
</li><li>Subscript, Superscript, Insert Custom Character
</li></ul>
</li></ul>
<p><b>Simple Toolbar</b>
</p>
The simple toolbar provides one row of buttons as shown below.<div class="thumb tnone"><div class="thumbinner" style="width:612px;"><a href="/proxy/index.php?option=com_help&view=help&keyref=File:Help25-screenshot-editor-tinymce-simple.png" class="image"><img alt="Help25-screenshot-editor-tinymce-simple.png" src="http://docs.joomla.org/images/a/aa/Help25-screenshot-editor-tinymce-simple.png" width="610" height="25" class="thumbimage" /></a>  <div class="thumbcaption"></div></div></div>
<ul><li><b>First Row.</b>
<ul><li>Buttons allow you to make text bold, italic, underlined, or strikethrough.
</li><li>Undo (Ctrl+Z) and Re-do (Ctrl+Y).
</li><li>Cleanup Messy Code. This button allows you to clean up HTML code, perhaps from HTML text that you copied in from another source.
</li><li>Unordered list, Ordered list.
</li></ul>
</li></ul>
The extended toolbar provides the most extensive editing options, as shown below.<div class="thumb tnone"><div class="thumbinner" style="width:611px;"><a href="/proxy/index.php?option=com_help&view=help&keyref=File:Help25-screenshot-editor-tinymce-extended.png" class="image"><img alt="Help25-screenshot-editor-tinymce-extended.png" src="http://docs.joomla.org/images/9/91/Help25-screenshot-editor-tinymce-extended.png" width="609" height="106" class="thumbimage" /></a>  <div class="thumbcaption"></div></div></div>This option provides all of the same buttons as documented in the Advanced Toolbar above. In addition, the following options are available:
<ul><li><b>First Row.</b>
<ul><li>Font Family. Select the desired font.
</li><li>Font Size. Select the desired font size.
</li></ul>
</li></ul>
<ul><li><b>Second Row.</b>
<ul><li>Find and Find/Replace.
</li><li>Insert Date or Time.
</li><li>Select Text Color or Background Color.
</li><li>Toggle Full Screen Mode.
</li></ul>
</li></ul>
<ul><li><b>Third Row.</b>
<ul><li>Insert New Table, Table Row Properties, Table Cell Properties, Insert Row Before, Insert Row After, Delete Row, Insert Column Before, Insert Column After, Delete Column, Split Merged Table Cells, Merge Table Cells.
</li><li>Insert Emotions.
</li><li>Insert Embedded Media. To insert embedded media (such as Flash), place the cursor at the desired location and press this button. A popup dialog will display that allows you to enter the Type, File or URL, and other information about the media.
</li><li>Insert horizontal line.
</li><li>Direction Left to Right and Direction Right to Left. These buttons allow you to enter or change the text direction, for example for languages that read right to left.
</li></ul>
</li></ul>
<ul><li><b>Fourth Row.</b>
<ul><li>Cut, Copy, Paste, Paste as Plain Text, Paste from Word. Often when copying and pasting text from other sources, such as PDF files, Word documents, or web pages, the selected text contains formatting information that is not needed or wanted. Using the Paste as Plain Text will strip out all formatting from the text. Paste as Word tries to preserve some of the formatting while stripping out unnecessary formatting.
</li><li>Select All. 
</li><li>Insert New Layer, Move Forward, Move Backware, Toggle Absolute Position. For working with layered items.
</li><li>Edit CSS Style. A popup dialog box displays that allows you to enter CSS style information for the selected text.
</li><li>Citation, Abbreviation, Acronym, Insertion, Deletion, Insert/Edit Attributes.
</li><li>Show/Hide Visual Control Characters (like paragraph endings). 
</li><li>Show/Hide Block Elements.
</li><li>Insert Non-Breaking Space Character.
</li><li>Block Quote.
</li><li>Insert Predefined Template Content.
</li></ul>
</li></ul>
<h4> <span class="mw-headline" id="Code_Mirror_Editor">Code Mirror Editor</span></h4>
The CodeMirror editor is designed to make it easy to enter HTML code in an article or description. CodeMirror supports syntax highlighting and auto-completion, as shown in this screenshot.<div class="thumb tnone"><div class="thumbinner" style="width:313px;"><a href="/proxy/index.php?option=com_help&view=help&keyref=File:Help25-screenshot-editor-codemirror-example.png" class="image"><img alt="Help25-screenshot-editor-codemirror-example.png" src="http://docs.joomla.org/images/8/80/Help25-screenshot-editor-codemirror-example.png" width="311" height="138" class="thumbimage" /></a>  <div class="thumbcaption"></div></div></div> CodeMirror offers some of the same advantages of using No Editor, but makes it somewhat easier to work with raw HTML code.
<h4> <span class="mw-headline" id="No_Editor">No Editor</span></h4>
<p>If 'No editor' is selected for a User, then a simple text editor displays. This allows you to enter in raw, unformatted HTML. You can use the toolbar 'Preview' button to preview how the HTML will display.
</p><p>Note that the 'No Editor' option can be useful if you are entering in 'boilerplate' or custom HTML, for example to create a PayPal link. TinyMCE automatically re-formats and strips some HTML when a file is saved. This can cause complex HTML to not work correctly.
</p><p>If this happens, you can temporarily change the editor to 'No Editor' and create the desired content. Note that if you wish to edit this content in the future, you should be careful to change your editor to 'No Editor'. Otherwise, if you open and save the content with TinyMCE, you may lose your custom HTML.
</p>
<h4> <span class="mw-headline" id="Editor_Buttons">Editor Buttons</span></h4>
<p>Five buttons are located just below the edit window, as shown below:
</p>
<div class="thumb tnone"><div class="thumbinner" style="width:419px;"><a href="/proxy/index.php?option=com_help&view=help&keyref=File:Help25-screenshot-editor-buttons.png" class="image"><img alt="Help25-screenshot-editor-buttons.png" src="http://docs.joomla.org/images/2/2c/Help25-screenshot-editor-buttons.png" width="417" height="41" class="thumbimage" /></a>  <div class="thumbcaption"></div></div></div>
<p><b>Article.</b> This button opens a modal window that allows you to easily create a link to any article on the current site. The link is created using the article's title as the link text. The modal window is the same as for selecting an article for a Single Article Menu Item. To create a link to the desired article:
</p>
<ul><li> Place the cursor at the point in the article where you want the linked article title to be inserted.
</li><li> Click on the Article button to open the modal window.
</li><li> Click on the title to select the desired article in the modal window. You can use the filters and search to help find the desired article.
</li><li> A link with the article's title will be inserted at the current cursor location.
</li><li> If needed, you can edit the link text.
</li></ul>
<b>Image.</b> This button provides an easy way to insert an image into an Article. Images may be inserted from the 'images' folder and may also be uploaded. When you click the Image button, a window pops up, as shown below:<div class="thumb tnone"><div class="thumbinner" style="width:809px;"><a href="/proxy/index.php?option=com_help&view=help&keyref=File:Help25-screenshot-editor-image-button.png" class="image"><img alt="Help25-screenshot-editor-image-button.png" src="http://docs.joomla.org/images/0/0e/Help25-screenshot-editor-image-button.png" width="807" height="478" class="thumbimage" /></a>  <div class="thumbcaption"></div></div></div>
<ul><li><b>Directory.</b> The current directory on the host server. This is the 'images' directory under your Joomla! home directory. Use the drop-down list box to select a subdirectory.
</li><li><b>Up.</b> Navigate to the parent directory. Note that the top directory for this function is 'images/stories'. You can not navigate to a higher directory.
</li><li><b>Insert.</b> Insert the selected image. The insert point will be the current cursor position. You will see the image display inside the edit window.
</li><li><b>Cancel</b>. Cancel the operation and close the popup window. You can cancel also in clicking the X at right top corner.
</li><li><b>Thumbnail Browse Area.</b> Click on an image thumbnail to select the image. Click on a folder icon to navigate to that subdirectory.
</li><li><b>Image URL.</b> Click on one of the image thumbnails and the URL for the image will be entered for you.
</li><li><b>Align.</b> Select the desired alignment (left or right) from the drop-down list box. 
</li><li><b>Image Description.</b> Enter a description for the image.
</li><li><b>Image Title.</b> Enter a Title for this image. This displays when a User hovers the mouse on the image.
</li><li><b>Caption.</b> If checked, image title will display as a caption below the image.
</li><li><b>Choose Files.</b> Click this button to browse to an image file to upload from your local computer. A file dialog will open allowing you to select a file.
</li><li><b>Start Upload.</b> Once you have selected a file, press this button to upload the file to your Joomla! 'images' folder. The thumbnail for the new image will now show in the thumbnail area.
</li></ul>
<b>Pagebreak.</b> This button allows you to insert a pagebreak inside an Article. A pagebreak allows for page navigation when the article is displayed on a layout. This is useful for long articles. When this button is pressed, a popup window is displayed as shown below:<div class="thumb tnone"><div class="thumbinner" style="width:436px;"><a href="/proxy/index.php?option=com_help&view=help&keyref=File:Help25-screenshot-editor-pagebreak-button.png" class="image"><img alt="Help25-screenshot-editor-pagebreak-button.png" src="http://docs.joomla.org/images/d/d0/Help25-screenshot-editor-pagebreak-button.png" width="434" height="136" class="thumbimage" /></a>  <div class="thumbcaption"></div></div></div>
<ul><li> <b>Page Title</b>. Enter the title to display for the new page (for example, 'Page 2').
</li><li> <b>Table of Contents Alias</b>. Optional field to display in the table of contents for this page. In a multi-page article, Joomla! displays a 'table of contents' for the page that allows the user to select any page. If this field is blank, the Page Title will be used. If you want a different title in the table of contents, enter it here.
</li><li> <b>Insert Page Break.</b> Click this button to insert the pagebreak with the entered fields. The Pagebreak will display as a gray dashed line across the Article. Note that a pagebreak cannot be edited. If you need to change a field in the pagebreak, click on the Article just past the pagebreak, press Backspace until the pagebreak is deleted, then insert a new pagebreak with the desired information.
</li><li><b>Read more...</b> This button inserts a 'Read more...' break in the Article. This shows as a red dotted line across the Article. If an Article has a 'Read more...' break, only the text before the break, called the Into Text, will initially display, along with a 'Read more...' link. If the User clicks this link, either the entire Article or just the part after the 'Read more...' link is displayed. This depends on the setting of the 'Intro Text' parameters for the Article and in the Global Configuration. The 'Read more...' break allows you to save space on pages by just showing the Intro Text. Note that the 'Read more...' break only shows in the Front Page, Section, and Category Blog layouts. If you want to insert breaks for an Article shown in an Article Layout, use the Page Break button.
</li></ul>
<p><b>Toggle Editor.</b> If you are using the TinyMCE editor, a Toggle Editor button will show. This button allows you to toggle between the TinyMCE editor and No Editor.
</p>
<h4> <span class="mw-headline" id="Editor_Buttons_2">Editor Buttons</span></h4>
<p>Five buttons are located just below the edit window, as shown below:
</p>
<div class="thumb tnone"><div class="thumbinner" style="width:419px;"><a href="/proxy/index.php?option=com_help&view=help&keyref=File:Help25-screenshot-editor-buttons.png" class="image"><img alt="Help25-screenshot-editor-buttons.png" src="http://docs.joomla.org/images/2/2c/Help25-screenshot-editor-buttons.png" width="417" height="41" class="thumbimage" /></a>  <div class="thumbcaption"></div></div></div>
<p><b>Article.</b> This button opens a modal window that allows you to easily create a link to any article on the current site. The link is created using the article's title as the link text. The modal window is the same as for selecting an article for a Single Article Menu Item. To create a link to the desired article:
</p>
<ul><li> Place the cursor at the point in the article where you want the linked article title to be inserted.
</li><li> Click on the Article button to open the modal window.
</li><li> Click on the title to select the desired article in the modal window. You can use the filters and search to help find the desired article.
</li><li> A link with the article's title will be inserted at the current cursor location.
</li><li> If needed, you can edit the link text.
</li></ul>
<b>Image.</b> This button provides an easy way to insert an image into an Article. Images may be inserted from the 'images' folder and may also be uploaded. When you click the Image button, a window pops up, as shown below:<div class="thumb tnone"><div class="thumbinner" style="width:809px;"><a href="/proxy/index.php?option=com_help&view=help&keyref=File:Help25-screenshot-editor-image-button.png" class="image"><img alt="Help25-screenshot-editor-image-button.png" src="http://docs.joomla.org/images/0/0e/Help25-screenshot-editor-image-button.png" width="807" height="478" class="thumbimage" /></a>  <div class="thumbcaption"></div></div></div>
<ul><li><b>Directory.</b> The current directory on the host server. This is the 'images' directory under your Joomla! home directory. Use the drop-down list box to select a subdirectory.
</li><li><b>Up.</b> Navigate to the parent directory. Note that the top directory for this function is 'images/stories'. You can not navigate to a higher directory.
</li><li><b>Insert.</b> Insert the selected image. The insert point will be the current cursor position. You will see the image display inside the edit window.
</li><li><b>Cancel</b>. Cancel the operation and close the popup window. You can cancel also in clicking the X at right top corner.
</li><li><b>Thumbnail Browse Area.</b> Click on an image thumbnail to select the image. Click on a folder icon to navigate to that subdirectory.
</li><li><b>Image URL.</b> Click on one of the image thumbnails and the URL for the image will be entered for you.
</li><li><b>Align.</b> Select the desired alignment (left or right) from the drop-down list box. 
</li><li><b>Image Description.</b> Enter a description for the image.
</li><li><b>Image Title.</b> Enter a Title for this image. This displays when a User hovers the mouse on the image.
</li><li><b>Caption.</b> If checked, image title will display as a caption below the image.
</li><li><b>Choose Files.</b> Click this button to browse to an image file to upload from your local computer. A file dialog will open allowing you to select a file.
</li><li><b>Start Upload.</b> Once you have selected a file, press this button to upload the file to your Joomla! 'images' folder. The thumbnail for the new image will now show in the thumbnail area.
</li></ul>
<b>Pagebreak.</b> This button allows you to insert a pagebreak inside an Article. A pagebreak allows for page navigation when the article is displayed on a layout. This is useful for long articles. When this button is pressed, a popup window is displayed as shown below:<div class="thumb tnone"><div class="thumbinner" style="width:436px;"><a href="/proxy/index.php?option=com_help&view=help&keyref=File:Help25-screenshot-editor-pagebreak-button.png" class="image"><img alt="Help25-screenshot-editor-pagebreak-button.png" src="http://docs.joomla.org/images/d/d0/Help25-screenshot-editor-pagebreak-button.png" width="434" height="136" class="thumbimage" /></a>  <div class="thumbcaption"></div></div></div>
<ul><li> <b>Page Title</b>. Enter the title to display for the new page (for example, 'Page 2').
</li><li> <b>Table of Contents Alias</b>. Optional field to display in the table of contents for this page. In a multi-page article, Joomla! displays a 'table of contents' for the page that allows the user to select any page. If this field is blank, the Page Title will be used. If you want a different title in the table of contents, enter it here.
</li><li> <b>Insert Page Break.</b> Click this button to insert the pagebreak with the entered fields. The Pagebreak will display as a gray dashed line across the Article. Note that a pagebreak cannot be edited. If you need to change a field in the pagebreak, click on the Article just past the pagebreak, press Backspace until the pagebreak is deleted, then insert a new pagebreak with the desired information.
</li><li><b>Read more...</b> This button inserts a 'Read more...' break in the Article. This shows as a red dotted line across the Article. If an Article has a 'Read more...' break, only the text before the break, called the Into Text, will initially display, along with a 'Read more...' link. If the User clicks this link, either the entire Article or just the part after the 'Read more...' link is displayed. This depends on the setting of the 'Intro Text' parameters for the Article and in the Global Configuration. The 'Read more...' break allows you to save space on pages by just showing the Intro Text. Note that the 'Read more...' break only shows in the Front Page, Section, and Category Blog layouts. If you want to insert breaks for an Article shown in an Article Layout, use the Page Break button.
</li></ul>
<p><b>Toggle Editor.</b> If you are using the TinyMCE editor, a Toggle Editor button will show. This button allows you to toggle between the TinyMCE editor and No Editor.
</p>
<h3> <span class="mw-headline" id="Publishing_Options">Publishing Options</span></h3>
<p><b>Note: This slider can be hidden by users with Admin Permission for the article manager.</b>
</p>
This section allows you to enter parameters for this Article, as shown below: <div class="thumb tnone"><div class="thumbinner" style="width:523px;"><a href="/proxy/index.php?option=com_help&view=help&keyref=File:Help25-screenshot-article-edit-publishing-options.png" class="image"><img alt="Help25-screenshot-article-edit-publishing-options.png" src="http://docs.joomla.org/images/c/ca/Help25-screenshot-article-edit-publishing-options.png" width="521" height="307" class="thumbimage" /></a>  <div class="thumbcaption"></div></div></div> These entries are optional. Joomla! automatically creates default entries for these values.
<ul><li> <b>Created by</b>.  Name of the Joomla! User who created this item. This will default to the currently logged-in user. If you want to change this to a different user, click the Select User button to select a different user.
</li></ul>
<ul><li><b>Created By Alias.</b> This optional field allows you to enter in an alias for this Author for this Article. This allows you to display a different Author name for this Article.
</li></ul>
<ul><li><b>Created Date.</b> This field defaults to the current time when the Article was created. You can enter in a different date and time or click on the calendar icon to find the desired date.
</li></ul>
<ul><li><b>Start Publishing.</b> Date and time to start publishing. Use this field if you want to enter content ahead of time and then have it published automatically at a future time.
</li></ul>
<ul><li><b>Finish Publishing.</b> Date and time to finish publishing. Use this field if you want to have content automatically changed to Unpublished state at a future time (for example, when it is no longer applicable).
</li></ul>
<ul><li><b>Modified By.</b> Displays who last edited the article. Note this field is non-editable.
</li></ul>
<ul><li><b>Modified Date.</b> Date and time the article was last modified on. Note this field is non-editable.
</li></ul>
<ul><li><b>Revision.</b> How many times the article has been edited. Note this field is non-editable.
</li></ul>
<ul><li><b>Hits.</b> The number of times an item has been viewed.
</li></ul>
<h3> <span class="mw-headline" id="Basic_Options">Basic Options</span></h3>
<p><a href="/proxy/index.php?option=com_help&view=help&keyref=File:Help25-content-edit-category-basic-options.png" class="image"><img alt="Help25-content-edit-category-basic-options.png" src="http://docs.joomla.org/images/f/fb/Help25-content-edit-category-basic-options.png" width="520" height="141" /></a>
</p>
<ul><li><b>Alternative Layout.</b> If you have defined one or more alternative layouts for the Single Article menu item, you can select the layout to use for this article. See <a href="/proxy/index.php?option=com_help&view=help&keyref=Layout_Overrides_in_Joomla_2.5" title="Layout Overrides in Joomla 2.5" class="mw-redirect">Layout Overrides in Joomla 2.5</a> for more information about alternative layouts.
</li></ul>
<ul><li><b>Image.</b> Click the Select button to choose an image that will be displayed with the category. This will open a modal window that allows you to select an image from your images folder. See <a href="#Editor_Buttons">Editor Buttons</a> for more information on working with images. After you have selected an image, you can hover the mouse on the "Preview" text to see a preview of the image.
</li></ul>
<ul><li><b>Note</b>. Item note. This is normally for the site administrator's use (for example, to document information about this item) and does not show in the front end of the site.
</li></ul>
<h3> <span class="mw-headline" id="Metadata_Options">Metadata Options</span></h3>
This section allows you to enter Metadata Information for this Article. Metadata is information about the Article that is not displayed but is available to Search Engines and other systems to classify the Article. This gives you more control over how the content will be analyzed by these programs. All of these entries are optional. Metadata is shown inside HTML meta elements. The entry screen is shown below:<div class="thumb tnone"><div class="thumbinner" style="width:524px;"><a href="/proxy/index.php?option=com_help&view=help&keyref=File:Help25-screenshot-article-category-edit-metadata-options.png" class="image"><img alt="Help25-screenshot-article-category-edit-metadata-options.png" src="http://docs.joomla.org/images/0/0a/Help25-screenshot-article-category-edit-metadata-options.png" width="522" height="232" class="thumbimage" /></a>  <div class="thumbcaption"></div></div></div>
<ul><li><b>Meta Description.</b> An optional paragraph to be used as the description of the page in the HTML output. This will generally display in the results of search engines. If entered, this creates an HTML meta element with a name attribute of "description" and a content attribute equal to the entered text.
</li></ul>
<ul><li><b>Meta Keywords.</b> Optional entry for keywords. Must be entered separated by commas (for example, "cats, dogs, pets") and may be entered in upper or lower case. (For example, "CATS" will match "cats" or "Cats"). Keywords can be used in several ways:
</li></ul>
<ol><li> To help Search Engines and other systems classify the content of the Article. 
</li><li> In combination with Banner tags, to display specific Banners based on the Article content. For example, say you have one Banner with an ad for dog products and another Banner for cat products. You can have your dog Banner display when a User is viewing a dog-related Article and your cat Banner display for a cat-related Article. To do this, you would:
<ol><li> Add the keywords 'dog' and 'cat' to the appropriate Articles.
</li><li> Add the Tags 'dog' and 'cat' to the appropriate Banners in the <a href="/proxy/index.php?option=com_help&view=help&keyref=Help25:Components_Banners_Banners_Edit" title="Help25:Components Banners Banners Edit"> Banner Manager New/Edit</a> screen.
</li><li> Set the Banner module Parameter 'Search By Tags' to 'Yes in the <a href="/proxy/index.php?option=com_help&view=help&keyref=Help25:Extensions_Module_Manager_Banners" title="Help25:Extensions Module Manager Banners"> Banner Module Edit</a> screen.
</li></ol>
</li><li> For articles only, in combination with the <a href="/proxy/index.php?option=com_help&view=help&keyref=Help25:Extensions_Module_Manager_Articles_Related" title="Help25:Extensions Module Manager Articles Related"> Related Articles module</a>, to display Articles that share at least one keyword in common. For example, if the current Article displayed has the keywords "cats, dogs, monkeys", any other Articles with at least one of these keywords will show in the Related Articles module.
</li></ol>
<ul><li><b>Author.</b> Optional entry for an Author name within the metadata. If entered, this creates an HTML meta element with the name attribute of "author" and the content attribute as entered here.
</li></ul>
<ul><li><b>Robots.</b> The instructions for web "robots" that browse to this page.
<ul><li><i>Use Global:</i> Use the value set in the Component&#8594;Options for this component.
</li><li><i>Index, Follow:</i> Index this page and follow the links on this page.
</li><li><i>No index, Follow:</i> Do not index this page, but still follow the links on the page. For example, you might do this for a site map page where you want the links to be indexed but you don't want this page to show in search engines.
</li><li><i>Index, No follow:</i> Index this page, but do not follow any links on the page. For example, you might want to do this for an events calendar, where you want the page to show in search engines but you do not want to index each event.
</li><li><i>No index, no follow:</i> Do not index this page or follow any links on the page.
</li></ul>
</li></ul>
<h2> <span class="mw-headline" id="Toolbar">Toolbar</span></h2>
<p>At the top right you will see the toolbar:
</p><p><a href="/proxy/index.php?option=com_help&view=help&keyref=File:Help25-Toolbar-Save-SaveClose-SaveNew-Cancel-Help.png" class="image"><img alt="Help25-Toolbar-Save-SaveClose-SaveNew-Cancel-Help.png" src="http://docs.joomla.org/images/0/05/Help25-Toolbar-Save-SaveClose-SaveNew-Cancel-Help.png" width="325" height="65" /></a>
</p><p>The functions are:
</p>
<ul><li><b>Save</b>. Saves the content category and stays in the current screen.
</li><li><b>Save &amp; Close</b>. Saves the content category and closes the current screen.
</li><li><b>Save &amp; New</b>. Saves the content category and keeps the editing screen open and ready to create another content category.
</li><li><b>Cancel/Close</b>. Closes the current screen and returns to the previous screen without saving any modifications you may have made.
</li><li><b>Help</b>. Opens this help screen.
</li></ul>
<h2> <span class="mw-headline" id="Related_Information">Related Information</span></h2>
<ul><li>To work with existing Categories: <a href="/proxy/index.php?option=com_help&view=help&keyref=Help25:Components_Content_Categories" title="Help25:Components Content Categories">Category Manager</a>
</li><li>To work with Articles: <a href="/proxy/index.php?option=com_help&view=help&keyref=Help25:Content_Article_Manager" title="Help25:Content Article Manager">Article Manager</a>
</li><li>To create a page showing Articles for a Category in a Blog layout: <a href="/proxy/index.php?option=com_help&view=help&keyref=Screen.menus.edit.15#Category_Blog_Layout" title="Screen.menus.edit.15" class="mw-redirect">Menu Item Manager - New/Edit - Category Blog Layout</a>
</li><li>To create a page showing Articles for a Category in a List layout: <a href="/proxy/index.php?option=com_help&view=help&keyref=Screen.menus.edit.15#Category_List_Layout" title="Screen.menus.edit.15" class="mw-redirect">Menu Item Manager - New/Edit - Category List Layout</a>
</li></ul>
</article>