<?php
/**
 * HUBzero CMS
 *
 * Copyright 2005-2011 Purdue University. All rights reserved.
 *
 * This file is part of: The HUBzero(R) Platform for Scientific Collaboration
 *
 * The HUBzero(R) Platform for Scientific Collaboration (HUBzero) is free
 * software: you can redistribute it and/or modify it under the terms of
 * the GNU Lesser General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any
 * later version.
 *
 * HUBzero is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * HUBzero is a registered trademark of Purdue University.
 *
 * @package   hubzero-cms
 * @author    Christopher Smoak <csmoak@purdue.edu>
 * @copyright Copyright 2005-2011 Purdue University. All rights reserved.
 * @license   http://www.gnu.org/licenses/lgpl-3.0.html LGPLv3
 */

// Check to ensure this file is included in Joomla!
defined('_JEXEC') or die('Restricted access');
?>
<h1>Forum Sections</h1>

<p>Sections are a way to organize or group related categories (topics).</p>

<hr />

<h2>Creating a Section</h2>
<p>You can <a target="_blank" href="<?php echo JRoute::_('index.php?option=com_forum&task=new'); ?>">create your own group</a> as a registered user. Just fill in a simple form choosing a group name, a title, and a brief description, so that others will know what your group is about. Once created, your group title and description will be available for all to see in the <a target="_blank" href="<?php echo JRoute::_('index.php?option=com_groups&task=browse'); ?>">list of all groups.</a> Each group also has its own page, which contains a link that other users can click on to request membership.</p>

<hr />

<h2>Organizing Sections</h2>
<p>By default, sections are sequenced by their creation time (oldest to newest), but may be reordered manually.</p>