<article>
	<h1><span>Groups Manager</span></h1>

	<ul class="nav">
		<li><a href="#overview">Overview</a></li>
		<li><a href="#column-headers">Column Headers</a></li>
		<li><a href="#toolbar">Toolbar</a></li>
		<li><a href="#list-filters">List Filters</a></li>
	</ul>

	<section id="overview">
		<h2><span>Overview</span></h2>

		<p>Here you will a list of groups.</p>
	</section>
	<section id="column-headers">
		<h2><span>Column Headers</span></h2>

		<p>Click on the column heading to sort the list by that column's value. The list will be sorted in order by that column and a sort icon will show next to the column name. Click a second time to reverse the sort to high-to-low. The sort icon will change to high-to-low.</p>

		<dl>
			<dt>Checkbox</dt>
			<dd>Check this box to select one or more items. To select all items, check the box in the column heading. After one or more boxes are checked, click a toolbar button to take an action on the selected item or items. Many toolbar actions, such as Publish and Unpublish, can work with multiple items. Others, such as Edit, only work on one item at a time. If multiple items are checked and you press Edit, the first item will be opened for editing.</dd>

			<dt>ID</dt>
			<dd>This is a unique identification number for this item assigned automatically by the system. It is used to identify the item internally and cannot be changed. When creating a new item, this field is 0 until the entry is saved, at which point a new ID is assigned to it.</dd>

			<dt>Name</dt>
			<dd>The name of the item. This entry is required. You can open the item for editing by clicking on the Name.</dd>

			<dt>Type</dt>
			<dd>(System/Hub/Project/Super/Course) The type of the group. Type can affect when/how the group is displayed and functions.</dd>

			<dt>Published</dt>
			<dd>(Public/Private/Registered/Trashed) The published status of the item.</dd>

			<dt>Approved</dt>
			<dd>Groups must be approved before they appear in the site listing, searches, etc.</dd>

			<dt>Members</dt>
			<dd>How many members can be found within that group. Clicking the number will present a list of members and controls for managing them.</dd>

			<dt>Pages</dt>
			<dd>Clicking this will present a list of pages and controls for managing them.</dd>
		</dl>
	</section>
	<section id="toolbar">
		<h2><span>Toolbar</span></h2>
		<p>At the top right you will see the toolbar.</p>
		<p>The functions are:</p>
		<dl>
			<dt>Options</dt>
			<dd>Opens the Options window where settings such as default parameters or permissions can be edited.</dd>

			<dt>New</dt>
			<dd>Opens the editing screen to create a new group.</dd>

			<dt>Edit</dt>
			<dd>Opens the editing screen for the selected group. If more than one group is selected (where applicable), only the first group will be opened. The editing screen can also be opened by clicking on the Name of the group.</dd>

			<dt>Trash</dt>
			<dd>Permanently removes the selected entries and any associated content.</dd>

			<dt>Help</dt>
			<dd>Opens this help screen.</dd>
		</dl>
	</section>
	<section id="list-filters">
		<h2><span>List Filters</span></h2>
		<p>Above the column headers is a row of filters to help in finding a specific group or list of groups.</p>

		<dl>
			<dt>Filter by Type</dt>
			<dd>
				<p>You can filter the list of items by the type of the group.</p>
			</dd>

			<dt>Filter by Discoverability</dt>
			<dd>
				<p>Discoverability controls how users can find or discover the group on the site.</p>
				<ul>
					<li><i>Visible:</i> The group displays in the groups browse listing and search results.</li>
					<li><i>Hidden:</i> The group does <strong>not</strong> display in the groups browse listing or search results.</li>
				</ul>
			</dd>

			<dt>Filter by Policy Type</dt>
			<dd>
				<p>Allows for only showing items with the specified member join policy.</p>
				<ul>
					<li><i>Open:</i> Anyone can join the group.</li>
					<li><i>Restricted:</i> Users must apply for membership in the group.</li>
					<li><i>Invite only:</i> Only users that have received an invitation may join the group.</li>
					<li><i>Closed:</i> No further membership requests or additions will be allowed.</li>
				</ul>
			</dd>

			<dt>Page Controls</dt>
			<dd>
				<p>When the number of items is more than one page, you will see a page control bar as shown below.</p>

				<dl>
					<dt>Display #</dt>
					<dd>Select the number of items to show on one page.</dd>
					<dt>Start</dt>
					<dd>Click to go to the first page.</dd>
					<dt>Prev</dt>
					<dd>Click to go to the previous page.</dd>
					<dt>Page numbers</dt>
					<dd>Click to go to the desired page.</dd>
					<dt>Next</dt>
					<dd>Click to go to the next page.</dd>
					<dt>End</dt>
					<dd>Click to go to the last page.</dd>
				</dl>
			</dd>
		</dl>
	</section>
</article>