<article>
	<h1>Poll Manager</h1>

	<ul class="nav">
		<li><a href="#overview">Overview</a></li>
		<li><a href="#column-headers">Column Headers</a></li>
		<li><a href="#toolbar">Toolbar</a></li>
		<li><a href="#list-filters">List Filters</a></li>
	</ul>

	<p>Select <b>Components &#8594; Poll</b> from the drop-down menu on the back-end of your installation.</p>

	<section id="description">
		<h2><span>Description</span></h2>
		<p>The Poll Manager is where you can edit existing Polls and create new ones.</p>
	</section>
	<section id="column-headers">
		<h2><span>Column Headers</span></h2>
		<p>Click on the column heading to sort the list by that column's value.</p>
		<dl>
			<dt>#</dt>
			<dd>This entry number for the current listing.</dd>

			<dt>Checkbox</dt>
			<dd>Check this box to select one or more items. To select all items, check the box in the column heading. After one or more boxes are checked, click a toolbar button to take an action on the selected item or items. Many toolbar actions, such as Publish and Unpublish, can work with multiple items. Others, such as Edit, only work on one item at a time. If multiple items are checked and you press Edit, the first item will be opened for editing.</dd>

			<dt>Title</dt>
			<dd>The name of the item. This entry is required. You can open the item for editing by clicking on the Title.</dd>

			<dt>Published</dt>
			<dd>(Published/Unpublished) The published status of the item.</dd>

			<dt>Open</dt>
			<dd>(Open/Closed) This indicates if a poll is still accepting votes or not.</dd>

			<dt>Votes</dt>
			<dd>The number of votes recorded for the poll.</dd>

			<dt>Options</dt>
			<dd>The number of options associated with a poll.</dd>

			<dt>Lag</dt>
			<dd>The delay time between consecutive votes. This is how long a user must wait before they can vote again.</dd>

			<dt>ID</dt>
			<dd>This is a unique identification number for this item assigned automatically. It is used to identify the item internally, and you cannot change this number. When creating a new item, this field displays 0 until you save the new entry, at which point a new ID is assigned to it.</dd>
		</dl>
	</section>
	<section id="toolbar">
		<h2><span>Toolbar</span></h2>
		<p>At the top right you will see the toolbar. The functions are:</p>
		<dl>
			<dt>Publish</dt>
			<dd>Makes the selected entries available to visitors to your website.</dd>

			<dt>Unpublish</dt>
			<dd>Makes the selected entries unavailable to visitors to your website.</dd>

			<dt>Trash</dt>
			<dd>Permanently deletes the selected entries.</dd>

			<dt>New</dt>
			<dd>Opens the editing screen to create a new entry.</dd>

			<dt>Edit</dt>
			<dd>Opens the editing screen for the selected entry. If more than one entry is selected (where applicable), only the first entry will be opened. The editing screen can also be opened by clicking on the Title of the entry.</dd>

			<dt>Help</dt>
			<dd>Opens this help screen.</dd>
		</dl>
	</section>
	<section id="list-filters">
		<h2><span>List Filters</span></h2>

		<dl>
			<dt>Filter by Search</dt>
			<dd>
				<p>Lets you search event titles.</p>
			</dd>

			<dt>Filter by State</dt>
			<dd>
				<p>Lets you show only items with the selected published status.</p>
				<ul>
					<li><i>- Select Status -:</i> Shows items that are Published and Unpublished.</li>
					<li><i>Published:</i> Shows only items that are Published.</li>
					<li><i>Unpublished:</i> Shows only items that are Unpublished.</li>
				</ul>
			</dd>
		</dl>

		<h3>Page Controls</h3>
		<p>When the number of items is more than one page, you will see a page control bar as shown below.</p>

		<dl>
			<dt>Display #</dt>
			<dd>Select the number of items to show on one page.</dd>
			<dt>Start</dt>
			<dd>Click to go to the first page.</dd>
			<dt>Prev</dt>
			<dd>Click to go to the previous page.</dd>
			<dt>Page numbers</dt>
			<dd>Click to go to the desired page.</dd>
			<dt>Next</dt>
			<dd>Click to go to the next page.</dd>
			<dt>End</dt>
			<dd>Click to go to the last page.</dd>
		</dl>
	</section>
</article>