<article>
	<h1>Global Check-In</h1>

	<p>A component which allows Administrators to "check-in" or unlock items currently "locked" whether they are in-use by other users or the item wasn't closed properly.</p>

	<section>
		<h2> <span class="mw-headline" id="How_to_access">How to access</span></h2>
		<p>To access this screen:</p>
		<ul>
			<li> Select <b>Site &#8594; Maintenance &#8594; Global Check-in</b> from the drop-down menus.</li>
		</ul>
	</section>
	<section>
		<h2> <span class="mw-headline" id="Description">Description</span></h2>
		<p>Selecting this menu option allows Joomla! administrators to perform a global check-in of all currently pending or locked items. It then shows the results of the Global Check-in. This is useful, for example, if an Article is locked by a User who opened it for editing and never finished the editing session. In this case, other Users are not able to edit this Article. Performing a Global Check-in releases all such items.</p>
	</section>
	<section>
		<h2> <span class="mw-headline" id="Toolbar">Toolbar</span></h2>
		<p>At the top right you will see the toolbar:</p>
		<p>The functions are:</p>
		<ul>
			<li><b>Check In</b>. Checks-in the selected items. Works with one or multiple items selected.</li>
			<li><b>Options</b>. Opens the Options window where settings such as default parameters or permissions can be edited.</li>
			<li><b>Help</b>. Opens this help screen.</li>
		</ul>
	</section>
	<section>
		<h2> <span class="mw-headline" id="Column_Headers">Column Headers</span></h2>
		<ul><li><b>Checkbox</b>. Check this box to select one or more items. To select all items, check the box in the column heading. After one or more boxes are checked, click a toolbar button to take an action on the selected item or items. Many toolbar actions, such as Publish and Unpublish, can work with multiple items. Others, such as Edit, only work on one item at a time. If multiple items are checked and you press Edit, the first item will be opened for editing.
		</li><li> <b>Database Table</b>. The name of the table checked.
		</li><li> <b>Items to check-in</b>. Items that need to be checked-in.
		</li></ul>
	</section>
	<section>
		<h2> <span class="mw-headline" id="List_Filters">List Filters</span></h2>
		<ul>
			<li>
				<b>Page Controls.</b> When the number of items is more than one page, you will see a page control bar as shown below.
				<ul>
					<li><b>Display #:</b> Select the number of items to show on one page.</li>
					<li><b>Start:</b> Click to go to the first page.</li>
					<li><b>Prev:</b> Click to go to the previous page.</li>
					<li><b>Page numbers:</b> Click to go to the desired page.</li>
					<li><b>Next:</b> Click to go to the next page.</li>
					<li><b>End:</b> Click to go to the last page.</li>
				</ul>
			</li>
		</ul>
	</section>
	<section>
		<h2> <span class="mw-headline" id="Quick_Tips">Quick Tips</span></h2>
		<ul>
			<li>Make sure no one is busy editing any items before you perform a global check-in. When a Global Check-in is done, <i>all</i> items are checked in, including those currently being edited.</li>
		</ul>
	</section>
	<section>
	<h2> <span class="mw-headline" id="Related_Information">Related Information</span></h2>
	<ul><li>To see all logged in users: <a href="/proxy/index.php?option=com_help&view=help&keyref=Help25:Users_User_Manager" title="Help25:Users User Manager">User Manager</a>
	</li></ul>
	</section>
</article>