<article>
	<h1>Global Check-In</h1>

	<p>A component which allows Administrators to "check-in" or unlock items currently "locked" whether they are in-use by other users or the item wasn't closed properly.</p>

	<section id="description">
		<h2><span>Description</span></h2>
		<p>Selecting this menu option allows administrators to perform a global check-in of all currently pending or locked items. It then shows the results of the Global Check-in. This is useful, for example, if an Article is locked by a User who opened it for editing and never finished the editing session. In this case, other Users are not able to edit this Article. Performing a Global Check-in releases all such items.</p>
	</section>
	<section id="toolbar">
		<h2><span>Toolbar</span></h2>
		<p>At the top right you will see the toolbar. The functions are:</p>
		<dl>
			<dt>Check In</dt>
			<dd>Checks-in the selected items. Works with one or multiple items selected.</dd>
			<dd>Options</dt>
			<dd>Opens the Options window where settings such as default parameters or permissions can be edited.</dd>
			<dd>Help</dt>
			<dd>Opens this help screen.</dd>
		</dl>
	</section>
	<section id="column-headers">
		<h2><span>Column Headers</span></h2>
		<dl>
			<dt>Checkbox</dt>
			<dd>Check this box to select one or more items. To select all items, check the box in the column heading. After one or more boxes are checked, click a toolbar button to take an action on the selected item or items. Many toolbar actions, such as Publish and Unpublish, can work with multiple items. Others, such as Edit, only work on one item at a time. If multiple items are checked and you press Edit, the first item will be opened for editing.</dd>
			<dt>Database Table</dt>
			<dd>The name of the table checked.</dd>
			<dt>Items to check-in</dt>
			<dd>Items that need to be checked-in.</dd>
		</dl>
	</section>
	<section id="list-filters">
		<h2><span>List Filters</span></h2>
		<ul>
			<li>
				<b>Page Controls.</b> When the number of items is more than one page, you will see a page control bar as shown below.
				<dl>
					<dt>Display #:</dt>
					<dd>Select the number of items to show on one page.</dd>
					<dt>Start:</dt>
					<dd>Click to go to the first page.</dd>
					<dt>Prev:</dt>
					<dd>Click to go to the previous page.</dd>
					<dt>Page numbers:</dt>
					<dd>Click to go to the desired page.</dd>
					<dt>Next:</dt>
					<dd>Click to go to the next page.</dd>
					<dt>End:</dt>
					<dd>Click to go to the last page.</dd>
				</dl>
			</li>
		</ul>
	</section>
	<section id="quick-tips">
		<h2><span>Quick Tips</span></h2>
		<p>Make sure no one is busy editing any items before you perform a global check-in. When a Global Check-in is done, <i>all</i> items are checked in, including those currently being edited.</p>
	</section>
	<section id="related-info">
		<h2><span>Related Information</span></h2>
		<p>To see all logged in users: <a href="<?php echo Route::url('index.php?option=com_help&component=com_users&page=users'); ?>" title="Users User Manager">User Manager</a></p>
	</section>
</article>