		<article>
			<h1><span>Wish Lists: Edit Comment</span></h1>

			<ul class="nav">
				<li><a href="#overview">Overview</a></li>
				<li><a href="#toolbar">Toolbar</a></li>
				<li><a href="#details">Details</a></li>
				<li><a href="#parameters">Parameters</a></li>
			</ul>

			<section id="overview">
				<h2><span>Overview</span></h2>

				<p>A wish comment.</p>
			</section>
			<section id="toolbar">
				<h2><span>Toolbar</span></h2>
				<p>At the top right you will see the toolbar.</p>
				<p>The functions are:</p>
				<dl>
					<dt>Save</dt>
					<dd>Save changes and return to the edit form.</dd>

					<!-- <dt>Save &amp; Close</dt>
					<dd>Save changes and return to the listing of entries.</dd> -->

					<dt>Cancel</dt>
					<dd>Discard any changes made and return to the listing of entries.</dd>

					<dt>Help</dt>
					<dd>Opens this help screen.</dd>
				</dl>
			</section>
			<section id="details">
				<h2><span>Details</span></h2>

				<dl>
					<dt>Comment</dt>
					<dd>The primary content of the entry.</dd>
				</dl>
			</section>
			<section id="parameters">
				<h2><span>Parameters</span></h2>

				<p>The following options control various aspects of the published state (when and if an entry is available to users).</p>

				<dl>
					<dt>Status</dt>
					<dd>The published status of the entry.</dd>

					<dt>Anonymous</dt>
					<dd>Determines if post is marked as being made anonymously or not. Anonymous posts do <strong>not</strong> show the author's name or link to their profile.</dd>
				</dl>
			</section>
		</article>