		<article>
			<h1><span>Wish Lists: Edit List</span></h1>

			<ul class="nav">
				<li><a href="#overview">Overview</a></li>
				<li><a href="#toolbar">Toolbar</a></li>
				<li><a href="#details">Details</a></li>
				<li><a href="#parameters">Parameters</a></li>
			</ul>

			<section id="overview">
				<h2><span>Overview</span></h2>

				<p>A wish list.</p>
			</section>
			<section id="toolbar">
				<h2><span>Toolbar</span></h2>
				<p>At the top right you will see the toolbar.</p>
				<p>The functions are:</p>
				<dl>
					<dt>Save</dt>
					<dd>Save changes and return to the edit form.</dd>

					<!-- <dt>Save &amp; Close</dt>
					<dd>Save changes and return to the listing of entries.</dd> -->

					<dt>Cancel</dt>
					<dd>Discard any changes made and return to the listing of entries.</dd>

					<dt>Help</dt>
					<dd>Opens this help screen.</dd>
				</dl>
			</section>
			<section id="details">
				<h2><span>Details</span></h2>

				<p>Every entry consists of a <strong>title</strong>, <strong>category</strong>, and <strong>reference ID</strong>.</p>

				<dl>
					<dt>Category</dt>
					<dd>The category or "type" the list is. This value will typically correspond to another component that may have a wish list plugin.</dd>

					<dt>Reference ID</dt>
					<dd>The unique ID of the object the wish list is attached to. This is used in conjuntion with the <strong>category</strong> field. For example: A list with Category of "group" and Reference ID of "1234" will be associated to group #1234.</dd>

					<dt>Title</dt>
					<dd>The title of the post. A required field.</dd>

					<dt>Description</dt>
					<dd>A short description of the wish list.</dd>
				</dl>
			</section>
			<section id="parameters">
				<h2><span>Parameters</span></h2>

				<p>The following options control various aspects of the published state (when and if an entry is available to users).</p>

				<dl>
					<dt>State</dt>
					<dd>The published status of the entry.</dd>

					<dt>Public</dt>
					<dd>Controls access level. If checked, all users can access the wish list. If not checked, the list is private.</dd>
				</dl>
			</section>
		</article>