		<article>
			<h1><span>Wish Lists: Edit Wish</span></h1>

			<ul class="nav">
				<li><a href="#overview">Overview</a></li>
				<li><a href="#toolbar">Toolbar</a></li>
				<li><a href="#details">Details</a></li>
				<li><a href="#parameters">Parameters</a></li>
			</ul>

			<section id="overview">
				<h2><span>Overview</span></h2>

				<p>A wish list.</p>
			</section>
			<section id="toolbar">
				<h2><span>Toolbar</span></h2>
				<p>At the top right you will see the toolbar.</p>
				<p>The functions are:</p>
				<dl>
					<dt>Save</dt>
					<dd>Save changes and return to the edit form.</dd>

					<!-- <dt>Save &amp; Close</dt>
					<dd>Save changes and return to the listing of entries.</dd> -->

					<dt>Cancel</dt>
					<dd>Discard any changes made and return to the listing of entries.</dd>

					<dt>Help</dt>
					<dd>Opens this help screen.</dd>
				</dl>
			</section>
			<section id="details">
				<h2><span>Details</span></h2>

				<p>Every entry consists of a <strong>title</strong>, <strong>category</strong>, and <strong>description</strong>.</p>

				<dl>
					<dt>Category</dt>
					<dd>The list the wish belongs to.</dd>

					<dt>Title</dt>
					<dd>The title of the post. A required field.</dd>

					<dt>Description</dt>
					<dd>A short description of the wish list.</dd>
				</dl>
			</section>
			<section id="parameters">
				<h2><span>Parameters</span></h2>

				<p>The following options control various aspects of the published state (when and if an entry is available to users).</p>

				<dl>
					<dt>Status</dt>
					<dd>The published status of the entry.</dd>

					<dt>Private</dt>
					<dd>Controls access level. If not checked, all users can access the wish. If checked, the wish is private.</dd>

					<dt>Accepted</dt>
					<dd>If the wish has been accepted or not.</dd>

					<dt>Anonymous</dt>
					<dd>Determines if post is marked as being made anonymously or not. Anonymous posts do <strong>not</strong> show the author's name or link to their profile.</dd>

					<dt>Points</dt>
					<dd>The number of bonus points to be awarded upon completion (granting) of the wish. This requires the "economy" be enabled for the site.</dd>
				</dl>
			</section>
		</article>