<?php
/**
 * HUBzero CMS
 *
 * Copyright 2005-2011 Purdue University. All rights reserved.
 *
 * This file is part of: The HUBzero(R) Platform for Scientific Collaboration
 *
 * The HUBzero(R) Platform for Scientific Collaboration (HUBzero) is free
 * software: you can redistribute it and/or modify it under the terms of
 * the GNU Lesser General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any
 * later version.
 *
 * HUBzero is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * HUBzero is a registered trademark of Purdue University.
 *
 * @package   hubzero-cms
 * @author    Christopher Smoak <csmoak@purdue.edu>
 * @copyright Copyright 2005-2011 Purdue University. All rights reserved.
 * @license   http://www.gnu.org/licenses/lgpl-3.0.html LGPLv3
 */

// Check to ensure this file is included in Joomla!
defined('_JEXEC') or die('Restricted access');
?>

<h1>Group Page Categories</h1>
<p>Page categories are a simple easy to use way to group related pages together.</p>
<p class="info">Categories are NOT hierarchical.</p>

<hr />

<h3>Adding Page Categories</h3>
<ol>
	<li>Navigate to the page manager.</li>
	<li>Click on the "Manage Page Categories" tab.</li>
	<li>Here you will see any current page categories.</li>
	<li>Click the "New Page Category" button. Fill in the name field, color is optonal, then click "Save Category".</li>
</ol>
<figure>
	<img src="/components/com_groups/help/images/categories/manager.png">
	<figcaption>Group Category Manager</figcaption>
</figure>


<hr />

<h3>Editing Page Categories</h3>
<ol>
	<li>Navigate to the page manager.</li>
	<li>Click on the "Manage Page Categories" tab.</li>
	<li>Here you will see any current page categories.</li>
	<li>Click on the "Manage Page Category" button for the category you wish to edit.</li>
	<li>Change the name or color settings, then click the "Save Category" button to finish.</li>
</ol>
<figure>
	<img src="/components/com_groups/help/images/categories/edit.png">
	<figcaption>Edit Page Category</figcaption>
</figure>

<hr />

<h3>Assigning Page Categories</h3>
<p>Putting a page into a page category is done through the edit page interface.</p>