<article>
	<h1><span>Storefront: Products</span></h1>
	<ul class="nav">
		<li><a href="#overview">Overview</a></li>
		<li><a href="#column-headers">Column Headers</a></li>
		<li><a href="#toolbar">Toolbar</a></li>
		<li><a href="#sub-menu">Sub-menu Links</a></li>
		<li><a href="#list-filters">List Filters</a></li>
	</ul>
	<div class="section" id="overview">
		<h2><span>Overview</span></h2>

		<p>Here you will a list of store products.</p>
	</div>
	<div class="section" id="column-headers">
		<h2><span>Column Headers</span></h2>

		<p>Click on the column heading to sort the list by that column's value. The list will be sorted in order by that column and a sort icon will show next to the column name. Click a second time to reverse the sort to high-to-low. The sort icon will change to high-to-low.</p>

		<dl>
			<dt>Checkbox</dt>
			<dd>Check this box to select one or more items. To select all items, check the box in the column heading. After one or more boxes are checked, click a toolbar button to take an action on the selected item or items. Many toolbar actions, such as Publish and Unpublish, can work with multiple items. Others, such as Edit, only work on one item at a time. If multiple items are checked and you press Edit, the first item will be opened for editing.</dd>

			<dt>Title</dt>
			<dd>The name of the item. This entry is required. You can open the item for editing by clicking on the Title.</dd>

			<dt>Alias</dt>
			<dd>A normalized name (only alpha-numeric characters, dashes, underscores) used primarily for URLs.</dd>

			<dt>State</dt>
			<dd>(Published/Unpublished/Trashed) The published status of the item.</dd>
		</dl>
	</div>
	<div class="section" id="toolbar">
		<h2><span>Toolbar</span></h2>
		<p>At the top right you will see the toolbar.</p>
		<p>The functions are:</p>
		<dl>
			<dt>Options</dt>
			<dd>Opens the Options window where settings such as default parameters or permissions can be edited.</dd>

			<dt>Run</dt>
			<dd>Force a job to run, disregarding "next run" and recurrence settings.</dd>

			<dt>Publish</dt>
			<dd>Makes the selected entries available to be purchased.</dd>

			<dt>Unpublish</dt>
			<dd>Makes the selected entries unavailable to be purchased.</dd>

			<dt>New</dt>
			<dd>Opens the editing screen to create a new entry.</dd>

			<dt>Edit</dt>
			<dd>Opens the editing screen to edit an entry. An entry's checkbox must be checked.</dd>

			<dt>Delete</dt>
			<dd>Permanently remove the selected entries from the system.</dd>

			<dt>Help</dt>
			<dd>Opens this help screen.</dd>
		</dl>
	</div>
	<div class="section" id="sub-menu">
		<h2><span>Sub-menu Links</span></h2>
		<p>At the top left, above the filters, you will see sub-menu options. The links are:</p>
		<dl>
			<dt>Products</dt>
			<dd>Show the list of products.</dd>
			<dt>Collections</dt>
			<dd>Show the list of product collections.</dd>
			<dt>Option Groups</dt>
			<dd>Show the list of product option groups.</dd>
		</dl>
	</div>
	<div class="section" id="list-filters">
		<h2><span>List Filters</span></h2>

		<h3>Page Controls</h3>
		<p>When the number of items is more than one page, you will see a page control bar as shown below.</p>

		<dl>
			<dt>Display #</dt>
			<dd>Select the number of items to show on one page.</dd>
			<dt>Start</dt>
			<dd>Click to go to the first page.</dd>
			<dt>Prev</dt>
			<dd>Click to go to the previous page.</dd>
			<dt>Page numbers</dt>
			<dd>Click to go to the desired page.</dd>
			<dt>Next</dt>
			<dd>Click to go to the next page.</dd>
			<dt>End</dt>
			<dd>Click to go to the last page.</dd>
		</dl>
	</div>
</article>