<article>
	<h1><span>Citations: Format</span></h1>

	<ul class="nav">
		<li><a href="#overview">Overview</a></li>
		<li><a href="#toolbar">Toolbar</a></li>
		<li><a href="#format">Format</a></li>
	</ul>

	<section id="description">
		<h2><span>Description</span></h2>
		<p>This is where a format for diplaying a citaiton can be selected (from a list of pre-determined formats) or created (for a custom format).</p>
	</section>
	<section id="toolbar">
		<h2><span>Toolbar</span></h2>
		<p>At the top right you will see the toolbar.</p>
		<p>The functions are:</p>
		<dl>
			<dt>Save &amp; Close</dt>
			<dd>Save changes and return to the listing of entries.</dd>

			<dt>Help</dt>
			<dd>Opens this help screen.</dd>
		</dl>
	</section>
	<section id="format">
		<h2><span>Format</span></h2>

		<dl>
			<dt>Style</dt>
			<dd>Select a pre-determined style for formatting citations, such as APA or IEEE, or a custom style.</dd>

			<dt>String</dt>
			<dd>The is where a custom citation format can be created. The format specified here will <em>only</em> be used if <strong>Style></strong> is set to "custom". When creating a format, one can enter from a list of available placeholders to dynamically build the citation for each entry. For example, when "{AUTHORS}" is entered, the system will replace "{AUTHORS}" with the list of authors entered for the citation entry.</dd>
		</dl>
	</section>
</article>