<article>
	<h1><span>Article Manager: Articles</span></h1>

	<ul class="nav">
		<li><a href="#overview">Overview</a></li>
		<li><a href="#column-headers">Column Headers</a></li>
		<li><a href="#toolbar">Toolbar</a></li>
		<li><a href="#sub-menu">Sub-menu Links</a></li>
		<li><a href="#list-filters">List Filters</a></li>
	</ul>

	<section id="overview">
		<h2><span class="mw-headline" id="Description">Description</span></h2>
		<p>The Article Manager is used to add and edit articles. See <a href="/proxy/index.php?option=com_help&view=help&keyref=Help25:Content_Article_Manager#Toolbar" title="Help25:Content Article Manager">Toolbar</a> below for a detailed list of all functions.</p>
	</section>
	<section id="column-headers">
		<h2><span class="mw-headline" id="Column_Headers">Column Headers</span></h2>
		<p>Click on the column heading to sort the list by that column's value. The list will be sorted in order by that column and a sort icon will show next to the column name, as shown below.</p>
		<div class="thumb tnone">
		<div class="thumbinner" style="width:282px;"><a href="/proxy/index.php?option=com_help&view=help&keyref=File:Help25-chunk-colheader-order-ascending.png" class="image"><img alt="Help25-chunk-colheader-order-ascending.png" src="http://docs.joomla.org/images/7/78/Help25-chunk-colheader-order-ascending.png" width="280" height="86" class="thumbimage" /></a>
		<div class="thumbcaption"></div>
		</div>
		</div>
		<p>Click a second time to reverse the sort to high-to-low. The sort icon will change to high-to-low, as shown below.</p>
		<div class="thumb tnone">
		<div class="thumbinner" style="width:276px;"><a href="/proxy/index.php?option=com_help&view=help&keyref=File:Help25-chunk-colheader-order-descending.png" class="image"><img alt="Help25-chunk-colheader-order-descending.png" src="http://docs.joomla.org/images/1/1d/Help25-chunk-colheader-order-descending.png" width="274" height="95" class="thumbimage" /></a>
		<div class="thumbcaption"></div>
		</div>
		</div>
		<ul>
		<li><b>Checkbox</b>. Check this box to select one or more items. To select all items, check the box in the column heading. After one or more boxes are checked, click a toolbar button to take an action on the selected item or items. Many toolbar actions, such as Publish and Unpublish, can work with multiple items. Others, such as Edit, only work on one item at a time. If multiple items are checked and you press Edit, the first item will be opened for editing.</li>
		</ul>
		<ul>
		<li><b>Title</b>. The name of the item. For a Menu Item, the Title will display in the Menu. For an Article or Category, the Title may optionally be displayed on the web page. This entry is required. You can open the item for editing by clicking on the Title.</li>
		</ul>
		<ul>
		<li><b>Status.</b> (Published/Unpublished/Archived/Trashed) The published status of the item.</li>
		<li><b>Featured.</b> Whether or not the Article will show on the Featured Articles Page. You can change an Article's published state by clicking on the icon in the column.</li>
		</ul>
		<ul>
		<li><b>Category.</b> The Category this item belongs to.</li>
		</ul>
		<ul>
		<li><b>Ordering</b>. The order in which to display items. You can sort the list by order number by clicking on the Ordering label in the column heading. If the list is sorted by this column, you can change the order by clicking the arrows or by entering the sequential order and clicking the 'Save Order' icon. This is shown in the screen below.
		<div class="thumb tnone">
		<div class="thumbinner" style="width:730px;"><a href="/proxy/index.php?option=com_help&view=help&keyref=File:Help25-chunk-colheader-order-icons.png" class="image"><img alt="Help25-chunk-colheader-order-icons.png" src="http://docs.joomla.org/images/b/b6/Help25-chunk-colheader-order-icons.png" width="728" height="170" class="thumbimage" /></a>
		<div class="thumbcaption"></div>
		</div>
		</div>
		Note that the ordering is only defined within a single category. For this reason, it is easier to re-order the list if you use the Category filter to select one category.</li>
		</ul>
		<ul>
		<li><b>Access.</b> The viewing level access for this item.</li>
		<li><b>Created by.</b> Name of the Joomla! User who created this item.</li>
		<li><b>Date.</b> The date this Article was created. This date is added automatically by Joomla!, but you may change it in the Publishing Options - Article section of the <a href="/proxy/index.php?option=com_help&view=help&keyref=Help25:Content_Article_Manager_Edit" title="Help25:Content Article Manager Edit">Content Article Manager Edit</a>.</li>
		</ul>
		<ul>
		<li><b>Hits.</b> The number of times an item has been viewed.</li>
		</ul>
		<ul>
		<li><b>Language</b>. Item language.</li>
		</ul>
		<ul>
		<li><b>ID</b>. This is a unique identification number for this item assigned automatically by Joomla!. It is used to identify the item internally, and you cannot change this number. When creating a new item, this field displays 0 until you save the new entry, at which point a new ID is assigned to it.</li>
		</ul>
	</section>
	<section id="toolbar">
		<h2><span class="mw-headline">Toolbar</span></h2>
		<p>At the top right you will see the toolbar:</p>
		<p><a href="/proxy/index.php?option=com_help&view=help&keyref=File:Help25-Toolbar-New-Edit-Publish-Unpublish-Featured-Archive-Checkin-Trash-Options-Help.png" class="image"><img alt="Help25-Toolbar-New-Edit-Publish-Unpublish-Featured-Archive-Checkin-Trash-Options-Help.png" src="http://docs.joomla.org/images/e/e9/Help25-Toolbar-New-Edit-Publish-Unpublish-Featured-Archive-Checkin-Trash-Options-Help.png" width="584" height="65" /></a></p>
		<p>The functions are:</p>
		<ul>
		<li><b>New</b>. Opens the editing screen to create a new article.</li>
		<li><b>Edit</b>. Opens the editing screen for the selected article. If more than one article is selected (where applicable), only the first article will be opened. The editing screen can also be opened by clicking on the Title or Name of the article.</li>
		<li><b>Publish</b>. Makes the selected articles available to visitors to your website.</li>
		<li><b>Unpublish</b>. Makes the selected articles unavailable to visitors to your website.</li>
		<li><b>Featured.</b> Marks selected articles as featured. Works with one or multiple articles selected.</li>
		<li><b>Archive</b>. Changes the status of the selected articles to indicate that they are archived. Archived articles can be moved back to the published or unpublished state by selecting "Archived" in the Select Status filter and changing the status of the articles to Published or Unpublished as preferred.</li>
		<li><b>Check In</b>. Checks-in the selected articles. Works with one or multiple articles selected.</li>
		<li><b>Trash</b>. Changes the status of the selected articles to indicate that they are trashed. Trashed articles can still be recovered by selecting "Trashed" in the Select Status filter and changing the status of the articles to Published or Unpublished as preferred. To permanently delete trashed articles, select "Trashed" in the Select Status filter, select the articles to be permanently deleted, then click the Empty Trash toolbar icon.</li>
		<li><b>Options</b>. Opens the Options window where settings such as default parameters or permissions can be edited. See <a href="/proxy/index.php?option=com_help&view=help&keyref=Help25:Content_Article_Manager_Options" title="Help25:Content Article Manager Options">Article Manager Options</a> for more information.</li>
		<li><b>Help</b>. Opens this help screen.</li>
		</ul>
	</section>
	<section id="toolbar-links">
		<h2> <span class="mw-headline" id="Toolbar_Links">Toolbar Links</span></h2>
		<p>At the top left, above the Filter, you will see the following two links:</p>
		<p><a href="/proxy/index.php?option=com_help&view=help&keyref=File:Help25-contents-manager-links.png" class="image"><img alt="Help25-contents-manager-links.png" src="http://docs.joomla.org/images/d/de/Help25-contents-manager-links.png" width="352" height="36" /></a></p>
		<ul>
		<li><b>Articles.</b> This link takes you to the screen you are currently on.</li>
		<li><b>Categories.</b> Click this link to go to the <a href="/proxy/index.php?option=com_help&view=help&keyref=Help25:Components_Content_Categories" title="Help25:Components Content Categories">Content Manager: Categories</a> screen.</li>
		<li><b>Featured Articles.</b> Click this link to go to the <a href="/proxy/index.php?option=com_help&view=help&keyref=Help25:Content_Featured_Articles" title="Help25:Content Featured Articles">Content Manager: Featured Articles</a> screen.</li>
		</ul>
	</section>
	<section id="list-filters">
		<h2> <span class="mw-headline" id="List_Filters">List Filters</span></h2>
		<p>Above the column headers are a series of controls that let you limit what items show in the manager screen. More than one filter may be entered. In this case, only items that meet all of the filter conditions will show on the list.</p>
		<ul>
		<li><b>Filter by Partial Title or ID.</b> In the upper left is a filter field and two buttons, as shown below.
		<div class="thumb tnone">
		<div class="thumbinner" style="width:285px;"><a href="/proxy/index.php?option=com_help&view=help&keyref=File:Help25-chunk-colheader-filter-field.png" class="image"><img alt="Help25-chunk-colheader-filter-field.png" src="http://docs.joomla.org/images/0/03/Help25-chunk-colheader-filter-field.png" width="283" height="46" class="thumbimage" /></a>
		<div class="thumbcaption"></div>
		</div>
		</div>
		<ul>
		<li>To filter by partial title, enter part of the title and click Search.</li>
		<li>To filter by ID number, enter "id:xx", where "xx" is the ID number (for example, "id:9").</li>
		</ul>
		</li>
		</ul>
		<dl>
		<dd>Click Clear to clear the Filter field and restore the list to its unfiltered state.</dd>
		</dl>
		<ul>
		<li><b>Filter by Published Status.</b> Lets you show only items with the selected published status.
		<div class="thumb tnone">
		<div class="thumbinner" style="width:104px;"><a href="/proxy/index.php?option=com_help&view=help&keyref=File:Help25-chunk-colheader-select-status.png" class="image"><img alt="Help25-chunk-colheader-select-status.png" src="http://docs.joomla.org/images/8/85/Help25-chunk-colheader-select-status.png" width="102" height="97" class="thumbimage" /></a>
		<div class="thumbcaption"></div>
		</div>
		</div>
		<ul>
		<li><i>- Select Status -:</i> Shows items that are Published and Unpublished. Does <i>not</i> show items that are Trashed or Archived.</li>
		<li><i>Published:</i> Shows only items that are Published.</li>
		<li><i>Unpublished:</i> Shows only items that are Unpublished.</li>
		<li><i>Archived:</i> Shows only items that are Archived.</li>
		<li><i>Trashed:</i> Shows only items that are Trashed. <i>Important Note:</i> To permanently delete items:
		<ol>
		<li>Change the status of the items to Trashed.</li>
		<li>Change the Status filter to Trashed. At this point the trashed items will show and an icon called "Empty trash" will show in the toolbar.</li>
		<li>Select the desired trashed items and click on "Empty Trash" in the toolbar. The items will be permanently deleted.</li>
		</ol>
		</li>
		<li><i>All:</i> Shows all items regardless of published status.</li>
		</ul>
		</li>
		</ul>
		<ul>
		<li><b>Filter by Category.</b> Lets you show only items assigned to a specific category. The list box will show the categories defined for your site, similar to the example below.
		<div class="thumb tnone">
		<div class="thumbinner" style="width:148px;"><a href="/proxy/index.php?option=com_help&view=help&keyref=File:Help25-chunk-colheader-select-category.png" class="image"><img alt="Help25-chunk-colheader-select-category.png" src="http://docs.joomla.org/images/2/25/Help25-chunk-colheader-select-category.png" width="146" height="137" class="thumbimage" /></a>
		<div class="thumbcaption"></div>
		</div>
		</div>
		<ul>
		<li><i>- Select Category -:</i> Show items assigned to any category.</li>
		<li><i>&lt;your category&gt;:</i> Show items assigned only to this category.</li>
		</ul>
		</li>
		</ul>
		<ul>
		<li><b>Filter by Max Levels (Category Level).</b> Lets you show only items whose category is at or above the specified level in the category hierarchy.
		<div class="thumb tnone">
		<div class="thumbinner" style="width:127px;"><a href="/proxy/index.php?option=com_help&view=help&keyref=File:Help25-chunk-colheader-select-max-levels.png" class="image"><img alt="Help25-chunk-colheader-select-max-levels.png" src="http://docs.joomla.org/images/c/cf/Help25-chunk-colheader-select-max-levels.png" width="125" height="162" class="thumbimage" /></a>
		<div class="thumbcaption"></div>
		</div>
		</div>
		<ul>
		<li><i>- Select Max Levels -:</i> Show all items regardless of level of their assigned category.</li>
		<li><i>1:</i> Only show items whose category is at the top level in the category hierarchy (in other words, with categories whose parent category is "- No Parent -".)</li>
		<li><i>2-10:</i> Only show items whose category is in the top 2-10 levels in the category hierarchy.</li>
		</ul>
		</li>
		</ul>
		<ul>
		<li><b>Filter by Viewing Access Level.</b> Lets you show only items that have a specified viewing access level. The list box will show the access levels defined for your site, similar to the example below.
		<div class="thumb tnone">
		<div class="thumbinner" style="width:189px;"><a href="/proxy/index.php?option=com_help&view=help&keyref=File:Help25-chunk-colheader-select-access.png" class="image"><img alt="Help25-chunk-colheader-select-access.png" src="http://docs.joomla.org/images/8/8c/Help25-chunk-colheader-select-access.png" width="187" height="84" class="thumbimage" /></a>
		<div class="thumbcaption"></div>
		</div>
		</div>
		<ul>
		<li><i>- Select Access -:</i> Show items with any viewing access level.</li>
		<li><i>&lt;your access level&gt;:</i> Show items only with this viewing access level.</li>
		</ul>
		</li>
		</ul>
		<ul>
		<li><b>Filter by Author.</b> Lets you show only items that have the specified author. The list box will show the authors for your site, similar to the example below.
		<div class="thumb tnone">
		<div class="thumbinner" style="width:125px;"><a href="/proxy/index.php?option=com_help&view=help&keyref=File:Help25-chunk-colheader-select-author.png" class="image"><img alt="Help25-chunk-colheader-select-author.png" src="http://docs.joomla.org/images/a/aa/Help25-chunk-colheader-select-author.png" width="123" height="71" class="thumbimage" /></a>
		<div class="thumbcaption"></div>
		</div>
		</div>
		<ul>
		<li><i>- Select Author -:</i> Show all items regardless of their author.</li>
		<li><i>&lt;your author&gt;:</i> Only show items with the specified author.</li>
		</ul>
		</li>
		</ul>
		<ul>
		<li><b>Filter by Language.</b> Lets you show only items that have a specific language assigned. The list box will show the languages defined for your site, similar to the example below.
		<div class="thumb tnone">
		<div class="thumbinner" style="width:122px;"><a href="/proxy/index.php?option=com_help&view=help&keyref=File:Help25-chunk-colheader-select-language.png" class="image"><img alt="Help25-chunk-colheader-select-language.png" src="http://docs.joomla.org/images/7/75/Help25-chunk-colheader-select-language.png" width="120" height="71" class="thumbimage" /></a>
		<div class="thumbcaption"></div>
		</div>
		</div>
		<ul>
		<li><i>- Select Language - or All:</i> Show items for any language.</li>
		<li><i>&lt;your language&gt;:</i> Show items only for this language.</li>
		</ul>
		</li>
		</ul>
		<ul>
		<li><b>Page Controls.</b> When the number of items is more than one page, you will see a page control bar as shown below.
		<div class="thumb tnone">
		<div class="thumbinner" style="width:543px;"><a href="/proxy/index.php?option=com_help&view=help&keyref=File:Help25-chunk-colheader-pagination.png" class="image"><img alt="Help25-chunk-colheader-pagination.png" src="http://docs.joomla.org/images/7/76/Help25-chunk-colheader-pagination.png" width="541" height="37" class="thumbimage" /></a>
		<div class="thumbcaption"></div>
		</div>
		</div>
		<ul>
		<li><b>Display #:</b> Select the number of items to show on one page.</li>
		<li><b>Start:</b> Click to go to the first page.</li>
		<li><b>Prev:</b> Click to go to the previous page.</li>
		<li><b>Page numbers:</b> Click to go to the desired page.</li>
		<li><b>Next:</b> Click to go to the next page.</li>
		<li><b>End:</b> Click to go to the last page.</li>
		</ul>
		</li>
		</ul>
	</section>
	<section id="options">
		<h2> <span class="mw-headline" id="Batch_Process">Batch Process</span></h2>
		<p>This section allows you to change settings for a group of selected items. The fields are as shown below.</p>
		<div class="thumb tnone">
		<div class="thumbinner" style="width:331px;"><a href="/proxy/index.php?option=com_help&view=help&keyref=File:Help25-chunk-colheader-batch-process.png" class="image"><img alt="Help25-chunk-colheader-batch-process.png" src="http://docs.joomla.org/images/e/ec/Help25-chunk-colheader-batch-process.png" width="329" height="182" class="thumbimage" /></a>
		<div class="thumbcaption"></div>
		</div>
		</div>
		<p>You can change one value or all three values at one time. Note that if you copy items to a new category, changes you have selected fro access level and language will be applied to the copies, not the original.</p>
		<p>To batch process a group of items:</p>
		<ol>
		<li>Select one or more items on the list by checking the desired check boxes.</li>
		<li>Set one or more of the following values:
		<ul>
		<li>To change the access levels, select the desired new access level from the Set Access Level list box.</li>
		<li>To change the Language, select the desired language from the Set Language list box.</li>
		<li>To change the Category, select a category. To leave the category unchanged, use the default value of "Select".
		<ul>
		<li>To copy the items to a different category, select the desired category from the category list box and check the Copy option. In this case, the original items are unchanged and the copies are assigned to the new category and, if selected, the new access level and language.</li>
		<li>To move the items to a different category, select the desired category from the category list box and check the Move option. In this case, the original items will be moved to a new category and, if selected, be assigned the new access level and language.</li>
		</ul>
		</li>
		</ul>
		</li>
		<li>When all of the settings are entered, click on Process to perform the changes. A message "Batch process completed successfully." will show.</li>
		</ol>
		<p>Note that nothing will happen if you (a) don't have any items selected or (b) have not selected an access level, language, or category.</p>
		<p>If you wish to clear your entered selections, click on the Clear button. This will return all of the Batch controls to their default values. Note that this does <i>not</i> uncheck the check boxes for the items.</p>
	</section>
	<section id="options">
		<h2> <span class="mw-headline" id="Options">Options</span></h2>
		<p>Clicking on the Options icon in the toolbar opens a modal window where you can set component level options for articles. To see the help screen for Options, click <a href="/proxy/index.php?option=com_help&view=help&keyref=Help25:Content_Article_Manager_Options" title="Help25:Content Article Manager Options">Article Manager Options</a></p>
	</section>
	<section id="tips">
		<h2> <span class="mw-headline" id="Quick_Tips">Quick Tips</span></h2>
		<ul>
		<li>If Joomla is installed without sample data, one article category called "Uncategorised" is created automatically. If you want to use other categories for articles, you should create them before trying to add articles.</li>
		<li>To see trashed and archived articles, set the Status filter to All.</li>
		<li>To change the ordering of articles within a category, click on the Ordering column heading to sort by this column. Also, it is easier to see the ordering if you filter on the desired category.</li>
		</ul>
	</section>
	<section id="related">
		<h2> <span class="mw-headline" id="Related_Information">Related Information</span></h2>
		<ul>
		<li>To add or edit Articles: <a href="/proxy/index.php?option=com_help&view=help&keyref=Help25:Content_Article_Manager_Edit" title="Help25:Content Article Manager Edit">Article Manager: New/Edit</a></li>
		<li>To manage Categories: <a href="/proxy/index.php?option=com_help&view=help&keyref=Help25:Components_Content_Categories" title="Help25:Components Content Categories">Category Manager</a></li>
		<li>To manage Featured Articles: <a href="/proxy/index.php?option=com_help&view=help&keyref=Help25:Content_Featured_Articles" title="Help25:Content Featured Articles">Article Manager: Featured Articles</a></li>
		</ul>
	</section>
</article>