		<article>
			<h1><span>Tags Manager: Tagged Items: Adding/Editing</span></h1>

			<ul class="nav">
				<li><a href="#overview">Overview</a></li>
				<li><a href="#toolbar">Toolbar</a></li>
				<li><a href="#details">Details</a></li>
			</ul>

			<section id="overview">
				<h2><span>Overview</span></h2>

				<p>You will be presented with a form to create a tag/item link or "tag an item".</p>
			</section>
			<section id="toolbar">
				<h2><span>Toolbar</span></h2>
				<p>At the top right you will see the toolbar. The functions are:</p>
				<dl>
					<dt>Save</dt>
					<dd>Save changes and return to the edit form.</dd>

					<dt>Save &amp; Close</dt>
					<dd>Save changes and return to the listing of entries.</dd>

					<dt>Cancel</dt>
					<dd>Discard any changes made and return to the listing of entries.</dd>

					<dt>Help</dt>
					<dd>Opens this help screen.</dd>
				</dl>
			</section>
			<section id="details">
				<h2><span>Details</span></h2>

				<dl>
					<dt>ID</dt>
					<dd>ID if the entry.</dd>

					<dt>Item Type</dt>
					<dd>The type of item being tagged. This typically corresponds to a component name (without the 'com_' prefix), such as 'wishlist', 'blog', etc.</dd>

					<dt>Item ID</dt>
					<dd>The ID of the item being tagged.</dd>
				</dl>
			</section>
		</article>