		<article>
			<h1><span>Tags: Merge</span></h1>
			<div class="section">
				<h2><span>Overview</span></h2>
				<p>Should a situation arise where two or more tags should really be one tag, you can merge them. To merge tags, check the box next to the tags you wish to merge and hit the &#8220;merge&#8221; button in the toolbar located at the top right of the page.</p>
				<p>You will then be presented with a list of the tags you want to merge (and how many items are using each tag) and the options to either:</p>
				<ul>
					<li>Merge the tags under another existing tag (ex: everything tagged with &#8220;h2o&#8221; and &#8220;hydro&#8221; can be merged to just &#8220;hydro&#8221;) or</li>
					<li>Merge the tags into a new tag (ex: everything tagged with &#8220;h2o&#8221; and &#8220;hydro&#8221; can be merged to &#8220;water&#8221;)</li>
				</ul>
				<p>Click &#8220;Save&#8221; in the upper right portion of the page to perform the final merge. <strong>Note:</strong> This cannot be undone!</p>
			</div>
		</article>