<article>
	<h1>Extension Manager: Update</h1>

	<p>This screen is accessed from the back-end Joomla! administrator panel. It is used to update extensions that are installed in your Joomla! installation.</p>
<h2> <span class="mw-headline" id="How_to_Access">How to Access</span></h2>
<ul><li>Select <b>Extensions → Extension Manager</b> from the drop-down menu of the <i><b>Joomla! Administrator Panel</b></i>. Then select the <b>Update</b> menu item in the <i><b>Extension manager</b></i> screen that appears, or
</li><li>Press the extension Update button in the <a href="/proxy/index.php?option=com_help&view=help&keyref=Help25:Site_Control_Panel" title="Help25:Site Control Panel">Control Panel</a>
</li></ul>
<h2> <span class="mw-headline" id="Description">Description</span></h2>
<p>This screen allows you to update installed extensions.  You will only be able to update extensions which support this feature. For extensions which support this feature, you will be able to perform an in-place update of the extension without having to upload and install the updated extension files like you did with previous versions of Joomla!. The update feature utilizes standard HTTP connection mechanisms to download the extension update files from a remote update server.
</p>
<h2> <span class="mw-headline" id="Column_Headers">Column Headers</span></h2>
<ul><li><b>Checkbox</b>. Check this box to select one or more items. To select all items, check the box in the column heading. After one or more boxes are checked, click a toolbar button to take an action on the selected item or items. Many toolbar actions, such as Publish and Unpublish, can work with multiple items. Others, such as Edit, only work on one item at a time. If multiple items are checked and you press Edit, the first item will be opened for editing.
</li><li><b>Name.</b> The name of the extension.
</li><li><b>Install Type.</b> The type of installation that will be performed by the update. Usually this will be type <i><b>Update</b></i> which will perform an in-place update of the extension
</li><li><b>Type.</b> The extension type. Examples of extension types are module, plug-in, template, component, or language.
</li><li><b>Version.</b> The version number of the available update.
</li><li><b>Folder.</b> If the extension is a plug-in, the subdirectory of your Joomla! installation's /plugins directory where the extension is located. By default Joomla! has the following subdirectories in the plugins directory which each represent the different types of plug-ins that are defined: authentication, content, editors, editors-xtd, extension, search, system, user.
</li><li><b>Client.</b> Specifies if this is a site or administrator extension.
</li><li><b>URL Details.</b> The URL for the extension update XML file which contains the information needed by your Joomla! installation to perform the update.
</li></ul>
<h2> <span class="mw-headline" id="List_Filters">List Filters</span></h2>
<ul><li><b>Page Controls.</b> When the number of items is more than one page, you will see a page control bar as shown below.
<ul><li><b>Display #:</b> Select the number of items to show on one page.
</li><li><b>Start:</b> Click to go to the first page.
</li><li><b>Prev:</b> Click to go to the previous page.
</li><li><b>Page numbers:</b> Click to go to the desired page.
</li><li><b>Next:</b> Click to go to the next page.
</li><li><b>End:</b> Click to go to the last page.
</li></ul>
</li></ul>
<h2> <span class="mw-headline" id="Toolbar">Toolbar</span></h2>
<p>At the top right you will see the toolbar. The functions are:
</p>
<ul><li><b>Update</b>. Updates the selected extension(s).
</li><li><b>Find Updates</b>. Scans your Joomla! installation and locates extensions with an available update.
</li><li><b>Purge Cache</b>. Clears cached information about available extension updates.  This will update the list of available extension updates shown on this screen.
</li><li><b>Options</b>. Opens the Options window where settings such as default parameters or permissions can be edited.
</li><li><b>Help</b>. Opens this help screen.
</li></ul>
<h2> <span class="mw-headline" id="Links_to_Other_Screens">Links to Other Screens</span></h2>
<p>At the top left, you will see the following five links:
</p>
<ul><li><b>Install.</b> Links to the <a href="/proxy/index.php?option=com_help&view=help&keyref=Help25:Extensions_Extension_Manager_Install" title="Help25:Extensions Extension Manager Install">Install Screen</a>.
</li><li><b>Update.</b> Links to the <strong class="selflink">Update Screen</strong>.
</li><li><b>Manage.</b> Links to the <a href="/proxy/index.php?option=com_help&view=help&keyref=Help25:Extensions_Extension_Manager_Manage" title="Help25:Extensions Extension Manager Manage">Manage Screen</a>.
</li><li><b>Discover.</b> Links to the <a href="/proxy/index.php?option=com_help&view=help&keyref=Help25:Extensions_Extension_Manager_Discover" title="Help25:Extensions Extension Manager Discover">Discover Screen</a>.
</li><li><b>Database.</b> Links to the <a href="/proxy/index.php?option=com_help&view=help&keyref=Help25:Extensions_Extension_Manager_Database" title="Help25:Extensions Extension Manager Database">Database Screen</a>.
</li><li><b>Warnings.</b> Links to the <a href="/proxy/index.php?option=com_help&view=help&keyref=Help25:Extensions_Extension_Manager_Warnings" title="Help25:Extensions Extension Manager Warnings">Warnings Screen</a>.
</li><li><b>Install Langauges.</b> Links to the <a href="/proxy/index.php?option=com_help&view=help&keyref=Help25:Extensions_Extension_Manager_languages" title="Help25:Extensions Extension Manager languages">Languages Screen</a>.
</li></ul>
<h2> <span class="mw-headline" id="Quick_Tips">Quick Tips</span></h2>
<ul><li> Only extensions which support the Joomla! update system will be listed in this screen. If you use extensions which do not support the new update system or you are not sure, consult the extension developer's website.
</li></ul>
<ul><li> It is critical to keep your extensions up-to-date. Failure to do so may expose a vulnerability in your Joomla! installation which can be exploited by hackers.
</li></ul>
<ul><li> It is recommended to backup your Joomla! installation files and database before attempting to update extensions or the Joomla! installation itself. This will ensure that you can restore your Joomla! installation to its previous state if the update fails or causes unexpected results.
</li></ul>
</article>