<article>
	<h1>Extension Manager: Warnings</h1>

	<p>This screen is accessed from the back-end administrator panel. It will display warnings related to your installed extensions.</p>

	<sction>
		<h2><span class="mw-headline" id="How_to_Access">How to Access</span></h2>
		<ul>
			<li>Select <b>Extensions → Extension Manager</b> from the drop-down menu of the <i><b>Administrator Panel</b></i>. Then select the <b>Warnings</b> menu item in the <i><b>Extension manager</b></i> screen that appears.</li>
		</ul>
	</section>
	<sction>
		<h2><span class="mw-headline" id="Description">Description</span></h2>
		<p>This screen will display any warnings related to extensions you have installed in your installation. Warnings such as possible conflicts in your installation or dependency failures may appear here.</p>
	</section>
	<sction>
		<h2><span class="mw-headline" id="Toolbar">Toolbar</span></h2>
		<p>At the top right you will see the toolbar. The functions are:</p>
		<ul>
			<li><b>Options</b>. Opens the Options window where settings such as default parameters or permissions can be edited.</li>
			<li><b>Help</b>. Opens this help screen.</li>
		</ul>
	</section>
	<sction>
		<h2><span class="mw-headline" id="Links_to_Other_Screens">Links to Other Screens</span></h2>
		<p>At the top left, you will see the following five links:</p>
		<ul>
			<li><b>Install.</b> Links to the <a href="<?php echo Route::url('index.php?option=com_help&view=help&keyref=Help25:Extensions_Extension_Manager_Install'); ?>" title="Help25:Extensions Extension Manager Install">Install Screen</a>.</li>
			<li><b>Update.</b> Links to the <a href="<?php echo Route::url('index.php?option=com_help&view=help&keyref=Help25:Extensions_Extension_Manager_Update'); ?>" title="Help25:Extensions Extension Manager Update">Update Screen</a>.</li>
			<li><b>Manage.</b> Links to the <a href="<?php echo Route::url('index.php?option=com_help&view=help&keyref=Help25:Extensions_Extension_Manager_Manage'); ?>" title="Help25:Extensions Extension Manager Manage">Manage Screen</a>.</li>
			<li><b>Discover.</b> Links to the <a href="<?php echo Route::url('index.php?option=com_help&view=help&keyref=Help25:Extensions_Extension_Manager_Discover'); ?>" title="Help25:Extensions Extension Manager Discover">Discover Screen</a>.</li>
			<li><b>Database.</b> Links to the <a href="<?php echo Route::url('index.php?option=com_help&view=help&keyref=Help25:Extensions_Extension_Manager_Database'); ?>" title="Help25:Extensions Extension Manager Database">Database Screen</a>.</li>
			<li><b>Warnings.</b> Links to the <strong class="selflink">Warnings Screen</strong>.</li>
			<li><b>Install Langauges.</b> Links to the <a href="<?php echo Route::url('index.php?option=com_help&view=help&keyref=Help25:Extensions_Extension_Manager_languages'); ?>" title="Help25:Extensions Extension Manager languages">Languages Screen</a>.</li>
		</ul>
	</section>
</article>