<article>
	<h1><span>Billboards Manager: Edit Billboard</span></h1>

	<ul class="nav">
		<li><a href="#overview">Overview</a></li>
		<li><a href="#toolbar">Toolbar</a></li>
		<li><a href="#content">Billboard Content</a></li>
		<li><a href="#learn-more">Learn More Link</a></li>
		<li><a href="#styling">Billboard Styling</a></li>
	</ul>

	<section id="description">
		<h2><span>Description</span></h2>
		<p>This is where you can add a new Billboard or edit an existing Billboard.</p>
	</section>
	<section id="toolbar">
		<h2><span>Toolbar</span></h2>
		<p>At the top right you will see the toolbar.</p>
		<p>The functions are:</p>
		<dl>
			<dt>Images</dt>
			<dd>Upload and manage images used.</dd>

			<dt>Save &amp; Close</dt>
			<dd>Save changes and return to the listing of entries.</dd>

			<dt>Cancel</dt>
			<dd>Discard any changes made and return to the listing of entries.</dd>

			<dt>Help</dt>
			<dd>Opens this help screen.</dd>
		</dl>
	</section>
	<section id="content">
		<h2><span>Billboard Content</span></h2>

		<dl>
			<dt>Name</dt>
			<dd>The Title for this item. This may or may not display on the page, depending on the parameter values you choose.</dd>

			<dt>Collection</dt>
			<dd>The collection the entry can be found in.</dd>

			<dt>Collection</dt>
			<dd>The collection the entry can be found in.</dd>

			<dt>Order</dt>
			<dd>The order in which the entry will appear in the chosen collection.</dd>

			<dt>Header</dt>
			<dd>A display header for the billboard.</dd>

			<dt>Backgorund Image</dt>
			<dd>The image used for the backgorund of the billboard.</dd>

			<dt>Text</dt>
			<dd>The text displayed in the billboard.</dd>
		</dl>
	</section>
	<section id="learn-more">
		<h2><span>Learn More Link</span></h2>

		<dl>
			<dt>Text</dt>
			<dd>The text of the link.</dd>

			<dt>Target</dt>
			<dd>The URI for the links.</dd>

			<dt>Class</dt>
			<dd>A CSS class to apply to the link.</dd>

			<dt>Location</dt>
			<dd>The positioning of the link in the billboard.</dd>
		</dl>
	</section>
	<section id="styling">
		<h2><span>Billboard Styling</span></h2>

		<dl>
			<dt>Alias</dt>
			<dd>Board alias.</dd>

			<dt>Text Padding</dt>
			<dd>The padding applied to the block of text. This is in CSS short-hand and each number position represents a side of padding, in order: top right bottom left. Accepted values are any number followed by <b>px</b>, <b>%</b>, or <b>em</b>. Example: 12px 4px 16px 20px</dd>

			<dt>CSS</dt>
			<dd>Custom CSS to apply to the entry.</dd>
		</dl>
	</section>
</article>