<?php
/**
 * @package    hubzero-cms
 * @copyright  Copyright 2005-2019 HUBzero Foundation, LLC.
 * @license    http://opensource.org/licenses/MIT MIT
 */
?>
<article>
	<h1>Support FAQ's</h1>

	<nav>
		<ol>
			<li>
				<a href="#mathquestion">Why the math question?</a>
			</li>
		</ol>
	</nav>

	<section id="mathquestion">
		<h3>Why the math question?</h3>
		<p>When you use the Help button to submit a trouble report, it may ask you a simple math question such as "What is the sum of 3 and 5?" You get this if you're not logged in. Providing a correct answer gives us some indication that you're a human that has read and understood the question--not a bot that is attempting to put spam on our site!</p>
	</section>
</article>