<article>
	<h1><span>Support: Stats</span></h1>
	<section>
		<h2><span>Overview</span></h2>

		<p>The stats page gives a basic overview of support ticket activity starting at the beginning of a chosen year, defaulting to the current year if none specified.</p>

		<p>The following data is shown:</p>

		<ul>
			<li>Tickets opened for the given year</li>
			<li>Tickets closed for the given year</li>
			<li>Tickets opened for the current month of the year</li>
			<li>Tickets closed for the current month of the year</li>
			<li>Tickets opened for the current week of the year</li>
			<li>Tickets closed for the current week of the year</li>
			<li>Open tickets</li>
			<li>Unassigned tickets</li>
			<li>Average ticket lifetime</li>
			<li>A list of administrators and the number of tickets closed
				<ul>
					<li>closed for the given year</li>
					<li>closed for the current month of the year</li>
					<li>closed for the current week of the year</li>
				</ul>
			</li>
			<li>A line chart displaying Tickets Submitted (red) vs. Closed (green) on a monthly basis</li>
		</ul>

		<p>Stats shown may also be filtered by group.</p>
	</section>
</article>
