		<article>
			<h1><span>Support: Ticket</span></h1>
			<section>
				<h2><span>Overview</span></h2>

				<p>Here you will find a submitted ticket and all associated data, including comments, change and notification logs, and attachments.</p>
			</section>
			<section>
				<h2><span>Changes</span></h2>

				<p>The original ticket data may not be modified in any way. Only associated or non-destructive changes may occur, such as changing status, severity, adding/removing tags, and assigning owner. All changes are tracked in a log.</p>

				<h3>Status</h3>
				<dl>
					<dt>Open</dt>
					<dd>An open issue. The ticket needs to be addressed in some fashion.</dd>

					<dt>Awaiting user action</dt>
					<dd>This is for when you need more information from or the ticket submitter to perform a specific task (such as test that a fix is working for them). In short, further progress on the ticket is dependant upon the some course of action from the ticket submitter.</dd>

					<dt>Closed</dt>
					<dd>The ticket is considered recolved. Here, a list of resolutions can be specified to better filter and generate stats by.</dd>
				</dl>

				<h3 id="owner">Owner</h3>

				<p>The owner of a ticket is the <i>current</i> user assigned to perform some action or address the the issue presented by the ticket in some way. Ownership may change several times during the life of the ticket and is tracked in the change log. When assigned to a ticket as an owner, the ticket will appear in the user's "My assigned tickets" list.</p>

				<h3>Group</h3>

				<p>Sometimes, a ticket may belong to a group of users rather than a specific person.</p>

				<h3 id="severity">Severity</h3>

				<dl>
					<dt><span style="color: blue;">Low</span></dt>
					<dd>
						<p>Minor loss of application functionality, product feature requests, how-to questions. The issue consists of "how-to" questions including issues related to one or multiple modules and integration, installation and configuration inquiries, enhancement requests, or documentation questions.</p>
						<h4>Qualifying Conditions</h4>
						<ul>
							<li>Problem does not have significant impact to the Customer or occurs in functionality that is not critical or frequently used (Example: Customer is having trouble with configuration in the Administrative interface).
							<li>There are no extenuating circumstances that would require this issue to be resolved outside of the normal software. (Example: Customer has general questions about functionality of a particular item. Customer does not understand X in documentation and would like clarification).</li>
							<li>The problem causes little impact on your operations or a reasonable workaround for the problem has been implemented.</li>
							<li>The problem results in minimal or no interruptions to normal operations.</li>
							<li>Non-critical, Minor loss of application functionality or product Feature Request question (Example: Customer wants to know if a particular function is possible).</li>
							<li>Minor infractions including documentation or cosmetic error not impacting production.</li>
							<li>Functionality does not match documented specifications.</li>
							<li>Service enhancements requests.</li>
						</ul>
					</dd>

					<dt>Normal</dt>
					<dd>
						<p>Moderate loss of application functionality or performance resulting in multiple users impacted in their normal functions. Minor feature/product failure, convenient workaround exists/minor performance degradation/not impacting production.</p>
						<h4>Qualifying Conditions</h4>
						<ul>
							<li>System is up and running, but the problem causes non-negligible impact. Workaround exists, but it is only temporary (Example: A cron job can be triggered manually but does not run when scheduled).</li>
							<li>The software still functions in the Customer's business environment, but there are functional limitations that are not critical in the daily operation (Example: Customer is getting Resources created correctly but wants them to behave in a different manner.)</li>
							<li>Does not prevent operation of a production system or there is some degradation in performance (Example: The issue affects only users from a specific location).</li>
							<li>Moderate loss of application functionality or performance resulting in multiple users impacted in their normal functions (Examples: Some Super Groups experience performance issues due to size and complexity of the group).</li>
							<li>Important to long-term productivity (Example: Customer cannot set up a particular group).</li>
						</ul>
					</dd>

					<dt><span style="color: orange;">High</span></dt>
					<dd>
						<p>Critical loss of application functionality or performance resulting in high number of users unable to perform their normal functions. Major feature/product failure; inconvenient workaround or no workaround exists. The program is usable but severely limited.</p>
						<h4>Qualifying Conditions</h4>
						<ul>
							<li>Service interruptions to some, but not all, components (Examples: components not functional for some users but functional for others).</li>
							<li>Time sensitive issue reported by Customer, which may adversely affect business impact, monitoring or productivity (Examples: Upcoming conferences, demos and training).</li>
							<li>In a production system, important tasks cannot be performed, but the error does not impair essential operations (Example: Group approval and Registration Confirmation).</li>
						</ul>
					</dd>

					<dt><span style="color: red;">Critical</span></dt>
					<dd>
						<p>Production application down or major malfunction resulting in a product inoperative condition. Users unable to reasonably perform their normal functions.</p>
						<h4>Qualifying Conditions</h4>
						<ul>
							<li>Hub completely unusable</li>
							<li>Upgrade to a newer version of Hubzero has failed to install.</li>
							<li>No user can log into the web interface.</li>
						</ul>
					</dd>
				</dl>
			</section>
			<section>
				<h2><span>Commenting</span></h2>

				<p>Comments are visible to anyone who has access to read this ticket, including the ticket submitter, unless the comment is marked <strong>private</strong>.</p>

				<h3>Notifying others</h3>

				<p>You may send the comment to others by filling in username, user ID, or email addresses in the "Send message to" field. Any value entered here is <em>sticky</em>--that is, the value will be retained and the field pre-filled for the next comment. This makes it easy to keep the same set of people notified. All notifications are tracked in a log.</p>
			</section>
			<section>
				<h2><span>Watching</span></h2>

				<p>When watching a ticket, you will be notified of any comments added or changes made. You may stop watching at any time.</p>
			</section>
		</article>