<?php
/**
 * HUBzero CMS
 *
 * Copyright 2005-2011 Purdue University. All rights reserved.
 *
 * This file is part of: The HUBzero(R) Platform for Scientific Collaboration
 *
 * The HUBzero(R) Platform for Scientific Collaboration (HUBzero) is free
 * software: you can redistribute it and/or modify it under the terms of
 * the GNU Lesser General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any
 * later version.
 *
 * HUBzero is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * HUBzero is a registered trademark of Purdue University.
 *
 * @package   hubzero-cms
 * @author    Christopher Smoak <csmoak@purdue.edu>
 * @copyright Copyright 2005-2011 Purdue University. All rights reserved.
 * @license   http://www.gnu.org/licenses/lgpl-3.0.html LGPLv3
 */

// Check to ensure this file is included in Joomla!
defined('_JEXEC') or die('Restricted access');
?>

<h1>Tools Sessions</h1>

<ol>
	<li>
		<a href="#renamesession">Renaming Tool Sessions</a>
	</li>
	<li>
		<a href="#sharesession">Sharing Tool Sessions</a>
	</li>
</ol>


<a name="renamesession"></a>
<h3>Renaming Tool Sessions</h3>
<p>You can rename a simulation session by simple double-clicking the session title just above the active tool area. The title will then become a text box where you can input any title you wish. Press the TAB key or ENTER key to save changes or press ESC to cancel.</p>
<img src="/components/com_tools/help/en-GB/tool-rename-session.png" />

<hr />

<a name="sharesession"></a>
<h3>Sharing Tool Sessions</h3>
<p>Have some interesting results from a simulation that you'd like someone else to see? Share the session!</p>

<p>Enter one or more login names in the form beneath the tool session and click on the Share button. Anyone added for sharing will see your tool session listed on their own My Sessions area on their my nanoHUB page. Just as you would click a link to resume a tool session, they can click the link and access your session. Many people can access a single session at the same time and discuss the results on a conference call.</p>

<p><strong>Note:</strong> If you don't want others to have control of the tool, be sure to select the Read-Only checkbox before sharing the session.</p>
<img src="/components/com_tools/help/en-GB/tool-share-session.png" />



