<?php
/**
 * @package    hubzero-cms
 * @copyright  Copyright (c) 2005-2024 The Regents of the University of California.
 * @license    http://opensource.org/licenses/MIT MIT
 */

use Hubzero\Content\Migration\Base;

// No direct access
defined('_HZEXEC_') or die();

/**
 * Migration script for adding User Secret to jos_users table
 *
 * This migration script creates a jos_users column to populate
 * with a unique user secret, on user login. On 'down' migration the column
 * is dropped from the table.
 *
 **/
class Migration20230901000000ComMembers extends Base
{
	// specify table name
	static $tableName = '#__users';

	// specify column to create
	static $columnData = [['name' => 'secret',
				'type' => 'char(32)',
				'restriction' => 'UNIQUE',
				'default' => 'NULL'],
				];

	/**
	 * Up
	 *
	 * Create 'secret' column in jos_users if needed.
	 *
	 * Note that we have logging callbacks, per
	 * https://help.hubzero.org/documentation/22/webdevs/database/migrations
	 *
	 **/
	public function up()
	{
		$tableName = self::$tableName;
		$columnData = self::$columnData;

		// Add column to jos_users table to hold user secret
		// If the table exists, add column if it is absent:
		if ($this->db->tableExists($tableName))
		{
			if (!$this->db->tableHasField($tableName, $columnData[0]['name']))
			{
				$this->log('No column `secret` found in table `jos_users`, creating...', 'info');

				// generate and run query to create column
				$query = $this->_generateSafeAddColumns($tableName, $columnData);
				$this->_queryIfTableExists($tableName, $query);

			}
			// Generate and save user secrets
			$this->generateUserSecrets();
		}
	}

	/**
	 * Down
	 *
	 * Drop 'secret' column from jos_users table.
	 *
	 **/
	public function down()
	{
		$tableName = self::$tableName;
		$columnData = self::$columnData;

		// generate query to drop column from table:
		$query = $this->_generateSafeDropColumns($tableName, $columnData);

		// execute the query, if column is found in the specified table:
		$this->_queryIfTableExists($tableName, $query);

		$this->log('Column `secret` dropped from table `jos_users`', 'info');
	}

	/**
	 * generateUserSecrets()
	 *
	 * Populate 'secret' column in jos_users table for those users who have
	 * logged in during the last year, but have no secret set. Each secret is a
	 * unique, random 32-character string.
	 *
	 **/
	private function generateUserSecrets()
	{
		$tableName = self::$tableName;
		$columnData = self::$columnData;
		$column = $columnData[0]['name'];

		// User secret is generated by taking a MD5 hash of concatenated random numbers in SQL:
		$targetUsers = "UPDATE $tableName
			SET $column = MD5(CONCAT(NOW(), RAND(), UUID()))
			WHERE $column IS NULL
			AND lastVisitDate > DATE_SUB(CURDATE(), INTERVAL 1 YEAR)";
                $this->db->setQuery($targetUsers);
                $this->db->query();

		$this->log('Saved new secrets for target users', 'info');
	}
}
