<?php
/**
 * HUBzero CMS
 *
 * Copyright 2005-2011 Purdue University. All rights reserved.
 *
 * This file is part of: The HUBzero(R) Platform for Scientific Collaboration
 *
 * The HUBzero(R) Platform for Scientific Collaboration (HUBzero) is free
 * software: you can redistribute it and/or modify it under the terms of
 * the GNU Lesser General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any
 * later version.
 *
 * HUBzero is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * HUBzero is a registered trademark of Purdue University.
 *
 * @package   hubzero-cms
 * @author    Sam Wilson <samwilson@purdue.edu>
 * @copyright Copyright 2005-2011 Purdue University. All rights reserved.
 * @license   http://www.gnu.org/licenses/lgpl-3.0.html LGPLv3
 */

// Check to ensure this file is included in Joomla!
defined('_JEXEC') or die('Restricted access');
?>

<h1>Courses Help</h1>
<p>
	The HUBzero courses platform offers many features to get you up and running, distributing online course materials and interactive content to a local classroom, or around the world. Though the platform has been designed to be simple and self-serve, there are also plenty of options to keep you busy. Follow a link below to help clear up those options, or dive deeper into the intricacies of the HUBzero courses platform!
</p>
<h2>Students</h2>
<ul>
	<li>
		<a href="<?php echo JRoute::_('index.php?option=com_help&component=courses&page=basics'); ?>">Why enroll?</a>
	</li>
</ul>
<h2>Instructors:</h2>
<h4>Building a course</h4>
<ul>
	<li>
		<a href="<?php echo JRoute::_('index.php?option=com_help&component=courses&page=builder'); ?>">Using the interactive builder</a>
	</li>
</ul>