		<article>
			<h1><span>Wish Lists: Wishes</span></h1>

			<ul class="nav">
				<li><a href="#overview">Overview</a></li>
				<li><a href="#column-headers">Column Headers</a></li>
				<li><a href="#toolbar">Toolbar</a></li>
				<li><a href="#sub-menu">Sub-menu Links</a></li>
				<li><a href="#list-filters">List Filters</a></li>
			</ul>

			<section id="overview">
				<h2><span>Overview</span></h2>

				<p>Here you will a list of "wish list".</p>
			</section>
			<section id="column-headers">
				<h2><span>Column Headers</span></h2>

				<p>Click on the column heading to sort the list by that column's value. The list will be sorted in order by that column and a sort icon will show next to the column name. Click a second time to reverse the sort to high-to-low. The sort icon will change to high-to-low.</p>

				<dl>
					<dt>Checkbox</dt>
					<dd>Check this box to select one or more items. To select all items, check the box in the column heading. After one or more boxes are checked, click a toolbar button to take an action on the selected item or items. Many toolbar actions, such as Publish and Unpublish, can work with multiple items. Others, such as Edit, only work on one item at a time. If multiple items are checked and you press Edit, the first item will be opened for editing.</dd>

					<dt>Title</dt>
					<dd>The name of the item. This entry is required. You can open the item for editing by clicking on the Title.</dd>

					<dt>Submitter</dt>
					<dd>The author of the entry.</dd>

					<dt>Submitted</dt>
					<dd>The date this post was created. This date is added automatically upon creation.</dd>

					<dt>State</dt>
					<dd>(Unpublish/Published) The published status of the item.</dd>

					<dt>Access</dt>
					<dd>Which user 'access levels' have access to this item. You can change an item's Access Level by clicking on its name to open it up for editing. The default user 'access levels' which come preconfigured are:
						<ul>
							<li>Public: Everyone has access including website visitors who have not logged in</li>
							<li>Registered: Only users with registered status or higher will have access</li>
							<li>Special: Only users with author status or higher have access</li>
						</ul>
					</dd>

					<dt>Comments</dt>
					<dd>This covers if a post has comments enabled and how many comments have been posted to that entry. Clicking the number of comments will present a list of comments for that specific post.</dd>
				</dl>
			</section>
			<section id="toolbar">
				<h2><span>Toolbar</span></h2>
				<p>At the top right you will see the toolbar.</p>
				<p>The functions are:</p>
				<dl>
					<dt>Publish</dt>
					<dd>Makes the selected posts available to visitors to the site.</dd>

					<dt>Unpublish</dt>
					<dd>Makes the selected posts unavailable to visitors to the site.</dd>

					<dt>Edit</dt>
					<dd>pens the editing screen for the selected list. If more than one list is selected (where applicable), only the first list will be opened. The editing screen can also be opened by clicking on the Title of the list.</dd>

					<dt>New</dt>
					<dd>Opens the editing screen to create a new wish list.</dd>

					<dt>Trash</dt>
					<dd>Permanently remove the selected lists and all associated content (wishes, etc.).</dd>

					<dt>Help</dt>
					<dd>Opens this help screen.</dd>
				</dl>
			</section>
			<section id="sub-menu">
				<h2><span>Sub-menu Links</span></h2>
				<p>At the top left, above the filters, you will see sub-menu options. These are essentially filters for blog posts, filtering by the primary scopes (or types) of blogs. The links are:</p>
				<dl>
					<dt>Lists</dt>
					<dd>Display a listing of created wish lists.</dd>
					<dt>Wishes</dt>
					<dd>Display a list of wishes. Typically, a <strong>list</strong> ID will be passed, filtering the list to only the wishes associated with that list.</dd>
					<dt>Comments</dt>
					<dd>Display a list of comments. Typically, a <strong>wish</strong> ID will be passed, filtering the list to only the comments associated with that wish.</dd>
				</dl>
			</section>
			<section id="list-filters">
				<h2><span>List Filters</span></h2>
				<p>The list of "wish list" which appears on this screen may be very large. You can use one of the available filters or any combination of them to limit the number of entries displayed to just the wish lists which match your filter parameters.</p>

				<dl>
					<dt>Search</dt>
					<dd>Above the column headers is a search box for filtering results by a keyword or phrase..</dd>
					<dt>State</dt>
					<dd>Display only those wish lists that are associated to a specific state.</dd>
				</dl>
				<p>Click Clear to clear the Filter field and restore the list to its unfiltered state.</p>

				<h3>Page Controls</h3>
				<p>When the number of items is more than one page, you will see a page control bar as shown below.</p>

				<dl>
					<dt>Display #</dt>
					<dd>Select the number of items to show on one page.</dd>
					<dt>Start</dt>
					<dd>Click to go to the first page.</dd>
					<dt>Prev</dt>
					<dd>Click to go to the previous page.</dd>
					<dt>Page numbers</dt>
					<dd>Click to go to the desired page.</dd>
					<dt>Next</dt>
					<dd>Click to go to the next page.</dd>
					<dt>End</dt>
					<dd>Click to go to the last page.</dd>
				</dl>
			</section>
		</article>