<article>
	<h1><span>Article Manager: Options</span></h1>

	<ul class="nav">
		<li><a href="#overview">Overview</a></li>
	</ul>

	<section id="overview">
		<h2><span class="mw-headline" id="Description">Description</span></h2>
		<p>The Article Manager options</p>
	</section>

	<section>
					<h5 class="subtitle"></h5>
					<div class="clear_both"></div>
					<div class="mw-bodytext">
						<div id="mw-content-text" lang="en" dir="ltr" class="mw-content-ltr"><div class="hf-nsheader"></div><div class="hf-header"></div><div style="position:relative; z-index:10; float:right; margin:0 0 1em 1em; max-width:100%;">
<div id="toc" class="toc">
<div id="toctitle">
<h2>Contents</h2>
</div>
<ul>
<li class="toclevel-1 tocsection-1"><a href="#How_To_Access"><span class="tocnumber">1</span> <span class="toctext">How To Access</span></a></li>
<li class="toclevel-1 tocsection-2"><a href="#Description"><span class="tocnumber">2</span> <span class="toctext">Description</span></a></li>
<li class="toclevel-1 tocsection-3"><a href="#Screenshot"><span class="tocnumber">3</span> <span class="toctext">Screenshot</span></a></li>
<li class="toclevel-1 tocsection-4"><a href="#Toolbar"><span class="tocnumber">4</span> <span class="toctext">Toolbar</span></a></li>
<li class="toclevel-1 tocsection-5"><a href="#Form_Fields"><span class="tocnumber">5</span> <span class="toctext">Form Fields</span></a>
<ul>
<li class="toclevel-2 tocsection-6"><a href="#Articles_Options"><span class="tocnumber">5.1</span> <span class="toctext">Articles Options</span></a></li>
<li class="toclevel-2 tocsection-7"><a href="#Editing_Layout_Options"><span class="tocnumber">5.2</span> <span class="toctext">Editing Layout Options</span></a></li>
<li class="toclevel-2 tocsection-8"><a href="#Category_Options"><span class="tocnumber">5.3</span> <span class="toctext">Category Options</span></a></li>
<li class="toclevel-2 tocsection-9"><a href="#Categories_Options"><span class="tocnumber">5.4</span> <span class="toctext">Categories Options</span></a></li>
<li class="toclevel-2 tocsection-10"><a href="#Blog_.2F_Featured_Layout_Options"><span class="tocnumber">5.5</span> <span class="toctext">Blog / Featured Layout Options</span></a></li>
<li class="toclevel-2 tocsection-11"><a href="#List_Layout_Options"><span class="tocnumber">5.6</span> <span class="toctext">List Layout Options</span></a></li>
<li class="toclevel-2 tocsection-12"><a href="#Shared_Options"><span class="tocnumber">5.7</span> <span class="toctext">Shared Options</span></a></li>
<li class="toclevel-2 tocsection-13"><a href="#Integration_Options"><span class="tocnumber">5.8</span> <span class="toctext">Integration Options</span></a></li>
<li class="toclevel-2 tocsection-14"><a href="#Permissions"><span class="tocnumber">5.9</span> <span class="toctext">Permissions</span></a></li>
</ul>
</li>
<li class="toclevel-1 tocsection-15"><a href="#Quick_Tips"><span class="tocnumber">6</span> <span class="toctext">Quick Tips</span></a></li>
<li class="toclevel-1 tocsection-16"><a href="#Related_Information"><span class="tocnumber">7</span> <span class="toctext">Related Information</span></a></li>
</ul>
</div>
</div>
<p>Global default settings for menu types which display articles in different layouts and formats.</p>
<h2><span class="mw-headline" id="How_To_Access">How To Access</span></h2>
<p>To access this screen:</p>
<ul>
<li>Navigate to the <a href="/Help25:Content_Article_Manager" title="Help25:Content Article Manager">Article Manager</a> screen, then</li>
<li>Click the <b>Options</b> toolbar button. This opens the Article Manager Options screen in a modal window.</li>
</ul>
<h2><span class="mw-headline" id="Description">Description</span></h2>
<p>This screen is where you can set global defaults for menu items that display articles. These default values will be used when you select "Use Global" for an option in an Articles menu item. For example, if you normally want to show the Create Date for an article in your Articles menu items, then set that option to "Show" here and it will be the default value. You do <i>not</i> need to set any of these options. Your Joomla site will work with the default settings.</p>
<p>Article options are divided into nine groups as follows. Each controls the appearance of the listed type of layout.</p>
<ul>
<li><b>Articles:</b> Articles in Single Article or blog layouts.</li>
<li><b>Editing Layout:</b> Front-end article add/edit layout.</li>
<li><b>Category:</b> Single Category layouts -- for example, when you click on a category to view the articles it contains.</li>
<li><b>Categories:</b> Articles Categories layout.</li>
<li><b>Blog/Featured Layouts:</b> Featured and Category Blog Layout.</li>
<li><b>List Layouts:</b> Category List Layout.</li>
<li><b>Shared Options:</b> Shared options for list, blog, and featured layouts.</li>
<li><b>Integration:</b> Feed Link and Read More options.</li>
<li><b>Permissions:</b> ALC permissions for actions on articles.</li>
</ul>
<h2><span class="mw-headline" id="Toolbar">Toolbar</span></h2>
<p>At the top right of the Options modal window you will see the toolbar.</p>
<p>The functions are:</p>
<ul>
<li><b>Save.</b> Saves any changed options and keeps the window open. Use this, for example, to see the effect of Permissions changes you have made.</li>
<li><b>Save &amp; Close.</b> Saves any changed options and closes the modal window.</li>
<li><b>Cancel.</b> Closes the modal window without saving any changes.</li>
</ul>
<h2><span class="mw-headline" id="Form_Fields">Form Fields</span></h2>
<h3><span class="mw-headline" id="Articles_Options">Articles Options</span></h3>
<p>Article Options control how an article will show in a Single Article menu item or, in some cases, in a Blog menu item.</p>
<ul>
<li><b>Choose a layout.</b> If you have defined any alternative layouts for articles, you may choose one of them from the list to be the default value for Single Article menu items.</li>
<li><b>Show Title.</b> (Hide/Show). Hide or Show the article title.</li>
</ul>
<ul>
<li><b>Linked Titles.</b> (Use Global/No/Yes). If the Article's Title is shown, whether to show it as a link to the article.</li>
</ul>
<ul>
<li><b>Show Intro Text.</b> (Hide/Show) Hide or Show an Article's Intro Text when the 'Read more...' link is selected. Intro Text is the part of the Article before a 'Read more...' break. If this parameter is 'Show', when the User selects the 'Read more...' link, the entire article will display, including the Intro Text. If this parameter is 'Hide', when the User selects the 'Read more...' link, only the part of the Article after the 'Read more...' link will display.</li>
</ul>
<ul>
<li><b>Show Category.</b> (Use Global/Hide/Show). Whether or not to show the Article's Category.</li>
<li><b>Link Category.</b> (No/Yes). If the category title is shown, whether or not to show it as a link to a Single Category menu item for the category. Note that you can set this to be either a blog or list layout with the "Choose a layout" option in the Category Options.</li>
<li><b>Show Parent.</b> (Hide/Show). Hide or Show the title of the parent category of the article's category. This is provided for backward compatibility to the role of Sections in Joomla version 1.5.</li>
<li><b>Link Parent.</b> (No/Yes). If the parent category is shown, whether or not to show it as a link to a Single Category menu item for the category. Note that you can set this to be either a blog or list layout with the "Choose a layout" option in the Category Options.</li>
</ul>
<ul>
<li><b>Show Author.</b> (Use Global/Hide/Show) Whether to show the author of the Article.</li>
<li><b>Link Author.</b> (No/Yes). If the author is shown, whether or not to show it as a link to the Joomla user. Note that this will only show as a link if there is a Contact associated with this user. Also, a link will not show if there is an Author Alias value for the article.</li>
<li><b>Show Create Date.</b> (Hide/Show). Hide or show the article's create date.</li>
<li><b>Show Modify Date.</b> (Hide/Show). Hide or show the date the article was last modified.</li>
<li><b>Show Publish Date.</b> (Hide/Show). Hide or show the article's published date.</li>
<li><b>Show Navigation.</b> (Hide/Show). Hide or Show a navigation link (e.g., Next, Previous) between articles.</li>
<li><b>Show Voting.</b> (Hide/Show). Hide or Show a voting button for the article. This allows users to vote for an article.</li>
</ul>
<ul>
<li><b>Show "Read More".</b> (Hide/Show) Whether or not to show the "Read More..." link to link from the part of the article before the "Read More..." break to the rest of the Article.</li>
</ul>
<ul>
<li><b>Show Title with Read More.</b> (Hide/Show) Whether or not to show the article title as part of the Read More link. If set to Show, the Read More link will be in the format "Read More: &lt;article title&gt;". If set to Hide, the Read More link will be "Read more...".</li>
</ul>
<ul>
<li><b>Read More Limit.</b> If the title is included with the Read More text, the maximum number of characters from the title to include. This can prevent the Read More text to become excessively long if the article has a very long title.</li>
<li><b>Show Icons.</b> (Hide/Show). Hide or Show icons for the print and email buttons. If Show, and if the print or email icons are set to show, these will show as icons instead of text links.</li>
<li><b>Show Print Icon.</b> (Hide/Show). Hide or Show a button or link to allow printing the article.</li>
<li><b>Show Email Icon.</b> (Hide/Show). Hide or Show a button or link to allow emailing the article.</li>
</ul>
<ul>
<li><b>Show Hits.</b> (Use Global/Hide/Show). Show or Hide the number of times the article has been hit (displayed by a user).</li>
<li><b>Show Unauthorised Links.</b> (Hide/Show). If set to Show, the Intro Text for restricted articles will show. Clicking on the "Read More" link will require users to log in to view the full article content. If set to Hide, articles that the user is not authorised to view (based on the viewing access level for the article) will not show.</li>
<li><b>Positioning of the Links.</b> (Above/Below). If there are links associated with this article, whether to show them above or below the article.</li>
</ul>
<h3><span class="mw-headline" id="Editing_Layout_Options">Editing Layout Options</span></h3>
<ul>
<li><b>Show Publishing Options.</b> (No/Yes). If No, the Publishing Options slider in the <a href="/Help25:Content_Article_Manager_Edit" title="Help25:Content Article Manager Edit">Article Manager: Add/Edit Screen</a> will not show. This means that back-end users will not be able to edit the fields Created by, Created by alias, Created Date, Start Publishing, or Finish Publishing. These fields will always be set to their default values.</li>
<li><b>Show Article Options.</b> (No/Yes). If No, the Article Options slider in the <a href="/Help25:Content_Article_Manager_Edit" title="Help25:Content Article Manager Edit">Article Manager: Add/Edit Screen</a> will not show. This means that back-end users will not be able to edit the fields in this slider. These fields will always be set to their default values.</li>
<li><b>Frontend Images and Links.</b> (No/Yes). If Yes, the Images and Links fields will show in the Front End article editor screen. These fields allow users to optionally enter two images and three links in an easy-to-use form in the front end. When used with a single-article override, this can allow the site administrator to create a simple form for users to create standard article layouts.</li>
<li><b>Administrator Images and Links.</b> (No/Yes). If Yes, the Images and Links slider will show in the <a href="/Help25:Content_Article_Manager_Edit" title="Help25:Content Article Manager Edit">Article Manager: Add/Edit Screen</a>.</li>
<li><b>URL A Target Window.</b> Sets the default value for the target for the first Link in the article. Choices are:
<ul>
<li><i>Open in parent window:</i> Opens the in the main browser window, replacing the current Joomla article.</li>
<li><i>Open in new window:</i> Opens the link in a new browser window.</li>
<li><i>Open in pop up:</i> Opens the link in a pop-up browser window (without full navigation controls).</li>
<li><i>Modal:</i> Opens the link in a modal pop-up window.</li>
</ul>
</li>
<li><b>URL B Target Window.</b> Sets the default value for the target for the second Link in the article. Same options as URL A.</li>
<li><b>URL C Target Window.</b> Sets the default value for the target for the third Link in the article. Same options as URL A.</li>
<li><b>Intro Image Float.</b> (Right/Left/None). Sets the float attribute for an Intro Image selected in the Into Image field.</li>
<li><b>Full Text Image Float.</b> (Right/Left/None). Sets the float attribute for an Intro Image selected in the Into Image field.</li>
</ul>
<h3><span class="mw-headline" id="Category_Options">Category Options</span></h3>
<p>Category Options control how articles will show when you drill down to a Category to view its articles.</p>
<ul>
<li><b>Choose a layout.</b> (Blog/List/user defined). This lets you select the default layout to show when you click on a Category link. If you create an alternative layout for a category layout, you may select that as the default.</li>
<li><b>Category Title.</b> (Hide/Show) Hide or Show the title of the category.</li>
<li><b>Category Description.</b> (Hide/Show) Hide or Show the description for the category.</li>
<li><b>Category Image.</b> (Hide/Show) Hide or Show the category image.</li>
<li><b>Subcategory Levels.</b> (None/All/1-5). Categories in Joomla can be created in a hierarchy. This lets you control how many levels of subcategories to show when showing a category view.</li>
<li><b>Empty Categories.</b> (Hide/Show) Hide or Show categories that don't contain any articles or subcategories.</li>
<li><b>No Articles Message.</b> (Hide/Show) If Show, and if Empty Categories is Show, a message "There are no articles in this category" will show if a category contains no articles.</li>
<li><b>Subcategories Descriptions.</b> (Hide/Show) Hide or Show the descriptions for subcategories that are shown.</li>
<li><b># Articles in Category.</b> (Hide/Show) Hide or Show a count of the total number of articles in each category.</li>
</ul>
<h3><span class="mw-headline" id="Categories_Options">Categories Options</span></h3>
<p>Categories Options control the display of the List All Categories menu item.</p>
<ul>
<li><b>Top Level Category Description.</b> (Hide/Show). Hide or Show the description of the top-level category.</li>
<li><b>Subcategory Levels.</b> (All/1-5). How many levels in the hierarchy to show.</li>
<li><b>Empty Categories.</b> (Hide/Show). Hide or Show categories that contain no articles and no subcategories.</li>
<li><b>Subcategories Descriptions.</b> (Hide/Show). Hide or Show the description of each subcategory.</li>
<li><b># Articles in Category.</b> (Hide/Show). Hide or Show a count of the total number of articles in each category.</li>
</ul>
<h3><span class="mw-headline" id="Blog_.2F_Featured_Layout_Options">Blog / Featured Layout Options</span></h3>
<p>These options control the layout of the Category Blog and Featured Articles layouts.</p>
<ul>
<li><b># Leading Articles.</b> Number of Articles to show using the full width of the main display area. "0" means that no Articles will show when using the full width. If an Article has a "Read more..." break, only the part of the text before the break (the Intro text) will display.</li>
<li><b># Intro Articles.</b> Determines the number of Articles to display after the leading Article. These Articles will display in the number of columns set in the Columns parameter below. If an Article has a "Read more..." break, only the text before the break (Intro text) will display, followed by a "Read more..." link. The order order in which to display the articles is determined by the Category Order and Article Order parameters below.</li>
<li><b># Columns.</b> The number of columns to use in the Intro Text area. This is normally between 1 and 3 (depending on the template you are using). If 1 is used, the Into Text Articles will display using the full width of the display area, just like the Leading Articles.</li>
<li><b># Links.</b> The number of Links to display in the 'Links' area of the page. These links allow a User to link to additional Articles, if there are more Articles than can fit on the first page of the Blog Layout.</li>
<li><b>Multi Column Order.</b> In multi-column blog layouts, whether to order articles Down the columns or Across the columns.
<ul>
<li><i>Down:</i> Order articles going down the first column and then over to the next column, for example:</li>
</ul>
</li>
</ul>
<dl>
<dd>
<dl>
<dd>
<table class="wikitable">
<tr>
<td>article 1</td>
<td>1 (continued)</td>
</tr>
<tr>
<td>article 2</td>
<td>article 4</td>
</tr>
<tr>
<td>article 3</td>
<td>article 5</td>
</tr>
</table>
</dd>
</dl>
</dd>
</dl>
<dl>
<dd>
<ul>
<li><i>Across:</i> Order articles going across the columns and then back to the first column, for example:</li>
</ul>
</dd>
</dl>
<dl>
<dd>
<dl>
<dd>
<table class="wikitable">
<tr>
<td>article 1</td>
<td>1 (continued)</td>
</tr>
<tr>
<td>article 2</td>
<td>article 3</td>
</tr>
<tr>
<td>article 4</td>
<td>article 5</td>
</tr>
</table>
</dd>
</dl>
</dd>
</dl>
<ul>
<li><b>Include Subcategories.</b> (None/All/1-5). If None, only articles from the current category will show. If 1-5, all articles from the current category and subcategories up to and including that level will show. If All, all articles from the current category and all subcategories will show.</li>
</ul>
<h3><span class="mw-headline" id="List_Layout_Options">List Layout Options</span></h3>
<p>These options control the appearance of the Category List layout.</p>
<ul>
<li><b>Display Select.</b> (Hide/Show) Whether to hide or show the Display # control that allows the user to select the number of items to show in the list.
If there are more items than this number, you can use the page navigation buttons (Start, Prev, Next, End, and page numbers) to navigate between pages. Note that if you have a large number of items, it may be helpful to use the Filter options, located above the column headings, to limit which items display.</li>
<li><b>Filter Field.</b> The Filter Field creates a text field where a user can enter a field to be used to filter the articles shown in the list.
</li>
</ul>
<dl>
<dd>The possible options for this (in the back-end menu item edit) are shown below.
<ul>
<li><i>Hide:</i> Don't show a filter field.</li>
<li><i>Title:</i> Filter on article title.</li>
<li><i>Author:</i> Filter on the author's name.</li>
<li><i>Hits:</i> Filter on the number of article hits.</li>
</ul>
</dd>
</dl>
<ul>
<li><b>Table Headings.</b> (Hide/Show) Table Headings show a heading above the article list.
If set to <i>Show</i>, this heading will show about the list. Otherwise the list will show with no headings.</li>
<li><b>Show Date.</b> This option allows you to show a date in the list. The options are as follows.
</li>
</ul>
<dl>
<dd>
<ul>
<li><i>Hide:</i> Don't show any date.</li>
<li><i>Created:</i> Show the created date.</li>
<li><i>Modified:</i> Show the date of the last modification.</li>
<li><i>Created:</i> Show the start publishing date.</li>
</ul>
</dd>
</dl>
<ul>
<li><b>Date Format.</b> Optional format string to control the format of the date (if shown). If left blank, the date will use the DATE_FORMAT_LC1 format from the language file (for example, "D M Y" for "31 December 2012" or "m-d-y" for "12-31-12"). See <a rel="nofollow" target="_blank" class="external text" href="http://www.php.net/manual/en/function.date.php">PHP Date Documentation</a> for more information.</li>
<li><b>Show Hits in List.</b> (Hide/Show) Whether to hide or show the number of hits for this item.</li>
<li><b>Show Author in List.</b> (Hide/Show) Whether to hide or show the name of the author.</li>
</ul>
<h3><span class="mw-headline" id="Shared_Options">Shared Options</span></h3>
<p>These options are shared by a number of the articles menu item types.</p>
<ul>
<li><b>Category Order.</b> Order of Categories in this Layout. The following options are available.
<ul>
<li><i>No Order:</i> Articles are ordered only by the Article Order, without regard to Category.</li>
<li><i>Title Alphabetical:</i> Categories are displayed in alphabetical order (A to Z)</li>
<li><i>Title Reverse Alphabetical:</i> Categories are displayed in reverse alphabetical order (Z to A)</li>
<li><i>Category Manager Order:</i> Categories are ordered according to the Order column entered in the <a href="/Help25:Components_Content_Categories" title="Help25:Components Content Categories">Category Manager</a>.</li>
</ul>
</li>
<li><b>Article Order.</b> Order of articles in this Layout. The following options are available.
<ul>
<li><i>Most recent first:</i> Articles are displayed starting with the most recent and ending with the oldest.</li>
<li><i>Oldest first:</i> Articles are displayed starting with the oldest and ending with the most recent.</li>
<li><i>Title Alphabetical:</i> Articles are displayed by Title in alphabetical order (A to Z)</li>
<li><i>Title Reverse Alphabetical:</i> Articles are displayed by Title in reverse alphabetical order (Z to A)</li>
<li><i>Author Alphabetical:</i> Articles are displayed by Author in alphabetical order (A to Z)</li>
<li><i>Author Reverse Alphabetical:</i> Articles are displayed by Author in reverse alphabetical order (Z to A)</li>
<li><i>Most Hits:</i> Articles are displayed by the number of hits, starting with the one with the most hits and ending with the one with the least hits</li>
<li><i>Least Hits:</i> Articles are displayed by the number of hits, starting with the one with the least hits and ending with the one with the most hits</li>
<li><i>Ordering:</i> Articles are ordered according to the Order column entered in the <a href="/Help25:Content_Article_Manager" title="Help25:Content Article Manager">Article Manager</a>.</li>
</ul>
</li>
<li><b>Date for Ordering.</b> The date used when articles are sorted by date. The following options are available.
<ul>
<li><i>Created:</i> Use the article created date.</li>
<li><i>Modified:</i> Use the article modified date.</li>
<li><i>Published:</i> Use the article start publishing date.</li>
</ul>
</li>
<li><b>Pagination.</b> Hide or Show Pagination support. Pagination provides page links at the bottom of the page that allow the User to navigate to additional pages. These are needed if the Articles will not fit on one page.
The following options are available.
<ul>
<li><i>Auto:</i> Pagination links shown if needed.</li>
<li><i>Show:</i> Pagination links shown if needed.</li>
<li><i>Hide:</i> Pagination links not shown. Note: In this case, Users will not be able to navigate to additional pages.</li>
</ul>
</li>
<li><b>Pagination Results.</b> Hide or Show the current page number and total pages (e.g., "Page 1 of 2") at the bottom of each page.</li>
</ul>
<h3><span class="mw-headline" id="Integration_Options">Integration Options</span></h3>
<p>These options control the display of news feeds.</p>
<ul>
<li><b>Show Feed Link.</b> (Hide/Show) Whether to Hide or Show a link to a news feed (RSS Feed). If set to Show, a Feed Link will show up as a feed icon in the address bar of most modern browsers).</li>
<li><b>For each feed item show.</b> (Intro Text/Full Text) If Intro Text, only the article's intro text will show in the feed. Otherwise, the entire text of the article will show.</li>
<li><b>Show "Read More".</b> (Hide/Show) Hide or Show a "Read more" link in the newsfeed.</li>
</ul>
<h3><span class="mw-headline" id="Permissions">Permissions</span></h3>
<p>This section lets you set up the default ACL permissions for all articles in all categories. These permissions may be overridden for specific categories and for specific articles.</p>
<p>To change the permissions, do the following.</p>
<ol>
<li>Select the Group by clicking its title.</li>
<li>Find the desired Action. Possible Actions are:
<dl>
<dd><i>Configure.</i> Users can access this screen (<strong class="selflink">Article Manager→Options</strong>).</dd>
<dd><i>Access Administrative Interface.</i> Users can access the <a href="/Help25:Content_Article_Manager" title="Help25:Content Article Manager">Article Manager</a>.</dd>
<dd><i>Create.</i> Users can create new articles.</dd>
<dd><i>Delete.</i> Users can delete articles.</dd>
<dd><i>Edit.</i> Users can edit the contents of articles.</dd>
<dd><i>Edit State.</i> User can change the published state and related information for articles.</dd>
<dd><i>Edit Own.</i> User can edit the content or published state for articles that this user created.</dd>
</dl>
</li>
<li>Select the desired permission for the action you wish to change. Possible settings are:
<dl>
<dd><i>Inherited.</i> Inherited for users in this Group from <a href="/Help25:Site_Global_Configuration" title="Help25:Site Global Configuration">Global Configuration</a>.</dd>
<dd><i>Allowed.</i> Allowed for users in this Group. Note that, if this action is Denied at one of the higher levels, the Allowed permission here will not take effect. A Denied setting cannot be overridden.</dd>
<dd><i>Denied.</i> Denied for users in this Group.</dd>
</dl>
</li>
<li>Click Save. When the screen refreshes, the Calculated Setting column will show the effective permission for this Group and Action.</li>
</ol>
<h2><span class="mw-headline" id="Quick_Tips">Quick Tips</span></h2>
<ul>
<li>If you are a beginning user, you can just keep the default values here until you learn more about using global options.</li>
<li>If you are an advanced user, you can save time by creating good default values here. When you set up menu items and create articles, you will be able to accept the default values for most options.</li>
<li>All values set here can be overridden at the menu item, category, or article level.</li>
</ul>
<h2><span class="mw-headline" id="Related_Information">Related Information</span></h2>
<ul>
<li>To create and edit articles and article categories: <a href="/Help25:Content_Article_Manager" title="Help25:Content Article Manager">Article Manager</a></li>
<li>For more information about Joomla's ACL system: <a href="/Access_Control_List/1.6-2.5/Tutorial" title="Access Control List/1.6-2.5/Tutorial" class="mw-redirect">ACL Tutorial</a></li>
</ul>
	</section>
</article>