#!/bin/sh
#
# Copyright 2005-2009 by Purdue Research Foundation, West Lafayette, IN 47906.
# All rights reserved.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License,
# Version 2 as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#

if [ -f /usr/lib/mw/bin/maxwell ] ; then
cd /var/lib/mw
exec /usr/lib/mw/bin/maxwell $*
else
if [ -f /opt/mw/bin/maxwell ] ; then
cd /var/lib/mw
exec /opt/mw/bin/maxwell $*
else
cd /var/lib/narwhal
exec /opt/narwhal/narwhal $*
fi
fi
