<article>
	<h1><span>Citations Manager: Citations</span></h1>

	<ul class="nav">
		<li><a href="#overview">Overview</a></li>
		<li><a href="#column-headers">Column Headers</a></li>
		<li><a href="#toolbar">Toolbar</a></li>
		<li><a href="#sub-menu">Sub-menu Links</a></li>
		<li><a href="#list-filters">List Filters</a></li>
	</ul>

	<section id="overview">
		<h2><span>Overview</span></h2>

		<p>Here you will a list of citation entries.</p>
	</section>
	<section id="column-headers">
		<h2><span>Column Headers</span></h2>

		<p>Click on the column heading to sort the list by that column's value. The list will be sorted in order by that column and a sort icon will show next to the column name. Click a second time to reverse the sort to high-to-low. The sort icon will change to high-to-low.</p>

		<dl>
			<dt>Checkbox</dt>
			<dd>Check this box to select one or more items. To select all items, check the box in the column heading. After one or more boxes are checked, click a toolbar button to take an action on the selected item or items. Many toolbar actions, such as Publish and Unpublish, can work with multiple items. Others, such as Edit, only work on one item at a time. If multiple items are checked and you press Edit, the first item will be opened for editing.</dd>

			<dt>Type</dt>
			<dd>The type the citation is for.</dd>

			<dt>Title/Author(s)</dt>
			<dd>The title and list of authors for the item. You can open the item for editing by clicking on the Title.</dd>

			<dt>Year</dt>
			<dd>The year of the item being cited (e.g., publication year).</dd>

			<dt>Affiliated</dt>
			<dd>Indicates if the entry is from an organization affiliated with the hub.</dd>

			<dt>Funded by</dt>
			<dd>Who funded the work behind the citation.</dd>
		</dl>
	</section>
	<section id="toolbar">
		<h2><span>Toolbar</span></h2>
		<p>At the top right you will see the toolbar.</p>
		<p>The functions are:</p>
		<dl>
			<dt>Options</dt>
			<dd>Opens the Options window where settings such as default parameters or permissions can be edited.</dd>

			<dt>New</dt>
			<dd>Opens the editing screen to create a new entry.</dd>

			<dt>Edit</dt>
			<dd>Opens the editing screen for the selected entry. If more than one entry is selected (where applicable), only the first entry will be opened. The editing screen can also be opened by clicking on the Name of the entry.</dd>

			<dt>Trash</dt>
			<dd>Permanently removes the selected entries and any associated content.</dd>

			<dt>Help</dt>
			<dd>Opens this help screen.</dd>
		</dl>
	</section>
	<section id="sub-menu">
		<h2><span>Sub-menu Links</span></h2>
		<p>At the top left, above the filters, you will see sub-menu options. The links are:</p>
		<dl>
			<dt>Citations</dt>
			<dd>A list of citations.</dd>
			<dt>Stats</dt>
			<dd>Basic statistics about the entries.</dd>
			<dt>Types</dt>
			<dd>The types of materials that can be cited.</dd>
			<dt>Sponsors</dt>
			<dd>Sponsors that can be associated with citations.</dd>
			<dt>Format</dt>
			<dd>Specify the format citations should appear in (e.g., APA, IEEE).</dd>
		</dl>
	</section>
	<section id="list-filters">
		<h2><span>List Filters</span></h2>

		<p>Above the column headers is a search box for filtering results by a keyword or phrase.</p>
		<p>A select box is also available for determining the sort order of entries displayed.</p>

		<h3>Page Controls</h3>
		<p>When the number of items is more than one page, you will see a page control bar as shown below.</p>

		<dl>
			<dt>Display #</dt>
			<dd>Select the number of items to show on one page.</dd>
			<dt>Start</dt>
			<dd>Click to go to the first page.</dd>
			<dt>Prev</dt>
			<dd>Click to go to the previous page.</dd>
			<dt>Page numbers</dt>
			<dd>Click to go to the desired page.</dd>
			<dt>Next</dt>
			<dd>Click to go to the next page.</dd>
			<dt>End</dt>
			<dd>Click to go to the last page.</dd>
		</dl>
	</section>
</article>