<article>
	<h1><span>Citations Manager: Edit Citation</span></h1>

	<ul class="nav">
		<li><a href="#overview">Overview</a></li>
		<li><a href="#toolbar">Toolbar</a></li>
		<li><a href="#details">Citaiton Sponsor</a></li>
	</ul>

	<section id="description">
		<h2><span>Description</span></h2>
		<p>This is where you can add a new sponsoror edit an existing Sponsor.</p>
	</section>
	<section id="toolbar">
		<h2><span>Toolbar</span></h2>
		<p>At the top right you will see the toolbar.</p>
		<p>The functions are:</p>
		<dl>
			<dt>Save &amp; Close</dt>
			<dd>Save changes and return to the listing of entries.</dd>

			<dt>Cancel</dt>
			<dd>Discard any changes made and return to the listing of entries.</dd>

			<dt>Help</dt>
			<dd>Opens this help screen.</dd>
		</dl>
	</section>
	<section id="details">
		<h2><span>Citation Sponsor</span></h2>

		<dl>
			<dt>Name</dt>
			<dd>The Title for this item.</dd>

			<dt>Link</dt>
			<dd>A link for the sponsor.</dd>

			<dt>Image</dt>
			<dd>An image associated witht he sponsor. This is typically a logo.</dd>
		</dl>
	</section>
</article>