<?php
/**
 * HUBzero CMS
 *
 * Copyright 2005-2011 Purdue University. All rights reserved.
 *
 * This file is part of: The HUBzero(R) Platform for Scientific Collaboration
 *
 * The HUBzero(R) Platform for Scientific Collaboration (HUBzero) is free
 * software: you can redistribute it and/or modify it under the terms of
 * the GNU Lesser General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any
 * later version.
 *
 * HUBzero is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * HUBzero is a registered trademark of Purdue University.
 *
 * @package   hubzero-cms
 * @author    Christopher Smoak <csmoak@purdue.edu>
 * @copyright Copyright 2005-2011 Purdue University. All rights reserved.
 * @license   http://www.gnu.org/licenses/lgpl-3.0.html LGPLv3
 */

// Check to ensure this file is included in Joomla!
defined('_JEXEC') or die('Restricted access');
?>

<h1>Tags FAQs</h1>

<ol>
	<li>
		<a href="#whataretags">What are tags?</a>
	</li>
	<li>
		<a href="#createtags">How do I create a new tag?</a>
	</li>
	<li>
		<a href="#deletetags">How can I delete a tag?</a>
	</li>
	<li>
		<a href="#removetag">How can I remove a tag from a resource/group/my profile/etc?</a>
	</li>
	<li>
		<a href="#taglimit">Is there a limit on the number of tags I can add to an item?</a>
	</li>
	<li>
		<a href="#whotagged">Can I tell who's tagged another member's content?</a>
	</li>
</ol>


<a name="whataretags"></a>
<h3>What are tags?</h3>
<p>Tags are like keywords or category labels. Tags help you find content, events, and members which have something in common or similar interests. Tags can be added to groups, your profile, resources, wiki pages, and events.</p>

<hr />

<a name="createtags"></a>
<h3>How do I create a new tag?</h3>
<p>When creating or editing content, your profile, groups, etc. you can add or remove tags as you wish. If a tag doesn't already exist, simply typing it in a "Tags" form field will create it and make it available for everyone to use.</p>

<hr />

<a name="deletetags"></a>
<h3>How can I delete a tag?</h3>
<p>You can't. Tags can only be deleted by the site administrators. You may only remove tags from a piece of content or profile.</p>

<hr />

<a name="removetag"></a>
<h3>How can I remove a tag from a resource/group/my profile/etc?</h3>
<p>When editing content, your profile, groups, etc. you can remove tags by simply deleting them from the list presented in the "Tags" form field.</p>

<hr />

<a name="taglimit"></a>
<h3>Is there a limit on the number of tags I can add to an item?</h3>
<p>No. You should be able to add as many tags as you want to taggable content/profiles.</p>

<hr />

<a name="whotagged"></a>
<h3>Can I tell who's tagged another member's content?</h3>
<p>No. Who tagged an item and what tags they added is currently not available to users.</p>