<article>
	<h1><span>Store Manager: Items</span></h1>

	<ul class="nav">
		<li><a href="#overview">Overview</a></li>
		<li><a href="#column-headers">Column Headers</a></li>
		<li><a href="#toolbar">Toolbar</a></li>
		<li><a href="#sub-menu">Sub-menu Links</a></li>
		<li><a href="#list-filters">List Filters</a></li>
	</ul>

	<section id="overview">
		<h2><span>Overview</span></h2>

		<p>Here you will a list of citation entries.</p>
	</section>
	<section id="column-headers">
		<h2><span>Column Headers</span></h2>

		<p>Click on the column heading to sort the list by that column's value. The list will be sorted in order by that column and a sort icon will show next to the column name. Click a second time to reverse the sort to high-to-low. The sort icon will change to high-to-low.</p>

		<dl>
			<dt>ID</dt>
			<dd>This is a unique identification number for this item assigned automatically by the system. It is used to identify the item internally and cannot be changed. When creating a new item, this field is 0 until the entry is saved, at which point a new ID is assigned to it.</dd>

			<dt>Category</dt>
			<dd>The category the item can be found in.</dd>

			<dt>Title</dt>
			<dd>The name of the item. This entry is required. You can open the item for editing by clicking on the Title.</dd>

			<dt>Description</dt>
			<dd>A short description of the item.</dd>

			<dt>Price</dt>
			<dd>The price (without denomination) of the item.</dd>

			<dt>Times Ordered</dt>
			<dd>The number of times this item has been ordered.</dd>

			<dt>In Stock</dt>
			<dd>An indicator of if the item is in stock or not.</dd>

			<dt>Published</dt>
			<dd>The published status of the item.</dd>
		</dl>
	</section>
	<section id="toolbar">
		<h2><span>Toolbar</span></h2>
		<p>At the top right you will see the toolbar. The functions are:</p>
		<dl>
			<dt>Options</dt>
			<dd>Opens the Options window where settings such as default parameters or permissions can be edited.</dd>

			<dt>New</dt>
			<dd>Opens the editing screen to create a new entry.</dd>

			<dt>Help</dt>
			<dd>Opens this help screen.</dd>
		</dl>
	</section>
	<section id="sub-menu">
		<h2><span>Sub-menu Links</span></h2>
		<p>At the top left, above the filters, you will see sub-menu options. The links are:</p>
		<dl>
			<dt>Orders</dt>
			<dd>A list of orders and their status.</dd>
			<dt>Store Items</dt>
			<dd>Manage items available in the store.</dd>
		</dl>
	</section>
	<section id="list-filters">
		<h2><span>List Filters</span></h2>

		<p>Above the column headers are two select boxes for:</p>
		<ol>
			<li><strong>Filter by</strong>: options for narrowing the list of items to make finding entries easier.</li>
			<li><strong>Sort by</strong>: options for how the list of items is sorted.</li>
		</ol>

		<h3>Page Controls</h3>
		<p>When the number of items is more than one page, you will see a page control bar as shown below.</p>

		<dl>
			<dt>Display #</dt>
			<dd>Select the number of items to show on one page.</dd>
			<dt>Start</dt>
			<dd>Click to go to the first page.</dd>
			<dt>Prev</dt>
			<dd>Click to go to the previous page.</dd>
			<dt>Page numbers</dt>
			<dd>Click to go to the desired page.</dd>
			<dt>Next</dt>
			<dd>Click to go to the next page.</dd>
			<dt>End</dt>
			<dd>Click to go to the last page.</dd>
		</dl>
	</section>
</article>