<article>
	<h1><span>Store Manager: Orders</span></h1>

	<ul class="nav">
		<li><a href="#overview">Overview</a></li>
		<li><a href="#column-headers">Column Headers</a></li>
		<li><a href="#toolbar">Toolbar</a></li>
		<li><a href="#sub-menu">Sub-menu Links</a></li>
		<li><a href="#list-filters">List Filters</a></li>
	</ul>

	<section id="overview">
		<h2><span>Overview</span></h2>

		<p>Here you will a list of orders for items in the store.</p>
	</section>
	<section id="column-headers">
		<h2><span>Column Headers</span></h2>

		<dl>
			<dt>ID</dt>
			<dd>This is a unique identification number for this item assigned automatically by the system. It is used to identify the item internally and cannot be changed. When creating a new item, this field is 0 until the entry is saved, at which point a new ID is assigned to it.</dd>

			<dt>Status</dt>
			<dd>The status of the order, indicating orders that have been processed, completed, etc.</dd>

			<dt>Ordered Item(s)</dt>
			<dd>The items ordered.</dd>

			<dt>Total</dt>
			<dd>The total cost of items in the order.</dd>

			<dt>By</dt>
			<dd>Who placed the order.</dd>

			<dt>Date</dt>
			<dd>When the order was placed.</dd>
		</dl>
	</section>
	<section id="toolbar">
		<h2><span>Toolbar</span></h2>
		<p>At the top right you will see the toolbar.</p>
		<p>The functions are:</p>
		<dl>
			<dt>Options</dt>
			<dd>Opens the Options window where settings such as default parameters or permissions can be edited.</dd>

			<dt>Help</dt>
			<dd>Opens this help screen.</dd>
		</dl>
	</section>
	<section id="sub-menu">
		<h2><span>Sub-menu Links</span></h2>
		<p>At the top left, above the filters, you will see sub-menu options. The links are:</p>
		<dl>
			<dt>Orders</dt>
			<dd>A list of orders and their status.</dd>
			<dt>Store Items</dt>
			<dd>Manage items available in the store.</dd>
		</dl>
	</section>
	<section id="list-filters">
		<h2><span>List Filters</span></h2>

		<p>Above the column headers are two select boxes for:</p>
		<ol>
			<li><strong>Filter by</strong>: options for narrowing the list of orders to make finding entries easier.</li>
			<li><strong>Sort by</strong>: options for how the list of orders is sorted.</li>
		</ol>

		<h3>Page Controls</h3>
		<p>When the number of items is more than one page, you will see a page control bar as shown below.</p>

		<dl>
			<dt>Display #</dt>
			<dd>Select the number of items to show on one page.</dd>
			<dt>Start</dt>
			<dd>Click to go to the first page.</dd>
			<dt>Prev</dt>
			<dd>Click to go to the previous page.</dd>
			<dt>Page numbers</dt>
			<dd>Click to go to the desired page.</dd>
			<dt>Next</dt>
			<dd>Click to go to the next page.</dd>
			<dt>End</dt>
			<dd>Click to go to the last page.</dd>
		</dl>
	</section>
</article>