<article>
	<h1><span>Store Manager: Order</span></h1>

	<ul class="nav">
		<li><a href="#overview">Overview</a></li>
		<li><a href="#toolbar">Toolbar</a></li>
		<li><a href="#details">Details</a></li>
	</ul>

	<section id="description">
		<h2><span>Description</span></h2>
		<p>This is where you can add a new sponsoror edit an existing Sponsor.</p>
	</section>
	<section id="toolbar">
		<h2><span>Toolbar</span></h2>
		<p>At the top right you will see the toolbar.</p>
		<p>The functions are:</p>
		<dl>
			<dt>Save &amp; Close</dt>
			<dd>Save changes and return to the listing of entries.</dd>

			<dt>Cancel</dt>
			<dd>Discard any changes made and return to the listing of entries.</dd>

			<dt>Help</dt>
			<dd>Opens this help screen.</dd>
		</dl>
	</section>
	<section id="details">
		<h2><span>Details</span></h2>

		<dl>
			<dt>Items</dt>
			<dd>A list of items ordered.</dd>

			<dt>Shipping</dt>
			<dd>Shipping information for the order.</dd>

			<dt>User Info</dt>
			<dd>Information about the user who placed the order.</dd>

			<dt>Notes</dt>
			<dd>Notes the administrator may have about this order.</dd>
		</dl>
	</section>
</article>