		<article>
			<h1><span>Knowledge Base: Articles</span></h1>

			<ul class="nav">
				<li><a href="#overview">Overview</a></li>
				<li><a href="#column-headers">Column Headers</a></li>
				<li><a href="#toolbar">Toolbar</a></li>
				<li><a href="#sub-menu">Sub-menu Links</a></li>
				<li><a href="#list-filters">List Filters</a></li>
			</ul>

			<section id="overview">
				<h2><span>Overview</span></h2>

				<p>Here you will a list of knowledge base articles.</p>
			</section>
			<section id="column-headers">
				<h2><span>Column Headers</span></h2>

				<p>Click on the column heading to sort the list by that column's value. The list will be sorted in order by that column and a sort icon will show next to the column name. Click a second time to reverse the sort to high-to-low. The sort icon will change to high-to-low.</p>

				<dl>
					<dt>Checkbox</dt>
					<dd>Check this box to select one or more items. To select all items, check the box in the column heading. After one or more boxes are checked, click a toolbar button to take an action on the selected item or items. Many toolbar actions, such as Publish and Unpublish, can work with multiple items. Others, such as Edit, only work on one item at a time. If multiple items are checked and you press Edit, the first item will be opened for editing.</dd>

					<dt>Title</dt>
					<dd>The name of the item. This entry is required. You can open the item for editing by clicking on the Title.</dd>

					<dt>Published</dt>
					<dd>(Published/Unpublished/Trashed) The published status of the item.</dd>

					<dt>Category</dt>
					<dd>The category the article can be found in.</dd>

					<dt>Votes</dt>
					<dd>The number of times an article has been up or down-voted.</dd>
				</dl>
			</section>
			<section id="toolbar">
				<h2><span>Toolbar</span></h2>
				<p>At the top right you will see the toolbar.</p>
				<p>The functions are:</p>
				<dl>
					<dt>Publish</dt>
					<dd>Makes the selected posts available to visitors to the site.</dd>

					<dt>Unpublish</dt>
					<dd>Makes the selected posts unavailable to visitors to the site.</dd>

					<dt>New</dt>
					<dd>Opens the editing screen to create a new article.</dd>

					<dt>Edit</dt>
					<dd>pens the editing screen for the selected article. If more than one article is selected (where applicable), only the first article will be opened. The editing screen can also be opened by clicking on the Title or Name of the article.</dd>

					<dt>Trash</dt>
					<dd>Permanently remove the selected lists and all associated content (wishes, etc.).</dd>

					<dt>Help</dt>
					<dd>Opens this help screen.</dd>
				</dl>
			</section>
			<section id="sub-menu">
				<h2><span>Sub-menu Links</span></h2>
				<p>At the top left, above the filters, you will see sub-menu options. These are essentially filters for blog posts, filtering by the primary scopes (or types) of blogs. The links are:</p>
				<dl>
					<dt>Categories</dt>
					<dd>List all categories.</dd>
					<dt>Articles</dt>
					<dd>List all articles.</dd>
				</dl>
			</section>
			<section id="list-filters">
				<h2><span>List Filters</span></h2>

				<dl>
					<dt>Category</dt>
					<dd>A list of all available categories. Selecting an item form the list will display only those articles assigned to that category.</dd>
				</dl>

				<h3>Page Controls</h3>
				<p>When the number of items is more than one page, you will see a page control bar as shown below.</p>

				<dl>
					<dt>Display #</dt>
					<dd>Select the number of items to show on one page.</dd>
					<dt>Start</dt>
					<dd>Click to go to the first page.</dd>
					<dt>Prev</dt>
					<dd>Click to go to the previous page.</dd>
					<dt>Page numbers</dt>
					<dd>Click to go to the desired page.</dd>
					<dt>Next</dt>
					<dd>Click to go to the next page.</dd>
					<dt>End</dt>
					<dd>Click to go to the last page.</dd>
				</dl>
			</section>
		</article>