language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm

install:
  - composer install

script:
  - vendor/bin/phpunit --configuration build/phpunit.xml && cat build/testdox.txt build/coverage.txt

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - php vendor/bin/coveralls -v
