<article>
	<h1>Clear Cache</h1>

	<ul class="nav">
		<li><a href="#overview">Overview</a></li>
		<li><a href="#description">Description</a></li>
		<li><a href="#toolbar">Toolbar</a></li>
		<li><a href="#list-filters">List Filters</a></li>
		<li><a href="#column-headers">Column Headers</a></li>
		<li><a href="#quick-tips">Quick Tips</a></li>
		<li><a href="#related-info">Related Information</a></li>
	</ul>

	<section id="overview">
		<h2><span>Overview</span></h2>
		<p>Component to clear cache files from the cache folders if enabled under the  <a href="<?php echo Route::url('index.php?option=com_help&component=com_config&page=global_config'); ?>" title="Site: Global Configuration">Site Global Configuration</a> settings.</p>
	</section>
	<section id="description">
		<h2> <span class="mw-headline" id="Description">Description</span></h2>
		<p>This tool will delete <i>all</i> Cache files from the cache folders - including current ones - from your web server. As admin functions are cached too, some cache folders might appear as if they were not cleaned because they get recreated before cache content is rescanned after this action.</p>
		<p>Cache files are temporary files that are created to improve the performance of your site. If you have made significant changes to your web site, such as changing your Template or Language, your cache files may be out of date. To avoid any problems caused by out of date cache files, you can delete all of the cache files.</p>
		<ul>
			<li>Because this process deletes <strong>all</strong> Cache files, the website may be a little slower immediately after running Clean Cache.  Once this process is complete, users lose the benefit of using the cache files until they are re-created by the CMS to be up to date with your current site.</li>
			<li>In contrast, the <a href="<?php echo Route::url('index.php?option=com_help&component=com_cache&page=purge_expired'); ?>" title="Site Maintenance: Purge Expired Cache">Purge Expired Cache</a> option will check each Cache file individually for being out of date, but the process is slower and requires more system resources.  However, the website should perform close to the same speed for users visiting your site, since all up to date files are still available for your current site.</li>
		</ul>
	</section>
	<section id="toolbar">
		<h2><span>Toolbar</span></h2>
		<p>At the top right you will see the toolbar. The functions are:</p>
		<dl>
			<dt>Delete</dt>
			<dd>Deletes the selected items. Works with one or multiple items selected.</dd>

			<dt>Options</dt>
			<dd>Opens the Options window where settings such as default parameters or permissions can be edited.</dd>

			<dt>Help</dt>
			<dd>Opens this help screen.</dd>
		</dl>
	</section>
	<section id="list-filters">
		<h2><span>List Filters</span></h2>
		<p>The drop-down list at the top right allows you to filter the list with the following options:</p>
		<dl>
			<dt>Site</dt>
			<dd>This is the default and allows you to see the cache files for the front-end of the web site.</dd>

			<dt>Administrator</dt>
			<dd>Select this option to see the cache files for the Administrator back-end of the web site.</dd>
		</dl>

		<h3>Page Controls</h3>
		<p>When the number of items is more than one page, you will see a page control bar as shown below.</p>

		<dl>
			<dt>Display #</dt>
			<dd>Select the number of items to show on one page.</dd>
			<dt>Start</dt>
			<dd>Click to go to the first page.</dd>
			<dt>Prev</dt>
			<dd>Click to go to the previous page.</dd>
			<dt>Page numbers</dt>
			<dd>Click to go to the desired page.</dd>
			<dt>Next</dt>
			<dd>Click to go to the next page.</dd>
			<dt>End</dt>
			<dd>Click to go to the last page.</dd>
		</dl>
	</section>
	<section id="column-headers">
		<h2><span>Column Headers</span></h2>
		<dl>
			<dt>#</dt>
			<dd>An indexing number automatically assigned by the CMS for ease of reference.</dd>
			<dt>Checkbox</dt>
			<dd>Check this box to select one or more items. To select all items, check the box in the column heading. After one or more boxes are checked, click a toolbar button to take an action on the selected item or items. Many toolbar actions, such as Publish and Unpublish, can work with multiple items. Others, such as Edit, only work on one item at a time. If multiple items are checked and you press Edit, the first item will be opened for editing.</dd>
			<dt>Cache Group</dt>
			<dd>The type of item being cached in this file. This is also the name of the subdirectory where this type of cache file is stored. The cache files are stored in the directory "&lt;path-to-site&gt;/app/cache/&lt;Cache Group Name&gt;".</dd>
			<dt>Number of Files</dt>
			<dd>The number of files currently in this cache group.</dd>
			<dt>Size</dt>
			<dd>The total size, in KB, of the cache files in this group.</dd>
		</dl>
	</section>
	<section id="quick-tips">
		<h2><span>Quick Tips</span></h2>
		<p>Normally you want to delete all cache files. To do this, click the check box in the column heading to select all files and then click the Delete icon in the toolbar.</p>
	</section>
	<section id="related-info">
		<h2><span>Related Information</span></h2>
		<p>To change the cache settings for your site: <a href="<?php echo Route::url('index.php?option=com_help&component=com_config&page=global_config'); ?>" title="Site: Global Configuration">Global Configuration - Cache Settings</a></p>
	</section>
</article>