<article>
	<h1><span>Language Manager: Edit Content Language</span></h1>

	<ul class="nav">
		<li><a href="#overview">Overview</a></li>
		<li><a href="#column-headers">Column Headers</a></li>
		<li><a href="#toolbar">Toolbar</a></li>
		<li><a href="#list-filters">List Filters</a></li>
	</ul>

	<section id="overview">
		<h2> <span class="mw-headline" id="Description">Description</span></h2>
		<p>In the Language Manager: Edit Content Language you can set the title, URL, image, code, and description of the installed langauges. You may also update or add meta keywords and description.</p>
		<h2> <span class="mw-headline" id="Details_.26_Options">Details &amp; Options</span></h2>
		<h3> <span class="mw-headline" id="Details">Details</span></h3>
		<ul>
		<li><b>Title.</b> The name of the language as it will appear ion the lists.</li>
		<li><b>Title Native.</b> Language title IN the native language.</li>
		<li><b>URL Language Code.</b> URL Language Code for this language. If 'en' is used then it will be added after the site URL. Example: <a rel="nofollow" class="external free" href="http://mysite.com/en">http://mysite.com/en</a>. Note: The prefix must be unique over all the languages.</li>
		<li><b>Image Prefix.</b> Name of the image file for this language when using the "Use Image Flags" Language Switcher basic option. Example: If 'en' is chosen, then the image shall be en.gif. Images and CSS for this module are in media/mod_languages/</li>
		<li><b>Language Tag.</b> Enter here the language tag - example: en-GB for English (UK). This should be the exact prefix used for the language installed or to be installed.</li>
		</ul>
		<ul>
		<li><b>Status.</b> (Published/Unpublished/Archived/Trashed) The published status of the item.</li>
		<li><b>Description.</b> Enter a description for the language</li>
		</ul>
		<ul>
		<li><b>ID</b>. This is a unique identification number for this item assigned automatically by Joomla!. It is used to identify the item internally, and you cannot change this number. When creating a new item, this field displays 0 until you save the new entry, at which point a new ID is assigned to it.</li>
		</ul>
		<h3> <span class="mw-headline" id="MetaData_Options">MetaData Options</span></h3>
		<p><a href="/proxy/index.php?option=com_help&view=help&keyref=File:Help25-Extenions-Language-Manager-metadata-Installed.png" class="image"><img alt="Help25-Extenions-Language-Manager-metadata-Installed.png" src="http://docs.joomla.org/images/2/28/Help25-Extenions-Language-Manager-metadata-Installed.png" width="521" height="237" /></a></p>
		<ul>
		<li><b>Meta Description.</b> An optional paragraph to be used as the description of the page in the HTML output. This will generally display in the results of search engines. If entered, this creates an HTML meta element with a name attribute of "description" and a content attribute equal to the entered text.</li>
		</ul>
		<ul>
		<li><b>Meta Keywords.</b> Optional entry for keywords. Must be entered separated by commas (for example, "cats, dogs, pets") and may be entered in upper or lower case. (For example, "CATS" will match "cats" or "Cats"). Keywords can be used in several ways:</li>
		</ul>
		<ol>
		<li>To help Search Engines and other systems classify the content of the Article.</li>
		<li>In combination with Banner tags, to display specific Banners based on the Article content. For example, say you have one Banner with an ad for dog products and another Banner for cat products. You can have your dog Banner display when a User is viewing a dog-related Article and your cat Banner display for a cat-related Article. To do this, you would:
		<ol>
		<li>Add the keywords 'dog' and 'cat' to the appropriate Articles.</li>
		<li>Add the Tags 'dog' and 'cat' to the appropriate Banners in the <a href="/proxy/index.php?option=com_help&view=help&keyref=Help25:Components_Banners_Banners_Edit" title="Help25:Components Banners Banners Edit">Banner Manager New/Edit</a> screen.</li>
		<li>Set the Banner module Parameter 'Search By Tags' to 'Yes in the <a href="/proxy/index.php?option=com_help&view=help&keyref=Help25:Extensions_Module_Manager_Banners" title="Help25:Extensions Module Manager Banners">Banner Module Edit</a> screen.</li>
		</ol>
		</li>
		<li>For articles only, in combination with the <a href="/proxy/index.php?option=com_help&view=help&keyref=Help25:Extensions_Module_Manager_Articles_Related" title="Help25:Extensions Module Manager Articles Related">Related Articles module</a>, to display Articles that share at least one keyword in common. For example, if the current Article displayed has the keywords "cats, dogs, monkeys", any other Articles with at least one of these keywords will show in the Related Articles module.</li>
		</ol>
		<h3> <span class="mw-headline" id="Site_Name">Site Name</span></h3>
		<p><a href="/proxy/index.php?option=com_help&view=help&keyref=File:Help25-Extenions-Language-Manager-site-name.png" class="image"><img alt="Help25-Extenions-Language-Manager-site-name.png" src="http://docs.joomla.org/images/d/d3/Help25-Extenions-Language-Manager-site-name.png" width="519" height="97" /></a></p>
		<ul>
		<li><b>Custom Site Name.</b> You can optionally override the site name set in the Global Configuration here.</li>
		</ul>
		<h2> <span class="mw-headline" id="Toolbar">Toolbar</span></h2>
		<p>At the top right you will see the toolbar:</p>
		<p><a href="/proxy/index.php?option=com_help&view=help&keyref=File:Help25-Toolbar-Save-SaveClose-SaveNew-Cancel-Help.png" class="image"><img alt="Help25-Toolbar-Save-SaveClose-SaveNew-Cancel-Help.png" src="http://docs.joomla.org/images/0/05/Help25-Toolbar-Save-SaveClose-SaveNew-Cancel-Help.png" width="325" height="65" /></a></p>
		<p>The functions are:</p>
		<ul>
		<li><b>Save</b>. Saves the content language and stays in the current screen.</li>
		<li><b>Save &amp; Close</b>. Saves the content language and closes the current screen.</li>
		<li><b>Save &amp; New</b>. Saves the content language and keeps the editing screen open and ready to create another content language.</li>
		<li><b>Cancel/Close</b>. Closes the current screen and returns to the previous screen without saving any modifications you may have made.</li>
		<li><b>Help</b>. Opens this help screen.</li>
		</ul>
		<h2> <span class="mw-headline" id="Quick_Tips">Quick Tips</span></h2>
		<ul>
		<li>Users can use any Language from the list of installed Languages, either by having it assigned in the <a href="/proxy/index.php?option=com_help&view=help&keyref=Help25:Users_User_Manager" title="Help25:Users User Manager">User Manager</a> or by filling out a <a href="/proxy/index.php?option=com_help&view=help&keyref=Help25:Menus_Menu_Item_Manager_Edit#User_Form_Layout" title="Help25:Menus Menu Item Manager Edit">Menu Item Manager - New/Edit - User Form Layout</a> at the Front end. This will cause the Joomla! system prompts to be generated in this Language just for this User. For example, if a User chooses Spanish as their language, then the Search Module will show with prompts in Spanish.</li>
		<li>This User's choice is not affected by the Default Language set for the Front-end.</li>
		</ul>
		<dl>
		<dd>
		<ul>
		<li>Changing a User's Language or the Default Language does not affect the web site's Articles and other content.</li>
		</ul>
		</dd>
		</dl>
		<ul>
		<li><b>Important</b>: Do not delete the default language files (for example, with FTP). This will create errors on both the Front-end and Back-end.</li>
		</ul>
		<ul>
		<li>Additional Languages can be added using the <a href="/proxy/index.php?option=com_help&view=help&keyref=Help25:Extensions_Extension_Manager_Install" title="Help25:Extensions Extension Manager Install">Extension Manager - Install Screen</a>.</li>
		</ul>
		<ul>
		<li>If desired, you can show the Front-end site in one Language and show the Back-end administration pages in a different Language. Also, individual articles can be configured to use a different language in the Advanced Parameter pane when editing the Article.</li>
		</ul>
		<h2> <span class="mw-headline" id="Related_Information">Related Information</span></h2>
		<ul>
		<li>To install more Languages: <a href="/proxy/index.php?option=com_help&view=help&keyref=Help25:Extensions_Extension_Manager_Install" title="Help25:Extensions Extension Manager Install">Extension Manager - Install Screen</a></li>
		<li>To uninstall a Language: <a href="/proxy/index.php?option=com_help&view=help&keyref=Help25:Extensions_Extension_Manager_Manage" title="Help25:Extensions Extension Manager Manage">Extension Manager - Manage</a></li>
		<li>To change the Language for a User: <a href="/proxy/index.php?option=com_help&view=help&keyref=Help25:Users_User_Manager_Edit" title="Help25:Users User Manager Edit">User Manager - New/Edit</a></li>
		<li>To set the Language of an Article: <a href="/proxy/index.php?option=com_help&view=help&keyref=Help25:Content_Article_Manager_Edit#Parameters_-_Advanced" title="Help25:Content Article Manager Edit">Article Manager - New/Edit - Parameters - Advanced</a></li>
		</ul>
	</section>
</article>