<article>
	<h1><span>Mass Mail</span></h1>

	<p>Send an email to registered users.
</p>
<h2> <span class="mw-headline" id="How_to_access">How to access</span></h2>
<p>Select <b>Users &#8594; Mass Mail Users</b> from the drop-down menu on the Back-end of your Joomla! installation.
</p>
<h2> <span class="mw-headline" id="Description">Description</span></h2>
<p>The Mass Mail screen allows Users who are members of the "Super Administrator" group to send an email message to registered users for the site. Users can be selected based on groups.
</p>
<h2> <span class="mw-headline" id="Screenshot">Screenshot</span></h2>
<p><a href="/proxy/index.php?option=com_help&view=help&keyref=File:Help25-users_mass_mail_users-screen.png" class="image"><img alt="Help25-users mass mail users-screen.png" src="http://docs.joomla.org/images/7/7c/Help25-users_mass_mail_users-screen.png" width="800" height="364" /></a>
</p>
<h2> <span class="mw-headline" id="Details_and_Message">Details and Message</span></h2>
<ul><li><b>Mail to Child Groups.</b> Whether or not to send the Email to members of all child groups of the selected group. For example, if this box is checked and the "Public" group is selected, the email would be sent to all users, since all groups are child groups of "Public".
</li><li><b>Send in HTML mode.</b> Whether or not to send the Email with headers that identify it as an HTML document. Email clients that support this will render any HTML codes.
</li><li><b>Send to disabled users.</b> Whether or not to send the Email to users who have had their accounts disabled.
</li><li><b>Group.</b> Select the groups you want to send the Email to.
</li><li><b> Recipients as BCC.</b> If checked, all recipients will be included as BCC entries, so none will see any of the other recipients' Email addresses. Because many mail routers treat Email without a <i>To:</i> entry as spam, the site email will be used for the <i>To:</i> entry.
</li><li><b>Subject</b> Enter the Subject of the Email. Try to make it as descriptive as possible. Any text entered in the <i>Subject Prefix</i> parameter in Options (<a href="/proxy/index.php?option=com_help&view=help&keyref=Help25:Users_Mass_Mail_Users#Mass_Mail" title="Help25:Users Mass Mail Users">User Options &#8594; Mass Mail</a>) will be placed in front of the subject you enter here.
</li><li><b>Message.</b> Enter the body of the Email. Any text entered in the <i>Mailbody Suffix</i> parameter in Options (<a href="/proxy/index.php?option=com_help&view=help&keyref=Help25:Users_Mass_Mail_Users#Mass_Mail" title="Help25:Users Mass Mail Users">User Options &#8594; Mass Mail</a>) will be added to the text you enter here.
</li></ul>
<h2> <span class="mw-headline" id="Options">Options</span></h2>
<p>Click the Options button to open the <b>User Manager Options</b> window which lets you configure this component.
</p><p><a href="/proxy/index.php?option=com_help&view=help&keyref=File:Help25-Users-User-Manager-Options-modal-window.png" class="image"><img alt="Help25-Users-User-Manager-Options-modal-window.png" src="http://docs.joomla.org/images/7/78/Help25-Users-User-Manager-Options-modal-window.png" width="650" height="415" /></a>
</p>
<h3> <span class="mw-headline" id="Buttons_Common_to_All_Tabs">Buttons Common to All Tabs</span></h3>
<ul><li><b>Save</b>. Saves the user options and stays in the current screen.
</li><li><b>Save &amp; Close</b>. Saves the user options and closes the current screen.
</li><li><b>Cancel/Close</b>. Closes the current screen and returns to the previous screen without saving any modifications you may have made.
</li></ul>
<h3> <span class="mw-headline" id="Component">Component</span></h3>
<p><a href="/proxy/index.php?option=com_help&view=help&keyref=File:Help25-Users-User-Manager-Options-Component-screen.png" class="image"><img alt="Help25-Users-User-Manager-Options-Component-screen.png" src="http://docs.joomla.org/images/5/5d/Help25-Users-User-Manager-Options-Component-screen.png" width="670" height="340" /></a>
</p>
<ul><li><b>Allow User Registration.</b> (Yes/No) If set Yes, users can register from the front end of the site using the Create an Account link provided on the Login module. If set to No, the "Create and Account" link will not show. 
</li><li><b>New User Registration Group.</b> The group that users are assigned to by default when they register on the site. Defaults to Registered.
</li><li><b>Guest User Group.</b> The group that guests are assigned to. (Guests are visitors to the site who are not logged in.) This is set to Public by default. If you change this to a different group, it is possible to create content on the site that is visible to guests but not visible to logged in users. See <a href="/proxy/index.php?option=com_help&view=help&keyref=ACL_Tutorial_for_Joomla_1.6#Allowing_Guest-Only_Access_to_Menu_Items_and_Modules" title="ACL Tutorial for Joomla 1.6" class="mw-redirect">Allowing Guest-Only Access to Menu Items and Modules</a>.
</li><li><b>Send Password.</b> If set to yes the user will be emailed their password on the registration email. Note there are potential security issues if this is set to yes.
</li><li><b>New User Account Activation.</b>
<ul><li><b>None.</b> User account will be active immediately with no action required.
</li><li><b>Self.</b> User will receive an email with an activation link. The account will be activated when the user clicks the activation link.
</li><li><b>Admin.</b> User will receive an email with an activation link. When the user clicks this link, the Site Admin will be notified via email and the Site Admin needs to activate the user's account.
</li></ul>
</li><li><b>Notification Mail to Administrators.</b> (Yes/No) Send email notification to administrators with <b>User Account Activation</b>.
</li><li><b>Captcha.</b> Use Captcha for User Account Registration and Username or User Password reminders. 
</li><li><b>Frontend User Parameters.</b> (Show/Hide) If set to Show, users will be able to modify their language, editor, and help site preferences from the front end of the site. If set to Hide, the user will not be able to change these settings.
</li><li><b>Frontend Language.</b> (Show/Hide) Show or hide the option for users to set their default site language.
</li><li><b>Change Login Name.</b> (Yes/No) Allow user to change Login Name.
</li><li><b>Maximum Reset Count.</b> (0-20) Maximum number of reset password attempts per <b>Time in Hours</b>. Zero means no limit on reset password attempts.
</li><li><b>Time in Hours.</b> (1-24) Time period in hours for the <b>Maximum Reset Count</b>.
</li></ul>
<h3> <span class="mw-headline" id="Mass_Mail">Mass Mail</span></h3>
<p><a href="/proxy/index.php?option=com_help&view=help&keyref=File:Help25-Users-User-Manager-Options-Mass-Mail-screen.png" class="image"><img alt="Help25-Users-User-Manager-Options-Mass-Mail-screen.png" src="http://docs.joomla.org/images/9/9b/Help25-Users-User-Manager-Options-Mass-Mail-screen.png" width="670" height="151" /></a>
</p>
<ul><li><b>Subject Prefix</b>. Enter optional text to be inserted automatically before the subject of the mass email.
</li><li><b>Mailbody Suffix</b>. Enter optional text to be inserted automatically after the body of the email (for example, a signature).
</li></ul>
<h3> <span class="mw-headline" id="Permissions">Permissions</span></h3>
<p>This screen allows you to set the component permissions in Joomla. This is important to consider if you have sites with many different user categories all of whom need to have different accessibilities to the component. The screenshot below describes what you should see and the text below that describes what each permission level gives the user access to:
</p><p><a href="/proxy/index.php?option=com_help&view=help&keyref=File:Help25-Users-User-Manager-Options-permissions.png" class="image"><img alt="Help25-Users-User-Manager-Options-permissions.png" src="http://docs.joomla.org/images/6/62/Help25-Users-User-Manager-Options-permissions.png" width="670" height="387" /></a>
</p><p>You work on one Group at a time by opening the slider for that group. You change the permissions in the Select New Settings drop-down list boxes.
The options for each value are Inherited, Allowed, or Denied. The Calculated Setting column shows you the setting in effect. It is either Not Allowed (the default), Allowed, or Denied.
Note that the Calculated Setting column is not updated until you press the Save button in the toolbar. To check that the settings are what you want, press the Save button and check the Calculated Settings column.
</p><p>The default values used here are the ones set in the <a href="/proxy/index.php?option=com_help&view=help&keyref=Help25:Site_Global_Configuration#Permissions" title="Help25:Site Global Configuration">Global Configuration Permissions Tab</a>
</p>
<dl><dd><dl><dt>Configure</dt><dd> Open the users component option screens (the modal window these options are in)
</dd><dt>Access Administration Interface</dt><dd> Open the users component manger screens
</dd><dt>Create&#160;</dt><dd> Create new users in the component
</dd><dt>Delete&#160;</dt><dd> Delete existing users in the component
</dd><dt>Edit&#160;</dt><dd> Edit existing users in the component
</dd><dt>Edit State&#160;</dt><dd> Change an users state (Publish, Unpublish, Archive, and Trash) in the component.
</dd></dl>
</dd></dl>
<p>There are two very important points to understand from this screen. The first is to see how the permissions can be inherited from the parent Group. The second is to see how you can control the default permissions by Group and by Action.
This provides a lot of flexibility. For example, if you wanted Shop Suppliers to be able to have the ability to create an article about their product, you could just change their Create value to "Allowed". If you wanted to not allow members of Administrator group to delete objects or change their state, you would change their permissions in these columns to Inherited (or Denied).
It is also important to understand that the ability to have child groups is completely optional. It allows you to save some time when setting up new groups. However, if you like, you can set up all groups to have Public as the parent and not inherit any permissions from a parent group.
</p>
<h2> <span class="mw-headline" id="Toolbar">Toolbar</span></h2>
<p>At the top right you will see the toolbar:
</p><p><a href="/proxy/index.php?option=com_help&view=help&keyref=File:Help25-Toolbar-SendEmail-Cancel-Options-Help.png" class="image"><img alt="Help25-Toolbar-SendEmail-Cancel-Options-Help.png" src="http://docs.joomla.org/images/6/69/Help25-Toolbar-SendEmail-Cancel-Options-Help.png" width="247" height="65" /></a>
</p><p>The functions are:
</p>
<ul><li><b>Send Mail</b>. Send the email and return to the main Mass Mail screen
</li><li><b>Cancel/Close</b>. Closes the current screen and returns to the previous screen without saving any modifications you may have made.
</li><li><b>Options</b>. Opens the Options window where settings such as default parameters or permissions can be edited.
</li><li><b>Help</b>. Opens this help screen.
</li></ul>
<h2> <span class="mw-headline" id="Related_Information">Related Information</span></h2>
<ul><li> <a href="/proxy/index.php?option=com_help&view=help&keyref=Help25:Users_Mass_Mail_Users#Options" title="Help25:Users Mass Mail Users">Users Configuration</a>
</li><li> <a href="/proxy/index.php?option=com_help&view=help&keyref=Help25:Menus_Menu_Item_User_Registration" title="Help25:Menus Menu Item User Registration">Front End User Registration</a>
</li><li> <a href="/proxy/index.php?option=com_help&view=help&keyref=Help25:Components_Messaging_Write" title="Help25:Components Messaging Write">Write Private Message</a>
</li></ul>
</article>