<article>
	<h1><span>User Manager: Edit User</span></h1>

	<p>Allows an administrator to create a new user.
</p>
<h2> <span class="mw-headline" id="How_to_access">How to access</span></h2>
<p>To edit an existing user, navigate to the User Manager (<b>Users &#8594; User Manager</b>). Then
</p>
<ul><li> Click on the name of the user or
</li><li> Click on the check box for the user and click on the edit button.
</li></ul>
<p>To create a new user,
</p>
<ul><li> Select <b>Users &#8594; User Manager &#8594; Add New User</b> from the menu or
</li><li> Click on the <b>New</b> button in the User Manager.
</li></ul>
<h2> <span class="mw-headline" id="Description">Description</span></h2>
<p>In this screen, you have the ability to create a new user (if you clicked on the 'New' button in the User Manager), or edit an existing user (if you selected a user and clicked on the 'Edit' button in the User Manager, or clicked on the name of a user).
</p>

<h2> <span class="mw-headline" id="User_Fields"> User Fields </span></h2>
<p><b>Account Details</b>
</p>
<ul><li> <b>Name</b>. The (full) name of the user.
</li><li><b>Login Name</b>. The user name that will be entered during login.
</li><li><b>Password</b>. The password that will be entered during login.
</li><li><b>Confirm Password</b>. The same password again (to make sure the password is entered correctly).
</li><li><b>Email</b>. Email address for this user.
</li><li><b>Registration Date</b>. The date this user was registered.
</li><li><b>Last Visit Date</b>. The date this user last logged into the site.
</li></ul>
<ul><li> <b>Receive System E-mails</b>. Here you can select whether to let this user receive the system e-mails or not. Only available when editing Administrators or Super Administrators.
</li></ul>
<ul><li> <b>Block User</b>. Here you can select whether to disable this user or not. Only available when editing Administrators or Super Administrators.
</li></ul>
<ul><li><b>ID</b>. This is a unique identification number for this item assigned automatically by Joomla!. It is used to identify the item internally, and you cannot change this number. When creating a new item, this field displays 0 until you save the new entry, at which point a new ID is assigned to it.
</li></ul>
<p><b>Assigned User Groups</b>
</p>
<ul><li><b>Assigned User Groups</b>. Check the box next to each User Group that this user will be a member of. The groups that a user belongs to detemine what actions the user can do on the site and what objects the user can view on the site.
</li></ul>
<p><b>Basic Settings</b>
</p>
<ul><li><b>Backend Template Style</b>. The template style to use for this user in the administrative backend.
</li></ul>
<ul><li> <b>Back-end Language</b>. Here you can select the back-end language of the user. All installed languages for the back-end will be displayed in the drop-down box. Default is the language set in Language Manager.
</li></ul>
<ul><li> <b>Front-end Language</b>. Here you can select the front-end language of the user. All installed languages for the front-end will be displayed in the drop-down box. Default is the language set in Language Manager.
</li><li><b>Editor</b>. The editor to use for this user.
</li></ul>
<ul><li> <b>Help Site</b>. Set the help site of the user. Default is the Help Server set in the Global Configuration.
</li></ul>
<ul><li> <b>Time Zone</b>. Set the time zone of the user. Default is the Time Zone set in the Global Configuration.
</li></ul>
<h2> <span class="mw-headline" id="Toolbar"> Toolbar</span></h2>
<p>At the top right you will see the toolbar:
</p><p>The functions are:
</p>
<ul><li><b>Save</b>. Saves the user and stays in the current screen.
</li><li><b>Save &amp; Close</b>. Saves the user and closes the current screen.
</li><li><b>Save &amp; New</b>. Saves the user and keeps the editing screen open and ready to create another user.
</li><li><b>Cancel/Close</b>. Closes the current screen and returns to the previous screen without saving any modifications you may have made.
</li><li><b>Help</b>. Opens this help screen.
</li></ul>
<h2> <span class="mw-headline" id="Quick_tips">Quick tips</span></h2>
<ul><li>Name, Login Name, and Email are required.
</li><li>If you did not fill in a particular language, editor, help site and/or time zone, the default settings from the Global Configuration, Language Manager and/or Template Manager are set.
</li></ul>
<h2> <span class="mw-headline" id="Related_information">Related information</span></h2>
<ul>
	<li><a href="<?php echo Route::url('index.php?option=com_help&view=help&keyref=Help25:Users_User_Manager'); ?>" title="Help25:Users User Manager">User Manager: Users</a></li>
	<li><a href="<?php echo Route::url('index.php?option=com_help&view=help&keyref=Help25:Users_Groups'); ?>" title="Help25:Users Groups">User Manager: Users Groups</a></li>
	<li><a href="<?php echo Route::url('index.php?option=com_help&view=help&keyref=Access_Control_List/1.6-2.5/Tutorial'); ?>" title="Access Control List/1.6-2.5/Tutorial" class="mw-redirect">ACL Tutorial for Joomla 1.6, 1.7 and 2.5</a></li>
</ul>
</article>