<?php
/**
 * HUBzero CMS
 *
 * Copyright 2005-2011 Purdue University. All rights reserved.
 *
 * This file is part of: The HUBzero(R) Platform for Scientific Collaboration
 *
 * The HUBzero(R) Platform for Scientific Collaboration (HUBzero) is free
 * software: you can redistribute it and/or modify it under the terms of
 * the GNU Lesser General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any
 * later version.
 *
 * HUBzero is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * HUBzero is a registered trademark of Purdue University.
 *
 * @package   hubzero-cms
 * @author    Christopher Smoak <csmoak@purdue.edu>
 * @copyright Copyright 2005-2011 Purdue University. All rights reserved.
 * @license   http://www.gnu.org/licenses/lgpl-3.0.html LGPLv3
 */

// Check to ensure this file is included in Joomla!
defined('_JEXEC') or die('Restricted access');
?>

<h1>Resources Help</h1>
<p>Think of a hub as an empty library. Resources are items on the shelves. Unlike a traditional library, resources not only be publications, but also videos, tools, animations, and other types. Anyone can upload resources, although some hubs require moderation and approval before a resource is posted.</p>
<ul>
	<li>
		<a href="<?php echo JRoute::_('index.php?option=com_help&component=resources&page=faqs'); ?>">FAQ's</a>
	</li>
	<li>
		<a href="<?php echo JRoute::_('index.php?option=com_help&component=resources&page=rating'); ?>">Rating a Resource</a>
	</li>
	<li>
		<a href="<?php echo JRoute::_('index.php?option=com_help&component=resources&page=video'); ?>">How to View/Download Video Content?</a>
	</li>
</ul>