<article>
	<h1><span>User Manager: Edit Group</span></h1>

	<h2> <span class="mw-headline" id="How_to_access">How to access</span></h2>
<p>To edit an existing user group, navigate to the User Groups tab of the User Manager (<b>Users &#8594; User Manager &#8594; User Groups</b>). Then
</p>
<ol><li> click on the name of the group or
</li><li> click on the check box for the group and click on the Edit button.
</li></ol>
<p>To create a new user group,
</p>
<ol><li> select <b>Users &#8594; Groups &#8594; Add New Group</b> from the menu or
</li><li> click on the New button in the User Manager: User Groups screen.
</li></ol>
<h2> <span class="mw-headline" id="Description">Description</span></h2>
<p>User groups play a central role in what a user can do and see on the site. Creating user groups is normally the first step in setting up the security system for your site.
</p><p>User Groups control what actions a user can take on the site. Actions include things like creating a new article, changing options for a component, or logging in. The site administrator assigns permissions for various actions to each group. Permissions for actions can be assigned at different levels in the component hierarchy (Global Configuration, component options, categories, and articles). If a user does not have permission for a given action, the user cannot perform that action.
</p><p>User groups also control which objects a user can view on the site. Objects include categories, articles, modules, menu items, and others. When you create an access level, one or more user groups are assigned to it. Then, when you create an object (such as a menu item or module), the object is assigned an access level. If a user is a member of a group that is assigned to an access level, this user can view any object assigned to that access level. If not, then that user cannot view that object.
</p><p>User groups can be arranged in a hierarchy. If so, then all child groups inherit the action permissions and access levels of a parent group. If used wisely, this feature can save a lot of time setting up your security system, since it means that you don't have to enter duplicate setup information.
</p><p>In this screen, you can create a new user group or edit an existing user group.
</p>
<h2> <span class="mw-headline" id="Screenshot"> Screenshot </span></h2>
<p><a href="/proxy/index.php?option=com_help&view=help&keyref=File:Help25-users_groups_edit-screen.png" class="image"><img alt="Help25-users groups edit-screen.png" src="http://docs.joomla.org/images/9/9b/Help25-users_groups_edit-screen.png" width="800" height="214" /></a>
</p>
<h2> <span class="mw-headline" id="User_Group_Details"> User Group Details </span></h2>
<ul><li><b>Group Title</b>. The name of the group.
</li><li><b>Group Parent</b>. The parent group of this group. Note that each group inherits the permissions from its parent group. If you do not want this group to inherit any permissions, make its parent group "Public". See <a href="/proxy/index.php?option=com_help&view=help&keyref=Access_Control_List/1.6-2.5/Tutorial" title="Access Control List/1.6-2.5/Tutorial" class="mw-redirect">ACL Tutorial for Joomla 1.6, 1.7 and 2.5</a> for more information.
</li></ul>
<h2> <span class="mw-headline" id="Toolbar"> Toolbar</span></h2>
<p>At the top right you will see the toolbar:
</p><p><a href="/proxy/index.php?option=com_help&view=help&keyref=File:Help25-Toolbar-Save-SaveClose-SaveNew-SaveCopy-Close-Help.png" class="image"><img alt="Help25-Toolbar-Save-SaveClose-SaveNew-SaveCopy-Close-Help.png" src="http://docs.joomla.org/images/0/08/Help25-Toolbar-Save-SaveClose-SaveNew-SaveCopy-Close-Help.png" width="414" height="65" /></a>
</p><p>The functions are:
</p>
<ul><li><b>Save</b>. Saves the user group and stays in the current screen.
</li><li><b>Save &amp; Close</b>. Saves the user group and closes the current screen.
</li><li><b>Save &amp; New</b>. Saves the user group and keeps the editing screen open and ready to create another user group.
</li><li><b>Save as Copy</b>. Saves your changes to a copy of the current user group.  Does not affect the current user group.  This toolbar icon is not shown if you are creating a new user group.
</li><li><b>Cancel/Close</b>. Closes the current screen and returns to the previous screen without saving any modifications you may have made.
</li><li><b>Help</b>. Opens this help screen.
</li></ul>
<h2> <span class="mw-headline" id="Quick_tips">Quick tips</span></h2>
<ul><li>If a new group will have similar permissions to an existing group, you can save work by making the new group a child of the existing group. That way, you only need to change the permissions that are different for the new group.
</li></ul>
<h2> <span class="mw-headline" id="Related_information">Related information</span></h2>
<ul><li> <a href="/proxy/index.php?option=com_help&view=help&keyref=Help25:Users_Groups" title="Help25:Users Groups">User Manager: Users Groups</a>
</li><li> <a href="/proxy/index.php?option=com_help&view=help&keyref=Access_Control_List/1.6-2.5/Tutorial" title="Access Control List/1.6-2.5/Tutorial" class="mw-redirect">ACL Tutorial for Joomla 1.6, 1.7 and 2.5</a>
</li></ul>
</article>