<article>
	<h1><span>User Manager: Edit Viewing Access Level</span></h1>

	<h2> <span class="mw-headline" id="How_to_access">How to access</span></h2>
<p>To edit an existing access level, navigate to the Viewing Access Levels tab of the  User Manager (<b>Users &#8594; User Manager &#8594; Viewing Access Levels</b>).  Then
</p>
<ol><li> click on the desired Level Name or
</li><li> click on the check box for the access level and click on the Edit button.
</li></ol>
<p>To create a new access level,
</p>
<ol><li> select <b>Users &#8594; Access Levels &#8594; Add New Access Level</b> from the menu or
</li><li> click on the New button in the User Manager: Viewing Access Levels screen.
</li></ol>
<h2> <span class="mw-headline" id="Description">Description</span></h2>
<p>Access levels control which users can view which objects on your site. Objects include menu items, modules, categories, and component items (articles, contacts, and so on). Each object in the site is assigned to one access level. User groups are also assigned to each access level.
</p><p>If a user is a member of a group that in turn has permission for an access level, then that user can view all objects assigned to that access level. It is important to understand that user groups can be arranged in a parent-child hierarchy. If so, then a child group has access to all access levels that the parent group has access to. So you don't need to assign a child group access to levels that its parent group already has access to.
</p>
<h2> <span class="mw-headline" id="Access_Levels_Details"> Access Levels Details </span></h2>
<ul><li><b>Level Title</b>. The name of this access level.
</li><li><b>User Groups Having Viewing Access</b>. All user groups defined for the site will display, with a check box for each. Check the boxes for all groups that will have access to this level. Remember that you don't have to check child groups if a parent group has access. The child will inherit the access from the parent.
</li></ul>
<h2> <span class="mw-headline" id="Toolbar"> Toolbar</span></h2>
<p>At the top right you will see the toolbar. The functions are:</p>
<ul><li><b>Save</b>. Saves the access level and stays in the current screen.
</li><li><b>Save &amp; Close</b>. Saves the access level and closes the current screen.
</li><li><b>Save &amp; New</b>. Saves the access level and keeps the editing screen open and ready to create another access level.
</li><li><b>Cancel/Close</b>. Closes the current screen and returns to the previous screen without saving any modifications you may have made.
</li><li><b>Help</b>. Opens this help screen.
</li></ul>
<h2> <span class="mw-headline" id="Quick_tips">Quick tips</span></h2>
<ul><li>If you add a new group, you may need to edit any access levels that this group should have access to.
</li></ul>
<h2> <span class="mw-headline" id="Related_information">Related information</span></h2>
<ul><li> <a href="<?php echo Route::url('index.php?option=com_help&view=help&keyref=Help25:Users_Access_Levels'); ?>" title="Help25:Users Access Levels">User Manager: Viewing Access Levels</a>
</li><li> <a href="<?php echo Route::url('index.php?option=com_help&view=help&keyref=Help25:Users_Groups'); ?>" title="Help25:Users Groups">User Manager: User Groups</a>
</li><li> <a href="<?php echo Route::url('index.php?option=com_help&view=help&keyref=Access_Control_List_Tutorial'); ?>" title="Access Control List Tutorial" class="mw-redirect">ACL Tutorial</a>
</li></ul>
</article>